use std::io::{self,Cursor,Read,Write};
use std::collections::BTreeMap;
use serde::Deserialize;
use serde_json::{json,Value};
use zeroize::{Zeroize,Zeroizing};
use msoffice_crypto::{classify,Family};
const LIMIT:usize=64*1024*1024;
#[derive(Deserialize)]
struct Request{mode:String,name:String,size:usize,password:String}
impl Drop for Request{fn drop(&mut self){self.password.zeroize();}}
fn u16_at(b:&[u8],n:usize)->Option<u16>{Some(u16::from_le_bytes(b.get(n..n+2)?.try_into().ok()?))}
fn u32_at(b:&[u8],n:usize)->Option<u32>{Some(u32::from_le_bytes(b.get(n..n+4)?.try_into().ok()?))}
fn text(bytes:&[u8],wide:bool,cp:u16)->String{
 let value=if wide||cp==1200{String::from_utf16_lossy(&bytes.chunks_exact(2).map(|c|u16::from_le_bytes([c[0],c[1]])).collect::<Vec<_>>())}else{let label=match cp{936=>"gbk".into(),932=>"shift_jis".into(),949=>"euc-kr".into(),950=>"big5".into(),65001=>"utf-8".into(),_=>format!("windows-{cp}")};encoding_rs::Encoding::for_label(label.as_bytes()).unwrap_or(encoding_rs::WINDOWS_1252).decode(bytes).0.into_owned()};
 value.trim_end_matches('\0').chars().filter(|c|!c.is_control()||*c=='\n'||*c=='\t').take(2048).collect()
}
fn property(data:&[u8],offset:usize,cp:u16)->Option<Value>{match u32_at(data,offset)?{
 2=>Some(json!(u16_at(data,offset+4)?)),3=>Some(json!(u32_at(data,offset+4)?)),
 kind@30|kind@31=>{let count=u32_at(data,offset+4)?as usize;let size=count.checked_mul(if kind==31{2}else{1})?;if size>8192{return None;}Some(json!(text(data.get(offset+8..offset+8+size)?,kind==31,cp)))},
 64=>{let n=u64::from_le_bytes(data.get(offset+4..offset+12)?.try_into().ok()?)/10000;if n<11644473600000{return None;}Some(json!(n-11644473600000))},_=>None}}
fn properties(data:&[u8],document:bool,fields:&mut BTreeMap<String,Value>)->Result<(),&'static str>{
 if data.len()<48||u16_at(data,0)!=Some(0xfffe){return Err("DOCUMENT_INVALID");}let sections=u32_at(data,24).ok_or("DOCUMENT_INVALID")?as usize;if !(1..=8).contains(&sections)||28+sections*20>data.len(){return Err("DOCUMENT_INVALID");}
 for index in 0..sections{let offset=u32_at(data,44+index*20).ok_or("DOCUMENT_INVALID")?as usize;let length=u32_at(data,offset).ok_or("DOCUMENT_INVALID")?as usize;let section=data.get(offset..offset.checked_add(length).ok_or("DOCUMENT_INVALID")?).ok_or("DOCUMENT_INVALID")?;let count=u32_at(section,4).ok_or("DOCUMENT_INVALID")?as usize;if count>1024||8+count*8>section.len(){return Err("DOCUMENT_INVALID");}let mut entries=BTreeMap::new();
 for i in 0..count{let id=u32_at(section,8+i*8).ok_or("DOCUMENT_INVALID")?;let at=u32_at(section,12+i*8).ok_or("DOCUMENT_INVALID")?as usize;if at<8+count*8||at>=section.len()||entries.insert(id,at).is_some(){return Err("DOCUMENT_INVALID");}}
 let cp=entries.get(&1).and_then(|at|u16_at(section,at+4)).unwrap_or(1252);if index>0{continue;}let names:&[(u32,&str)]=if document{&[(2,"category"),(7,"slides"),(15,"company")]}else{&[(2,"title"),(3,"subject"),(4,"author"),(5,"keywords"),(6,"description"),(8,"lastAuthor"),(9,"revision"),(12,"created"),(13,"modified"),(14,"declaredPages"),(15,"words"),(18,"application")]};for(id,name)in names{if let Some(value)=entries.get(id).and_then(|at|property(section,*at,cp)){fields.insert((*name).into(),value);}}}Ok(())
}
fn stream(comp:&mut cfb::CompoundFile<Cursor<&[u8]>>,name:&str,limit:usize)->Result<Option<Vec<u8>>,&'static str>{if !comp.is_stream(name){return Ok(None);}let mut input=comp.open_stream(name).map_err(|_|"DOCUMENT_INVALID")?;let mut data=Vec::new();input.by_ref().take((limit+1)as u64).read_to_end(&mut data).map_err(|_|"DOCUMENT_INVALID")?;if data.len()>limit{return Err("DOCUMENT_LIMIT");}Ok(Some(data))}
fn legacy(data:&[u8],name:&str,encryption:&str)->Result<Vec<u8>,&'static str>{
 let mut comp=cfb::CompoundFile::open(Cursor::new(data)).map_err(|_|"DOCUMENT_INVALID")?;if comp.walk().take(20001).count()>20000{return Err("DOCUMENT_LIMIT");}let ext=name.rsplit('.').next().unwrap_or("").to_ascii_lowercase();let valid=match ext.as_str(){"doc"=>comp.is_stream("/WordDocument"),"xls"=>comp.is_stream("/Workbook")||comp.is_stream("/Book"),"ppt"=>comp.is_stream("/PowerPoint Document"),_=>false};if !valid{return Err("DOCUMENT_INVALID");}
 let mut fields:BTreeMap<String,Value>=BTreeMap::new();fields.insert("format".into(),json!(ext.to_uppercase()));fields.insert("encryption".into(),json!(encryption));if let Some(bytes)=stream(&mut comp,"/\u{5}SummaryInformation",4*1024*1024)?{properties(&bytes,false,&mut fields)?;}if let Some(bytes)=stream(&mut comp,"/\u{5}DocumentSummaryInformation",4*1024*1024)?{properties(&bytes,true,&mut fields)?;}
 if ext=="xls"{let key=if comp.is_stream("/Workbook"){"/Workbook"}else{"/Book"};if let Some(bytes)=stream(&mut comp,key,LIMIT)?{let mut at=0;let mut sheets=0;while at+4<=bytes.len(){let id=u16_at(&bytes,at).ok_or("DOCUMENT_INVALID")?;let size=u16_at(&bytes,at+2).ok_or("DOCUMENT_INVALID")?as usize;if at+4+size>bytes.len(){return Err("DOCUMENT_INVALID");}if id==0x85{sheets+=1;}at+=4+size;}if sheets>0{fields.insert("sheets".into(),json!(sheets));}}}serde_json::to_vec(&fields).map_err(|_|"DOCUMENT_INVALID")
}
fn pdf(data:&[u8],password:&str)->Result<Vec<u8>,&'static str>{
 let mut options=lopdf::LoadOptions::with_password(password);options.max_decompressed_size=Some(16*1024*1024);let doc=lopdf::Document::load_mem_with_options(data,options).map_err(|e|if matches!(e,lopdf::Error::Decryption(_)){if password.is_empty(){"PASSWORD_REQUIRED"}else{"BAD_PASSWORD"}}else{"DOCUMENT_INVALID"})?;if doc.is_encrypted(){return Err(if password.is_empty(){"PASSWORD_REQUIRED"}else{"BAD_PASSWORD"});}if doc.objects.len()>200000{return Err("DOCUMENT_LIMIT");}
 let mut fields:BTreeMap<String,Value>=BTreeMap::new();fields.insert("format".into(),json!("PDF"));fields.insert("pages".into(),json!(doc.get_pages().len()));fields.insert("encryption".into(),json!(if doc.was_encrypted(){"PDF password"}else{"None"}));
 if let Ok((_,info))=doc.trailer.get(b"Info").and_then(|o|doc.dereference(o)).and_then(|(id,o)|o.as_dict().map(|d|(id,d))){for(name,key)in[(b"Title".as_slice(),"title"),(b"Author","author"),(b"Subject","subject"),(b"Keywords","keywords"),(b"Creator","creator"),(b"Producer","producer"),(b"CreationDate","created"),(b"ModDate","modified")]{if let Ok(raw)=info.get(name).and_then(|o|o.as_str()){let value=if raw.starts_with(&[0xfe,0xff]){String::from_utf16_lossy(&raw[2..].chunks_exact(2).map(|c|u16::from_be_bytes([c[0],c[1]])).collect::<Vec<_>>())}else{lopdf::decode_text_string(info.get(name).unwrap()).unwrap_or_else(|_|text(raw,false,1252))};fields.insert(key.into(),json!(value.chars().take(2048).collect::<String>()));}}}serde_json::to_vec(&fields).map_err(|_|"DOCUMENT_INVALID")
}
fn office(data:&[u8],request:&Request)->Result<(u8,Vec<u8>),&'static str>{
 let class=classify(data);if class.password_key.as_ref().and_then(|p|p.spin_count).unwrap_or(0)>1_000_000{return Err("DOCUMENT_LIMIT");}if class.is_encrypted()&&!class.is_supported(){return Err("DOCUMENT_UNSUPPORTED");}
 if matches!(class.family,Family::Agile|Family::Standard){let mut container=cfb::CompoundFile::open(Cursor::new(data)).map_err(|_|"DOCUMENT_INVALID")?;let mut package=container.open_stream("/EncryptedPackage").map_err(|_|"DOCUMENT_INVALID")?;let mut length=[0u8;8];package.read_exact(&mut length).map_err(|_|"DOCUMENT_INVALID")?;if u64::from_le_bytes(length)>LIMIT as u64{return Err("DOCUMENT_LIMIT");}let result=msoffice_crypto::decrypt_ooxml(data,&request.password).map_err(|e|match e{msoffice_crypto::Error::WrongPassword=>if request.password.is_empty(){"PASSWORD_REQUIRED"}else{"BAD_PASSWORD"},_=>"DOCUMENT_INVALID"})?;if result.len()>LIMIT{return Err("DOCUMENT_LIMIT");}return Ok((2,result));}
 if class.is_encrypted(){let plain=Zeroizing::new(msoffice_crypto::decrypt_binary_office(data,&request.password).map_err(|e|match e{msoffice_crypto::Error::WrongPassword=>if request.password.is_empty(){"PASSWORD_REQUIRED"}else{"BAD_PASSWORD"},_=>"DOCUMENT_INVALID"})?);Ok((1,legacy(&plain,&request.name,&format!("{:?}",class.family))?))}else{Ok((1,legacy(data,&request.name,"None")?))}
}
fn run()->Result<(u8,Vec<u8>),&'static str>{let mut input=io::stdin().lock();let mut size=[0u8;4];input.read_exact(&mut size).map_err(|_|"DOCUMENT_INVALID")?;let count=u32::from_le_bytes(size)as usize;if count>8192{return Err("DOCUMENT_LIMIT");}let mut header=Zeroizing::new(vec![0u8;count]);input.read_exact(&mut header).map_err(|_|"DOCUMENT_INVALID")?;let request:Request=serde_json::from_slice(&header).map_err(|_|"DOCUMENT_INVALID")?;if request.size==0||request.size>LIMIT||request.password.len()>2048||request.name.len()>1024{return Err("DOCUMENT_LIMIT");}let mut data=Zeroizing::new(vec![0u8;request.size]);input.read_exact(&mut data).map_err(|_|"DOCUMENT_INVALID")?;let mut extra=[0u8;1];if input.read(&mut extra).map_err(|_|"DOCUMENT_INVALID")?!=0{return Err("DOCUMENT_INVALID");}match request.mode.as_str(){"pdf"=>Ok((1,pdf(&data,&request.password)?)),"office"=>office(&data,&request),_=>Err("DOCUMENT_UNSUPPORTED")}}
fn main(){let(kind,mut data)=match run(){Ok(v)=>v,Err(code)=>(0,code.as_bytes().to_vec())};let mut output=io::stdout().lock();let _=output.write_all(&[kind]);let _=output.write_all(&data);let _=output.flush();data.zeroize();}
