const {chromium}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {setup}=require('./renderer-fixture.cjs'),{setupText}=require('./language-text-fixture.cjs'),{setupData}=require('./language-data-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
const build=require('esbuild').build;
(async()=>{
 await fs.mkdir('work/actions-034',{recursive:true});
 const compiled=await build({stdin:{contents:"import {ActionScope,actionFeedback} from './src/renderer/actions';import {canvasPng} from './src/renderer/image-encode';Object.assign(window,{ActionScope,actionFeedback,canvasPng});",resolveDir:process.cwd()},bundle:true,write:false,outfile:'fixture.js',platform:'browser'});
 const css=await fs.readFile('src/renderer/actions.css','utf8'),referenceCSS=await fs.readFile('D:/Repositories/One/src/renderer/system-information.css','utf8'),svg=decodeURIComponent(css.match(/data:image\/svg\+xml,([^']+)/)[1]),referenceIcon=require('node:module').createRequire('D:/Repositories/One/package.json')('lucide').RotateCw;for(const [tag,attributes]of referenceIcon)assert(svg.includes('<'+tag+' d=\"'+attributes.d+'\"'));assert.equal((svg.match(/<path /g)||[]).length,referenceIcon.length);assert(referenceCSS.includes('animation:information-spin 1.4s linear infinite'));
 const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],results=[],encoding=[];
 const checked=(name,value)=>{assert(Object.values(value).every(v=>v===true),name+' '+JSON.stringify(value));results.push({name,...value});};
 try{
  for(const theme of ['light','dark'])for(const reducedMotion of ['no-preference','reduce']){
   const context=await browser.newContext({viewport:{width:1000,height:700},reducedMotion}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
   await page.setContent(`<html data-theme="${theme}"><head><style>${await fs.readFile('D:/Repositories/One/src/renderer/styles.css','utf8')}${compiled.outputFiles.find(f=>f.path.endsWith('.css')).text}</style></head><body><button id="run" class="primary" aria-busy="false"><span>保存副本</span></button><button id="other">Other</button><div id="replacement"></div></body></html>`);
   await page.addScriptTag({content:compiled.outputFiles.find(f=>f.path.endsWith('.js')).text});
   await page.evaluate(()=>{window.scope=new ActionScope();window.calls=0;window.errors=[];const b=document.getElementById('run');window.size=b.getBoundingClientRect().toJSON();scope.bind(b,()=>{calls++;return new Promise((resolve,reject)=>{window.release=resolve;window.fail=reject;});},e=>errors.push(String(e)),'save');});
   await page.locator('#run').click();await page.evaluate(()=>{document.getElementById('run').dispatchEvent(new Event('click'));void scope.run('save',()=>calls++);});await page.waitForSelector('#run.action-pending');
   checked('pending '+theme+' '+reducedMotion,await page.locator('#run').evaluate(b=>{const r=b.getBoundingClientRect(),s=getComputedStyle(b),p=getComputedStyle(b,'::after');return {once:calls===1,busy:b.getAttribute('aria-busy')==='true',disabled:b.disabled,width:r.width===size.width,height:r.height===size.height,border:s.borderTopWidth==='1px',labelCleared:s.color==='rgba(0, 0, 0, 0)',glyph:p.maskImage!=='none',motion:matchMedia('(prefers-reduced-motion:reduce)').matches?p.animationName==='none':p.animationName==='one-action-spin'};}));
   assert.equal(await page.locator('#run').getAttribute('aria-label'),null);assert.equal(await page.locator('#run').textContent(),'保存副本');assert.equal(await page.getByRole('button',{name:'保存副本'}).count(),1);
   await page.evaluate(()=>{const old=document.getElementById('run'),fresh=old.cloneNode(true);window.removedButton=old;fresh.id='fresh';fresh.disabled=false;fresh.removeAttribute('aria-busy');fresh.classList.remove('action-pending');old.remove();document.getElementById('replacement').append(fresh);scope.bind(fresh,()=>{calls++;return Promise.resolve();},e=>errors.push(String(e)),'save');scope.bind(document.getElementById('other'),()=>{window.otherRan=true;},e=>errors.push(String(e)),'other');});
   await page.locator('#other').click();checked('rerender '+theme+' '+reducedMotion,await page.evaluate(()=>({joined:document.getElementById('fresh').disabled,independent:otherRan===true,once:calls===1})));
   await page.evaluate(()=>fail(new Error('Fixture failure')));await page.waitForFunction(()=>!document.getElementById('fresh').disabled);
   checked('failure recovery '+theme+' '+reducedMotion,await page.evaluate(()=>({errorOnce:errors.length===1,cleared:!document.getElementById('fresh').classList.contains('action-pending'),restored:!document.getElementById('fresh').hasAttribute('aria-busy')})));
   await page.locator('#fresh').click();await page.evaluate(()=>removedButton.dispatchEvent(new Event('click')));assert.equal(await page.evaluate(()=>calls),2);
   checked('fast synchronous '+theme+' '+reducedMotion,await page.evaluate(async()=>{const b=document.getElementById('fresh');await scope.run('fast',()=>42,[b]);await new Promise(r=>setTimeout(r,175));return {noFlash:!b.classList.contains('action-pending'),restored:!b.disabled&&!b.hasAttribute('aria-busy')};}));
   checked('nested leases '+theme+' '+reducedMotion,await page.evaluate(async()=>{const b=document.getElementById('fresh'),a=new ActionScope(),c=new ActionScope();let endA,endC;const pa=a.run('a',()=>new Promise(r=>endA=r),[b]),pc=c.run('c',()=>new Promise(r=>endC=r),[b]);endA();await pa;const held=b.disabled&&b.getAttribute('aria-busy')==='true';endC();await pc;return {held,restored:!b.disabled&&!b.hasAttribute('aria-busy')};}));
   checked('focus recovery '+theme+' '+reducedMotion,await page.evaluate(async()=>{const b=document.getElementById('fresh'),other=document.getElementById('other');b.focus();await scope.run('focus',()=>Promise.resolve(),[b]);const restored=document.activeElement===b;b.focus();await scope.run('focus-other',()=>{other.focus();return Promise.resolve();},[b]);return {restored,preserved:document.activeElement===other};}));
   checked('initial state '+theme+' '+reducedMotion,await page.evaluate(async()=>{const b=document.getElementById('fresh');b.disabled=true;b.setAttribute('aria-busy','false');await scope.run('keep',()=>Promise.resolve(),[b]);const retained=b.disabled&&b.getAttribute('aria-busy')==='false';b.disabled=false;const end=actionFeedback(b);end();end();return {retained,idempotent:b.getAttribute('aria-busy')==='false'};}));
   await context.close();
  }
  // Execute the built main UI and real event handlers against isolated IPC.
  const context=await browser.newContext({viewport:{width:1240,height:800}});for(const fn of [setup,extra,setupText,setupData])await context.addInitScript(fn,'zh-CN');
  await context.addInitScript(()=>{const base=clip;window.test={copies:[],remember:0,failNext:false};window.clip=new Proxy({settings:value=>{test.settings=(test.settings||0)+1;return new Promise(resolve=>test.settingsDone=()=>{fixture.state.settings=value;resolve();});},search:async()=>fixture.state.clips.map(c=>c.id),rememberSearch:()=>{test.remember++;return new Promise(resolve=>test.rememberDone=resolve);},copy:(...args)=>{test.copies.push(args);return new Promise((resolve,reject)=>{test.copyDone=resolve;test.copyFail=reject;});}},{get:(o,k)=>k in o?o[k]:base[k]});});
  await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');
  await page.locator('#search').fill('fixture');await page.waitForTimeout(160);await page.locator('#results').focus();await page.evaluate(()=>{test.rememberDone();test.remember=0;});await page.locator('#copy').click();await page.waitForFunction(()=>test.remember===1);
  await page.evaluate(()=>{document.getElementById('copy').dispatchEvent(new Event('click'));document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,bubbles:true}));});
  await page.locator('.clip-row[data-id=image]').click();await page.waitForSelector('#ai-image',{state:'attached'});checked('main pending rerender',await page.evaluate(()=>({blocked:document.getElementById('copy').disabled&&document.getElementById('paste').disabled,rememberOnce:test.remember===1})));
  await page.evaluate(()=>test.rememberDone());await page.waitForFunction(()=>test.copies.length===1);assert.deepEqual(await page.evaluate(()=>test.copies[0]),['text',false]);
  await page.evaluate(()=>test.copyFail(new Error('Synthetic copy error')));await page.waitForFunction(()=>!document.getElementById('copy').disabled);assert.match(await page.locator('#toast').textContent(),/Synthetic copy error/);await page.locator('#copy').click();await page.waitForFunction(()=>test.remember===2);await page.evaluate(()=>test.rememberDone());await page.waitForFunction(()=>test.copies.length===2);await page.evaluate(()=>test.copyDone());await page.waitForFunction(()=>!document.getElementById('copy').disabled);results.push({name:'main clipboard selection captured, keyboard/click deduplicated, failure retry',passed:true});
  await page.locator('#search').fill('');await page.locator('[data-page=data]').click();await page.waitForSelector('#backup-directory',{state:'attached'});await page.locator('.section-nav button').nth(1).click();await page.evaluate(()=>fixture.block='backup-folder');await page.locator('#backup-choose-folder').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='backup-folder'));
  await page.locator('[data-page=history]').click();await page.locator('[data-page=data]').click();await page.waitForSelector('#backup-directory',{state:'attached'});await page.locator('.section-nav button').nth(1).click();await page.evaluate(()=>{window.folderBefore=document.getElementById('backup-directory').value;fixture.release();});await page.waitForFunction(()=>!document.getElementById('backup-choose-folder').disabled);assert.equal(await page.locator('#backup-directory').inputValue(),await page.evaluate(()=>folderBefore));results.push({name:'late folder selection leaves new page untouched',passed:true});
  // Form submit events are gated even when dispatched directly, bypassing disabled buttons.
  await page.locator('.section-nav button').nth(2).click();await page.locator('#protected-export').click();await page.locator('#export-password').fill('Fixture-password-2026');await page.locator('#export-repeat').fill('Fixture-password-2026');await page.evaluate(()=>fixture.block='backup-export');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='backup-export'));await page.evaluate(()=>{const f=document.querySelector('dialog form');f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c[0]==='backup-export').length),1);await page.evaluate(()=>document.querySelector('dialog').dispatchEvent(new Event('cancel',{cancelable:true})));await page.waitForTimeout(150);assert.equal(await page.locator('dialog[open]').count(),1);await page.evaluate(()=>fixture.release());await page.waitForSelector('dialog[open]',{state:'detached'});results.push({name:'modal save submits exactly once',passed:true});
  await page.locator('[data-page=settings]').click();await page.waitForSelector('#save-settings');await page.locator('#save-settings').click();await page.waitForFunction(()=>test.settings===1);await page.locator('[data-page=history]').click();await page.evaluate(()=>test.settingsDone());await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('设置已保存'));assert.equal(await page.locator('h1').textContent(),'全部记录');assert.equal(await page.locator('#settings-feedback').count(),0);results.push({name:'late settings save leaves selected page intact',passed:true});
  await page.locator('[data-page=tools]').click();await page.waitForSelector('[data-ai-edit=remote]');await page.locator('[data-ai-edit=remote]').click();await page.locator('#ai-key').fill('Private-fixture-old-key');await page.evaluate(()=>fixture.block='profile-save');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='profile-save'));await page.locator('#modal-close').click();await page.waitForSelector('dialog[open]',{state:'detached'});await page.locator('#new-ai-profile').click();await page.locator('#ai-key').fill('Private-fixture-new-key');await page.evaluate(()=>fixture.release());await page.waitForTimeout(200);assert.equal(await page.locator('#ai-key').inputValue(),'Private-fixture-new-key');assert.equal(await page.locator('dialog[open]').count(),1);results.push({name:'old profile save does not wipe or close new dialog',passed:true});
  await context.close();
  // Compare the public canvas APIs in Chromium, including the native and fallback encoders.
  const imagePage=await browser.newPage();await imagePage.addScriptTag({content:compiled.outputFiles.find(f=>f.path.endsWith('.js')).text});
  for(const fallback of [false,true])for(const dimensions of [[1,1],[63,47],[900,900]]){
   const value=await imagePage.evaluate(async({fallback,dimensions})=>{const c=document.createElement('canvas');[c.width,c.height]=dimensions;const g=c.getContext('2d'),pixels=g.createImageData(c.width,c.height);let seed=1729;for(let i=0;i<pixels.data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;pixels.data[i]=seed>>>24;}g.putImageData(pixels,0,0);const baselineStart=performance.now(),expected=c.toDataURL('image/png').split(',')[1],baselineMs=performance.now()-baselineStart,original=Uint8Array.prototype.toBase64;let ticks=0,maxGap=0,last=performance.now();const timer=setInterval(()=>{const now=performance.now();ticks++;maxGap=Math.max(maxGap,now-last);last=now;},2);if(fallback)Uint8Array.prototype.toBase64=undefined;const started=performance.now();let actual;try{actual=await canvasPng(c);}finally{Uint8Array.prototype.toBase64=original;clearInterval(timer);}const elapsed=performance.now()-started;const decode=async value=>{const image=await createImageBitmap(new Blob([Uint8Array.from(atob(value),c=>c.charCodeAt(0))],{type:'image/png'}));const target=document.createElement('canvas');target.width=image.width;target.height=image.height;const ctx=target.getContext('2d');ctx.drawImage(image,0,0);image.close();return ctx.getImageData(0,0,target.width,target.height).data;};const a=await decode(actual),b=await decode(expected);return {equal:a.length===b.length&&a.every((v,i)=>v===b[i]),sameEncodedBytes:actual===expected,encoded:actual.length,ticks,maxGap,elapsed,baselineMs};},{fallback,dimensions});assert(value.equal,JSON.stringify({fallback,dimensions,value}));if(dimensions[0]===900)assert(value.ticks>1,'Large export should yield between chunks');encoding.push({fallback,dimensions,...value});
  }
  checked('encoder failure recovery',await imagePage.evaluate(async()=>{const c=document.createElement('canvas');c.toBlob=fn=>fn(null);let failed=false;try{await canvasPng(c);}catch(e){failed=true;}const d=document.createElement('canvas');d.width=d.height=1;return {failed,retry:(await canvasPng(d)).length>0};}));await imagePage.close();
  assert.deepEqual(errors,[]);await fs.writeFile('work/actions-034/results.json',JSON.stringify({passed:true,cases:results.length,results,encoding,errors,scope:'One button styling with actual built controller; headless isolated IPC and canvas, no system clipboard, native dialogs or desktop input'},null,2));console.log(JSON.stringify({passed:true,cases:results.length,encoding}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
