const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
async function run(){
 const output=path.resolve('work/advanced');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app;
 try{
  const target=await helper.firstWindow();await target.waitForSelector('#target');
  app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');const errors=[];page.on('pageerror',e=>errors.push(e.message));
  console.log('Step: image templates');
  const png=await target.evaluate(()=>{const c=document.createElement('canvas');c.width=900;c.height=320;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='black';x.font='bold 52px Arial';x.fillText('CLIPPER IMAGE 2026',40,100);x.font='42px Arial';x.fillText('Windows clipboard',40,180);x.fillText('Image template preview',40,250);return c.toDataURL().split(',')[1]});const imageFile=path.join(output,'Image fixture.png');await fs.writeFile(imageFile,Buffer.from(png,'base64'));
  await helper.evaluate(async({clipboard,ClipboardItem},png)=>clipboard.write([new ClipboardItem({'image/png':new Blob([Buffer.from(png,'base64')],{type:'image/png'})})]),png);
  await expect.poll(async()=> (await page.evaluate(()=>window.clipper.state())).clips.some(c=>c.kind==='image')).toBe(true);const imageId=(await page.evaluate(()=>window.clipper.state())).clips.find(c=>c.kind==='image').id;
  await page.locator('#save-reply').click();await page.locator('#reply-title').fill('图片回复');await page.locator('#dialog [type=submit]').click();await page.locator('[data-page=replies]').click();await expect(page.locator('.image-preview img')).toBeVisible();await page.locator('#copy').click();assert.equal(await helper.evaluate(async({clipboard})=>clipboard.has('image/png')),true);
  console.log('Step: variable template');
  await page.locator('#new-reply').click();await page.locator('#reply-title').fill('预约确认');await page.locator('#reply-text').fill('{{姓名}}，你的预约已确认。\n日期：{{日期}}\n事项：{{事项}}');await page.locator('#dialog [type=submit]').click();await page.getByRole('button',{name:'预约确认',exact:true}).click();await page.locator('#copy').click();await page.locator('[data-variable="0"]').fill('张三');await page.locator('[data-variable="1"]').fill('设计评审');await expect(page.locator('#template-preview')).toContainText('张三');await page.screenshot({path:path.join(output,'template-variables.png')});await page.locator('#dialog [type=submit]').click();const text=await helper.evaluate(async({clipboard})=>clipboard.readText());assert.match(text,/张三/);assert.match(text,/设计评审/);assert.doesNotMatch(text,/\{\{/);
  console.log('Step: file drop and shelf');
  const file=path.join(output,'文件.txt');await fs.writeFile(file,'原文件保持不变');await page.locator('[data-page=shelf]').click();await page.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='test-files';document.body.appendChild(input)});await page.locator('#test-files').setInputFiles(file);await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('test-files').files)));await expect(page.locator('.clip-row')).toHaveCount(1);const fileId=(await page.evaluate(()=>window.clipper.state())).shelf[0];await page.locator('#save-reply').click();await page.locator('#reply-title').fill('文件回复');await page.locator('#dialog [type=submit]').click();
  await page.evaluate(id=>window.clipper.batch([id],'shelf'),imageId);await expect(page.locator('.clip-row')).toHaveCount(2);await page.screenshot({path:path.join(output,'drag-shelf.png')});
  console.log('Step: native drag payload');
  await app.evaluate(({BrowserWindow})=>{global.dragCalls=[];BrowserWindow.getAllWindows()[0].webContents.startDrag=arg=>global.dragCalls.push({files:arg.files,iconEmpty:arg.icon.isEmpty()})});await page.locator(`[data-id="${fileId}"]`).dispatchEvent('dragstart');await expect.poll(()=>app.evaluate(()=>global.dragCalls.length)).toBe(1);assert.deepEqual((await app.evaluate(()=>global.dragCalls))[0].files,[file]);await page.locator(`[data-id="${imageId}"]`).dispatchEvent('dragstart');await expect.poll(()=>app.evaluate(()=>global.dragCalls.length)).toBe(2);const draggedImage=(await app.evaluate(()=>global.dragCalls))[1].files[0];const originalPng=(await page.evaluate(id=>window.clipper.detail(id),imageId)).payload.png;const hash=data=>require('node:crypto').createHash('sha256').update(data).digest('hex');assert.equal(hash(await fs.readFile(draggedImage)),hash(Buffer.from(originalPng,'base64')));assert.equal(await fs.readFile(file,'utf8'),'原文件保持不变');
  console.log('Step: category and batch');
  await helper.evaluate(async({clipboard})=>clipboard.writeText('https://example.com/clipboard'));await expect.poll(async()=> (await page.evaluate(()=>window.clipper.state())).clips.some(c=>c.kind==='link')).toBe(true);
  await page.locator('#add-category').click();await page.locator('#category-name').fill('参考链接');await page.locator('#category-kind').selectOption('link');await page.locator('#category-contains').fill('example.com');await page.locator('#dialog [type=submit]').click();await page.getByRole('button',{name:'参考链接',exact:true}).click();await expect(page.locator('.clip-row')).toHaveCount(1);await page.locator('#batch-mode').click();await page.locator('#batch-all').click();await page.locator('#batch-favorite').click();await expect.poll(async()=> (await page.evaluate(()=>window.clipper.state())).clips.filter(c=>c.favorite).length).toBe(1);await page.locator('#batch-all').click();await page.locator('#batch-tag').click();await page.locator('#batch-tags').fill('参考, 工作');await page.locator('#dialog [type=submit]').click();await expect.poll(async()=> (await page.evaluate(()=>window.clipper.state())).clips.some(c=>c.tags.includes('参考'))).toBe(true);await page.screenshot({path:path.join(output,'category-batch.png')});
  await page.locator('[data-page=history]').click();await page.locator('[data-kind=image]').click();await expect(page.locator('#ocr')).toHaveCount(0);
  console.log('Step: image import bounds');const oversized=path.join(output,'oversized.png'),bad=Buffer.from(png,'base64');bad.writeUInt32BE(20000,16);bad.writeUInt32BE(20000,20);await fs.writeFile(oversized,bad);await page.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='image-import';document.body.appendChild(input)});await page.locator('#image-import').setInputFiles(oversized);const rejected=await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('image-import').files)).catch(e=>e.message));assert.match(rejected,/像素过大/);const jpeg=path.join(output,'photo.jpg');await fs.writeFile(jpeg,Buffer.from(await helper.evaluate(({nativeImage},png)=>nativeImage.createFromBuffer(Buffer.from(png,'base64')).toJPEG(80).toString('base64'),png),'base64'));await page.locator('#image-import').setInputFiles(jpeg);await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('image-import').files)));
  await page.locator('[data-page=settings]').click();await page.locator('[data-theme-choice=dark]').click();await page.locator('#save-settings').click();await page.locator('[data-page=shelf]').click();await page.waitForTimeout(180);await page.screenshot({path:path.join(output,'shelf-dark.png')});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,richTemplates:true,variables:true,categories:true,batch:true,realFileObjects:true,dragPayloadVerified:true,imageHeaderLimits:true,jpegImport:true,profile,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard()).catch(e=>console.error('clipboard restore failed',e));await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
