const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
async function service(t,probe){const dir=await generated.mkdtemp(path.join(os.tmpdir(),'clip-appearance-ipc-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'appearance.json'),handlers=new Map(),windows=[];
 const electron={webContents:{getAllWebContents:()=>windows.map(w=>w.webContents)},app:{on:()=>{}},session:{defaultSession:{protocol:{handle:()=>{}}},fromPartition:()=>({protocol:{handle:()=>{}}})},net:{fetch:()=>{}},BrowserWindow:{fromWebContents:sender=>windows.find(w=>w.webContents===sender),getAllWindows:()=>windows},ipcMain:{handle:(name,fn)=>handlers.set(name,fn)}};
 const builtinRequire=name=>{if(name==='electron')return electron;if(name==='node:child_process'&&probe){const execFile=()=>{};execFile[require('node:util').promisify.custom]=async(_helper,args)=>({stdout:JSON.stringify(args[0]==='fonts'?[]:await probe(args[1]))});return {...require(name),execFile};}return require(name);};
 const module={exports:{}};vm.runInNewContext(await fs.readFile('work/test-appearance-service.cjs','utf8'),{module,exports:module.exports,require:builtinRequire,__dirname:path.resolve('work'),Buffer,URL,console},{filename:'appearance-service-test.cjs'});
 const app=new module.exports.AppearanceService(file);await app.init();
 function window(url='clip://app/index.html'){const messages=[],frame={url},w={isDestroyed:()=>false,isVisible:()=>false,isMinimized:()=>false,isMaximized:()=>false,isMaximizable:()=>true,isMinimizable:()=>true,webContents:{isDestroyed:()=>false,mainFrame:frame,getURL:()=>url,send:(...args)=>messages.push(args)}};windows.push(w);return {w,messages,event:{sender:w.webContents,senderFrame:frame}};}
 return {app,file,dir,window,read:handlers.get('clip:appearance-state'),handlers};
}
test('Appearance IPC refuses foreign windows and nested frames even with a trusted URL',async t=>{const {window,read,handlers}=await service(t),owned=window();assert.deepEqual([...handlers.keys()].sort(),['clip:appearance-state','clip:installed-fonts','clip:font-source','clip:chrome-state','clip:chrome-action','clip:window-confirm-answer'].sort());assert.throws(()=>read({sender:{mainFrame:owned.event.senderFrame},senderFrame:owned.event.senderFrame}),/拒绝/);assert.throws(()=>read({...owned.event,senderFrame:{url:'clip://app/index.html'}}),/拒绝/);assert.throws(()=>read(window('https://example.invalid/index.html').event),/拒绝/);assert.equal(read(owned.event).value.scale,100);});
test('Locked and recovery windows can read appearance without any history or setter access',async t=>{const {app,window,read,handlers}=await service(t);await app.save({font:'sans',scale:125,density:'compact'});for(const name of ['unlock','recovery','tray','capture','recorder','image-editor']){const state=read(window(`clip://app/${name}.html`).event);assert.equal(state.value.scale,125);assert.deepEqual(Object.keys(state).sort(),['value','warning']);state.value.scale=100;assert.equal(read(window().event).value.scale,125);}assert.equal(handlers.has('clip:appearance-save'),false);});
test('Appearance notifies live owned windows while closing renderers cannot invalidate a saved preference',async t=>{const {app,file,window}=await service(t),closing=window(),untrusted=window('https://example.invalid/index.html'),closed=window(),live=window('clip://app/tray.html');closing.w.webContents.send=()=>{throw Error('renderer closed');};closed.w.isDestroyed=()=>true;const result=await app.save({font:'mono',scale:150,density:'compact'});assert.equal(result.value.scale,150);assert.equal(live.messages.length,1);assert.equal(live.messages[0][0],'clip:appearance-changed');assert.equal(untrusted.messages.length,0);assert.equal(closed.messages.length,0);assert.equal(JSON.parse(await fs.readFile(file,'utf8')).value.scale,150);});
test('Appearance validation and disk failures produce no notification or live state change',async t=>{const {app,file,window,read}=await service(t),owned=window();await assert.rejects(app.save({font:'system',scale:900,density:'compact'}),/无效/);await fs.mkdir(file);await assert.rejects(app.save({font:'mono',scale:150,density:'compact'}));assert.equal(owned.messages.length,0);assert.equal(read(owned.event).value.scale,100);});
test('Native chrome state reports only the requesting owned top-level window and includes minimization visibility',async t=>{const {window,handlers}=await service(t),read=handlers.get('clip:chrome-state'),owned=window();assert.equal(read(owned.event).visible,false);owned.w.isVisible=()=>true;assert.equal(read(owned.event).visible,true);owned.w.isMinimized=()=>true;assert.equal(read(owned.event).visible,false);assert.throws(()=>read({...owned.event,senderFrame:{url:'clip://app/index.html'}}),/拒绝/);assert.throws(()=>read({sender:{mainFrame:owned.event.senderFrame},senderFrame:owned.event.senderFrame}),/拒绝/);assert.throws(()=>read(window('https://example.invalid/index.html').event),/拒绝/);});

test('Font sources coalesce concurrent helper reads and return isolated cached metadata',async t=>{let reads=0;const {dir,window,handlers}=await service(t,async family=>{reads++;await new Promise(resolve=>setImmediate(resolve));return {path:path.join(dir,'test.ttf'),index:0,fullName:family,postscript:family};});await fs.writeFile(path.join(dir,'test.ttf'),'font');const source=handlers.get('clip:font-source'),event=window().event;const values=await Promise.all([source(event,'Emoji'),source(event,'Emoji')]);assert.equal(reads,1);assert.equal(values[0].url,values[1].url);values[0].local.push('mutated');assert.equal((await source(event,'Emoji')).local.includes('mutated'),false);assert.equal(reads,1);await assert.rejects(source(window('https://example.invalid/index.html').event,'Emoji'),/拒绝/);await assert.rejects(source(event,'bad\0name'));assert.equal(reads,1);assert.deepEqual(Object.keys(values[1]).sort(),['local','url']);});
test('Refreshing installed fonts invalidates the source lookup and expired source tokens are bounded',async t=>{let reads=0;const {dir,window,handlers}=await service(t,async family=>{reads++;return {path:path.join(dir,'test.ttf'),index:0,fullName:family};});await fs.writeFile(path.join(dir,'test.ttf'),'font');const source=handlers.get('clip:font-source'),event=window().event;const first=await source(event,'Emoji');await handlers.get('clip:installed-fonts')(event,true);const next=await source(event,'Emoji');assert.notEqual(first.url,next.url);assert.equal(reads,2);for(let i=0;i<64;i++)await source(event,'Family'+i);await source(event,'Emoji');assert.equal(reads,67);});
test('A failed helper request can retry instead of poisoning the font source cache',async t=>{let reads=0;const {dir,window,handlers}=await service(t,async family=>{if(++reads===1)throw Error('temporary failure');return {path:path.join(dir,'test.ttf'),index:0,fullName:family};});await fs.writeFile(path.join(dir,'test.ttf'),'font');const source=handlers.get('clip:font-source'),event=window().event;await assert.rejects(source(event,'Emoji'),/temporary failure/);assert.match((await source(event,'Emoji')).url,/clip-font:/);assert.equal(reads,2);});

test('A font lookup finishing after refresh cannot replace the new generation',async t=>{let reads=0,finish;const {dir,window,handlers}=await service(t,async family=>{reads++;if(reads===1)await new Promise(resolve=>finish=resolve);return {path:path.join(dir,'test.ttf'),index:0,fullName:family};});await fs.writeFile(path.join(dir,'test.ttf'),'font');const source=handlers.get('clip:font-source'),event=window().event;const previous=source(event,'Emoji');await new Promise(resolve=>setImmediate(resolve));assert.ok(finish);await handlers.get('clip:installed-fonts')(event,true);const current=await source(event,'Emoji');finish();const stale=await previous;assert.notEqual(stale.url,current.url);assert.equal((await source(event,'Emoji')).url,current.url);assert.equal(reads,2);});
