const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
async function service(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'clipper-appearance-ipc-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'appearance.json'),handlers=new Map(),windows=[];
 const electron={app:{on:()=>{}},session:{defaultSession:{protocol:{handle:()=>{}}},fromPartition:()=>({protocol:{handle:()=>{}}})},net:{fetch:()=>{}},BrowserWindow:{fromWebContents:sender=>windows.find(w=>w.webContents===sender),getAllWindows:()=>windows},ipcMain:{handle:(name,fn)=>handlers.set(name,fn)}};
 const module={exports:{}};vm.runInNewContext(await fs.readFile('work/test-appearance-service.cjs','utf8'),{module,exports:module.exports,require:name=>name==='electron'?electron:require(name),Buffer,URL,console},{filename:'appearance-service-test.cjs'});
 const app=new module.exports.AppearanceService(file);await app.init();
 function window(url='clipper://app/index.html'){const messages=[],frame={url},w={isDestroyed:()=>false,isVisible:()=>false,isMinimized:()=>false,isMaximized:()=>false,isMaximizable:()=>true,isMinimizable:()=>true,webContents:{isDestroyed:()=>false,mainFrame:frame,getURL:()=>url,send:(...args)=>messages.push(args)}};windows.push(w);return {w,messages,event:{sender:w.webContents,senderFrame:frame}};}
 return {app,file,window,read:handlers.get('clipper:appearance-state'),handlers};
}
test('Appearance IPC refuses foreign windows and nested frames even with a trusted URL',async t=>{const {window,read,handlers}=await service(t),owned=window();assert.deepEqual([...handlers.keys()].sort(),['clipper:appearance-state','clipper:installed-fonts','clipper:font-source','clipper:chrome-state','clipper:chrome-action','clipper:window-confirm-answer'].sort());assert.throws(()=>read({sender:{mainFrame:owned.event.senderFrame},senderFrame:owned.event.senderFrame}),/拒绝/);assert.throws(()=>read({...owned.event,senderFrame:{url:'clipper://app/index.html'}}),/拒绝/);assert.throws(()=>read(window('https://example.invalid/index.html').event),/拒绝/);assert.equal(read(owned.event).value.scale,100);});
test('Locked and recovery windows can read appearance without any history or setter access',async t=>{const {app,window,read,handlers}=await service(t);await app.save({font:'sans',scale:125,density:'compact'});for(const name of ['unlock','recovery','tray','capture','recorder','scroll','image-editor']){const state=read(window(`clipper://app/${name}.html`).event);assert.equal(state.value.scale,125);assert.deepEqual(Object.keys(state).sort(),['value','warning']);state.value.scale=100;assert.equal(read(window().event).value.scale,125);}assert.equal(handlers.has('clipper:appearance-save'),false);});
test('Appearance notifies live owned windows while closing renderers cannot invalidate a saved preference',async t=>{const {app,file,window}=await service(t),closing=window(),untrusted=window('https://example.invalid/index.html'),closed=window(),live=window('clipper://app/tray.html');closing.w.webContents.send=()=>{throw Error('renderer closed');};closed.w.isDestroyed=()=>true;const result=await app.save({font:'mono',scale:150,density:'compact'});assert.equal(result.value.scale,150);assert.equal(live.messages.length,1);assert.equal(live.messages[0][0],'clipper:appearance-changed');assert.equal(untrusted.messages.length,0);assert.equal(closed.messages.length,0);assert.equal(JSON.parse(await fs.readFile(file,'utf8')).value.scale,150);});
test('Appearance validation and disk failures produce no notification or live state change',async t=>{const {app,file,window,read}=await service(t),owned=window();await assert.rejects(app.save({font:'system',scale:900,density:'compact'}),/无效/);await fs.mkdir(file);await assert.rejects(app.save({font:'mono',scale:150,density:'compact'}));assert.equal(owned.messages.length,0);assert.equal(read(owned.event).value.scale,100);});
test('Native chrome state reports only the requesting owned top-level window and includes minimization visibility',async t=>{const {window,handlers}=await service(t),read=handlers.get('clipper:chrome-state'),owned=window();assert.equal(read(owned.event).visible,false);owned.w.isVisible=()=>true;assert.equal(read(owned.event).visible,true);owned.w.isMinimized=()=>true;assert.equal(read(owned.event).visible,false);assert.throws(()=>read({...owned.event,senderFrame:{url:'clipper://app/index.html'}}),/拒绝/);assert.throws(()=>read({sender:{mainFrame:owned.event.senderFrame},senderFrame:owned.event.senderFrame}),/拒绝/);assert.throws(()=>read(window('https://example.invalid/index.html').event),/拒绝/);});
