const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {AppearanceStore,defaultAppearance,validateAppearance,trustedAppearancePage}=require('../work/test-exports.cjs');
const chosen={...defaultAppearance(),font:'mono',scale:150,density:'compact'};
async function fixture(t){const dir=await generated.mkdtemp(path.join(os.tmpdir(),'clip-appearance-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'appearance.json');return {dir,file,store:new AppearanceStore(file)};}
test('Appearance accepts only bounded options and discards unrelated data',()=>{for(const value of [null,{},[],{...chosen,font:'url(https://example.invalid)'},{...chosen,scale:200},{...chosen,scale:'150'},{...chosen,density:'tiny'}])assert.throws(()=>validateAppearance(value));assert.deepEqual(validateAppearance({...chosen,clipboard:'private'}),chosen);const defaults=defaultAppearance();defaults.scale=150;assert.equal(defaultAppearance().scale,100);});
test('Appearance read access is confined to owned application pages',()=>{for(const page of ['index','quick','tray','tray-menu','shelf','capture','recorder','image-editor','unlock','recovery'])assert.equal(trustedAppearancePage(`clip://app/${page}.html`),true);assert.equal(trustedAppearancePage('clip://app/index.html?quick=1'),true);for(const url of ['https://app/index.html','file:///index.html','clip://other/index.html','clip://app/web/index.html','clip://app/index.html/extra','not a url'])assert.equal(trustedAppearancePage(url),false);});
test('Appearance survives restart independently of clipboard database',async t=>{const {dir,file,store}=await fixture(t);assert.deepEqual(await store.load(),{value:defaultAppearance(),warning:''});await store.save({...chosen,secret:'must not persist'});assert.deepEqual(await new AppearanceStore(file).load(),{value:chosen,warning:''});assert.deepEqual(await fs.readdir(dir),['appearance.json']);assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),{version:1,value:chosen});});
test('Appearance serializes consecutive saves and isolates caller mutations',async t=>{const {file,store}=await fixture(t),first={...chosen};const a=store.save(first);first.font='sans';const b=store.save({...chosen,scale:110});await Promise.all([a,b]);const state=store.state();assert.equal(state.value.scale,110);state.value.scale=150;assert.equal(store.state().value.scale,110);assert.equal((await new AppearanceStore(file).load()).value.scale,110);});
test('Appearance corruption and oversized files preserve evidence until explicit save',async t=>{const {file,store}=await fixture(t);for(const raw of ['{broken','null',JSON.stringify({version:999,value:chosen}),JSON.stringify({version:1,value:{...chosen,scale:999}}),' '.repeat(2049)]){await fs.writeFile(file,raw);const state=await store.load();assert.deepEqual(state.value,defaultAppearance());assert.ok(state.warning);assert.equal(await fs.readFile(file,'utf8'),raw);}await store.save(chosen);assert.equal(store.state().warning,'');assert.deepEqual((await store.load()).value,chosen);});
test('Appearance failed replacement keeps live settings and removes its temporary file',async t=>{const {dir,file,store}=await fixture(t);await store.save(chosen);await fs.unlink(file);await fs.mkdir(file);await assert.rejects(store.save(defaultAppearance()));assert.deepEqual(store.state().value,chosen);assert.deepEqual(await fs.readdir(dir),['appearance.json']);await fs.rmdir(file);await store.save(defaultAppearance());assert.deepEqual(store.state().value,defaultAppearance());});
test('Appearance rejects invalid save without replacing valid persisted settings',async t=>{const {file,store}=await fixture(t);await store.save(chosen);const raw=await fs.readFile(file,'utf8');assert.throws(()=>store.save({...chosen,scale:0}));assert.equal(await fs.readFile(file,'utf8'),raw);assert.deepEqual(store.state().value,chosen);});
