const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('@playwright/test'),asar=require('@electron/asar');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs'),{prepare}=require('./auxiliary-043-fixture.cjs');
const archive=process.env.CLIPPER_AUXILIARY_ASAR,out=process.env.CLIPPER_TEST_OUTPUT_DIR||'work/current/auxiliary-043',results=[],errors=[];
const read=name=>archive?asar.extractFile(archive,('dist/renderer/'+name).replaceAll('/','\\')):fs.readFileSync('dist/renderer/'+name);
const pass=name=>results.push(name),delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});try{
for(const [language,theme]of [['zh-CN','light'],['en','dark']]){
 const context=await browser.newContext({viewport:{width:740,height:560}});await context.addInitScript(setup,language);await context.addInitScript(extra);await context.addInitScript(prepare,{theme});await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);assert(/^[\w./-]+$/.test(name)&&!name.includes('..'));await route.fulfill({body:read(name),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('https://clipper.test/tray.html');await page.waitForSelector('#preview pre');await page.waitForFunction(()=>document.getElementById('filters').classList.contains('segment-ready'));assert.equal(await page.locator('.tray-row').count(),80);assert(await page.locator('#filters button').evaluateAll(nodes=>nodes.every(n=>getComputedStyle(n).borderTopWidth==='0px')));pass(language+' One recent skeleton and segment indicator');
 const initial=await page.evaluate(()=>{window.keepRow=document.querySelector('[data-id=aux-0]');window.keepFilter=document.querySelector('#filters button');window.keepPreview=document.querySelector('#preview .preview-content');window.keepPre=document.querySelector('#preview pre');const range=document.createRange();range.setStart(keepPre.firstChild,8);range.setEnd(keepPre.firstChild,24);getSelection().removeAllRanges();getSelection().addRange(range);document.getElementById('preview').scrollTop=120;window.previewScroll=document.getElementById('preview').scrollTop;keepFilter.focus();return {previews:fixture.aux.previews,selection:getSelection().toString()};});
 for(let i=0;i<5;i++){await page.evaluate(i=>{fixture.aux.records[0].source='Changed '+i;fixture.aux.records[0].title='Updated '+i;fixture.auxRefresh('tray');},i);await page.waitForFunction(i=>document.querySelector('#preview .preview-heading strong')?.textContent==='Updated '+i,i);}
 assert(await page.evaluate(()=>keepRow===document.querySelector('[data-id=aux-0]')&&keepFilter===document.activeElement&&keepPreview===document.querySelector('#preview .preview-content')&&keepPre===document.querySelector('#preview pre')&&document.getElementById('preview').scrollTop===previewScroll));assert.equal(await page.evaluate(()=>fixture.aux.previews),initial.previews);assert.equal(await page.evaluate(()=>getSelection().toString()),initial.selection);pass(language+' Refresh preserves focused One control, rows, text selection and reading position');
 await page.evaluate(()=>{fixture.aux.failUse=true;document.querySelector('[data-id=aux-0]').click();});await page.waitForFunction(()=>fixture.aux.copies.length===1);assert(await page.evaluate(()=>fixture.aux.copies[0].token===fixture.aux.lastTokens['aux-0']));await page.waitForFunction(()=>!document.getElementById('copy-selected').disabled);pass(language+' Retained row uses fresh action ticket and failed use remains retryable');
 await page.evaluate(()=>{window.segmentButtons=Array.from(document.querySelectorAll('#filters button'));segmentButtons[0].focus();});await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('#filters [data-kind=text]')?.getAttribute('aria-pressed')==='true'&&!document.getElementById('copy-selected').disabled);assert(await page.evaluate(()=>segmentButtons.every((b,n)=>b===document.querySelectorAll('#filters button')[n])&&document.activeElement===segmentButtons[1]));pass(language+' One segment keyboard transition keeps all button elements');
 await page.locator('#filters [data-kind=image]').click();await page.waitForSelector('#preview img');await page.waitForFunction(()=>document.querySelector('#preview img')?.naturalWidth===32);const imageReads=await page.evaluate(()=>{window.previewImage=document.querySelector('#preview img');return fixture.aux.previews;});await page.evaluate(()=>{fixture.aux.records[1].title='Changed image';fixture.auxRefresh('tray');});await page.waitForFunction(()=>document.querySelector('#preview strong')?.textContent==='Changed image');assert(await page.evaluate(()=>previewImage===document.querySelector('#preview img')));assert.equal(await page.evaluate(()=>fixture.aux.previews),imageReads);pass(language+' Image metadata retains decoded preview');
 await page.evaluate(()=>{document.querySelector('[data-id=aux-1]').dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true}));});assert(await page.evaluate(()=>fixture.aux.drags.length===1&&fixture.aux.drags[0].token===fixture.aux.lastTokens['aux-1']));await page.evaluate(()=>fixture.auxNotice('tray','Private drag finished'));pass(language+' Reused image row drags once with current ticket');
 await page.evaluate(()=>{fixture.aux.records[1].hash='changed-image-body';fixture.auxRefresh('tray');});await page.waitForFunction(n=>fixture.aux.previews===n+1,imageReads);pass(language+' Original content changes invalidate recent preview');
 await page.locator('#filters [data-kind=all]').click();await page.waitForSelector('[data-id=aux-0]');await page.locator('[data-id=aux-0]').focus();await page.waitForSelector('#preview pre');await page.evaluate(()=>{fixture.aux.blockPreview=true;fixture.aux.records[0].hash='pending-new-body';fixture.auxRefresh('tray');});await page.waitForFunction(()=>fixture.aux.pending.length===1);await page.locator('#filters [data-kind=files]').click();await page.waitForFunction(()=>fixture.aux.pending.length===2);await page.evaluate(()=>{fixture.aux.pending.shift()();fixture.aux.pending.shift()();fixture.aux.blockPreview=false;});await page.waitForSelector('#preview .files');assert.equal(await page.locator('#preview pre').count(),0);pass(language+' Late preview cannot overwrite changed filter');
 await page.evaluate(()=>{fixture.aux.records=[];fixture.auxRefresh('tray');});await page.waitForFunction(()=>document.getElementById('copy-selected').disabled&&document.querySelectorAll('.tray-row').length===0);assert.equal(await page.locator('#preview .files').count(),0);pass(language+' Empty results retire selected preview and disable operations');
 await page.evaluate(()=>{const d=document.createElement('dialog');d.id='probe-dialog';document.body.append(d);d.showModal();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),0);await page.evaluate(()=>{document.getElementById('probe-dialog').close();document.getElementById('probe-dialog').remove();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),1);pass(language+' Open dialog owns Escape before recent window');
 await page.setViewportSize({width:420,height:440});await page.goto('https://clipper.test/shelf.html');await page.waitForSelector('.shelf-row');assert.equal(await page.locator('.shelf-row').count(),140);const shelf=await page.evaluate(()=>{window.shelfRow=document.querySelector('[data-id=aux-1]');window.shelfImage=shelfRow.querySelector('img');window.shelfCopy=shelfRow.querySelector('[data-copy]');shelfCopy.focus();return fixture.aux.shelfReads;});await page.evaluate(()=>{fixture.aux.records[1].title='New shelf title';fixture.auxRefresh('shelf');});await page.waitForFunction(()=>document.querySelector('[data-id=aux-1] strong')?.textContent==='New shelf title');assert(await page.evaluate(()=>shelfRow===document.querySelector('[data-id=aux-1]')&&shelfImage===shelfRow.querySelector('img')&&shelfCopy===document.activeElement));pass(language+' Shelf metadata keeps row, thumbnail, action button and focus');
 await page.evaluate(()=>{fixture.aux.blockCopy=true;document.querySelector('[data-copy=aux-1]').click();});await page.waitForFunction(()=>!!fixture.aux.copyResolve);await page.waitForTimeout(180);for(let i=0;i<3;i++){await page.evaluate(i=>{fixture.aux.records[1].title='Busy title '+i;fixture.auxRefresh('shelf');},i);await page.waitForFunction(i=>document.querySelector('[data-id=aux-1] strong')?.textContent==='Busy title '+i,i);}assert(await page.evaluate(()=>shelfCopy===document.querySelector('[data-copy=aux-1]')&&shelfCopy.disabled&&shelfCopy.classList.contains('action-pending')&&fixture.aux.copies.length===1));await page.evaluate(()=>{fixture.aux.blockCopy=false;fixture.aux.copyResolve();});await page.waitForFunction(()=>!document.querySelector('[data-copy=aux-1]').disabled);pass(language+' Busy shelf action remains one operation across reused controls');
 const anchor=await page.evaluate(()=>{const box=document.getElementById('items');box.scrollTop=900;const r=box.getBoundingClientRect();window.shelfAnchor=document.elementFromPoint(r.left+24,r.top+12).closest('.shelf-row');return {id:shelfAnchor.dataset.id,offset:shelfAnchor.getBoundingClientRect().top};});await page.evaluate(()=>{fixture.aux.records.unshift({...fixture.aux.records[0],id:'arriving'});fixture.auxRefresh('shelf');});await page.waitForSelector('[data-id=arriving]');assert(await page.evaluate(({id,offset})=>shelfAnchor===document.querySelector('[data-id="'+id+'"]')&&Math.abs(shelfAnchor.getBoundingClientRect().top-offset)<1,anchor));pass(language+' Shelf arrival preserves the record being read');
 await page.evaluate(()=>{const item=fixture.aux.records.find(i=>i.id==='aux-1');item.kind='text';item.thumbnail=undefined;fixture.auxRefresh('shelf');});await page.waitForFunction(()=>document.querySelector('[data-id=aux-1]')?.draggable===false);await page.evaluate(()=>document.querySelector('[data-id=aux-1]').dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true})));assert.equal(await page.evaluate(()=>fixture.aux.drags.length),0);pass(language+' Changed row clears obsolete native drag');
 await page.evaluate(()=>document.querySelector('[data-id=aux-0] .row-body').dispatchEvent(new MouseEvent('dblclick',{bubbles:true})));await page.waitForFunction(()=>fixture.aux.copies.length===2);assert.deepEqual(await page.evaluate(()=>fixture.aux.copies[1]),{id:'aux-0',paste:true});pass(language+' Delegated shelf double-click pastes the current record once');
 const hidden=await page.evaluate(()=>{const box=document.getElementById('items'),rect=box.getBoundingClientRect(),row=document.elementFromPoint(rect.left+24,rect.top+12).closest('.shelf-row');window.savedShelfAnchor={id:row.dataset.id,offset:row.getBoundingClientRect().top-rect.top};fixture.windowVisible(false);return fixture.aux.shelfReads;});assert.equal(await page.locator('.shelf-row,img').count(),0);await page.evaluate(()=>{fixture.aux.records.unshift({...fixture.aux.records[0],id:'hidden-arrival'});for(let i=0;i<100;i++)fixture.auxRefresh('shelf');});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>fixture.aux.shelfReads),hidden);await page.evaluate(()=>fixture.windowVisible(true));await page.waitForSelector('.shelf-row');assert(await page.evaluate(()=>Math.abs(document.querySelector('[data-id="'+savedShelfAnchor.id+'"]').getBoundingClientRect().top-document.getElementById('items').getBoundingClientRect().top-savedShelfAnchor.offset)<1));pass(language+' Hidden shelf retires rows and thumbnails, reads nothing and restores the reading anchor after hidden arrivals');
 await page.evaluate(()=>{fixture.aux.blockShelf=true;fixture.auxRefresh('shelf');});await page.waitForFunction(()=>fixture.aux.pending.length===1);await page.evaluate(()=>{fixture.windowVisible(false);fixture.aux.pending.shift()();fixture.aux.blockShelf=false;});await page.waitForTimeout(80);assert.equal(await page.locator('.shelf-row').count(),0);await page.evaluate(()=>fixture.windowVisible(true));await page.waitForSelector('.shelf-row');pass(language+' Late shelf result cannot restore hidden contents');
 const count=await page.evaluate(()=>{const n=fixture.aux.shelfReads;for(let i=0;i<200;i++)fixture.auxRefresh('shelf');return n;});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>fixture.aux.shelfReads),count+1);pass(language+' Two hundred updates coalesce into one shelf state read');
 await page.evaluate(()=>{fixture.aux.records=[];fixture.auxRefresh('shelf');});await page.waitForSelector('#empty-choose');await page.evaluate(()=>{for(let i=0;i<5;i++)fixture.auxRefresh('shelf');});await page.waitForTimeout(100);await page.locator('#empty-choose').click();assert.equal(await page.evaluate(()=>fixture.aux.chooses),1);pass(language+' Reused empty-state chooser binds one action');
 await page.evaluate(()=>{const d=document.createElement('dialog');d.id='probe-dialog';document.body.append(d);d.showModal();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),0);await page.evaluate(()=>{document.getElementById('probe-dialog').close();document.getElementById('probe-dialog').remove();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),1);pass(language+' Open dialog owns Escape before shelf window');
 await page.setViewportSize({width:1240,height:800});await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');await page.evaluate(()=>{const d=document.createElement('dialog');d.id='guard-dialog';document.body.append(d);d.showModal();for(const key of ['Escape','Enter'])document.body.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides+fixture.aux.copies.length),0);pass(language+' Main dialog blocks underlying hide and paste shortcuts');
 await page.goto('https://clipper.test/image-editor.html');await page.waitForFunction(()=>document.getElementById('image')?.width===640);await page.locator('#rotate').click();const steps=await page.locator('#steps').textContent();await page.evaluate(()=>{const d=document.createElement('dialog');d.id='guard-dialog';document.body.append(d);d.showModal();for(const key of ['z','s'])document.body.dispatchEvent(new KeyboardEvent('keydown',{key,ctrlKey:true,bubbles:true,cancelable:true}));});assert.equal(await page.locator('#steps').textContent(),steps);assert.equal(await page.evaluate(()=>fixture.aux.copies.length),0);pass(language+' Image editor dialog blocks underlying undo and save');
 for(const name of ['capture','selection']){await page.goto('https://clipper.test/'+name+'.html');await page.waitForTimeout(100);await page.evaluate(()=>{const d=document.createElement('dialog');d.id='guard-dialog';document.body.append(d);d.showModal();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),0);await page.evaluate(()=>{document.getElementById('guard-dialog').close();document.getElementById('guard-dialog').remove();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>fixture.aux.hides),1);pass(language+' '+name+' dialog owns Escape');}
 await context.close();
}
assert.deepEqual(errors,[]);assert.equal(results.length,48);const report={passed:true,version:JSON.parse(fs.readFileSync('package.json')).version,packaged:!!archive,cases:results.length,results,errors,scope:'Actual production renderer/CSS/components in headless Edge; isolated synthetic IPC with rotating action tokens; no system clipboard or physical input.'};fs.writeFileSync(out+'/'+(archive?'packaged':'results')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,cases:results.length,packaged:!!archive}));
}finally{await browser.close();}})().catch(e=>{console.error(e,results.slice(-5));process.exitCode=1;});
