const {_electron:electron,expect}=require('@playwright/test');
const near=(actual,expected)=>assert.ok(actual.every((v,i)=>Math.abs(v-expected[i])<=4),`Color mismatch: ${actual} / ${expected}`);
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
async function run(){
 const output=path.resolve('work/capture');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIP_TEST_MODE:'1',CLIP_DATA_DIR:profile,CLIP_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app;
 try{
  const fixture=await helper.firstWindow();await fixture.waitForSelector('#target');await fixture.evaluate(()=>{document.body.innerHTML='<div style="height:100vh;background:linear-gradient(to right,#164b9b 0%,#164b9b 50%,#c63138 50%,#c63138 100%)"></div>';document.body.style.cssText='margin:0;overflow:hidden';});
  app=await electron.launch(process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');
  const displays=await app.evaluate(({screen})=>screen.getAllDisplays().map(d=>({id:d.id,bounds:d.bounds,scale:d.scaleFactor})));const results=[];
  const sample=async id=>{const data=await page.evaluate(id=>window.clip.detail(id),id);return app.evaluate(({nativeImage},png)=>{const img=nativeImage.createFromBuffer(Buffer.from(png,'base64')),size=img.getSize(),b=img.toBitmap();const pixel=(x,y)=>{const i=(y*size.width+x)*4;return [b[i+2],b[i+1],b[i]]};return {size,left:pixel(Math.floor(size.width/4),Math.floor(size.height/2)),right:pixel(Math.floor(size.width*3/4),Math.floor(size.height/2))}},data.payload.png);};
  for(const d of displays){
   await helper.evaluate(async(_,bounds)=>{global.helperWindow.setFullScreen(false);global.helperWindow.setBounds(bounds);global.helperWindow.show();global.helperWindow.setFullScreen(true);global.helperWindow.setAlwaysOnTop(true,'screen-saver');global.helperWindow.focus();},d.bounds);await fixture.waitForTimeout(1200);
   const screenId=await page.evaluate(id=>window.clip.screenshot('screen',id),d.id);assert.ok(screenId);const whole=await sample(screenId);console.log('CAPTURE_DIAGNOSTICS',JSON.stringify({display:d,whole,helper:await helper.evaluate(async({screen})=>({bounds:global.helperWindow.getBounds(),fullscreen:global.helperWindow.isFullScreen(),focused:global.helperWindow.isFocused(),displays:screen.getAllDisplays().map(d=>({id:d.id,bounds:d.bounds,scale:d.scaleFactor}))}))}));near(whole.left,[22,75,155]);near(whole.right,[198,49,56]);
   const pending=page.evaluate(id=>window.clip.screenshot('region',id),d.id);pending.catch(()=>{});const overlay=await app.waitForEvent('window');await overlay.waitForSelector('#screen');await expect.poll(()=>overlay.locator('#screen').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);assert.equal(await overlay.evaluate(()=>typeof window.clip),'undefined');
   const actual=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/capture.html'));return {content:w.getContentBounds(),outer:w.getBounds(),fullscreen:w.isFullScreen()};});assert.equal(actual.fullscreen,true);assert.deepEqual(actual.outer,d.bounds);await expect.poll(()=>overlay.evaluate(()=>({width:innerWidth,height:innerHeight})),{timeout:5000}).toEqual({width:actual.content.width,height:actual.content.height});const bounds=await overlay.evaluate(()=>({width:innerWidth,height:innerHeight}));console.log('OVERLAY',JSON.stringify({bounds,native:await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().includes('capture')).map(w=>({bounds:w.getBounds(),content:w.getContentBounds(),fullscreen:w.isFullScreen()})))}));const x=80,y=90,width=320,height=180;await overlay.mouse.move(x,y);await overlay.mouse.down();await overlay.mouse.move(x+width,y+height,{steps:8});await overlay.mouse.up();await expect(overlay.locator('#capture-actions')).toBeVisible();await overlay.locator('#save').click();const cropId=await pending;const crop=await sample(cropId);
   const expectedWidth=Math.ceil((x+width)*whole.size.width/bounds.width)-Math.floor(x*whole.size.width/bounds.width),expectedHeight=Math.ceil((y+height)*whole.size.height/bounds.height)-Math.floor(y*whole.size.height/bounds.height);assert.deepEqual(crop.size,{width:expectedWidth,height:expectedHeight});near(crop.left,[22,75,155]);near(crop.right,[22,75,155]);
   const count=(await page.evaluate(()=>window.clip.state())).clips.length;const cancelled=page.evaluate(id=>window.clip.screenshot('region',id),d.id);cancelled.catch(()=>{});const cancelOverlay=await app.waitForEvent('window');await cancelOverlay.waitForSelector('#screen');await cancelOverlay.keyboard.press('Escape').catch(e=>{if(!cancelOverlay.isClosed())throw e;});assert.equal(await cancelled,null);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,count);
   results.push({id:d.id,scale:d.scale,screen:whole.size,region:crop.size,cancel:true,isolatedPreload:true});
  }
  const invalid=await page.evaluate(()=>window.clip.screenshot('screen',-999).catch(e=>e.message));assert.match(invalid,/断开/);
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIP_PACKAGED_EXE,displays:results},null,2));
 }finally{if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
