const {chromium,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
function prepare(){
 const parent='00000000-0000-4000-8000-000000000001',legacy='00000000-0000-4000-8000-000000000002';
 fixture.state.categories=[{id:parent,name:'Parent',color:'#7b8e9c',manual:true,allowChildren:true,kind:'all',contains:'',source:'',tag:''},{id:legacy,name:'Legacy',color:'#7b8e9c',kind:'text',contains:'',source:'',tag:''}];fixture.state.settings.maxHistoryMiB=1024;
 clipper.category=async value=>{fixture.calls.push(['category',structuredClone(value)]);const saved={...value,id:value.id||'00000000-0000-4000-8000-000000000003'},index=fixture.state.categories.findIndex(item=>item.id===saved.id);if(index<0)fixture.state.categories.push(saved);else fixture.state.categories[index]=saved;return saved.id;};
 clipper.categoryCounts=async()=>Object.fromEntries(fixture.state.categories.map(category=>[category.id,category.manual?0:fixture.state.clips.filter(item=>category.kind==='all'||item.kind===category.kind).length]));
 fixture.eyeDropperMode='pick';fixture.eyeDropperCalls=0;window.EyeDropper=class{async open({signal}){fixture.eyeDropperCalls++;if(fixture.eyeDropperMode==='cancel')throw new DOMException('Canceled','AbortError');if(signal.aborted)throw new DOMException('Canceled','AbortError');return {sRGBHex:'#21b5c4'};}};
}
(async()=>{
 const output=path.resolve('work/development/category-form');await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
 try{for(const [language,width,height,scale,dark]of [['zh-CN',1476,976,100,false],['en',900,720,125,true],['en',560,640,125,false]]){
  const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await context.addInitScript({content:`(${setup.toString()})(${JSON.stringify(language)});(${extra.toString()})();(${prepare.toString()})();fixture.state.dark=${dark};fixture.state.settings.theme=${JSON.stringify(dark?'dark':'light')};fixture.appearance({...fixture.value(),scale:${scale}});`});
  await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto('https://clipper.test/index.html');await expect(page.locator('[data-category="00000000-0000-4000-8000-000000000002"] small')).toHaveText('1');await page.locator('#add-category').click();await expect(page.locator('#category-name')).toBeFocused();await expect(page.locator('[data-category-mode],.category-rule-card,.category-builder .tabs')).toHaveCount(0);await expect(page.locator('#category-mode-trigger')).toBeVisible();
  await page.locator('#category-name').fill('Test category');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#modal-error')).toContainText(language==='en'?'Specify at least one':'至少指定一个');assert(await page.locator('#modal-error').evaluate(node=>{const s=getComputedStyle(node);return s.borderTopWidth==='1px'&&s.backgroundColor!=='rgba(0, 0, 0, 0)'&&getComputedStyle(node,'::before').content!=='none';}));await page.screenshot({path:path.join(output,language+'-'+width+'-feedback.png')});await page.locator('#category-contains').fill('Example');await expect(page.locator('#modal-error')).toBeEmpty();await page.locator('#category-contains').fill('');
  await page.locator('#category-icon-trigger').click();await expect(page.locator('#category-icon-panel:popover-open')).toBeVisible();await expect(page.locator('.category-icon-grid')).not.toHaveAttribute('aria-busy','true');assert.equal(await page.locator('[data-category-icon]').count(),120);await page.locator('.category-icon-scroll').evaluate(node=>node.scrollTop=node.scrollHeight);await expect.poll(()=>page.locator('[data-category-icon]').count()).toBeGreaterThan(120);await page.locator('.category-icon-search input').fill('no-such-icon');await expect(page.locator('.category-icon-empty')).toBeVisible();await page.locator('.category-icon-search input').fill('star');await page.locator('[data-category-icon=star]').click();await expect(page.locator('#category-icon-trigger')).toHaveAttribute('data-icon','star');await expect(page.locator('#category-icon-trigger')).toBeFocused();await page.locator('#category-icon-trigger').click();await page.keyboard.press('Escape');await expect(page.locator('#dialog')).toBeVisible();await expect(page.locator('#category-icon-trigger')).toBeFocused();await page.locator('#category-icon-trigger').click();await page.locator('.category-icon-search input').fill('alarm clock check');await page.locator('[data-category-icon=alarm-clock-check]').click();await expect(page.locator('#category-icon-trigger')).toHaveAttribute('data-icon','alarm-clock-check');
  const choose=async(id,value)=>{await page.locator('#'+id).evaluate((select,value)=>{select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));},value);};
  const colors=await page.locator('[data-category-color]').evaluateAll(nodes=>nodes.map(node=>node.dataset.categoryColor));assert.equal(new Set(colors).size,7);assert(colors.includes('#ef4444')&&colors.includes('#3b82f6')&&colors.includes('#f59e0b'));await expect(page.locator('[data-category-color][aria-pressed=true]')).toHaveCount(1);
  assert(await page.locator('.category-colors').evaluate(node=>{const r=node.querySelector(':scope>span').getBoundingClientRect(),name=document.querySelector('label[for=category-name]').getBoundingClientRect(),parent=document.querySelector('label[for=category-parent]').getBoundingClientRect();return Math.abs(r.left-name.left)<1&&Math.abs(r.left-parent.left)<1;}));
  await page.locator('[data-category-color="#ef4444"]').click();await expect(page.locator('#category-color')).toHaveValue('#ef4444');await expect(page.locator('[data-category-color="#ef4444"]')).toHaveAttribute('aria-pressed','true');await page.locator('#category-color-trigger').click();await expect(page.locator('#category-color-panel:popover-open')).toBeVisible();assert(await page.locator('#category-color-panel').evaluate(node=>!!node.closest('dialog[open]')),'The color picker must remain interactive inside the modal');
  await page.locator('#category-color-panel .color-picker-hex input').fill('#321fed');await expect(page.locator('#category-color')).toHaveValue('#321fed');await expect(page.locator('[data-category-color][aria-pressed=true]')).toHaveCount(0);await expect(page.locator('#category-color-trigger')).toHaveClass(/chosen/);await page.screenshot({path:path.join(output,language+'-'+width+'-color.png')});await page.keyboard.press('Escape');await expect(page.locator('#dialog')).toBeVisible();await expect(page.locator('#category-color-trigger')).toBeFocused();
  await page.locator('#category-color-trigger').click();await page.locator('.color-picker-eyedropper').click();await expect(page.locator('#category-color')).toHaveValue('#21b5c4');await page.evaluate(()=>fixture.eyeDropperMode='cancel');await page.locator('#category-color-trigger').click();await page.locator('.color-picker-eyedropper').click();await expect(page.locator('#category-color')).toHaveValue('#21b5c4');assert.equal(await page.evaluate(()=>fixture.eyeDropperCalls),2);
  await page.locator('#category-mode-trigger').click();await page.locator('.select-popup [role=option]').filter({hasText:language==='en'?'Manual':'手动整理'}).click();await expect(page.locator('#category-dynamic-rules')).toBeHidden();await expect(page.locator('#category-manual-help')).toBeVisible();await choose('category-mode','dynamic');await expect(page.locator('#category-dynamic-rules')).toBeVisible();
  await page.locator('#category-name').fill('Saved category');await choose('category-parent','00000000-0000-4000-8000-000000000001');await choose('category-kind','files');await choose('category-period','custom');await expect(page.locator('#category-custom-dates')).toBeVisible();
  await page.locator('#category-from').evaluate(input=>input.value='2026-10-01');await page.locator('#category-to').evaluate(input=>input.value='2026-10-07');await page.locator('#category-custom-dates .clipper-date-trigger').first().scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.locator('#category-custom-dates .clipper-date-trigger').first().click();await expect(page.locator('.clipper-calendar:popover-open')).toBeVisible();await page.locator('[data-calendar-day="2026-10-01"]').click();await page.locator('#category-contains').fill('Invoice [0-9]{4}');await page.locator('#category-regex').check();await page.locator('#category-source').fill('Explorer');await page.locator('#category-tag').fill('Work');await page.locator('.category-status-option').filter({hasText:language==='en'?'Favorited':'已收藏'}).click();await page.locator('.category-status-option').filter({hasText:language==='en'?'Pinned':'已置顶'}).click();await page.locator('#category-extensions').fill('PDF, .docx');await choose('category-size','small');await page.locator('#category-permanent').check();await page.locator('#category-children').check();
  await page.locator('#category-size-trigger').scrollIntoViewIfNeeded();assert(await page.locator('.category-builder').evaluate(node=>node.scrollWidth<=node.clientWidth+1));assert(await page.locator('#dialog').evaluate(node=>{const r=node.getBoundingClientRect(),save=node.querySelector('[type=submit]').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&save.bottom<=r.bottom&&save.top>=r.top;}));if(language==='en')assert(!/[\u4e00-\u9fff]/.test(await page.locator('.category-builder').innerText()));await page.screenshot({path:path.join(output,language+'-'+width+'-rules.png')});
  await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible();const saved=await page.evaluate(()=>fixture.calls.filter(([name])=>name==='category').at(-1)[1]);assert.equal(saved.icon,'alarm-clock-check');assert.equal(saved.color,'#21b5c4');assert.equal(saved.kind,'files');assert.equal(saved.contains,'Invoice [0-9]{4}');assert.equal(saved.containsRegex,true);assert.equal(saved.favorite,true);assert.equal(saved.pinned,true);assert.equal(saved.period,'custom');assert.deepEqual(saved.extensions,['pdf','docx']);assert.equal(saved.from,'2026-10-01');assert.equal(saved.to,'2026-10-07');assert.equal(saved.parentId,'00000000-0000-4000-8000-000000000001');
  await expect(page.locator('[data-category="00000000-0000-4000-8000-000000000003"] [data-category-glyph=alarm-clock-check]')).toBeVisible();await page.locator('#sidebar-toggle').click();await expect(page.locator('#categories')).toBeVisible();await expect.poll(async()=> (await page.locator('#categories').boundingBox()).width).toBeLessThanOrEqual(44);assert(await page.locator('#categories').evaluate(node=>{const s=getComputedStyle(node),r=node.getBoundingClientRect();return s.borderTopWidth==='1px'&&r.width<=44;}));for(const button of await page.locator('#categories [data-category]').all()){await expect(button).toBeVisible();assert(await button.evaluate(node=>{const r=node.getBoundingClientRect(),icon=node.querySelector('.icon').getBoundingClientRect();return Math.abs((r.left+r.right)/2-(icon.left+icon.right)/2)<1;}));}await page.screenshot({path:path.join(output,language+'-'+width+'-collapsed.png')});await page.locator('#sidebar-toggle').click();
  await page.locator('[data-category="00000000-0000-4000-8000-000000000003"]').click();await page.locator('#collection-more-toggle').click();await page.locator('#edit-category').click();await expect(page.locator('#category-color')).toHaveValue('#21b5c4');await expect(page.locator('#category-icon-trigger')).toHaveAttribute('data-icon','alarm-clock-check');await expect(page.locator('#category-kind')).toHaveValue('files');await expect(page.locator('#category-period')).toHaveValue('custom');await expect(page.locator('#category-regex')).toBeChecked();await expect(page.locator('#category-favorite')).toBeChecked();await choose('category-mode','manual');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible();const manual=await page.evaluate(()=>fixture.calls.filter(([name])=>name==='category').at(-1)[1]);assert.equal(manual.manual,true);assert.equal(manual.kind,'all');assert.equal(manual.contains,'');assert.equal(manual.favorite,undefined);assert.equal(manual.period,undefined);assert.deepEqual(manual.extensions,[]);
  await page.locator('#manage-categories').click();await expect(page.locator('[data-category-move]')).toHaveCount(0);const beforeOrder=await page.locator('.category-order-row').evaluateAll(rows=>rows.map(row=>row.dataset.categoryOrder));await page.locator('.category-order-grip').nth(1).focus();await page.keyboard.press('Alt+ArrowUp');await expect.poll(()=>page.locator('.category-order-row').first().getAttribute('data-category-order')).toBe(beforeOrder[1]);await page.screenshot({path:path.join(output,language+'-'+width+'-manage.png')});await page.locator('#modal-cancel').click();
  await page.locator('[data-category="00000000-0000-4000-8000-000000000002"]').click();await page.locator('#collection-more-toggle').click();await page.locator('#edit-category').click();await expect(page.locator('#category-color')).toHaveValue('#7b8e9c');await expect(page.locator('#category-color-trigger')).toHaveClass(/chosen/);await page.locator('#category-color-trigger').click();await page.locator('#modal-close').click();await expect(page.locator('#category-color-panel:popover-open')).toHaveCount(0);await page.locator('#add-category').click();await expect(page.locator('#category-color-panel')).toHaveCount(1);await page.locator('#modal-cancel').click();await context.close();
 }assert.deepEqual(errors,[]);console.log('PASS: aligned category fields, distinct palette/custom picker, simulated screen picking/cancel, modal keyboard/lifecycle, automatic/manual switch, rule/save/edit/legacy color and icon preservation, inline validation feedback and collapsed category navigation and responsive Chinese/light + English/dark/125% layouts');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
