const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupData}=require('./language-data-fixture.cjs'),{checkpoints}=require('./checkpoint-fixture.cjs');
const result=[],errors=[];
(async()=>{await fs.mkdir('work/checkpoints',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});try{
 for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){const context=await browser.newContext({viewport:{width:1240,height:780},colorScheme:theme});await context.addInitScript(setup,language);await context.addInitScript(setupData);await context.addInitScript(checkpoints);await context.addInitScript(theme=>fixture.state.dark=theme==='dark',theme);await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const call=async(name,count=1)=>page.waitForFunction(({name,count})=>fixture.pointCalls.filter(c=>c[0]===name).length>=count,{name,count});
 const count=async name=>page.evaluate(name=>fixture.pointCalls.filter(c=>c[0]===name).length,name);
 const start=async()=>{await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');await page.locator('[data-page="settings"]').click();await page.waitForSelector('.settings-nav [data-section="9"]');await page.locator('.settings-nav [data-section="9"]').click();await page.waitForSelector('[data-checkpoint-restore]');};
 const geometry=async name=>{for(const [w,h,scale]of [[1240,780,100],[860,600,150],[700,600,150]]){await page.setViewportSize({width:w,height:h});await page.evaluate(scale=>fixture.appearance({font:'system',scale,density:'comfortable'}),scale);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const value=await page.evaluate(()=>{const visible=e=>!!e.getClientRects().length;const root=document.querySelector('dialog[open]')||document.getElementById('content')||document.querySelector('main');const nav=root.querySelector('.section-nav'),active=nav?.querySelector('[aria-current=page]'),n=nav?.getBoundingClientRect(),a=active?.getBoundingClientRect();return {selectedCategoryVisible:!n||!a||a.left>=n.left-1&&a.right<=n.right+1&&a.top>=n.top-1&&a.bottom<=n.bottom+1,bodyFits:document.body.scrollWidth<=innerWidth+1,rootFits:root.scrollWidth<=root.clientWidth+1,offscreen:[...root.querySelectorAll('button,input')].filter(visible).filter(e=>!e.closest('.section-nav')).filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1;}).map(e=>({id:e.id,text:e.textContent,rect:e.getBoundingClientRect().toJSON(),parent:e.parentElement.className}))};});assert(value.selectedCategoryVisible,name+': selected category hidden');assert(value.bodyFits,name+': body overflow');assert(value.rootFits,name+': root overflow');assert.deepEqual(value.offscreen,[],name+':'+w+':'+scale);result.push({language,theme,name,w,h,scale,value});}await page.setViewportSize({width:1240,height:780});await page.evaluate(()=>fixture.appearance({font:'system',scale:100,density:'comfortable'}));};
 await start();assert.equal(await page.locator('.checkpoint-entry').count(),3);assert.equal(await page.locator('[data-checkpoint-restore]').nth(2).isDisabled(),true);if(language==='en')assert.equal(await page.locator('#checkpoint-create').textContent(),'Create checkpoint');await geometry('list');if(language==='zh-CN'&&theme==='light')await page.screenshot({path:'work/checkpoints/data-preview.png'});
 await page.locator('#checkpoint-create').click();await call('create');await page.waitForFunction(()=>document.querySelectorAll('.checkpoint-entry').length===4);
 await page.locator('[data-checkpoint-delete]').last().click();assert.equal(await page.getByRole('dialog',{name:await page.locator('#modal-title').innerText()}).count(),1);await page.locator('#modal-cancel').click();assert.equal(await count('delete'),0);await page.locator('[data-checkpoint-delete]').last().click();await page.locator('dialog [type=submit]').click();await call('delete');await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.equal(await page.locator('.checkpoint-entry').count(),3);
 // Encrypted checkpoint credentials, explicit key mode, preview cancellation and password wipe.
 await page.locator('[data-checkpoint-restore]').nth(1).click();await page.waitForSelector('#checkpoint-password');assert.equal(await page.locator('#checkpoint-password').evaluate(node=>node===document.activeElement),true);assert.equal(await page.locator('#injected-point').count(),0);await geometry('unlock');const password=await page.locator('#checkpoint-password').elementHandle();await page.locator('#checkpoint-password').fill('C7-TEST-RECOVERY-KEY');await page.locator('#checkpoint-use-key').check();await page.locator('dialog [type=submit]').click();await page.waitForSelector('.restore-summary');assert.equal(await password.evaluate(n=>n.value),'');await password.dispose();const args=await page.evaluate(()=>fixture.pointCalls.find(c=>c[0]==='preview'));assert.equal(args[4],'recovery');await geometry('preview');await page.locator('#modal-cancel').click();await call('cancel');assert.equal(await count('restore'),0);
 // Plain checkpoint into protected history requires a matching password and saved key.
 await page.locator('[data-checkpoint-restore]').first().click();await page.waitForSelector('#checkpoint-new-password');await page.locator('#checkpoint-new-password').fill('checkpoint fixture password');await page.locator('#checkpoint-repeat').fill('not matching');const before=await count('preview');await page.locator('dialog [type=submit]').click();assert.equal(await count('preview'),before);await page.locator('#checkpoint-repeat').fill('checkpoint fixture password');const newPassword=await page.locator('#checkpoint-new-password').elementHandle();await page.locator('dialog [type=submit]').click();await page.waitForSelector('#checkpoint-proof');assert.equal(await newPassword.evaluate(n=>n.value),'');await newPassword.dispose();await geometry('new-key');assert.equal(await page.locator('#injected-point').count(),0);const key=await page.locator('#checkpoint-recovery-key').elementHandle();await page.locator('#checkpoint-proof').fill('C7-POINT-FIXTURE-ONLY-DO-NOT-USE');await page.locator('dialog [type=submit]').click();await call('restore');await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.equal(await key.evaluate(n=>n.textContent),'');await key.dispose();assert.equal(await page.evaluate(()=>fixture.state.settings.paused),true);
 // Startup recovery uses the same chosen checkpoint and keeps incompatible buttons disabled.
 await page.goto('https://clip.test/recovery.html');await page.waitForSelector('[data-startup-checkpoint]');assert.equal(await page.locator('[data-startup-checkpoint]').nth(2).isDisabled(),true);await geometry('startup-list');await page.locator('[data-startup-checkpoint]').nth(1).click();await page.waitForSelector('#password');await page.locator('#password').fill('startup fixture password');await page.locator('#unlock button').click();await page.waitForFunction(()=>!document.getElementById('summary').hidden);await geometry('startup-preview');if(language==='zh-CN'&&theme==='light')await page.screenshot({path:'work/checkpoints/startup-preview.png'});await page.locator('#cancel').click();await page.waitForFunction(()=>!document.getElementById('choices').hidden);assert.equal(await page.locator('[data-startup-checkpoint]').nth(2).isDisabled(),true);
 await context.close();}
 assert.deepEqual(errors,[]);await fs.writeFile('work/checkpoints/ui-results.json',JSON.stringify({scope:'Built renderers with isolated synthetic IPC, no system clipboard or input',cases:result.length,errors,result},null,2));console.log(JSON.stringify({cases:result.length,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
