const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto');
const {Store,StorageManager,CheckpointManager,CheckpointRecovery,RecoveryManager,HistoryVault,openDatabase,recoveryJob,cancelRecoveryJobs,setInterfaceLanguage}=require('../work/test-exports.cjs');
const currentVersion=require('../package.json').version;
const folder=()=>generated.mkdtemp(path.resolve('work/checkpoint-'));
const sha=async file=>createHash('sha256').update(await fs.readFile(file)).digest('hex');
async function source(encrypted=false){const root=await folder(),id=randomUUID(),vault=new HistoryVault(),protection=encrypted?await vault.prepare('checkpoint fixture password'):undefined;if(protection)await fs.writeFile(path.join(root,'history-vault.json'),JSON.stringify(protection.record));const store=new Store(path.join(root,'history.sqlite'),false,false,protection?.key);store.setMeta('profile-id',id);store.setMeta('application-version','0.24.0');return {root,id,store,protection};}
test('startup checkpoints before schema migration, pruning and version writes; a matching restart creates no duplicate',async()=>{
 const s=await source();s.store.add({text:'old unpinned data retained in checkpoint'},'fixture',undefined,undefined,false);s.store.setMeta('settings',{...s.store.settings,maxItems:50,retentionDays:1});s.store.db.exec('PRAGMA user_version=2');s.store.db.exec("UPDATE clips SET updated=1,data=json_set(data,'$.updatedAt',1,'$.createdAt',1)");s.store.close();const old=await sha(path.join(s.root,'history.sqlite'));
 const manager=new StorageManager(s.root),store=await manager.start(),points=await manager.checkpoints.list(manager.profileId);assert.equal(points.length,1);assert.equal(points[0].schema,2);assert.equal(points[0].sourceVersion,'0.24.0');assert.equal(points[0].targetVersion,currentVersion);const point=await manager.checkpoints.verify(points[0].id,s.id),raw=openDatabase(path.join(point.directory,'history.sqlite'),true);assert.equal(raw.prepare('PRAGMA user_version').get().user_version,2);assert.equal(raw.prepare('SELECT count(*) AS n FROM clips').get().n,1);assert.equal(JSON.parse(raw.prepare("SELECT value FROM meta WHERE key='application-version'").get().value),'0.24.0');raw.close();assert.equal(store.list().length,0);assert.equal(store.meta('application-version',''),currentVersion);store.close();assert.notEqual(await sha(path.join(s.root,'history.sqlite')),old);
 const restarted=new StorageManager(s.root);(await restarted.start()).close();assert.equal((await restarted.checkpoints.list(s.id)).length,1);
});
test('fresh history has no empty checkpoint; missing pointed database never creates a replacement',async()=>{
 const root=await folder(),manager=new StorageManager(root);(await manager.start()).close();assert.equal((await manager.checkpoints.list()).length,0);await fs.unlink(path.join(root,'history.sqlite'));const pointer=await fs.readFile(path.join(root,'storage-location.json'),'utf8');await assert.rejects(()=>new StorageManager(root).start(),/缺失/);assert.equal(await fs.readFile(path.join(root,'storage-location.json'),'utf8'),pointer);await assert.rejects(()=>fs.stat(path.join(root,'history.sqlite')));
});
test('failed checkpoint blocks startup without changing the original database or pointer',async()=>{
 const root=await folder(),old=new StorageManager(root,undefined,'0.24.0');const store=await old.start();store.add({text:'keep before failed upgrade'},'fixture');store.close();const before=await sha(path.join(root,'history.sqlite')),pointer=await fs.readFile(path.join(root,'storage-location.json'),'utf8'),manager=new StorageManager(root);manager.checkpoints.create=async()=>{throw new Error('fixture disk failure');};await assert.rejects(()=>manager.start(),/fixture disk failure/);assert.equal(await sha(path.join(root,'history.sqlite')),before);assert.equal(await fs.readFile(path.join(root,'storage-location.json'),'utf8'),pointer);
});
test('snapshot includes committed WAL, private configuration, extra tables, indexes and triggers in the exact original schema',async()=>{
 const s=await source(),root=await folder(),manager=new CheckpointManager(root),clip=s.store.add({text:'WAL snapshot content'},'fixture');s.store.setQueue([clip.id]);s.store.setMeta('ai-profiles',{key:'checkpoint-secret-fixture'});s.store.db.exec("CREATE TABLE custom(key TEXT PRIMARY KEY,value TEXT);CREATE INDEX custom_value ON custom(value);CREATE TRIGGER custom_copy AFTER INSERT ON custom BEGIN UPDATE custom SET value=value||' trigger' WHERE key=NEW.key;END;INSERT INTO custom VALUES('x','extra');PRAGMA user_version=3");
 const before=s.store.backup(),point=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual');assert.equal(point.schema,3);const info=await manager.verify(point.id,s.id),raw=openDatabase(path.join(info.directory,'history.sqlite'),true);assert.equal(raw.prepare('SELECT value FROM custom').get().value,'extra trigger');assert.equal(raw.prepare("SELECT count(*) AS n FROM sqlite_master WHERE name IN ('custom_value','custom_copy')").get().n,2);assert.equal(raw.prepare('PRAGMA user_version').get().user_version,3);assert.equal(raw.prepare('PRAGMA journal_mode').get().journal_mode,'delete');raw.close();const readonly=new Store(path.join(info.directory,'history.sqlite'),false,true);const restored=readonly.backup();assert.deepEqual({...restored,exportedAt:before.exportedAt},before);assert.equal(readonly.meta('ai-profiles',{}).key,'checkpoint-secret-fixture');assert.deepEqual(readonly.queue,[clip.id]);readonly.close();s.store.close();await manager.verify(point.id,s.id);
});
test('encrypted snapshot stays encrypted and readable with original password and recovery key',async()=>{
 const s=await source(true),root=await folder(),manager=new CheckpointManager(root);s.store.add({text:'UNIQUE_CHECKPOINT_PRIVATE_CONTENT'},'fixture');s.store.db.exec('PRAGMA user_version=4');const point=await manager.create(s.root,s.id,'0.24.0','0.25.0','upgrade',s.protection.key);assert.equal(point.encrypted,true);assert.equal(point.schema,4);const dir=(await manager.verify(point.id,s.id)).directory;assert.equal((await fs.readFile(path.join(dir,'history.sqlite'))).includes(Buffer.from('UNIQUE_CHECKPOINT_PRIVATE_CONTENT')),false);assert.deepEqual(JSON.parse(await fs.readFile(path.join(dir,'history-vault.json'),'utf8')),s.protection.record);
 for(const [value,mode]of [['checkpoint fixture password','password'],[s.protection.recoveryKey,'recovery']]){const vault=new HistoryVault();await vault.load(dir);await vault.unlock(value,mode);const key=vault.copyKey();const db=openDatabase(path.join(dir,'history.sqlite'),true,key);assert.equal(db.prepare('PRAGMA user_version').get().user_version,4);db.close();key.fill(0);vault.lock();}s.store.close();s.protection.key.fill(0);
});
test('wrong keys and cancellation leave no committed or pending checkpoint',async()=>{
 const s=await source(true),root=await folder(),manager=new CheckpointManager(root);await assert.rejects(()=>manager.create(s.root,s.id,'0.24.0','0.25.0','manual',Buffer.alloc(32,88)));await assert.rejects(()=>manager.create(s.root,s.id,'0.24.0','0.25.0','manual',s.protection.key,()=>false),/取消/);assert.deepEqual(await fs.readdir(manager.root),[]);s.store.close();s.protection.key.fill(0);
});
test('only the three latest automatic upgrade points are retained; manual points and other profiles survive',async()=>{
 const s=await source(),root=await folder(),manager=new CheckpointManager(root),manual=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual');const foreign=await source(),other=await manager.create(foreign.root,foreign.id,'0.24.0','0.25.0','upgrade');for(const version of ['0.25.0','0.26.0','0.27.0','0.28.0'])await manager.create(s.root,s.id,'0.24.0',version,'upgrade');const points=await manager.list(s.id);assert.equal(points.filter(p=>p.reason==='upgrade').length,3);assert(points.some(p=>p.id===manual.id));assert.equal((await manager.list(foreign.id))[0].id,other.id);assert.equal(points.some(p=>p.targetVersion==='0.25.0'&&p.reason==='upgrade'),false);s.store.close();foreign.store.close();
});
test('changed checksums, unknown files, foreign IDs and links are refused without deleting any data',async()=>{
 const s=await source(),root=await folder(),manager=new CheckpointManager(root),point=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual'),dir=path.join(manager.root,point.id),file=path.join(dir,'history.sqlite'),before=await fs.readFile(file);await assert.rejects(()=>manager.verify('../history.sqlite'));await assert.rejects(()=>manager.remove(point.id,randomUUID()),/不属于/);await fs.writeFile(path.join(dir,'history.sqlite-wal'),'unrecognized WAL');await assert.rejects(()=>manager.verify(point.id),/其他文件/);await assert.rejects(()=>manager.remove(point.id,s.id),/其他文件/);await fs.unlink(path.join(dir,'history.sqlite-wal'));await fs.appendFile(file,'altered');await assert.rejects(()=>manager.remove(point.id,s.id),/改变/);assert(await fs.stat(file));await fs.writeFile(file,before);const external=await folder(),externalFile=path.join(external,'keep.txt');await fs.writeFile(externalFile,'keep');await fs.rename(dir,dir+'.preserved');await fs.symlink(external,dir,'junction');await assert.rejects(()=>manager.verify(point.id),/链接/);assert.equal(await fs.readFile(externalFile,'utf8'),'keep');await fs.unlink(dir);await fs.rename(dir+'.preserved',dir);await manager.remove(point.id,s.id);await assert.rejects(()=>fs.stat(dir));s.store.close();
});
test('checkpoint recovery copies into a paused branch; checkpoint and current history remain intact',async()=>{
 const root=await folder(),manager=new StorageManager(root),current=await manager.start(),clip=current.add({text:'recover original data'},'fixture');current.setMeta('automatic-backup',{enabled:true});current.setMeta('lan-config',{enabled:true,peers:[{id:'fixture'}]});const point=await manager.checkpoint(),dir=(await manager.checkpoints.verify(point.id,manager.profileId)).directory,hash=await sha(path.join(dir,'history.sqlite'));current.add({text:'keep newer source'},'fixture');const old=manager.directory,recovery=new RecoveryManager(manager),choice=await recovery.choose('database',dir),preview=await recovery.preview(choice.token);assert.equal(preview.clips,1);const next=await recovery.commit(choice.token);assert.notEqual(manager.directory,old);assert.equal(next.list().length,1);assert.equal(next.get(clip.id).payload.text,'recover original data');assert.equal(next.settings.paused,true);assert.equal(next.meta('automatic-backup',{}).enabled,false);assert.equal(next.meta('lan-config',{}).enabled,false);assert.equal(current.list().length,2);assert.equal(await sha(path.join(dir,'history.sqlite')),hash);next.close();current.close();await manager.checkpoints.verify(point.id,manager.profileId);
});
test('restoring plaintext into protected history requires a fresh password and never stores a plaintext database',async()=>{
 const root=await folder(),manager=new StorageManager(root),old=await manager.start();old.add({text:'RESTORE_PRIVATE_MARKER'},'fixture');const point=await manager.checkpoint(),dir=(await manager.checkpoints.verify(point.id,manager.profileId)).directory,p=await manager.prepareEncryption('fresh fixture vault password'),encrypted=await manager.encrypt(p.token,p.recoveryKey),recovery=new RecoveryManager(manager),choice=await recovery.choose('database',dir);assert.equal(choice.requiresProtection,true);await assert.rejects(()=>recovery.preview(choice.token),/设置/);const preview=await recovery.preview(choice.token,undefined,'restored fixture password');await assert.rejects(()=>recovery.commit(choice.token,'wrong'),/恢复密钥/);const next=await recovery.commit(choice.token,preview.recoveryKey);assert.equal(manager.vault.state().encrypted,true);next.close();encrypted.close();assert.equal((await fs.readFile(path.join(manager.directory,'history.sqlite'))).includes(Buffer.from('RESTORE_PRIVATE_MARKER')),false);const vault=new HistoryVault();await vault.load(manager.directory);await vault.unlock('restored fixture password','password');vault.lock();
});
test('cancelled recovery and a changed destination/protection cannot commit an old preview',async()=>{
 const s=await source(),root=await folder(),manager=new StorageManager(root);const current=await manager.start(),recovery=new RecoveryManager(manager);const choosing=recovery.choose('database',s.root);recovery.cancel();await assert.rejects(()=>choosing,/过期/);const choice=await recovery.choose('database',s.root);await recovery.preview(choice.token);const pointer=await fs.readFile(path.join(root,'storage-location.json'),'utf8');const committing=recovery.commit(choice.token);recovery.cancel();await assert.rejects(()=>committing,/过期/);assert.equal(await fs.readFile(path.join(root,'storage-location.json'),'utf8'),pointer);assert.equal((await fs.readdir(root)).filter(n=>n.startsWith('recovered-')).length,0);const another=await recovery.choose('database',s.root);await recovery.preview(another.token);manager.directory=path.join(root,'different');await assert.rejects(()=>recovery.commit(another.token),/过期/);current.close();s.store.close();
});
test('large snapshot, validation and copying keep the main event loop responsive; worker timeout releases handles',async()=>{
 const s=await source(),root=await folder(),manager=new CheckpointManager(root);for(let i=0;i<64;i++)s.store.add({text:i+'-'+'x'.repeat(900000)},'fixture',undefined,undefined,false);let ticks=0;const timer=setInterval(()=>ticks++,10);try{const point=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual');assert(ticks>5);const before=ticks,dir=(await manager.verify(point.id,s.id)).directory;await recoveryJob({operation:'copy',source:path.join(dir,'history.sqlite'),file:path.join(root,'copy.sqlite')});assert(ticks-before>5);await assert.rejects(()=>recoveryJob({operation:'inspect',source:path.join(s.root,'history.sqlite')},path.resolve('work/recovery-worker.cjs'),1),/取消或超时/);const pending=recoveryJob({operation:'inspect',source:path.join(s.root,'history.sqlite')});cancelRecoveryJobs();await assert.rejects(()=>pending,/取消或超时/);const retry=await recoveryJob({operation:'inspect',source:path.join(s.root,'history.sqlite')});assert.equal(retry.clips,64);await fs.writeFile(path.join(root,'responsiveness.json'),JSON.stringify({records:64,bytes:point.bytes,eventLoopTicks:ticks,copyCompleted:true}));}finally{clearInterval(timer);s.store.close();}
});
test('pre-install and startup automatic checkpoints share the retention cap; manual data survives',async()=>{const s=await source(),root=await folder(),manager=new CheckpointManager(root);const manual=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual');for(const [version,reason]of [['0.25.0','update'],['0.25.0','upgrade'],['0.26.0','update'],['0.26.0','upgrade']])await manager.create(s.root,s.id,'0.24.0',version,reason);const points=await manager.list(s.id);assert.equal(points.filter(p=>p.reason!=='manual').length,3);assert(points.some(p=>p.id===manual.id));s.store.close();});
test('a live WAL writer can continue while a checkpoint keeps one consistent transaction',async()=>{const s=await source(),root=await folder(),manager=new CheckpointManager(root);s.store.db.exec('CREATE TABLE revision(value INTEGER);INSERT INTO revision VALUES(0)');s.store.setMeta('snapshot-revision',0);let revision=0;const timer=setInterval(()=>{s.store.db.exec('BEGIN');try{s.store.db.prepare('UPDATE revision SET value=?').run(++revision);s.store.setMeta('snapshot-revision',revision);s.store.db.exec('COMMIT');}catch(e){s.store.db.exec('ROLLBACK');throw e;}},5);try{const point=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual');assert(revision>0);const dir=(await manager.verify(point.id,s.id)).directory,db=openDatabase(path.join(dir,'history.sqlite'),true);const captured=db.prepare('SELECT value FROM revision').get().value;assert.equal(JSON.parse(db.prepare("SELECT value FROM meta WHERE key='snapshot-revision'").get().value),captured);assert(captured<=revision);db.close();}finally{clearInterval(timer);s.store.close();}});
test('checkpoint service refuses changed files after choosing or previewing and preserves the pointer',async()=>{const root=await folder(),storage=new StorageManager(root),store=await storage.start();store.add({text:'immutable original'},'fixture');const point=await storage.checkpoint(),service=new CheckpointRecovery(storage),file=path.join(storage.checkpoints.root,point.id,'history.sqlite'),original=await fs.readFile(file),pointer=await fs.readFile(path.join(root,'storage-location.json'),'utf8');let choice=await service.choose(point.id);await fs.appendFile(file,'changed');await assert.rejects(()=>service.preview(choice.token),/改变/);await fs.writeFile(file,original);await assert.rejects(()=>service.preview(choice.token),/过期/);choice=await service.choose(point.id);await service.preview(choice.token);await fs.appendFile(file,'changed again');await assert.rejects(()=>service.commit(choice.token),/改变/);assert.equal(await fs.readFile(path.join(root,'storage-location.json'),'utf8'),pointer);assert.equal(store.list().length,1);store.close();});
test('startup checkpoint service restores an encrypted foreign profile only when explicitly chosen',async()=>{const s=await source(true),root=await folder(),manager=new CheckpointManager(root);s.store.add({text:'ENCRYPTED_SERVICE_MARKER'},'fixture');const point=await manager.create(s.root,s.id,'0.24.0','0.25.0','manual',s.protection.key),storage=new StorageManager(root),empty=await storage.start(),service=new CheckpointRecovery(storage);await assert.rejects(()=>service.choose(point.id),/不属于/);const choice=await service.choose(point.id,false);await assert.rejects(()=>service.preview(choice.token,'bad password'));await assert.rejects(()=>service.preview(choice.token,s.protection.recoveryKey,undefined,'recovery'),/稍候/);await new Promise(resolve=>setTimeout(resolve,1550));const preview=await service.preview(choice.token,s.protection.recoveryKey,undefined,'recovery');assert.equal(preview.clips,1);const next=await service.commit(choice.token);assert.equal(storage.vault.state().encrypted,true);assert.equal(storage.vault.state().hello,false);assert.equal(next.settings.paused,true);assert.throws(()=>empty.list());next.close();assert.equal((await fs.readFile(path.join(storage.directory,'history.sqlite'))).includes(Buffer.from('ENCRYPTED_SERVICE_MARKER')),false);s.store.close();s.protection.key.fill(0);});
test('worker error messages follow the active interface language',async()=>{setInterfaceLanguage('en');try{await assert.rejects(()=>recoveryJob({operation:'unsupported'}),{message:'Invalid checkpoint operation'});}finally{setInterfaceLanguage('zh-CN');}});
