const {chromium}=require('@playwright/test'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),asar=require('@electron/asar');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs'),{prepare,probe,regressionProbe}=require('./chrome-044-fixture.cjs');
const archive=process.env.CLIPPER_CHROME_ASAR,baseline='E:/CodexWork/Clipper/2026-10-02/outputs/Clipper-0.43.0-win-x64/resources/app.asar',out='work/chrome-044';fs.mkdirSync(out,{recursive:true});let browser;
(async()=>{browser=await chromium.launch({channel:'msedge',headless:true});const results=[],regressions=[];
async function pageFor(language,theme,source,width=1280){const context=await browser.newContext({viewport:{width,height:800}});await context.addInitScript(setup,language);await context.addInitScript(extra);await context.addInitScript(prepare);await context.addInitScript(theme=>{fixture.state.dark=theme==='dark';fixture.state.settings.theme=theme;},theme);await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1),body=source?asar.extractFile(source,('dist/renderer/'+name).replaceAll('/','\\')):fs.readFileSync(path.join('dist/renderer',name));await route.fulfill({body,contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('.preview-body');return {context,page,errors};}
{const {context,page,errors}=await pageFor('zh-CN','light',baseline),before=await page.evaluate(regressionProbe);assert.deepEqual(before,{filterFocus:false,categoryFocus:false,batchLock:false,stackGroup:false});assert.deepEqual(errors,[]);regressions.push({baseline:'0.43.0',observations:before});await context.close();}
for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){const {context,page,errors}=await pageFor(language,theme,archive);const checks=await page.evaluate(probe);results.push(...checks.map(name=>({language,theme,name})));assert.deepEqual(errors,[]);await page.waitForSelector('#detail .preview-body');await page.waitForTimeout(250);await page.screenshot({path:out+'/'+language+'-'+theme+'-replies.png'});await context.close();}
for(const width of [840,1000,1440]){const {context,page,errors}=await pageFor('en','light',archive,width);const observations=await page.evaluate(async()=>{const frames=async()=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);},all=document.querySelector('[data-kind=all]'),code=document.querySelector('[data-kind=code]'),group=document.getElementById('filters'),toolbar=document.querySelector('.collection-toolbar'),search=document.getElementById('search');all.focus();all.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true,cancelable:true}));await frames();const r=code.getBoundingClientRect(),g=group.getBoundingClientRect(),css=getComputedStyle(search);return {focus:document.activeElement===code,retained:all===document.querySelector('[data-kind=all]'),visible:r.left>=g.left-1&&r.right<=g.right+1,body:document.body.scrollWidth<=innerWidth,inputBorder:css.borderTopWidth,search:search===document.getElementById('search')&&toolbar.contains(search)};});assert(observations.focus&&observations.retained&&observations.visible&&observations.body&&observations.search);assert.equal(observations.inputBorder,'0px');results.push({width,name:'Responsive segment keeps focus, overflow target, One search and page width',observations});assert.deepEqual(errors,[]);await page.waitForSelector('#detail .text-reader[data-ready=true]');await page.waitForTimeout(250);await page.screenshot({path:out+'/responsive-'+width+'.png'});await context.close();}
const report={passed:true,version:JSON.parse(fs.readFileSync('package.json')).version,packaged:!!archive,cases:results.length,results,regressions,physicalInput:false,systemClipboard:false,scope:'Real production renderer in private headless Edge, isolated fixture API. Reference controls are separately compared with pinned actual One styles; this suite checks application integration.'};fs.writeFileSync(out+(archive?'/packaged.json':'/results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,cases:results.length,regressions}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
