const {app,BrowserWindow,clipboard,ClipboardItem}=require('electron');
const koffi=require('koffi');
global.focusTarget=async()=>{
 global.helperWindow.setAlwaysOnTop(true,'screen-saver');global.helperWindow.show();global.helperWindow.focus();
 await new Promise(r=>setTimeout(r,150));
 const u=koffi.load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)');
 const bounds=global.helperWindow.getContentBounds(),point=require('electron').screen.dipToScreenPoint({x:bounds.x+200,y:bounds.y+150});
 for(const flags of [0xc001,0x0002,0x0004]){const input=Buffer.alloc(40);input.writeInt32LE(Math.round((point.x-metric(76))*65535/(metric(78)-1)),8);input.writeInt32LE(Math.round((point.y-metric(77))*65535/(metric(79)-1)),12);input.writeUInt32LE(flags,20);if(send(1,input,40)!==1)throw Error('Native target focus failed');}
 await new Promise(r=>setTimeout(r,150));
};
const rawUser=koffi.load('user32.dll'),rawKernel=koffi.load('kernel32.dll'),rawOpen=rawUser.func('bool __stdcall OpenClipboard(uintptr_t)'),rawClose=rawUser.func('bool __stdcall CloseClipboard()'),rawHas=rawUser.func('bool __stdcall IsClipboardFormatAvailable(uint32)'),rawRegister=rawUser.func('uint32 __stdcall RegisterClipboardFormatW(str16)'),rawGet=rawUser.func('uintptr_t __stdcall GetClipboardData(uint32)'),rawSet=rawUser.func('uintptr_t __stdcall SetClipboardData(uint32,uintptr_t)'),rawSize=rawKernel.func('uintptr_t __stdcall GlobalSize(uintptr_t)'),rawLock=rawKernel.func('void* __stdcall GlobalLock(uintptr_t)'),rawUnlock=rawKernel.func('bool __stdcall GlobalUnlock(uintptr_t)'),rawAlloc=rawKernel.func('uintptr_t __stdcall GlobalAlloc(uint32,uintptr_t)'),rawFree=rawKernel.func('uintptr_t __stdcall GlobalFree(uintptr_t)'),rawMove=rawKernel.func('void __stdcall RtlMoveMemory(void*,void*,uintptr_t)');
const openRaw=async()=>{for(let i=0;i<100;i++){if(rawOpen(0))return;await new Promise(r=>setTimeout(r,20));}throw Error('Original clipboard is busy');};
async function preserveRaw(){await openRaw();try{global.originalRaw=[];for(const name of [8,17,'PNG','HTML Format','Rich Text Format','JFIF','GIF','TIFF','image/jpeg','image/gif','image/webp','image/tiff','image/bmp']){const id=typeof name==='number'?name:rawRegister(name);if(!rawHas(id))continue;const h=rawGet(id),size=Number(rawSize(h));if(!h||!size)continue;if(size>256*1024*1024)throw Error('Original clipboard is too large for safe test restoration');const p=rawLock(h);if(!p)throw Error('Cannot preserve original clipboard');try{global.originalRaw.push({id,data:Buffer.from(koffi.decode(p,'uint8',size))});}finally{rawUnlock(h);}}}finally{rawClose();}}
global.restoreClipboard=async()=>{await clipboard.write(global.originalClipboard);await openRaw();try{for(const {id,data}of global.originalRaw){const h=rawAlloc(0x42,data.length);if(!h)throw Error('Cannot restore original clipboard');let transferred=false;try{const p=rawLock(h);if(!p)throw Error('Cannot restore original clipboard');try{rawMove(p,data,data.length);}finally{rawUnlock(h);}if(!rawSet(id,h))throw Error('Cannot restore original clipboard');transferred=true;}finally{if(!transferred)rawFree(h);}}}finally{rawClose();}};
app.setPath('userData',process.env.CLIP_HELPER_PROFILE);
app.whenReady().then(async()=>{await preserveRaw();global.originalClipboard=[];for(const item of await clipboard.read()){const data={};for(const type of item.types)data[type]=await item.getType(type);if(Object.keys(data).length)global.originalClipboard.push(new ClipboardItem(data));}global.helperWindow=new BrowserWindow({width:650,height:420,title:'Clip 测试目标',webPreferences:{preload:process.env.CLIP_FOLDER_RECEIVER==='1'?require('node:path').join(__dirname,'folder-drop-preload.cjs'):undefined,nodeIntegration:false,contextIsolation:true,sandbox:true}});await global.helperWindow.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<html lang="zh-CN"><title>Clip 测试目标</title><body><h2>Clip 粘贴验收</h2><textarea id="target" style="width:95%;height:200px"></textarea></body></html>'));});
