const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupText}=require('./language-text-fixture.cjs');
const output=process.env.CLIPPER_TEST_OUTPUT_DIR||path.resolve('work/current/codex-ui');
function setupCodex(){
 Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>fixture.calls.push(['copy-text',text])},configurable:true});
 fixture.codex={available:true,loggedIn:false,login:'idle'};fixture.ai.profiles.push({...fixture.ai.profiles[1],id:'codex',revision:'codex-revision',name:'Codex',kind:'codex',baseUrl:'codex://local',model:'',timeoutSeconds:300});fixture.ai.defaultId='codex';
 const base=window.clipper,call=(name,result)=>async()=>{fixture.calls.push([name]);return typeof result==='function'?result():result;},overrides={
  codexStatus:async()=>fixture.codex,codexLogin:call('codex-login',()=>fixture.codex={available:true,loggedIn:false,login:'pending',verificationUrl:'https://auth.openai.com/codex/device',userCode:'ABCD-1234'}),
  codexCancelLogin:call('codex-cancel',()=>fixture.codex={available:true,loggedIn:false,login:'idle'}),codexLogout:call('codex-logout',()=>fixture.codex={available:true,loggedIn:false,login:'idle'}),codexOpenLogin:call('codex-open'),
 };window.clipper=new Proxy(overrides,{get:(object,key)=>key in object?object[key]:base[key]});
}
(async()=>{await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],results=[];try{for(const language of ['zh-CN','en']){
 const context=await browser.newContext({viewport:{width:1366,height:900}});await context.addInitScript(setup,language);await context.addInitScript(setupText);await context.addInitScript(setupCodex);
 await context.route('https://clipper.test/**',async route=>{const file=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(file))return route.abort();try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',file)),contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript'});}catch{return route.abort();}});
 const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');await page.locator('[data-page=text-tools]').click();await page.waitForSelector('#new-ai-profile');
 const close=async()=>{await page.locator('#modal-close').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);},shot=async name=>{await page.evaluate(async()=>{await Promise.allSettled(document.getAnimations().filter(animation=>animation.effect?.getTiming().iterations!==Infinity).map(animation=>animation.finished));});await page.screenshot({path:path.join(output,language+'-'+name+'.png')});};
 await page.locator('[data-ai-edit=codex]').click();await page.waitForFunction(()=>document.getElementById('codex-status').dataset.state==='idle');assert.equal(await page.locator('#ai-base').isVisible(),false);assert.equal(await page.locator('#ai-key').isVisible(),false);assert.equal(await page.locator('#ai-temperature').isVisible(),false);assert.equal(await page.locator('#ai-model').inputValue(),'');assert.equal(await page.locator('.ai-profile-model .field').count(),3);assert.equal(await page.locator('#ai-model').evaluate(element=>getComputedStyle(element.closest('label')).borderBottomWidth),'0px');await shot('disconnected');
 await page.locator('#codex-login').click();await page.waitForSelector('#codex-device:visible');assert.equal(await page.locator('#codex-device-code').textContent(),'ABCD-1234');assert.equal(await page.locator('#codex-login').isVisible(),false);assert.equal(await page.locator('#codex-logout').isVisible(),false);await page.locator('#codex-open-login').click();assert(fixtureCall(await page.evaluate(()=>fixture.calls),'codex-open'));await page.locator('#codex-copy-code').click();await page.waitForFunction(()=>fixture.calls.some(call=>call[0]==='copy-text'));assert.equal((await page.evaluate(()=>fixture.calls.filter(call=>call[0]==='copy-text').at(-1)))[1],'ABCD-1234');await shot('authorization');
 await page.locator('#codex-cancel-login').click();await page.waitForFunction(()=>document.getElementById('codex-status').dataset.state==='idle');await page.locator('#codex-login').click();await page.evaluate(()=>fixture.codex={available:true,loggedIn:true,login:'complete',email:'fixture@example.invalid',planType:'pro'});await page.waitForFunction(()=>document.getElementById('codex-status').dataset.state==='connected');assert.equal(await page.locator('#codex-device').isVisible(),false);assert.equal(await page.locator('#codex-logout').isVisible(),true);assert((await page.locator('#codex-account-detail').textContent()).includes('fixture@example.invalid'));await shot('connected');
 await page.locator('#ai-kind').selectOption('openai');assert.equal(await page.locator('.codex-account').isVisible(),false);assert.equal(await page.locator('#ai-base').isEnabled(),true);await page.locator('#ai-kind').selectOption('codex');assert.equal(await page.locator('#ai-base').isEnabled(),false);await page.locator('#ai-timeout').fill('120');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);const save=await page.evaluate(()=>fixture.calls.filter(call=>call[0]==='profile-save').at(-1)[1]);assert.equal(save.kind,'codex');assert.equal(save.baseUrl,'codex://local');assert.equal(save.model,'');assert.equal(save.timeoutSeconds,120);assert.equal(save.apiKey,undefined);
 await page.locator('[data-ai-models=codex]').click();await page.waitForFunction(()=>!document.getElementById('models-select').disabled);await page.locator('#models-select').selectOption('中文模型');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);assert.equal(await page.locator('[data-ai-edit=codex]').count(),1);
 await page.evaluate(()=>fixture.ai.profiles.find(profile=>profile.id==='codex').model='');await page.locator('[data-page=history]').click();await page.locator('#more-actions').click();await page.locator('#translate').click();await page.waitForSelector('#run-ai-action');assert.equal(await page.locator('#run-tool').isDisabled(),true);assert.equal(await page.locator('#send-consent-row').isVisible(),true);await page.locator('#send-consent').check();assert.equal(await page.locator('#run-tool').isDisabled(),false);await page.locator('#run-tool').click();await page.waitForFunction(()=>document.getElementById('tool-output').value.length>0);const request=await page.evaluate(()=>fixture.calls.filter(call=>call[0]==='ai-run').at(-1)[1]);assert.equal(request.approvedDestination,'codex://local');assert.equal(request.profileId,'codex');await close();
 for(const [width,height,dark]of [[860,650,false],[620,650,true]]){await page.setViewportSize({width,height});await page.evaluate(dark=>{fixture.state.dark=dark;fixture.refresh();},dark);await page.locator('[data-page=text-tools]').click();await page.waitForSelector('[data-ai-edit=codex]');await page.locator('[data-ai-edit=codex]').click();await page.waitForSelector('#codex-status');await shot('connected-'+width);await page.locator('#codex-login').click();await page.waitForSelector('#codex-device:visible');await shot('authorization-'+width);assert.equal(await page.locator('.modal-body').evaluate(element=>element.scrollWidth>element.clientWidth+1),false);await close();await page.evaluate(()=>fixture.codex={available:true,loggedIn:true,login:'complete',email:'fixture@example.invalid',planType:'pro'});}
 results.push({language,passed:true,checks:['Codex-specific fields and compact account layout','device-code copy/open/cancel and sign-in completion','shared model and timeout region without duplicate divider','profile type switching and saved values','model selection and default-model requests','explicit cloud consent','narrow and dark layouts']});await context.close();
 }assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'results.json'),JSON.stringify({scope:'Production renderer with simulated account and AI requests',results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
function fixtureCall(calls,name){return calls.some(call=>call[0]===name);}
