const {chromium,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{setup}=require('./renderer-fixture.cjs');
function customize(){
 const base=fixture.state.clips[0];fixture.state.clips[1].thumbnail=document.createElement('canvas').toDataURL();fixture.state.categories=[{id:'fixture-category',name:'工作',color:'#3482ef',icon:'folder',manual:true}];fixture.state.queue=fixture.state.clips.map(c=>c.id);fixture.state.shelf=[];fixture.state.favoriteOrder=[];
 fixture.state.snippets=[{...base,id:'reply-one',text:'等等',title:'一些',tags:[]},{...base,id:'reply-two',text:'您好，已经收到您的反馈。\n我们会在今天完成确认，并回复处理结果。',title:'收到反馈',shortcut:'Control+Alt+1',tags:[]}];
 clip.removeSnippets=async ids=>{if(fixture.failBatch)throw Error('删除失败，请重试');fixture.removed=ids;fixture.state.snippets=fixture.state.snippets.filter(s=>!ids.includes(s.id));};
 clip.onShortcutInput=()=>()=>{};clip.recordShortcut=async()=>{};clip.search=async()=>fixture.state.clips.map(c=>c.id);clip.categoryCounts=async()=>({'fixture-category':3});clip.useSnippet=async(id,paste)=>{fixture.used=[id,paste];};clip.snippetDetail=async id=>({...fixture.state.snippets.find(s=>s.id===id),payload:{text:fixture.state.snippets.find(s=>s.id===id).text}});clip.removeSnippet=async id=>{fixture.state.snippets=fixture.state.snippets.filter(s=>s.id!==id);};clip.reorderSnippets=async ids=>{fixture.state.snippets=ids.map(id=>fixture.state.snippets.find(s=>s.id===id));};
}
(async()=>{
 const output=path.resolve(process.env.CLIP_TEST_OUTPUT_DIR||'work/collection-view-ui');await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
 try{for(const [dark,width,scale]of [[false,1476,100],[true,860,125]]){
  const context=await browser.newContext({viewport:{width,height:976}});await context.addInitScript({content:`(${setup.toString()})();(${customize.toString()})();fixture.state.dark=${dark};fixture.appearance({font:'system',scale:${scale},density:'comfortable'});`});
  await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto('https://clip.test/index.html');await expect(page.locator('.clip-row')).toHaveCount(3);
  const baseline=await page.locator('.clip-row[data-id=text] .row-content').innerHTML();
  await page.evaluate(()=>{fixture.state.shelf=['image'];fixture.refresh();});await expect(page.locator('.clip-row')).toHaveCount(2);await expect(page.locator('.clip-row[data-id=image]')).toHaveCount(0);await expect(page.locator('#count-history')).toHaveText('2');await expect(page.locator('#count-shelf')).toHaveText('1');
  await page.locator('#search').fill('图片');await expect(page.locator('.clip-row[data-id=image]')).toHaveCount(0);await page.locator('#search').fill('');
  await page.evaluate(()=>{fixture.state.shelf=fixture.state.clips.map(c=>c.id);fixture.refresh();});await expect(page.locator('#count-history')).toHaveText('0');await expect(page.locator('.clip-row')).toHaveCount(0);
  for(const selector of ['[data-page=stack]','[data-page=shelf]','[data-category=fixture-category]']){
   await page.locator(selector).click();await expect(page.locator('.clip-row')).toHaveCount(3);assert.equal(await page.locator('.clip-row[data-id=text] .row-content').innerHTML(),baseline);await expect(page.locator('.clip-row[data-id=image] .record-thumbnail')).toBeVisible();await expect(page.locator('#detail .preview-title')).toHaveCount(0);await expect(page.locator('#detail .detail-kind')).toHaveText('文本');await expect(page.locator('#detail .preview-metadata>.preview-application')).toHaveText('LayoutFixture');
   if(selector!=='[data-page=stack]'){
    await page.locator('#batch-mode').click();await expect(page.locator('#batch-all')).not.toBeChecked();assert.equal(await page.locator('#batch-all').evaluate(node=>node.indeterminate),false);
    await page.locator('[data-check=text]').check();assert.equal(await page.locator('#batch-all').evaluate(node=>node.indeterminate),true);await expect(page.locator('.batch-count')).toHaveText('已选择 1 项');
    await page.locator('#batch-all').click();await expect(page.locator('#batch-all')).toBeChecked();await expect(page.locator('input[data-check]:checked')).toHaveCount(3);assert.equal(await page.locator('#batch-all').evaluate(node=>node.indeterminate),false);
    await page.locator('#batch-all').click();await expect(page.locator('input[data-check]:checked')).toHaveCount(0);await expect(page.locator('.batch-actions button').first()).toBeDisabled();await page.locator('#batch-mode').click();
   }
  }
  await page.locator('[data-page=history]').click();await expect(page.locator('.clip-row')).toHaveCount(0);await page.evaluate(()=>{fixture.state.shelf=[];fixture.refresh();});await expect(page.locator('.clip-row')).toHaveCount(3);await expect(page.locator('#count-history')).toHaveText('3');
  await page.locator('[data-page=replies]').click();await expect(page.locator('.reply-card')).toHaveCount(2);await expect(page.locator('#detail')).toHaveCount(0);const first=page.locator('.reply-card[data-id=reply-one]');
  const dimensions=await first.evaluate(card=>({height:card.getBoundingClientRect().height,width:card.getBoundingClientRect().width,overflow:card.scrollWidth>card.clientWidth+1}));assert(dimensions.height<190*scale/100);assert(dimensions.width<=381);assert.equal(dimensions.overflow,false);assert(await page.locator('#results').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await first.locator('[data-reply-use=copy]').click();assert.deepEqual(await page.evaluate(()=>fixture.used),['reply-one',false]);await first.locator('[data-reply-use=paste]').click();assert.deepEqual(await page.evaluate(()=>fixture.used),['reply-one',true]);
  await first.locator('[data-reply-more]').click();await expect(first.locator('[data-reply-menu]')).toBeVisible();await first.locator('[data-reply-edit]').click();await expect(page.locator('dialog[open]')).toBeVisible();assert(await page.locator('#dialog form').evaluate(form=>form.noValidate));await page.locator('#dialog').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{}))));const titleBox=await page.locator('#reply-title').boundingBox(),bodyBox=await page.locator('#reply-text').boundingBox();assert(Math.abs(titleBox.x-bodyBox.x)<1&&Math.abs(titleBox.width-bodyBox.width)<1);assert(await page.locator('#reply-title').evaluate(input=>getComputedStyle(input.closest('.field')).flexDirection==='column'));await page.locator('#reply-title').fill('  ');await page.locator('#reply-text').fill('');const formBefore=await page.locator('#dialog').boundingBox();await page.locator('#dialog [type=submit]').click();assert.deepEqual(await page.locator('#dialog').boundingBox(),formBefore);assert.deepEqual(await page.locator('#reply-text').boundingBox(),bodyBox);await expect(page.locator('#modal-error')).toBeEmpty();assert(await page.locator('.form-field-error').evaluateAll(nodes=>nodes.every(node=>node.parentElement.classList.contains('form-field-heading'))));await expect(page.locator('.form-field-error')).toHaveCount(2);await expect(page.locator('#reply-title')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#reply-title')).toBeFocused();await page.locator('#reply-title').fill('标题');await expect(page.locator('.form-field-error')).toHaveCount(1);await page.screenshot({path:path.join(output,(dark?'dark':'light')+'-reply-form.png')});await page.locator('#modal-cancel').click();await expect(page.locator('dialog[open]')).toHaveCount(0);
  await page.screenshot({path:path.join(output,(dark?'dark':'light')+'-reply-cards.png')});
  await page.locator('button[data-reply-layout=list]').click();await expect(page.locator('#results')).toHaveAttribute('data-reply-layout','list');await expect(page.locator('#detail')).toHaveCount(0);assert(await page.locator('#results').evaluate(el=>el.scrollWidth<=el.clientWidth+1));assert(await page.locator('.reply-card').evaluateAll(cards=>cards.every(card=>card.scrollWidth<=card.clientWidth+1)));await first.locator('[data-reply-use=copy]').click();assert.deepEqual(await page.evaluate(()=>fixture.used),['reply-one',false]);await page.screenshot({path:path.join(output,(dark?'dark':'light')+'-reply-list.png')});
  const listAlignment=await first.evaluate(card=>{const title=card.querySelector('header>strong').getBoundingClientRect(),preview=card.querySelector('.reply-card-preview'),text=document.createRange();text.selectNodeContents(preview);const body=text.getBoundingClientRect(),footer=card.querySelector('footer').getBoundingClientRect(),grip=card.querySelector('.row-sort-grip').getBoundingClientRect(),kind=card.querySelector('.reply-card-kind').getBoundingClientRect();return {aligned:Math.abs(title.x-body.x)<=1,stacked:body.y>=title.bottom,actionsRight:footer.x>title.x,gripLeft:grip.right<=kind.x};});assert.deepEqual(listAlignment,{aligned:true,stacked:true,actionsRight:true,gripLeft:true});
  await page.reload();await page.locator('[data-page=replies]').click();await expect(page.locator('#results')).toHaveAttribute('data-reply-layout','list');await expect(page.locator('button[data-reply-layout=list]')).toHaveAttribute('aria-pressed','true');
  await page.locator('#search').fill('反馈');await expect(page.locator('.reply-card')).toHaveCount(1);await page.locator('button[data-reply-layout=cards]').click();await expect(page.locator('.reply-card')).toHaveCount(1);await expect(page.locator('#results')).toHaveAttribute('data-reply-layout','cards');await page.locator('#search').fill('');await expect(page.locator('.reply-card')).toHaveCount(2);
  await first.locator('[data-reply-more]').click();await page.keyboard.press('Escape');await expect(first.locator('[data-reply-more]')).toHaveAttribute('aria-expanded','false');
  await expect(page.locator('#reply-hotkeys')).toHaveCount(0);await page.locator('#batch-mode').click();await expect(page.locator('[data-reply-check]')).toHaveCount(2);await expect(page.locator('#batch-delete')).toBeDisabled();await first.locator('.reply-card-preview').click();await expect(first.locator('[data-reply-check]')).toBeChecked();assert.equal(await page.locator('#batch-all').evaluate(el=>el.indeterminate),true);await page.locator('button[data-reply-layout=list]').click();await expect(first.locator('[data-reply-check]')).toBeChecked();await expect(first.locator('footer')).toBeHidden();await page.evaluate(()=>fixture.refresh());await expect(first.locator('[data-reply-check]')).toBeChecked();await page.locator('#batch-all').click();await expect(page.locator('[data-reply-check]:checked')).toHaveCount(2);await page.screenshot({path:path.join(output,(dark?'dark':'light')+'-reply-batch.png')});await page.locator('#batch-delete').click();await page.locator('#modal-cancel').click();await expect(page.locator('.reply-card')).toHaveCount(2);await page.locator('#batch-mode').click();await expect(page.locator('[data-reply-check]')).toHaveCount(0);await page.locator('button[data-reply-layout=cards]').click();
  await first.locator('[data-reply-more]').click();await first.locator('[data-reply-delete]').click();await page.locator('dialog[open] button[type=submit]').click();await expect(page.locator('.reply-card')).toHaveCount(1);
  await expect(page.locator('dialog[open]')).toHaveCount(0);await page.locator('#batch-mode').click();await page.locator('#search').fill('not-found');await expect(page.locator('.reply-card')).toHaveCount(0);await expect(page.locator('.empty')).toBeVisible();await expect(page.locator('#batch-all')).toBeDisabled();await page.locator('#search').fill('');await page.locator('#batch-all').click();await page.evaluate(()=>fixture.failBatch=true);await page.locator('#batch-delete').click();await page.locator('dialog[open] button[type=submit]').click();await expect(page.locator('#modal-error')).toContainText('删除失败');await expect(page.locator('[data-reply-check]:checked')).toHaveCount(1);await page.evaluate(()=>fixture.failBatch=false);await page.locator('dialog[open] button[type=submit]').click();await expect(page.locator('.reply-card')).toHaveCount(0);assert.deepEqual(await page.evaluate(()=>fixture.removed),['reply-two']);await expect(page.locator('.batch-count')).toHaveText('已选择 0 项');await context.close();
 }assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,shelfExcludedFromHistory:true,replyLayouts:true,replyLayoutPersisted:true,sharedRecordLayout:true,sharedDetailLayout:true,triStateBatch:true,replyCards:true,copyPaste:true,editDelete:true,menuKeyboard:true,lightDark:true,scaledNarrow:true,systemClipboard:false},null,2));console.log('PASS: shared collection rendering, tri-state batch selection and compact reply cards with actions, menus, search and scaling');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
