const {chromium}=require('@playwright/test'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),esbuild=require('esbuild'),asar=require('@electron/asar');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs'),{prepare}=require('./collection-042-fixture.cjs');
const archive=process.env.CLIPPER_COLLECTION_ASAR,baseline=process.env.CLIPPER_COLLECTION_BASELINE_ASAR,out=process.env.CLIPPER_TEST_OUTPUT_DIR||'work/current/collection-042';fs.mkdirSync(out,{recursive:true});let browser;const results=[],perf=[];
(async()=>{browser=await chromium.launch({channel:'msedge',headless:true});const library=(await esbuild.build({stdin:{contents:"import * as markup from './src/renderer/markup';import {ActionScope,setActionDisabled} from './src/renderer/actions';window.components={...markup,ActionScope,setActionDisabled};",resolveDir:process.cwd()},bundle:true,write:false,outfile:'work/collection-042/components.js'})).outputFiles.find(f=>f.path.endsWith('.js')).text;
const context=await browser.newContext();await context.route('https://component.test/**',route=>route.fulfill({body:library,contentType:'text/javascript'}));const component=await context.newPage();await component.goto('about:blank');await component.setContent('<main id="rows"></main><section id="preview"></section><button id="operation">Operation</button>');await component.addScriptTag({url:'https://component.test/library.js'});
const checks=await component.evaluate(async()=>{const {keyedMarkup,patchMarkup,ActionScope,setActionDisabled}=components,root=document.getElementById('rows'),checks=[],check=(name,value)=>{if(!value)throw Error(name);checks.push(name);},row=(id,title=id,checked=false)=>({key:id,html:'<div><input type="checkbox" '+(checked?'checked':'')+'><button id="'+id+'" aria-label="'+title+'"><span>'+title+'</span></button></div>'});
 keyedMarkup(root,[row('a'),row('b')]);const a=root.firstElementChild,b=root.lastElementChild;const records=[];const observer=new MutationObserver(r=>records.push(...r));observer.observe(root,{subtree:true,attributes:true,childList:true,characterData:true});keyedMarkup(root,[row('a'),row('b')]);await Promise.resolve();check('Unchanged One row markup has no mutations',records.length===0);
 document.getElementById('b').focus();keyedMarkup(root,[row('new'),row('b'),row('a')]);check('Keyed reorder preserves row identity and keyboard focus',root.children[1]===b&&root.children[2]===a&&document.activeElement.id==='b');
 const button=document.getElementById('b');keyedMarkup(root,[row('b','Updated',true),row('a')]);check('Changed row updates text, label and checked state in place',document.getElementById('b')===button&&button.textContent==='Updated'&&button.getAttribute('aria-label')==='Updated'&&root.firstElementChild.querySelector('input').checked);
 keyedMarkup(root,[row('a')]);check('Deleted rows are removed',!b.isConnected&&root.children.length===1);observer.disconnect();
 keyedMarkup(root,[{key:'a',html:'<button id="plain-row">Row</button>'}]);keyedMarkup(root,[{key:'a',html:'<div><input type="checkbox"><button>Row</button></div>'}]);keyedMarkup(root,[{key:'a',html:'<button id="restored-row">Row</button>'}]);check('A row can enter and leave a batch wrapper without a detached insertion cursor',root.children.length===1&&root.firstElementChild.id==='restored-row');
 const host=document.getElementById('preview');patchMarkup(host,'<div class="preview-body">Original</div><button id="toggle" class="quiet"><span>One icon</span></button>');const body=host.firstElementChild,toggle=document.getElementById('toggle');body.innerHTML='<div class="live-reader">User reader</div>';toggle.innerHTML='<span>Runtime icon</span>';toggle.classList.add('action-pending');toggle.setAttribute('aria-pressed','true');patchMarkup(host,'<div class="preview-body"></div><button id="toggle" class="quiet active"><span>One icon</span></button>',undefined,n=>n.classList.contains('preview-body'));check('Authored metadata preserves live reader and runtime icon',host.firstElementChild===body&&body.textContent==='User reader'&&toggle.textContent==='Runtime icon');check('Authored class changes preserve runtime busy state',toggle.classList.contains('active')&&toggle.classList.contains('action-pending')&&toggle.getAttribute('aria-pressed')==='true');
 const op=document.getElementById('operation'),scope=new ActionScope();let registrations=0,calls=0,chosen=-1,end;const add=op.addEventListener.bind(op);op.addEventListener=(type,...args)=>{if(type==='click')registrations++;return add(type,...args);};for(let i=0;i<1000;i++)scope.bind(op,()=>{calls++;chosen=i;},e=>{throw e;},'same');op.click();await Promise.resolve();await Promise.resolve();check('Repeated binding adds one listener and invokes latest action once',registrations===1&&calls===1&&chosen===999);
 const pending=scope.run('pending',()=>new Promise(resolve=>end=resolve),[op]);setActionDisabled(op,true);end();await pending;check('Business disabled state survives pending action completion',op.disabled);setActionDisabled(op,false);check('Business disabled state can be restored',!op.disabled);return checks;});results.push(...checks.map(name=>({name})));
await context.close();
async function pageFor(mode){const context=await browser.newContext({viewport:{width:1240,height:800}});for(const fn of [setup,extra,prepare])await context.addInitScript(fn,'zh-CN');await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(name.startsWith('probe-image-')){const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');return route.fulfill({body:png,contentType:'image/png'});}const source=mode==='before'?baseline:archive;const bytes=source?asar.extractFile(source,('dist/renderer/'+name).replaceAll('/','\\')):fs.readFileSync(path.join('dist/renderer',name));await route.fulfill({body:bytes,contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('.text-reader[data-ready=true]');return {context,page,errors};}
const pass=name=>results.push({name});
const {context:ctx,page,errors}=await pageFor('after');
await page.evaluate(async()=>{window.readerModule=await import('/text-preview/text-preview.js');window.readerNode=document.querySelector('.text-reader');window.wrapNode=document.getElementById('preview-wrap');window.filterNode=document.querySelector('[data-kind=all]');window.rowNode=document.querySelector('[data-id=reader]');document.querySelector('.cm-content').focus();});await page.locator('.cm-content').press('Control+f');await page.locator('.code-search input').fill('END_COLLECTION_042');await page.locator('.code-search input').press('Enter');await page.locator('#preview-wrap').click();await page.waitForTimeout(150);const before=await page.evaluate(()=>{const host=document.querySelector('#detail .preview-body'),s=readerModule.captureTextPreview(host);return {requests:collectionProbe.requests,details:collectionProbe.details,selection:readerModule.previewState(host).selection,wrap:s.wrap,search:s.search,top:document.querySelector('.cm-scroller').scrollTop,icon:wrapNode.innerHTML};});
for(let i=0;i<5;i++){await page.evaluate(i=>{const item=fixture.state.clips[0];item.favorite=!item.favorite;item.pinned=!item.pinned;item.source='source-'+i;item.tags=['tag-'+i];item.updatedAt=Date.now()+i;fixture.refresh();},i);await page.waitForFunction(i=>document.querySelector('#record-info dd').textContent==='source-'+i,i);}
const preserved=await page.evaluate(()=>{const host=document.querySelector('#detail .preview-body'),s=readerModule.captureTextPreview(host);return {sameReader:readerNode===document.querySelector('.text-reader'),sameWrap:wrapNode===document.getElementById('preview-wrap'),sameRow:rowNode===document.querySelector('[data-id=reader]'),sameFilter:filterNode===document.querySelector('[data-kind=all]'),requests:collectionProbe.requests,details:collectionProbe.details,selection:readerModule.previewState(host).selection,wrap:s.wrap,search:s.search,top:document.querySelector('.cm-scroller').scrollTop,icon:wrapNode.innerHTML};});assert(preserved.sameReader&&preserved.sameWrap&&preserved.sameRow&&preserved.sameFilter);assert.equal(preserved.requests,before.requests);assert.equal(preserved.details,before.details);for(const key of ['wrap','search','icon'])assert.deepEqual(preserved[key],before[key]);assert(Math.abs(preserved.top-before.top)<2);pass('Metadata changes preserve actual reader, selection, search, wrap, scroll, icon and payload request');
await page.locator('[data-kind=all]').focus();await page.evaluate(()=>{const clip={...fixture.state.clips.at(-1),id:'incoming',hash:'incoming',title:'Incoming'};fixture.state.clips.unshift(clip);fixture.refresh();});await page.waitForSelector('[data-id=incoming]');assert.equal(await page.evaluate(()=>document.activeElement===filterNode),true);pass('Incoming record preserves segmented filter keyboard focus');
for(let i=0;i<4;i++)await page.locator('#load-more').click();await page.locator('[data-id=record-120]').evaluate(e=>e.scrollIntoView({block:'start'}));const anchor=await page.evaluate(()=>{const root=document.getElementById('results'),r=root.getBoundingClientRect(),node=document.elementFromPoint(r.left+24,r.top+12).closest('.clip-row');return {id:node.dataset.id,offset:node.getBoundingClientRect().top-r.top};});await page.evaluate(()=>{fixture.state.clips.unshift({...fixture.state.clips.at(-1),id:'next-incoming',hash:'next-incoming',title:'Next incoming'});fixture.refresh();});await page.waitForSelector('[data-id=next-incoming]',{state:'attached'});const afterAnchor=await page.evaluate(id=>{const root=document.getElementById('results'),row=root.querySelector('[data-id="'+id+'"]');return row.getBoundingClientRect().top-root.getBoundingClientRect().top;},anchor.id);assert(Math.abs(afterAnchor-anchor.offset)<2);pass('Arrival above a scrolled list preserves the record being read');
await page.locator('[data-id=picture]').click();await page.waitForFunction(()=>document.querySelector('.image-preview img')?.naturalWidth===1);const picture=await page.evaluate(()=>{window.imageNode=document.querySelector('.image-preview img');return {details:collectionProbe.details,released:collectionProbe.released.length};});await page.evaluate(()=>{const item=fixture.state.clips.find(c=>c.id==='picture');item.favorite=!item.favorite;fixture.refresh();});await page.waitForFunction(()=>document.getElementById('favorite').getAttribute('aria-pressed')==='true');assert.equal(await page.evaluate(()=>imageNode===document.querySelector('.image-preview img')),true);assert.equal(await page.evaluate(()=>collectionProbe.details),picture.details);assert.equal(await page.evaluate(()=>collectionProbe.released.length),picture.released);pass('Image metadata retains decoded element and original lease');
await page.locator('#share-record').evaluate(e=>e.click());await page.waitForFunction(()=>collectionProbe.sharePending.length===1);await page.evaluate(()=>{fixture.state.clips.find(c=>c.id==='picture').shared=true;fixture.refresh();});await page.waitForFunction(()=>document.getElementById('share-record').getAttribute('aria-pressed')==='true');await page.evaluate(()=>collectionProbe.sharePending.shift()());await page.waitForFunction(()=>!document.getElementById('share-record').hasAttribute('aria-busy'));assert(await page.locator('#share-record').isDisabled());assert.equal(await page.evaluate(()=>collectionProbe.shareCalls),1);pass('Shared metadata and pending action preserve business disablement');
await page.locator('[data-id=picture]').dispatchEvent('dragstart');assert.deepEqual(await page.evaluate(()=>collectionProbe.drags),['picture']);await page.evaluate(()=>{const item=fixture.state.clips.find(c=>c.id==='picture');item.kind='text';item.hash='converted-picture';fixture.refresh();});await page.waitForFunction(()=>document.querySelector('[data-id=picture]').draggable===false);assert.equal(await page.locator('[data-id=picture]').evaluate(e=>e.ondragstart===null),true);pass('Reused row clears obsolete native drag eligibility');
await page.locator('[data-page=stack]').click();assert.equal(await page.locator('[data-id=reader]').count(),2);const first=await page.locator('[data-id=reader]').first().evaluate(e=>{window.duplicateNode=e;return e.dataset.queueIndex;});await page.locator('[data-id=reader]').last().click();await page.locator('#dequeue').evaluate(e=>e.click());await page.waitForFunction(()=>collectionProbe.queueCalls.length===1);assert.deepEqual(await page.evaluate(()=>collectionProbe.queueCalls[0]),[2,'reader','dequeue',['reader','picture','reader']]);await page.evaluate(()=>fixture.refresh());await page.waitForTimeout(80);assert.equal(await page.locator('[data-id=reader]').first().evaluate(e=>e===duplicateNode),true);pass('Duplicate stack rows retain distinct slot identities and correct action index');
await page.locator('[data-page=history]').click();await page.locator('#batch-mode').click();await page.locator('[data-check=reader]').check();await page.evaluate(()=>{const item=fixture.state.clips.find(c=>c.id==='reader');item.title='Updated batch row';fixture.refresh();});await page.waitForSelector('[aria-label="Updated batch row"]');assert(await page.locator('[data-check=reader]').isChecked());pass('Batch selection survives row metadata updates');await page.locator('#batch-mode').click();
await page.locator('[data-page=replies]').click();await page.waitForSelector('.text-reader[data-ready=true]');const reply=await page.evaluate(()=>{window.replyReader=document.querySelector('.text-reader');return {details:collectionProbe.details,requests:collectionProbe.requests};});await page.evaluate(()=>{fixture.state.snippets[0].shortcut='Control+1';fixture.refresh();});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>replyReader===document.querySelector('.text-reader')),true);assert.equal(await page.evaluate(()=>collectionProbe.details),reply.details);assert.equal(await page.evaluate(()=>readerModule.previewText(document.querySelector('#detail .preview-body'))===collectionProbe.text),true);pass('Snippet shortcut metadata retains full text rather than projected summary');
await page.evaluate(()=>{collectionProbe.text='Changed complete reply';fixture.state.snippets[0].revision=2;fixture.refresh();});await page.waitForSelector('#detail pre.text-preview');assert.equal(await page.locator('#detail pre.text-preview').textContent(),'Changed complete reply');pass('Content revision replaces the old reader');
await page.locator('[data-page=history]').click();await page.evaluate(()=>{collectionProbe.blocking=true;fixture.state.clips.find(c=>c.id==='reader').hash='pending-reader';fixture.refresh();});await page.locator('[data-id=reader]').click();await page.waitForFunction(()=>collectionProbe.pending.length===1);for(let i=0;i<3;i++){await page.evaluate(i=>{fixture.state.clips.find(c=>c.id==='reader').source='pending-source-'+i;fixture.refresh();},i);await page.waitForTimeout(60);}assert.equal(await page.evaluate(()=>collectionProbe.pending.length),1);await page.evaluate(()=>{collectionProbe.blocking=false;collectionProbe.pending.shift()();});await page.waitForFunction(()=>document.querySelector('#record-info dd')?.textContent==='pending-source-2');pass('Pending preview is shared across metadata updates and applies latest metadata');
await page.evaluate(()=>{fixture.windowVisible(false);});assert.equal(await page.locator('#detail .preview-body').count(),0);await page.evaluate(()=>fixture.windowVisible(true));await page.waitForSelector('#detail .preview-body');pass('Visibility still retires retained preview contents');assert.deepEqual(errors,[]);await ctx.close();
// Alternate versions. Each trial loads 500 rows, then records ten real production refreshes.
for(let trial=0;trial<3;trial++)for(const mode of baseline?(trial%2?['after','before']:['before','after']):['after']){const {context,page,errors}=await pageFor(mode);for(let i=0;i<4;i++)await page.locator('#load-more').click();await page.locator('[data-id=record-150]').click();await page.evaluate(()=>{window.keptRow=document.querySelector('[data-id=record-150]');window.churn={added:0,removed:0};window.listObserver=new MutationObserver(rs=>{for(const r of rs){churn.added+=r.addedNodes.length;churn.removed+=r.removedNodes.length;}});listObserver.observe(document.getElementById('results'),{childList:true,subtree:true});});const times=[];for(let i=0;i<10;i++){const ms=await page.evaluate(async i=>{const count=fixture.state.clips.length,start=performance.now();fixture.state.clips.unshift({...fixture.state.clips.at(-1),id:'bench-'+i,hash:'bench-'+i,title:'Bench '+i});fixture.refresh();while(!document.querySelector('[data-id="bench-'+i+'"]'))await new Promise(requestAnimationFrame);return performance.now()-start;},i);times.push(ms);}const value=await page.evaluate(()=>{listObserver.disconnect();return {...churn,kept:keptRow===document.querySelector('[data-id=record-150]'),rows:document.querySelectorAll('.clip-row').length,details:collectionProbe.details,workerRequests:collectionProbe.requests};});assert.deepEqual(errors,[]);if(mode==='after'){assert(value.kept);assert(value.removed<=10);assert(value.added<=10);}perf.push({mode,trial,...value,medianMs:times.sort((a,b)=>a-b)[5],samples:times});await context.close();}
const report={passed:true,version:'0.42.0',packaged:!!archive,cases:results.length,results,performance:{trials:3,rows:500,records:10002,refreshes:10,alternating:!!baseline,baselineCompared:!!baseline,raw:perf,scope:'Headless actual production renderer; synthetic isolated IPC; each latency includes the intentional 32 ms refresh debounce. DOM identity and churn are measured; full application memory and physical input are not measured.'},physicalInput:false,systemClipboard:false};fs.writeFileSync(out+(archive?'/packaged.json':'/results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,cases:results.length,perf}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
