const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupText}=require('./language-text-fixture.cjs');
const {builtinCommands,setInterfaceLanguage}=require('../work/test-exports.cjs');
const output=process.env.CLIP_TEST_OUTPUT_DIR||path.resolve('work/current/commands-ui');
function commandsFixture(builtins){
 fixture.commands=[...builtins,...JSON.parse(localStorage.getItem('fixture-commands')||'[]')];
 const persist=()=>localStorage.setItem('fixture-commands',JSON.stringify(fixture.commands.filter(command=>!command.builtin)));
 const base=window.clip,overrides={
  commands:async()=>{if(fixture.delayCommands)await new Promise(resolve=>fixture.releaseCommands=resolve);return fixture.commands;},
  saveCommand:async value=>{fixture.calls.push(['command-save',value]);const command={...value,id:value.id||crypto.randomUUID(),revision:crypto.randomUUID(),builtin:false};fixture.commands=value.id?fixture.commands.map(item=>item.id===value.id?command:item):[...fixture.commands,command];persist();return command.id;},
  removeCommand:async(id,revision)=>{fixture.calls.push(['command-remove',id,revision]);fixture.commands=fixture.commands.filter(command=>command.id!==id);persist();},
 };window.clip=new Proxy(overrides,{get:(object,key)=>key in object?object[key]:base[key]});
}
(async()=>{
 await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[],errors=[];let context;
 try{for(const language of ['zh-CN','en']){
  setInterfaceLanguage(language);context=await browser.newContext({viewport:{width:1366,height:900}});await context.addInitScript(setup,language);await context.addInitScript(setupText);await context.addInitScript(commandsFixture,builtinCommands());
  await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});}catch{return route.abort();}});
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  const start=async()=>{await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');};
  const close=async()=>{await page.locator('#modal-close').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);};
  const submit=async()=>{await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);};
  const shot=async name=>{await page.evaluate(async()=>{await Promise.allSettled(document.getAnimations().filter(animation=>animation.effect?.getTiming().iterations!==Infinity).map(animation=>animation.finished));await new Promise(requestAnimationFrame);});await page.screenshot({path:path.join(output,language+'-'+name+'.png')});};
  await start();assert.equal(await page.locator('[data-page=ai],[data-page=scripts]').count(),0);await page.locator('[data-page=text-tools]').click();await page.waitForSelector('#new-ai-profile');assert.deepEqual(await page.locator('[data-text-tab]').evaluateAll(buttons=>buttons.map(button=>button.dataset.textTab)),['ai','commands','scripts']);assert.equal(await page.locator('[data-page=text-tools]').textContent(),language==='en'?'AI & Scripts':'AI与脚本');
  await page.waitForSelector('.text-tools-toolbar .tabs.segment-ready');await page.evaluate(()=>{fixture.segment=document.querySelector('.text-tools-toolbar .tabs');fixture.segmentStart=fixture.segment.style.getPropertyValue('--segment-x');fixture.delayCommands=true;});
  await page.locator('[data-text-tab=commands]').click();await page.waitForFunction(()=>fixture.segment.style.getPropertyValue('--segment-x')!==fixture.segmentStart);assert.equal(await page.locator('[data-text-tab=commands]').isDisabled(),false);assert.equal(await page.locator('[data-text-tab=commands]').getAttribute('aria-selected'),'true');assert(await page.evaluate(()=>fixture.segment===document.querySelector('.text-tools-toolbar .tabs')));assert(await page.locator('.text-tools-toolbar .tabs').evaluate(element=>getComputedStyle(element,'::before').transitionDuration.split(',').some(value=>parseFloat(value)>0)));
  await page.locator('[data-text-tab=scripts]').click();await page.waitForSelector('#new-script');await page.evaluate(async()=>{fixture.delayCommands=false;fixture.releaseCommands();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});assert.equal(await page.locator('#new-script').count(),1);assert.equal(await page.locator('#new-command').count(),0);assert(await page.evaluate(()=>fixture.segment===document.querySelector('.text-tools-toolbar .tabs')));
  await page.locator('[data-text-tab=scripts]').press('ArrowLeft');await page.waitForSelector('#new-command');assert(await page.locator('[data-text-tab=commands]').evaluate(button=>document.activeElement===button));assert(await page.evaluate(()=>fixture.segment===document.querySelector('.text-tools-toolbar .tabs')));
  await page.locator('[data-text-tab=commands]').click();await page.waitForSelector('#new-command');assert.equal(await page.locator('.command-card').count(),3);await shot('library');
  await page.locator('#new-command').click();await page.locator('#command-title').fill('Email <img id="command-injected">');await page.locator('[data-command-icon=mail]').click();await page.locator('#command-prompt').fill('Polish {{text}} in {{language}} with {{tone}}. Title: {{title}}. Source: {{source}}. ');await page.locator('[data-insert-variable=date]').click();assert((await page.locator('#command-prompt').inputValue()).endsWith('{{date}}'));await shot('editor');await submit();await page.waitForFunction(()=>fixture.commands.length===4);assert.equal(await page.locator('#command-injected').count(),0);const command=await page.evaluate(()=>fixture.commands.at(-1));assert.equal(command.icon,'mail');assert.equal(await page.locator('#command-edit-'+command.id).count(),1);
  await page.locator('#command-edit-'+command.id).click();await page.locator('#command-title').fill('Polish email');await submit();await page.locator('#command-copy-translate').click();await page.locator('#command-title').fill('Translation copy');await submit();const copy=await page.evaluate(()=>fixture.commands.at(-1));assert.equal(copy.builtin,false);await page.locator('#command-delete-'+copy.id).click();await submit();assert.equal(await page.locator('.command-card').count(),4);
  await start();await page.locator('[data-page=text-tools]').click();await page.locator('[data-text-tab=commands]').click();await page.waitForSelector('#new-command');assert.equal(await page.locator('.command-card').count(),4);await page.locator('[data-text-tab=scripts]').click();await page.waitForSelector('#new-script');const toolbar=await page.locator('.text-tools-toolbar').evaluate(element=>{const tabs=element.querySelector('.tabs').getBoundingClientRect(),actions=element.querySelector('.heading-actions').getBoundingClientRect();return {sameRow:Math.abs(tabs.y+tabs.height/2-actions.y-actions.height/2)<3,overlap:tabs.right>actions.x};});assert(toolbar.sameRow);assert(!toolbar.overlap);
  await page.locator('[data-page=history]').click();await page.locator('[data-id=text]').click();await page.locator('#more-actions').click();await page.locator('#run-command').click();await page.waitForSelector('#run-ai-action');await page.locator('#run-ai-action').selectOption(command.id);await page.waitForSelector('#run-ai-action-trigger .select-option-icon');assert.equal(await page.locator('#ai-command-icon').count(),0);assert.equal(await page.locator('#run-ai-action-trigger .select-option-icon svg').getAttribute('data-lucide-icon'),'lucide:command-mail');await page.locator('#run-ai-action-trigger').click();assert.equal(await page.locator('#run-ai-action-trigger-options [role=option] .select-option-icon').count(),5);assert(await page.locator('#run-ai-action-trigger-options .select-option-icon svg').evaluateAll(icons=>icons.every(icon=>getComputedStyle(icon).opacity==='1')));await shot('command-options');await page.locator('#run-ai-action-trigger-options [role=option]').filter({hasText:'Polish email'}).click();assert.equal(await page.locator('#run-ai-action').inputValue(),command.id);await page.locator('#run-ai-profile').selectOption('local');assert.equal(await page.locator('#run-tool').isDisabled(),true);await page.locator('[data-command-value=tone]').fill('friendly');await page.locator('.ai-command-preview>summary').click();assert.match(await page.locator('#ai-command-preview').textContent(),/friendly/);await shot('run-command');await page.locator('#run-tool').click();await page.waitForFunction(()=>document.getElementById('tool-output').value.length>0);const request=await page.evaluate(()=>fixture.calls.find(call=>call[0]==='ai-run')[1]);assert.equal(request.command.id,command.id);assert.equal(request.command.values.tone,'friendly');assert.equal(request.command.values.source,'LayoutFixture.exe');assert.equal(request.image,undefined);await close();
  await page.locator('[data-id=image]').click();await page.locator('#more-actions').click();await page.locator('#ai-image').click();await page.waitForSelector('.ai-input-image>img');assert.equal(await page.locator('#result-replace').count(),0);assert.equal(await page.locator('#run-tool').isDisabled(),true);await page.locator('#send-consent').check();await shot('vision');await page.locator('#run-tool').click();await page.waitForFunction(()=>document.getElementById('tool-output').value.length>0);const vision=await page.evaluate(()=>fixture.calls.filter(call=>call[0]==='ai-run').at(-1)[1]);assert.deepEqual(vision.image,{clipId:'image',hash:'fixture'});assert.equal(vision.action,'custom');assert(vision.instruction.length>0);await submit();
  for(const [width,height,dark]of [[860,600,false],[620,650,true]]){await page.setViewportSize({width,height});await start();await page.evaluate(dark=>{fixture.state.dark=dark;fixture.refresh();},dark);await page.locator('[data-page=text-tools]').click();await page.locator('[data-text-tab=commands]').click();await page.waitForSelector('#new-command');await shot('library-'+width);assert.equal(await page.locator('.tools-scroll').evaluate(element=>element.scrollWidth>element.clientWidth+1),false);await page.locator('#new-command').click();await shot('editor-'+width);assert.equal(await page.locator('.modal-body').evaluate(element=>element.scrollWidth>element.clientWidth+1),false);await close();await page.locator('[data-page=history]').click();await page.locator('[data-id=image]').click();await page.locator('#more-actions').click();await page.locator('#ai-image').click();await page.waitForSelector('.ai-input-image');await shot('vision-'+width);assert.equal(await page.locator('.modal-body').evaluate(element=>element.scrollWidth>element.clientWidth+1),false);await close();}
  results.push({language,passed:true,checks:['single navigation entry and ordered shared segments','shared indicator stays mounted and animated during asynchronous switching','keyboard tab focus retained','stale tab response discarded','create/edit/duplicate/delete/persist and escaping','icon and cursor variable insertion','toolbar remains one row','command icons in selected value and every menu option','command variables and request metadata','image preview, explicit send consent and protected original','narrow and dark layouts']});await context.close();context=undefined;
 }
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'results.json'),JSON.stringify({scope:'Production renderer with simulated IPC; no actual AI requests',results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));
 }finally{await context?.close();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
