const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
const markup=`<div id="foundation" style="position:fixed;top:70px;left:220px;padding:16px;background:var(--surface);z-index:5;display:flex;flex-direction:column;gap:12px;width:360px"><button id="sample-button">Button</button><button id="sample-primary" class="primary">Primary</button><input id="sample-input" placeholder="Input"><textarea id="sample-textarea">Text</textarea><label class="switch"><input id="sample-switch" type="checkbox" checked><span class="switch-track"></span></label><button id="sample-select" class="custom-select"><span>Option</span></button><span class="number-control"><input id="sample-number" type="number" value="10"><button>+</button></span><div class="tabs"><button id="sample-tab" class="selected">Tab</button></div></div>`;
(async()=>{await fs.mkdir('work/components-030',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];try{
 const componentCSS=await fs.readFile("D:/Repositories/One/src/renderer/components.css","utf8"),controller=(await require("esbuild").build({stdin:{contents:"import {setupSegments} from 'D:/Repositories/One/src/renderer/segments.ts';setupSegments();",resolveDir:process.cwd()},bundle:true,write:false,platform:"browser"})).outputFiles[0].text;const css=await fs.readFile('D:/Repositories/One/src/renderer/styles.css','utf8');
 for(const theme of ['light','dark']){const context=await browser.newContext({viewport:{width:1240,height:800}});await context.addInitScript(setup);await context.addInitScript(extra);await context.addInitScript(theme=>fixture.state.dark=theme==='dark',theme);
  await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
  const actual=await context.newPage();await actual.goto('https://clipper.test/index.html');await actual.waitForSelector('#copy');await actual.evaluate(markup=>document.body.insertAdjacentHTML('beforeend',markup),markup);
  const reference=await context.newPage();await reference.setContent(`<html data-theme="${theme}"><head><style>${css}${componentCSS}</style><style>:root[data-theme=dark]{--surface:#181818;--fg:#eee;--accent:#e4e4e4;--on-accent:#141414}</style></head><body><div id="app">${markup}</div></body></html>`);
  await reference.addScriptTag({content:controller});await actual.waitForSelector("#foundation .segment-ready");await reference.waitForSelector("#foundation .segment-ready");for(const p of [actual,reference])await p.waitForFunction(()=>getComputedStyle(document.getElementById("sample-tab")).backgroundColor==="rgba(0, 0, 0, 0)");
  for(const name of ['button','primary','input','textarea','switch','select','number','tab']){const selector='#sample-'+name,read=e=>{const s=getComputedStyle(e);return Object.fromEntries(['backgroundColor','color','borderTopWidth','borderTopLeftRadius','paddingLeft','paddingRight','fontSize'].map(k=>[k,s[k]]));};const a=await actual.locator(selector).evaluate(read),b=await reference.locator(selector).evaluate(read);assert.deepEqual(a,b,theme+' '+name);results.push({theme,name,styles:a});}
  await context.close();
 }
 await fs.writeFile('work/components-030/results.json',JSON.stringify({passed:true,cases:results.length,source:'Actual One '+JSON.parse(await fs.readFile('D:/Repositories/One/package.json','utf8')).version+' styles.css, components.css and segments.ts compared against built Clipper components in Chromium',results},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
