const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http'),{DatabaseSync}=require('node:sqlite');
async function run(){
 const output=path.resolve('work/data-ui');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),target=await fs.mkdtemp(path.join(output,'target-')),backups=await fs.mkdtemp(path.join(output,'backups-'));
 const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 let auth='';const server=http.createServer((req,res)=>{auth=req.headers.authorization;res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'fixture-model'}]}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app;
 const options=process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env};
 try{
  const helperPage=await helper.firstWindow();app=await electron.launch(options);let page=await app.firstWindow();await page.waitForSelector('#search');const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await helper.evaluate(({clipboard})=>clipboard.writeText('Storage migration fixture'));await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.length).toBe(1);const clip=(await page.evaluate(()=>window.clipper.state())).clips[0];
  await page.evaluate(async id=>{await window.clipper.action(id,'favorite');await window.clipper.action(id,'enqueue');await window.clipper.snippet({title:'持久回复',text:'持久内容'});await window.clipper.category({name:'迁移分类',color:'#7b8e9c',kind:'text',contains:'',source:'',tag:''});},clip.id);
  const custom=await page.evaluate(()=>window.clipper.saveScript({name:'迁移脚本',description:'fixture',code:'return input.toUpperCase();',timeoutMs:1000,permission:'selected-text'}));
  const aiId=await page.evaluate(base=>window.clipper.aiProfile({name:'迁移服务',kind:'openai',baseUrl:base,model:'fixture-model',maxTokens:128,timeoutSeconds:5,temperature:null,tokenField:'max_tokens',apiKey:'migration-api-key-fixture'}),'http://127.0.0.1:'+server.address().port+'/v1');
  const png=await helperPage.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=80;const x=c.getContext('2d');x.fillStyle='#4167a4';x.fillRect(0,0,120,80);return c.toDataURL().split(',')[1];});await helper.evaluate(async({clipboard,ClipboardItem},png)=>clipboard.write([new ClipboardItem({'image/png':new Blob([Buffer.from(png,'base64')],{type:'image/png'})})]),png);
  await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.length).toBe(2);const imageId=(await page.evaluate(()=>window.clipper.state())).clips.find(c=>c.kind==='image').id;await page.evaluate(async id=>{await window.clipper.batch([id],'shelf');await window.clipper.snippet({title:'图片模板',clipId:id});},imageId);
  await page.evaluate(()=>window.clipper.webStart({host:'127.0.0.1',minutes:5,follow:false}));
  console.log('Migration: confirmation, full state, continued capture and encrypted service credentials');
  await page.locator('[data-page=data]').click();await expect(page.locator('#storage-directory')).toHaveText(profile);await app.evaluate(({dialog},directory)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[directory]});},target);await page.locator('#migrate-storage').click();await expect(page.locator('.modal-heading')).toContainText('迁移');assert.equal((await page.evaluate(()=>window.clipper.dataState())).directory,profile);await page.screenshot({path:path.join(output,'migration-preview.png')});await page.locator('#dialog [type=submit]').click();await expect(page.locator('#storage-directory')).toHaveText(target);
  assert.equal((await page.evaluate(()=>window.clipper.webState())).running,false);
  const state=await page.evaluate(()=>window.clipper.state());assert.equal(state.clips.length,2);assert.deepEqual(state.queue,[clip.id]);assert.deepEqual(state.shelf,[imageId]);assert.equal(state.snippets.length,2);assert.equal(state.categories.length,1);assert.equal((await page.evaluate(()=>window.clipper.scripts())).some(s=>s.id===custom),true);
  await page.evaluate(id=>window.clipper.aiModels(id,crypto.randomUUID()),aiId);assert.equal(auth,'Bearer migration-api-key-fixture');
  await helper.evaluate(({clipboard})=>clipboard.writeText('Captured after migration'));await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.length).toBe(3);const oldDb=new DatabaseSync(path.join(profile,'history.sqlite'),{readOnly:true});try{assert.equal(oldDb.prepare('SELECT count(*) n FROM clips').get().n,2);}finally{oldDb.close();}
  console.log('Automatic backup: real DPAPI persistence, encrypted output and file retention');
  await app.evaluate(({dialog},directory)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[directory]});},backups);await page.locator('#backup-choose-folder').click();await page.locator('#backup-enabled').check();await page.locator('#backup-keep').fill('2');await page.locator('#backup-password').fill('automatic fixture recovery password');await page.locator('#backup-password-repeat').fill('automatic fixture recovery password');await page.locator('#save-backup-settings').click();await expect(page.locator('#backup-now')).toBeEnabled();await page.locator('#backup-now').click();await expect(page.locator('.backup-entry')).toHaveCount(1);await page.screenshot({path:path.join(output,'data-backup-light.png')});
  let data=await page.evaluate(()=>window.clipper.dataState());assert.equal(data.backup.hasPassword,true);assert.equal(JSON.stringify(data).includes('automatic fixture recovery password'),false);const encrypted=await fs.readFile(path.join(backups,data.entries[0].name));assert.equal(encrypted.includes(Buffer.from('Storage migration fixture')),false);
  const raw=Buffer.concat(await Promise.all(['history.sqlite','history.sqlite-wal'].map(n=>fs.readFile(path.join(target,n)).catch(()=>Buffer.alloc(0)))));assert.equal(raw.includes(Buffer.from('automatic fixture recovery password')),false);assert.equal(raw.includes(Buffer.from('migration-api-key-fixture')),false);
  await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},path.join(target,'history.sqlite'));await assert.rejects(()=>page.evaluate(()=>window.clipper.exportProtected()),/不能覆盖/);
  await fs.rename(backups,backups+'-offline');await assert.rejects(()=>page.evaluate(()=>window.clipper.backupNow()));await expect.poll(async()=>(await page.evaluate(()=>window.clipper.dataState())).backup.lastError).not.toBe('');await fs.rename(backups+'-offline',backups);await page.evaluate(()=>window.clipper.backupNow());assert.equal((await page.evaluate(()=>window.clipper.dataState())).backup.lastError,'');
  const manual=path.join(output,'manual-'+path.basename(profile)+'.clipper');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},manual);await page.locator('#protected-export').click();await page.locator('#export-password').fill('manual fixture recovery password');await page.locator('#export-repeat').fill('manual fixture recovery password');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible();assert.equal((await fs.stat(manual)).size>0,true);
  console.log('Restore: incorrect password, checked preview, cancellation and merge'); await page.evaluate(()=>{window.restoreCloseHeadings=[];document.querySelector('#dialog').addEventListener('close',()=>window.restoreCloseHeadings.push(document.querySelector('.modal-heading h2').textContent));});
  await page.evaluate(async()=>{const s=await window.clipper.state();await window.clipper.batch(s.clips.map(c=>c.id),'delete');for(const reply of s.snippets)await window.clipper.removeSnippet(reply.id);for(const category of s.categories)await window.clipper.removeCategory(category.id);});await page.evaluate(id=>window.clipper.removeScript(id),custom);await helper.evaluate(({clipboard})=>clipboard.writeText('New local item must survive restoration'));await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.length).toBe(1);
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},manual);await page.locator('#restore-file').click();await page.locator('#restore-password').fill('incorrect password');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#modal-error')).toContainText('密码不正确');assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);await page.locator('#restore-password').fill('manual fixture recovery password');await page.locator('#dialog [type=submit]').click();await expect(page.locator('.restore-summary')).toBeVisible();await page.screenshot({path:path.join(output,'restore-preview.png')});assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);await page.locator('#modal-cancel').click();assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);
  await page.locator('#restore-file').click();await page.locator('#restore-password').fill('manual fixture recovery password');await page.locator('#dialog [type=submit]').click();await expect(page.locator('.restore-summary')).toBeVisible();await page.locator('#dialog [type=submit]').click();await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.length).toBe(4);const restored=await page.evaluate(()=>window.clipper.state());assert.equal(restored.snippets.length,2);assert.equal(restored.categories.length,1);assert.equal(restored.clips.some(c=>c.preview==='New local item must survive restoration'),true);assert.equal((await page.evaluate(()=>window.clipper.scripts())).some(s=>s.name==='迁移脚本'),true);
  await expect.poll(()=>page.evaluate(()=>window.restoreCloseHeadings.length)).toBe(4);assert.deepEqual(await page.evaluate(()=>window.restoreCloseHeadings),['解锁备份','备份校验通过','解锁备份','备份校验通过']);console.log('Restart: custom directory and overdue automatic backup without re-entering the password');
  const priorSuccess=(await page.evaluate(()=>window.clipper.dataState())).backup.lastSuccess;await app.close();const database=new DatabaseSync(path.join(target,'history.sqlite'));try{const saved=JSON.parse(database.prepare("SELECT value FROM meta WHERE key='automatic-backup'").get().value);saved.nextAt=1;database.prepare("UPDATE meta SET value=? WHERE key='automatic-backup'").run(JSON.stringify(saved));}finally{database.close();}
  app=await electron.launch(options);page=await app.firstWindow();await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clipper.dataState())).directory,target);assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,4);await expect.poll(async()=>(await page.evaluate(()=>window.clipper.dataState())).backup.lastSuccess,{timeout:20000}).toBeGreaterThan(priorSuccess);assert.equal((await page.evaluate(()=>window.clipper.dataState())).entries.length,2);await page.evaluate(id=>window.clipper.aiModels(id,crypto.randomUUID()),aiId);assert.equal(auth,'Bearer migration-api-key-fixture');
  await page.locator('[data-page=settings]').click();await page.locator('[data-theme-choice=dark]').click();await page.locator('#save-settings').click();await page.locator('[data-page=data]').click();await expect(page.locator('.backup-entry')).toHaveCount(2);await page.screenshot({path:path.join(output,'data-backup-dark.png')});assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,migrationPreservesFullState:true,oldDirectoryRetained:true,captureContinues:true,serviceKeyAfterMigration:true,encryptedManualAndAutomaticBackup:true,actualDPAPI:true,previewBeforeRestore:true,wrongPasswordNoWrites:true,mergeKeepsNewData:true,restartCustomDirectory:true,overdueBackupOnRestart:true,profile,target,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
