const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const delivery=path.resolve('../delivery-0.35.0'),built=path.join(delivery,'release/0.35.0/win-unpacked'),outputs='C:/Users/ruida/Documents/Codex/2026-10-01/c/outputs',target=path.join(outputs,'Clipper-0.35.0-win-x64');
const read=file=>JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'')),hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const files=(folder,prefix='')=>fs.readdirSync(folder,{withFileTypes:true}).flatMap(e=>{assert(!e.isSymbolicLink(),'Unexpected link: '+e.name);return e.isDirectory()?files(path.join(folder,e.name),prefix+e.name+'/'):[prefix+e.name];});
const baseline=read('work/checkpoints/package/results.json'),runtime=read('work/version-027/package-results.json'),packaged=read('work/package-035/results.json'),ui=read('work/ui-028/results.json'),native=read('work/ui-028/native-results.json'),search=read('work/search-029/results.json'),packagedSearch=read('work/package-035/search-results.json'),transfer=read('work/transfer-032/results.json'),packagedTransfer=read('work/package-035/transfer-results.json'),components=read('work/components-030/results.json'),media=read('work/language-media/layout-results.json'),clipboard=read('work/clipboard-033/results.json'),packagedClipboard=read('work/package-035/clipboard-results.json');
const preview=read('work/preview-035/behavior.json'),nativePreview=read('work/preview-035/packaged.json'),beforePreview=read('work/preview-035/before-small.json'),afterPreview=read('work/preview-035/after-small.json'),largePreview=read('work/preview-035/after.json');assert(preview.passed&&preview.cases===16&&nativePreview.passed&&nativePreview.version==='0.35.0'&&nativePreview.CSP&&beforePreview.passed&&afterPreview.passed&&largePreview.passed&&largePreview.results.every(r=>r.bytes<=1048576&&r.detailCalls===0));
const actions=read('work/actions-034/results.json'),surfaces=read('work/actions-034/surfaces.json'),nativeActions=read('work/actions-034/packaged.json');assert(actions.passed&&actions.cases===35&&actions.encoding.every(v=>v.equal));assert(surfaces.passed&&surfaces.cases===12);assert(nativeActions.passed&&nativeActions.version==='0.35.0'&&nativeActions.hidden&&nativeActions.pixelEquality);
assert(components.passed&&components.cases===16);assert(media.cases===48&&media.errors.length===0&&media.failures.length===0);assert(clipboard.passed&&packagedClipboard.passed&&packagedClipboard.cancelledWithoutOpening&&packagedClipboard.recoveredAfterCancel&&packagedClipboard.mixedFormatBlocks===37);assert(baseline.passed&&baseline.version==='0.35.0');assert(runtime.passed&&runtime.version==='0.35.0'&&runtime.packagedSyncWorker&&runtime.packagedRustHelper);assert(packaged.passed&&packaged.version==='0.35.0'&&packaged.packagedImageTransfer&&packaged.packagedClipboardMemory);assert.equal(ui.errors.length,0);assert.equal(ui.cases,120);assert.equal(native.errors.length,0);assert(native.fontFaceLoaded);assert(search.passed&&search.cases===16);assert(packagedSearch.passed&&packagedSearch.cases===9);assert(transfer.passed&&packagedTransfer.passed&&packagedTransfer.resumedCache&&packagedTransfer.protectedExport);
assert.match(fs.readFileSync('work/core-035.log','utf8'),/# pass 339\r?\n# fail 0/);assert.equal(fs.readFileSync('work/typecheck-035.log','utf8').trim(),'');assert.equal(read('work/language-entry/bindings-review.json').unbound.length,0);assert.equal(read('work/language-entry/bindings-review.json').files.length,145);assert.equal(read('work/language-coverage.json').missing.length,0);
const signature=read('../delivery-0.35.0/work/signature-035.json');assert.equal(signature.Status,2);const executable=path.join(built,'Clipper.exe');const shippedVersion=execFileSync(executable,['-e','process.stdout.write(require('+JSON.stringify(path.join(built,'resources/app.asar/package.json'))+').version)'],{env:{...process.env,ELECTRON_RUN_AS_NODE:'1'},windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(shippedVersion,'0.35.0');
assert.equal(hash(path.join(built,'resources/app.asar')),baseline.asarSHA256);assert(!fs.existsSync(target),'Existing deliveries are immutable');fs.mkdirSync(outputs,{recursive:true});const expected=files(built);fs.cpSync(built,target,{recursive:true,force:false,errorOnExist:true});assert.deepEqual(files(target).sort(),expected.sort());for(const file of expected)assert.equal(hash(path.join(target,file)),hash(path.join(built,file)),file);
const source=path.resolve('work/package-035/source'),verify=path.resolve('work/package-035/source-verify'),zip=path.join(outputs,'Clipper-0.35.0-source.zip'),folders=['assets','build','docs','installer-ui','licenses','scripts','src','tests'],roots=fs.readdirSync(process.cwd(),{withFileTypes:true}).filter(e=>e.isFile()).map(e=>e.name);
assert(!fs.existsSync(source)&&!fs.existsSync(verify)&&!fs.existsSync(zip));fs.mkdirSync(source,{recursive:true});for(const folder of folders){for(const file of files(folder))assert.equal(hash(path.join(folder,file)),hash(path.join(delivery,folder,file)),folder+'/'+file);fs.cpSync(folder,path.join(source,folder),{recursive:true});}for(const file of roots){assert.equal(hash(file),hash(path.join(delivery,file)),file);fs.copyFileSync(file,path.join(source,file));}
fs.mkdirSync(path.join(source,'validation'));const validations=[['work/preview-035/behavior.json','preview-behavior.json'],['work/preview-035/packaged.json','packaged-preview.json'],['work/preview-035/before-small.json','preview-before.json'],['work/preview-035/after-small.json','preview-after.json'],['work/preview-035/after.json','preview-large.json'],['work/daily-process-memory-035.json','uncontrolled-daily-memory.json'],['work/actions-034/results.json','async-actions.json'],['work/actions-034/surfaces.json','async-surfaces.json'],['work/actions-034/packaged.json','packaged-actions.json'],['work/components-030/results.json','one-components.json'],['work/language-media/layout-results.json','media.json'],['work/clipboard-033/results.json','clipboard.json'],['work/package-035/clipboard-results.json','packaged-clipboard.json'],['../delivery-0.35.0/work/signature-035.json','signature.json'],['work/core-035.log','logic.log'],['work/typecheck-035.log','typecheck.log'],['work/language-coverage.json','language.json'],['work/language-entry/bindings-review.json','language-bindings.json'],['work/ui-028/results.json','ui.json'],['work/search-029/results.json','search.json'],['work/ui-028/native-results.json','native-font.json'],['work/transfer-032/results.json','transfer.json'],['work/package-035/transfer-results.json','packaged-transfer.json'],['work/checkpoints/package/results.json','packaged-baseline.json'],['work/version-027/package-results.json','packaged-previous-features.json'],['work/package-035/results.json','packaged-ui.json'],['work/package-035/search-results.json','packaged-search.json']];for(const [file,name]of validations)fs.copyFileSync(file,path.join(source,'validation',name));
const seven='C:/Users/ruida/AppData/Local/electron-builder/Cache/7zip@1.0.0/7zip-win-x64-a34pt/bin/7za.exe';execFileSync(seven,['a','-tzip','-mcu=on',zip,...folders,...roots,'validation'],{cwd:source,windowsHide:true,stdio:'ignore',timeout:60000});execFileSync(seven,['x',zip,'-o'+verify,'-y'],{windowsHide:true,stdio:'ignore',timeout:60000});assert.deepEqual(files(source).sort(),files(verify).sort());for(const file of files(source))assert.equal(hash(path.join(source,file)),hash(path.join(verify,file)),file);
const report={passed:true,version:'0.35.0',program:{executable:path.join(target,'Clipper.exe'),files:expected.length,asarSHA256:baseline.asarSHA256,allFilesVerified:true,actualExecutableVersion:shippedVersion,inventory:expected.map(file=>({file,bytes:fs.statSync(path.join(target,file)).size,sha256:hash(path.join(target,file))}))},source:{files:files(source).length,bytes:fs.statSync(zip).size,sha256:hash(zip),exactContentVerified:true},validation:{previewBehaviorGroups:16,preview,nativePreview,beforePreview,afterPreview,largePreview,asyncActionCases:47,asyncActions:actions,asyncSurfaces:surfaces,packagedAsyncActions:nativeActions,logic:339,mediaFeedback:48,clipboardMemory:clipboard,packagedClipboardMemory:packagedClipboard,basicComponentComparison:components,UI:120,search:16,languageBindingFiles:145,packagedSearchGroups:9,installedFonts:native.fonts,packagedBuildFiles:baseline.builtFilesVerified,packagedRuntime:runtime,packagedUI:packaged,transfer,packagedTransfer,unchangedUIReference:'120 UI, 48 media feedback and 16 current One component comparisons were rerun; complete 348 layout, feedback and motion baselines are carried from 0.32/0.31 and are not counted as current reruns'},limitations:{systemClipboard:false,desktopInput:false,physicalTwoDeviceSync:false,desktopDwmPixels:false,controlledResidentMemory:false,signature:'NotSigned',publicRelease:false}};
fs.writeFileSync(path.join(outputs,'Clipper-0.35.0-交付校验.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(outputs,'Clipper-0.35.0-SHA256SUMS.txt'),[[zip,path.basename(zip)],[path.join(target,'Clipper.exe'),'Clipper-0.35.0-win-x64/Clipper.exe'],[path.join(target,'resources/app.asar'),'Clipper-0.35.0-win-x64/resources/app.asar']].map(([file,name])=>hash(file)+'  '+name).join('\n')+'\n');
for(const [file,name]of [['work/search-029/zh-CN-light.png','全部记录'],['work/ui-028/zh-CN-tray-740.png','最近记录'],['work/ui-028/zh-CN-shelf-420.png','拖放窗口'],['work/ui-028/settings-1.png','外观设置'],['work/ui-028/settings-2.png','界面语言'],['work/ui-028/sync-0.png','局域网同步']])fs.copyFileSync(file,path.join(outputs,'Clipper-0.35.0-'+name+'.png'));
for(const [file,label]of [['image-saving','图片保存'],['shelf-copying','容器复制'],['recent-copying','最近记录复制']])fs.copyFileSync('work/actions-034/'+file+'.png',path.join(outputs,'Clipper-0.35.0-'+label+'.png'));
fs.writeFileSync(path.join(outputs,'Clipper-0.35.0-交付说明.md'),`# Clipper 0.35.0

从旧版托盘退出后，运行完整目录里的 Clipper.exe。移动时保留整个目录，无需安装。

本轮从 One 0.16.4 实际源码迁移全文阅读组件，代码和长文字支持完整查找、选择复制、语法高亮及自动换行。记录和快捷回复均接入。后台刷新不重新加载未变化的详情，切页释放阅读器并拦截旧请求。短普通文字继续使用轻量预览，阅读器和语法包按需加载。

原记录和主操作复制/粘贴保持完整；阅读器选择复制采用 LF 换行。文字入库上限仍为 UTF-8 1 MiB。

339 项逻辑、16 组全文预览、47 项异步操作、120 项页面控件、48 项媒体反馈、16 项搜索及 16 项 One 基础组件比对通过；类型和145个语言绑定文件检查通过。实际 Electron 隐藏沙箱及打包后 ASAR 的模块、样式、worker、CSP和全文查找通过。程序与源码逐文件核对。

同样的 80500 字符单行样本，五次后台刷新最大定时器间隔从约 570 ms 到约 9 ms，重复详情请求由5次降为0次。阅读器增加少量 JavaScript 堆开销，其他多行/代码首次加载也增加模块开销；不能声称全部场景更快或全应用内存全面下降。详细范围见 docs/验收-0.35.0.md 和交付校验报告。

未操作系统剪贴板、物理键鼠或日常资料；真实桌面拖放和整机受控内存未复测。未签名、未公开发布。全套348项布局与动效基线沿用以前版本，不计为本轮重测。
`);
console.log(JSON.stringify({passed:true,version:shippedVersion,executable:report.program.executable,programFiles:expected.length,sourceFiles:report.source.files,sourceBytes:report.source.bytes,sourceSHA256:report.source.sha256,asarSHA256:baseline.asarSHA256}));
