const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function gesture(driver,points,release=true){return driver.evaluate(async({app,screen},{points,release})=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)'),foreground=u.func('uintptr_t __stdcall GetForegroundWindow()'),pid=u.func('uint32 __stdcall GetWindowThreadProcessId(uintptr_t,_Out_ uint32*)'),observations=[],wait=ms=>new Promise(r=>setTimeout(r,ms));const mouse=(p,flags)=>{p=screen.dipToScreenPoint({x:Math.round(p.x),y:Math.round(p.y)});const b=Buffer.alloc(40);b.writeInt32LE(Math.round((p.x-metric(76))*65535/(metric(78)-1)),8);b.writeInt32LE(Math.round((p.y-metric(77))*65535/(metric(79)-1)),12);b.writeUInt32LE(flags|0xc001,20);if(send(1,b,40)!==1)throw Error('Mouse input rejected')};try{mouse(points[0],0);await wait(150);mouse(points[0],2);await wait(100);{const id=[0];pid(foreground(),id);observations.push(id[0]);}for(let j=1;j<points.length;j++){const from=points[j-1],to=points[j];for(let i=1;i<=18;i++){mouse({x:from.x+(to.x-from.x)*i/18,y:from.y+(to.y-from.y)*i/18},0);await wait(30)}if(to.wait)await wait(to.wait);if(to.mark){const id=[0];pid(foreground(),id);observations.push(id[0]);}}}finally{if(release)mouse(points.at(-1),4);}return observations;},{points,release});}
async function run(){const output=path.resolve('work/desktop-drag');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;let app,originalCursor;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});
 try{await helper.firstWindow();originalCursor=await helper.evaluate(({screen})=>screen.getCursorScreenPoint());app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');await app.evaluate(({app})=>app.on('browser-window-created',(_event,w)=>w.on('show',()=>{if(w.webContents.getURL().endsWith('/shelf.html'))w.setAlwaysOnTop(true,'screen-saver');})));const d=(await page.evaluate(()=>window.clipper.desktopState())).displays[0],a=d.workArea;const file=path.join(output,'OLE-文件.txt'),content='通过 Windows 原生拖放进入顶部容器';await fs.writeFile(file,content);
 const sourceEvent=helper.waitForEvent('window');await helper.evaluate(async({BrowserWindow,ipcMain,nativeImage},{file,preload,a,icon})=>{global.helperWindow.hide();ipcMain.on('desktop-fixture:drag',event=>event.sender.startDrag({file,files:[file],icon:nativeImage.createFromPath(icon).resize({width:48})}));global.sourceWindow=new BrowserWindow({x:a.x+30,y:a.y+160,width:430,height:430,title:'Clipper 原生拖放验收',webPreferences:{preload,sandbox:true,contextIsolation:true}});await global.sourceWindow.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<body style="font:15px Segoe UI;margin:20px"><h2>文件拖放验收</h2><div id="source" draggable="true" style="padding:30px;background:#e4ebf4;border:1px solid #9aaac1">把这个文件拖至顶部中央</div><div id="target" style="padding:25px;background:#eee;margin-top:25px;min-height:80px">文件拖出接收区</div><script>document.getElementById("source").ondragstart=e=>{e.preventDefault();window.desktopFixture.drag()};window.drops=[];document.addEventListener("dragover",e=>{e.preventDefault();e.dataTransfer.dropEffect="copy"});document.addEventListener("drop",async e=>{e.preventDefault();for(const f of e.dataTransfer.files)window.drops.push({name:f.name,size:f.size,text:f.type.startsWith("text")?await f.text():null})});</script>'));},{file,preload:path.resolve('tests/desktop-fixture-preload.cjs'),a,icon:path.resolve('assets/clipper.png')});const source=await sourceEvent;await source.waitForSelector('#source');
 await page.evaluate(async id=>window.clipper.configureDesktop({... (await window.clipper.desktopState()).options,dockEnabled:false,shelfTop:true,shelfOnTop:true,displayId:id,dwellMs:200}),d.id);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.hide()));await helper.evaluate(()=>{global.sourceWindow.setAlwaysOnTop(true,'screen-saver');global.sourceWindow.show();global.sourceWindow.focus()});const local=await source.locator('#source').boundingBox(),sourceBounds=await helper.evaluate(()=>global.sourceWindow.getContentBounds()),from={x:sourceBounds.x+local.x+local.width/2,y:sourceBounds.y+local.y+local.height/2},top={x:a.x+a.width/2,y:a.y+2,wait:1000,mark:true},target={x:top.x,y:a.y+190,wait:400};
 console.log('Native OLE: external file triggers top shelf during held drag');const opened=app.waitForEvent('window');const focused=await gesture(app,[from,top,target]);const shelf=await opened;await shelf.waitForSelector('#items');await expect(shelf.locator('.shelf-row')).toHaveCount(1);const item=(await shelf.evaluate(()=>window.clipperShelf.state())).items[0],detail=await page.evaluate(id=>window.clipper.detail(id),item.id);assert.deepEqual(detail.payload.files,[file]);assert.equal(await fs.readFile(file,'utf8'),content);assert.equal(focused[1],focused[0]);
 await shelf.screenshot({path:path.join(output,'top-drop.png')});
 console.log('Native OLE: shelf file and image drag out to another process');
 const dragOut=async id=>{await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html'));w.show();w.focus()});const row=await shelf.locator(`[data-id="${id}"]`).boundingBox(),b=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).getContentBounds()),box=await source.locator('#target').boundingBox();await gesture(helper,[{x:b.x+row.x+90,y:b.y+row.y+row.height/2},{x:sourceBounds.x+box.x+box.width/2,y:sourceBounds.y+box.y+box.height/2,wait:400}]);};
 await dragOut(item.id);await expect.poll(()=>source.evaluate(()=>window.drops)).toEqual([{name:path.basename(file),size:Buffer.byteLength(content),text:content}]);
 await shelf.evaluate(()=>{const input=document.createElement('input');input.id='image';input.type='file';document.body.appendChild(input)});await shelf.locator('#image').setInputFiles(path.resolve('assets/clipper.png'));await shelf.evaluate(()=>window.clipperShelf.dropFiles([...document.getElementById('image').files]));await expect(shelf.locator('.shelf-row')).toHaveCount(2);const img=(await shelf.evaluate(()=>window.clipperShelf.state())).items.find(c=>c.kind==='image'),original=await page.evaluate(id=>window.clipper.detail(id),img.id);await source.evaluate(()=>window.drops=[]);await dragOut(img.id);await expect.poll(()=>source.evaluate(()=>window.drops)).toEqual([{name:'Clipper-'+original.hash+'.png',size:Buffer.from(original.payload.png,'base64').length,text:null}]);
 await helper.evaluate(()=>{global.sourceWindow.show();global.sourceWindow.focus()});await gesture(helper,[{x:sourceBounds.x+10,y:sourceBounds.y+10},{x:sourceBounds.x+40,y:sourceBounds.y+10}]);await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).isVisible())).toBe(false);assert.equal(await fs.readFile(file,'utf8'),content);
 console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,nativeTopActivation:true,nativeExternalFileIn:true,noFocusTheft:true,nativeFileOut:true,nativeImageOut:true,autoShelfHides:true,sourceUnchanged:true,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(({clipboard})=>global.restoreClipboard());await helper.evaluate(({app,screen},point)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),koffi=req('koffi'),u=koffi.load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),set=u.func('bool __stdcall SetCursorPos(int,int)'),b=Buffer.alloc(40);b.writeUInt32LE(4,20);send(1,b,40);if(point){const p=screen.dipToScreenPoint(point);set(p.x,p.y)}return true},originalCursor).catch(()=>{});await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
