const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const sameBounds=(actual,expected)=>{for(const key of ['x','y','width','height'])assert.ok(Math.abs(actual[key]-expected[key])<=2,JSON.stringify({actual,expected}));};
async function run(){
 const output=path.resolve('work/desktop-ui');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const launch=()=>electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app,originalCursor,errors=[];
 const watch=p=>p.on('pageerror',e=>errors.push(e.message));
 try{await helper.firstWindow();originalCursor=await helper.evaluate(({screen})=>screen.getCursorScreenPoint());app=await launch();let page=await app.firstWindow();watch(page);await page.waitForSelector('#search');
  const initial=await page.evaluate(()=>window.clipper.desktopState());assert.equal(initial.options.dockEnabled,false);assert.equal(initial.options.shelfTop,false);const display=initial.displays[0],a=display.workArea;
  const configure=async patch=>page.evaluate(async patch=>window.clipper.configureDesktop({... (await window.clipper.desktopState()).options,...patch}),patch);
  const move=async(point,button=0)=>helper.evaluate(({app,screen},{point,button})=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)'),p=screen.dipToScreenPoint(point),b=Buffer.alloc(40);b.writeInt32LE(Math.round((p.x-metric(76))*65535/(metric(78)-1)),8);b.writeInt32LE(Math.round((p.y-metric(77))*65535/(metric(79)-1)),12);b.writeUInt32LE(button|0xc001,20);if(send(1,b,40)!==1)throw Error('Mouse input rejected');},{point,button});
  console.log('Collection: vertical navigation, scroll and search caret');
  await page.evaluate(async()=>{for(let i=0;i<30;i++)await window.clipper.saveOcr(`灵感 ${String(i+1).padStart(2,'0')} · 在手边留住每次复制\n需求梳理、设计片段与待办，按自己的节奏整理。\n横向卡片内容 ${i}`);});
  assert.equal(await page.locator('#grid-view,#list-view,#card-direction').count(),0);await expect(page.locator('.clip-row')).toHaveCount(30);await page.locator('.clip-row').first().click();await page.locator('#results').focus();const first=await page.locator('.clip-row.selected').getAttribute('data-id');await page.keyboard.press('ArrowDown');assert.notEqual(await page.locator('.clip-row.selected').getAttribute('data-id'),first);await page.locator('#results').evaluate(el=>el.scrollTop=500);const anchor=await page.locator('#results').evaluate(el=>{const r=el.getBoundingClientRect(),row=document.elementFromPoint(r.left+24,r.top+12)?.closest('.clip-row');return {id:row?.dataset.id,top:row?.getBoundingClientRect().top};});assert.ok(anchor.id);await page.evaluate(()=>window.clipper.saveOcr('内容更新时保留滚动位置'));await delay(300);const retained=await page.locator(`[data-id="${anchor.id}"]`).evaluate(el=>el.getBoundingClientRect().top);assert.ok(Math.abs(retained-anchor.top)<2,JSON.stringify({anchor,retained}));
  await page.locator('#search').fill('灵感');await expect(page.locator('.clip-row')).toHaveCount(30);await page.locator('#search').evaluate(el=>el.setSelectionRange(1,1));const selection=await page.locator('.clip-row.selected').getAttribute('data-id');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#search').evaluate(el=>el.selectionStart),0);assert.equal(await page.locator('.clip-row.selected').getAttribute('data-id'),selection);await page.locator('#search').fill('');
  await expect(page.locator('.clip-row')).toHaveCount(31);assert.equal(await page.locator('#result-count').count(),0);await page.locator('.clip-row').first().evaluate(el=>el.scrollIntoView({block:'nearest'}));await page.screenshot({path:path.join(output,'collection-list.png')});assert.equal(await page.locator('.clip-row').nth(0).evaluate(el=>el.getBoundingClientRect().left),await page.locator('.clip-row').nth(1).evaluate(el=>el.getBoundingClientRect().left));
  console.log('Settings: controls, duplicate and OS hotkey conflict rollback');
  await page.locator('[data-page=settings]').click();await page.locator('#desktop-dockEnabled').check();await expect.poll(()=>page.evaluate(async()=> (await window.clipper.desktopState()).options.dockEnabled)).toBe(true);await page.locator('#desktop-edge').evaluate(node=>{node.value='right';node.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('#desktop-dwell').evaluate(node=>{node.value='200';node.dispatchEvent(new Event('change',{bubbles:true}));});await expect.poll(()=>page.evaluate(async()=> (await window.clipper.desktopState()).options.dwellMs)).toBe(200);await page.screenshot({path:path.join(output,'desktop-settings.png')});
  const before=(await page.evaluate(()=>window.clipper.desktopState())).options;assert.match(await page.evaluate(async()=>{try{await window.clipper.configureDesktop({... (await window.clipper.desktopState()).options,shelfShortcut:(await window.clipper.state()).settings.shortcut});return 'allowed'}catch(e){return e.message}}),/不能重复/);assert.deepEqual((await page.evaluate(()=>window.clipper.desktopState())).options,before);
  assert.equal(await helper.evaluate(({globalShortcut})=>globalShortcut.register('Control+Shift+F11',()=>{})),true);assert.match(await page.evaluate(async()=>{try{await window.clipper.configureDesktop({... (await window.clipper.desktopState()).options,shelfShortcut:'Control+Shift+F11'});return 'allowed'}catch(e){return e.message}}),/已被占用/);assert.deepEqual((await page.evaluate(()=>window.clipper.desktopState())).options,before);assert.equal(await app.evaluate(({globalShortcut},key)=>globalShortcut.isRegistered(key),before.shelfShortcut),true);await helper.evaluate(({globalShortcut})=>globalShortcut.unregisterAll());
  console.log('Dock: four real window positions and hover without focus theft');
  let quick;for(const edge of ['left','right','top','bottom']){await configure({dockEdge:edge,displayId:display.id});const quickEvent=quick?null:app.waitForEvent('window');await page.evaluate(()=>window.clipper.showQuick());if(quickEvent){quick=await quickEvent;watch(quick);}await quick.waitForSelector('#search');await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/tray.html')).isVisible())).toBe(true);const b=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/tray.html')).getBounds());console.log('dock',JSON.stringify({edge,b,a}));assert.ok(b.x>=a.x-2&&b.y>=a.y-2&&b.x+b.width<=a.x+a.width+2&&b.y+b.height<=a.y+a.height+2);if(edge==='left')assert.ok(Math.abs(b.x-a.x)<=2);if(edge==='right')assert.ok(Math.abs(b.x+b.width-a.x-a.width)<=2);if(edge==='top')assert.ok(Math.abs(b.y-a.y)<=2);if(edge==='bottom')assert.ok(Math.abs(b.y+b.height-a.y-a.height)<=2);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/tray.html')).hide());}
  await configure({dockEdge:'right',autoHide:true});await helper.evaluate(()=>global.focusTarget());await helper.evaluate(()=>global.helperWindow.setAlwaysOnTop(false));assert.equal(await helper.evaluate(()=>global.helperWindow.isFocused()),true);await move({x:a.x+100,y:a.y+200});await delay(350);await move({x:a.x+a.width-1,y:a.y+Math.floor(a.height/2)});
  const visible=()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/tray.html')).isVisible());await expect.poll(visible).toBe(true);assert.equal(await helper.evaluate(()=>global.helperWindow.isFocused()),true);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/tray.html')).isFocused()),false);await quick.screenshot({path:path.join(output,'edge-panel.png')});await move({x:a.x+80,y:a.y+200});await expect.poll(visible).toBe(false);
  await helper.evaluate((_,bounds)=>{global.helperWindow.setFullScreen(false);global.helperWindow.setBounds({x:bounds.x+100,y:bounds.y+100,width:650,height:420});global.helperWindow.setFullScreen(true);global.helperWindow.focus()},display.bounds);await delay(400);sameBounds(await helper.evaluate(()=>global.helperWindow.getBounds()),display.bounds);await move({x:a.x+a.width-1,y:a.y+400});await delay(650);assert.equal(await visible(),false);await helper.evaluate(()=>global.helperWindow.setFullScreen(false));await move({x:a.x+100,y:a.y+200});await delay(300);
  console.log('Shelf: independent API, text/file/image content, membership and source preservation');
  await configure({dockEnabled:false});await page.locator('[data-page=shelf]').click();const shelfEvent=app.waitForEvent('window');await page.locator('#open-shelf').click();const shelf=await shelfEvent;watch(shelf);await shelf.waitForSelector('#items');assert.equal(await shelf.evaluate(()=>typeof window.clipper),'undefined');await shelf.evaluate(()=>window.clipperShelf.dropText('<script>window.injected=true</script>\n文字也可以留在容器中'));await expect(shelf.locator('.shelf-row')).toHaveCount(1);assert.equal(await shelf.evaluate(()=>window.injected),undefined);
  const file=path.join(output,'shelf-source.txt');await fs.writeFile(file,'Keep the source file unchanged');await shelf.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='files';document.body.appendChild(input)});await shelf.locator('#files').setInputFiles(file);await shelf.evaluate(()=>window.clipperShelf.dropFiles([...document.getElementById('files').files]));await shelf.locator('#files').setInputFiles(path.resolve('assets/clipper.png'));await shelf.evaluate(()=>window.clipperShelf.dropFiles([...document.getElementById('files').files]));await expect(shelf.locator('.shelf-row')).toHaveCount(3);assert.equal((await page.evaluate(()=>window.clipper.state())).shelf.length,3);
  const shelfItems=(await shelf.evaluate(()=>window.clipperShelf.state())).items;const image=shelfItems.find(c=>c.kind==='image'),text=shelfItems.find(c=>c.kind==='text');await shelf.evaluate(id=>window.clipperShelf.copy(id,false),text.id);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),'<script>window.injected=true</script>\n文字也可以留在容器中');await shelf.evaluate(id=>window.clipperShelf.remove(id),text.id);await assert.rejects(shelf.evaluate(id=>window.clipperShelf.copy(id,false),text.id),/已移出/);assert.ok((await page.evaluate(()=>window.clipper.state())).clips.some(c=>c.id===text.id));assert.equal(await fs.readFile(file,'utf8'),'Keep the source file unchanged');
  const denial=await app.evaluate(async({BrowserWindow,ipcMain})=>{const shelf=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')),main=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/index.html'));const result=[];for(const [name,w]of [['state',shelf],['shelf-state',main]])try{await ipcMain._invokeHandlers.get('clipper:'+name)({sender:w.webContents,senderFrame:w.webContents.mainFrame});result.push('allowed')}catch(e){result.push(e.message)}return result;});assert.deepEqual(denial,['拒绝访问','拒绝访问']);
  await shelf.locator('#top').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).isAlwaysOnTop()),false);await delay(600);let saved={x:a.x+150,y:a.y+100,width:420,height:560};await app.evaluate(({BrowserWindow},bounds)=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).setBounds(bounds),saved);await delay(700);saved=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).getBounds());console.log('Saved bounds',saved);await shelf.screenshot({path:path.join(output,'floating-shelf.png')});await page.evaluate(async()=>window.clipper.settings({... (await window.clipper.state()).settings,theme:'dark'}));await expect(shelf.locator('html')).toHaveAttribute('data-theme','dark');await shelf.screenshot({path:path.join(output,'floating-shelf-dark.png')});
  console.log('Lifecycle: screenshot hides shelf, lock destroys all content windows, unlock recreates with saved options');
  await app.evaluate(({desktopCapturer,BrowserWindow})=>{global.__captureShelfHidden=false;const get=desktopCapturer.getSources;desktopCapturer.getSources=async(...args)=>{global.__captureShelfHidden=BrowserWindow.getAllWindows().filter(w=>/index.html|shelf.html/.test(w.webContents.getURL())).every(w=>!w.isVisible());return get(...args);};});await page.evaluate(id=>window.clipper.screenshot('screen',id),display.id);assert.equal(await app.evaluate(()=>global.__captureShelfHidden),true);
  console.log('Migration: shortcut cannot read a closed store during directory handoff');
  const migrationDir=await fs.mkdtemp(path.join(output,'migrated-'));await app.evaluate(({globalShortcut,dialog},directory)=>{global.__desktopBindings=new Map();const register=globalShortcut.register.bind(globalShortcut),choose=dialog.showOpenDialog;globalShortcut.register=(key,fn)=>{global.__desktopBindings.set(key,fn);return register(key,fn)};dialog.showOpenDialog=async()=>({canceled:false,filePaths:[directory]});const io=process.getBuiltinModule('node:fs/promises'),unlink=io.unlink;io.unlink=async file=>{if(String(file).includes('.clipper-migration-')){global.__desktopMigrating=true;await new Promise(r=>setTimeout(r,1000));}return unlink(file)};global.__restoreDesktopTest=()=>{globalShortcut.register=register;dialog.showOpenDialog=choose;io.unlink=unlink;};},migrationDir);
  await page.evaluate(async()=>{await window.clipper.recordShortcut(true);await window.clipper.recordShortcut(false);});await configure({});const plan=await page.evaluate(()=>window.clipper.chooseStorage()),quickKey=(await page.evaluate(()=>window.clipper.state())).settings.quickShortcut;const migrating=page.evaluate(token=>window.clipper.migrateStorage(token),plan.token);await expect.poll(()=>app.evaluate(()=>!!global.__desktopMigrating)).toBe(true);const shortcutResult=await app.evaluate((_electron,key)=>{try{global.__desktopBindings.get(key)();return 'ok'}catch(e){return e.message}},quickKey);await migrating;await app.evaluate(()=>global.__restoreDesktopTest());assert.equal(shortcutResult,'ok');assert.equal((await page.evaluate(()=>window.clipper.dataState())).directory,migrationDir);
  const secret='desktop history fixture password';await page.evaluate(async password=>{const v=await window.clipper.prepareEncryption(password);await window.clipper.encryptHistory(v.token,v.recoveryKey);},secret);const unlockEvent=app.waitForEvent('window');await page.evaluate(()=>window.clipper.lockHistory()).catch(()=>{});const unlock=await unlockEvent;await expect(unlock.locator('#heading')).toHaveText('历史已锁定');assert.equal(shelf.isClosed(),true);assert.equal(quick.isClosed(),true);assert.equal(page.isClosed(),true);assert.equal((await app.windows()).length,1);await unlock.locator('#unlock-value').fill(secret);const reopen=app.waitForEvent('window');await unlock.locator('#unlock-submit').click();page=await reopen;watch(page);await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clipper.desktopState())).options.shelfOnTop,false);assert.equal((await app.windows()).length,1);
  const again=app.waitForEvent('window');await page.evaluate(()=>window.clipper.showShelf());const shelf2=await again;await shelf2.waitForSelector('#items');await delay(400);sameBounds(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).getBounds()),saved);assert.ok((await shelf2.evaluate(()=>window.clipperShelf.state())).items.some(c=>c.id===image.id));
  await app.close();app=await launch();const locked=await app.firstWindow();await locked.waitForSelector('#unlock-value');await locked.locator('#unlock-value').fill(secret);const restarted=app.waitForEvent('window');await locked.locator('#unlock-submit').click();page=await restarted;await page.waitForSelector('#search');const last=app.waitForEvent('window');await page.evaluate(()=>window.clipper.showShelf());await (await last).waitForSelector('#items');await delay(400);sameBounds(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/shelf.html')).getBounds()),saved);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,verticalNavigation:true,keyboardAndCaret:true,scrollPreserved:true,fourEdges:true,nativeHover:true,noFocusTheft:true,autoHide:true,fullscreenSuppression:true,hotkeyRollback:true,shelfIsolation:true,shelfTextFilesImages:true,sourceUnchanged:true,captureHidesShelf:true,lockDestroysAll:true,encryptedRestart:true,savedBounds:true,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(({clipboard})=>global.restoreClipboard());await helper.evaluate(({app,screen},point)=>{if(point){const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),koffi=req('koffi'),u=koffi.load('user32.dll'),set=u.func('bool __stdcall SetCursorPos(int,int)'),p=screen.dipToScreenPoint(point);set(p.x,p.y);}return true},originalCursor).catch(()=>{});await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
