const {test}=require('node:test'),assert=require('node:assert/strict');
const {desktopDefaults,validateDesktop,contains,clampRect,shelfCompactRect,outerEdgeAt,topShelfAt,coversDisplay,cardNavigation,validRect,dragGestureReady}=require('../work/test-exports.cjs');
const main={id:1,name:'Primary',bounds:{x:0,y:0,width:1707,height:960},workArea:{x:0,y:0,width:1707,height:912}},left={id:2,name:'Left',bounds:{x:-1920,y:-200,width:1920,height:1080},workArea:{x:-1920,y:-200,width:1920,height:1040}};
test('desktop settings migrate defaults and reject malformed timing, boolean, screen, shortcut',()=>{assert.deepEqual(validateDesktop({}),desktopDefaults);for(const value of [null,{cardDirection:'diagonal'},{shelfPosition:'center'},{displayId:Infinity},{displayId:'1'},{dwellMs:199},{dwellMs:1501},{dwellMs:400.5},{shelfTop:1},{shelfAutoDrag:1},{shelfShortcut:'D'},{shelfShortcut:'Control+Control+D'},{shelfShortcut:'Shift+'}])assert.throws(()=>validateDesktop(value));assert.equal(validateDesktop({shelfShortcut:'Super+Shift+F12'}).shelfShortcut,'Shift+Super+F12');assert.equal('dockEdge' in validateDesktop({dockEdge:'left'}),false);assert.equal('extra' in validateDesktop({extra:true}),false);});
test('auto drag ignores clicks and short movements',()=>{const start={x:100,y:100};assert.equal(dragGestureReady(start,{x:200,y:100},179),false);assert.equal(dragGestureReady(start,{x:130,y:100},300),false);assert.equal(dragGestureReady(start,{x:136,y:100},180),true);});
test('quick hover previews default on for old settings and preserve an explicit disable',()=>{
 const {quickHoverPreview,...previous}=desktopDefaults;assert.equal(quickHoverPreview,true);assert.equal(validateDesktop(previous).quickHoverPreview,true);
 assert.equal(validateDesktop({...previous,quickHoverPreview:false}).quickHoverPreview,false);
 assert.equal(validateDesktop({...previous,quickHoverPreview:true}).quickHoverPreview,true);
 for(const value of [null,0,1,'false',[],{}])assert.throws(()=>validateDesktop({...previous,quickHoverPreview:value}));
});
test('compact shelf targets the chosen corner inside each work area',()=>{for(const area of [main.workArea,left.workArea,{x:200,y:100,width:230,height:145}])for(const position of ['top-right','top-left','bottom-right','bottom-left']){const rect=shelfCompactRect(area,position);assert.ok(contains(area,{x:rect.x,y:rect.y}));assert.ok(rect.x+rect.width<=area.x+area.width&&rect.y+rect.height<=area.y+area.height);assert.equal(rect.width,Math.min(300,area.width));assert.equal(rect.height,Math.min(138,area.height));if(area.width>rect.width+40)assert.equal(position.endsWith('right'),rect.x>area.x+(area.width-rect.width)/2);if(area.height>rect.height+40)assert.equal(position.startsWith('bottom'),rect.y>area.y+(area.height-rect.height)/2);}});
test('window bounds clamp inside the work area',()=>{assert.equal(validRect({x:NaN,y:0,width:30,height:30}),false);assert.deepEqual(clampRect({x:-3000,y:-3000,width:900,height:1500},main.workArea),{x:0,y:0,width:900,height:912});});
test('edge trigger excludes shared physical boundary and corners but permits outer work-area edges',()=>{assert.equal(outerEdgeAt({x:0,y:450},main,[main,left],'left'),false);assert.equal(outerEdgeAt({x:0,y:900},main,[main,left],'left'),false);assert.equal(outerEdgeAt({x:0,y:800},main,[main],'left'),true);assert.equal(outerEdgeAt({x:1706,y:5},main,[main],'right'),false);assert.equal(outerEdgeAt({x:1706,y:500},main,[main],'right'),true);assert.equal(outerEdgeAt({x:900,y:911},main,[main],'bottom'),true);assert.equal(outerEdgeAt({x:900,y:960},main,[main],'bottom'),false);assert.equal(outerEdgeAt({x:-1920,y:200},left,[main,left],'left'),true);});
test('top drag target is centered, excludes stacked monitors, fullscreen respects physical display',()=>{assert.equal(topShelfAt({x:853,y:3},main,[main]),true);assert.equal(topShelfAt({x:1060,y:3},main,[main]),false);const upper={id:3,name:'Upper',bounds:{x:0,y:-960,width:1707,height:960},workArea:{x:0,y:-960,width:1707,height:910}};assert.equal(topShelfAt({x:853,y:3},main,[main,upper]),false);assert.equal(coversDisplay(main.bounds,main),true);assert.equal(coversDisplay(main.workArea,main),false);assert.equal(coversDisplay(left.bounds,main),false);});
test('card keyboard steps by row or direction and clamps incomplete final row',()=>{assert.equal(cardNavigation(0,12,3,'grid','ArrowDown'),3);assert.equal(cardNavigation(4,6,3,'grid','ArrowUp'),1);assert.equal(cardNavigation(2,8,3,'grid','ArrowRight'),2);assert.equal(cardNavigation(3,8,3,'grid','ArrowLeft'),3);assert.equal(cardNavigation(4,6,3,'grid','ArrowDown'),5);assert.equal(cardNavigation(2,8,1,'horizontal','ArrowRight'),3);assert.equal(cardNavigation(2,8,1,'vertical','ArrowRight'),2);assert.equal(cardNavigation(0,8,1,'horizontal','ArrowLeft'),0);assert.equal(cardNavigation(0,0,1,'grid','ArrowDown'),-1);});
