const {chromium}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),net=require('node:net'),{spawn}=require('node:child_process');
const root=path.resolve('.'),out=path.resolve('work/development'),profile=path.join(out,'profile'),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let launcher,connection,log='',ended=false,exitCode;const edits=new Map(),cases=[],times=[];
async function poll(fn,message,timeout=30000){const start=Date.now();let last;while(Date.now()-start<timeout){if(ended)throw Error('Development launcher exited '+exitCode+'\n'+log.slice(-5000));try{const value=await fn();if(value)return value;}catch(error){last=error;}await wait(100);}throw Error(message+(last?' '+last:''));}
async function edit(file,probe){assert(!edits.has(file));const original=await fs.readFile(file);edits.set(file,{original,probe:Buffer.from(probe)});await fs.appendFile(file,probe);}
async function restore(file){const record=edits.get(file);if(!record)return;const current=await fs.readFile(file);assert(current.equals(Buffer.concat([record.original,record.probe])),'Source changed independently: '+file);await fs.writeFile(file,record.original);edits.delete(file);}
async function connect(port){return poll(async()=>{let browser;try{browser=await chromium.connectOverCDP('http://127.0.0.1:'+port);const page=browser.contexts().flatMap(context=>context.pages()).find(page=>page.url()==='clipper://app/index.html');if(!page)return false;await page.waitForSelector('#search',{timeout:1500});connection={browser,page};return connection;}catch{return false;}},'Development window not ready',90000);}
async function origin(){return connection.page.evaluate(()=>performance.timeOrigin);}
async function refreshed(before){await poll(async()=>await origin()!==before,'Renderer did not refresh');await connection.page.waitForSelector('#search');}
async function restarted(port,before){await poll(()=>!before.isConnected(),'Electron did not exit normally');await connect(port);assert((await connection.page.evaluate(()=>clipper.state())).settings.paused);}
(async()=>{
 await fs.mkdir(out,{recursive:true});const server=net.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;await new Promise(resolve=>server.close(resolve));
 const env={...process.env,CLIPPER_DEV_DEBUG_PORT:String(port),CLIPPER_DEV_HIDDEN:'1',CLIPPER_DEV_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
 launcher=spawn(process.execPath,['scripts/dev.mjs'],{cwd:root,env,windowsHide:true,stdio:['ignore','pipe','pipe','ipc']});launcher.stdout.on('data',data=>{log+=data;});launcher.stderr.on('data',data=>{log+=data;});launcher.once('exit',code=>{ended=true;exitCode=code;});
 await connect(port);let page=connection.page;
 const state=await page.evaluate(async()=>({state:await clipper.state(),data:await clipper.dataState(),desktop:await clipper.desktopState(),node:typeof require,chrome:await clipperChrome.state()}));
 assert.equal(state.node,'undefined');await page.evaluate(async()=>{const value=await clipper.state();await clipper.settings({...value.settings,paused:true});});assert((await page.evaluate(()=>clipper.state())).settings.paused);assert(!state.desktop.options.shelfTop);assert.equal(path.resolve(state.data.defaultDirectory),profile);assert.equal(state.chrome.visible,false);cases.push('Actual sandboxed app uses an isolated, paused development profile without showing a window');
 await page.evaluate(()=>clipper.clear());await page.evaluate(()=>clipper.applyText({mode:'save',source:'脚本处理',text:'Private development fixture'}));assert.equal((await page.evaluate(()=>clipper.state())).clips.length,1);
 let before=await origin(),start=Date.now();await edit('src/renderer/styles.css','\n:root{--clipper-development-probe:verified}\n');await poll(()=>connection.page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--clipper-development-probe').trim()==='verified'),'CSS did not refresh');await refreshed(before);times.push({kind:'css',ms:Date.now()-start});await restore('src/renderer/styles.css');await poll(()=>connection.page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--clipper-development-probe').trim()===''),'CSS restore not reflected');cases.push('Imported renderer CSS changes and restoration both refresh the actual window');
 before=await origin();await edit('src/renderer/index.html','\n<meta name="clipper-development-probe" content="html">\n');await poll(()=>connection.page.evaluate(()=>!!document.querySelector('meta[name=clipper-development-probe]')),'HTML did not refresh');await refreshed(before);before=await origin();await restore('src/renderer/index.html');await refreshed(before);assert(!await connection.page.evaluate(()=>document.querySelector('meta[name=clipper-development-probe]')));cases.push('Static HTML is watched and copied before refresh');
 before=await origin();await edit('src/renderer/app.ts','\ndocument.documentElement.dataset.clipperDevelopmentProbe="renderer";\n');await poll(()=>connection.page.evaluate(()=>document.documentElement.dataset.clipperDevelopmentProbe==='renderer'),'Renderer TS did not refresh');await refreshed(before);before=await origin();await restore('src/renderer/app.ts');await refreshed(before);cases.push('Renderer TypeScript rebuilds and reloads');
 before=await origin();const logStart=log.length;await edit('src/renderer/app.ts','\nexport const = ;\n');await poll(()=>log.slice(logStart).includes('Expected'),'Compilation error not reported');await wait(500);assert.equal(await origin(),before);await restore('src/renderer/app.ts');await refreshed(before);cases.push('Failed compilation retains the last working window and recovers when fixed');
 for(const file of ['src/preload/index.ts','src/main/index.ts']){const previous=connection.browser;start=Date.now();await edit(file,'\n// CLIPPER_DEVELOPMENT_RESTART_PROBE\n');await restarted(port,previous);times.push({kind:file,ms:Date.now()-start});const restored=connection.browser;await restore(file);await restarted(port,restored);assert.equal((await connection.page.evaluate(()=>clipper.state())).clips.length,1);cases.push(file+' changes and restoration restart normally and retain only the private fixture');}
 const stale=path.resolve('dist/renderer/text-preview/stale-development.js');await fs.writeFile(stale,'// private stale generated chunk\n');await edit('src/renderer/text-preview.ts','\n// CLIPPER_DEVELOPMENT_READER_PROBE\n');await poll(async()=>{try{await fs.stat(stale);return false;}catch(error){return error.code==='ENOENT';}},'Stale reader chunk not retired');before=await origin();await restore('src/renderer/text-preview.ts');await refreshed(before);cases.push('Successful reader rebuild removes unreferenced generated chunks');
 assert((await connection.page.evaluate(()=>clipper.state())).settings.paused);await connection.page.evaluate(()=>clipper.clear());
 launcher.send({type:'clipper:dev-stop'});const end=Date.now();while(!ended&&Date.now()-end<15000)await wait(100);assert(ended,'Launcher did not retire its own process');assert.equal(exitCode,0);cases.push('Development shutdown disposes watchers and normally closes only its owned Electron app');
 const result={passed:true,cases:cases.length,checks:cases,times,root,profile,sourceRestored:edits.size===0,windowShown:false,systemClipboard:false,physicalInput:false,scope:'Actual full application in a physically hidden development window. Real esbuild watch, copied HTML, parent IPC, sandbox preload and normal Electron restarts. Private saved text; no capture, paste, hardware input or daily profiles.'};await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{for(const file of [...edits.keys()])try{await restore(file);}catch(error){console.error(error);process.exitCode=1;}if(launcher?.connected&&!ended)launcher.send({type:'clipper:dev-stop'});await fs.writeFile(path.join(out,'run.log'),log);});
