const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
(async()=>{await fs.mkdir('work/dialog-038',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];try{
const controller=(await require('esbuild').build({stdin:{contents:"import {dialogMarkup,openDialog} from 'D:/Repositories/One/src/renderer/dialog.ts';window.referenceDialog={dialogMarkup,openDialog};",resolveDir:process.cwd()},bundle:true,write:false,platform:'browser'})).outputFiles[0].text;const css=(await fs.readFile('D:/Repositories/One/src/renderer/styles.css','utf8'))+(await fs.readFile('D:/Repositories/One/src/renderer/components.css','utf8'));
for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){
const context=await browser.newContext({viewport:{width:1240,height:800},reducedMotion:'reduce'});for(const fn of [setup,extra])await context.addInitScript(fn,language);await context.addInitScript(theme=>{fixture.state.dark=theme==='dark';fixture.answers=[];clipperChrome.onConfirm=fn=>fixture.confirm=fn;clipperChrome.answerConfirm=async(token,response)=>fixture.answers.push({token,response});},theme);
await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');await page.locator('#search').focus();await page.evaluate(()=>fixture.confirm({token:'private',message:'Keep <img src=x> edits?',detail:'Exact detail',buttons:['Keep','Discard'],defaultId:0,cancelId:0}));await page.waitForSelector('.confirm-dialog[open]');assert.equal(await page.locator('.confirm-dialog h2').textContent(),'Keep <img src=x> edits?');assert.equal(await page.locator('.confirm-dialog h2 img').count(),0);
const reference=await context.newPage();await reference.setContent('<html data-theme="'+theme+'"><head><style>'+css+'</style><style>:root[data-theme=dark]{--surface:#181818;--fg:#eee;--accent:#e4e4e4;--on-accent:#141414}</style></head><body></body></html>');await reference.addScriptTag({content:controller});await reference.evaluate(()=>{document.body.innerHTML=referenceDialog.dialogMarkup({id:'reference',title:'Keep <img src=x> edits?',body:'Exact detail',actions:'<button>Keep</button><button class="primary">Discard</button>'});referenceDialog.openDialog(document.querySelector('dialog'));});
for(const selector of ['.one-dialog-heading','.one-dialog-heading h2','.one-dialog-body','.one-dialog-actions']){const read=e=>{const s=getComputedStyle(e);return Object.fromEntries(['paddingTop','paddingRight','paddingBottom','paddingLeft','fontSize','fontWeight','lineHeight','borderTopWidth','gap','backgroundColor','color','overflowY','flexShrink'].map(k=>[k,s[k]]));};assert.deepEqual(await page.locator('.confirm-dialog '+selector).evaluate(read),await reference.locator(selector).evaluate(read),theme+' '+selector);results.push({language,theme,selector,comparedWithActualOne:true});}
await page.keyboard.press('Escape');await page.waitForSelector('.confirm-dialog',{state:'detached'});assert.equal(await page.evaluate(()=>document.activeElement.id),'search');assert.deepEqual(await page.evaluate(()=>fixture.answers),[{token:'private',response:0}]);await reference.close();
await page.locator('#add-category').click();await page.waitForSelector('#dialog[open]');assert.equal(await page.locator('#dialog .one-dialog-heading').count(),1);assert.equal(await page.locator('#dialog .one-dialog-body').count(),1);assert.equal(await page.locator('#dialog .one-dialog-actions').count(),1);await page.waitForSelector('#dialog .type-choices.segment-ready');assert(await page.locator('[data-category-kind]').evaluateAll(items=>items.every(b=>getComputedStyle(b).borderTopWidth==='0px')));await page.locator('[data-category-kind=all]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-category-kind=text]').getAttribute('class'),'active');await page.evaluate(()=>{const d=document.querySelector('#dialog'),input=d.querySelector('input');input.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,clientX:input.getBoundingClientRect().x+2,clientY:input.getBoundingClientRect().y+2}));d.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:0,clientY:0}));});assert(await page.locator('#dialog').evaluate(d=>d.open),'Dragging out must not dismiss');await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:150}));assert(await page.locator('#dialog').evaluate(d=>d.scrollHeight<=d.clientHeight+1));await page.screenshot({path:'work/dialog-038/'+language+'-'+theme+'.png'});await page.evaluate(()=>{const d=document.querySelector('#dialog');for(const type of ['mousedown','click'])d.dispatchEvent(new MouseEvent(type,{bubbles:true,clientX:0,clientY:0}));});await page.waitForSelector('#dialog[open]',{state:'detached'});assert.equal(await page.evaluate(()=>document.activeElement.id),'add-category');assert.deepEqual(errors,[]);results.push({language,theme,formSkeleton:true,focusRestore:true,backdropGesture:true,largeText:true});await context.close();
}
await fs.writeFile('work/dialog-038/results.json',JSON.stringify({passed:true,cases:results.length,actualOneVersion:JSON.parse(await fs.readFile('D:/Repositories/One/package.json')).version,systemClipboard:false,desktopInput:false,results},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
