const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
async function run(){
 const output=path.resolve('work/drag');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app,ole;
 try{
  const target=await helper.firstWindow();await target.waitForSelector('#target');await target.evaluate(()=>{document.body.innerHTML='<div id="drop" style="height:100vh;background:#e8edf3;display:grid;place-items:center">Clipper 文件拖放验收</div>';document.body.style.margin='0';window.drops=[];window.dropBytes={};document.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';});document.addEventListener('drop',async e=>{e.preventDefault();for(const f of e.dataTransfer.files){window.dropBytes[f.name]=Array.from(new Uint8Array(await f.arrayBuffer()));window.drops.push({name:f.name,size:f.size,text:f.type.startsWith('text')?await f.text():null});}});});
  app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({x:0,y:80,width:900,height:720}));await helper.evaluate(()=>{global.helperWindow.setBounds({x:960,y:80,width:650,height:720});global.helperWindow.show();global.helperWindow.setAlwaysOnTop(true,'screen-saver');});
  const file=path.join(output,'native-drop.txt');await fs.writeFile(file,'Clipper OLE drag fixture');await page.locator('[data-page=shelf]').click();await page.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='native-files';document.body.appendChild(input)});await page.locator('#native-files').setInputFiles(file);await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('native-files').files)));await expect(page.locator('.clip-row')).toHaveCount(1);
  const drag=async selector=>{
  const row=await page.locator(selector).boundingBox();const local={x:row.x+row.width/2,y:row.y+row.height/2};const from=await app.evaluate(({BrowserWindow,screen},p)=>{const b=BrowserWindow.getAllWindows()[0].getContentBounds();BrowserWindow.getAllWindows()[0].setAlwaysOnTop(true,'screen-saver');BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();return screen.dipToScreenPoint({x:Math.round(b.x+p.x),y:Math.round(b.y+p.y)})},local);const to=await helper.evaluate(({screen})=>{const b=global.helperWindow.getContentBounds();return screen.dipToScreenPoint({x:b.x+300,y:b.y+300})});
  await helper.evaluate(async({app,screen},{from,to})=>{const require=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json'));const koffi=require('koffi'),u=koffi.load('user32.dll');const send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)');const vx=metric(76),vy=metric(77),vw=metric(78),vh=metric(79);const mouse=(p,flags)=>{const b=Buffer.alloc(40);b.writeInt32LE(Math.round((p.x-vx)*65535/(vw-1)),8);b.writeInt32LE(Math.round((p.y-vy)*65535/(vh-1)),12);b.writeUInt32LE(flags|0xc001,20);if(send(1,b,40)!==1)throw Error('Mouse input rejected');};const wait=ms=>new Promise(r=>setTimeout(r,ms));mouse(from,0);await wait(150);mouse(from,2);try{await wait(120);for(let i=1;i<=20;i++){mouse({x:from.x+(to.x-from.x)*i/20,y:from.y+(to.y-from.y)*i/20},0);await wait(60);}}finally{mouse(to,4);}},{from,to});
  };
  await drag('.clip-row');
  await expect.poll(()=>target.evaluate(()=>window.drops),{timeout:5000}).toEqual([{name:'native-drop.txt',size:24,text:'Clipper OLE drag fixture'}]);assert.equal(await fs.readFile(file,'utf8'),'Clipper OLE drag fixture');await page.locator('#native-files').setInputFiles(path.resolve('assets/clipper.png'));await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('native-files').files)));await expect(page.locator('.clip-row')).toHaveCount(2);const image=await page.evaluate(async()=>{const s=await window.clipper.state();return window.clipper.detail(s.clips.find(c=>c.kind==='image').id)});await target.evaluate(()=>window.drops=[]);await drag('[data-id="'+image.id+'"]');await expect.poll(()=>target.evaluate(()=>window.drops),{timeout:5000}).toEqual([{name:'Clipper-'+image.hash+'.png',size:Buffer.from(image.payload.png,'base64').length,text:null}]);const jpegBase=await app.evaluate(({nativeImage},png)=>nativeImage.createFromBuffer(Buffer.from(png,'base64')).toJPEG(85).toString('base64'),image.payload.png),body=Buffer.from('Clipper original JPEG metadata'),segment=Buffer.alloc(4);segment.writeUInt16BE(0xfffe);segment.writeUInt16BE(body.length+2,2);const rawJPEG=Buffer.concat([Buffer.from(jpegBase,'base64').subarray(0,2),segment,body,Buffer.from(jpegBase,'base64').subarray(2)]),originalFile=path.join(output,'original.jpg');await fs.writeFile(originalFile,rawJPEG);await page.locator('#native-files').setInputFiles(originalFile);await page.evaluate(()=>window.clipper.dropFiles(Array.from(document.getElementById('native-files').files)));await expect(page.locator('.clip-row')).toHaveCount(3);const jpg=await page.evaluate(async()=>{const s=await window.clipper.state();for(const c of s.clips){const d=await window.clipper.detail(c.id);if(d.payload.formats?.some(f=>f.name==='JFIF'))return d;}});assert.equal(jpg.payload.formats[0].data,rawJPEG.toString('base64'));await target.evaluate(()=>window.drops=[]);await drag('[data-id="'+jpg.id+'"]');const name='Clipper-'+jpg.hash+'.jpg';await expect.poll(()=>target.evaluate(()=>window.drops),{timeout:5000}).toEqual([{name,size:rawJPEG.length,text:null}]);assert.deepEqual(Buffer.from(await target.evaluate(name=>window.dropBytes[name],name)),rawJPEG);assert.deepEqual(await fs.readFile(originalFile),rawJPEG);
ole=await require('./virtual-fixture.cjs').fixture();const attachmentBytes=Buffer.from('Virtual attachment drag 中文\0\xff'),attachmentName='邮件附件.txt';await ole.request({action:'set',entries:[{name:attachmentName,data:attachmentBytes.toString('base64'),type:'stream'}]});await expect.poll(async()=>{const s=await page.evaluate(()=>window.clipper.state());return s.clips.find(c=>c.title.includes(attachmentName));},{timeout:12000}).toBeTruthy();const attachment=await page.evaluate(async name=>(await window.clipper.state()).clips.find(c=>c.title.includes(name)),attachmentName);await page.evaluate(id=>window.clipper.batch([id],'shelf'),attachment.id);await ole.close();ole=undefined;await target.evaluate(()=>window.drops=[]);await drag('[data-id="'+attachment.id+'"]');await expect.poll(()=>target.evaluate(()=>window.drops),{timeout:5000}).toEqual([{name:attachmentName,size:attachmentBytes.length,text:attachmentBytes.toString('utf8')}]);assert.deepEqual(Buffer.from(await target.evaluate(name=>window.dropBytes[name],attachmentName)),attachmentBytes);
console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,nativeOLEFileDrop:true,nativeOLEVirtualAttachmentAfterSourceExit:true,nativeOLEImageDrop:true,nativeOLEOriginalJPEGBytes:true,importedJPEGMetadata:true,sourceUnchanged:true}));
 }finally{if(ole)await ole.close();if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
