const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {Store,EfficiencyService,HotkeyRegistry,efficiencyDefaults,validateEfficiency,rememberSearch,shortcutKey}=require('../work/test-exports.cjs');
test('Recent searches normalize, deduplicate, bound and reject multiline or oversized input',()=>{let h=[];for(let i=0;i<25;i++)h=rememberSearch(h,'项目 '+i);assert.equal(h.length,20);assert.equal(h[0],'项目 24');h=rememberSearch(h,'  Project  ');h=rememberSearch(h,'project');assert.equal(h.filter(s=>/project/i.test(s)).length,1);assert.equal(h[0],'project');assert.deepEqual(rememberSearch(h,' '),h);for(const bad of [null,7,'x\ny','x'.repeat(513)])assert.throws(()=>rememberSearch(h,bad));});
test('Efficiency preferences reject duplicate IDs, reordered hotkey duplicates, and repeated modifiers',()=>{assert.equal(shortcutKey('Shift+Control+A'),'Control+Shift+A');for(const v of ['Control+Control+A','A','Control+Shift+?','Control+Alt+F25'])assert.throws(()=>shortcutKey(v));const a=randomUUID(),b=randomUUID();for(const bindings of [[{id:a,shortcut:'Control+Alt+Q'},{id:b,shortcut:'Alt+Control+Q'}],[{id:a,shortcut:'Control+Alt+Q'},{id:a,shortcut:'Control+Alt+W'}]])assert.throws(()=>validateEfficiency({...efficiencyDefaults,bindings}));});
test('Atomic hotkey replacement preserves prior callbacks when a newly reserved key conflicts',()=>{const map=new Map(),events=[];const registry=new HotkeyRegistry({register:(key,fn)=>{fn();if(key.endsWith('+X'))return false;map.set(key,fn);return true;},unregister:key=>map.delete(key)});registry.replace([['Control+Alt+A',()=>events.push('old')]]);assert.deepEqual(events,[]);assert.throws(()=>registry.replace([['Control+Alt+A',()=>events.push('replacement')],['Control+Alt+B',()=>{}],['Control+Alt+X',()=>{}]]),/占用/);assert.deepEqual([...map.keys()],['Control+Alt+A']);map.get('Control+Alt+A')();assert.deepEqual(events,['old']);registry.replace([['Alt+Control+A',()=>events.push('new')]]);map.get('Control+Alt+A')();assert.deepEqual(events,['old','new']);const old=map.get('Control+Alt+A');registry.clear();old();assert.deepEqual(events,['old','new']);assert.equal(map.size,0);});
test('Startup keeps available hotkeys while reporting unavailable combinations',()=>{const map=new Map();const registry=new HotkeyRegistry({register:(key,fn)=>{if(key.endsWith('+X'))return false;map.set(key,fn);return true;},unregister:key=>map.delete(key)});assert.match(registry.replace([['Control+Alt+X',()=>{}],['Control+Alt+Y',()=>{}]],false),/占用/);assert.equal(map.size,1);assert.throws(()=>registry.replace([['Control+Alt+Y',()=>{}],['Alt+Control+Y',()=>{}]]),/重复/);assert.equal(map.size,1);assert.match(registry.replace([['Control+Alt+Y',()=>{}],['Alt+Control+Y',()=>{}]],false),/重复/);assert.equal(map.size,1);});
test('Search history and reply hotkeys persist locally but are excluded from history backups',()=>{const file=path.join(generated.mkdtempSync(path.resolve('work/efficiency-core-')),'history.sqlite');let s=new Store(file),service=new EfficiencyService(()=>s);const id=s.saveSnippet({title:'签名',text:'谢谢'});service.remember('not recorded');assert.deepEqual(service.state().history,[]);service.save({...efficiencyDefaults,historyEnabled:true,bindings:[{id,shortcut:'Control+Alt+1'}]});service.remember('私有搜索');s.close();s=new Store(file);try{assert.equal(service.state().history[0],'私有搜索');assert.equal(service.options().bindings[0].id,id);const backup=s.backup();assert.equal(JSON.stringify(backup).includes('私有搜索'),false);assert.equal(JSON.stringify(backup).includes('Control+Alt+1'),false);service.remove('私有搜索');assert.deepEqual(service.state().history,[]);service.remember('erase');service.save({...service.options(),historyEnabled:false});assert.deepEqual(s.meta('recent-searches',[]),[]);s.removeSnippet(id);assert.deepEqual(service.options().bindings,[]);}finally{s.close();}});
test('Reply preview is bound to snapshot and target; consumed, changed or canceled intents cannot paste',()=>{const s=new Store(':memory:');try{const id=s.saveSnippet({title:'预览',text:'你好 {{姓名}}'}),service=new EfficiencyService(()=>s),target={hwnd:123,pid:456};service.fill(s.snippets()[0],target);const intent=service.take();assert.equal(intent.kind,'fill');assert.equal(service.take(),null);assert.deepEqual(service.resolve(intent.token).target,target);assert.throws(()=>service.resolve(randomUUID()),/过期/);s.saveSnippet({id,title:'改过',text:'不同 {{姓名}}'});assert.throws(()=>service.resolve(intent.token),/改变/);service.cancel(intent.token);assert.throws(()=>service.resolve(intent.token),/过期/);service.browse();assert.deepEqual(service.take(),{kind:'browse'});assert.equal(service.active,false);}finally{s.close();}});

test('Expired reply previews are revoked without retaining their snapshot',()=>{const s=new Store(':memory:'),realNow=Date.now;try{s.saveSnippet({title:'Expire',text:'Hello {{name}}'});const service=new EfficiencyService(()=>s);service.fill(s.snippets()[0],{hwnd:123,pid:456});const intent=service.take(),now=realNow();Date.now=()=>now+11*60000;assert.equal(service.active,false);assert.throws(()=>service.resolve(intent.token),/过期/);assert.equal(service.take(),null);}finally{Date.now=realNow;s.close();}});

test('Batch reply deletion validates the whole selection and removes its bindings and order entries',()=>{const store=new Store(':memory:'),service=new EfficiencyService(()=>store);try{
 const ids=['First','Second','Third'].map(title=>store.saveSnippet({title,text:title}));store.reorderSnippets(ids);service.save({...efficiencyDefaults,bindings:ids.map((id,index)=>({id,shortcut:'Control+Alt+'+(index+1)}))});
 for(const invalid of [[],null,[ids[0],'invalid'],[ids[0],randomUUID()],Array(501).fill(ids[0])]){assert.throws(()=>service.removeSnippets(invalid));assert.equal(store.snippetIDs().length,3);assert.equal(service.options().bindings.length,3);}
 store.db.exec('SAVEPOINT reply_delete');service.removeSnippets([ids[0],ids[1]]);store.db.exec('ROLLBACK TO reply_delete; RELEASE reply_delete');assert.equal(store.snippetIDs().length,3);assert.deepEqual(store.snippetOrder(),ids);assert.equal(service.options().bindings.length,3);
 service.removeSnippets([ids[0],ids[2],ids[0]]);assert.deepEqual(store.snippetOrder(),[ids[1]]);assert.deepEqual(service.options().bindings,[{id:ids[1],shortcut:'Control+Alt+2'}]);assert.equal(store.snippet(ids[1]).text,'Second');
}finally{store.close();}});
