const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path');
async function fixture(name){const output=path.resolve('work/'+name);await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),env={...process.env,CLIP_TEST_MODE:'1',CLIP_DATA_DIR:profile,CLIP_HELPER_PROFILE:await fs.mkdtemp(path.join(output,'helper-'))};delete env.ELECTRON_RUN_AS_NODE;const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env}),target=await helper.firstWindow();await target.waitForSelector('#target');const originalCursor=await helper.evaluate(({screen})=>screen.getCursorScreenPoint());let app,page;
 const start=async()=>{app=await electron.launch(process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});page=await app.firstWindow();await page.waitForSelector('#search');};await start();
 const focus=async(text='')=>{await helper.evaluate(()=>global.focusTarget());await target.locator('#target').fill(text);await target.locator('#target').focus();await helper.evaluate(()=>global.helperWindow.setAlwaysOnTop(false));};
 const key=keys=>helper.evaluate(({app},keys)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),send=req('koffi').load('user32.dll').func('uint32 __stdcall SendInput(uint32,void*,int)'),codes={Control:17,Alt:18,Shift:16,Super:91};const down=keys.split('+').map(k=>codes[k]||(/^F\d+$/.test(k)?111+Number(k.slice(1)):k.charCodeAt(0))),items=[...down.map(k=>[k,0]),...down.slice().reverse().map(k=>[k,2])],buffer=Buffer.alloc(40*items.length);items.forEach(([k,flags],i)=>{buffer.writeUInt32LE(1,i*40);buffer.writeUInt16LE(k,i*40+8);buffer.writeUInt32LE(flags,i*40+12)});if(send(items.length,buffer,40)!==items.length)throw Error('Physical key injection failed');},keys);
 const click=async locator=>{await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/index.html'));w.setAlwaysOnTop(true,'screen-saver');w.show();w.focus();});const box=await page.locator(locator).boundingBox(),bounds=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/index.html')).getContentBounds());await helper.evaluate(({app,screen},point)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)'),p=screen.dipToScreenPoint(point),buffer=Buffer.alloc(120);for(let i=0;i<3;i++){buffer.writeInt32LE(Math.round((p.x-metric(76))*65535/(metric(78)-1)),i*40+8);buffer.writeInt32LE(Math.round((p.y-metric(77))*65535/(metric(79)-1)),i*40+12);buffer.writeUInt32LE(0xc001|[0,2,4][i],i*40+20);}if(send(3,buffer,40)!==3)throw Error('Mouse injection failed');},{x:bounds.x+box.x+box.width/2,y:bounds.y+box.y+box.height/2});};
 return {output,profile,helper,target,get app(){return app},get page(){return page},focus,key,click,start,setPage:p=>page=p,restart:async()=>{await app.close();await start();},close:async()=>{try{if(app)await app.close();}finally{try{await helper.evaluate(()=>global.restoreClipboard());await helper.evaluate(({app,screen},point)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),set=req('koffi').load('user32.dll').func('bool __stdcall SetCursorPos(int,int)'),p=screen.dipToScreenPoint(point);set(p.x,p.y);},originalCursor);}finally{await helper.close();}}}};
}
module.exports={fixture,expect};
