const {_electron:electron,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
async function run(){
 const output=path.resolve('work/verification');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-'));const helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIP_TEST_MODE:'1',CLIP_DATA_DIR:profile,CLIP_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let application;let original;
 try{
  const target=await helper.firstWindow();await target.waitForSelector('#target');await target.evaluate(()=>{window.inputEvents=[];for(const type of ['keydown','keyup','paste','focusin'])document.addEventListener(type,e=>window.inputEvents.push({type,key:e.key,ctrl:e.ctrlKey,target:e.target.id}))});
  application=await electron.launch(process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await application.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.waitForSelector('#search');
  const initial=await page.evaluate(()=>window.clip.state());assert.equal(initial.clips.length,0);assert.equal(initial.native,true,initial.status);assert.equal(initial.hotkeyError,'');
  const secure=await application.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration}});assert.deepEqual(secure,{sandbox:true,contextIsolation:true,nodeIntegration:false});
  const write=async text=>{await helper.evaluate(async({clipboard},text)=>{await clipboard.writeText(text)},text);await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.some(c=>c.preview===text.slice(0,240)),{timeout:10000}).toBe(true);};
  await write('你好，Clip。\n把每次复制，留在随手可及的地方。');await write('https://github.com/One-Clip/OneClip');await write('const clipboard = await readClipboard();\nconsole.log(clipboard);');
  const text='项目记录\n'+'内容 '.repeat(120)+'深层检索命中';await write(text);await page.locator('#search').fill('深层检索命中');await expect(page.locator('.clip-row')).toHaveCount(1);await page.locator('#search').fill('');await expect(page.locator('.clip-row')).toHaveCount(4);
  await page.locator('.clip-row').first().click();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-id')),await page.locator('.clip-row').nth(1).getAttribute('data-id'));await page.locator('#search').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement?.id),'search');
  await helper.evaluate(async({clipboard,ClipboardItem})=>clipboard.write([new ClipboardItem({'text/plain':'富文本测试','text/html':'<b>富文本测试</b>'})]));await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.length).toBe(5);
  await helper.evaluate(async({clipboard,ClipboardItem},icon)=>{const fs=process.getBuiltinModule('node:fs');await clipboard.write([new ClipboardItem({'image/png':new Blob([fs.readFileSync(icon)],{type:'image/png'})})])},path.resolve('assets/clip.png'));await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.some(c=>c.kind==='image')).toBe(true);
  await page.locator('[data-kind=image]').click();await expect(page.locator('.clip-row')).toHaveCount(1);await expect(page.locator('.image-preview img')).toBeVisible();await page.locator('#copy').click();const imagePresent=await application.evaluate(async({clipboard})=>clipboard.has('image/png'));assert.equal(imagePresent,true);
  await page.locator('[data-kind=all]').click();await page.locator('#search').fill('你好，Clip');await expect(page.locator('.clip-row')).toHaveCount(1);await page.locator('#favorite').click();await page.locator('#pin').click();await page.locator('.detail-more summary').click();await page.locator('#enqueue').click();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).queue.length).toBe(1);
  await page.locator('#edit').click();await page.locator('#edit-tags').fill('工作, 常用');await page.locator('#dialog [type=submit]').click();await page.locator('#search').fill('工作');await expect(page.locator('.clip-row')).toHaveCount(1);
  const count=(await page.evaluate(()=>window.clip.state())).clips.length;await page.locator('#copy').click();await expect(page.locator('#toast')).toContainText('已复制');await new Promise(r=>setTimeout(r,650));assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,count);
  await page.locator('#delete').click();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.length).toBe(count-1);await page.locator('#undo-toast').click();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.length).toBe(count);
  await page.locator('[data-page=replies]').click();await page.locator('#new-reply').click();await page.locator('#reply-title').fill('邮件签名');await page.locator('#reply-text').fill('谢谢，期待你的回复。\nClip');await page.locator('#dialog [type=submit]').click();await expect(page.locator('.clip-row')).toHaveCount(1);await page.locator('#copy').click();assert.equal(await helper.evaluate(async({clipboard})=>clipboard.readText()),'谢谢，期待你的回复。\nClip');
  await page.locator('[data-page=history]').click();await page.locator('#search').fill('你好，Clip');await expect(page.locator('.clip-row')).toHaveCount(1);await page.locator('.detail-more summary').click();await page.locator('#split').click();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).queue.length).toBe(2);await page.locator('[data-page=stack]').click();await expect(page.locator('.clip-row')).toHaveCount(2);const before=(await page.evaluate(()=>window.clip.state())).queue;await page.locator('.detail-more summary').click();await page.locator('#queue-down').click();assert.notDeepEqual((await page.evaluate(()=>window.clip.state())).queue,before);
  await helper.evaluate(()=>global.focusTarget());await target.locator('#target').click();await new Promise(r=>setTimeout(r,500));await application.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].setAlwaysOnTop(true,'screen-saver');BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus()});
  const first=(await page.evaluate(async()=>{const s=await window.clip.state();return window.clip.detail(s.queue[0])})).payload.text;await page.locator('#paste-next').click();await expect(target.locator('#target')).toHaveValue(first,{timeout:5000}).catch(async error=>{console.log('PASTE_DIAGNOSTICS',JSON.stringify({toast:await page.locator('#toast').textContent(),state:await page.evaluate(async()=>{const s=await window.clip.state();return {queue:s.queue,status:s.status}}),target:await helper.evaluate(()=>({focused:global.helperWindow.isFocused(),visible:global.helperWindow.isVisible()})),inputEvents:await target.evaluate(()=>({events:window.inputEvents,focus:document.activeElement.id,focused:document.hasFocus()})),clipboardExpected:await helper.evaluate(async({clipboard},expected)=>(await clipboard.readText())===expected,first)}));throw error;});await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).queue.length).toBe(1);
  await application.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus()});
  await page.locator('[data-page=settings]').click();await page.locator('.settings-nav button').filter({hasText:'记录与隐私'}).click();await page.locator('#paused').check();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).settings.paused).toBe(true);await helper.evaluate(async({clipboard})=>clipboard.writeText('这条不应被记录'));await new Promise(r=>setTimeout(r,700));assert.equal((await page.evaluate(()=>window.clip.state())).clips.some(c=>c.preview==='这条不应被记录'),false);await page.locator('#paused').uncheck();await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).settings.paused).toBe(false);await new Promise(r=>setTimeout(r,700));assert.equal((await page.evaluate(()=>window.clip.state())).clips.some(c=>c.preview==='这条不应被记录'),false);
  await page.locator('.settings-nav button').filter({hasText:'外观'}).click();await page.locator('[data-theme-choice=dark]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.waitForTimeout(220);await page.screenshot({path:path.join(output,'settings-dark.png')});await page.locator('[data-page=history]').click();await page.waitForTimeout(220);await page.screenshot({path:path.join(output,'history-dark.png')});
  await page.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,theme:'light'})});await page.waitForTimeout(220);await page.screenshot({path:path.join(output,'history-light.png')});await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,650));await page.waitForTimeout(220);await page.screenshot({path:path.join(output,'compact.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);const final=await page.evaluate(()=>window.clip.state());console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIP_PACKAGED_EXE,clips:final.clips.length,realPaste:true,native:final.native,screenshots:output,profile},null,2));
 }finally{if(application)await application.close();await helper.evaluate(async({clipboard})=>{await global.restoreClipboard()}).catch(()=>{});await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
