const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
(async()=>{await fs.mkdir('work/feedback-0281',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],results=[];try{
 for(const language of ['zh-CN','en']){const context=await browser.newContext();for(const fn of [setup,extra])await context.addInitScript(fn,language);await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  for(const view of ['index','tray','shelf']){for(const [width,height,scale]of view==='index'?[[1180,780,100],[860,600,150]]:view==='tray'?[[740,560,100],[440,360,150]]:[[420,440,100],[280,220,150]]){
   await page.setViewportSize({width,height});await page.goto('https://clipper.test/'+view+'.html');await page.waitForTimeout(100);const id=view==='index'?'toast':'notice';assert.equal(await page.locator('#'+id).evaluate(e=>e.matches(':popover-open')),false);await page.evaluate(scale=>fixture.appearance({...fixture.value(),scale}),scale);
   for(const dark of [false,true]){await page.evaluate(dark=>{document.documentElement.dataset.theme=dark?'dark':'light';},dark);for(const position of ['top-left','top-center','top-right','bottom-left','bottom-center','bottom-right']){
    const text=language==='en'?'Could not finish this operation. The saved content is still available.':'操作未完成，保存的内容仍可继续使用。';await page.evaluate(({position,text})=>{fixture.appearance({...fixture.value(),toastPosition:position});document.dispatchEvent(new CustomEvent('clipper:feedback',{detail:text}));},{position,text});await page.waitForTimeout(220);
    const value=await page.locator('#'+id).evaluate(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return {position:c.position,visible:e.matches(':popover-open'),color:c.color,background:c.backgroundColor,left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,innerWidth,innerHeight};});assert.equal(value.position,'fixed');assert(value.visible);assert.notEqual(value.color,value.background);assert(value.left>=0&&value.right<=width+1&&value.top>=52&&value.bottom<=height+1,JSON.stringify({view,position,width,height,scale,dark,value}));if(position.endsWith('left'))assert(Math.abs(value.left-20)<1);else if(position.endsWith('right'))assert(Math.abs(value.right-(width-20))<1);else assert(Math.abs(value.left+value.width/2-width/2)<1);if(position.startsWith('top'))assert(Math.abs(value.top-64)<1);else assert(Math.abs(value.bottom-(height-24))<1);results.push({language,view,width,height,scale,dark,position});
   }}
   if(view!=='index'){const long=Array.from({length:50},(_,i)=>(i+1)+' · '+(language==='en'?'A detailed diagnostic line.':'诊断信息需要可以滚动阅读。')).join('\n');await page.evaluate(long=>document.dispatchEvent(new CustomEvent('clipper:feedback',{detail:long})),long);await page.waitForTimeout(220);await page.locator('#notice').focus();const previous=await page.locator('#items').evaluate(e=>e.scrollTop);await page.keyboard.press('End');assert(await page.locator('#notice').evaluate(e=>e.scrollTop>0));assert.equal(await page.locator('#items').evaluate(e=>e.scrollTop),previous);assert.equal(await page.locator('#notice').getAttribute('aria-live'),'polite');await page.clock.install();await page.clock.fastForward(8000);assert(await page.locator('#notice').evaluate(e=>e.matches(':popover-open')));await page.locator(view==='tray'?'#search':'#choose').focus();await page.clock.fastForward(7001);assert.equal(await page.locator('#notice').innerText(),'');assert.equal(await page.locator('#notice').evaluate(e=>e.matches(':popover-open')),false);assert.equal(await page.locator('#notice').getAttribute('tabindex'),'-1');await page.clock.resume();}
  }}
  await page.setViewportSize({width:1180,height:780});await page.goto('https://clipper.test/index.html');await page.waitForTimeout(100);await page.evaluate(()=>{document.getElementById('dialog').showModal();document.dispatchEvent(new CustomEvent('clipper:feedback',{detail:'Feedback over a modal dialog'}));});assert(await page.locator('#toast').evaluate(e=>e.matches(':popover-open')));assert.equal(await page.locator('dialog[open]').count(),1);await context.close();
 }
 assert.deepEqual(errors,[]);const report={passed:true,cases:results.length,errors,positions:6,languages:2,themes:2,modalTopLayer:true,longMessageKeyboardScroll:true,readingPausesDismissal:true,scope:'Built renderers in an isolated headless browser, synthetic IPC, no system clipboard or desktop input.',results};await fs.writeFile('work/feedback-0281/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,results:undefined}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
