const {_electron:electron,expect}=require('@playwright/test');
const {build}=require('esbuild');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){
 await build({entryPoints:['src/main/native.ts'],outfile:'work/native-test.cjs',bundle:true,platform:'node',external:['koffi']});
 const output=path.resolve('work/integration');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-'));const helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIP_TEST_MODE:'1',CLIP_DATA_DIR:profile,CLIP_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const options=process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env};
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let application;
 try{
 await helper.firstWindow();await helper.evaluate(({app},nativePath)=>{const require=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json'));global.native=require(nativePath);global.native.initNative()},path.resolve('work/native-test.cjs'));
 application=await electron.launch(options);let page=await application.firstWindow();await page.waitForSelector('#search');
 const file=path.join(output,'文件 test.txt');await fs.writeFile(file,'file payload');
 await helper.evaluate((_e,file)=>global.native.writeFiles([file],Number(global.helperWindow.getNativeWindowHandle().readBigUInt64LE())),file);
 await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.some(c=>c.kind==='files')).toBe(true);
 const fileId=(await page.evaluate(()=>window.clip.state())).clips.find(c=>c.kind==='files').id;
 await page.evaluate(id=>window.clip.copy(id,false),fileId);await expect.poll(async()=>{try{return await helper.evaluate(()=>global.native.readFiles());}catch(e){if(String(e).includes('剪贴板忙'))return [];throw e;}},{timeout:3000,intervals:[50,100,200]}).toEqual([file]);
 await fs.rename(file,file+'.moved');await page.evaluate(id=>window.clip.action(id,'enqueue'),fileId);const missing=await page.evaluate(async()=>window.clip.next().then(()=>null).catch(e=>e.message));assert.match(missing,/源文件/);assert.deepEqual((await page.evaluate(()=>window.clip.state())).queue,[fileId]);await fs.rename(file+'.moved',file);
 const baseline=(await page.evaluate(()=>window.clip.state())).clips.length;
 await helper.evaluate(async({clipboard,ClipboardItem})=>clipboard.write([new ClipboardItem({'text/plain':'private fixture','electron application/osclipboard;format="CanIncludeInClipboardHistory"':new Blob([new Uint8Array([0,0,0,0])])})]));await delay(750);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline);
 await page.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,excludedApps:[...s.settings.excludedApps,'electron.exe']})});await helper.evaluate(async({clipboard})=>clipboard.writeText('excluded fixture'));await delay(750);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline);
 await page.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,excludedApps:s.settings.excludedApps.filter(x=>x!=='electron.exe')})});await delay(500);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline);
 await helper.evaluate(async({clipboard})=>clipboard.writeText('<script>window.compromised=true</script>'));await expect.poll(async()=> (await page.evaluate(()=>window.clip.state())).clips.length).toBe(baseline+1);assert.equal(await page.evaluate(()=>window.compromised),undefined);
 await page.evaluate(()=>window.clip.snippet({title:'备份回复',text:'恢复后仍应存在'}));const backupPath=path.join(output,'backup.json');await application.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},backupPath);await page.evaluate(()=>window.clip.backup('export'));const backup=JSON.parse(await fs.readFile(backupPath,'utf8'));assert.equal(backup.format,'clip-backup');assert.equal(backup.clips.length,baseline+1);
 await page.evaluate(async()=>{await window.clip.clearQueue();await window.clip.clear()});assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,0);await application.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},backupPath);await page.evaluate(()=>window.clip.backup('import'));assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline+1);await page.evaluate(()=>window.clip.backup('import'));assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline+1);
 const originalSettings=(await page.evaluate(()=>window.clip.state())).settings;const conflict='Control+Alt+F11';await helper.evaluate(({globalShortcut},key)=>{if(!globalShortcut.register(key,()=>{}))throw Error('test conflict key already occupied')},conflict);
 const failure=await page.evaluate(async key=>{const s=await window.clip.state();return window.clip.settings({...s.settings,shortcut:key}).then(()=>null).catch(e=>e.message)},conflict);assert.match(failure,/占用/);assert.equal((await page.evaluate(()=>window.clip.state())).settings.shortcut,originalSettings.shortcut);assert.equal(await application.evaluate(({globalShortcut},key)=>globalShortcut.isRegistered(key),originalSettings.shortcut),true);await helper.evaluate(({globalShortcut})=>globalShortcut.unregisterAll());
 await page.locator('[data-page=settings]').click();await page.locator('#shortcut').focus();await expect.poll(()=>application.evaluate(({globalShortcut},key)=>globalShortcut.isRegistered(key),originalSettings.shortcut)).toBe(false);await page.locator('#shortcut').press('Escape');await expect.poll(()=>application.evaluate(({globalShortcut},key)=>globalShortcut.isRegistered(key),originalSettings.shortcut)).toBe(true);
 const recentPromise=application.waitForEvent('window');await page.evaluate(()=>window.clip.showTray());const recent=await recentPromise;await recent.waitForSelector('.tray-row');await recent.locator('#search').fill('script');await expect(recent.locator('.tray-row')).toHaveCount(1);await recent.locator('.tray-row').click();assert.equal(await helper.evaluate(async({clipboard})=>clipboard.readText()),'<script>window.compromised=true</script>');
 await application.close();application=await electron.launch(options);page=await application.firstWindow();await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,baseline+1);assert.equal((await page.evaluate(()=>window.clip.state())).snippets.length,1);
 console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIP_PACKAGED_EXE,files:true,privateClipboard:true,excludedApps:true,queueFailurePreserved:true,backupRoundTrip:true,hotkeyConflictRollback:true,recentPanel:true,restartPersistence:true},null,2));
 }finally{if(application)await application.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard()).catch(()=>{});await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
