// Headless dialog layout and data-preservation checks. All application APIs are mocked.
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{setup,measure}=require('./renderer-fixture.cjs'),{setupDialogs,openDialog}=require('./language-dialog-fixture.cjs');
const specs=[['category','新建分类','New category',['#category-name','#category-source','#category-tag']],['reply','新建快捷回复','New quick reply',['#reply-title','#reply-text','#reply-shortcut']],['reply-fill','填写回复内容','Fill in reply',['[data-variable="0"]','#template-preview']],['reply-image','新建快捷回复','New quick reply',['#reply-title','.template-attachment','#reply-shortcut']],['search','搜索历史','Recent searches',['#remember-searches','#clear-searches','[data-reuse-search="0"]']],['stack-rules','堆栈规则','Stack rules',['#stack-kind','#stack-mode','#stack-source','#stack-trim']],['stack-batch','批量入栈','Add batch',['#stack-order','#stack-preview','#stack-summary']],['formats','格式与信息','Formats & info',['#format-tab','#metadata-tab','[data-export-format="Rich Text Format"]','[data-export-attachment="0"]','#read-file-info']],['metadata','格式与信息','Formats & info',['#metadata-target','#metadata-location','#metadata-read','#metadata-values']]];
(async()=>{await fs.mkdir('work/language-dialogs',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[],failures=[],errors=[];let context;try{for(const language of ['en','zh-CN']){
 context=await browser.newContext({viewport:{width:860,height:600}});await context.addInitScript(setup,language);await context.addInitScript(setupDialogs);await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});}catch{return route.abort();}});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 for(const [name,zh,en,selectors] of specs){await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');await openDialog(page,name);assert.equal(await page.locator('#dialog h2').textContent(),language==='en'?en:zh);
  for(const font of language==='en'?['system','sans','mono']:['mono'])for(const scale of language==='en'?[100,110,125,150]:[100,150])for(const density of ['comfortable','compact']){await page.evaluate(value=>fixture.appearance(value),{font,scale,density});await page.evaluate(()=>new Promise(requestAnimationFrame));const label=`${language} ${name} ${font} ${scale} ${density}`;let metrics={};for(const selector of [...selectors,'#modal-close','dialog button[type="submit"]']){await page.locator(selector).scrollIntoViewIfNeeded();metrics={...metrics,...await measure(page,[selector])};}const overflow=await page.locator('.modal-body').evaluate(el=>el.scrollWidth>el.clientWidth+1);results.push({label,metrics,overflow});for(const [key,value] of Object.entries(metrics))if(value===false||typeof value==='object'&&(value.missing||!value.visible||!value.reachable))failures.push({label,key,value});if(overflow)failures.push({label,key:'modal horizontal overflow'});}
  await page.locator('.modal-body').evaluate(el=>el.scrollTop=0);await page.screenshot({path:`work/language-dialogs/${name}-${language}-150.png`});assert.equal(await page.locator('#injected-search,#injected-stack,#injected-metadata').count(),0);
 }
 await context.close();context=undefined;
 }await fs.writeFile('work/language-dialogs/results.json',JSON.stringify({scope:'Actual renderer bundles in headless Edge with mocked IPC; no Windows input or clipboard',cases:results.length,failures,errors,results},null,2));console.log(JSON.stringify({cases:results.length,failures:failures.length,firstFailures:failures.slice(0,12),errors},null,2));assert.equal(errors.length,0);assert.equal(failures.length,0,'See work/language-dialogs/results.json');
 }finally{await context?.close();await browser.close();console.log('Headless context and browser closed.');}})().catch(error=>{console.error(error);process.exitCode=1;});
