// Headless language preference integration only. Full English catalog coverage is a separate gate.
const {setup:setupBase}=require('./renderer-fixture.cjs');
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
function setup(current){const base=window.clipper;let choice=current;const item={id:'sample',kind:'text',hash:'sample',title:'界面语言',preview:'保存 设置 中文正文',source:'保存.exe',updatedAt:Date.now(),createdAt:Date.now(),favorite:false,pinned:false,tags:['保存'],bytes:30};
 const state={clips:[item],snippets:[],queue:[],shelf:[],categories:[],settings:{theme:'system',view:'list',paused:false,maxItems:1000,retentionDays:30,excludedApps:[],shortcut:'Control+Shift+V',quickShortcut:'Control+Alt+V',nextShortcut:'Control+Alt+N',launchAtLogin:false},desktop:{cardDirection:'grid'},stack:{options:{kind:'all',source:'',contains:'',mode:'whole',trim:true},running:false,reason:''},dark:false,native:true,status:'',bytes:30,hotkeyError:''};
 const languageState=()=>({choice,current,next:choice==='system'?'en':choice,restartRequired:(choice==='system'?'en':choice)!==current,warning:false});
 window.fixture={read:languageState,saves:0};window.clipperLanguage={current,state:async()=>languageState()};window.clipperAppearance={state:async()=>({value:{font:'system',scale:100,density:'comfortable'},warning:''}),onChange:()=>()=>{}};
 window.clipper=new Proxy({state:async()=>state,detail:async()=>({...item,payload:{text:'保存 设置 界面语言\nD:\\资料\\中文路径.txt'}}),replyIntent:async()=>null,integrations:async()=>({pending:null}),configureLanguage:async value=>{choice=value;fixture.saves++;return languageState();},onChange:()=>()=>{},onNotice:()=>()=>{}},{get:(object,key)=>key in object?object[key]:base[key]});
 window.capture={data:async()=>({image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4J8AAAAASUVORK5CYII='}),complete:async()=>{}};
}
(async()=>{await fs.mkdir('work/language-ui',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});let context;try{for(const language of ['zh-CN','en']){context=await browser.newContext({viewport:{width:860,height:600}});await context.addInitScript(setupBase,language);await context.addInitScript(setup,language);await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});}catch{return route.abort();}});const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('.text-preview');assert.equal(await page.locator('html').getAttribute('lang'),language);assert.equal(await page.locator('.row-title').first().textContent(),'界面语言');assert.equal(await page.locator('.text-preview').textContent(),'保存 设置 界面语言\nD:\\资料\\中文路径.txt');await page.locator('[data-page="settings"]').click();await page.waitForSelector('.settings-nav');await page.locator('.settings-nav button').first().click();assert.equal(await page.locator('#interface-language').inputValue(),language);assert.equal(await page.locator('#language-settings,#save-settings').count(),0);await page.locator('#interface-language').selectOption(language==='en'?'zh-CN':'en');await page.waitForFunction(()=>fixture.saves===1);assert.equal(await page.evaluate(()=>fixture.read().choice),language==='en'?'zh-CN':'en');assert.equal(await page.evaluate(()=>fixture.read().current),language);await page.screenshot({path:`work/language-ui/preferences-${language}.png`});await page.locator('[data-page="history"]').click();assert.equal(await page.locator('.row-title').first().textContent(),'界面语言');await page.goto('https://clipper.test/capture.html');assert.equal(await page.locator('#cancel').textContent(),language==='en'?'Cancel':'取消');assert.deepEqual(errors,[]);await context.close();context=undefined;console.log(language+': inline preference save, isolated language state, product HTML and preserved user text passed.');}}finally{await context?.close();await browser.close();console.log('Headless context and browser closed.');}})().catch(error=>{console.error(error);process.exitCode=1;});
