const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {LanguageStore,resolveLanguage,validateLanguageChoice,languageFromArguments,validateMessage,renderMessage,templateMessage,setInterfaceLanguage,t,formatDate,formatNumber,formatBytes}=require('../work/test-exports.cjs');
async function fixture(t){const dir=await generated.mkdtemp(path.join(os.tmpdir(),'clipper-language-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {dir,file:path.join(dir,'language.json')};}
test('Language choices preserve existing Chinese defaults and map OS language explicitly',()=>{for(const language of ['zh-CN','zh-TW','zh_HK','ZH-hans'])assert.equal(resolveLanguage('system',language),'zh-CN');for(const language of ['en-US','ja-JP','fr-FR',''])assert.equal(resolveLanguage('system',language),'en');assert.equal(resolveLanguage('zh-CN','en-US'),'zh-CN');assert.equal(resolveLanguage('en','zh-CN'),'en');for(const choice of [null,'',{},'en-US','zh-TW'])assert.throws(()=>validateLanguageChoice(choice));});
test('Preload language accepts a single explicit application argument only',()=>{assert.equal(languageFromArguments(['electron','--clipper-ui-language=en']),'en');for(const args of [[],['--clipper-ui-language=fr'],['--clipper-ui-language=en','--clipper-ui-language=zh-CN']])assert.equal(languageFromArguments(args),'zh-CN');});
test('Translated message placeholders can reorder without translating user values',()=>{const source='从 ⟦0⟧ 复制 ⟦1⟧',translation='Copy ⟦1⟧ from ⟦0⟧';assert.equal(renderMessage(source,translation,['中文文件.txt','保存 ⟦0⟧ <script>']),'Copy 保存 ⟦0⟧ <script> from 中文文件.txt');assert.equal(templateMessage(['已删除 ',' 条']),'已删除 ⟦0⟧ 条');for(const invalid of ['','Copy ⟦0⟧','Copy ⟦0⟧ ⟦0⟧','Copy ⟦2⟧ ⟦1⟧'])assert.throws(()=>validateMessage(source,invalid));assert.throws(()=>renderMessage(source,translation,['one']));assert.throws(()=>templateMessage(['literal ⟦0⟧']));});
test('Language formatting keeps bytes and timestamps stable while changing display',()=>{try{setInterfaceLanguage('en');assert.equal(t('保存'),'Save');assert.equal(t`值：${'保存'}`,'值：保存');assert.equal(formatNumber(12345.5),'12,345.5');assert.equal(formatBytes(1536),'2 KB');assert.equal(formatBytes(1572864),'1.5 MB');const epoch=Date.UTC(2026,0,2,13,4);assert.match(formatDate(epoch,{timeZone:'UTC',year:'numeric',month:'long',day:'numeric'}),/January 2, 2026/);setInterfaceLanguage('zh-CN');assert.equal(t('保存'),'保存');assert.match(formatDate(epoch,{timeZone:'UTC',year:'numeric',month:'long',day:'numeric'}),/2026年1月2日/);assert.throws(()=>formatBytes(-1));}finally{setInterfaceLanguage('zh-CN');}});
test('Saving a language changes the next launch without changing current session',async t=>{const {file}=await fixture(t),store=new LanguageStore(file,'en-US');assert.deepEqual(store.state(),{choice:'zh-CN',current:'zh-CN',next:'zh-CN',restartRequired:false,warning:false});const saved=await store.save('en');assert.equal(saved.current,'zh-CN');assert.equal(saved.next,'en');assert.equal(saved.restartRequired,true);assert.equal(new LanguageStore(file,'en-US').state().current,'en');await store.save('zh-CN');assert.equal(store.state().restartRequired,false);assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),{version:1,choice:'zh-CN'});});
test('System language resolves afresh on launch and is not saved as history content',async t=>{const {file}=await fixture(t),store=new LanguageStore(file,'zh-HK');await store.save('system');assert.equal(new LanguageStore(file,'en-GB').state().current,'en');assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),{version:1,choice:'system'});});
test('Invalid language settings fall back while preserving original evidence',async t=>{const {file}=await fixture(t);for(const raw of ['null','{broken',JSON.stringify({version:9,choice:'en'}),JSON.stringify({version:1,choice:'fr'}),'x'.repeat(2049)]){await fs.writeFile(file,raw);const store=new LanguageStore(file,'en-US');assert.equal(store.state().warning,true);assert.equal(store.state().current,'zh-CN');assert.equal(await fs.readFile(file,'utf8'),raw);}const store=new LanguageStore(file,'en-US');await store.save('en');assert.equal(store.state().warning,false);});
test('Concurrent saves serialize; failed replacement neither changes state nor leaves temp files',async t=>{const {file,dir}=await fixture(t),store=new LanguageStore(file,'en-US');await Promise.all([store.save('system'),store.save('en')]);assert.equal(store.state().choice,'en');await fs.unlink(file);await fs.mkdir(file);await assert.rejects(store.save('zh-CN'));assert.equal(store.state().choice,'en');assert.deepEqual(await fs.readdir(dir),['language.json']);await fs.rmdir(file);await store.save('zh-CN');assert.equal(store.state().choice,'zh-CN');});
test('Unknown message names cannot read the catalog object prototype',()=>{try{setInterfaceLanguage('en');for(const value of ['constructor','toString','__proto__'])assert.equal(t(value),value);}finally{setInterfaceLanguage('zh-CN');}});

test('Text tool localization preserves profile/script payloads, prompts and URL data',()=>{
 const {validateAIProfile,validateScript,aiMessages,parseExternalUrl}=require('../work/test-exports.cjs');
 const profile={name:'中文 服务',kind:'openai',baseUrl:'https://example.invalid/v1',model:'中文模型',maxTokens:2048,timeoutSeconds:30,temperature:null,tokenField:'max_completion_tokens',apiKey:'fixture-key-only'};
 const script={name:'保存',description:'中文说明',code:'// 保存\nreturn input + "设置";',timeoutMs:500,permission:'selected-text'};
 const request={input:'保存 <img> ⟦0⟧',action:'custom',language:'简体中文',instruction:'保留原文和 {{姓名}}'};let baseline;
 try{for(const language of ['zh-CN','en']){setInterfaceLanguage(language);const values={profile:validateAIProfile(profile),script:validateScript(script),messages:aiMessages(request),translated:aiMessages({...request,action:'translate'}),url:parseExternalUrl('clipper-win://add?text='+encodeURIComponent(request.input))};if(baseline)assert.deepEqual(values,baseline);else baseline=values;assert.equal(values.messages[1].content,request.input);assert.ok(values.messages[0].content.endsWith(request.instruction));assert.ok(values.translated[0].content.includes('into 简体中文.'));assert.equal(values.url.text,request.input);}}finally{setInterfaceLanguage('zh-CN');}
});

test('Text tool validation translates owned errors without changing accepted values',()=>{
 const {toolText,validateAIProfile,validateScript,aiMessages,parseExternalUrl}=require('../work/test-exports.cjs');
 const profile={name:'保存',kind:'openai',baseUrl:'https://example.invalid',model:'中文',maxTokens:2048,timeoutSeconds:30,temperature:null,tokenField:'max_tokens'};
 const cases=[()=>toolText(''),()=>toolText('a'.repeat(1025),1024),()=>validateAIProfile({...profile,baseUrl:'http://example.invalid'}),()=>validateAIProfile({...profile,apiKey:'bad\nvalue'}),()=>validateScript({name:'保存'}),()=>aiMessages({input:'保存',action:'bad',language:'简体中文',instruction:''}),()=>parseExternalUrl('clipper-win://delete?text=保存')];
 try{for(const language of ['zh-CN','en']){setInterfaceLanguage(language);for(const call of cases)assert.throws(call,error=>language==='en'?!/[\u3400-\u9fff]/.test(error.message):/[\u3400-\u9fff]/.test(error.message));assert.throws(cases[0],{message:language==='en'?'Enter text to process':'请输入要处理的文字'});assert.equal(toolText('保存'),'保存');}}finally{setInterfaceLanguage('zh-CN');}
});
