// Renderer translations and geometry; native dialogs and backend messages are not covered here.
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup,measure}=require('./renderer-fixture.cjs');
(async()=>{const out='work/language-panels';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});let context;const results=[],failures=[],errors=[];try{context=await browser.newContext();await context.addInitScript(setup,'en');await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});}catch{return route.abort();}});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 for(const [file,size,selectors,scrollable,title] of [['selection',[560,96],['#actions button:first-child','#actions button:last-child','#source'],false,'Copy'],['selection',[430,96],['#actions button:first-child','#actions button:last-child','#source'],false,'Copy'],['unlock',[480,570],['#unlock-submit','#use-recovery','#recover','#quit'],true,'Unlock history'],['recovery',[700,600],['#retry','#choose-database','#choose-backup','#quit'],true,'Retry original folder'],['recorder',[680,520],['#start','#refresh','#resolution','#microphone'],true,'Start recording'],['scroll',[680,540],['#start','#display'],true,'Choose region and start'],['image-editor',[760,620],['#viewport','#copy','#save','#zoom'],false,'Copy image'],['capture',[860,600],['#capture-hint'],false,'Drag to select']]){
  await page.setViewportSize({width:size[0],height:size[1]});await page.goto('https://clipper.test/'+file+'.html');await page.waitForSelector(selectors[0]);assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.ok((await page.locator('body').textContent()).includes(title),file+' is not using translated renderer text');
  for(const font of ['system','sans','mono'])for(const scale of [100,110,125,150])for(const density of ['comfortable','compact']){await page.evaluate(v=>fixture.appearance(v),{font,scale,density});await page.evaluate(()=>new Promise(requestAnimationFrame));const label=`${file} ${size.join('x')} ${font} ${scale} ${density}`;let metrics={};for(const selector of selectors){if(scrollable)await page.locator(selector).scrollIntoViewIfNeeded();metrics={...metrics,...await measure(page,[selector])};}results.push({label,metrics});for(const [key,value] of Object.entries(metrics))if(value===false||typeof value==='object'&&(value.missing||!value.visible||key!=='#capture-hint'&&!value.reachable))failures.push({label,key,value});if(file==='image-editor')assert.deepEqual(await page.locator('#image').evaluate(c=>[c.width,c.height]),[640,360]);}
  await page.screenshot({path:path.join(out,file+'-'+size[0]+'-en-150.png')});
 }
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({scope:'English renderer panels with mocked IPC; other UI/backend translation still pending',cases:results.length,failures,errors,results},null,2));console.log(JSON.stringify({cases:results.length,failures:failures.length,examples:failures.slice(0,10),errors},null,2));assert.deepEqual(errors,[]);assert.equal(failures.length,0);
 }finally{await context?.close();await browser.close();console.log('Headless context and browser closed.');}})().catch(error=>{console.error(error);process.exitCode=1;});
