const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs'),{setupDialogs}=require('./language-dialog-fixture.cjs');
(async()=>{await fs.mkdir('work/motion-030',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];try{
 for(const language of ['zh-CN','en'])for(const reduced of [false,true]){
  const context=await browser.newContext({viewport:{width:1240,height:800},reducedMotion:reduced?'reduce':'no-preference'});for(const fn of [setup,extra,setupDialogs])await context.addInitScript(fn,language);
  await context.addInitScript(()=>{fixture.answers=[];fixture.pending=[];clipChrome.onConfirm=fn=>{fixture.confirm=fn;return()=>{};};clipChrome.answerConfirm=async(token,response)=>{if(fixture.failAnswer){fixture.failAnswer=false;throw Error('Fixture answer failure');}fixture.answers.push({token,response});};const base=clip;window.clip=new Proxy({category:()=>new Promise(resolve=>{fixture.resolveCategory=resolve;}),search:q=>new Promise(resolve=>fixture.pending.push({q,resolve}))},{get:(o,k)=>k in o?o[k]:base[k]});});
  await context.route('https://clip.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');
  await page.evaluate(()=>{document.body.insertAdjacentHTML('beforeend','<div id="motion-tabs" class="tabs" style="position:fixed;left:360px;top:65px;z-index:10"><button class="selected">First</button><button>Second longer</button><button disabled>Disabled</button><button hidden>Hidden</button><button>Last</button></div>');document.querySelectorAll('#motion-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#motion-tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});});
  await page.waitForSelector('#motion-tabs.segment-ready');await page.locator('#motion-tabs button').nth(0).focus();await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Last');await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'First');await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Last');
  await page.locator('#motion-tabs button').nth(1).click();await page.waitForFunction(()=>{const group=document.getElementById('motion-tabs'),b=group.querySelector('.selected');return group.style.getPropertyValue('--segment-x')===b.offsetLeft+'px'&&group.style.getPropertyValue('--segment-width')===b.offsetWidth+'px';});
  const motion=await page.locator('#motion-tabs').evaluate(g=>({indicator:getComputedStyle(g,'::before').transitionDuration,button:getComputedStyle(g.querySelector('.selected')).backgroundColor}));assert.equal(motion.button,'rgba(0, 0, 0, 0)');assert.equal(motion.indicator,reduced?'0s':'0.22s, 0.22s, 0.22s');await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:150}));await page.waitForFunction(()=>{const g=document.getElementById('motion-tabs'),b=g.querySelector('.selected');return g.style.getPropertyValue('--segment-width')===b.offsetWidth+'px';});await page.evaluate(()=>{document.getElementById('motion-tabs').remove();fixture.appearance({...fixture.value(),scale:100});});
  for(const method of ['close','escape','outside']){await page.evaluate(method=>fixture.confirm({token:method,message:'Unsaved changes',detail:'Retain or discard',buttons:['Keep','Discard'],defaultId:0,cancelId:0}),method);await page.waitForSelector('.one-dialog[open]');assert.equal(await page.evaluate(()=>document.activeElement.dataset.response),'0');assert.equal(await page.locator('.one-dialog').evaluate(d=>getComputedStyle(d).padding),'0px');if(method==='close')await page.locator('.one-dialog [aria-label]').click();else if(method==='escape')await page.keyboard.press('Escape');else await page.mouse.click(20,20);await page.waitForSelector('.one-dialog',{state:'detached'});assert.equal(await page.evaluate(()=>fixture.answers.at(-1).response),0);}
  await page.evaluate(()=>{fixture.failAnswer=true;fixture.confirm({token:'retry',message:'Retry changes',detail:'',buttons:['Keep','Discard'],defaultId:0,cancelId:0});});await page.locator('.one-dialog [data-response="1"]').click();await page.waitForFunction(()=>document.querySelector('.confirm-error').textContent.includes('Fixture answer failure'));assert.equal(await page.locator('.one-dialog [data-response="1"]').isDisabled(),false);await page.screenshot({path:`work/motion-030/${language}-${reduced?'reduced':'normal'}-dialog.png`});await page.locator('.one-dialog [data-response="1"]').click();await page.waitForSelector('.one-dialog',{state:'detached'});assert.equal(await page.evaluate(()=>fixture.answers.filter(a=>a.token==='retry').length),1);
  await page.locator('#add-category').click();await page.waitForSelector('#dialog[open]');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('dialog').open);
  await page.locator('#add-category').click();await page.locator('#category-name').fill('Old pending form');await page.locator('#category-contains').fill('match');await page.locator('#dialog [type=submit]').click();await page.waitForFunction(()=>!!fixture.resolveCategory);await page.locator('#modal-cancel').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);await page.locator('#add-category').click();await page.locator('#category-name').fill('New open form');await page.evaluate(async()=>{fixture.resolveCategory();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});assert.equal(await page.locator('#dialog').evaluate(d=>d.open),true);assert.equal(await page.locator('#category-name').inputValue(),'New open form');await page.locator('#modal-close').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);
  await page.locator('#search').fill('A');await page.waitForFunction(()=>fixture.pending.length===1);await page.locator('#search').fill('B');await page.locator('#search').fill('A');await page.evaluate(()=>fixture.pending[0].resolve(['image']));await page.waitForFunction(()=>fixture.pending.length===2);assert.equal(await page.locator('.clip-row').count(),3);await page.evaluate(()=>fixture.pending[1].resolve(['text']));await page.waitForFunction(()=>document.querySelectorAll('.clip-row').length===1);assert.equal(await page.locator('.clip-row').getAttribute('data-id'),'text');
  await page.locator('#search').fill('New');await page.waitForFunction(()=>fixture.pending.length===3);await page.evaluate(()=>{fixture.state.clips.push({...fixture.state.clips[0],id:'new',title:'New item'});fixture.refresh();});await page.waitForFunction(()=>fixture.pending.length===4);await page.evaluate(()=>{fixture.pending[3].resolve(['new']);fixture.pending[2].resolve(['image']);});await page.waitForFunction(()=>document.querySelector('.clip-row')?.dataset.id==='new');await page.locator('.search-clear').click();await page.waitForFunction(()=>document.querySelectorAll('.clip-row').length===4);assert.deepEqual(errors,[]);
  results.push({language,reduced,segmentKeyboardAndResize:true,oneDialogAndRetry:true,formEscape:true,deferredSaveKeepsNewForm:true,staleSearchIgnored:true,freshStateRetained:true});await context.close();
 }
 await fs.writeFile('work/motion-030/results.json',JSON.stringify({passed:true,cases:results.length,scope:'Built renderer in isolated headless browser. One segment indicator, dialog actions/motion, query races; mocked IPC.',results},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
