const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),esbuild=require('esbuild');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
const baseline='C:/Users/ruida/Documents/Codex/2026-10-01/c/outputs/Clipper-0.40.0-win-x64/resources/app.asar';
const asar=require('@electron/asar'),archive=process.env.CLIPPER_OPTIONS_ASAR,out='work/options-041';fs.mkdirSync(out,{recursive:true});
const fixture=()=>{window.fontCalls=[];window.releaseFont=[];window.fontDelay=false;const fonts=Array.from({length:2400},(_,i)=>({family:'Font '+String(i).padStart(4,'0'),label:'Font '+String(i).padStart(4,'0'),aliases:['Group '+(i%8)]}));const api={installedFonts:async()=>fonts,uiFontSource:async family=>{fontCalls.push(family);if(fontDelay)await new Promise(resolve=>releaseFont.push(resolve));return null;}};Object.assign(window.clipperAppearance,api);window.one=api;};
const readAsset=(mode,file)=>mode==='before'||archive?asar.extractFile(mode==='before'?baseline:archive,('dist/renderer/'+file).replaceAll('/','\\')):fs.readFileSync('dist/renderer/'+file);
const cases=[],perf=[];let browser;
(async()=>{browser=await chromium.launch({channel:'msedge',headless:true});const controller=(await esbuild.build({stdin:{contents:"import {customControls} from './tests/fixtures/one-041/src/renderer/controls';import {setupFontPicker} from './tests/fixtures/one-041/src/renderer/font-picker';window.reference={customControls,setupFontPicker};",resolveDir:process.cwd()},nodePaths:[path.resolve('node_modules')],bundle:true,platform:'browser',outfile:'work/options-041/reference.js',write:false})).outputFiles;
const js=controller.find(f=>!f.path.endsWith('.css')).text;
for(const mode of ['after','reference','before']){
 const context=await browser.newContext({viewport:{width:1240,height:800}});for(const fn of [setup,extra,fixture])await context.addInitScript(fn,'zh-CN');
 await context.route('https://clipper.test/**',async route=>{const file=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:file==='one-reference.js'?js:readAsset(mode==='reference'?'after':mode,file),contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'text/javascript'});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');await page.locator('[data-page=settings]').click();await page.locator('.section-nav button').filter({hasText:'外观'}).click();
 if(mode==='reference'){await page.addScriptTag({url:'https://clipper.test/one-reference.js'});await page.evaluate(()=>{const original=document.getElementById('appearance-font'),button=original.cloneNode(true);button.id='reference-font';original.replaceWith(button);reference.setupFontPicker(button);});}
 const fontId=mode==='reference'?'reference-font':'appearance-font';await page.locator('#'+fontId).click();await page.waitForFunction(()=>document.querySelectorAll('.font-option').length===2403);
 const anatomy=await page.locator('.font-popup').evaluate(e=>[e.className,...Array.from(e.children,n=>n.className)]);if(mode==='after')cases.push({name:'Actual One font menu anatomy',anatomy});if(mode==='reference')assert.deepEqual(anatomy,cases.find(c=>c.name==='Actual One font menu anatomy').anatomy);
 const measure=async()=>page.evaluate(async()=>{const list=document.querySelector('.font-options'),sample=document.querySelector('.font-sample'),rows=Array.from(list.children);rows[0].dispatchEvent(new PointerEvent('pointerenter'));await new Promise(r=>requestAnimationFrame(r));let styles=0,classes=0;const observer=new MutationObserver(records=>{for(const record of records){if(record.target===sample)styles++;else classes++;}});observer.observe(list,{subtree:true,attributes:true,attributeFilter:['class']});observer.observe(sample,{attributes:true,attributeFilter:['style']});const start=performance.now();for(let i=1;i<=200;i++)rows[i].dispatchEvent(new PointerEvent('pointerenter'));const elapsed=performance.now()-start;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));observer.disconnect();return {ms:elapsed,styleMutations:styles,classMutations:classes,focused:list.querySelectorAll('.focused').length,active:document.getElementById('appearance-font-search').getAttribute('aria-activedescendant')};});
 if(mode!=='before'){
  const v=await measure();assert.equal(v.styleMutations,1);assert.equal(v.classMutations,400);assert.equal(v.focused,1);cases.push({name:mode+' 200 pointer moves: stable rows and one frame preview',...v});
  const position=await page.evaluate(()=>({page:document.scrollingElement.scrollTop,panel:document.querySelector('.section-panels').scrollTop}));await page.locator('#appearance-font-search').press('ArrowDown');const changed=await page.evaluate(()=>({page:document.scrollingElement.scrollTop,panel:document.querySelector('.section-panels').scrollTop,list:document.querySelector('.font-options').scrollTop}));assert.equal(changed.page,position.page);assert.equal(changed.panel,position.panel);assert(changed.list>0);const bounds=await page.locator('.font-options').evaluate(list=>{const row=list.querySelector('.focused'),r=row.getBoundingClientRect(),l=list.getBoundingClientRect();return {ownParent:row.offsetParent===list,visible:r.top>=l.top-1&&r.bottom<=l.bottom+1};});assert.deepEqual(bounds,{ownParent:true,visible:true});cases.push({name:mode+' font row positioned in its own list and fully revealed'});cases.push({name:mode+' keyboard scroll stays inside font menu'});
  await page.locator('#appearance-font-search').fill('Font 0377');await page.waitForFunction(()=>document.querySelectorAll('.font-option').length===1);await page.locator('#appearance-font-search').press('Enter');assert.equal(await page.locator('#'+fontId).evaluate(e=>e.value),'installed:Font 0377');cases.push({name:mode+' font search and keyboard choose'});
  await page.evaluate(fontId=>{document.getElementById(fontId).value='installed:Missing Font';},fontId);await page.locator('#'+fontId).click();await page.locator('#appearance-font-search').fill('Missing Font');await page.locator('#appearance-font-search').press('Enter');assert.equal(await page.locator('.font-popup').count(),1);assert.equal(await page.locator('.font-option').getAttribute('aria-disabled'),'true');cases.push({name:mode+' missing font remains nonselectable'});await page.locator('#appearance-font-search').fill('not-present-zz');assert.equal(await page.locator('.font-option').count(),0);assert.equal(await page.locator('#appearance-font-search').getAttribute('aria-activedescendant'),null);cases.push({name:mode+' empty font search has no stale active option'});await page.locator('#appearance-font-search').press('Escape');
  await page.locator('#'+fontId).click();await page.locator('#appearance-font-search').fill('Font 0444');await page.evaluate(()=>{fontDelay=true;});await page.waitForFunction(()=>releaseFont.length===1);await page.locator('#appearance-font-search').press('Escape');await page.evaluate(()=>{fontDelay=false;releaseFont.shift()();});await page.waitForTimeout(50);assert.equal(await page.locator('.font-popup').count(),0);cases.push({name:mode+' delayed font result stays closed'});
  await page.locator('#'+fontId).click();await page.evaluate(()=>{window.detachedSample=document.querySelector('.font-sample');window.detachedWrites=0;window.sampleObserver=new MutationObserver(r=>detachedWrites+=r.length);sampleObserver.observe(detachedSample,{attributes:true,attributeFilter:['style']});const item=document.querySelectorAll('.font-option')[2000];item.dispatchEvent(new PointerEvent('pointerenter'));document.getElementById('appearance-font-search').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>detachedWrites),0);await page.evaluate(()=>sampleObserver.disconnect());cases.push({name:mode+' closing cancels queued font frame'});
 }else await page.locator('#appearance-font-search').press('Escape');
 // Alternate pointer streams within this isolated page; timings are diagnostic, not a pass threshold.
 await page.locator('#'+fontId).click();await page.waitForFunction(()=>document.querySelectorAll('.font-option').length>=2403);await measure();for(let round=0;round<3;round++)perf.push({mode,round,...await measure()});await page.locator('#appearance-font-search').press('Escape');
 if(mode!=='before'){
  if(mode==='reference')await page.evaluate(()=>{const root=document.createElement('section');root.id='option-fixture';root.innerHTML='<select id="options-test"><option disabled value="0">Zero</option><option value="1">Alpha</option><option disabled value="2">Alpha disabled</option><option value="3">Beta</option><option disabled value="4">Last</option></select>';document.body.append(root);reference.customControls(root);});
  else {await page.evaluate(()=>{const root=document.createElement('section');root.id='option-fixture';root.innerHTML='<select id="options-test"><option disabled value="0">Zero</option><option value="1">Alpha</option><option disabled value="2">Alpha disabled</option><option value="3">Beta</option><option disabled value="4">Last</option></select>';document.body.append(root);});await page.waitForSelector('#options-test-trigger');}
  const id=mode==='reference'?'options-test':'options-test-trigger',button=page.locator('#'+id);await button.click();const selected=()=>page.locator('.select-popup .focused').innerText();assert.equal(await selected(),'Alpha');await button.press('ArrowDown');assert.equal(await selected(),'Beta');await button.press('ArrowUp');assert.equal(await selected(),'Alpha');await button.press('End');assert.equal(await selected(),'Beta');await button.press('Home');assert.equal(await selected(),'Alpha');await button.press('b');assert.equal(await selected(),'Beta');cases.push({name:mode+' select arrows/home/end/typeahead skip disabled rows'});
  await page.locator('.select-popup [aria-disabled=true]').first().dispatchEvent('pointerenter');assert.equal(await selected(),'Beta');await page.locator('.select-popup [aria-disabled=true]').first().dispatchEvent('click');assert.equal(await button.getAttribute('aria-expanded'),'true');cases.push({name:mode+' disabled rows ignore pointer focus and choose'});
  await button.press('Enter');assert.equal(await button.evaluate(e=>e.value),'3');cases.push({name:mode+' select keyboard choice'});
  await page.evaluate(id=>document.getElementById(id).dispatchEvent(new CustomEvent('one:options',{detail:[{label:'Disabled',value:'x',disabled:true}]})),id);await button.click();assert.equal(await button.getAttribute('aria-activedescendant'),null);assert.equal(await page.locator('.select-popup .focused').count(),0);await button.press('Enter');assert.equal(await button.getAttribute('aria-expanded'),'true');cases.push({name:mode+' all disabled options have no invalid active descendant'});await button.press('Escape');
  await page.evaluate(id=>document.getElementById(id).dispatchEvent(new CustomEvent('one:options',{detail:[]})),id);await button.click();assert.equal(await page.locator('.select-empty').innerText(),'没有可选项');assert.equal(await button.getAttribute('aria-activedescendant'),null);cases.push({name:mode+' empty select uses One status row'});await button.press('Escape');
  if(mode==='after'){
   await page.evaluate(()=>{const select=document.getElementById('options-test');select.dispatchEvent(new CustomEvent('one:options',{detail:[{label:'One',value:'1'},{label:'Two',value:'2'}]}));window.formChanges=0;select.addEventListener('change',()=>formChanges++);select.value='2';});assert.equal(await button.innerText(),'Two');await button.click();await button.press('Home');await button.press('Enter');assert.equal(await page.locator('#options-test').inputValue(),'1');assert.equal(await page.evaluate(()=>formChanges),1);cases.push({name:'Original form select value/options/change preserved'});
   await button.click();await page.evaluate(()=>{document.getElementById('options-test').value='2';});assert.equal(await page.locator('.select-popup [aria-selected=true]').innerText(),'Two');cases.push({name:'External value changes update selected row'});await page.evaluate(()=>document.getElementById('options-test').options[1].text='Two renamed');await page.waitForFunction(()=>!document.querySelector('#options-test-trigger[aria-expanded=true]'));assert.equal(await button.innerText(),'Two renamed');cases.push({name:'Native option mutations close and synchronize menu'});
   await button.click();await page.evaluate(()=>document.getElementById('options-test').disabled=true);await page.waitForFunction(()=>document.getElementById('options-test-trigger').disabled);assert.equal(await button.getAttribute('aria-expanded'),'false');cases.push({name:'Disabled form closes its popup'});
   await page.evaluate(()=>document.getElementById('options-test').disabled=false);await button.click();await page.evaluate(()=>document.getElementById('option-fixture').remove());await page.waitForFunction(()=>!document.querySelector('.select-popup'));cases.push({name:'Removed form disposes popup and observer'});
  }
 }
 assert.deepEqual(errors,[],mode);await context.close();
}
const summary=Object.fromEntries(['before','after','reference'].map(mode=>{const rows=perf.filter(r=>r.mode===mode);return [mode,{medianMs:rows.map(r=>r.ms).sort((a,b)=>a-b)[1],styleMutations:rows.map(r=>r.styleMutations),classMutations:rows.map(r=>r.classMutations)}];}));
const result={passed:true,version:'0.41.0',referenceVersion:JSON.parse(fs.readFileSync('tests/fixtures/one-041/package.json')).version,cases:cases.length,results:cases,performance:{fonts:2400,moves:200,trials:3,summary,raw:perf,scope:'Headless production renderer and pinned actual One controller; UI font source synthetic; diagnostic timings, no full app memory or physical input.'},packaged:!!archive,systemClipboard:false,desktopInput:false};fs.writeFileSync(out+(archive?'/packaged.json':'/results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:true,cases:cases.length,summary}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
