const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict'),asar=require('@electron/asar');
(async()=>{const stage=process.cwd(),delivery=path.resolve('../delivery-0.41.0'),root=path.join(delivery,'release/0.41.0/win-unpacked'),archive=path.join(root,'resources/app.asar');fs.mkdirSync('work/package-041',{recursive:true});
 // Prepare private fixtures from this source before packaged checks.
 const esbuild=require('esbuild');fs.mkdirSync('work/transfer-032',{recursive:true});fs.mkdirSync('work/clipboard-033',{recursive:true});
 await esbuild.build({stdin:{contents:"export * from './src/main/transfer';export {thumbnail} from './src/main/clipboard';export {framePNG} from './src/main/stitch';",resolveDir:stage,loader:'ts'},outfile:'work/transfer-032/after.cjs',bundle:true,platform:'node',external:['electron','koffi','./native','./attachment-runtime']});
 await esbuild.build({entryPoints:['src/main/clipboard.ts'],outfile:'work/clipboard-033/after.cjs',bundle:true,platform:'node',external:['electron','./native','./attachment-runtime']});
 await esbuild.build({entryPoints:['src/main/native.ts'],outfile:'work/clipboard-033/after-native.cjs',bundle:true,platform:'node',external:['koffi']});
 await esbuild.build({entryPoints:['src/main/stitch.ts'],outfile:'work/clipboard-033/frame.cjs',bundle:true,platform:'node'});
 const {randomBytes}=require('node:crypto'),{framePNG}=require(path.resolve('work/clipboard-033/frame.cjs'));fs.writeFileSync('work/clipboard-033/image.png',framePNG({width:1600,height:1600,data:randomBytes(1600*1600*4)}));fs.writeFileSync('work/clipboard-033/original.bin',randomBytes(10*1024*1024));
 for(const entry of ['index','tray','shelf','image-editor','recorder','scroll','selection','unlock','recovery','capture']){const html=asar.extractFile(archive,('dist/renderer/'+entry+'.html').replaceAll('/','\\')).toString();assert.equal((html.match(/href="one-ui.css"/g)||[]).length,1,entry);assert.equal((html.match(/<link rel="stylesheet"/g)||[]).length,2,entry);}
 const baseline=fs.readFileSync('tests/program-versions-package.cjs','utf8').replaceAll('delivery-0.26.0','delivery-0.41.0').replaceAll('release/0.26.0','release/0.41.0').replaceAll('delivery-0.23.0','delivery-0.36.0').replaceAll('0\\.23\\.0','0\\.35\\.0').replace("'RollbackHost.exe']","'RollbackHost.exe','DocumentInfo.exe','FontHost.exe']");
 const file=path.resolve('work/package-041/baseline.cjs');fs.writeFileSync(file,baseline);execFileSync(process.execPath,[file],{stdio:'inherit',windowsHide:true});
 // Existing production-core acceptance executes actual packaged workers/helpers with an isolated host.
 let functions=fs.readFileSync('tests/version-027-package.cjs','utf8');functions=functions.slice(functions.indexOf(" await require('esbuild')"));functions="const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');(async()=>{const development="+JSON.stringify(stage)+",delivery="+JSON.stringify(delivery)+",archive="+JSON.stringify(archive)+";"+functions;
 const featureFile=path.resolve('work/package-041/features.cjs');fs.writeFileSync(featureFile,functions);execFileSync(process.execPath,[featureFile],{stdio:'inherit',windowsHide:true});
 // Run the production font service/renderer against the packaged sandbox preload and font helper.
 await require('esbuild').build({entryPoints:['tests/native-ui-028-renderer.ts'],outfile:'work/native-ui-028.js',bundle:true,platform:'browser',target:'chrome138'});
 await require('esbuild').build({entryPoints:['src/main/appearance-service.ts'],outfile:'work/native-ui-028-service.cjs',bundle:true,platform:'node',external:['electron'],define:{__dirname:JSON.stringify(path.join(archive,'dist/main'))}});
 let host=fs.readFileSync('tests/native-ui-028-host.cjs','utf8').replace("path.resolve('dist/preload/index.cjs')",JSON.stringify(path.join(archive,'dist/preload/index.cjs'))).replace("'dist/renderer/one-components.css'",JSON.stringify(path.join(archive,'dist/renderer/one-components.css'))).replace("'dist/renderer/redesign-028.css'",JSON.stringify(path.join(archive,'dist/renderer/redesign-028.css')));
 const nativeHost=path.resolve('work/package-041/native-host.cjs');host=host.replace("require('../work/native-ui-028-service.cjs')","require("+JSON.stringify(path.resolve('work/native-ui-028-service.cjs'))+")");fs.writeFileSync(nativeHost,host);
 const original=fs.readFileSync('tests/native-ui-028.cjs','utf8').replace("args:['tests/native-ui-028-host.cjs']","args:["+JSON.stringify(nativeHost)+"]");const nativeTest=path.resolve('work/package-041/native-test.cjs');fs.writeFileSync(nativeTest,original);execFileSync(process.execPath,[nativeTest],{stdio:'inherit',windowsHide:true});
 for(const name of ['one-ui.css','one-components.css','redesign-028.css','redesign-029.css','recent-shelf.css'])assert(asar.extractFile(archive,('dist/renderer/'+name).replaceAll('/','\\')).equals(fs.readFileSync(path.join(delivery,'dist/renderer',name))),name);
 // Execute search against the actual ASAR worker, including its encrypted native dependency.
 await require('esbuild').build({entryPoints:['tests/performance-030-exports.ts'],outfile:'work/package-041/search-services.cjs',bundle:true,platform:'node',external:['better-sqlite3-multiple-ciphers']});
 const searchHost=path.resolve('work/package-041/search-host.cjs');let searchSource=fs.readFileSync('tests/search-030-native.cjs','utf8').replace("require('../work/performance-030/after.cjs')",'require('+JSON.stringify(path.resolve('work/package-041/search-services.cjs'))+')').replaceAll("path.resolve('dist/main/search-worker.cjs')",JSON.stringify(path.join(archive,'dist/main/search-worker.cjs')));fs.writeFileSync(searchHost,searchSource);execFileSync(path.join(root,'Clipper.exe'),[searchHost,'--host'],{stdio:'inherit',env:{...process.env,ELECTRON_RUN_AS_NODE:'1'},windowsHide:true,timeout:60000});
 const searchRuntime=JSON.parse(fs.readFileSync('work/search-030-native/results.json'));assert(searchRuntime.passed&&searchRuntime.cases===9);fs.copyFileSync('work/search-030-native/results.json','work/package-041/search-results.json');
 const transferEnv={...process.env,CLIPPER_TRANSFER_ASAR:archive};delete transferEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/transfer-032-host.cjs','packaged'],{stdio:'inherit',env:transferEnv,windowsHide:true,timeout:60000});const transfer=JSON.parse(fs.readFileSync('work/transfer-032/packaged.json'));assert(transfer.passed&&transfer.resumedCache&&transfer.protectedExport&&transfer.export.largestDecodedBufferBytes===196608);fs.copyFileSync('work/transfer-032/packaged.json','work/package-041/transfer-results.json');
 const clipboardEnv={...process.env,CLIPPER_CLIPBOARD_ASAR:archive};delete clipboardEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/clipboard-033-host.cjs','packaged'],{stdio:'inherit',env:clipboardEnv,windowsHide:true,timeout:60000});const preparedClipboard=JSON.parse(fs.readFileSync('work/clipboard-033/packaged.json'));assert(preparedClipboard.passed&&preparedClipboard.cancelledWithoutOpening&&preparedClipboard.recoveredAfterCancel&&preparedClipboard.mixedFormatBlocks===37&&preparedClipboard.original.largestBase64Buffer===196608);fs.copyFileSync('work/clipboard-033/packaged.json','work/package-041/clipboard-results.json');
 const previewEnv={...process.env,CLIPPER_PREVIEW_ASAR:archive};delete previewEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/preview-035-electron-host.cjs'],{stdio:'inherit',env:previewEnv,windowsHide:true,timeout:60000});const preview=JSON.parse(fs.readFileSync('work/preview-035/packaged.json'));assert(preview.passed&&preview.version==='0.41.0'&&preview.CSP&&preview.fullSearch);
 const actionEnv={...process.env,CLIPPER_ACTIONS_ASAR:archive};delete actionEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/actions-034-electron-host.cjs'],{stdio:'inherit',env:actionEnv,windowsHide:true,timeout:60000});const actions=JSON.parse(fs.readFileSync('work/actions-034/packaged.json'));assert(actions.passed&&actions.version==='0.41.0'&&actions.pixelEquality&&actions.hidden);
 const imageEnv={...process.env,CLIPPER_IMAGES_ASAR:archive};delete imageEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/preview-036-host.cjs'],{stdio:'inherit',env:imageEnv,windowsHide:true,timeout:60000});const images=JSON.parse(fs.readFileSync('work/preview-036/packaged.json'));assert(images.passed&&images.version==='0.41.0'&&images.productionRenderer&&images.CSP&&images.exactPNG&&images.encrypted&&images.retainedPNGBytes===0);
 
 const coreHost=path.resolve('work/package-041/core-host.cjs');fs.writeFileSync(coreHost,
 "const fs=require('node:fs'),Module=require('node:module'),path=require('node:path');const archive="+JSON.stringify(archive)+";const fixture=new Module(path.join(archive,'dist/main/performance-fixture.cjs'));fixture.filename=path.join(archive,'dist/main/performance-fixture.cjs');fixture.paths=Module._nodeModulePaths(path.dirname(fixture.filename));fixture._compile(fs.readFileSync("+JSON.stringify(path.resolve('work/test-exports.cjs'))+",'utf8'),fixture.filename);global.__clipperPackagedCore=fixture.exports;const source=fs.readFileSync('tests/performance-037-core.cjs','utf8').replace(\"require('../work/test-exports.cjs')\",'global.__clipperPackagedCore');const tests=new Module(__filename);tests.filename=__filename;tests.paths=Module._nodeModulePaths(path.dirname(__filename));tests._compile(source,__filename);".replaceAll('\\"','"'));
 const coreOutput=execFileSync(path.join(root,'Clipper.exe'),['--test-reporter=tap',coreHost],{encoding:'utf8',env:{...process.env,ELECTRON_RUN_AS_NODE:'1'},windowsHide:true,timeout:60000});fs.writeFileSync('work/package-041/core.log',coreOutput);assert.match(coreOutput,/# pass 8\r?\n# fail 0/);

 const captureHost=path.resolve('work/package-041/capture-host.cjs');fs.writeFileSync(captureHost,
 "const fs=require('node:fs'),Module=require('node:module'),path=require('node:path');const archive="+JSON.stringify(archive)+";const fixture=new Module(path.join(archive,'dist/main/capture-fixture.cjs'));fixture.filename=path.join(archive,'dist/main/capture-fixture.cjs');fixture.paths=Module._nodeModulePaths(path.dirname(fixture.filename));fixture._compile(fs.readFileSync("+JSON.stringify(path.resolve('work/test-exports.cjs'))+",'utf8'),fixture.filename);global.__clipperPackagedCore=fixture.exports;const source=fs.readFileSync('tests/capture-038-core.cjs','utf8').replace(\"require('../work/test-exports.cjs')\",'global.__clipperPackagedCore');const tests=new Module(__filename);tests.filename=__filename;tests.paths=Module._nodeModulePaths(path.dirname(__filename));tests._compile(source,__filename);".replaceAll('\\"','"'));
 const captureOutput=execFileSync(path.join(root,'Clipper.exe'),['--test-reporter=tap',captureHost],{encoding:'utf8',env:{...process.env,ELECTRON_RUN_AS_NODE:'1',CLIPPER_CAPTURE_WORKER:path.join(archive,'dist/main/capture-writer-worker.cjs')},windowsHide:true,timeout:60000});fs.writeFileSync('work/package-041/capture-core.log',captureOutput);assert.match(captureOutput,/# pass 13\r?\n# fail 0/);
 const assetsEnv={...process.env,CLIPPER_ASSETS_ASAR:archive};delete assetsEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/assets-040-host.cjs'],{env:assetsEnv,stdio:'inherit',windowsHide:true,timeout:60000});const assets=JSON.parse(fs.readFileSync('work/assets-040/packaged.json'));assert(assets.passed&&assets.cases===10&&assets.actualNativeStyleSheets&&assets.mainSearchBorder==='0px');
 const visibilityEnv={...process.env,CLIPPER_VISIBILITY_ASAR:archive};delete visibilityEnv.ELECTRON_RUN_AS_NODE;for(const host of ['tests/visibility-040-host.cjs','tests/visibility-040-native-host.cjs','tests/visibility-040-pending-host.cjs'])execFileSync(require('electron'),[host,...(host.endsWith('/visibility-040-host.cjs')?['packaged','0']:[])],{env:visibilityEnv,stdio:'inherit',windowsHide:true,timeout:60000});const visibility=JSON.parse(fs.readFileSync('work/visibility-040/packaged-0.json')),nativeVisibility=JSON.parse(fs.readFileSync('work/visibility-040/native-packaged.json')),pendingVisibility=JSON.parse(fs.readFileSync('work/visibility-040/pending-packaged.json'));assert(visibility.passed&&visibility.version==='0.41.0'&&visibility.cases.length===14);assert(nativeVisibility.passed&&nativeVisibility.cases===7&&nativeVisibility.ownerLeaseRetirement&&nativeVisibility.mainCallbackSource);assert(pendingVisibility.passed&&pendingVisibility.cases===3&&pendingVisibility.pendingImportDisposed&&pendingVisibility.pendingWorkerTerminated);
 const optionsEnv={...process.env,CLIPPER_OPTIONS_ASAR:archive};execFileSync(process.execPath,['tests/options-041.cjs'],{env:optionsEnv,stdio:'inherit',windowsHide:true,timeout:60000});const options=JSON.parse(fs.readFileSync('work/options-041/packaged.json'));assert(options.passed&&options.cases===32&&options.packaged);
 const result={passed:true,packagedOptions:true,packagedNativeSharedStyles:true,packagedWindowVisibility:true,packagedOwnerLeaseRetirement:true,packagedPendingReaderCancellation:true,packagedOneUI:true,desktopEntries:10,packagedPerformanceCore:8,packagedCaptureCore:13,packagedImagePreview:true,packagedFullTextPreview:true,packagedAsyncActions:true,version:'0.41.0',packagedSourceAndBuild:true,packagedEncryptedRecovery:true,packagedPreviousFeatures:true,packagedNativeFont:true,packagedRendererAssets:true,packagedEncryptedSearch:true,packagedImageTransfer:true,packagedClipboardMemory:true,systemClipboard:false,desktopInput:false};fs.writeFileSync('work/package-041/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;});
