const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict'),asar=require('@electron/asar');
(async()=>{const stage=process.cwd(),delivery=path.resolve('../delivery-0.28.0'),root=path.join(delivery,'release/0.28.0/win-unpacked'),archive=path.join(root,'resources/app.asar');fs.mkdirSync('work/package-028',{recursive:true});
 const baseline=fs.readFileSync('tests/program-versions-package.cjs','utf8').replaceAll('delivery-0.26.0','delivery-0.28.0').replaceAll('release/0.26.0','release/0.28.0').replaceAll('delivery-0.23.0','delivery-0.27.0').replaceAll('0\\.23\\.0','0\\.27\\.0').replace("'RollbackHost.exe']","'RollbackHost.exe','DocumentInfo.exe','FontHost.exe']");
 const file=path.resolve('work/package-028/baseline.cjs');fs.writeFileSync(file,baseline);execFileSync(process.execPath,[file],{stdio:'inherit',windowsHide:true});
 // Existing production-core acceptance executes actual packaged workers/helpers with an isolated host.
 let functions=fs.readFileSync('tests/version-027-package.cjs','utf8');functions=functions.slice(functions.indexOf(" await require('esbuild')"));functions="const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');(async()=>{const development="+JSON.stringify(stage)+",delivery="+JSON.stringify(delivery)+",archive="+JSON.stringify(archive)+";"+functions;
 const featureFile=path.resolve('work/package-028/features.cjs');fs.writeFileSync(featureFile,functions);execFileSync(process.execPath,[featureFile],{stdio:'inherit',windowsHide:true});
 // Run the production font service/renderer against the packaged sandbox preload and font helper.
 await require('esbuild').build({entryPoints:['src/main/appearance-service.ts'],outfile:'work/native-ui-028-service.cjs',bundle:true,platform:'node',external:['electron'],define:{__dirname:JSON.stringify(path.join(archive,'dist/main'))}});
 let host=fs.readFileSync('tests/native-ui-028-host.cjs','utf8').replace("path.resolve('dist/preload/index.cjs')",JSON.stringify(path.join(archive,'dist/preload/index.cjs'))).replace("'dist/renderer/one-components.css'",JSON.stringify(path.join(archive,'dist/renderer/one-components.css'))).replace("'dist/renderer/redesign-028.css'",JSON.stringify(path.join(archive,'dist/renderer/redesign-028.css')));
 const nativeHost=path.resolve('work/package-028/native-host.cjs');host=host.replace("require('../work/native-ui-028-service.cjs')","require("+JSON.stringify(path.resolve('work/native-ui-028-service.cjs'))+")");fs.writeFileSync(nativeHost,host);
 const original=fs.readFileSync('tests/native-ui-028.cjs','utf8').replace("args:['tests/native-ui-028-host.cjs']","args:["+JSON.stringify(nativeHost)+"]");const nativeTest=path.resolve('work/package-028/native-test.cjs');fs.writeFileSync(nativeTest,original);execFileSync(process.execPath,[nativeTest],{stdio:'inherit',windowsHide:true});
 for(const name of ['one-components.css','redesign-028.css','recent-shelf.css'])assert(asar.extractFile(archive,('dist/renderer/'+name).replaceAll('/','\\')).equals(fs.readFileSync(path.join(delivery,'dist/renderer',name))),name);
 const result={passed:true,version:'0.28.0',packagedSourceAndBuild:true,packagedEncryptedRecovery:true,packagedPreviousFeatures:true,packagedNativeFont:true,packagedRendererAssets:true,systemClipboard:false,desktopInput:false};fs.writeFileSync('work/package-028/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;});
