const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict'),asar=require('@electron/asar');
(async()=>{const stage=process.cwd(),delivery=path.resolve('../delivery-0.32.0'),root=path.join(delivery,'release/0.32.0/win-unpacked'),archive=path.join(root,'resources/app.asar');fs.mkdirSync('work/package-032',{recursive:true});
 const baseline=fs.readFileSync('tests/program-versions-package.cjs','utf8').replaceAll('delivery-0.26.0','delivery-0.32.0').replaceAll('release/0.26.0','release/0.32.0').replaceAll('delivery-0.23.0','delivery-0.31.0').replaceAll('0\\.23\\.0','0\\.31\\.0').replace("'RollbackHost.exe']","'RollbackHost.exe','DocumentInfo.exe','FontHost.exe']");
 const file=path.resolve('work/package-032/baseline.cjs');fs.writeFileSync(file,baseline);execFileSync(process.execPath,[file],{stdio:'inherit',windowsHide:true});
 // Existing production-core acceptance executes actual packaged workers/helpers with an isolated host.
 let functions=fs.readFileSync('tests/version-027-package.cjs','utf8');functions=functions.slice(functions.indexOf(" await require('esbuild')"));functions="const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');(async()=>{const development="+JSON.stringify(stage)+",delivery="+JSON.stringify(delivery)+",archive="+JSON.stringify(archive)+";"+functions;
 const featureFile=path.resolve('work/package-032/features.cjs');fs.writeFileSync(featureFile,functions);execFileSync(process.execPath,[featureFile],{stdio:'inherit',windowsHide:true});
 // Run the production font service/renderer against the packaged sandbox preload and font helper.
 await require('esbuild').build({entryPoints:['tests/native-ui-028-renderer.ts'],outfile:'work/native-ui-028.js',bundle:true,platform:'browser',target:'chrome138'});
 await require('esbuild').build({entryPoints:['src/main/appearance-service.ts'],outfile:'work/native-ui-028-service.cjs',bundle:true,platform:'node',external:['electron'],define:{__dirname:JSON.stringify(path.join(archive,'dist/main'))}});
 let host=fs.readFileSync('tests/native-ui-028-host.cjs','utf8').replace("path.resolve('dist/preload/index.cjs')",JSON.stringify(path.join(archive,'dist/preload/index.cjs'))).replace("'dist/renderer/one-components.css'",JSON.stringify(path.join(archive,'dist/renderer/one-components.css'))).replace("'dist/renderer/redesign-028.css'",JSON.stringify(path.join(archive,'dist/renderer/redesign-028.css')));
 const nativeHost=path.resolve('work/package-032/native-host.cjs');host=host.replace("require('../work/native-ui-028-service.cjs')","require("+JSON.stringify(path.resolve('work/native-ui-028-service.cjs'))+")");fs.writeFileSync(nativeHost,host);
 const original=fs.readFileSync('tests/native-ui-028.cjs','utf8').replace("args:['tests/native-ui-028-host.cjs']","args:["+JSON.stringify(nativeHost)+"]");const nativeTest=path.resolve('work/package-032/native-test.cjs');fs.writeFileSync(nativeTest,original);execFileSync(process.execPath,[nativeTest],{stdio:'inherit',windowsHide:true});
 for(const name of ['one-components.css','redesign-028.css','redesign-029.css','recent-shelf.css'])assert(asar.extractFile(archive,('dist/renderer/'+name).replaceAll('/','\\')).equals(fs.readFileSync(path.join(delivery,'dist/renderer',name))),name);
 // Execute search against the actual ASAR worker, including its encrypted native dependency.
 await require('esbuild').build({entryPoints:['tests/performance-030-exports.ts'],outfile:'work/package-032/search-services.cjs',bundle:true,platform:'node',external:['better-sqlite3-multiple-ciphers']});
 const searchHost=path.resolve('work/package-032/search-host.cjs');let searchSource=fs.readFileSync('tests/search-030-native.cjs','utf8').replace("require('../work/performance-030/after.cjs')",'require('+JSON.stringify(path.resolve('work/package-032/search-services.cjs'))+')').replaceAll("path.resolve('dist/main/search-worker.cjs')",JSON.stringify(path.join(archive,'dist/main/search-worker.cjs')));fs.writeFileSync(searchHost,searchSource);execFileSync(path.join(root,'Clipper.exe'),[searchHost,'--host'],{stdio:'inherit',env:{...process.env,ELECTRON_RUN_AS_NODE:'1'},windowsHide:true,timeout:60000});
 const searchRuntime=JSON.parse(fs.readFileSync('work/search-030-native/results.json'));assert(searchRuntime.passed&&searchRuntime.cases===9);fs.copyFileSync('work/search-030-native/results.json','work/package-032/search-results.json');
 const transferEnv={...process.env,CLIPPER_TRANSFER_ASAR:archive};delete transferEnv.ELECTRON_RUN_AS_NODE;execFileSync(require('electron'),['tests/transfer-032-host.cjs','packaged'],{stdio:'inherit',env:transferEnv,windowsHide:true,timeout:60000});const transfer=JSON.parse(fs.readFileSync('work/transfer-032/packaged.json'));assert(transfer.passed&&transfer.resumedCache&&transfer.protectedExport&&transfer.export.largestDecodedBufferBytes===196608);fs.copyFileSync('work/transfer-032/packaged.json','work/package-032/transfer-results.json');
 const result={passed:true,version:'0.32.0',packagedSourceAndBuild:true,packagedEncryptedRecovery:true,packagedPreviousFeatures:true,packagedNativeFont:true,packagedRendererAssets:true,packagedEncryptedSearch:true,packagedImageTransfer:true,systemClipboard:false,desktopInput:false};fs.writeFileSync('work/package-032/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;});
