const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
(async()=>{fs.mkdirSync('work/performance-031',{recursive:true});const build=require('esbuild').build;
 for(const [name,source] of [['before','../delivery-0.30.0/tests/performance-031-exports.ts'],['after','tests/performance-031-exports.ts']]){
  const contents=name==='before'?"export {contentInfo,exportFormat,exportAttachment} from '../delivery-0.30.0/src/main/content-info';export {validateAttachments} from '../delivery-0.30.0/src/shared/attachments';export {validateFormats} from '../delivery-0.30.0/src/shared/formats';export {Store} from '../delivery-0.30.0/src/main/store';":undefined;
  await build({...(contents?{stdin:{contents,resolveDir:process.cwd(),loader:'ts'}}:{entryPoints:[source]}),outfile:'work/performance-031/'+name+'.cjs',bundle:true,platform:'node',external:['better-sqlite3-multiple-ciphers','electron','./native','./file-commit','./attachment-export']});
  const text=execFileSync(require('electron'),['--expose-gc','tests/performance-031-host.cjs',name],{env:{...process.env,ELECTRON_RUN_AS_NODE:'1'},encoding:'utf8',windowsHide:true,timeout:60000});const result=JSON.parse(text.trim());fs.writeFileSync('work/performance-031/'+name+'.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }
 const before=JSON.parse(fs.readFileSync('work/performance-031/before.json')),after=JSON.parse(fs.readFileSync('work/performance-031/after.json'));require('node:assert/strict').deepEqual(after.info,before.info);fs.writeFileSync('work/performance-031/comparison.json',JSON.stringify({passed:true,scope:'Actual production format-info, validators and export function in isolated Electron Node runtime. Synthetic 10MiB private format, VM dialog/commit adapters and private real file I/O. Seven timing samples; decoded allocation sizes instrumented, not whole-app peak memory.',before,after},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
