const {chromium}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {setup}=require('./renderer-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
const {prepare}=require('./preview-035-fixture.cjs');

(async()=>{await fs.mkdir('work/preview-035',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[],errors=[];
try{for(const language of ['zh-CN','en'])for(const theme of ['light','dark'])for(const kind of ['rows','long-line','code']){
 const context=await browser.newContext({viewport:{width:1240,height:800}}),requests=[];await context.addInitScript(setup,language);await context.addInitScript(extra,language);await context.addInitScript(prepare,{theme,kind});
 await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);assert(/^[\w./-]+$/.test(name)&&!name.includes('..'));requests.push(name);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');assert(!requests.some(n=>n.startsWith('text-preview')),'Reader assets must remain unloaded for short text');assert.equal(await page.evaluate(()=>test.workers),0);
 await page.locator('[data-id=reader]').click();await page.waitForSelector('.text-reader[data-ready=true]');
 const initial=await page.evaluate(async()=>{window.readerModule=await import('/text-preview/text-preview.js');const host=document.querySelector('#detail .preview-body');window.readerRoot=document.querySelector('.text-reader');return {exact:readerModule.previewText(host)===test.text.replace(/\r\n|\r/g,'\n'),state:readerModule.previewState(host),visible:document.querySelector('.cm-content').textContent.length,workers:test.workers,bytes:new TextEncoder().encode(test.text).length};});
 assert(initial.exact&&initial.state.readOnly&&initial.workers===0);assert(initial.bytes<=1048576);assert(initial.visible<initial.state.length/2);if(kind==='code')await page.waitForSelector('.syntax-keyword');
 const editor=page.locator('.cm-content');await editor.focus();await editor.press('Control+f');await page.waitForSelector('.code-search input',{state:'visible'});assert.equal(await page.locator('.code-search input').getAttribute('placeholder'),language==='en'?'Find text':'查找文本');
 await page.locator('.code-search input').fill('END_PRIVATE_035_世界😃');await page.locator('.code-search input').press('Enter');const found=await page.evaluate(()=>readerModule.previewState(document.querySelector('#detail .preview-body')));assert.equal(found.selection.to,initial.state.length);assert(found.selection.from>initial.state.length-30);
 await page.locator('.code-search input').fill('MISSING_PRIVATE_MARKER');await page.locator('.code-search input').press('Enter');assert.equal(await page.locator('.preview-search-state').textContent(),language==='en'?'No matching text':'没有匹配文本');await page.locator('.code-search input').press('Escape');assert.equal(await page.evaluate(()=>test.hide),0);
 await editor.press('ArrowDown');await editor.press('Enter');assert.equal(await page.evaluate(()=>test.copies.length),0);assert.equal(await page.locator('[data-id=reader]').getAttribute('aria-pressed'),'true');await editor.press('a');assert(await page.evaluate(()=>readerModule.previewText(document.querySelector('#detail .preview-body'))===test.text.replace(/\r\n|\r/g,'\n')));
 await editor.press('Control+a');const copied=await page.evaluate(()=>{const data=new DataTransfer();document.querySelector('.cm-content').dispatchEvent(new ClipboardEvent('copy',{clipboardData:data,bubbles:true,cancelable:true}));return data.getData('text/plain');});assert.equal(copied,await page.evaluate(()=>test.text.replace(/\r\n|\r/g,'\n')),'Full selection copy uses the complete document without system clipboard');
 const wrap=await page.locator('#preview-wrap').getAttribute('aria-pressed');await page.locator('#preview-wrap').click();assert.equal(await page.locator('#preview-wrap').getAttribute('aria-pressed'),String(wrap!=='true'));await page.locator('#preview-wrap').click();
 await page.waitForTimeout(200);await page.setViewportSize({width:900,height:620});await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:150}));await page.waitForTimeout(160);const geometry=await page.locator('.text-reader').evaluate(el=>{const r=el.getBoundingClientRect(),scroller=el.querySelector('.cm-scroller');return {inside:r.x>=0&&r.y>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,scroll:scroller.clientWidth>0&&scroller.clientHeight>0,contained:document.body.scrollWidth<=innerWidth+1};});assert(Object.values(geometry).every(Boolean),JSON.stringify({language,theme,kind,geometry}));await page.setViewportSize({width:1240,height:800});await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:100}));await page.waitForTimeout(160);await editor.focus();await editor.press('ArrowRight');await editor.press('Escape');assert.equal(await page.evaluate(()=>test.hide),1);const before=await page.evaluate(()=>test.details);await page.evaluate(()=>document.querySelector('.cm-scroller').scrollTop=1000);await page.waitForTimeout(160);await page.evaluate(()=>{window.savedScroll=document.querySelector('.cm-scroller').scrollTop;for(let i=0;i<8;i++)fixture.refresh();});await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>test.details),before);const preserved=await page.evaluate(()=>({same:readerRoot===document.querySelector('.text-reader'),scroll:document.querySelector('.cm-scroller').scrollTop,saved:savedScroll}));assert(preserved.same&&preserved.scroll===preserved.saved,JSON.stringify({language,theme,kind,preserved}));
 await page.locator('#copy').click();await page.waitForTimeout(20);assert.deepEqual(await page.evaluate(()=>test.copies),[['reader',false]]);
 await page.evaluate(()=>{window.metadataScroll=document.querySelector('.cm-scroller').scrollTop;fixture.state.clips.find(c=>c.id==='reader').favorite=true;fixture.refresh();});await page.waitForFunction(()=>document.getElementById('favorite')?.getAttribute('aria-pressed')==='true');await page.waitForSelector('.text-reader[data-ready=true]');assert.equal(await page.evaluate(()=>test.details),before,'Metadata-only changes retain the full payload');assert(await page.evaluate(()=>readerRoot===document.querySelector('.text-reader')&&document.querySelector('.cm-scroller').scrollTop===metadataScroll&&readerModule.previewText(document.querySelector('#detail .preview-body'))===test.text.replace(/\r\n|\r/g,'\n')),'Metadata updates preserve the reader, reading position and exact full text');
 // A late full payload may not repopulate a different page or create a worker there.
 await page.evaluate(()=>{test.block=true;fixture.state.clips.find(c=>c.id==='reader').hash='reader-v2';fixture.refresh();});await page.waitForFunction(()=>!!test.resolve);await page.locator('[data-page=settings]').click();await page.waitForSelector('#save-settings',{state:'attached'});const workers=await page.evaluate(()=>test.workerRequests);await page.evaluate(()=>test.resolve());await page.waitForTimeout(120);assert.equal(await page.locator('.text-reader').count(),0);assert.equal(await page.evaluate(()=>test.workerRequests),workers);assert.equal(await page.evaluate(()=>test.workers),0);
 results.push({language,theme,kind,characters:initial.state.length,visibleCharacters:initial.visible,exactFullText:true,fullFind:true,fullSelectionCopy:true,originalCopyIPC:true,readOnly:true,idleLazy:true,unchangedRefresh:true,metadataRefresh:true,staleDisposal:true,narrowLargeFont:true,syntax:kind==='code'});
 await context.close();
}
for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){
 const context=await browser.newContext({viewport:{width:1240,height:800}});await context.addInitScript(setup,language);await context.addInitScript(extra,language);await context.addInitScript(prepare,{theme,kind:'rows'});await context.addInitScript(()=>{const base=clipper,snippet={id:'long-reply',kind:'text',title:'Full reply',text:test.text,updatedAt:100,revision:1,shortcut:''};fixture.state.snippets.push(snippet);test.snippetCalls=0;window.clipper=new Proxy({snippetDetail:async id=>{test.snippetCalls++;return id==='long-reply'?{...snippet,payload:{text:snippet.text}}:base.snippetDetail(id);},useSnippet:async(...args)=>test.copies.push(args)},{get:(o,k)=>k in o?o[k]:base[k]});});
 await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);assert(/^[\w./-]+$/.test(name)&&!name.includes('..'));await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');await page.locator('[data-page=replies]').click();await page.locator('[data-id=long-reply]').click();await page.waitForSelector('.text-reader[data-ready=true]');assert(await page.evaluate(async()=>{window.readerModule=await import('/text-preview/text-preview.js');return readerModule.previewText(document.querySelector('#detail .preview-body'))===test.text.replace(/\r\n|\r/g,'\n');}));await page.locator('#copy').click();await page.waitForFunction(()=>test.copies.length===1);assert.equal(await page.evaluate(()=>test.copies[0][0]),'long-reply');const calls=await page.evaluate(()=>test.snippetCalls);await page.evaluate(()=>fixture.refresh());await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>test.snippetCalls),calls);await page.evaluate(()=>{const s=fixture.state.snippets.find(s=>s.id==='long-reply');s.updatedAt++;s.revision++;s.text='CHANGED_PRIVATE_REPLY_035';fixture.refresh();});await page.waitForFunction(()=>document.querySelector('#detail .text-preview')?.textContent==='CHANGED_PRIVATE_REPLY_035');assert.equal(await page.locator('.text-reader').count(),0);assert.equal(await page.evaluate(()=>test.workers),0);results.push({language,theme,surface:'reply',fullText:true,originalCopyIPC:true,unchangedRefresh:true,contentInvalidation:true,disposal:true});await context.close();
}
assert.deepEqual(errors,[]);await fs.writeFile('work/preview-035/behavior.json',JSON.stringify({passed:true,cases:results.length,results,errors,scope:'Production renderer, workers and lazy ESM in headless Chromium, private <=1 MiB full text; clipboard copy tested using an injected DataTransfer, not system clipboard.'},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
