const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createHash}=require('node:crypto');
const {Store,StorageManager,RecoveryManager,BackupManager,encodeBackup,decodeBackup,exportInWorker,defaults}=require('../work/test-exports.cjs');
const folder=()=>generated.mkdtemp(path.resolve('work/recovery-'));
const sha=async file=>createHash('sha256').update(await fs.readFile(file)).digest('hex');
const worker=path.resolve('work/test-backup-worker.cjs');
test('startup detects damaged/default and future databases without mutating source',async()=>{
 for(const kind of ['damaged','future','settings']){const root=await folder(),file=path.join(root,'history.sqlite');if(kind==='damaged')await fs.writeFile(file,'broken fixture');else{const db=new Store(file);if(kind==='future')db.db.exec('PRAGMA user_version=900');else db.setMeta('settings',{...defaults,paused:'bad'});db.close();}const before=await sha(file);await assert.rejects(()=>new StorageManager(root).start());assert.equal(await sha(file),before);await assert.rejects(()=>fs.stat(path.join(root,'storage-location.json')));}
});
test('recovery copies a consistent WAL snapshot, preserves originals, queues and secrets, pauses recording and automation',async()=>{
 const root=await folder(),source=await folder(),dbfile=path.join(source,'history.sqlite'),sourceStore=new Store(dbfile);const clip=sourceStore.add({text:'recovered WAL content'},'fixture');sourceStore.setQueue([clip.id]);sourceStore.setMeta('ai-profiles',{key:'encrypted fixture'});sourceStore.setMeta('automatic-backup',{enabled:true,nextAt:1});sourceStore.setMeta('lan-config',{enabled:true,id:'cloned identity fixture',peers:[]});sourceStore.setMeta('lan-index',[]);sourceStore.save({...sourceStore.get(clip.id),shared:true});
 const manager=new StorageManager(root);await fs.writeFile(path.join(root,'storage-location.json'),'{broken pointer');await assert.rejects(()=>manager.start());const recover=new RecoveryManager(manager),choice=await recover.choose('database',source);const preview=await recover.preview(choice.token);assert.equal(preview.clips,1);assert.equal(sourceStore.settings.paused,false);
 const recovered=await recover.commit(choice.token);assert.notEqual(manager.directory,source);assert.equal(recovered.settings.paused,true);assert.equal(recovered.meta('lan-config',{}).enabled,false);assert.equal(recovered.meta('lan-config',{}).id,undefined);assert.deepEqual(recovered.meta('lan-index',[]),[]);assert.equal(recovered.get(clip.id).shared,false);assert.equal(recovered.meta('automatic-backup',{}).enabled,false);assert.deepEqual(recovered.queue,[clip.id]);assert.equal(recovered.meta('ai-profiles',{}).key,'encrypted fixture');assert.equal(sourceStore.meta('automatic-backup',{}).enabled,true);assert.equal(sourceStore.settings.paused,false);sourceStore.close();const oldHash=await sha(dbfile);recovered.add({text:'new restored copy'},'fixture');recovered.close();assert.equal(await sha(dbfile),oldHash);
 const previous=(await fs.readdir(root)).find(n=>n.startsWith('storage-location.before-recovery-'));assert.equal(await fs.readFile(path.join(root,previous),'utf8'),'{broken pointer');const restarted=new StorageManager(root);const opened=await restarted.start();assert.equal(opened.list().length,2);assert.equal(opened.settings.paused,true);opened.close();
});
test('recovery wrong password/cancel/changed source cannot commit; valid encrypted restore creates a new history',async()=>{
 const root=await folder(),manager=new StorageManager(root),source=new Store(':memory:');source.add({text:'backup only'},'fixture');const file=path.join(root,'restore.clipper');await fs.writeFile(file,await encodeBackup(source.backup(),'restore fixture password'));source.close();const before=await sha(file),recover=new RecoveryManager(manager);let choice=await recover.choose('backup',file);await assert.rejects(()=>recover.preview(choice.token,'wrong'));await assert.rejects(()=>recover.commit(choice.token),/先校验/);await recover.preview(choice.token,'restore fixture password');recover.cancel();await assert.rejects(()=>recover.commit(choice.token),/过期/);
 choice=await recover.choose('backup',file);await recover.preview(choice.token,'restore fixture password');const opened=await recover.commit(choice.token);assert.equal(opened.list().length,1);assert.equal(opened.settings.paused,true);assert.equal(await sha(file),before);opened.close();
 const other=await folder(),db=new Store(path.join(other,'history.sqlite'));db.add({text:'before'},'fixture');choice=await recover.choose('database',other);await recover.preview(choice.token);db.add({text:'after'},'fixture');const pointer=await fs.readFile(path.join(root,'storage-location.json'),'utf8');await assert.rejects(()=>recover.commit(choice.token),/改变/);assert.equal(await fs.readFile(path.join(root,'storage-location.json'),'utf8'),pointer);assert.equal((await fs.readdir(root)).filter(f=>f.startsWith('recovered-')).length,1);db.close();
});
test('recovery pointer commit failure keeps originals and cleans only its own candidate',async()=>{
 const root=await folder(),source=await folder(),store=new Store(path.join(source,'history.sqlite'));store.add({text:'stay intact'},'fixture');store.close();await fs.mkdir(path.join(root,'storage-location.json'));const recover=new RecoveryManager(new StorageManager(root)),choice=await recover.choose('database',source);await recover.preview(choice.token);const hash=await sha(path.join(source,'history.sqlite'));await assert.rejects(()=>recover.commit(choice.token));assert.equal(await sha(path.join(source,'history.sqlite')),hash);assert.deepEqual(await fs.readdir(root),['storage-location.json']);
});
test('read-only snapshot stays consistent while live store writes; metadata list excludes payload',async()=>{
 const root=await folder(),file=path.join(root,'history.sqlite'),live=new Store(file);const clip=live.add({text:'initial'},'fixture'),snapshot=new Store(file,false,true);live.add({text:'later'},'fixture');assert.equal(snapshot.backup().clips.length,1);assert.equal(live.list().length,2);assert.equal('payload' in live.list()[0],false);assert.equal(live.get(clip.id).payload.text,'initial');snapshot.close();live.close();
});
test('background export survives failures, releases handles and keeps the event loop responsive',async()=>{
 const root=await folder(),file=path.join(root,'history.sqlite'),output=path.join(root,'backup.clipper'),store=new Store(file);for(let i=0;i<24;i++)store.add({text:`${i}-`+'x'.repeat(900000)},'fixture',undefined,undefined,false);
 let ticks=0;const timer=setInterval(()=>ticks++,10);try{await exportInWorker(file,output,'worker fixture password',worker);assert.ok(ticks>5);const backup=await decodeBackup(await fs.readFile(output),'worker fixture password');assert.equal(backup.clips.length,24);
 await assert.rejects(()=>exportInWorker(file,path.join(root,'missing','fail.json'),undefined,worker));await assert.rejects(()=>exportInWorker(file,path.join(root,'timeout.json'),undefined,worker,1));await exportInWorker(file,path.join(root,'retry.json'),undefined,worker);assert.equal((await fs.readdir(root)).filter(n=>n.endsWith('.tmp')).length,0);assert.equal(store.list().length,24);
 }finally{clearInterval(timer);store.close();}
});
test('backup and migration/configuration exclude each other without blocking ordinary history writes',async()=>{
 const store=new Store(':memory:'),root=await folder();let finish;const waiting=new Promise(r=>finish=r),manager=new BackupManager(()=>store,'fixture',root,{available:async()=>true,encrypt:async x=>x,decrypt:async x=>x},()=>{},undefined,()=>waiting);
 const exporting=manager.export(path.join(root,'backup.json'));await assert.rejects(()=>manager.configure({enabled:false,directory:root,intervalHours:24,keep:7,encrypted:false}),/正在备份/);await assert.rejects(()=>manager.exclusive(async()=>{}),/正在备份/);store.add({text:'during backup'},'fixture');assert.equal(store.list().length,1);finish();await exporting;await manager.configure({enabled:false,directory:root,intervalHours:24,keep:7,encrypted:false});store.close();
});
