// Production page and recorder in hidden native windows. Only the source pixels and
// display grant are synthetic; recording, IPC, encrypted staging and preview are real.
const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{build}=require('esbuild');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 const output=path.resolve('work/development/recording-embed');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),entry=path.resolve('dist/main/recording-embed-test.cjs'),host=path.join(output,'host.cjs');
 await build({entryPoints:['src/main/index.ts'],outfile:entry,bundle:true,platform:'node',external:['electron','koffi','better-sqlite3-multiple-ciphers'],plugins:[{name:'synthetic-recording-fixture',setup(builder){builder.onLoad({filter:/[\\/]main[\\/]recording\.ts$/},async args=>{let contents=await fs.readFile(args.path,'utf8');contents=contents.replace('constructor(private ctx:Context){',`constructor(private ctx:Context){(globalThis as any).recordingFixture=this;this.previews.run=async type=>{const display=screen.getPrimaryDisplay();return type==='window'?[]:[{id:'screen:'+display.id+':0',name:'Fixture display',display_id:String(display.id),thumbnail:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4J8AAAAASUVORK5CYII='}];};`);contents=contents.replace('this.session.setDisplayMediaRequestHandler((request,callback)=>','this.session.setDisplayMediaRequestHandler((globalThis as any).recordingGrant=(request,callback)=>');return {contents,loader:'ts'};});}}]});
 await fs.writeFile(host,`const {app,BrowserWindow,globalShortcut}=require('electron');const shortcuts=new Set();globalShortcut.register=(key)=>{shortcuts.add(key);return true;};globalShortcut.unregisterAll=()=>shortcuts.clear();globalShortcut.unregister=key=>shortcuts.delete(key);globalShortcut.isRegistered=key=>shortcuts.has(key);app.setAppPath(${JSON.stringify(path.resolve('.'))});const visible=new Set();BrowserWindow.prototype.show=function(){visible.add(this.id);};BrowserWindow.prototype.showInactive=BrowserWindow.prototype.show;BrowserWindow.prototype.focus=function(){};BrowserWindow.prototype.isVisible=function(){return visible.has(this.id);};BrowserWindow.prototype.hide=function(){visible.delete(this.id);this.emit('hide');};require(${JSON.stringify(entry)});`);
 const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;delete env.CLIPPER_DEVELOPMENT;let app;const errors=[];
 try{
  app=await electron.launch({args:[host],env});const main=await app.firstWindow();main.on('pageerror',error=>errors.push(error.message));await main.waitForSelector('#search');await main.evaluate(async()=>{const state=await clipper.state();await clipper.settings({...state.settings,paused:true});});
  await main.locator('[data-page=capture-tools]').click();await expect(main.locator('[data-capture-mode]')).toHaveCount(3);await expect(main.locator('dialog[open]')).toHaveCount(0);await main.locator('#capture-tab-recording').click();await expect(main.locator('#recording-page-host')).toHaveAttribute('aria-busy','false');
  await expect.poll(()=>app.windows().find(page=>page.url().endsWith('/recorder.html'))?.url()).toContain('/recorder.html');const rec=app.windows().find(page=>page.url().endsWith('/recorder.html'));rec.on('pageerror',error=>errors.push(error.message));await rec.waitForSelector('#sources button');
  assert.equal(await rec.evaluate(()=>clipperRecorder.embedded),true);assert.equal(await rec.evaluate(()=>typeof window.clipper),'undefined');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().endsWith('/recorder.html')).length),0);await expect(rec.locator('body>header')).toBeHidden();await expect(rec.locator('#start')).toBeVisible();
  const bounds=()=>app.evaluate(()=>({bounds:recordingFixture.view.getBounds(),visible:recordingFixture.view.getVisible()}));const first=await bounds();assert(first.visible&&first.bounds.height>250);await main.locator('[data-page=cheats]').hover();await expect(main.locator('#one-tooltip.visible')).toBeVisible();
  const tooltip=await main.locator('#one-tooltip').evaluate(node=>node.getBoundingClientRect().toJSON()),embedded=(await bounds()).bounds;assert(tooltip.right<=embedded.x||tooltip.left>=embedded.x+embedded.width||tooltip.bottom<=embedded.y||tooltip.top>=embedded.y+embedded.height,'Sidebar tooltip must avoid the native recorder view');assert((await bounds()).visible);await main.screenshot({path:path.join(output,'tooltip.png')});await main.mouse.move(10,10);
  await rec.screenshot({path:path.join(output,'setup.png')});await main.evaluate(()=>document.getElementById('dialog').showModal());await expect.poll(async()=>(await bounds()).visible).toBe(false);await main.evaluate(()=>document.getElementById('dialog').close());await expect.poll(async()=>(await bounds()).visible).toBe(true);
  await main.evaluate(()=>clipper.configureAppearance({font:'system',scale:125,density:'comfortable'}));await expect.poll(()=>rec.evaluate(()=>document.documentElement.style.getPropertyValue('--text-scale'))).toBe('1.25');
  await app.evaluate(()=>recordingFixture.host.setSize(860,680));await expect.poll(async()=>(await bounds()).bounds.width).toBeLessThan(first.bounds.width);await expect(rec.locator('#start')).toBeInViewport();await rec.screenshot({path:path.join(output,'setup-narrow.png')});
  await app.evaluate(async({ipcMain})=>{const r=recordingFixture,w=r.host,v=r.view.webContents,fn=ipcMain._invokeHandlers.get('clipper:record-state');for(const event of [{sender:w.webContents,senderFrame:w.webContents.mainFrame},{sender:v,senderFrame:{url:v.getURL()}}]){try{await fn(event);throw Error('Accepted foreign recording IPC');}catch(error){if(!String(error).includes('拒绝'))throw error;}}});
  const denied=await rec.evaluate(async()=>{try{await navigator.mediaDevices.getUserMedia({video:true});return false;}catch{return true;}});assert(denied);
  await rec.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const context=canvas.getContext('2d');let frame=0;window.fixtureDrawing=setInterval(()=>{context.fillStyle=frame++%2?'#215daa':'#a74721';context.fillRect(0,0,320,180);},30);navigator.mediaDevices.getDisplayMedia=async()=>canvas.captureStream(30);});
  await app.evaluate(()=>{const r=recordingFixture,started=r.started.bind(r);r.started=(token,mime)=>{recordingGrant({frame:r.view.webContents.mainFrame,videoRequested:true,audioRequested:false},()=>{});return started(token,mime);};});
  const sizeBefore=await app.evaluate(()=>recordingFixture.host.getSize());await rec.locator('#start').click();await expect(rec.locator('#phase-label')).toHaveText('正在录制');assert.deepEqual(await app.evaluate(()=>recordingFixture.host.getSize()),sizeBefore);assert(await app.evaluate(()=>recordingFixture.host.isVisible()));await delay(700);
  await main.locator('[data-page=history]').click();await expect.poll(async()=>(await bounds()).visible).toBe(false);assert.equal((await rec.evaluate(()=>clipperRecorder.state())).phase,'recording');await delay(700);await main.locator('[data-page=capture-tools]').click();await expect(main.locator('#capture-tab-recording')).toHaveAttribute('aria-selected','true');await expect.poll(async()=>(await bounds()).visible).toBe(true);await expect(rec.locator('#phase-label')).toHaveText('正在录制');
  await rec.locator('#pause').click();await expect(rec.locator('#phase-label')).toHaveText('已暂停');await rec.locator('#pause').click();await delay(600);await rec.locator('#stop').click();await expect(rec.locator('#result')).toBeVisible();const state=await rec.evaluate(()=>clipperRecorder.state());assert(state.bytes>0&&state.seconds>1);await expect.poll(()=>rec.locator('#preview').evaluate(video=>video.videoWidth)).toBe(320);await expect.poll(()=>rec.locator('#preview').evaluate(video=>Number.isFinite(video.duration)&&video.duration>0)).toBe(true);
  await main.locator('[data-page=history]').click();await main.locator('[data-page=capture-tools]').click();assert.equal((await rec.evaluate(()=>clipperRecorder.state())).token,state.token);await rec.screenshot({path:path.join(output,'preview.png')});
  await assert.rejects(main.evaluate(()=>clipper.embedRecorder({x:-1,y:0,width:100,height:100})),/Invalid recording bounds/);await rec.evaluate(()=>clearInterval(window.fixtureDrawing));await rec.locator('#again').click();await rec.locator('dialog [data-response="1"]').click();await expect(rec.locator('#setup')).toBeVisible();
  await app.evaluate(async()=>{const r=recordingFixture;await r.abort();if(r.host)throw Error('Host retained');});assert.equal(await main.evaluate(()=>!!document.getElementById('content')),true);assert.deepEqual(errors,[]);
  console.log('PASS: inline native recorder, no extra window, isolated permissions, appearance, resize, modal and tooltip occlusion, retained real recording/pause/preview, invalid bounds and safe abort');
 }finally{if(app){await app.evaluate(async()=>{if(globalThis.recordingFixture)await recordingFixture.abort();}).catch(()=>{});await app.close().catch(()=>{});}}
})().catch(error=>{console.error(error);process.exitCode=1;});
