const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {Store,StorageManager,encodeBackup}=require('../work/test-exports.cjs');
async function run(){
 const output=path.resolve('work/recovery-ui');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),source=await fs.mkdtemp(path.join(output,'source-'));
 const sourceStore=new Store(path.join(source,'history.sqlite'));sourceStore.add({text:'恢复后可见的历史记录'},'fixture');sourceStore.saveSnippet({title:'恢复模板',text:'模板内容'});sourceStore.close();const read=new Store(path.join(source,'history.sqlite'),false,true),file=path.join(output,'backup-'+path.basename(profile)+'.clipper');await fs.writeFile(file,await encodeBackup(read.backup(),'recovery UI fixture password'));read.close();
 const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app;
 const launch=async root=>{const options=process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[]}:{args:[path.resolve('.')]};return electron.launch({...options,env:{...env,CLIPPER_DATA_DIR:root}});};
 const choose=async file=>app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);
 try{
  await fs.writeFile(path.join(profile,'storage-location.json'),'{damaged location fixture');app=await launch(profile);let page=await app.firstWindow();await page.waitForSelector('#choose-backup');await expect(page.locator('#retry')).toBeEnabled();assert.equal(await page.evaluate(()=>typeof window.clipper),'undefined');const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await helper.evaluate(({clipboard})=>clipboard.writeText('DO NOT CAPTURE DURING RECOVERY'));await page.waitForTimeout(800);await assert.rejects(()=>fs.stat(path.join(profile,'history.sqlite')));await page.screenshot({path:path.join(output,'recovery-light.png')});
  await choose(file);await page.locator('#choose-backup').click();await page.locator('#password').fill('wrong');await page.locator('#unlock button').click();await expect(page.locator('#feedback')).toContainText('密码不正确');await assert.rejects(()=>fs.stat(path.join(profile,'history.sqlite')));
  await page.locator('#password').fill('recovery UI fixture password');await page.locator('#unlock button').click();await expect(page.locator('#summary')).toBeVisible();await page.screenshot({path:path.join(output,'recovery-preview.png')});await page.locator('#cancel').click();await expect(page.locator('#choices')).toBeVisible();await assert.rejects(()=>fs.stat(path.join(profile,'history.sqlite')));
  await page.locator('#choose-backup').click();await page.locator('#password').fill('recovery UI fixture password');await page.locator('#unlock button').click();await expect(page.locator('#commit')).toBeEnabled();const ready=app.waitForEvent('window');await page.locator('#commit').click();page=await ready;await page.waitForSelector('#search');let state=await page.evaluate(()=>window.clipper.state());assert.equal(state.clips.length,1);assert.equal(state.settings.paused,true);assert.equal(state.snippets.length,1);const data=await page.evaluate(()=>window.clipper.dataState());assert.equal(data.backup.enabled,false);assert.equal(typeof data.backup.directory,'string');assert.equal(data.directory.startsWith(path.join(profile,'recovered-')),true);const saved=(await fs.readdir(profile)).find(n=>n.startsWith('storage-location.before-recovery-'));assert.equal(await fs.readFile(path.join(profile,saved),'utf8'),'{damaged location fixture');
  await app.close();app=await launch(profile);page=await app.firstWindow();await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);await app.close();app=null;
  // Existing directory recovery uses a copy, including when its source is currently open elsewhere.
  const broken=await fs.mkdtemp(path.join(output,'broken-'));await fs.writeFile(path.join(broken,'history.sqlite'),'corrupt database fixture');const before=await fs.readFile(path.join(broken,'history.sqlite'));app=await launch(broken);page=await app.firstWindow();await page.waitForSelector('#choose-database');await choose(source);await page.locator('#choose-database').click();await expect(page.locator('#summary')).toBeVisible();await app.evaluate(({nativeTheme})=>{nativeTheme.themeSource='dark';});await page.screenshot({path:path.join(output,'recovery-dark.png')});const next=app.waitForEvent('window');await page.locator('#commit').click();page=await next;await page.waitForSelector('#search');assert.deepEqual(await fs.readFile(path.join(broken,'history.sqlite')),before);assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);await app.close();app=null;
  // A disconnected directory can be reattached and retried without making a copy.
  const retryProfile=await fs.mkdtemp(path.join(output,'retry-')),target=await fs.mkdtemp(path.join(output,'target-')),storage=new StorageManager(retryProfile);await storage.start();storage.store.add({text:'retry existing directory'},'fixture');await storage.migrate((await storage.prepare(target)).token);storage.store.close();await fs.rename(target,target+'-offline');app=await launch(retryProfile);page=await app.firstWindow();await page.waitForSelector('#retry');await fs.rename(target+'-offline',target);const retryReady=app.waitForEvent('window');await page.locator('#retry').click();page=await retryReady;await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clipper.dataState())).directory,target);assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,1);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,restrictedRecovery:true,noCaptureDuringRecovery:true,wrongPasswordNoMutation:true,cancelNoMutation:true,encryptedRecovery:true,existingDirectoryCopy:true,originalDatabasePreserved:true,retryReattachedDirectory:true,restartUsesRecoveredCopy:true,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
