const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function wav(){const samples=48000*3,b=Buffer.alloc(44+samples*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(48000,24);b.writeUInt32LE(96000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples*2,40);for(let i=0;i<samples;i++)b.writeInt16LE(Math.round(Math.sin(2*Math.PI*659*i/48000)*10000),44+i*2);return b;}
async function run(){const output=path.resolve('work/recording-audio');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),micPath=path.join(output,'microphone-fixture.wav');await fs.writeFile(micPath,wav());const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;let app,rec;const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});
try{const source=await helper.firstWindow();await source.waitForSelector('#target');await source.evaluate(()=>{document.body.innerHTML='<h2>Clipper 系统声音验收</h2><button id="tone">播放低音量测试音</button>';document.getElementById('tone').onclick=async()=>{window.toneContext=new AudioContext();const oscillator=window.toneContext.createOscillator(),gain=window.toneContext.createGain();oscillator.frequency.value=437;gain.gain.value=.025;oscillator.connect(gain);gain.connect(window.toneContext.destination);oscillator.start();await window.toneContext.resume();};});
 const errors=[];const launch=async(fake=false)=>{const args=fake?['--use-fake-device-for-media-stream','--use-file-for-fake-audio-capture='+micPath]:[];app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args,env}:{args:[path.resolve('.'),...args],env});const main=await app.firstWindow();await main.waitForSelector('#search');const opened=app.waitForEvent('window');await main.evaluate(()=>clipper.openRecorder());rec=await opened;await rec.waitForSelector('#sources button');rec.on('pageerror',e=>errors.push(e.message));};await launch();
 const stats=async bytes=>rec.evaluate(async bytes=>{const context=new AudioContext(),audio=await context.decodeAudioData(Uint8Array.from(bytes).buffer),samples=audio.getChannelData(0),start=Math.floor(audio.sampleRate*.5),n=Math.min(samples.length-start,Math.floor(audio.sampleRate));let sum=0;for(let i=0;i<n;i++)sum+=samples[start+i]**2;const magnitude=f=>{let re=0,im=0;for(let i=0;i<n;i++){const phase=2*Math.PI*f*i/audio.sampleRate;re+=samples[start+i]*Math.cos(phase);im+=samples[start+i]*Math.sin(phase);}return Math.sqrt(re*re+im*im)/n;};const result={duration:audio.duration,channels:audio.numberOfChannels,rms:Math.sqrt(sum/n),system:magnitude(437),microphone:magnitude(659)};await context.close();return result;},[...bytes]);
 const record=async(microphone,system,video=false)=>{await rec.locator('#record-'+(video?'video':'audio')).click();if(video){await rec.locator('#windows').click();await rec.locator('#sources button').filter({hasText:'Clipper 测试目标'}).click();}await rec.locator('#system-audio').setChecked(system);await rec.locator('#microphone').setChecked(microphone);await rec.locator('#start').click();await expect(rec.locator('#phase-label')).toHaveText('正在录制',{timeout:15000});await wait(2300);await rec.locator('#stop').click();await expect(rec.locator('#result')).toBeVisible({timeout:15000});const state=await rec.evaluate(()=>window.clipperRecorder.state());if(video){assert.match(state.mime,/video\/mp4;codecs=avc1\.[0-9a-f]+,mp4a\.40\.2/i);await expect.poll(()=>rec.locator('#preview').evaluate(v=>v.videoWidth)).toBeGreaterThan(0);}else assert.equal(state.mime,'audio/mp4;codecs=mp4a.40.2');await expect.poll(()=>rec.locator('#preview').evaluate(v=>Number.isFinite(v.duration)&&v.duration>1)).toBe(true);const target=path.join(output,`audio-${microphone}-${system}-${Date.now()}.${video?'mp4':'m4a'}`);await app.evaluate(({dialog},file)=>dialog.showSaveDialog=async()=>({canceled:false,filePath:file}),target);await rec.evaluate(()=>window.clipperRecorder.save());const data=await stats(await fs.readFile(target));await rec.screenshot({path:path.join(output,`audio-${microphone}-${system}.png`)});await rec.evaluate(()=>window.clipperRecorder.cancel());await expect(rec.locator('#setup')).toBeVisible();return data;};
 console.log('Actual Windows loopback records known system tone; audio-only drops video');await source.locator('#tone').click();const system=await record(false,true);console.log('System',system);assert.ok(system.rms>.0005);assert.ok(system.system>.0001);const videoAudio=await record(false,true,true);assert.ok(videoAudio.system>.0001);await source.evaluate(()=>window.toneContext.close());
 console.log('Microphone pipeline uses a WAV test device, never the physical microphone');await app.close();await launch(true);const mic=await record(true,false);console.log('Microphone fixture',mic);assert.ok(mic.microphone>.01);
 console.log('Real system audio and a controlled microphone stream mix into one encoded audio track');await app.close();await launch();await rec.evaluate(()=>{navigator.mediaDevices.getUserMedia=async options=>{if(!options.audio||options.video)throw Error('Unexpected fixture access');const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain(),destination=context.createMediaStreamDestination();oscillator.frequency.value=659;gain.gain.value=.12;oscillator.connect(gain);gain.connect(destination);oscillator.start();await context.resume();window.mixFixtureContext=context;return destination.stream;};});await source.locator('#tone').click();const mixed=await record(true,true);console.log('Mixed',mixed);assert.ok(mixed.system>.0001&&mixed.microphone>.01);await source.evaluate(()=>window.toneContext.close());await rec.evaluate(()=>window.mixFixtureContext.close());assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,actualWindowsLoopback:true,knownSystemTone:true,microphoneFixture:true,physicalMicrophone:false,aacDecode:true,videoWithSystemAudio:true,mixedFrequencies:true,system,mic,mixed,output},null,2));
}finally{await sourceSafe();if(rec&&!rec.isClosed())await rec.evaluate(()=>window.clipperRecorder.cancel()).catch(()=>{});if(app)await app.close();await helper.evaluate(({clipboard})=>global.restoreClipboard());await helper.close();}async function sourceSafe(){try{const p=await helper.firstWindow();await p.evaluate(()=>window.toneContext?.close());}catch{}}}
run().catch(e=>{console.error(e);process.exitCode=1});
