const {chooseReferenceTab}=require('./reference-helpers.cjs');
const {chromium}=require('@playwright/test');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const {setup}=require('./renderer-fixture.cjs');

(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const errors=[];let context;
 try{
  context=await browser.newContext({viewport:{width:1280,height:820}});
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:'https://clipper.test'});
  await context.addInitScript(setup);
  await context.route('https://clipper.test/**',async route=>{
   const name=new URL(route.request().url()).pathname.slice(1);
   if(!/^(?:[\w.-]+|(?:katex-fonts|emoji-atlas)\/[\w.-]+)$/.test(name))return route.abort();
   try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.woff2')?'font/woff2':'application/javascript'});}catch{return route.abort();}
  });
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  await page.goto('https://clipper.test/index.html');await page.waitForSelector('.clip-row');
  assert.equal(await page.locator('.sidebar').evaluate(node=>Math.round(node.getBoundingClientRect().width)),208);
  assert.equal(await page.locator('.sidebar-group').count(),3);
  assert.equal(await page.locator('#main').evaluate(node=>getComputedStyle(node).borderLeftWidth),'1px');
  await page.locator('[data-page="symbols"]').click();
  await page.waitForSelector('.reference-item');
  await page.waitForSelector('.reference-emoji-glyph');
  assert.equal(await page.locator('.reference-page canvas,.reference-page img').count(),0);
  await fs.mkdir('work/reference-ui',{recursive:true});
  await page.screenshot({path:'work/reference-ui/emoji.png'});
  const number=async()=>Number((await page.locator('.reference-tabs>.active [data-tab-count]').textContent()).replace(/\D/g,''));
  const emojiTotal=await number();assert.ok(emojiTotal>1900&&emojiTotal<2100);
  assert.equal(await page.locator('.reference-tabs.segment-ready').count(),1);
  const referenceLayout=()=>page.locator('.reference-page').evaluate(root=>{const tabs=root.querySelector('.reference-tabs').getBoundingClientRect(),search=root.querySelector('.reference-search').getBoundingClientRect(),workspace=root.querySelector('.reference-workspace'),nav=root.querySelector('.reference-nav').getBoundingClientRect();return {sameRow:Math.abs(tabs.top+tabs.height/2-search.top-search.height/2)<1,searchRight:Math.abs(search.right-root.getBoundingClientRect().right-(-parseFloat(getComputedStyle(root).paddingRight)))<1,navWidth:nav.width,border:getComputedStyle(workspace).borderTopWidth};});
  const symbolsLayout=await referenceLayout();assert.ok(symbolsLayout.sameRow&&symbolsLayout.searchRight,JSON.stringify(symbolsLayout));assert.equal(symbolsLayout.border,'0px');
  assert.equal(await page.locator('.reference-heading p').count(),0);
  assert.ok(await page.locator('.reference-tones').evaluate(node=>node.getBoundingClientRect().top-document.querySelector('.reference-primary-controls').getBoundingClientRect().bottom<=16),'Tone selector should sit close to the controls');
  assert.equal(await page.locator('.reference-scroll').evaluate(node=>getComputedStyle(node).paddingRight),'14px');
  assert.ok(await page.locator('#reference-results').evaluate(node=>{const scroll=node.parentElement;return scroll.getBoundingClientRect().right-node.getBoundingClientRect().right>=14;}));
  assert.ok(await page.locator('.reference-item').count()<220,'Only nearby rows should be mounted');
  assert.equal(await page.locator('.reference-item strong,.reference-item small').count(),0);
  await page.locator('.reference-item').first().hover();await page.waitForSelector('.reference-popover:not([hidden])');
  const fullHeight=await page.locator('#reference-results').evaluate(node=>node.offsetHeight);
  await page.locator('[data-category="Food & Drink"]').click();
  await page.waitForFunction(()=>document.querySelector('.reference-scroll').scrollTop>1200);
  await page.waitForFunction(()=>document.querySelector('#reference-categories [aria-current]')?.dataset.category==='Food & Drink');
  await page.waitForTimeout(450);
  assert.ok(await page.locator('.reference-popover').evaluate(node=>node.hidden),'Category scrolling must not reopen stale hover details');
  assert.equal(await number(),emojiTotal,'Category navigation must not filter the list');
  assert.equal(await page.locator('#reference-results').evaluate(node=>node.offsetHeight),fullHeight);
  assert.ok(await page.locator('.reference-item').count()<220);
  await page.locator('[data-category="Smileys & Emotion"]').click();
  await page.waitForFunction(()=>document.querySelector('.reference-scroll').scrollTop===0);
  await page.locator('#reference-search').fill('grinning face');
  assert.ok(await page.locator('.reference-item').count()>0);
  await page.locator('.reference-item.reference-main').first().click();
  assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).length>0);
  assert.equal(await page.locator('.reference-nav .reference-tones').count(),1);assert.equal(await page.locator('#reference-tone-label,.reference-toolbar').count(),0);
  const face=page.locator('.reference-item[aria-label="grinning face"] .reference-emoji-glyph');
  await face.waitFor();assert.equal(await face.textContent(),'😀');
  await page.locator('[data-tone="5"]').click();
  assert.equal(await face.getAttribute('data-emoji'),'😀');
  assert.equal(await face.textContent(),'😀','Smileys have no Unicode skin tone variants');
  await page.locator('.reference-item[aria-label="grinning face"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'😀');
  for(const [name,base] of [['thumbs up','👍'],['person','🧑']]){
   await page.locator('#reference-search').fill(name);
   await page.waitForSelector(`.reference-item[aria-label="${name}"]`);
   const variants=new Set();
   for(let tone=0;tone<6;tone++){
    await page.locator(`[data-tone="${tone}"]`).click();
    const glyph=base+(tone?String.fromCodePoint(0x1F3FA+tone):'');
    await page.waitForFunction(({name,glyph})=>document.querySelector(`.reference-item[aria-label="${name}"] .reference-emoji-glyph`)?.textContent===glyph,{name,glyph});
    const span=page.locator(`.reference-item[aria-label="${name}"] .reference-emoji-glyph`);
    const box=await span.evaluate(node=>({width:node.offsetWidth,height:node.offsetHeight,font:getComputedStyle(node).fontFamily}));
    assert.ok(box.width>0&&box.height>0&&box.font.includes('Segoe UI Emoji'));
    variants.add(await span.textContent());
    await page.locator(`.reference-item[aria-label="${name}"]`).click();
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),glyph);
   }
   assert.equal(variants.size,6,`${name}: all six Unicode skin tone sequences must be displayed and copied`);
  }
  await page.screenshot({path:'work/reference-ui/person-dark-tone.png'});
  await page.locator('#reference-search').fill('thumbs up');
  await page.waitForFunction(()=>document.querySelector('.reference-item[aria-label="thumbs up"]'));
  await page.locator('[data-tone="3"]').click();
  await page.locator('.reference-item[aria-label="thumbs up"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'👍🏽');
  await page.mouse.move(10,10);await page.locator('.reference-item[aria-label="thumbs up"]').hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  assert.ok((await page.locator('.reference-popover').textContent()).includes('U+1F3FD'));
  assert.equal(await page.locator('[data-detail-tone]').count(),6);
  assert.deepEqual(await page.locator('[data-detail-tone] .reference-emoji-glyph').allTextContents(),['👍','👍🏻','👍🏼','👍🏽','👍🏾','👍🏿']);
  await page.locator('[data-detail-tone="1"]').hover();
  assert.equal(await page.locator('[data-detail-tone="3"]').getAttribute('aria-pressed'),'true','Hover previews without changing the selected tone');
  await page.locator('[data-tip-copy="main"]').hover();
  assert.ok((await page.locator('.reference-code').textContent()).includes('U+1F3FD'),'Leaving a tone restores the selected preview');
  await page.locator('[data-detail-tone="5"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'👍🏿');
  assert.equal(await page.locator('[data-detail-tone="5"]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('.reference-item[aria-label="thumbs up"] .reference-emoji-glyph').textContent(),'👍🏿');
  await page.screenshot({path:'work/reference-ui/skin-details.png'});
  await page.keyboard.press('Escape');await page.waitForSelector('.reference-popover[hidden]',{state:'attached'});
  await page.locator('#reference-search').fill('person');await page.waitForSelector('.reference-item[aria-label="person"]');
  assert.equal(await page.locator('.reference-item[aria-label="person"] .reference-emoji-glyph').textContent(),'🧑🏽','Other emoji retain the global tone');
  await page.locator('#reference-search').fill('thumbs up');await page.waitForSelector('.reference-item[aria-label="thumbs up"]');
  assert.equal(await page.locator('.reference-item[aria-label="thumbs up"] .reference-emoji-glyph').textContent(),'👍🏿','Individual tone survives filtering');
  await page.locator('[data-tone="3"]').click();
  assert.equal(await page.locator('.reference-item[aria-label="thumbs up"] .reference-emoji-glyph').textContent(),'👍🏽','Reapplying the global tone clears individual choices');
  await page.locator('[data-tone="1"]').click();
  assert.equal(await page.locator('.reference-item[aria-label="thumbs up"] .reference-emoji-glyph').textContent(),'👍🏻','Changing the global tone resets individual choices');
  await page.locator('#reference-search').fill('people holding hands');
  await page.waitForSelector('.reference-item[aria-label="people holding hands"]');
  await page.mouse.move(10,10);await page.locator('.reference-item[aria-label="people holding hands"]').hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  await page.locator('.reference-mixed-tones summary').click();
  const mixed='🧑🏻‍🤝‍🧑🏼';
  await page.locator('[data-variant="2"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),mixed);
  assert.equal(await page.locator('.reference-item[aria-label="people holding hands"] .reference-emoji-glyph').textContent(),mixed,'Mixed tone selection updates the tile');
  assert.equal(await page.locator('[data-variant="2"]').getAttribute('aria-pressed'),'true');
  await page.keyboard.press('Escape');
  await page.locator('.reference-item[aria-label="people holding hands"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),mixed,'The tile copies its selected mixed tone');
  await page.locator('#reference-search').fill('thumbs up');await page.waitForSelector('.reference-item[aria-label="thumbs up"]');
  await page.locator('#reference-search').fill('people holding hands');await page.waitForSelector('.reference-item[aria-label="people holding hands"]');
  assert.equal(await page.locator('.reference-item[aria-label="people holding hands"] .reference-emoji-glyph').textContent(),mixed,'Mixed tone survives filtering');
  await page.locator('[data-tone="3"]').click();
  assert.equal(await page.locator('.reference-item[aria-label="people holding hands"] .reference-emoji-glyph').textContent(),'🧑🏽‍🤝‍🧑🏽','Global tone resets mixed choices');
  await chooseReferenceTab(page,'entities');
  assert.ok((await page.locator('.reference-tabs>.active [data-tab-count]').textContent()).includes('2,125')||Number((await page.locator('.reference-tabs>.active [data-tab-count]').textContent()).replace(/\D/g,''))>2000);
  for(const [tab,minimum] of [['symbols',2300],['colors',149],['mime',2300],['ascii',128],['kaomoji',70]]){
   await chooseReferenceTab(page,tab);
   assert.ok(Number((await page.locator('.reference-tabs>.active [data-tab-count]').textContent()).replace(/\D/g,''))>=minimum,tab);
  }
  await page.mouse.move(10,10);await page.locator('.reference-item').first().hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  const kaomoji=await page.locator('.reference-popover-preview').evaluate(node=>{const r=node.getBoundingClientRect(),text=node.querySelector('span'),t=text.getBoundingClientRect();return {contained:t.left>=r.left&&t.right<=r.right&&t.top>=r.top&&t.bottom<=r.bottom,singleLine:node.scrollHeight<=node.clientHeight+1,nowrap:getComputedStyle(text).whiteSpace};});
  assert.ok(kaomoji.contained&&kaomoji.singleLine,JSON.stringify(kaomoji));assert.equal(kaomoji.nowrap,'pre');
  await page.waitForTimeout(200);await page.screenshot({path:'work/reference-ui/kaomoji-details.png'});
  await page.locator('[data-category]').nth(1).click();await page.waitForTimeout(600);
  assert.ok(await page.locator('.reference-popover').evaluate(node=>node.hidden));
  await chooseReferenceTab(page,'mime');
  await page.locator('#reference-search').fill('application/pdf');
  await page.waitForSelector('.reference-item[aria-label="application/pdf"]');
  await page.locator('.reference-item[aria-label="application/pdf"]').hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  assert.ok((await page.locator('.reference-popover').textContent()).includes('.pdf'));
  assert.ok((await page.locator('.reference-popover').textContent()).includes('PDF 文档'));
  await page.locator('#reference-search').fill('xlsx');
  await page.waitForSelector('.reference-item[aria-label="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]');
  await chooseReferenceTab(page,'symbols');
  await page.locator('.reference-item').first().focus();await page.keyboard.press('End');
  await page.waitForFunction(()=>Number(document.activeElement.dataset.entry)>2300);
  await page.keyboard.press('Home');await page.waitForFunction(()=>document.activeElement.dataset.entry==='0');
  await page.keyboard.press('Escape');
  await page.locator('[data-page="cheats"]').click();
  await page.waitForSelector('.reference-code-copy');
  for(const scroll of await page.locator('.reference-scroll').all())assert.equal(await scroll.evaluate(node=>getComputedStyle(node).paddingRight),'14px');
  assert.ok(await page.locator('#reference-results').evaluate(node=>{const scroll=node.parentElement;return scroll.getBoundingClientRect().right-node.getBoundingClientRect().right>=14;}));
  const cheatsLayout=await referenceLayout();assert.ok(cheatsLayout.sameRow&&cheatsLayout.searchRight,JSON.stringify(cheatsLayout));assert.equal(cheatsLayout.navWidth,symbolsLayout.navWidth);assert.equal(cheatsLayout.border,'0px');
  await page.screenshot({path:'work/reference-ui/git.png'});
  const snapshot=JSON.parse(await fs.readFile('src/renderer/reference-data/cheatsheets.json','utf8'));
  const git=snapshot.topics.find(topic=>topic.id==='git');
  for(const index of [65,30,95,12]){
   const section=git.sections[index],button=page.locator(`[data-category="${section.id}"]`);
   await button.scrollIntoViewIfNeeded();await button.click();
   const start=await page.locator('#reference-categories').evaluate(nav=>nav.scrollTop);
   for(let step=0;step<8;step++){
    await page.waitForTimeout(90);
    const selection=await button.evaluate(node=>{const nav=node.parentElement,r=node.getBoundingClientRect(),v=nav.getBoundingClientRect();return {current:node.getAttribute('aria-current'),visible:r.top>=v.top-1&&r.bottom<=v.bottom+1,top:nav.scrollTop};});
    assert.equal(selection.current,'location','Intermediate chapters must not replace the requested category');
    assert.ok(selection.visible&&Math.abs(selection.top-start)<=1,JSON.stringify(selection));
   }
  }
  // Scrolling the document manually releases the explicit selection and follows its actual heading.
  await page.locator('.reference-scroll').evaluate(scroll=>{scroll.dispatchEvent(new WheelEvent('wheel',{deltaY:-500,bubbles:true}));scroll.scrollTop=0;});
  await page.waitForFunction(id=>document.querySelector('#reference-categories [aria-current]')?.dataset.category===id,git.sections[0].id);
  for(const topic of snapshot.topics){
   await chooseReferenceTab(page,topic.id);
   assert.equal(await page.locator('[data-section]').count(),topic.sections.length,topic.id);
   assert.ok(topic.sections.reduce((n,s)=>n+s.items,0)>100);
   assert.ok(await page.locator('[data-body]:empty').count()>0,'Offscreen sections remain lazy');
   const example=topic.sections.find(section=>section.blocks.some(block=>block.type==='code'))||topic.sections.find(section=>section.markdown.includes('`'));
   await page.locator(`[data-category="${example.id}"]`).click();
   const body=page.locator(`[data-section="${example.id}"] [data-body]`);await body.locator('[class^="reference-syntax-"]').first().waitFor();
   const codeNode=body.locator('.reference-code-block pre>code,.reference-inline-code code').first();
   const font=await codeNode.evaluate(node=>({size:parseFloat(getComputedStyle(node).fontSize),family:getComputedStyle(node).fontFamily,block:!!node.closest('pre')}));
   assert.ok(font.size>=(font.block?14:13)&&font.family.includes('Cascadia Code'),topic.id+JSON.stringify(font));
   const copy=body.locator('.reference-code-copy,.reference-inline-code').first(),raw=await copy.getAttribute('data-code');await copy.click();
   assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),raw.replaceAll('\r\n','\n'),topic.id+' highlighting must not change copied source');
   await page.screenshot({path:`work/reference-ui/${topic.id}-highlight.png`});
   const last=topic.sections.at(-1);await page.locator(`[data-category="${last.id}"]`).click();
   await page.waitForFunction(id=>document.querySelector(`[data-section="${id}"] [data-body]`).childNodes.length>0,last.id);
   await page.waitForTimeout(600);
   const sidebarSelection=await page.locator(`[data-category="${last.id}"]`).evaluate(node=>{const r=node.getBoundingClientRect(),v=node.parentElement.getBoundingClientRect();return node.getAttribute('aria-current')==='location'&&r.top>=v.top-1&&r.bottom<=v.bottom+1;});assert.ok(sidebarSelection,'The selected sidebar category must stay visible: '+topic.id);
   assert.equal(await page.locator('[data-section]').count(),topic.sections.length,'Navigation preserves the entire topic');
   const targetVisible=await page.locator(`[data-section="${last.id}"]`).evaluate(node=>{const r=node.getBoundingClientRect(),v=document.querySelector('.reference-scroll').getBoundingClientRect();return r.top<v.bottom&&r.bottom>v.top;});assert.ok(targetVisible,'The selected section must remain visible after lazy rendering: '+topic.id);
   assert.ok(await page.locator('#reference-categories').evaluate(node=>node.scrollWidth<=node.clientWidth),'Category names must wrap without horizontal overflow');
  }
  assert.equal(await page.locator('.reference-popover').count(),1);
  await chooseReferenceTab(page,'latex');
  await page.locator('#reference-search').fill('希腊和希伯来字母');
  await page.waitForFunction(()=>document.querySelectorAll('[data-section]').length===1&&document.querySelector('[data-section] h3')?.textContent==='希腊和希伯来字母');
  await page.waitForSelector('.reference-formula');
  assert.ok(await page.locator('.katex').count()>20);
  const formula=page.getByRole('button',{name:'\\alpha',exact:true}).first();await formula.click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'\\alpha');
  await page.screenshot({path:'work/reference-ui/latex.png'});
  await chooseReferenceTab(page,'git');
  await page.locator('#reference-search').fill('git submodule');
  await page.waitForSelector('.reference-code-copy');
  const block=page.locator('.reference-code-copy').first(),code=await block.getAttribute('data-code');await block.click();
  assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),code.replaceAll('\r\n','\n'));
  await page.locator('#sidebar-toggle').click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('.sidebar').evaluate(node=>Math.round(node.getBoundingClientRect().width)),60);
  assert.equal(await page.locator('.sidebar-group-caption').first().evaluate(node=>getComputedStyle(node).opacity),'0');
  const geometry=await page.evaluate(()=>{const brand=document.querySelector('.brand').getBoundingClientRect(),title=document.querySelector('.title-tools').getBoundingClientRect(),main=document.querySelector('#main').getBoundingClientRect(),sidebar=document.querySelector('.sidebar').getBoundingClientRect(),pause=document.querySelector('#pause-nav .recording-indicator').getBoundingClientRect();return {continuous:title.top===brand.top&&title.bottom===main.top&&title.left===main.left,center:Math.abs(pause.x+pause.width/2-sidebar.x-sidebar.width/2)};});
  assert.ok(geometry.continuous);assert.ok(geometry.center<=1,JSON.stringify(geometry));
  await page.screenshot({path:'work/reference-ui/cheats.png'});
  await page.locator('[data-page="symbols"]').click();
  await page.waitForSelector('.reference-item');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
  await page.evaluate(()=>{document.documentElement.dataset.theme='dark';window.fixture.appearance({font:'system',scale:150,density:'comfortable'});});
  await page.setViewportSize({width:900,height:700});
  await page.waitForTimeout(200);
  await page.locator('[data-category="Flags"]').click();
  await page.waitForFunction(()=>document.querySelector('#reference-categories [aria-current]')?.dataset.category==='Flags');
  assert.ok(await page.locator('.reference-item').count()<160);
  await page.locator('.reference-item').last().hover();await page.waitForSelector('.reference-popover:not([hidden])');
  const visible=await page.locator('.reference-popover').evaluate(node=>{const r=node.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;});assert.ok(visible);
  await page.screenshot({path:'work/reference-ui/dark-large.png'});
  await page.locator('#sidebar-toggle').click();await page.waitForTimeout(300);
  for(const pageName of ['symbols','cheats']){
   await page.setViewportSize({width:640,height:700});
   await page.locator(`[data-page="${pageName}"]`).click();
   await page.evaluate(()=>window.fixture.appearance({font:'system',scale:150,density:'comfortable'}));
   await page.waitForSelector('.reference-tabs');await page.waitForTimeout(250);
   const geometry=await page.locator('.reference-primary-controls').evaluate(row=>{const tabs=row.querySelector('.reference-tabs'),search=row.querySelector('.reference-search'),r=row.getBoundingClientRect(),s=search.getBoundingClientRect();return {fits:row.scrollWidth<=row.clientWidth+1&&tabs.scrollWidth<=tabs.clientWidth+1,aligned:Math.abs(tabs.getBoundingClientRect().top+tabs.clientHeight/2-s.top-s.height/2)<1,inside:s.right<=r.right+1};});
   assert.ok(geometry.fits&&geometry.aligned&&geometry.inside,JSON.stringify(geometry));
   assert.ok(await page.locator('.reference-tabs>[data-tab][hidden]').count()>0,'Narrow large text must collapse excess segments: '+pageName);
   await page.locator('#reference-overflow-trigger').click();
   const menu=page.locator('.select-popup');await menu.waitFor();
   await menu.locator('[role=option]').last().click();await page.waitForTimeout(200);
   await page.screenshot({path:`work/reference-ui/${pageName}-compact.png`});
   assert.equal(await page.locator('.reference-tabs>[data-tab].active:not([hidden])').count(),1,'A dropdown selection must be promoted to a visible segment');
   assert.ok(await page.locator('.reference-nav').evaluate(node=>node.scrollWidth<=node.clientWidth));
   await page.setViewportSize({width:1600,height:820});await page.waitForTimeout(250);
   assert.equal(await page.locator('.reference-tabs>[data-tab][hidden]').count(),0,'Widening restores all segments');
   await page.setViewportSize({width:900,height:700});
  }
  await page.locator('[data-page="history"]').click();
  assert.equal(await page.locator('.reference-popover').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Reference catalogs, search, copy, topic navigation and One-sized sidebar passed.');
 }finally{await context?.close();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
