const {chromium}=require('@playwright/test');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const {setup}=require('./renderer-fixture.cjs');

(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const errors=[];let context;
 try{
  context=await browser.newContext({viewport:{width:1280,height:820}});
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:'https://clipper.test'});
  await context.addInitScript(setup);
  await context.route('https://clipper.test/**',async route=>{
   const name=new URL(route.request().url()).pathname.slice(1);
   if(!/^(?:[\w.-]+|(?:katex-fonts|emoji-atlas)\/[\w.-]+)$/.test(name))return route.abort();
   try{await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.woff2')?'font/woff2':'application/javascript'});}catch{return route.abort();}
  });
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  await page.goto('https://clipper.test/index.html');await page.waitForSelector('.clip-row');
  assert.equal(await page.locator('.sidebar').evaluate(node=>Math.round(node.getBoundingClientRect().width)),208);
  assert.equal(await page.locator('.sidebar-group').count(),4);
  assert.equal(await page.locator('#main').evaluate(node=>getComputedStyle(node).borderLeftWidth),'1px');
  await page.locator('[data-page="symbols"]').click();
  await page.waitForSelector('.reference-item');
  await page.waitForSelector('canvas.reference-emoji-image.ready');
  await fs.mkdir('work/reference-ui',{recursive:true});
  await page.screenshot({path:'work/reference-ui/emoji.png'});
  const number=async()=>Number((await page.locator('#reference-count').textContent()).replace(/\D/g,''));
  const emojiTotal=await number();assert.ok(emojiTotal>1900&&emojiTotal<2100);
  assert.equal(await page.locator('.reference-tabs.segment-ready').count(),1);
  assert.equal(await page.locator('.reference-heading p').count(),0);
  assert.ok(await page.locator('.reference-item').count()<220,'Only nearby rows should be mounted');
  assert.equal(await page.locator('.reference-item strong,.reference-item small').count(),0);
  await page.locator('.reference-item').first().hover();await page.waitForSelector('.reference-popover:not([hidden])');
  const fullHeight=await page.locator('#reference-results').evaluate(node=>node.offsetHeight);
  await page.locator('[data-category="Food & Drink"]').click();
  await page.waitForFunction(()=>document.querySelector('.reference-scroll').scrollTop>1200);
  await page.waitForFunction(()=>document.querySelector('#reference-categories [aria-current]')?.dataset.category==='Food & Drink');
  await page.waitForTimeout(450);
  assert.ok(await page.locator('.reference-popover').evaluate(node=>node.hidden),'Category scrolling must not reopen stale hover details');
  assert.equal(await number(),emojiTotal,'Category navigation must not filter the list');
  assert.equal(await page.locator('#reference-results').evaluate(node=>node.offsetHeight),fullHeight);
  assert.ok(await page.locator('.reference-item').count()<220);
  await page.locator('[data-category="Smileys & Emotion"]').click();
  await page.waitForFunction(()=>document.querySelector('.reference-scroll').scrollTop===0);
  await page.locator('#reference-search').fill('grinning face');
  assert.ok(await page.locator('.reference-item').count()>0);
  await page.locator('.reference-item.reference-main').first().click();
  assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).length>0);
  await page.locator('#reference-search').fill('thumbs up');
  await page.waitForFunction(()=>document.querySelector('.reference-item[aria-label="thumbs up"]'));
  await page.locator('[data-tone="3"]').click();
  await page.locator('.reference-item[aria-label="thumbs up"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'👍🏽');
  await page.mouse.move(10,10);await page.locator('.reference-item[aria-label="thumbs up"]').hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  assert.ok((await page.locator('.reference-popover').textContent()).includes('U+1F3FD'));
  assert.equal(await page.locator('[data-detail-tone]').count(),6);
  await page.locator('[data-detail-tone="5"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'👍🏿');
  await page.screenshot({path:'work/reference-ui/skin-details.png'});
  await page.keyboard.press('Escape');await page.waitForSelector('.reference-popover[hidden]',{state:'attached'});
  await page.locator('[data-tab="entities"]').click();
  assert.ok((await page.locator('#reference-count').textContent()).includes('2,125')||Number((await page.locator('#reference-count').textContent()).replace(/\D/g,''))>2000);
  for(const [tab,minimum] of [['symbols',2300],['colors',149],['mime',2300],['ascii',128],['kaomoji',70]]){
   await page.locator(`[data-tab="${tab}"]`).click();
   assert.ok(Number((await page.locator('#reference-count').textContent()).replace(/\D/g,''))>=minimum,tab);
  }
  await page.mouse.move(10,10);await page.locator('.reference-item').first().hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  const kaomoji=await page.locator('.reference-popover-preview').evaluate(node=>{const r=node.getBoundingClientRect(),text=node.querySelector('span'),t=text.getBoundingClientRect();return {contained:t.left>=r.left&&t.right<=r.right&&t.top>=r.top&&t.bottom<=r.bottom,singleLine:node.scrollHeight<=node.clientHeight+1,nowrap:getComputedStyle(text).whiteSpace};});
  assert.ok(kaomoji.contained&&kaomoji.singleLine,JSON.stringify(kaomoji));assert.equal(kaomoji.nowrap,'pre');
  await page.waitForTimeout(200);await page.screenshot({path:'work/reference-ui/kaomoji-details.png'});
  await page.locator('[data-category]').nth(1).click();await page.waitForTimeout(600);
  assert.ok(await page.locator('.reference-popover').evaluate(node=>node.hidden));
  await page.locator('[data-tab="mime"]').click();
  await page.locator('#reference-search').fill('application/pdf');
  await page.waitForSelector('.reference-item[aria-label="application/pdf"]');
  await page.locator('.reference-item[aria-label="application/pdf"]').hover();
  await page.waitForSelector('.reference-popover:not([hidden])');
  assert.ok((await page.locator('.reference-popover').textContent()).includes('.pdf'));
  assert.ok((await page.locator('.reference-popover').textContent()).includes('PDF 文档'));
  await page.locator('#reference-search').fill('xlsx');
  await page.waitForSelector('.reference-item[aria-label="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]');
  await page.locator('[data-tab="symbols"]').click();
  await page.locator('.reference-item').first().focus();await page.keyboard.press('End');
  await page.waitForFunction(()=>Number(document.activeElement.dataset.entry)>2300);
  await page.keyboard.press('Home');await page.waitForFunction(()=>document.activeElement.dataset.entry==='0');
  await page.keyboard.press('Escape');
  await page.locator('[data-page="cheats"]').click();
  await page.waitForSelector('.reference-code-copy');
  await page.screenshot({path:'work/reference-ui/git.png'});
  const snapshot=JSON.parse(await fs.readFile('src/renderer/reference-data/cheatsheets.json','utf8'));
  for(const topic of snapshot.topics){
   await page.locator(`[data-tab="${topic.id}"]`).click();
   assert.equal(await page.locator('[data-section]').count(),topic.sections.length,topic.id);
   assert.ok(topic.sections.reduce((n,s)=>n+s.items,0)>100);
   assert.ok(await page.locator('[data-body]:empty').count()>0,'Offscreen sections remain lazy');
   const last=topic.sections.at(-1);await page.locator(`[data-category="${last.id}"]`).click();
   await page.waitForFunction(id=>document.querySelector(`[data-section="${id}"] [data-body]`).childNodes.length>0,last.id);
   await page.waitForTimeout(600);
   assert.equal(await page.locator('[data-section]').count(),topic.sections.length,'Navigation preserves the entire topic');
   const targetVisible=await page.locator(`[data-section="${last.id}"]`).evaluate(node=>{const r=node.getBoundingClientRect(),v=document.querySelector('.reference-scroll').getBoundingClientRect();return r.top<v.bottom&&r.bottom>v.top;});assert.ok(targetVisible,'The selected section must remain visible after lazy rendering: '+topic.id);
   assert.ok(await page.locator('#reference-categories').evaluate(node=>node.scrollWidth<=node.clientWidth),'Category names must wrap without horizontal overflow');
  }
  assert.equal(await page.locator('.reference-popover').count(),1);
  await page.locator('[data-tab="latex"]').click();
  await page.locator('#reference-search').fill('希腊和希伯来字母');
  await page.waitForFunction(()=>document.querySelectorAll('[data-section]').length===1&&document.querySelector('[data-section] h3')?.textContent==='希腊和希伯来字母');
  await page.waitForSelector('.reference-formula');
  assert.ok(await page.locator('.katex').count()>20);
  const formula=page.getByRole('button',{name:'\\alpha',exact:true}).first();await formula.click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'\\alpha');
  await page.screenshot({path:'work/reference-ui/latex.png'});
  await page.locator('[data-tab="git"]').click();
  await page.locator('#reference-search').fill('git submodule');
  await page.waitForSelector('.reference-code-copy');
  const block=page.locator('.reference-code-copy').first(),code=await block.getAttribute('data-code');await block.click();
  assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),code.replaceAll('\r\n','\n'));
  await page.locator('#sidebar-toggle').click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('.sidebar').evaluate(node=>Math.round(node.getBoundingClientRect().width)),56);
  assert.equal(await page.locator('.sidebar-group-caption').first().evaluate(node=>getComputedStyle(node).opacity),'0');
  const geometry=await page.evaluate(()=>{const brand=document.querySelector('.brand').getBoundingClientRect(),title=document.querySelector('.title-tools').getBoundingClientRect(),main=document.querySelector('#main').getBoundingClientRect(),sidebar=document.querySelector('.sidebar').getBoundingClientRect(),pause=document.querySelector('#pause-nav .recording-indicator').getBoundingClientRect();return {continuous:title.top===brand.top&&title.bottom===main.top&&title.left===main.left,center:Math.abs(pause.x+pause.width/2-sidebar.x-sidebar.width/2)};});
  assert.ok(geometry.continuous);assert.ok(geometry.center<=1,JSON.stringify(geometry));
  await page.screenshot({path:'work/reference-ui/cheats.png'});
  await page.locator('[data-page="symbols"]').click();
  await page.waitForSelector('.reference-item');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
  await page.evaluate(()=>{document.documentElement.dataset.theme='dark';window.fixture.appearance({font:'system',scale:150,density:'comfortable'});});
  await page.setViewportSize({width:900,height:700});
  await page.waitForTimeout(200);
  await page.locator('[data-category="Flags"]').click();
  await page.waitForFunction(()=>document.querySelector('#reference-categories [aria-current]')?.dataset.category==='Flags');
  assert.ok(await page.locator('.reference-item').count()<160);
  await page.locator('.reference-item').last().hover();await page.waitForSelector('.reference-popover:not([hidden])');
  const visible=await page.locator('.reference-popover').evaluate(node=>{const r=node.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;});assert.ok(visible);
  await page.screenshot({path:'work/reference-ui/dark-large.png'});
  await page.locator('[data-page="history"]').click();
  assert.equal(await page.locator('.reference-popover').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Reference catalogs, search, copy, topic navigation and One-sized sidebar passed.');
 }finally{await context?.close();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
