function setup(language='zh-CN'){
 const listeners=[],changes=[];let appearance={font:'system',scale:100,density:'comfortable'};
 const base={id:'text',hash:'fixture',kind:'text',title:'项目说明 · 界面文字与空间',preview:'这是一份用于检查文字大小的说明。',source:'LayoutFixture.exe',createdAt:Date.now(),updatedAt:Date.now(),favorite:true,pinned:false,tags:['设计','窗口验证'],bytes:1024};
 const clips=[base,{...base,id:'image',kind:'image',title:'图片预览'}, {...base,id:'files',kind:'files',title:'文件夹及长路径'}];
 const fixtureCanvas=document.createElement('canvas');fixtureCanvas.width=640;fixtureCanvas.height=360;const drawing=fixtureCanvas.getContext('2d');drawing.fillStyle='#e7eee7';drawing.fillRect(0,0,640,360);drawing.fillStyle='#526d55';drawing.fillRect(32,32,240,296);drawing.fillStyle='#b48c5a';drawing.fillRect(296,32,312,144);drawing.fillStyle='#273d50';drawing.fillRect(296,200,312,128);drawing.fillStyle='#ffffff';drawing.font='24px sans-serif';drawing.fillText('640 x 360',64,192);const png=fixtureCanvas.toDataURL('image/png').split(',')[1];
 const payload=id=>id==='image'?{png}:id==='files'?{files:['D:\\项目资料\\设计与开发计划\\非常长的文件名称用于检查窄窗口换行.txt']}:{text:('中文说明 English 0123456789\n').repeat(20)};
 const state={clips,snippets:[{...base,id:'reply',text:'您好，感谢联系。',payload:{text:'您好，感谢联系。'}}],queue:['text'],shelf:[],categories:[],settings:{theme:'system',view:'list',paused:false,maxItems:1000,retentionDays:30,excludedApps:[],shortcut:'Control+Shift+V',nextShortcut:'Control+Alt+N',launchAtLogin:false},desktop:{cardDirection:'grid'},stack:{options:{kind:'all',source:'',contains:'',mode:'whole',trim:true},running:false,reason:''},dark:false,native:true,status:'',bytes:1024,hotkeyError:''};
 window.fixture={appearance:value=>{appearance=value;listeners.forEach(fn=>fn({value,warning:''}));},state,value:()=>appearance,refresh:()=>changes.forEach(fn=>fn()),copies:0};
 window.clipLanguage={current:language,state:async()=>({choice:language,current:language,next:language,restartRequired:false,warning:false})};
 window.clipAppearance={state:async()=>({value:appearance,warning:''}),onChange:fn=>{listeners.push(fn);return()=>{};}};
 const projected=item=>{const {payload:p,...meta}=item,b=s=>s.length*3/4-(s.endsWith('==')?2:s.endsWith('=')?1:0);return {...meta,revision:meta.revision||1,payload:{...(p.text!==undefined?{text:p.text}:{}),...(p.files?{files:p.files}:{}),...(p.attachments?{attachments:p.attachments.map(a=>({name:a.name,bytes:b(a.data),...(a.directory?{directory:true}:{})}))}:{}),png:!!p.png,html:!!p.html,rtf:!!p.rtf,...(p.formats?{formats:p.formats.map(f=>({name:f.name,bytes:b(f.data)}))}:{}),...(p.omittedFormats?{omittedFormats:p.omittedFormats}:{})},...(p.png?{imageURL:'data:image/png;base64,'+p.png}:{})};};
 window.clip=new Proxy({preview:async id=>projected(await window.clip.detail(id)),snippetPreview:async id=>projected(await window.clip.snippetDetail(id)),releasePreview:async()=>{},onUpdate:()=>()=>{},updateState:async()=>({phase:"idle",current:"0.50.0",automatic:false,installed:false,downloaded:0,error:"",checkedAt:0}),desktopState:async()=>({options:{displayId:null,dwellMs:450,shelfTop:false,shelfOnTop:true,shelfPosition:"top-right",shelfShortcut:"Control+Shift+D",cardDirection:"grid"},displays:[]}),efficiencyState:async()=>({options:{historyEnabled:false,repliesShortcut:"Control+Shift+R",bindings:[]},history:[]}),dataState:async()=>({directory:'D:\\Fixture',defaultDirectory:'D:\\Fixture',previousDirectory:'',databaseBytes:1024,backup:{enabled:false,directory:'',intervalHours:24,keep:10,encrypted:false,hasPassword:false,lastSuccess:0,lastAttempt:0,nextAt:0,lastError:''},entries:[]}),vaultState:async()=>({encrypted:false,unlocked:true,hello:false,helloAvailable:false,idleMinutes:15,plaintextDirectory:''}),checkpoints:async()=>[],state:async()=>state,detail:async id=>({...clips.find(c=>c.id===id),payload:payload(id)}),snippetDetail:async()=>state.snippets[0],replyIntent:async()=>null,integrations:async()=>({pending:null}),configureAppearance:async value=>{window.fixture.appearance(value);return {value,warning:''};},onChange:fn=>{changes.push(fn);return()=>{};},onNotice:()=>()=>{},copy:async()=>{window.fixture.copies++;}}, {get:(obj,key)=>key in obj?obj[key]:async()=>null});
 window.clipTray={state:async()=>({items:clips.map(c=>({...c,token:c.id,draggable:false})),categories:[],total:clips.length,counts:{all:3,text:1,image:1,files:1,link:0,code:0},dark:false,canPaste:true}),preview:async id=>({...clips.find(c=>c.id===id),text:payload(id).text||'',image:id==='image'?'data:image/png;base64,'+png:'',files:id==='files'?[{name:'项目资料/设计与开发计划/长路径文件.txt',saved:true,directory:false}]:[],truncated:false}),onChange:fn=>{setTimeout(fn,0);return()=>{};},onNotice:()=>()=>{},use:async()=>{},hide:async()=>{},main:async()=>{}};
 window.clip.programVersions=async()=>[];window.clip.cancelProgramRollback=async()=>{};
 window.clipShelf={state:async()=>({items:clips,dark:false,onTop:true}),onChange:()=>()=>{},onTransition:()=>()=>{},onNotice:()=>()=>{}};
 window.unlock={state:async()=>({ready:true,hello:true,helloAvailable:true})};
 window.recovery={dataState:async()=>({directory:'D:\\Fixture',defaultDirectory:'D:\\Fixture',previousDirectory:'',databaseBytes:1024,backup:{enabled:false,directory:'',intervalHours:24,keep:10,encrypted:false,hasPassword:false,lastSuccess:0,lastAttempt:0,nextAt:0,lastError:''},entries:[]}),vaultState:async()=>({encrypted:false,unlocked:true,hello:false,helloAvailable:false,idleMinutes:15,plaintextDirectory:''}),checkpoints:async()=>[],state:async()=>({error:'无法访问资料目录，请选择可用资料。',directory:'D:\\测试资料'})};
 window.capture={data:async()=>({image:'data:image/png;base64,'+png}),complete:async()=>{}};
 window.clipRecorder={state:async()=>({phase:'idle',dark:false,bytes:0,seconds:0,message:''}),sources:async()=>[{id:'screen:1',type:'screen',name:'显示器 1',thumbnail:'data:image/png;base64,'+png}],onChange:()=>()=>{},onStop:()=>()=>{}};
 window.clipImage={state:async()=>({url:'data:image/png;base64,'+png,dark:false}),dirty:async()=>{},onChange:()=>()=>{}};
}
async function measure(page,selectors){return page.evaluate(selectors=>{const result={body:document.body.scrollWidth<=innerWidth,root:document.documentElement.scrollWidth<=innerWidth};for(const selector of selectors){const source=document.querySelector(selector),el=source?.classList.contains("select-backing")?source.parentElement.querySelector(".custom-select"):source;if(!el){result[selector]={missing:true};continue;}const r=el.getBoundingClientRect();const center=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);result[selector]={x:r.x,y:r.y,w:r.width,h:r.height,visible:r.x>=-1&&r.y>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,reachable:!!center&&(center===el||el.contains(center)),overflow:el.scrollWidth>el.clientWidth+1};}return result;},selectors);}

module.exports={setup,measure};
