const {_electron}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
(async()=>{await fs.mkdir('work/scrollbar-0281',{recursive:true});const results=[],errors=[];for(const language of ['zh-CN','en']){const env={...process.env,CLIPPER_VERIFY_LANGUAGE:language};delete env.ELECTRON_RUN_AS_NODE;const app=await _electron.launch({executablePath:require('electron'),args:['tests/scrollbar-0281-host.cjs'],env});try{const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.tray-row');
 for(const view of ['tray','index','shelf','image-editor','recorder','unlock','recovery']){
  if(view==='image-editor'||view==='recorder')continue; // Their renderers require their own business fixtures; CSS is checked separately below.
  await page.goto('file:///'+path.resolve('dist/renderer/'+view+'.html').replaceAll('\\','/'));await page.waitForTimeout(120);
  for(const dark of [false,true]){await page.evaluate(dark=>{document.documentElement.dataset.theme=dark?'dark':'light';},dark);for(const scale of [100,150]){await page.evaluate(scale=>fixture.appearance({...fixture.value(),scale}),scale);const scrollers=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('*')].filter(e=>/auto|scroll/.test(getComputedStyle(e).overflowY));return nodes.map(e=>{const s=getComputedStyle(e),bar=getComputedStyle(e,'::-webkit-scrollbar'),button=getComputedStyle(e,'::-webkit-scrollbar-button'),thumb=getComputedStyle(e,'::-webkit-scrollbar-thumb'),track=getComputedStyle(e,'::-webkit-scrollbar-track');return {id:e.id||e.className,width:s.scrollbarWidth,barWidth:bar.width,arrows:button.display,radius:thumb.borderRadius,track:track.backgroundColor};});});for(const s of scrollers){assert.equal(s.width,'auto',JSON.stringify({view,s}));assert.equal(s.barWidth,'8px');assert.equal(s.arrows,'none');assert.equal(s.radius,'999px');assert.equal(s.track,'rgba(0, 0, 0, 0)');}assert(scrollers.length>0);results.push({language,view,dark,scale,scrollers:scrollers.length});
   if(view==='tray'){assert.equal(await page.locator('#hint,main>footer').count(),0);const before=await page.locator('#items').evaluate(e=>e.scrollTop);await page.locator('.tray-row').first().focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');assert.notEqual(await page.locator('.tray-row[aria-selected=true]').getAttribute('data-token'),'text');await page.locator('#items').evaluate(e=>e.scrollTop=e.scrollHeight);assert(await page.locator('#items').evaluate(e=>e.scrollTop>0));await page.locator('#items').evaluate(e=>e.scrollTop=0);await page.locator('#search').focus();await page.mouse.move(2,2);if(language==='zh-CN'&&scale===100){const bytes=await app.evaluate(async()=>(await global.fixtureWindow.webContents.capturePage()).toPNG().toString('base64'));await fs.writeFile('work/scrollbar-0281/recent-'+(dark?'dark':'light')+'.png',Buffer.from(bytes,'base64'));}}
  }}
 }
 assert.equal(await app.evaluate(()=>global.fixtureWindow.isVisible()),false);
 // All regular auxiliary documents load the same global rule sheet, including canvas/media windows.
 for(const view of ['image-editor','recorder','unlock','recovery','shelf','tray','index'])assert((await fs.readFile('dist/renderer/'+view+'.html','utf8')).includes('redesign-028.css'));
 }finally{await app.close();}}
 assert.deepEqual(errors,[]);const report={passed:true,cases:results.length,errors,nativeElectron:true,windowShown:false,arrowsRemoved:true,thinRoundedThumb:true,recentFooterRemoved:true,scrollingPreserved:true,scope:'Actual hidden Electron renders with production CSS and isolated business fixtures. No system clipboard or desktop input.',results};await fs.writeFile('work/scrollbar-0281/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,results:undefined}));
})().catch(e=>{console.error(e);process.exitCode=1;});
