const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupText}=require('./language-text-fixture.cjs'),{setupData}=require('./language-data-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
(async()=>{await fs.mkdir('work/search-029',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];try{
 for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){
  const context=await browser.newContext({viewport:{width:1240,height:800}});for(const fn of [setup,setupText,setupData,extra])await context.addInitScript(fn,language);await context.addInitScript(theme=>{fixture.state.dark=theme==='dark';const base=clipper;window.clipper=new Proxy({search:async value=>{fixture.calls.push(['search',value]);return fixture.state.clips.filter(c=>(c.title+' '+c.source).toLowerCase().includes(value.toLowerCase())).map(c=>c.id);}},{get:(o,k)=>k in o?o[k]:base[k]});},theme);
  await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});});
  const page=await context.newPage();await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');
  for(const scale of [100,150])for(const focused of [false,true]){await page.evaluate(scale=>fixture.appearance({...fixture.value(),scale}),scale);if(focused)await page.locator('#search').focus();else await page.locator('h1').click();
   const value=await page.locator('.filter-field').evaluate(field=>{const input=field.querySelector('input'),a=getComputedStyle(field),b=getComputedStyle(input),r=input.getBoundingClientRect(),f=field.getBoundingClientRect();return {singleBorder:a.borderTopWidth==='1px',transparentInput:b.backgroundColor==='rgba(0, 0, 0, 0)',unframedInput:b.borderTopWidth==='0px',noInnerRadius:b.borderTopLeftRadius==='0px',inside:r.x>f.x&&r.right<f.right,icon:!!field.querySelector('.icon'),noOverflow:field.scrollWidth<=field.clientWidth+1};});assert(Object.values(value).every(Boolean),JSON.stringify({language,theme,scale,focused,value}));results.push({language,theme,scale,focused,...value});
  }
  await page.locator('#search').fill('图片预览');await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='search'&&c[1]==='图片预览'));await page.waitForFunction(()=>document.querySelectorAll('.clip-row').length===1);assert.equal(await page.locator('.search-clear').isVisible(),true);await page.locator('.search-clear').click();assert.equal(await page.locator('#search').inputValue(),'');assert.equal(await page.evaluate(()=>document.activeElement.id),'search');await page.waitForFunction(()=>document.querySelectorAll('.clip-row').length===4);assert.equal(await page.locator('.search-clear').isVisible(),false);
  await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:100}));await page.screenshot({path:`work/search-029/${language}-${theme}.png`});await context.close();
 }
 await fs.writeFile('work/search-029/results.json',JSON.stringify({passed:true,cases:results.length,source:'One disk.css filter-field and maintenance-view.ts markup; built Clipper controller with isolated IPC',results},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
