const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function input(driver,{points,keys,restore}){return driver.evaluate(async({app,screen},{points,keys,restore})=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)'),pause=ms=>new Promise(r=>setTimeout(r,ms));const mouse=(p,flags)=>{p=screen.dipToScreenPoint({x:Math.round(p.x),y:Math.round(p.y)});const b=Buffer.alloc(40);b.writeInt32LE(Math.round((p.x-metric(76))*65535/(metric(78)-1)),8);b.writeInt32LE(Math.round((p.y-metric(77))*65535/(metric(79)-1)),12);b.writeUInt32LE(flags|0xc001,20);assertSend(b);};const key=(code,up)=>{const b=Buffer.alloc(40);b.writeUInt32LE(1,0);b.writeUInt16LE(code,8);b.writeUInt32LE(up?2:0,12);assertSend(b);};function assertSend(b){if(send(1,b,40)!==1)throw Error('Native input rejected');}
if(points){try{mouse(points[0],0);await pause(100);mouse(points[0],2);await pause(130);for(let i=1;i<=20;i++){mouse({x:points[0].x+(points.at(-1).x-points[0].x)*i/20,y:points[0].y+(points.at(-1).y-points[0].y)*i/20},0);await pause(20);}}finally{mouse(points.at(-1),4);}}
if(keys){try{for(const k of keys)key(k,false);await pause(140);}finally{for(const k of [...keys].reverse())key(k,true);}}
if(restore){for(const k of [0x11,0x12,0x58,0x1b])key(k,true);mouse(restore,4);}return true;},{points,keys,restore});}
async function run(){const output=path.resolve('work/selection-auto');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-')),env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:profile,CLIPPER_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;let app,cursor;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});
 try{const source=await helper.firstWindow();await source.waitForSelector('#target');cursor=await helper.evaluate(({screen})=>screen.getCursorScreenPoint());app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');await app.evaluate(({app})=>app.on('browser-window-created',(_event,w)=>w.on('show',()=>{if(w.webContents.getURL().endsWith('/selection.html'))w.setAlwaysOnTop(true,'screen-saver');})));const errors=[];app.on('window',p=>p.on('pageerror',e=>errors.push(e.message)));
 await helper.evaluate(({clipboard})=>{clipboard.writeText('Native selection clipboard sentinel');global.helperWindow.setBounds({x:50,y:100,width:760,height:440});});await source.evaluate(()=>{document.body.innerHTML='<h2>真实鼠标选区验收</h2><p id="words" style="font:24px Segoe UI;white-space:nowrap;margin:55px 25px 20px;width:max-content">WINDOWS selected 中文文字</p><p style="margin:25px">自动菜单保持原窗口焦点</p>';});
 const visible=()=>app.evaluate(({BrowserWindow})=>!!BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/selection.html'))?.isVisible());let menu;
 const select=async()=>{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.hide()));await helper.evaluate(async()=>{await global.focusTarget();global.helperWindow.setAlwaysOnTop(false)});const bounds=await helper.evaluate(()=>global.helperWindow.getContentBounds()),box=await source.locator('#words').boundingBox();await input(helper,{points:[{x:bounds.x+box.x,y:bounds.y+box.y+box.height/2},{x:bounds.x+box.x+box.width+15,y:bounds.y+box.y+box.height/2}]});assert.equal((await source.evaluate(()=>getSelection().toString())).trim(),'WINDOWS selected 中文文字');};
 const toolbar=async()=>{await expect.poll(visible).toBe(true);menu=(await app.windows()).find(p=>p.url().includes('/selection.html'));await expect(menu.locator('#text')).toContainText('WINDOWS selected 中文文字');};
 console.log('Native gesture: default off; enabled popup does not focus or alter clipboard');await select();await wait(700);assert.equal(await visible(),false);await page.evaluate(async()=>window.clipper.configureSelection({... (await window.clipper.selectionState()).options,enabled:true}));await select();await toolbar();assert.equal(await helper.evaluate(()=>global.helperWindow.isFocused()),true);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/selection.html')).isFocused()),false);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),'Native selection clipboard sentinel');const selected=await source.evaluate(()=>getSelection().toString());
 await menu.screenshot({path:path.join(output,'selection-auto.png')});
 console.log('Native inactive toolbar click saves without clipboard write');const b=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/selection.html')).getContentBounds()),button=await menu.locator('[data-action=save]').boundingBox();await input(helper,{points:[{x:b.x+button.x+button.width/2,y:b.y+button.y+button.height/2}]});await expect.poll(async()=>(await page.evaluate(()=>window.clipper.state())).clips.some(c=>c.preview===selected)).toBe(true);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),'Native selection clipboard sentinel');await expect.poll(visible).toBe(false);await expect(menu.locator('#text')).toHaveText('');
 console.log('Native Escape and typed input dismiss; automatic menu respects pause');await select();await toolbar();await input(helper,{keys:[0x1b]});await expect.poll(visible).toBe(false);await select();await toolbar();await input(helper,{keys:[0x41]});await expect.poll(visible).toBe(false);await page.evaluate(async()=>{const s=await window.clipper.state();await window.clipper.settings({...s.settings,paused:true});});await select();await wait(700);assert.equal(await visible(),false);
 console.log('Actual Ctrl+Alt+X remains available while automatic capture is paused');await input(helper,{keys:[0x11,0x12,0x58]});await toolbar();await expect(menu.locator('[data-action=copy]')).toBeFocused();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/selection.html')).isFocused()),true);await input(app,{keys:[0x1b]});await expect.poll(visible).toBe(false);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,actualNativeGesture:true,autoDefaultOff:true,noFocusTheft:true,noClipboardWrite:true,inactiveToolbarClick:true,escapeAndTypingDismiss:true,pauseStopsAuto:true,actualGlobalShortcut:true,previewCleared:true,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(({clipboard})=>global.restoreClipboard());if(cursor)await input(helper,{restore:cursor}).catch(()=>{});await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
