const {spawn,spawnSync}=require('node:child_process'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),readline=require('node:readline');
const {_electron:electron}=require('@playwright/test');
const {SelectionReader}=require('../work/test-exports.cjs');
async function run(){const output=path.resolve('work/selection-native');await fs.mkdir(output,{recursive:true});const framework=path.join(process.env.WINDIR,'Microsoft.NET/Framework64/v4.0.30319'),fixtureExe=path.join(output,'SelectionFixture.exe');const built=spawnSync(path.join(framework,'csc.exe'),['/nologo','/target:exe','/platform:x64','/out:'+fixtureExe,'/reference:System.Windows.Forms.dll','/reference:System.Drawing.dll','/reference:'+path.join(framework,'System.Web.Extensions.dll'),path.resolve('tests/SelectionFixture.cs')],{windowsHide:true,encoding:'utf8'});assert.equal(built.status,0,built.stdout+built.stderr);
 const env={...process.env,CLIPPER_HELPER_PROFILE:await fs.mkdtemp(path.join(output,'helper-'))};delete env.ELECTRON_RUN_AS_NODE;const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let fixture,cursor;
 const host=process.env.CLIPPER_PACKAGED_EXE?path.join(path.dirname(process.env.CLIPPER_PACKAGED_EXE),'resources/app.asar.unpacked/dist/native/SelectionHost.exe'):path.resolve('dist/native/SelectionHost.exe'),reader=new SelectionReader(host);
 try{await helper.firstWindow();cursor=await helper.evaluate(({screen})=>screen.getCursorScreenPoint());await helper.evaluate(({clipboard})=>clipboard.writeText('Native controls unchanged clipboard'));fixture=spawn(fixtureExe,[],{windowsHide:true,stdio:'pipe'});const lines=readline.createInterface({input:fixture.stdout}),queue=[],pending=[];lines.on('line',line=>{const value=JSON.parse(line),next=pending.shift();if(next)next(value);else queue.push(value)});const next=()=>Promise.race([queue.length?Promise.resolve(queue.shift()):new Promise(r=>pending.push(r)),new Promise((_,reject)=>{const t=setTimeout(()=>reject(Error('Native fixture timed out')),10000);t.unref()})]);assert.equal((await next()).ready,true);await helper.evaluate(async({app},pid)=>{await global.focusTarget();global.helperWindow.setAlwaysOnTop(false);const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json'));if(!req('koffi').load('user32.dll').func('bool __stdcall AllowSetForegroundWindow(uint32)')(pid))throw Error('Cannot grant native test fixture foreground transition');},fixture.pid);
  const read=async mode=>{fixture.stdin.write(mode+'\n');const request=await next();await new Promise(r=>setTimeout(r,200));const result=await reader.read({...request,id:mode});if(result.status==='stale'){const native=await helper.evaluate(({app})=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),get=u.func('uintptr_t __stdcall GetForegroundWindow()'),pid=u.func('uint32 __stdcall GetWindowThreadProcessId(uintptr_t,_Out_ uint32*)'),cls=u.func('int __stdcall GetClassNameW(uintptr_t,void*,int)'),h=get(),id=[0],b=Buffer.alloc(512);pid(h,id);const length=cls(h,b,256);return {hwnd:h,pid:id[0],className:b.toString('utf16le',0,length*2)};});console.log('STALE_SELECTION_FOREGROUND',JSON.stringify({mode,request,native}));}return result;};
  console.log('Real WinForms RichTextBox selection, caret, large selection and password control');const rich=await read('rich');assert.equal(rich.status,'ok');assert.equal(rich.text.replace(/\r\n?/g,'\n'),'Native 文字选区\n第二行 sample');assert.ok(rich.rects.length>0);assert.equal((await read('empty')).status,'none');assert.equal((await read('large')).status,'large');assert.equal((await read('password')).status,'protected');assert.equal((await read('rich')).status,'ok');assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),'Native controls unchanged clipboard');
  const saved=reader.pid;reader.cancel();assert.equal(reader.pid,undefined);await new Promise(r=>setTimeout(r,200));assert.throws(()=>process.kill(saved,0));
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,realWindowsRichText:true,noSelection:true,largeSelectionRejected:true,nativePasswordRejected:true,clipboardUnchanged:true,nativeWorkerTerminated:true},null,2));
 }finally{reader.cancel();if(fixture){fixture.stdin.end('exit\n');if(fixture.exitCode===null)fixture.kill();}await helper.evaluate(({clipboard})=>global.restoreClipboard());if(cursor)await helper.evaluate(({app,screen},cursor)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),set=req('koffi').load('user32.dll').func('bool __stdcall SetCursorPos(int,int)'),point=screen.dipToScreenPoint(cursor);set(point.x,point.y)},cursor);await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
