const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {StorageManager}=require('../work/test-exports.cjs');
async function run(){const output=path.resolve('work/sync-ui');await fs.mkdir(output,{recursive:true});const first=await fs.mkdtemp(path.join(output,'first-')),second=await fs.mkdtemp(path.join(output,'second-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const secondStore=new StorageManager(second);await secondStore.start();secondStore.store.saveSettings({...secondStore.store.settings,paused:true,shortcut:'Control+Shift+F18',nextShortcut:'Control+Alt+F20'});secondStore.store.setMeta('desktop-options',{shelfShortcut:'Control+Alt+F21'});secondStore.store.setMeta('efficiency',{historyEnabled:false,repliesShortcut:'Control+Alt+F23',bindings:[]});secondStore.store.close();
 const env={...process.env,CLIP_TEST_MODE:'1',CLIP_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let a,b;
 const launch=async root=>electron.launch(process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env:{...env,CLIP_DATA_DIR:root}}:{args:[path.resolve('.')],env:{...env,CLIP_DATA_DIR:root}});
 try{a=await launch(first);b=await launch(second);let pa=await a.firstWindow(),pb=await b.firstWindow();await pa.waitForSelector('#search');await pb.waitForSelector('#search');const errors=[];pa.on('pageerror',e=>errors.push(e.message));pb.on('pageerror',e=>errors.push(e.message));
  await helper.evaluate(({clipboard})=>clipboard.writeText('已有历史默认留在本机'));await expect.poll(async()=>(await pa.evaluate(()=>window.clip.state())).clips.length).toBe(1);
  for(const [page,name] of [[pa,'工作电脑'],[pb,'随身电脑']]){await page.locator('[data-page=sync]').click();await page.locator('#sync-name').fill(name);await page.locator('#sync-enabled').check();await page.locator('#sync-save').click();await expect.poll(async()=>(await page.evaluate(()=>window.clip.syncState())).enabled).toBe(true);await expect(page.locator('#sync-create')).toBeEnabled();}
  await pa.locator('#sync-create').click();await expect(pa.locator('#sync-invitation')).toHaveValue(/^clip-pair:/);const code=await pa.locator('#sync-invitation').inputValue();await pb.locator('#sync-join-code').fill(code);await pb.locator('#sync-join').click();await expect(pa.locator('[data-approve]')).toBeVisible();assert.equal((await pb.evaluate(()=>window.clip.state())).clips.length,0);await pa.screenshot({path:path.join(output,'pair-request.png')});await pa.locator('[data-approve]').click();await expect.poll(async()=>(await pb.evaluate(()=>window.clip.syncState())).peers.length,{timeout:12000}).toBe(1);assert.equal((await pb.evaluate(()=>window.clip.state())).clips.length,0);
  const firstClip=(await pa.evaluate(()=>window.clip.state())).clips[0];await pa.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,paused:true});});await helper.evaluate(({clipboard})=>clipboard.writeText('系统剪贴板保持原内容'));await pa.locator(`[data-share="${firstClip.id}"]`).click();await pb.evaluate(()=>window.clip.syncNow());await expect.poll(async()=>(await pb.evaluate(()=>window.clip.state())).clips.length,{timeout:12000}).toBe(1);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),'系统剪贴板保持原内容');
  // Real PNG created by Chromium and received through the TLS connection.
  const hp=await helper.firstWindow(),png=await hp.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=60;const ctx=canvas.getContext('2d');ctx.fillStyle='#59724a';ctx.fillRect(0,0,100,60);return canvas.toDataURL().split(',')[1];});await pa.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,paused:false});});await pa.locator('#sync-auto').check();await pa.locator('#sync-save').click();await expect.poll(async()=>(await pa.evaluate(()=>window.clip.syncState())).autoNew).toBe(true);
  await helper.evaluate(async({clipboard,ClipboardItem},png)=>clipboard.write([new ClipboardItem({'image/png':new Blob([Buffer.from(png,'base64')],{type:'image/png'})})]),png);await expect.poll(async()=>(await pb.evaluate(()=>window.clip.state())).clips.some(c=>c.kind==='image'),{timeout:15000}).toBe(true);const received=(await pb.evaluate(()=>window.clip.state())).clips.find(c=>c.kind==='image');const sent=(await pa.evaluate(()=>window.clip.state())).clips.find(c=>c.kind==='image');assert.equal((await pb.evaluate(id=>window.clip.detail(id),received.id)).payload.png,(await pa.evaluate(id=>window.clip.detail(id),sent.id)).payload.png);assert.ok(received.thumbnail);
  await pa.locator('[data-local="'+firstClip.id+'"]').click();await pa.locator('#dialog [type=submit]').click();await pb.evaluate(()=>window.clip.syncNow());await expect.poll(async()=>(await pb.evaluate(()=>window.clip.state())).clips.length).toBe(1);assert.equal((await pa.evaluate(()=>window.clip.state())).clips.find(c=>c.id===firstClip.id).localOnly,true);
  await helper.evaluate(({clipboard})=>clipboard.writeText('自动同步的新文字'));await expect.poll(async()=>(await pb.evaluate(()=>window.clip.state())).clips.some(c=>c.preview==='自动同步的新文字'),{timeout:15000}).toBe(true);await pa.screenshot({path:path.join(output,'sync-light.png')});
  const identity=(await pa.evaluate(()=>window.clip.syncState())).id;await a.close();a=await launch(first);pa=await a.firstWindow();await pa.waitForSelector('#search');assert.equal((await pa.evaluate(()=>window.clip.syncState())).id,identity);assert.equal((await pa.evaluate(()=>window.clip.syncState())).peers.length,1);await helper.evaluate(({clipboard})=>clipboard.writeText('重启后仍可同步'));await expect.poll(async()=>(await pb.evaluate(()=>window.clip.state())).clips.some(c=>c.preview==='重启后仍可同步'),{timeout:15000}).toBe(true);
  const privateData=await fs.readFile(path.join(first,'history.sqlite'));assert.equal(privateData.includes(Buffer.from('BEGIN PRIVATE KEY')),false);assert.equal(JSON.stringify(await pa.evaluate(()=>window.clip.syncState())).includes('secret'),false);
  await pb.locator('[data-revoke]').click();await pb.locator('#dialog [type=submit]').click();await expect.poll(async()=>(await pb.evaluate(()=>window.clip.syncState())).peers.length).toBe(0);const count=(await pb.evaluate(()=>window.clip.state())).clips.length;await helper.evaluate(({clipboard})=>clipboard.writeText('撤销后不会发送'));await pa.evaluate(()=>window.clip.syncNow());await pb.waitForTimeout(1200);assert.equal((await pb.evaluate(()=>window.clip.state())).clips.length,count);
  await pb.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,theme:'dark'});});await pb.screenshot({path:path.join(output,'sync-dark.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIP_PACKAGED_EXE,explicitPairing:true,oldHistoryPrivate:true,textAndPNG:true,noClipboardOverwrite:true,privateWithdraw:true,automaticCapture:true,restartIdentityAndDPAPI:true,revocation:true,output},null,2));
 }finally{if(a)await a.close();if(b)await b.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
