const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {Store,SyncService,syncRequest,privateAddress,SyncLedger,SyncDiscovery}=require('../work/test-exports.cjs');
const vault={available:async()=>true,encrypt:async s=>'unit:'+Buffer.from(s).toString('base64'),decrypt:async s=>Buffer.from(s.slice(5),'base64').toString()};
async function device(name){const store=new Store(':memory:'),service=new SyncService(()=>store,vault,()=>{},fn=>Promise.resolve().then(fn),undefined,{bindHost:'127.0.0.1',discovery:false});await service.configure({name,enabled:true,autoNew:false});return {store,service,close:async()=>{await service.stop();store.close();}};}
const pair=async(a,b)=>{await b.service.join(a.service.invite('127.0.0.1'));const request=a.service.state().pending[0];assert.ok(request);a.service.approve(request.id,true);await b.service.tick();assert.equal(b.service.state().peers.length,1);};
const identity=async d=>{const s=d.store.meta('lan-config',{});return {id:s.id,cert:s.cert,fingerprint:s.fingerprint,key:await vault.decrypt(s.secret)};};
const peer=d=>{const s=d.service.state();return {id:s.id,name:s.name,host:'127.0.0.1',port:s.port,fingerprint:s.fingerprint};};
test('Format-aware peers sync original bytes while legacy peers get compatible records and an upgrade notice',async()=>{const a=await device('formats A'),b=await device('formats B');try{await pair(a,b);const payload={text:'rich bytes',formats:[{name:'Rich Text Format',data:Buffer.from('{\\rtf1\\ansi caf\xe9}\0','latin1').toString('base64')}]},item=a.store.add(payload,'fixture');a.service.share(item.id);const plain=a.store.add({text:'compatible text'},'fixture');a.service.share(plain.id);const old=await syncRequest(await identity(b),peer(a),'/v1/manifest',undefined,undefined,3);assert.equal(old.records.length,1);assert.equal(old.records[0].hash,plain.hash);const record=a.service.ledger.manifest().find(r=>r.hash===item.hash);const bi=await identity(b);await assert.rejects(()=>syncRequest(bi,peer(a),'/v1/item',{id:record.id}),/升级/);await b.service.tick();assert.deepEqual(b.store.all().find(c=>c.hash===item.hash).payload,payload);const call=a.service.call.bind(a.service);a.service.call=async(...args)=>{const result=await call(...args);if(args[1]==='/v1/manifest')delete result.payloadVersion;return result;};const more=a.store.add({...payload,text:'pending bytes'},'fixture');a.service.share(more.id);const simple=a.store.add({text:'still syncs'},'fixture');a.service.share(simple.id);await a.service.tick();assert.match(a.service.state().peers[0].error,/升级/);assert.ok(b.store.all().some(c=>c.hash===simple.hash));assert.equal(b.store.all().some(c=>c.hash===more.hash),false);}finally{await a.close();await b.close();}});
test('TLS pairing requires invitation, approval and exact certificate pins before any HTTP data',async()=>{
 const a=await device('A'),b=await device('B'),c=await device('C');try{
  await assert.rejects(()=>syncRequest({},peer(a),'/v1/manifest')); // Missing client identity cannot authenticate.
  const ci=await identity(c);await assert.rejects(()=>syncRequest(ci,peer(a),'/v1/manifest'),/未配对/);
  let requests=0;a.service.server.on('request',()=>requests++);const before=requests;await assert.rejects(()=>syncRequest(ci,{...peer(a),fingerprint:'0'.repeat(64)},'/v1/pair',{secret:'must never be sent'}),/证书已改变/);assert.equal(requests,before);
  const code=a.service.invite('127.0.0.1');await assert.rejects(()=>syncRequest(ci,peer(a),'/v1/pair',{token:'0'.repeat(64),device:peer(c)}));await b.service.join(code);await assert.rejects(async()=>syncRequest(await identity(b),peer(a),'/v1/manifest'),/未配对/);a.service.approve(a.service.state().pending[0].id,true);await b.service.tick();assert.equal(a.service.state().peers.length,1);assert.equal(b.service.state().peers.length,1);await assert.rejects(()=>c.service.join(code),/已使用/);assert.equal(JSON.stringify(a.service.state()).includes('PRIVATE KEY'),false);
 }finally{await a.close();await b.close();await c.close();}
});
test('shared text syncs both ways, private/history/files stay local, and received items never auto-paste',async()=>{
 const a=await device('A'),b=await device('B');try{const hidden=a.store.add({text:'private existing history'},'fixture'),file=a.store.add({files:['C:\\fixture.txt']},'fixture');await pair(a,b);assert.equal(b.store.list().length,0);assert.throws(()=>a.service.share(file.id),/文件路径/);const clip=a.store.add({text:'shared text',html:'<b>shared text</b>'},'fixture');a.service.share(clip.id);await b.service.tick();assert.equal(b.store.list().length,1);assert.equal(b.store.all()[0].payload.html,'<b>shared text</b>');assert.equal(b.store.list()[0].shared,true);await b.service.tick();assert.equal(b.store.list().length,1);assert.equal(a.store.get(hidden.id).shared,undefined);
 const reply=b.store.add({text:'return direction'},'fixture');b.service.share(reply.id);await a.service.tick();assert.ok(a.store.list().some(x=>x.preview==='return direction'));
 a.service.local(clip.id,true);await b.service.tick();assert.equal(b.store.list().some(x=>x.preview==='shared text'),false);assert.equal(a.store.get(clip.id).localOnly,true);assert.throws(()=>a.service.share(clip.id),/仅本机/);a.service.local(clip.id,false);a.service.share(clip.id);await b.service.tick();assert.equal(b.store.list().length,2);
 }finally{await a.close();await b.close();}
});
test('offline divergent edits preserve both texts; tombstones win against replay and travel across three devices',async()=>{
 const a=await device('A'),b=await device('B'),c=await device('C');try{await pair(a,b);await c.service.join(b.service.invite('127.0.0.1'));b.service.approve(b.service.state().pending[0].id,true);await c.service.tick();const item=a.store.add({text:'original'},'fixture');a.service.share(item.id);await b.service.tick();await c.service.tick();const old=a.service.ledger.item(a.service.ledger.manifest()[0].id);assert.equal(c.store.list().length,1);await a.service.stop();await b.service.stop();a.store.edit(item.id,'edit from A',[]);b.store.edit(b.store.list()[0].id,'edit from B',[]);await a.service.start();await b.service.start();await b.service.tick();await a.service.tick();await c.service.tick();for(const device of [a,b,c])assert.deepEqual(device.store.list().map(x=>x.preview).sort(),['edit from A','edit from B']);
 const removed=a.store.list().find(x=>x.preview==='edit from B');a.store.delete(removed.id);await b.service.tick();await c.service.tick();assert.equal(c.store.list().length,1);assert.equal(c.service.ledger.apply(old.record,old.payload),false);assert.equal(c.store.list().some(x=>x.preview==='original'),false);
 }finally{await a.close();await b.close();await c.close();}
});
test('record integrity and index capacity failures roll back history, and private copies block re-publication',()=>{
 const store=new Store(':memory:'),id=randomUUID(),ledger=new SyncLedger(()=>store,()=>id);store.onChange=(p,n)=>ledger.observe(p,n);try{const clip=store.add({text:'immutable'},'fixture');ledger.publish(clip.id);const wire=ledger.item(ledger.manifest()[0].id),other=new Store(':memory:'),remote=new SyncLedger(()=>other,()=>randomUUID());try{assert.throws(()=>remote.apply(wire.record,{text:'changed'}),/校验/);assert.equal(other.list().length,0);other.setMeta('lan-index',Array.from({length:20000},(_,i)=>({...wire.record,id:randomUUID()+'.'+randomUUID(),deleted:true})));assert.throws(()=>remote.apply(wire.record,wire.payload),/20,000/);assert.equal(other.list().length,0);}finally{other.close();}
 const source=new Store(':memory:'),sender=new SyncLedger(()=>source,()=>randomUUID());try{const same=source.add({text:'immutable'},'fixture');sender.publish(same.id);ledger.local(clip.id,true);const incoming=sender.item(sender.manifest()[0].id);ledger.apply(incoming.record,incoming.payload);assert.equal(store.get(clip.id).localOnly,true);assert.equal(ledger.manifest().every(r=>r.deleted),true);}finally{source.close();}
 }finally{store.close();}
});
test('revocation and disable stop requests; expired/rejected invitations do not grant trust',async()=>{
 const a=await device('A'),b=await device('B');try{await b.service.join(a.service.invite('127.0.0.1'));a.service.approve(a.service.state().pending[0].id,false);await b.service.tick();assert.equal(b.service.state().peers.length,0);assert.ok(b.service.state().error);await pair(a,b);const ai=await identity(a),target=peer(b);b.service.revoke(a.service.state().id);await assert.rejects(()=>syncRequest(ai,target,'/v1/manifest'),/撤销/);await b.service.configure({name:'B',enabled:false,autoNew:false});await assert.rejects(()=>syncRequest(ai,target,'/v1/manifest'));assert.equal(b.service.server,undefined);for(const host of ['8.8.8.8','example.com','192.168.1.300','::1','10.0.0.1/path'])assert.equal(privateAddress(host),false);
 }finally{await a.close();await b.close();}
});
test('pair cancellation after approval removes provisional trust; expired codes cannot request access',async()=>{
 const a=await device('A'),b=await device('B');try{const code=a.service.invite('127.0.0.1'),invitation=JSON.parse(Buffer.from(code.slice(13),'base64url'));invitation.expires=Date.now()-1;await assert.rejects(()=>b.service.join('clipper-pair:'+Buffer.from(JSON.stringify(invitation)).toString('base64url')),/过期/);await b.service.join(code);a.service.approve(a.service.state().pending[0].id,true);assert.equal(a.service.state().peers.length,1);await b.service.cancelPairing();assert.equal(a.service.state().peers.length,0);await assert.rejects(async()=>syncRequest(await identity(b),peer(a),'/v1/manifest'),/未配对/);
 }finally{await a.close();await b.close();}
});
test('actual UDP multicast discovers both isolated device announcements without clipboard content',async()=>{
 const errors=[],first={id:randomUUID(),name:'Clipper discovery test A',host:'127.0.0.1',port:48301,fingerprint:'1'.repeat(64)},second={...first,id:randomUUID(),name:'Clipper discovery test B',port:48302,fingerprint:'2'.repeat(64)},a=new SyncDiscovery(()=>first,()=>{},e=>errors.push(e)),b=new SyncDiscovery(()=>second,()=>{},e=>errors.push(e));
 try{a.start();b.start();const until=Date.now()+7000;while(Date.now()<until&&(!a.list().length||!b.list().length))await new Promise(r=>setTimeout(r,100));assert.equal(a.list()[0]?.id,second.id);assert.equal(b.list()[0]?.id,first.id);assert.deepEqual(errors,[]);}finally{a.stop();b.stop();}
});
test('deduplication does not let a remote deletion erase a pre-existing local copy',async()=>{
 const a=await device('A'),b=await device('B');try{const local=b.store.add({text:'already mine'},'local fixture');b.store.update(local.id,{favorite:true,tags:['local tag']});const published=a.store.add({text:'already mine'},'fixture');a.service.share(published.id);await pair(a,b);assert.equal(b.store.list().length,1);a.store.delete(published.id);await b.service.tick();assert.equal(b.store.get(local.id).payload.text,'already mine');assert.equal(b.store.get(local.id).favorite,true);assert.deepEqual(b.store.get(local.id).tags,['local tag']);assert.equal(b.store.get(local.id).shared,false);}finally{await a.close();await b.close();}
});
