const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{png,decode}=require('./png-fixture.cjs');
const {Thumbnails}=require('../work/test-thumbnails.cjs'),host=process.env.CLIPPER_IMAGE_HOST||path.resolve('dist/native/ImageHost.exe');
test('native thumbnail bounds size, preserves source and handles straight alpha',async()=>{
 const thumbnails=new Thumbnails(host);try{for(const [width,height,color]of [[2,2,[255,0,0,128]],[3600,3300,[23,170,80,255]],[9000,4200,[30,80,255,255]]]){const bytes=png(width,height,()=>color),payload={png:bytes.toString('base64')},original=payload.png,url=await thumbnails.run(payload),output=decode(Buffer.from(url.split(',')[1],'base64')),scale=Math.min(1,280/width,180/height);assert.equal(output.width,Math.max(1,Math.round(width*scale)));assert.equal(output.height,Math.max(1,Math.round(height*scale)));for(let i=0;i<output.pixels.length;i++)assert(Math.abs(output.pixels[i]-color[i%output.bpp])<=2);assert.equal(payload.png,original);assert.equal(await thumbnails.run(payload),url);assert.deepEqual(thumbnails.stats(),{active:0,pending:0,encodedBytes:0});}}finally{await thumbnails.stop();}
});
test('corrupt PNG, invalid dimensions, missing host and expired task leave no decoder',async()=>{
 const thumbnails=new Thumbnails(host);try{const source=png(1000,1000);await assert.rejects(thumbnails.run({png:source.subarray(0,45).toString('base64')}));const huge=Buffer.from(source);huge.writeUInt32BE(20000,16);await assert.rejects(thumbnails.run({png:huge.toString('base64')}));await assert.rejects(new Thumbnails(path.resolve('work/missing-image-host.exe')).run({png:source.toString('base64')}));const expired=new Thumbnails(host,1);await assert.rejects(expired.run({png:source.toString('base64')}));assert.deepEqual(expired.stats(),{active:0,pending:0,encodedBytes:0});}finally{await thumbnails.stop();}
});
test('queued and active cancellation, bounded jobs and stop wait for native retirement',async()=>{
 const thumbnails=new Thumbnails(host),source=png(8000,4000).toString('base64');let live=true;const pending=Array.from({length:4},()=>thumbnails.run({png:source},()=>live));for(const promise of pending)promise.catch(()=>{});await assert.rejects(thumbnails.run({png:source}),/正在保存/);live=false;await thumbnails.stop();for(const promise of pending)await assert.rejects(promise,/取消/);assert.deepEqual(thumbnails.stats(),{active:0,pending:0,encodedBytes:0});await assert.rejects(thumbnails.run({png:source},()=>false),/取消/);
});
