const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function fixture(file){
 const module={exports:{}},timers=new Set(),screen=new EventEmitter(),calls={mouse:0,keys:0,cursor:0,meta:0,reads:0},data={};let blocked=false,buttons={left:false,right:false,middle:false};
 Object.assign(screen,{getCursorScreenPoint:()=>{calls.cursor++;return{x:100,y:100};},dipToScreenPoint:p=>p,screenToDipPoint:p=>p,getDisplayNearestPoint:()=>({id:1,workArea:{x:0,y:0,width:1920,height:1040}}),getAllDisplays:()=>[{id:1,label:'Test display',bounds:{x:0,y:0,width:1920,height:1080},workArea:{x:0,y:0,width:1920,height:1040}}]});
 class Window extends EventEmitter{constructor(){super();this.webContents=Object.assign(new EventEmitter(),{setWindowOpenHandler:()=>{},isLoading:()=>false,send:()=>{}});this.visible=false;}isDestroyed(){return false;}hide(){this.visible=false;this.emit('hide');}show(){this.visible=true;this.emit('show');}showInactive(){this.show();}focus(){}isFocused(){return false;}isVisible(){return this.visible;}isMinimized(){return false;}setFocusable(){}setBounds(b){this.bounds=b;}getBounds(){return this.bounds||{x:0,y:0,width:500,height:100};}getNativeWindowHandle(){const b=Buffer.alloc(8);b.writeBigUInt64LE(99n);return b;}loadURL(){return Promise.resolve();}destroy(){this.emit('closed');}setAlwaysOnTop(){}}
 class Reader{cancel(){}async read(){calls.reads++;return{status:'ok',text:'Synthetic selected text',rects:[]};}}
 const native={nativeAvailable:()=>true,foreground:()=>({hwnd:123,pid:456,name:'Test.exe'}),foregroundBounds:()=>null,mouseButtons:()=>{calls.mouse++;return buttons;},selectionKeyDown:()=>{calls.keys++;return false;}};
 const store={settings:{excludedApps:[],paused:false},meta:(key,fallback)=>{calls.meta++;return data[key]||fallback;},setMeta:(key,value)=>data[key]=value};
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{module,exports:module.exports,require:id=>id==='electron'?{app:{isPackaged:false},screen,BrowserWindow:Window}:id==='./native'?native:id==='./selection-reader'?{SelectionReader:Reader}:require(id),process,Buffer,TextDecoder,TextEncoder,__dirname:path.resolve('dist/main'),setTimeout,clearTimeout,setInterval:(fn,ms)=>{const timer=setInterval(fn,ms);timers.add(timer);return timer;},clearInterval:timer=>{timers.delete(timer);clearInterval(timer);},console},{filename:file});
 const common={store:()=>store,blocked:()=>blocked,dark:()=>false,changed:()=>{},show:()=>{},notice:()=>{},rememberTarget:()=>{},quick:()=>new Window(),peekQuick:()=>undefined,enqueue:fn=>Promise.resolve(fn()),commit:async()=>{}};const desktop=new module.exports.DesktopController(common),selection=new module.exports.SelectionService(common);
 return{desktop,selection,calls,timers,store,setBlocked:value=>blocked=value,setButtons:value=>buttons=value,close:()=>{desktop.dispose();selection.dispose();for(const timer of timers)clearInterval(timer);}};
}
(async()=>{fs.mkdirSync('work/tracking-031',{recursive:true});const build=require('esbuild').build;for(const name of ['before','after']){const contents=name==='before'?"export {DesktopController} from '../delivery-0.30.0/src/main/desktop';export {SelectionService} from '../delivery-0.30.0/src/main/selection';":undefined;await build({...(contents?{stdin:{contents,resolveDir:process.cwd(),loader:'ts'}}:{entryPoints:['tests/tracking-031-exports.ts']}),outfile:'work/tracking-031/'+name+'.cjs',bundle:true,platform:'node',external:['electron','./native','./selection-reader']});}
 const before=fixture(path.resolve('work/tracking-031/before.cjs')),after=fixture(path.resolve('work/tracking-031/after.cjs'));try{
  await wait(1250);assert(before.calls.mouse>10&&before.calls.cursor>10&&before.calls.meta>5);assert.deepEqual(after.calls,{mouse:0,keys:0,cursor:0,meta:2,reads:0});assert.equal(after.timers.size,0);const idle={before:{...before.calls,timers:before.timers.size},after:{...after.calls,timers:after.timers.size}};
  const options=after.desktop.options;after.desktop.configure({...options,dockEnabled:true});assert.equal(after.timers.size,1);after.desktop.configure({...options,dockEnabled:false});assert.equal(after.timers.size,0);
  after.selection.configure({...after.selection.options,enabled:true,delayMs:200});assert.equal(after.timers.size,1);after.setButtons({left:true,right:false,middle:false});await wait(90);after.setButtons({left:false,right:false,middle:false});await wait(340);assert.equal(after.calls.reads,1);assert(after.selection.view());after.selection.configure({...after.selection.options,enabled:false});assert.equal(after.timers.size,0);
  await after.selection.read(true);assert.equal(after.calls.reads,2);assert(after.selection.view());assert.equal(after.timers.size,1);after.selection.hide();assert.equal(after.timers.size,0);await after.selection.read(true);after.setBlocked(true);await wait(90);assert.equal(after.selection.view(),null);assert.equal(after.timers.size,0);after.setBlocked(false);after.selection.configure({...after.selection.options,enabled:true});after.selection.dispose();assert.equal(after.timers.size,0);
  fs.writeFileSync('work/tracking-031/results.json',JSON.stringify({passed:true,scope:'Actual production controllers with real Node timers for 1.25 seconds; synthetic native/screen/selection dependencies. Counts prove scheduler behavior, not OS CPU usage.',idle,disabledNoPolling:true,desktopEnableDisable:true,automaticSelection:true,keyboardWhileDisabled:true,blockedKeyboardCancels:true,disposeStops:true},null,2));console.log(JSON.stringify({passed:true,idle}));
 }finally{before.close();after.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

