const {fixture,expect}=require('./efficiency-fixture.cjs'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{spawnSync,execFile}=require('node:child_process');
async function run(){const output=path.resolve('work/tray-native');await fs.mkdir(output,{recursive:true});const framework=path.join(process.env.WINDIR,'Microsoft.NET','Framework64','v4.0.30319'),exe=path.join(output,'TrayIconLocator.exe');const build=spawnSync(path.join(framework,'csc.exe'),['/nologo','/target:exe','/platform:x64','/win32manifest:'+path.resolve('native/SelectionHost.manifest'),'/out:'+exe,...['UIAutomationClient.dll','UIAutomationTypes.dll','WindowsBase.dll'].map(n=>'/reference:'+path.join(framework,'WPF',n)),'/reference:'+path.join(framework,'System.Web.Extensions.dll'),path.resolve('tests/tray-icon-locator.cs')],{encoding:'utf8',windowsHide:true});assert.equal(build.status,0,build.stdout+build.stderr);const locate=()=>new Promise((resolve,reject)=>execFile(exe,[],{encoding:'utf8',windowsHide:true,timeout:8000},(err,out)=>{if(err)reject(err);else try{resolve(JSON.parse(out));}catch(e){reject(e);}}));
 const f=await fixture('tray-native');try{const text='真实托盘点击与原窗口粘贴';await f.page.evaluate(t=>window.clipper.saveOcr(t),text);await f.app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.hide()));await f.focus();
 const click=async(rect,button='left')=>{assert.ok(!rect.offscreen&&rect.width>0&&rect.height>0);await f.helper.evaluate(({app},{x,y,button})=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json')),u=req('koffi').load('user32.dll'),send=u.func('uint32 __stdcall SendInput(uint32,void*,int)'),metric=u.func('int __stdcall GetSystemMetrics(int)'),b=Buffer.alloc(120);for(let i=0;i<3;i++){b.writeInt32LE(Math.round((x-metric(76))*65535/(metric(78)-1)),i*40+8);b.writeInt32LE(Math.round((y-metric(77))*65535/(metric(79)-1)),i*40+12);b.writeUInt32LE(0xc001|[0,button==='right'?8:2,button==='right'?16:4][i],i*40+20);}if(send(3,b,40)!==3)throw Error('Native tray click rejected');},{x:rect.x+rect.width/2,y:rect.y+rect.height/2,button});};
 let current=await locate(),visible=current.icons.filter(i=>!i.offscreen&&i.width>0&&i.height>0),overflow=false;if(!visible.length){const expand=current.expand.filter(i=>!i.offscreen&&i.width>0&&i.height>0);assert.equal(expand.length,1,JSON.stringify(current));console.log('EXPAND_ICON',JSON.stringify(expand[0]));await click(expand[0]);overflow=true;await expect.poll(async()=>{current=await locate();visible=current.icons.filter(i=>!i.offscreen&&i.width>0&&i.height>0);return visible.length;}).toBe(1).catch(e=>{console.log('LOCATOR_RESULT',JSON.stringify(current));throw e;});}assert.equal(visible.length,1,JSON.stringify(current));
 console.log('Clicking observed notification-area icon',JSON.stringify({name:visible[0].name,overflow}));const opened=f.app.waitForEvent('window');await click(visible[0]);const panel=await opened;await panel.waitForSelector('.tray-row');await new Promise(r=>setTimeout(r,750));assert.equal(panel.isClosed(),false,'Tray panel lost focus after notification-area activation');await expect(panel.locator('#paste-selected')).toBeEnabled();await panel.screenshot({path:path.join(output,'actual-tray-entry.png')});await panel.locator('.tray-row').filter({hasText:text}).click({button:'right'});await expect(f.target.locator('#target')).toHaveValue(text);await expect.poll(()=>panel.isClosed()).toBe(true);
 const result={result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,realNotificationAreaClick:true,overflow,stablePopup:true,realTargetPaste:true};await fs.writeFile(path.join(output,'evidence.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }finally{await f.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
