const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {Store}=require('../work/test-exports.cjs');
async function run(){
 const output=path.resolve('work/tray-ui');await fs.mkdir(output,{recursive:true});
 const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:await fs.mkdtemp(path.join(output,'profile-')),CLIPPER_HELPER_PROFILE:await fs.mkdtemp(path.join(output,'helper-'))};delete env.ELECTRON_RUN_AS_NODE;
 const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});helper.process().stderr.on('data',data=>console.log('HELPER_STDERR',String(data)));let app;
 try{
  const target=await helper.firstWindow();await target.waitForSelector('#target');app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const main=await app.firstWindow();await main.waitForSelector('#search');assert.equal((await main.evaluate(()=>window.clipper.state())).hotkeyError,'','Exit the daily Clipper before testing');
  const png=await target.evaluate(()=>{const c=document.createElement('canvas');c.width=720;c.height=420;const g=c.getContext('2d');g.fillStyle='#eceff4';g.fillRect(0,0,720,420);g.fillStyle='#728b9c';g.fillRect(42,45,220,320);g.fillStyle='#fff';g.fillRect(290,45,386,320);g.fillStyle='#303844';g.font='32px Segoe UI';g.fillText('Clipper · Preview',316,116);g.font='20px Segoe UI';g.fillText('Saved image content',316,165);return c.toDataURL('image/png').split(',')[1];});
  const store=new Store(':memory:');let textClip,imageClip,folderClip;
  try{const base=Date.now()-1000;for(let i=0;i<90;i++)store.add({text:'历史记录 '+i},'Editor.exe',undefined,{updatedAt:base+i},false);textClip=store.add({text:'托盘 Café 检查\n原窗口粘贴内容\n<script>window.trayExecuted=true</script>'},'Editor.exe',undefined,{favorite:true,tags:['工作'],updatedAt:base+300},false);imageClip=store.add({png},'Capture.exe',undefined,{updatedAt:base+200},false);folderClip=store.add({attachments:[{name:'项目',data:'',directory:true},{name:'项目\\说明.txt',data:Buffer.from('tray folder contents').toString('base64')},{name:'空目录',data:'',directory:true}]},'Mail.exe',undefined,{updatedAt:base+100},false);store.saveCategory({name:'邮件文件',color:'#7b8e9c',kind:'files',contains:'说明',source:'mail',tag:''});const seed=path.join(output,'seed-'+Date.now()+'.json');await fs.writeFile(seed,JSON.stringify(store.backup()));await app.evaluate(({dialog},file)=>dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]}),seed);await main.evaluate(()=>window.clipper.backup('import'));}finally{store.close();}
  const imported=(await main.evaluate(()=>window.clipper.state())).clips;for(const item of [textClip,imageClip,folderClip]){const match=imported.find(c=>c.hash===item.hash);assert.ok(match);item.id=match.id;}
  await app.evaluate(({app,BrowserWindow})=>{global.trayEvents=[];app.on('browser-window-created',(_e,w)=>{for(const event of ['focus','blur','hide','closed'])w.on(event,()=>global.trayEvents.push({event,time:Date.now(),focused:BrowserWindow.getFocusedWindow()?.getTitle()}));});});
  const open=async()=>{await helper.evaluate(async()=>{await global.focusTarget();global.helperWindow.setAlwaysOnTop(false);});await target.locator('#target').focus();await helper.evaluate(({app},pid)=>{const req=process.getBuiltinModule('node:module').createRequire(process.getBuiltinModule('node:path').join(app.getAppPath(),'package.json'));if(!req('koffi').load('user32.dll').func('bool __stdcall AllowSetForegroundWindow(uint32)')(pid))throw Error('Cannot grant test foreground transition');},app.process().pid);const existing=app.windows().find(window=>window.url()==='clipper://app/tray.html'),opened=existing?Promise.resolve(existing):app.waitForEvent('window');await main.evaluate(()=>window.clipper.showTray());const panel=await opened;await panel.waitForSelector('.tray-row');return panel;};
  const hidden=()=>app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL()==='clipper://app/tray.html');return !window||!window.isVisible();});
  console.log('Tray panel lists recent entries, filters and previews without executing clipboard markup');
  let panel=await open();await expect(panel.locator('.tray-row')).toHaveCount(80);await expect(panel.locator('#count')).toContainText('80 / 93');await expect(panel.locator('#preview')).toContainText('原窗口粘贴内容');assert.equal(await panel.evaluate(()=>window.trayExecuted),undefined);assert.equal(await panel.evaluate(()=>typeof window.clipper), 'undefined');assert.equal(await panel.evaluate(()=>typeof require),'undefined');
  await panel.keyboard.press('ArrowDown');await expect(panel.locator('.preview-image')).toHaveCount(1);await panel.keyboard.press('ArrowUp');await expect(panel.locator('#preview')).toContainText('原窗口粘贴内容');await panel.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true})));assert.equal(panel.isClosed(),false);
  await panel.locator('#search').fill('café 工作');await expect(panel.locator('.tray-row')).toHaveCount(1);await expect(panel.locator('#preview')).toContainText('<script>');await panel.locator('#search').fill('');await expect(panel.locator('.tray-row')).toHaveCount(80);await panel.locator('#category').selectOption('favorites');await expect(panel.locator('.tray-row')).toHaveCount(1);await panel.locator('#category').selectOption('');await panel.locator('[data-kind="files"]').click();await expect(panel.locator('.tray-row')).toHaveCount(1);await expect(panel.locator('#preview')).toContainText('已保存文件夹');await expect(panel.locator('#preview')).toContainText('项目\\说明.txt');
  await panel.locator('[data-kind="all"]').click();await expect(panel.locator('.tray-row')).toHaveCount(80);const category=await panel.locator('#category option').allTextContents();assert.ok(category.includes('邮件文件'));await panel.locator('#category').selectOption({label:'邮件文件'});await expect(panel.locator('.tray-row')).toHaveCount(1);await panel.locator('#category').selectOption('');await expect(panel.locator('.tray-row')).toHaveCount(80);
  await panel.locator('[data-id="'+imageClip.id+'"]').hover();await expect(panel.locator('.preview-image')).toHaveCount(1);assert.match(await panel.locator('.preview-image').getAttribute('src'),/^clipper:\/\/app\/preview-image\/[0-9a-f-]{36}$/);assert.deepEqual(await panel.evaluate(async()=>{const image=document.querySelector('.preview-image');await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d');context.drawImage(image,0,0);return [canvas.width,canvas.height,...context.getImageData(0,0,1,1).data,...context.getImageData(50,50,1,1).data];}),[720,420,236,239,244,255,114,139,156,255]);await panel.screenshot({path:path.join(output,'tray-image-light.png')});await panel.locator('[data-id="'+textClip.id+'"]').hover();await expect(panel.locator('#preview')).toContainText('原窗口粘贴内容');await panel.screenshot({path:path.join(output,'tray-text-light.png')});
  console.log('Left click copies the complete original text and dismisses the tray panel');
  await panel.locator('[data-id="'+textClip.id+'"]').click();await expect.poll(hidden).toBe(true);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),textClip.payload.text);
  console.log('Right click restores the captured external target and pastes once');
  await target.locator('#target').fill('');panel=await open();await panel.locator('[data-id="'+textClip.id+'"]').click({button:'right'});await expect(target.locator('#target')).toHaveValue(textClip.payload.text);await expect.poll(hidden).toBe(true);
  console.log('Keyboard selection previews the row, Enter copies and Ctrl+Enter pastes');
  panel=await open();await panel.locator('#search').fill('托盘 Café');await expect(panel.locator('.tray-row')).toHaveCount(1);await panel.locator('.tray-row').focus();await panel.keyboard.press('Enter').catch(async e=>{if(!await hidden())throw e;});await expect.poll(hidden).toBe(true);assert.equal(await helper.evaluate(({clipboard})=>clipboard.readText()),textClip.payload.text);
  await target.locator('#target').fill('');panel=await open();await panel.locator('#search').fill('托盘 Café');await expect(panel.locator('.tray-row')).toHaveCount(1);await panel.locator('.tray-row').focus();await panel.keyboard.press('Control+Enter').catch(async e=>{if(!await hidden())throw e;});await expect(target.locator('#target')).toHaveValue(textClip.payload.text);await expect.poll(hidden).toBe(true);
  console.log('Dark mode and a narrow panel keep controls reachable');
  await main.evaluate(async()=>{const s=await window.clipper.state();await window.clipper.settings({...s.settings,theme:'dark'});});panel=await open();await panel.locator('[data-id="'+folderClip.id+'"]').hover();await expect(panel.locator('#preview')).toContainText('已保存文件夹');await panel.screenshot({path:path.join(output,'tray-folders-dark.png')});await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL()==='clipper://app/tray.html');w.setBounds({width:460,height:460});});await expect.poll(()=>panel.evaluate(()=>document.documentElement.dataset.theme)).toBe('dark');await panel.screenshot({path:path.join(output,'tray-narrow-dark.png')});const geometry=await panel.evaluate(()=>{const r=document.getElementById('copy-selected').getBoundingClientRect();return {right:r.right,bottom:r.bottom,width:innerWidth,height:innerHeight,overflow:document.body.scrollWidth>innerWidth};});assert.equal(geometry.overflow,false);assert.ok(geometry.bottom<=geometry.height&&geometry.right<=geometry.width);await panel.keyboard.press('Escape').catch(async e=>{if(!await hidden())throw e;});await expect.poll(hidden).toBe(true);
  console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,recentLimit:true,unicodeSearch:true,favoritesAndCategory:true,hoverTextImageFolders:true,markupInert:true,leftCopy:true,rightPaste:true,keyboardCopyPaste:true,arrowPreview:true,simulatedIMEGuard:true,lightDark:true,narrowLayout:true,escapeDismisses:true},null,2));
 }finally{if(app){console.log('TRAY_WINDOW_EVENTS',JSON.stringify(await app.evaluate(()=>global.trayEvents)));await app.close();}await helper.evaluate(()=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
