const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupText}=require('./language-text-fixture.cjs'),{setupData}=require('./language-data-fixture.cjs'),{extra}=require('./ui-028-fixture.cjs');
(async()=>{await fs.mkdir('work/ui-028',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],results=[];try{
 for(const language of ['zh-CN','en']){const context=await browser.newContext({viewport:{width:1240,height:800}});for(const fn of [setup,setupText,setupData,extra])await context.addInitScript(fn,language);
 await context.route('https://clipper.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return route.abort();await route.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clipper.test/index.html');await page.waitForSelector('#copy');
 assert.equal(await page.locator('.titlebar #pause-nav').count(),0);assert.equal(await page.locator('.sidebar #pause-nav').count(),1);await page.locator('#window-maximize').click();assert.equal(await page.locator('#window-maximize').getAttribute('aria-label'),language==='en'?'Restore':'还原');await page.locator('#window-maximize').click();
 await page.locator('[data-page=settings]').click();await page.waitForSelector('#desktop-edge-trigger',{state:'attached'});const tab=label=>page.locator('#content .section-nav button').filter({hasText:label});
 await tab(language==='en'?'Desktop interaction':'桌面交互').click();assert.equal(await page.locator('dialog[open]').count(),0);await page.locator('#desktop-edge-trigger').click();await page.keyboard.press('End');await page.keyboard.press('Enter');assert.equal(await page.locator('#desktop-edge').inputValue(),'bottom');await page.locator('#desktop-dockEnabled').check();await page.locator('#desktop-inline .inline-settings-footer button').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='desktop'));assert.equal(await page.evaluate(()=>fixture.calls.find(c=>c[0]==='desktop')[1].dockEdge),'bottom');
 await page.locator('#desktop-display-trigger').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#desktop-display-trigger').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.id),'desktop-display-trigger');
 await page.evaluate(()=>{const select=document.getElementById('desktop-display');select.insertAdjacentHTML('beforeend','<option value="2">Second screen</option>');select.value='2';});assert.equal(await page.locator('#desktop-display-trigger').innerText(),'Second screen');
 await tab(language==='en'?'Selection menu':'划词菜单').click();await page.locator('#selection-enabled').check();await page.locator('#selection-inline .inline-settings-footer button').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='selection'));assert.equal(await page.evaluate(()=>fixture.calls.find(c=>c[0]==='selection')[1].enabled),true);
 await tab(language==='en'?'Search & quick replies':'搜索与快捷回复').click();await page.locator('#history-enabled').check();await page.locator('#efficiency-inline .inline-settings-footer button').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='efficiency'));
 await tab(language==='en'?'Interface language':'界面语言').click();await page.locator('#interface-language-trigger').click();await page.keyboard.press('End');await page.keyboard.press('Enter');await page.locator('#language-inline .inline-settings-footer button').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='language'));assert.equal(await page.evaluate(()=>fixture.calls.find(c=>c[0]==='language')[1]),'system');
 await tab(language==='en'?'Appearance':'外观').click();await page.locator('#appearance-accent').fill('#4479d8');await page.locator('#appearance-accent').press('Tab');await page.waitForFunction(()=>fixture.value().accent==='#4479d8');await page.locator('#appearance-font').click();await page.locator('#appearance-font-search').fill('Consolas');await page.getByRole('option',{name:'Consolas',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.fontStatus==='ready'&&fixture.value().font==='installed:Consolas');
 await page.locator('#appearance-toastPosition-trigger').click();await page.keyboard.press('End');await page.keyboard.press('Enter');await page.waitForFunction(()=>fixture.value().toastPosition==='bottom-left');
 await page.evaluate(()=>fixture.failAppearance=true);await page.locator('#appearance-accent').fill('#41886c');await page.locator('#appearance-accent').press('Tab');await page.waitForFunction(()=>document.getElementById('appearance-accent').value==='#4479d8');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()),'#4479d8');
 await page.locator('#appearance-accent').fill('#bad');await page.locator('#appearance-accent').press('Tab');assert.equal(await page.locator('#appearance-accent').inputValue(),'#4479d8');
 await page.locator('#sidebar-toggle').hover();await page.waitForSelector('#one-tooltip.visible');assert.equal(await page.locator('#sidebar-toggle').getAttribute('aria-describedby'),'one-tooltip');await page.keyboard.press('Tab');assert.equal(await page.locator('#one-tooltip.visible').count(),0);
 for(const [name,labels]of [['settings',[language==='en'?'Appearance':'外观',language==='en'?'Desktop interaction':'桌面交互']],['ai',[]],['scripts',[]],['uri',[]],['sync',[]]]){await page.locator(`[data-page=${name}]`).click();await page.waitForTimeout(100);const tabs=page.locator('#content .section-nav button');for(let i=0;i<await tabs.count();i++){await tabs.nth(i).click();for(const [width,height,scale]of [[1240,800,100],[860,600,100],[860,600,150]]){await page.setViewportSize({width,height});await page.evaluate(scale=>fixture.appearance({...fixture.value(),scale}),scale);await page.waitForTimeout(20);const value=await page.evaluate(()=>({body:document.body.scrollWidth<=innerWidth,panels:[...document.querySelectorAll('.section-panels')].every(e=>e.scrollWidth<=e.clientWidth+1),controls:[...document.querySelectorAll('#content button,#content input,#content textarea')].filter(e=>e.getClientRects().length&&!e.matches('.select-backing')).every(e=>e.getBoundingClientRect().right<=innerWidth+1)}));assert.deepEqual(value,{body:true,panels:true,controls:true},JSON.stringify({name,i,width,height,scale,value}));results.push({language,name,section:i,width,height,scale});if(width===1240&&language==='zh-CN')await page.screenshot({path:`work/ui-028/${name}-${i}.png`});}}}
 await page.setViewportSize({width:1240,height:800});await page.evaluate(()=>fixture.appearance({...fixture.value(),scale:100}));await page.locator('[data-page=sync]').click();await tab(language==='en'?'Add device':'添加设备').click();await page.locator('#sync-create').click();await page.waitForFunction(()=>document.getElementById('sync-invitation').value==='clipper-pair:synthetic');await page.locator('#sync-join-code').fill('clipper-pair:other');await page.evaluate(()=>fixture.refresh());await page.waitForTimeout(80);assert.equal(await page.locator('#sync-join-code').inputValue(),'clipper-pair:other');await page.locator('#sync-join').click();await page.waitForFunction(()=>fixture.calls.some(c=>c[0]==='join'));
 for(const [name,width,height]of [['tray',740,560],['shelf',420,440],['shelf',280,220]]){await page.setViewportSize({width,height});await page.goto(`https://clipper.test/${name}.html`);await page.waitForTimeout(100);assert.equal(await page.locator('body>main').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight+1),true);assert.equal(await page.evaluate(()=>document.body.scrollWidth<=innerWidth),true);const outline=await page.locator(name==='shelf'?'header .toolbar button,.actions button':'.tray-row,#filters button,.header-actions button').evaluateAll(nodes=>nodes.every(e=>getComputedStyle(e).borderTopWidth==='0px'));assert.equal(outline,true);if(name==='shelf'){assert.equal(await page.locator('header #choose').count(),1);await page.locator('#choose').click();assert(await page.evaluate(()=>fixture.calls.some(c=>c[0]==='shelfChoose')));}else assert.equal(await page.locator('header #search').count(),1);await page.screenshot({path:`work/ui-028/${language}-${name}-${width}.png`});}
 await context.close();}
 assert.deepEqual(errors,[]);await fs.writeFile('work/ui-028/results.json',JSON.stringify({cases:results.length,errors,scope:'Production renderer bundles; isolated headless input, synthetic IPC and local installed-font loading. No system clipboard or desktop input.',results},null,2));console.log(JSON.stringify({cases:results.length,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
