const generated=require('./generated-fixtures.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {UpdateService}=require('../work/test-updates.cjs'),core=require('../work/test-update-core.cjs');
const bytes=Buffer.alloc(1024*1024,67),hash=crypto.createHash('sha256').update(bytes).digest('hex');
async function fixture(){const folder=await generated.mkdtemp(path.resolve('work/update-test-')),calls=[],changes=[];let mode='normal',installed=true,armed=0,cancelled=0,apiCalls=0;
 const release=()=>({tag_name:'v0.25.0',html_url:core.UPDATE_RELEASES_URL+'/tag/v0.25.0',draft:false,prerelease:false,body:'原始说明 <script>x</script>',assets:[{name:'Clipper-0.25.0-Setup-x64.exe',state:'uploaded',size:bytes.length,digest:'sha256:'+hash,browser_download_url:core.UPDATE_RELEASES_URL+'/download/v0.25.0/Clipper-0.25.0-Setup-x64.exe'}]});
 const server=http.createServer((req,res)=>{calls.push(req.url);if(req.url==='/latest'){apiCalls++;if(mode==='unpublished'||mode==='rate'){res.writeHead(mode==='unpublished'?404:403);return res.end();}if(mode==='malformed')return res.end('{invalid');return res.end(JSON.stringify(release()));}if(mode==='length')res.setHeader('Content-Length',bytes.length-1);if(mode==='slow'){let count=0;const timer=setInterval(()=>{if(++count>1024){clearInterval(timer);res.end();}else res.write(bytes.subarray(0,1024));},5);res.on('close',()=>clearInterval(timer));return;}res.end(mode==='checksum'?Buffer.alloc(bytes.length,68):mode==='short'?bytes.subarray(0,4):bytes);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
 const transport=(url,signal)=>new Promise((resolve,reject)=>{const req=http.get(origin+(url===core.UPDATE_API_URL?'/latest':'/installer'),{signal},resolve);req.on('error',reject);});
 const service=new UpdateService({version:'0.24.0',directory:folder,installed:async()=>installed,changed:s=>changes.push(s),arm:async()=>{armed++;return()=>cancelled++;},openFolder:file=>calls.push(file)},transport);await service.init();
 return {service,folder,changes,calls,mode:v=>mode=v,installed:v=>installed=v,armed:()=>armed,cancelled:()=>cancelled,apiCalls:()=>apiCalls,close:async()=>{await service.stop();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await fs.rm(folder,{recursive:true,force:true});}};
}
test('manual HTTP check, streaming download, verified installer and handoff preserve data boundary',async()=>{const f=await fixture();try{assert.equal(f.apiCalls(),0);assert.equal(f.service.state().automatic,false);assert.equal((await f.service.scheduled()).phase,'idle');const update=await f.service.check();assert.equal(update.phase,'available');assert.equal(update.release.version,'0.25.0');const ready=await f.service.download();assert.equal(ready.phase,'ready');assert.equal(ready.downloaded,bytes.length);const dir=(await fs.readdir(f.folder)).find(n=>n.startsWith('download-'));assert.deepEqual(await fs.readFile(path.join(f.folder,dir,'installer.exe')),bytes);assert.ok(f.changes.some(c=>c.phase==='downloading'));await f.service.install(()=>true);assert.equal(f.armed(),1);assert.equal(f.service.state().phase,'installing');assert.throws(()=>f.service.cancel(),/UPDATE_BUSY/);assert.ok(!f.calls.some(c=>String(c).includes('history')));}finally{await f.close();}});
test('automatic check preference persists and schedules at most once per day',async()=>{const f=await fixture();try{await f.service.configure(true);await f.service.scheduled();await f.service.scheduled();assert.equal(f.apiCalls(),1);const saved=JSON.parse(await fs.readFile(path.join(f.folder,'preferences.json'),'utf8'));assert.equal(saved.automatic,true);assert.ok(saved.checkedAt>0);await assert.rejects(f.service.configure('true'),/UPDATE_OPTIONS_INVALID/);}finally{await f.close();}});
test('404 is unpublished while rate limits and malformed JSON produce actionable errors',async()=>{const f=await fixture();try{f.mode('unpublished');assert.equal((await f.service.check()).phase,'unpublished');f.mode('rate');assert.equal((await f.service.check()).error,'UPDATE_RATE_LIMIT');f.mode('malformed');assert.equal((await f.service.check()).error,'UPDATE_RELEASE_INVALID');}finally{await f.close();}});
for(const [mode,error]of [['checksum','UPDATE_CHECKSUM'],['short','UPDATE_LENGTH'],['length','UPDATE_LENGTH']])test(mode+' download is discarded and cannot install',async()=>{const f=await fixture();try{await f.service.check();f.mode(mode);const result=await f.service.download();assert.equal(result.phase,'error');assert.equal(result.error,error);assert.equal((await fs.readdir(f.folder)).filter(n=>n.startsWith('download-')).length,0);await assert.rejects(f.service.install(()=>true),/UPDATE_NOT_READY/);assert.equal(f.armed(),0);}finally{await f.close();}});
test('cancellation stops a live HTTP transfer, removes partial file, and allows retry',async()=>{const f=await fixture();try{await f.service.check();f.mode('slow');const active=f.service.download();await new Promise(resolve=>setTimeout(resolve,40));assert.throws(()=>f.service.check(),/UPDATE_BUSY/);f.service.cancel();assert.equal((await active).phase,'available');assert.equal((await fs.readdir(f.folder)).filter(n=>n.startsWith('download-')).length,0);f.mode('normal');assert.equal((await f.service.download()).phase,'ready');}finally{await f.close();}});
test('portable mode, changed installation and unsaved operation never arm installation',async()=>{const f=await fixture();try{await f.service.check();await f.service.download();await assert.rejects(f.service.install(()=>false),/UPDATE_UNSAVED/);f.installed(false);await assert.rejects(f.service.install(()=>true),/UPDATE_PORTABLE/);f.service.showDownload();assert.ok(f.calls.at(-1).endsWith('installer.exe'));assert.equal(f.armed(),0);}finally{await f.close();}});
test('session invalidation during helper handshake cancels only the unstarted helper',async()=>{const f=await fixture();try{await f.service.check();await f.service.download();let validations=0;await assert.rejects(f.service.install(()=>++validations===1),/UPDATE_UNSAVED/);assert.equal(f.cancelled(),1);assert.equal(f.service.state().phase,'ready');}finally{await f.close();}});
test('startup preserves verified live helper folders, cleans abandoned downloads and reads prior outcome',async()=>{const f=await fixture();try{await fs.mkdir(path.join(f.folder,'download-abandoned'));await fs.mkdir(path.join(f.folder,'download-live'));await fs.mkdir(path.join(f.folder,'download-completed'));await fs.writeFile(path.join(f.folder,'download-completed/result.json'),JSON.stringify({success:false,version:'0.25.0',reason:'UPDATE_INSTALL_1612'}));const service=new UpdateService({version:'0.24.0',directory:f.folder,installed:async()=>true,active:async p=>p.endsWith('download-live'),changed:()=>{},arm:async()=>()=>{},openFolder:()=>{}});const state=await service.init();assert.equal(state.previous.success,false);assert.equal(state.previous.reason,'UPDATE_INSTALL_1612');assert.equal(await fs.access(path.join(f.folder,'download-abandoned')).then(()=>true,()=>false),false);assert.equal(await fs.access(path.join(f.folder,'download-live')).then(()=>true,()=>false),true);}finally{await f.close();}});
