const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),net=require('node:net');
async function closed(port){return new Promise(resolve=>{const s=net.connect(port,'127.0.0.1');s.once('connect',()=>{s.destroy();resolve(false)});s.once('error',()=>resolve(true));});}
async function run(){const output=path.resolve('work/vault-ui');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),helperProfile=await fs.mkdtemp(path.join(output,'helper-'));const env={...process.env,CLIP_TEST_MODE:'1',CLIP_DATA_DIR:profile,CLIP_HELPER_PROFILE:helperProfile};delete env.ELECTRON_RUN_AS_NODE;
 const options=process.env.CLIP_PACKAGED_EXE?{executablePath:process.env.CLIP_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env};const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app,errors=[];
 const watch=p=>p.on('pageerror',e=>errors.push(e.message));
 try{await helper.firstWindow();app=await electron.launch(options);let page=await app.firstWindow();watch(page);await page.waitForSelector('#search');const fixture='规划、灵感与待办，都留在自己的电脑里 · vault-sentinel-'+Date.now();await helper.evaluate(({clipboard},text)=>clipboard.writeText(text),fixture);await expect.poll(async()=>(await page.evaluate(()=>window.clip.state())).clips.length).toBe(1);const id=(await page.evaluate(()=>window.clip.state())).clips[0].id;
 await page.evaluate(async id=>{await window.clip.action(id,'favorite');await window.clip.action(id,'enqueue');await window.clip.snippet({title:'工作回复',text:'你好，方案已更新，请查收。'});await window.clip.category({name:'日常灵感',kind:'text',contains:'',tag:'',source:'',color:'#7b8e9c'});await window.clip.syncConfigure({enabled:true,name:'加密测试',autoNew:false});await window.clip.webStart({host:'127.0.0.1',minutes:5,follow:false});await window.clip.webPublish(id);},id);
 const lanPort=(await page.evaluate(()=>window.clip.syncState())).port;await fs.writeFile(path.join(profile,'keep-me.txt'),'unrelated');
 console.log('Enable: password, recovery confirmation, actual Electron native cipher');await page.locator('[data-page=settings]').click();await page.locator('.settings-nav button').filter({hasText:'当前存储'}).click();await page.locator('#vault-enable').click();await page.locator('#vault-new-password').fill('first history fixture password');await page.locator('#vault-repeat-password').fill('first history fixture password');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#vault-recovery-key')).toBeVisible();const recovery=await page.locator('#vault-recovery-key').textContent();assert.match(recovery,/^C7-/);await page.locator('#vault-recovery-proof').fill('wrong-recovery');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#modal-error')).toContainText('完整恢复密钥');await page.locator('#vault-recovery-proof').fill(recovery);await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible({timeout:20000});
 const data=await page.evaluate(()=>window.clip.dataState()),vault=await page.evaluate(()=>window.clip.vaultState());assert.equal(vault.encrypted,true);assert.equal(vault.unlocked,true);assert.equal(vault.plaintextDirectory,profile);assert.equal((await page.evaluate(()=>window.clip.webState())).running,false);const state=await page.evaluate(()=>window.clip.state());assert.deepEqual(state.queue,[id]);assert.equal(state.snippets.length,1);assert.equal(state.categories.length,1);
 for(const suffix of ['','-wal']){const raw=await fs.readFile(path.join(data.directory,'history.sqlite'+suffix)).catch(()=>Buffer.alloc(0));assert.equal(raw.includes(Buffer.from(fixture)),false);assert.equal(raw.includes(Buffer.from(recovery)),false);}
 console.log('Cleanup: explicit verified removal and encrypted worker export');await page.locator('#vault-cleanup').click();await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible();assert.equal(await fs.readFile(path.join(profile,'keep-me.txt'),'utf8'),'unrelated');await assert.rejects(fs.stat(path.join(profile,'history.sqlite')),/ENOENT/);assert.equal((await page.evaluate(()=>window.clip.vaultState())).plaintextDirectory,'');
 const backup=path.join(output,path.basename(profile)+'.clip');await app.evaluate(({dialog},file)=>dialog.showSaveDialog=async()=>({canceled:false,filePath:file}),backup);await page.evaluate(()=>window.clip.exportProtected('independent backup fixture password'));assert.equal((await fs.readFile(backup)).includes(Buffer.from(fixture)),false);
 await page.evaluate(()=>window.clip.configureVault(false,15));await expect(page.locator('#toast')).not.toBeVisible({timeout:8000});await page.screenshot({path:path.join(output,'history-protection-light.png')});
 await page.evaluate(()=>window.clip.webStart({host:'127.0.0.1',minutes:5,follow:false}));const webPort=Number(new URL((await page.evaluate(()=>window.clip.webState())).origin).port);const windowEvent=app.waitForEvent('window');await page.locator('#vault-lock').click().catch(()=>{});let unlock=await windowEvent;watch(unlock);await expect(unlock.locator('#heading')).toHaveText('历史已锁定',{timeout:20000});await expect.poll(()=>page.isClosed()).toBe(true);assert.equal(await closed(webPort),true);assert.equal(await closed(lanPort),true);assert.equal(await unlock.evaluate(()=>typeof window.clip),'undefined');
 console.log('Lock: renderer destruction, IPC isolation, listeners stopped, no capture');const denial=await app.evaluate(async({ipcMain,BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('/unlock.html'));try{await ipcMain._invokeHandlers.get('clip:state')({sender:w.webContents,senderFrame:w.webContents.mainFrame});return 'allowed';}catch(e){return e.message;}});assert.match(denial,/锁定|拒绝/);
 await unlock.screenshot({path:path.join(output,'locked-history.png')});await unlock.locator('#unlock-value').fill('incorrect history password');await unlock.locator('#unlock-submit').click();await expect(unlock.locator('#feedback')).toContainText('密码不正确');await helper.evaluate(({clipboard})=>clipboard.writeText('Must not record while locked'));await unlock.screenshot({path:path.join(output,'locked-password.png')});await new Promise(r=>setTimeout(r,1600));
 console.log('Recovery: key unlock, rotate password, preserve content');await unlock.locator('#use-recovery').click();await unlock.locator('#unlock-value').fill(recovery);await unlock.locator('#new-password').fill('second history fixture password');await unlock.locator('#repeat-password').fill('second history fixture password');const nextWindow=app.waitForEvent('window');await unlock.locator('#unlock-submit').click();page=await nextWindow;watch(page);await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,1);assert.equal((await page.evaluate(()=>window.clip.state())).clips[0].id,id);await helper.evaluate(({clipboard})=>clipboard.writeText('重新解锁，继续记录'));await expect.poll(async()=>(await page.evaluate(()=>window.clip.state())).clips.length).toBe(2);
 console.log('System lock signal and restart require credentials');let locked=app.waitForEvent('window');await app.evaluate(({powerMonitor})=>powerMonitor.emit('lock-screen'));unlock=await locked;await expect(unlock.locator('#heading')).toHaveText('历史已锁定');await app.close();app=await electron.launch(options);unlock=await app.firstWindow();await expect(unlock.locator('#heading')).toHaveText('历史已锁定');await unlock.locator('#unlock-value').fill('first history fixture password');await unlock.locator('#unlock-submit').click();await expect(unlock.locator('#feedback')).toContainText('密码不正确');await new Promise(r=>setTimeout(r,1600));await unlock.locator('#unlock-value').fill('second history fixture password');const reopened=app.waitForEvent('window');await unlock.locator('#unlock-submit').click();page=await reopened;watch(page);await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,2);await page.evaluate(async()=>{const s=await window.clip.state();await window.clip.settings({...s.settings,theme:'dark'});});await page.locator('[data-page=settings]').click();await page.locator('.settings-nav button').filter({hasText:'当前存储'}).click();await expect(page.locator('#vault-lock')).toBeVisible();await expect(page.locator('#toast')).not.toBeVisible({timeout:8000});await page.screenshot({path:path.join(output,'history-protection-dark.png')});assert.deepEqual(errors,[]);
 console.log('Turn off encryption: verified plaintext copy, original encrypted directory kept, restart opens directly');await page.locator('#vault-disable').click();await expect(page.locator('#dialog')).toBeVisible();await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).not.toBeVisible({timeout:20000});const plain=await page.evaluate(()=>window.clip.dataState());assert.notEqual(plain.directory,data.directory);assert.equal((await page.evaluate(()=>window.clip.vaultState())).encrypted,false);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,2);assert.equal((await fs.readFile(path.join(data.directory,'history-vault.json'),'utf8')).includes('chacha20'),true);await app.close();app=await electron.launch(options);page=await app.firstWindow();watch(page);await page.waitForSelector('#search');assert.equal((await page.evaluate(()=>window.clip.vaultState())).encrypted,false);assert.equal((await page.evaluate(()=>window.clip.state())).clips.length,2);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIP_PACKAGED_EXE,actualCipherInElectron:true,encryptedWorkerBackup:true,oldPlaintextRemoved:true,lockDestroysHistoryWindow:true,ipcDeniedWhileLocked:true,networkClosed:true,capturePaused:true,recoveryKeyAndPasswordRotation:true,systemLockSignal:true,restartLocked:true,decryptionPreservesHistory:true,oldEncryptedCopyRetained:true,helloAvailability:vault.helloAvailable,helloPromptTested:false,profile,directory:data.directory,output},null,2));
 }finally{if(app)await app.close();await helper.evaluate(async({clipboard})=>global.restoreClipboard());await helper.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
