// Production renderer bundles; headless browser input and synthetic IPC only.
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup}=require('./renderer-fixture.cjs'),{setupData}=require('./language-data-fixture.cjs');
function features(){
 const base=window.clip;fixture.featureCalls=[];fixture.state.queue=['text','text','image'];fixture.state.stack.options.duplicates=true;fixture.sync.autoFiles=false;
 const overrides={stackState:async()=>fixture.state.stack,queueAction:async(index,id,action,expected)=>{fixture.featureCalls.push(['queueAction',index,id,action,expected]);if(JSON.stringify(expected)!==JSON.stringify(fixture.state.queue))throw Error('Stale fixture queue');const queue=[...expected];if(action==='dequeue')queue.splice(index,1);else{const next=index+(action==='up'?-1:1);if(next>=0&&next<queue.length)[queue[index],queue[next]]=[queue[next],queue[index]];}fixture.state.queue=queue;fixture.refresh();},configureStack:async value=>{fixture.state.stack.options=value;fixture.featureCalls.push(['stack',value]);fixture.refresh();},contentInfo:async()=>({formats:[],files:[{name:'encrypted.pdf',path:'D:\\fixture\\encrypted.pdf',type:'.pdf',status:'not-read'}]}),metadata:async value=>{fixture.featureCalls.push(['metadata',value]);return {name:'encrypted.pdf',size:100,category:'pdf',fields:[{key:'pages',value:'30'}]};}};
 window.clip=new Proxy(overrides,{get:(obj,key)=>key in obj?obj[key]:base[key]});
}
async function route(context){await context.route('https://clip.test/**',async r=>{const name=new URL(r.request().url()).pathname.slice(1);if(!/^[\w.-]+$/.test(name))return r.abort();try{await r.fulfill({body:await fs.readFile(path.join('dist/renderer',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});}catch{return r.abort();}});}
(async()=>{await fs.mkdir('work/version-027',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],results=[];try{for(const language of ['zh-CN','en'])for(const theme of ['light','dark']){
 const context=await browser.newContext({viewport:{width:1240,height:780},colorScheme:theme});await context.addInitScript(setup,language);await context.addInitScript(setupData);await context.addInitScript(features);await context.addInitScript(theme=>fixture.state.dark=theme==='dark',theme);await route(context);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('https://clip.test/index.html');await page.waitForSelector('#copy');
 await page.locator('[data-page=stack]').click();assert.equal(await page.locator('.clip-row').count(),3);await page.locator('[data-queue-index="1"]').click();assert.equal(await page.locator('.clip-row.selected').count(),1);await page.evaluate(()=>fixture.refresh());await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>document.activeElement.dataset.queueIndex),'1');await page.locator('.detail-more summary').click();await page.locator('#queue-down').click();await page.waitForTimeout(90);assert.deepEqual(await page.evaluate(()=>fixture.state.queue),['text','image','text']);assert.equal(await page.locator('.clip-row.selected').getAttribute('data-queue-index'),'2');await page.locator('.detail-more summary').click();await page.locator('#dequeue').click();await page.waitForTimeout(90);assert.deepEqual(await page.evaluate(()=>fixture.state.queue),['text','image']);assert.equal(await page.evaluate(()=>fixture.featureCalls.filter(x=>x[0]==='queueAction').length),2);
 await page.locator('#stack-rules').click();assert.equal(await page.locator('#stack-duplicates').isChecked(),true);await page.locator('#stack-duplicates').uncheck();await page.locator('#dialog [type=submit]').click();await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>fixture.state.stack.options.duplicates),false);assert.equal(await page.locator('.clip-row').count(),2);
 await page.locator('[data-page=sync]').click();await page.waitForSelector('#sync-auto-files');assert.equal(await page.locator('#sync-auto-files').isChecked(),false);assert.equal(await page.locator('[data-share=files]').textContent(),language==='en'?'Share file copies':'共享文件副本');await page.locator('#sync-auto-files').check();await page.locator('#sync-save').click();await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>fixture.sync.autoFiles),true);
 await page.locator('[data-page=history]').click();await page.locator('[data-id=files]').click();await page.locator('.detail-more summary').click();await page.locator('#content-info').click();await page.waitForSelector('#metadata-tab');await page.locator('#metadata-tab').click();assert.equal(await page.locator('#metadata-password').getAttribute('type'),'password');await page.locator('#metadata-password').fill('fixture-open-password');await page.locator('#metadata-read').click();await page.waitForTimeout(60);assert.equal(await page.locator('#metadata-password').inputValue(),'');assert.equal(await page.evaluate(()=>fixture.featureCalls.find(x=>x[0]==='metadata')[1].password),'fixture-open-password');assert.match(await page.locator('#metadata-values').textContent(),/30/);
 for(const [width,height,scale]of [[1240,780,100],[840,780,100],[840,600,150]]){await page.setViewportSize({width,height});await page.evaluate(scale=>fixture.appearance({font:'system',scale,density:'comfortable'}),scale);assert.equal(await page.evaluate(()=>document.body.scrollWidth<=innerWidth+1),true);const bounds=await page.locator('#metadata-password').boundingBox();assert(bounds.width>100&&bounds.x>=0&&bounds.x+bounds.width<=width);results.push({language,theme,width,height,scale,passwordLayout:true});}
 if(language==='zh-CN'&&theme==='light')await page.screenshot({path:'work/version-027/metadata-preview.png'});await page.locator('#modal-close').click();await page.setViewportSize({width:1240,height:780});await page.evaluate(()=>fixture.appearance({font:'system',scale:100,density:'comfortable'}));await page.locator('[data-page=stack]').click();if(language==='zh-CN'&&theme==='light')await page.screenshot({path:'work/version-027/stack-preview.png'});await context.close();
 }assert.deepEqual(errors,[]);await fs.writeFile('work/version-027/ui-results.json',JSON.stringify({passed:true,scope:'Headless production renderer; no system input or clipboard',cases:results.length,errors,results},null,2));console.log(JSON.stringify({passed:true,cases:results.length,errors}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={route};
