using System;using System.IO;using System.Text;using System.Threading;using System.Runtime.InteropServices;using System.Runtime.InteropServices.ComTypes;using System.Collections.Generic;using System.Web.Script.Serialization;using System.Windows.Forms;
using IDataObject=System.Runtime.InteropServices.ComTypes.IDataObject;
using STATSTG=System.Runtime.InteropServices.ComTypes.STATSTG;
[ComVisible(true),ClassInterface(ClassInterfaceType.None)]
public sealed class VirtualAttachmentData:IDataObject {
 public sealed class Entry{public string name;public string data;public string type;public long? declared;public uint? attributes;}
 public Entry[] entries;public bool wide;public int delay;public bool fail;public bool privateHistory;
 [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern uint RegisterClipboardFormat(string value);
 [DllImport("kernel32.dll")] static extern IntPtr GlobalAlloc(uint flags,UIntPtr bytes);
 [DllImport("kernel32.dll")] static extern IntPtr GlobalLock(IntPtr handle);
 [DllImport("kernel32.dll")] static extern bool GlobalUnlock(IntPtr handle);
 [DllImport("ole32.dll")] static extern int CreateStreamOnHGlobal(IntPtr memory,bool release,out IStream stream);
 static IntPtr Global(byte[] bytes){var h=GlobalAlloc(0x42,new UIntPtr((uint)Math.Max(1,bytes.Length)));var p=GlobalLock(h);Marshal.Copy(bytes,0,p,bytes.Length);GlobalUnlock(h);return h;}
 static IntPtr Pointer(object value,string iid){var u=Marshal.GetIUnknownForObject(value);try{IntPtr p;var id=new Guid(iid);Marshal.ThrowExceptionForHR(Marshal.QueryInterface(u,ref id,out p));return p;}finally{Marshal.Release(u);}}
 static void Put(byte[] output,int offset,byte[] value){Array.Copy(value,0,output,offset,value.Length);}
 public void GetData(ref FORMATETC format,out STGMEDIUM medium){medium=new STGMEDIUM();uint id=unchecked((ushort)format.cfFormat);if(id==RegisterClipboardFormat(wide?"FileGroupDescriptorW":"FileGroupDescriptor")){int stride=wide?592:332;var bytes=new byte[4+stride*entries.Length];Put(bytes,0,BitConverter.GetBytes(entries.Length));for(int i=0;i<entries.Length;i++){int at=4+i*stride;var e=entries[i];uint flags=4|8|16|32;if(e.type!="storage"||e.declared.HasValue)flags|=64;Put(bytes,at,BitConverter.GetBytes(flags));Put(bytes,at+36,BitConverter.GetBytes(e.attributes??32));long time=new DateTime(2024,3,2,4,5,6,DateTimeKind.Utc).ToFileTimeUtc();foreach(int offset in new[]{40,48,56})Put(bytes,at+offset,BitConverter.GetBytes(time));long length=e.declared??Convert.FromBase64String(e.data??"").Length;Put(bytes,at+64,BitConverter.GetBytes((uint)((ulong)length>>32)));Put(bytes,at+68,BitConverter.GetBytes((uint)length));byte[] name=(wide?Encoding.Unicode:Encoding.Default).GetBytes(e.name+"\0");Array.Copy(name,0,bytes,at+72,Math.Min(name.Length,stride-72));}medium.tymed=TYMED.TYMED_HGLOBAL;medium.unionmember=Global(bytes);return;}
  if(id==RegisterClipboardFormat("CanIncludeInClipboardHistory")&&privateHistory){medium.tymed=TYMED.TYMED_HGLOBAL;medium.unionmember=Global(new byte[4]);return;}
  if(id!=RegisterClipboardFormat("FileContents")||format.lindex<0||format.lindex>=entries.Length)throw new COMException("Format unavailable",unchecked((int)0x80040064));Console.WriteLine("{\"reading\":true}");if(delay>0)Thread.Sleep(delay);if(fail)throw new COMException("Fixture failure",unchecked((int)0x80004005));var entry=entries[format.lindex];if(((entry.attributes??32)&16)!=0)throw new COMException("Directory content must not be requested",unchecked((int)0x80004005));var content=Convert.FromBase64String(entry.data??"");
  if(entry.type=="storage"){var bytes=new BoundedAttachmentBytes(12*1024*1024);IAttachmentStorage storage;Marshal.ThrowExceptionForHR(AttachmentHost.StgCreateDocfileOnILockBytes(bytes,0x1012,0,out storage));try{var clsid=new Guid("dd402312-477b-4e04-a4a9-5ea9e5126507");storage.SetClass(ref clsid);IStream stream;storage.CreateStream("body.txt",0x1012,0,0,out stream);stream.Write(content,content.Length,IntPtr.Zero);stream.Commit(0);Marshal.ReleaseComObject(stream);IAttachmentStorage nested;storage.CreateStorage("Nested",0x1012,0,0,out nested);nested.CreateStream("binary",0x1012,0,0,out stream);byte[] marker=new byte[]{0,255,31,128,10};stream.Write(marker,marker.Length,IntPtr.Zero);stream.Commit(0);Marshal.ReleaseComObject(stream);nested.Commit(0);Marshal.ReleaseComObject(nested);storage.Commit(0);medium.tymed=TYMED.TYMED_ISTORAGE;medium.unionmember=Pointer(storage,"0000000B-0000-0000-C000-000000000046");}finally{Marshal.ReleaseComObject(storage);}return;}
  if(entry.type=="stream"){IStream stream;Marshal.ThrowExceptionForHR(CreateStreamOnHGlobal(IntPtr.Zero,true,out stream));try{stream.Write(content,content.Length,IntPtr.Zero);stream.Seek(0,0,IntPtr.Zero);medium.tymed=TYMED.TYMED_ISTREAM;medium.unionmember=Pointer(stream,"0000000C-0000-0000-C000-000000000046");}finally{Marshal.ReleaseComObject(stream);}return;}
  medium.tymed=TYMED.TYMED_HGLOBAL;medium.unionmember=Global(content);
 }
 public int QueryGetData(ref FORMATETC f){uint id=unchecked((ushort)f.cfFormat);return id==RegisterClipboardFormat(wide?"FileGroupDescriptorW":"FileGroupDescriptor")||id==RegisterClipboardFormat("FileContents")||privateHistory&&id==RegisterClipboardFormat("CanIncludeInClipboardHistory")?0:unchecked((int)0x80040064);}
 public IEnumFORMATETC EnumFormatEtc(DATADIR direction){var values=new List<FORMATETC>{new FORMATETC{cfFormat=unchecked((short)RegisterClipboardFormat(wide?"FileGroupDescriptorW":"FileGroupDescriptor")),dwAspect=DVASPECT.DVASPECT_CONTENT,lindex=-1,tymed=TYMED.TYMED_HGLOBAL},new FORMATETC{cfFormat=unchecked((short)RegisterClipboardFormat("FileContents")),dwAspect=DVASPECT.DVASPECT_CONTENT,lindex=-1,tymed=TYMED.TYMED_HGLOBAL|TYMED.TYMED_ISTREAM|TYMED.TYMED_ISTORAGE}};if(privateHistory)values.Add(new FORMATETC{cfFormat=unchecked((short)RegisterClipboardFormat("CanIncludeInClipboardHistory")),dwAspect=DVASPECT.DVASPECT_CONTENT,lindex=-1,tymed=TYMED.TYMED_HGLOBAL});return new VirtualFormatEnum(values.ToArray());}
 public void GetDataHere(ref FORMATETC f,ref STGMEDIUM m){throw new NotImplementedException();}public int GetCanonicalFormatEtc(ref FORMATETC a,out FORMATETC b){b=a;b.ptd=IntPtr.Zero;return unchecked((int)0x80004001);}public void SetData(ref FORMATETC f,ref STGMEDIUM m,bool release){throw new NotImplementedException();}public int DAdvise(ref FORMATETC f,ADVF flags,IAdviseSink sink,out int connection){connection=0;return unchecked((int)0x80040003);}public void DUnadvise(int connection){}public int EnumDAdvise(out IEnumSTATDATA data){data=null;return unchecked((int)0x80040003);}
}
[ComVisible(true),ClassInterface(ClassInterfaceType.None)]public sealed class VirtualFormatEnum:IEnumFORMATETC{readonly FORMATETC[] values;int at;public VirtualFormatEnum(FORMATETC[] f){values=f;}public int Next(int count,FORMATETC[] output,int[] fetched){int n=0;while(n<count&&at<values.Length)output[n++]=values[at++];if(fetched!=null)fetched[0]=n;return n==count?0:1;}public int Skip(int count){at=Math.Min(values.Length,at+count);return at<values.Length?0:1;}public int Reset(){at=0;return 0;}public void Clone(out IEnumFORMATETC result){result=new VirtualFormatEnum(values){at=at};}}
internal static class VirtualAttachmentFixture {
 [DllImport("ole32.dll")] static extern int OleInitialize(IntPtr p);[DllImport("ole32.dll")] static extern void OleUninitialize();[DllImport("ole32.dll")] static extern int OleSetClipboard(IDataObject value);
 [DllImport("ole32.dll")] static extern int OleIsCurrentClipboard(IDataObject value);
 [DllImport("ole32.dll")] static extern int StgOpenStorageOnILockBytes(IBoundedLockBytes bytes,IAttachmentStorage priority,uint mode,IntPtr exclude,uint reserved,out IAttachmentStorage storage);
 [DllImport("user32.dll")] static extern uint GetClipboardSequenceNumber();
 public sealed class Request{public string id;public string action;public VirtualAttachmentData.Entry[] entries;public bool wide=true;public int delay;public bool fail;public bool privateHistory;public string data;public string path;}
 static FileStream held;static VirtualAttachmentData current;static Control owner;static JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=20*1024*1024};
 static string StreamData(IAttachmentStorage storage,string name){IStream stream;storage.OpenStream(name,IntPtr.Zero,0x10,0,out stream);try{STATSTG stat;stream.Stat(out stat,1);if(stat.cbSize>12*1024*1024)throw new Exception("Fixture data too large");var bytes=new byte[(int)stat.cbSize];stream.Read(bytes,bytes.Length,IntPtr.Zero);return Convert.ToBase64String(bytes);}finally{Marshal.ReleaseComObject(stream);}}
 static void Process(Request r){try{if(r.action=="quit"){if(current!=null&&OleIsCurrentClipboard(current)==0)OleSetClipboard(null);Console.WriteLine(json.Serialize(new{id=r.id,ok=true}));Application.ExitThread();return;}if(r.action=="inspect"){byte[] input=Convert.FromBase64String(r.data);var bytes=new BoundedAttachmentBytes(12*1024*1024);var p=Marshal.AllocHGlobal(input.Length);try{Marshal.Copy(input,0,p,input.Length);bytes.WriteAt(0,p,(uint)input.Length,IntPtr.Zero);}finally{Marshal.FreeHGlobal(p);}IAttachmentStorage storage;Marshal.ThrowExceptionForHR(StgOpenStorageOnILockBytes(bytes,null,0x10,IntPtr.Zero,0,out storage));try{STATSTG stat;storage.Stat(out stat,1);var body=StreamData(storage,"body.txt");IAttachmentStorage nested;storage.OpenStorage("Nested",null,0x10,IntPtr.Zero,0,out nested);try{Console.WriteLine(json.Serialize(new{id=r.id,body=body,nested=StreamData(nested,"binary"),clsid=stat.clsid.ToString()}));}finally{Marshal.ReleaseComObject(nested);}}finally{Marshal.ReleaseComObject(storage);}return;}
  if(r.action=="hold"){held=new FileStream(r.path,FileMode.Open,FileAccess.Read,FileShare.None);Console.WriteLine(json.Serialize(new{id=r.id,ok=true}));return;}if(r.action=="release"){held.Dispose();held=null;Console.WriteLine(json.Serialize(new{id=r.id,ok=true}));return;}
  current=new VirtualAttachmentData{entries=r.entries,wide=r.wide,delay=r.delay,fail=r.fail,privateHistory=r.privateHistory};Marshal.ThrowExceptionForHR(OleSetClipboard(current));Console.WriteLine(json.Serialize(new{id=r.id,sequence=GetClipboardSequenceNumber()}));
 }catch(Exception e){Console.WriteLine(json.Serialize(new{id=r.id,error=e.Message}));}}
 [STAThread]static void Main(){Console.InputEncoding=new UTF8Encoding(false);Console.OutputEncoding=new UTF8Encoding(false);OleInitialize(IntPtr.Zero);owner=new Control();var handle=owner.Handle;var reader=new Thread(()=>{string line;while((line=Console.ReadLine())!=null){var r=json.Deserialize<Request>(line);owner.BeginInvoke(new Action(()=>Process(r)));}owner.BeginInvoke(new Action(()=>{if(current!=null&&OleIsCurrentClipboard(current)==0)OleSetClipboard(null);Application.ExitThread();}));});reader.IsBackground=true;reader.Start();Console.WriteLine("{\"ready\":true}");Application.Run();OleUninitialize();}
}
