const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),crypto=require('node:crypto');
fs.mkdirSync('work/visibility-040',{recursive:true});const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;delete env.CLIPPER_VISIBILITY_ASAR;
execFileSync(require('electron'),['tests/visibility-040-host.cjs','after','0'],{env,stdio:'inherit',windowsHide:true,timeout:60000});
const samples=[];for(let round=1;round<=3;round++)for(const mode of round%2?['before','after']:['after','before']){execFileSync(require('electron'),['tests/visibility-040-host.cjs',mode,String(round)],{env,stdio:'inherit',windowsHide:true,timeout:60000});samples.push(JSON.parse(fs.readFileSync('work/visibility-040/'+mode+'-'+round+'.json')));}
const mean=values=>values.reduce((a,b)=>a+b,0)/values.length,summary=mode=>{const all=samples.filter(s=>s.mode===mode),rows={};for(const key of ['imageShown','imageHidden','textShown','textHidden'])rows[key]={imageLiveMiB:mean(all.map(s=>s.resources[key].images.liveSize))/1048576,heapMiB:mean(all.map(s=>s.resources[key].heap.usedSize))/1048576,privateMiB:mean(all.map(s=>s.resources[key].memory.privateBytes))/1024,workingSetMiB:mean(all.map(s=>s.resources[key].memory.workingSetSize))/1024};return rows;};
for(const s of samples){assert(s.passed&&s.hidden);if(s.mode==='after'){assert.equal(s.resources.imageHidden.images.liveSize,0);assert.equal(s.resources.textHidden.dom.readers,0);assert.equal(s.resources.textHidden.dom.workers,0);}else{assert.equal(s.resources.imageHidden.images.liveSize,4096*4096*4);assert.equal(s.resources.imageHidden.dom.images,1);assert.equal(s.resources.textHidden.dom.readers,1);}}
const behavior=JSON.parse(fs.readFileSync('work/visibility-040/after-0.json'));assert.equal(behavior.cases.length,14);assert(behavior.passed);
const reference='D:/Repositories/One/src/renderer/window-visibility.ts',source=fs.readFileSync(reference),baseline=path.resolve('../delivery-0.39.0/release/0.39.0/win-unpacked/resources/app.asar');
const result={passed:true,version:'0.40.0',behaviorCases:14,rounds:3,summary:{before:summary('before'),after:summary('after')},samples,behavior,reference:{path:reference,sha256:crypto.createHash('sha256').update(source).digest('hex'),version:JSON.parse(fs.readFileSync('D:/Repositories/One/package.json')).version},baseline:{version:'0.39.0',path:baseline,sha256:crypto.createHash('sha256').update(fs.readFileSync(baseline)).digest('hex')},scope:'Three alternating private, physically hidden offscreen renderer pairs. Visibility and IPC are emulated; real production assets, worker, sandbox and resource counters are used. GC forced equally; renderer memory only. Synthetic image/text; no physical input or daily history.'};
fs.writeFileSync('work/visibility-040/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({passed:true,behaviorCases:14,rounds:3,summary:result.summary}));
