const {test}=require('node:test'),assert=require('node:assert/strict'),https=require('node:https'),{randomUUID,X509Certificate}=require('node:crypto'),path=require('node:path');
const {Store,WebShareService,SyncService}=require('../work/test-exports.cjs');
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jG1sAAAAASUVORK5CYII=';
async function fixture(enqueue=fn=>Promise.resolve().then(fn)){let now=Date.now();const store=new Store(':memory:'),service=new WebShareService(()=>store,()=>{},enqueue,p=>p.png?'data:image/png;base64,'+p.png:undefined,path.resolve('dist/web'),{addresses:()=>['127.0.0.1'],now:()=>now});store.onChange=(p,n)=>service.observe(p,n);await service.start({host:'127.0.0.1',minutes:5,follow:false});const origin=service.state().origin;
 function request(route,body,token,headers={}){return new Promise((resolve,reject)=>{const req=https.request(origin+route,{rejectUnauthorized:false,method:body===undefined?'GET':'POST',headers:{Origin:origin,...(body===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{}),...headers}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{const data=Buffer.concat(chunks),raw=data.toString();let value;try{value=JSON.parse(raw);}catch{value=raw;}resolve({status:res.statusCode,headers:res.headers,value,data});});});req.on('error',reject);if(body!==undefined)req.write(JSON.stringify(body));req.end();});}
 async function connect(send=false){const invite=new URL(service.invite()).hash.slice('#clipper-web='.length),response=await request('/api/connect',{invite,name:'浏览器',verified:true});assert.equal(response.status,200);const id=service.state().clients.find(c=>c.code===response.value.code).id;service.approve(id,true,send);return {id,...response.value};}
 return {store,service,origin,request,connect,advance:ms=>{now+=ms;},close:async()=>{await service.stop();store.close();}};
}
test('web certificate has selected IP SAN; invite requires host/origin, verification, approval and one-time token',async()=>{const f=await fixture();try{const cert=new X509Certificate(f.service.server._sharedCreds.context.getCertificate());assert.equal(cert.checkIP('127.0.0.1'),'127.0.0.1');assert.equal(cert.fingerprint256.replaceAll(':','').toLowerCase(),f.service.state().fingerprint);const clip=f.store.add({text:'visible after approval'},'fixture');f.service.publish(clip.id);const invite=new URL(f.service.state().invitation).hash.slice('#clipper-web='.length);
 assert.equal((await f.request('/api/state')).status,403);assert.equal((await f.request('/api/connect',{invite,name:'browser',verified:true},null,{Host:'evil.test'})).status,403);assert.equal((await f.request('/api/connect',{invite,name:'browser',verified:true},null,{Origin:'https://evil.test'})).status,403);assert.equal((await f.request('/api/connect',{invite,name:'browser',verified:false})).status,403);
 const pending=await f.request('/api/connect',{invite,name:'browser',verified:true});assert.equal(pending.status,200);const before=await f.request('/api/state',undefined,pending.value.token);assert.equal(before.value.approved,false);assert.deepEqual(before.value.items,[]);assert.equal((await f.request('/api/item/'+f.service.state().items[0].id,undefined,pending.value.token)).status,403);assert.equal((await f.request('/api/connect',{invite,name:'replay',verified:true})).status,403);const id=f.service.state().clients[0].id;f.service.approve(id,true,false);assert.equal((await f.request('/api/state',undefined,pending.value.token)).value.items.length,1);assert.equal(JSON.stringify(f.service.state()).includes(pending.value.token),false);assert.equal(JSON.stringify(f.store.backup()).includes('PRIVATE KEY'),false);
 }finally{await f.close();}});
test('web scope exposes only selected plain text and PNG, never local history IDs, HTML, files, invitations or private records',async()=>{const f=await fixture();try{const c=await f.connect(),rich=f.store.add({text:'<script>alert(1)</script>',html:'<img src=x onerror=alert(2)>'},'Secret process.exe'),hidden=f.store.add({text:'hidden'},'fixture'),image=f.store.add({png},'fixture');f.service.publish(rich.id);f.service.publish(image.id);const list=(await f.request('/api/state',undefined,c.token)).value.items;assert.equal(list.length,2);assert.equal(JSON.stringify(list).includes('Secret process'),false);assert.equal((await f.request('/api/item/'+hidden.id,undefined,c.token)).status,404);assert.equal((await f.request('/api/item/'+list[0].id,undefined,c.token)).value.text,rich.payload.text);assert.equal((await f.request('/api/item/'+list[0].id,undefined,c.token)).value.html,undefined);assert.equal((await f.request('/api/item/'+list[1].id,undefined,c.token)).data.toString('base64'),png);
 for(const payload of [{files:['C:\\secret.txt']},{text:'https://127.0.0.1:54321/#clipper-web=secret'}])assert.throws(()=>f.service.publish(f.store.add(payload,'fixture').id),/不能共享/);const privateItem=f.store.add({text:'private'},'fixture');privateItem.localOnly=true;f.store.save(privateItem);assert.throws(()=>f.service.publish(privateItem.id),/不能共享/);assert.equal((await f.request('/../package.json',undefined,c.token)).status,404);
 }finally{await f.close();}});
test('web withdrawals follow edits, deletes, privacy and raw pruning, but rollbacks keep the original publication',async()=>{const f=await fixture();try{const c=await f.connect(),clip=f.store.add({text:'original'},'fixture');f.service.publish(clip.id);const id=f.service.state().items[0].id;f.store.db.exec('BEGIN');f.store.edit(clip.id,'rolled back',[]);f.store.db.exec('ROLLBACK');await Promise.resolve();assert.equal(f.service.state().items.length,1);f.store.edit(clip.id,'edited',[]);await Promise.resolve();assert.equal(f.service.state().items.length,0);assert.equal((await f.request('/api/item/'+id,undefined,c.token)).status,404);
 f.service.publish(clip.id);const privateItem=f.store.get(clip.id);privateItem.localOnly=true;f.store.save(privateItem);await Promise.resolve();assert.equal(f.service.state().items.length,0);privateItem.localOnly=false;f.store.save(privateItem);f.service.publish(clip.id);f.store.clear();f.service.reconcile();assert.equal(f.service.state().items.length,0);
 }finally{await f.close();}});
test('send role, idempotency, bounded payload and local-only dedup preserve existing sharing flags',async()=>{const f=await fixture();try{const reader=await f.connect();assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'blocked'}},reader.token)).status,403);assert.equal(f.store.list().length,0);const sender=await f.connect(true),body={requestId:randomUUID(),payload:{text:'from browser'}};assert.equal((await f.request('/api/send',body,sender.token)).status,200);assert.equal((await f.request('/api/send',body,sender.token)).status,200);assert.equal(f.store.list().length,1);assert.equal(f.store.list()[0].localOnly,true);assert.equal((await f.request('/api/send',{...body,payload:{text:'changed'}},sender.token)).status,409);
 const preexisting=f.store.add({text:'already shared'},'fixture');preexisting.shared=true;f.store.save(preexisting);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'already shared'}},sender.token)).status,200);assert.equal(f.store.get(preexisting.id).shared,true);assert.equal(f.store.get(preexisting.id).localOnly,undefined);
 for(const payload of [{files:['C:\\secret']},{text:'x',html:'<b>x</b>'},{text:'x'.repeat(1024*1024+1)}])assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload},sender.token)).status,400);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{png}},sender.token)).status,200);assert.equal(f.store.list().find(c=>c.kind==='image').localOnly,true);
 }finally{await f.close();}});
test('revocation while a send waits for the database queue prevents the write',async()=>{let queued;const f=await fixture(fn=>new Promise((resolve,reject)=>{queued=()=>{try{resolve(fn());}catch(e){reject(e);}};}));try{const c=await f.connect(true),pending=f.request('/api/send',{requestId:randomUUID(),payload:{text:'must not persist'}},c.token);while(!queued)await new Promise(r=>setTimeout(r,10));f.service.revoke(c.id);queued();assert.equal((await pending).status,403);assert.equal(f.store.list().length,0);}finally{await f.close();}});
test('real event stream announces changes and closes on revocation; expiry and restart discard session state',async()=>{const f=await fixture();let request;try{const c=await f.connect();const chunks=[];await new Promise((resolve,reject)=>{request=https.get(f.origin+'/api/events',{rejectUnauthorized:false,headers:{Authorization:'Bearer '+c.token}},res=>{res.on('data',v=>{chunks.push(v.toString());resolve();});res.on('error',()=>{});});request.on('error',reject);});const clip=f.store.add({text:'live'},'fixture');f.service.publish(clip.id);await new Promise(r=>setTimeout(r,250));assert.ok(chunks.join('').match(/event: changed/g).length>=2);f.service.revoke(c.id);await new Promise(r=>setTimeout(r,30));assert.ok(chunks.join('').includes('event: closed'));assert.equal((await f.request('/api/state',undefined,c.token)).status,403);
 f.advance(301000);assert.equal(f.service.state().running,false);await f.service.start({host:'127.0.0.1',minutes:5,follow:false});assert.equal(f.service.state().clients.length,0);assert.equal(f.service.state().items.length,0);assert.equal(f.service.state().follow,false);
 }finally{request?.destroy();await f.close();}});
test('follow capture respects private records and invitations; sync observer composition keeps LAN and web privacy aligned',async()=>{const f=await fixture();const vault={available:async()=>true,encrypt:async s=>s,decrypt:async s=>s},sync=new SyncService(()=>f.store,vault,()=>{},fn=>Promise.resolve().then(fn),undefined,{discovery:false,afterMutation:(p,n)=>f.service.observe(p,n)});try{f.service.setFollow(true);const clip=f.store.add({text:'new capture'},'fixture');f.service.capture(clip);assert.equal(f.service.state().items.length,1);sync.local(clip.id,true);await Promise.resolve();assert.equal(f.service.state().items.length,0);f.service.capture(f.store.get(clip.id));assert.equal(f.service.state().items.length,0);const invite=f.store.add({text:f.service.state().invitation},'fixture');sync.capture(invite);assert.equal(f.store.get(invite.id).localOnly,true);f.service.capture(f.store.get(invite.id));assert.equal(f.service.state().items.length,0);}finally{await sync.stop();await f.close();}});
test('capacity, request rate, idle expiry and invalid start options are bounded',async()=>{const f=await fixture();try{for(let i=0;i<4;i++)await f.connect();const invite=new URL(f.service.invite()).hash.slice('#clipper-web='.length),pending=await f.request('/api/connect',{invite,name:'fifth',verified:true});const p=f.service.state().clients.find(c=>c.code===pending.value.code);assert.throws(()=>f.service.approve(p.id,true,false),/最多/);f.service.approve(p.id,false,false);assert.equal((await f.request('/api/state',undefined,pending.value.token)).status,403);
 for(let i=0;i<100;i++)f.service.publish(f.store.add({text:'item '+i},'fixture').id);assert.throws(()=>f.service.publish(f.store.add({text:'overflow'},'fixture').id),/100/);f.advance(91000);assert.equal(f.service.state().clients.length,0);await f.service.stop();await assert.rejects(()=>f.service.start({host:'8.8.8.8',minutes:30,follow:false}));await assert.rejects(()=>f.service.start({host:'127.0.0.1',minutes:121,follow:false}));}finally{await f.close();}});
test('upload rate resets after a minute, invalid JSON and image dimensions never enter history',async()=>{const f=await fixture();try{const c=await f.connect(true);for(let i=0;i<10;i++)assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'bounded '+i}},c.token)).status,200);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'over limit'}},c.token)).status,429);assert.equal(f.store.list().length,10);f.advance(61000);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'next minute'}},c.token)).status,200);const large=Buffer.from(png,'base64');large.writeUInt32BE(20000,16);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{png:large.toString('base64')}},c.token)).status,400);assert.equal((await f.request('/api/send','not an object',c.token)).status,400);assert.equal((await f.request('/api/send',{requestId:randomUUID(),payload:{text:'bad media'}},c.token,{'Content-Type':'text/plain'})).status,415);assert.equal((await f.request('/api/send',{requestId:[randomUUID()],payload:{text:'array identifier'}},c.token)).status,400);assert.equal(f.store.list().length,11);}finally{await f.close();}});
test('stopping during asynchronous certificate creation cannot revive a listener',async()=>{const f=await fixture();try{await f.service.stop();const start=f.service.start({host:'127.0.0.1',minutes:30,follow:false});const rejected=assert.rejects(()=>start,/已取消/);await f.service.stop();await rejected;assert.equal(f.service.state().running,false);assert.equal(f.service.state().invitation,'');assert.equal(f.service.sockets.size,0);}finally{await f.close();}});

test('PNG sharing removes original metadata without changing local history',async()=>{const f=await fixture();try{const original=Buffer.from(png,'base64'),comment=Buffer.from('Comment\0private PNG metadata'),chunk=Buffer.alloc(comment.length+12);chunk.writeUInt32BE(comment.length);chunk.write('tEXt',4);comment.copy(chunk,8);chunk.writeUInt32BE(require('node:zlib').crc32(chunk.subarray(4,-4)),chunk.length-4);const source=Buffer.concat([original.subarray(0,-12),chunk,original.subarray(-12)]).toString('base64'),clip=f.store.add({png:source,formats:[{name:'Rich Text Format',data:Buffer.from('private raw format').toString('base64')}]},'fixture'),c=await f.connect();f.service.publish(clip.id);const response=await f.request('/api/item/'+f.service.state().items[0].id,undefined,c.token);assert.equal(response.status,200);assert.equal(response.data.includes(comment),false);assert.equal(response.data.toString('base64'),png);assert.equal(f.store.get(clip.id).payload.png,source);assert.equal(response.data.includes(Buffer.from('private raw format')),false);}finally{await f.close();}});
