const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){const output=path.resolve('work/window-capture');await fs.mkdir(output,{recursive:true});const env={...process.env,CLIPPER_TEST_MODE:'1',CLIPPER_DATA_DIR:await fs.mkdtemp(path.join(output,'profile-')),CLIPPER_HELPER_PROFILE:await fs.mkdtemp(path.join(output,'helper-'))};delete env.ELECTRON_RUN_AS_NODE;const helper=await electron.launch({args:[path.resolve('tests/clipboard-helper.cjs')],env});let app;
try{const fixture=await helper.firstWindow();await fixture.waitForSelector('#target');await helper.evaluate(()=>{global.helperWindow.setSize(680,460);global.helperWindow.setAlwaysOnTop(true,'screen-saver');global.helperWindow.show();global.helperWindow.focus();});await fixture.evaluate(()=>{document.body.style.cssText='margin:0;background:linear-gradient(to right,rgb(22,75,155) 50%,rgb(198,49,56) 50%);height:100vh';document.body.innerHTML='';});await wait(800);app=await electron.launch(process.env.CLIPPER_PACKAGED_EXE?{executablePath:process.env.CLIPPER_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});const page=await app.firstWindow();await page.waitForSelector('#search');
const choices=()=>page.evaluate(()=>window.clipper.captureWindows()),pick=async()=>{const list=await choices(),choice=list.find(s=>s.name==='Clipper 测试目标');assert.ok(choice,JSON.stringify(list.map(s=>s.name)));assert.ok(!list.some(s=>s.name==='Clipper'));return choice;};const sample=async id=>{const detail=await page.evaluate(id=>window.clipper.detail(id),id);assert.equal(detail.source,'窗口截图');return app.evaluate(({nativeImage},png)=>{const image=nativeImage.createFromBuffer(Buffer.from(png,'base64')),s=image.getSize(),b=image.toBitmap();return {size:s,colors:[.25,.75].map(x=>{const i=(Math.floor(s.height*.6)*s.width+Math.floor(s.width*x))*4;return [...b.subarray(i,i+3)].reverse();})};},detail.payload.png);};const near=(a,b)=>assert.ok(a.every((v,i)=>Math.abs(v-b[i])<7),JSON.stringify({a,b}));
console.log('Real window snapshot retains pixels while another window covers it');const first=await pick();const id=await page.evaluate(t=>window.clipper.screenshotWindow(t),first.token),shot=await sample(id);near(shot.colors[0],[22,75,155]);near(shot.colors[1],[198,49,56]);assert.ok(shot.size.width>680&&shot.size.width<=2560);assert.ok(shot.size.width*shot.size.height<=4_000_000);
await helper.evaluate(async({BrowserWindow})=>{global.coverWindow=new BrowserWindow({bounds:global.helperWindow.getBounds(),width:900,height:700,alwaysOnTop:true,frame:false,backgroundColor:'#00ee00'});global.coverWindow.setBounds(global.helperWindow.getBounds());global.coverWindow.setAlwaysOnTop(true,'screen-saver');await global.coverWindow.loadURL('data:text/html,<body style="margin:0;background:%2300ee00"></body>');global.coverWindow.show();});await wait(400);const covered=await pick(),coveredId=await page.evaluate(t=>window.clipper.screenshotWindow(t),covered.token),coveredShot=await sample(coveredId);near(coveredShot.colors[0],[22,75,155]);near(coveredShot.colors[1],[198,49,56]);
console.log('Expired, forged, minimized and closed window choices fail without history changes');const stale=await pick();await choices();await assert.rejects(page.evaluate(t=>window.clipper.screenshotWindow(t),stale.token),/失效/);await assert.rejects(page.evaluate(()=>window.clipper.screenshotWindow('window:123:0')),/失效/);const minimized=await pick();await helper.evaluate(()=>global.helperWindow.minimize());await assert.rejects(page.evaluate(t=>window.clipper.screenshotWindow(t),minimized.token),/关闭或最小化/);assert.ok(!(await choices()).some(c=>c.name==='Clipper 测试目标'));await helper.evaluate(()=>global.helperWindow.restore());await wait(300);
console.log('Suspend invalidates a capture awaiting real desktop source enumeration');const pendingChoice=await pick();const count=(await page.evaluate(()=>window.clipper.state())).clips.length;await app.evaluate(({desktopCapturer})=>{const original=desktopCapturer.getSources;global.restoreWindowCapture=()=>desktopCapturer.getSources=original;desktopCapturer.getSources=async options=>{const result=await original(options);await new Promise(r=>setTimeout(r,600));return result;};});const pending=page.evaluate(t=>window.clipper.screenshotWindow(t),pendingChoice.token);await wait(350);await app.evaluate(({powerMonitor})=>powerMonitor.emit('suspend'));assert.equal(await pending,null);await app.evaluate(({powerMonitor})=>{global.restoreWindowCapture();powerMonitor.emit('resume');});assert.equal((await page.evaluate(()=>window.clipper.state())).clips.length,count);
await helper.evaluate(()=>global.coverWindow.destroy());await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/index.html')).show());await page.locator('[data-page=capture-tools]').click();await page.locator('#capture-window').click();await expect(page.locator('.capture-window-choice').filter({hasText:'Clipper 测试目标'})).toBeVisible();await page.locator('.capture-window-choice').evaluateAll(nodes=>nodes.forEach(n=>{if(!n.textContent.includes('Clipper 测试目标'))n.remove();}));await page.screenshot({path:path.join(output,'window-picker.png')});await page.keyboard.press('Escape');const closed=await pick();await helper.evaluate(({BrowserWindow})=>{global.keepalive=new BrowserWindow({show:false});global.helperWindow.destroy();});await assert.rejects(page.evaluate(t=>window.clipper.screenshotWindow(t),closed.token),/关闭或最小化/);console.log(JSON.stringify({result:'PASS',packaged:!!process.env.CLIPPER_PACKAGED_EXE,shot,coveredShot,stale:true,minimized:true,closed:true,suspend:true,ownWindowsExcluded:true},null,2));
}finally{if(app)await app.close();await helper.evaluate(({clipboard})=>global.restoreClipboard());await helper.close();}}run().catch(e=>{console.error(e);process.exitCode=1});

