import './language';
import './appearance';
import { contextBridge, ipcRenderer, webUtils } from 'electron';
import type { API } from '../shared/types';
const invoke=(name:string,...args:unknown[])=>ipcRenderer.invoke('clipper:'+name,...args);
const api:API={
 preview:id=>invoke('preview',id),snippetPreview:id=>invoke('snippet-preview',id),releasePreview:url=>invoke('preview-release',url),
  programVersions:()=>invoke('program-version-list'),deleteProgramVersion:id=>invoke('program-version-delete',id),chooseProgramVersion:id=>invoke('program-version-choose',id),previewProgramVersion:(token,password,newPassword,mode)=>invoke('program-version-preview',token,password,newPassword,mode),rollbackProgramVersion:(token,proof)=>invoke('program-version-commit',token,proof),cancelProgramRollback:()=>invoke('program-version-cancel'),
  checkpoints:()=>invoke('checkpoint-list'),createCheckpoint:()=>invoke('checkpoint-create'),deleteCheckpoint:id=>invoke('checkpoint-delete',id),chooseCheckpoint:id=>invoke('checkpoint-choose',id),previewCheckpoint:(token,password,newPassword,mode)=>invoke('checkpoint-preview',token,password,newPassword,mode),restoreCheckpoint:(token,proof)=>invoke('checkpoint-commit',token,proof),cancelCheckpoint:()=>invoke('checkpoint-cancel'),
  updateState:()=>invoke('update-state'),configureUpdates:automatic=>invoke('update-configure',automatic),checkUpdate:()=>invoke('update-check'),downloadUpdate:()=>invoke('update-download'),cancelUpdate:()=>invoke('update-cancel'),installUpdate:()=>invoke('update-install'),showUpdateDownload:()=>invoke('update-show'),onUpdate:callback=>{const listener=(_e:unknown,value:import('../shared/updates').UpdateState)=>callback(value);ipcRenderer.on('clipper:update-changed',listener);return()=>ipcRenderer.removeListener('clipper:update-changed',listener);},
  appIcons:names=>invoke('app-icons',names),reloadLanguage:()=>invoke('language-reload'),configureLanguage:value=>invoke('language-save',value),configureAppearance:value=>invoke('appearance-save',value),stackState:()=>invoke('stack-state'),configureStack:value=>invoke('stack-configure',value),setStackRunning:value=>invoke('stack-running',value),previewStack:order=>invoke('stack-preview',order),commitStack:token=>invoke('stack-commit',token),cancelStackPreview:()=>invoke('stack-cancel'),reverseStack:()=>invoke('stack-reverse'),efficiencyState:()=>invoke('efficiency-state'),configureEfficiency:value=>invoke('efficiency-configure',value),rememberSearch:query=>invoke('remember-search',query),removeSearch:query=>invoke('remove-search',query),replyIntent:()=>invoke('reply-intent'),resolveReply:(token,values)=>invoke('resolve-reply',token,values),openRecorder:()=>invoke('record-open'),
  selectionState:()=>invoke('selection-state'),configureSelection:value=>invoke('selection-configure',value),readSelection:()=>invoke('selection-read'),selectionInput:()=>invoke('selection-input'),
  showTray:()=>invoke('tray-open'),desktopState:()=>invoke('desktop-state'),configureDesktop:value=>invoke('desktop-configure',value),showQuick:()=>invoke('desktop-quick'),showShelf:()=>invoke('desktop-shelf'),
  vaultState:()=>invoke('vault-state'),prepareEncryption:password=>invoke('vault-prepare',password),cancelEncryption:()=>invoke('vault-cancel'),encryptHistory:(token,proof)=>invoke('vault-encrypt',token,proof),cleanupPlaintext:()=>invoke('vault-cleanup'),changeHistoryPassword:password=>invoke('vault-password',password),configureVault:(hello,idle)=>invoke('vault-configure',hello,idle),lockHistory:()=>invoke('vault-lock'),
  webState:()=>invoke('web-state'),webStart:value=>invoke('web-start',value),webStop:()=>invoke('web-stop'),webInvite:()=>invoke('web-invite'),webCopyInvite:()=>invoke('web-copy-invite'),webApprove:(id,accept,allowSend)=>invoke('web-approve',id,accept,allowSend),webRevoke:id=>invoke('web-revoke',id),webPublish:id=>invoke('web-publish',id),webRemove:id=>invoke('web-remove',id),webFollow:value=>invoke('web-follow',value),
  syncState:()=>invoke('sync-state'),syncConfigure:value=>invoke('sync-configure',value),syncInvite:host=>invoke('sync-invite',host),syncJoin:code=>invoke('sync-join',code),syncApprove:(id,accept)=>invoke('sync-approve',id,accept),syncCancel:()=>invoke('sync-cancel'),syncRevoke:id=>invoke('sync-revoke',id),syncNow:()=>invoke('sync-now'),syncShare:id=>invoke('sync-share',id),syncLocal:(id,only)=>invoke('sync-local',id,only),
  dataState:()=>invoke('data-state'),chooseStorage:()=>invoke('storage-choose'),migrateStorage:token=>invoke('storage-migrate',token),chooseBackupFolder:()=>invoke('backup-folder'),configureBackup:value=>invoke('backup-configure',value),backupNow:()=>invoke('backup-now'),exportProtected:password=>invoke('backup-protected',password),chooseRestore:name=>invoke('restore-choose',name),previewRestore:(token,password)=>invoke('restore-preview',token,password),restoreBackup:token=>invoke('restore-commit',token),cancelRestore:token=>invoke('restore-cancel',token),
  aiState:()=>invoke('ai-state'),aiProfile:value=>invoke('ai-profile',value),removeAIProfile:id=>invoke('ai-remove',id),defaultAIProfile:id=>invoke('ai-default',id),aiModels:(profileId,requestId)=>invoke('ai-models',profileId,requestId),aiRun:value=>invoke('ai-run',value),aiCancel:id=>invoke('ai-cancel',id),
  scripts:()=>invoke('scripts'),saveScript:value=>invoke('script-save',value),removeScript:id=>invoke('script-remove',id),runScript:value=>invoke('script-run',value),cancelScript:id=>invoke('script-cancel',id),scriptBackup:mode=>invoke('script-backup',mode),applyText:value=>invoke('apply-text',value),
  integrations:()=>invoke('integrations'),registerIntegration:enabled=>invoke('integration-register',enabled),resolveExternal:(id,accept)=>invoke('external-resolve',id,accept),
  recordShortcut:active=>invoke('record-shortcut',active),search:(query,category)=>invoke('search',query,category),state:()=>invoke('state'),detail:id=>invoke('detail',id),action:(id,a)=>invoke('action',id,a),undo:()=>invoke('undo'),edit:(id,text,tags)=>invoke('edit',id,text,tags),copy:(id,paste,plain=false)=>invoke('copy',id,paste,plain),next:()=>invoke('next'),clearQueue:()=>invoke('clear-queue'),queueAction:(index,id,action,expected)=>invoke('queue-action',index,id,action,expected),
  snippet:value=>invoke('snippet',value),snippetDetail:id=>invoke('snippet-detail',id),removeSnippet:id=>invoke('remove-snippet',id),useSnippet:(id,paste,values)=>invoke('use-snippet',id,paste,values),
  batch:(ids,action,tags)=>invoke('batch',ids,action,tags),category:value=>invoke('category',value),removeCategory:id=>invoke('remove-category',id),
  metadata:value=>invoke('metadata',value),cancelMetadata:id=>invoke('metadata-cancel',id),
  exportAttachment:(id,index)=>invoke('export-attachment',id,index),contentInfo:(id,readFiles=false)=>invoke('content-info',id,readFiles),exportFormat:(id,name)=>invoke('export-format',id,name),
  editImage:id=>invoke('image-open',id),captureWindows:()=>invoke('capture-windows'),screenshotWindow:token=>invoke('screenshot-window',token),
  addFiles:()=>invoke('add-files'),dropFiles:files=>invoke('drop-files',files.map(file=>webUtils.getPathForFile(file))),drag:id=>ipcRenderer.send('clipper:drag',id),exportImage:id=>invoke('export-image',id),
  ocrStatus:()=>invoke('ocr-status'),ocr:(id,language)=>invoke('ocr',id,language),cancelOcr:()=>invoke('cancel-ocr'),saveOcr:text=>invoke('save-ocr',text),openScrollCapture:()=>invoke('scroll-open'),screens:()=>invoke('screens'),screenshot:(mode,display)=>invoke('screenshot',mode,display),
  settings:value=>invoke('settings',value),backup:mode=>invoke('backup',mode),clear:()=>invoke('clear'),hide:()=>invoke('hide'),quit:()=>invoke('quit'),onChange:callback=>{const listener=()=>callback();ipcRenderer.on('clipper:changed',listener);return()=>ipcRenderer.removeListener('clipper:changed',listener);},onNotice:callback=>{const listener=(_e:unknown,text:string)=>callback(text);ipcRenderer.on('clipper:notice',listener);return()=>ipcRenderer.removeListener('clipper:notice',listener);}
};
contextBridge.exposeInMainWorld('clipper',api);
