import {importDroppedFiles} from './file-drop';
import './language';
import './appearance';
import { contextBridge, ipcRenderer, webUtils } from 'electron';
import type { API } from '../shared/types';
const invoke=(name:string,...args:unknown[])=>ipcRenderer.invoke('clip:'+name,...args);
const api:API={
 onShortcutInput:callback=>{const listener=(_event:unknown,input:import('../shared/shortcut').ShortcutInput)=>callback(input);ipcRenderer.on('clip:shortcut-input',listener);return()=>ipcRenderer.removeListener('clip:shortcut-input',listener);},
 configureChatShortcut:value=>invoke('chat-shortcut',value),openChat:id=>invoke('chat-open',id),onChatSettings:callback=>{const listener=()=>callback();ipcRenderer.on('clip:open-text-tools',listener);return()=>ipcRenderer.removeListener('clip:open-text-tools',listener);},
 tasks:()=>invoke('tasks'),cancelTask:id=>invoke('task-cancel',id),retryTask:id=>invoke('task-retry',id),clearTasks:()=>invoke('task-clear'),copyTaskLink:id=>invoke('task-copy-link',id),
 startImageUpload:(id,force=false)=>invoke('image-upload-start',id,force),imageUploadRecord:id=>invoke('image-upload-record',id),
 onTasks:callback=>{const listener=(_e:unknown,value:import('../shared/tasks').TaskState)=>callback(value);ipcRenderer.on('clip:tasks-changed',listener);return()=>ipcRenderer.removeListener('clip:tasks-changed',listener);},
 restart:()=>invoke('restart'),openReference:url=>invoke('reference-open',url),
 preview:id=>invoke('preview',id),snippetPreview:id=>invoke('snippet-preview',id),releasePreview:url=>invoke('preview-release',url),
  programVersions:()=>invoke('program-version-list'),deleteProgramVersion:id=>invoke('program-version-delete',id),chooseProgramVersion:id=>invoke('program-version-choose',id),previewProgramVersion:(token,password,newPassword,mode)=>invoke('program-version-preview',token,password,newPassword,mode),rollbackProgramVersion:(token,proof)=>invoke('program-version-commit',token,proof),cancelProgramRollback:()=>invoke('program-version-cancel'),
  checkpoints:()=>invoke('checkpoint-list'),createCheckpoint:()=>invoke('checkpoint-create'),deleteCheckpoint:id=>invoke('checkpoint-delete',id),chooseCheckpoint:id=>invoke('checkpoint-choose',id),previewCheckpoint:(token,password,newPassword,mode)=>invoke('checkpoint-preview',token,password,newPassword,mode),restoreCheckpoint:(token,proof)=>invoke('checkpoint-commit',token,proof),cancelCheckpoint:()=>invoke('checkpoint-cancel'),
  updateState:()=>invoke('update-state'),configureUpdates:automatic=>invoke('update-configure',automatic),checkUpdate:()=>invoke('update-check'),downloadUpdate:()=>invoke('update-download'),cancelUpdate:()=>invoke('update-cancel'),installUpdate:()=>invoke('update-install'),showUpdateDownload:()=>invoke('update-show'),onUpdate:callback=>{const listener=(_e:unknown,value:import('../shared/updates').UpdateState)=>callback(value);ipcRenderer.on('clip:update-changed',listener);return()=>ipcRenderer.removeListener('clip:update-changed',listener);},
  appIcons:names=>invoke('app-icons',names),reloadLanguage:()=>invoke('language-reload'),configureLanguage:value=>invoke('language-save',value),configureAppearance:value=>invoke('appearance-save',value),stackState:()=>invoke('stack-state'),configureStack:value=>invoke('stack-configure',value),setStackRunning:value=>invoke('stack-running',value),previewStack:order=>invoke('stack-preview',order),commitStack:token=>invoke('stack-commit',token),cancelStackPreview:()=>invoke('stack-cancel'),reverseStack:()=>invoke('stack-reverse'),efficiencyState:()=>invoke('efficiency-state'),configureEfficiency:value=>invoke('efficiency-configure',value),rememberSearch:query=>invoke('remember-search',query),removeSearch:query=>invoke('remove-search',query),replyIntent:()=>invoke('reply-intent'),resolveReply:(token,values)=>invoke('resolve-reply',token,values),
  showQuick:()=>invoke('quick-open'),configureQuickShortcut:value=>invoke('quick-shortcut',value),configureWinVInterception:value=>invoke('quick-intercept-win-v',value),showTray:()=>invoke('tray-open'),desktopState:()=>invoke('desktop-state'),configureDesktop:value=>invoke('desktop-configure',value),showShelf:()=>invoke('desktop-shelf'),
  vaultState:()=>invoke('vault-state'),prepareEncryption:password=>invoke('vault-prepare',password),cancelEncryption:()=>invoke('vault-cancel'),encryptHistory:(token,proof)=>invoke('vault-encrypt',token,proof),decryptHistory:()=>invoke('vault-decrypt'),cleanupPlaintext:()=>invoke('vault-cleanup'),changeHistoryPassword:password=>invoke('vault-password',password),configureVault:(hello,idle)=>invoke('vault-configure',hello,idle),lockHistory:()=>invoke('vault-lock'),
  webState:()=>invoke('web-state'),webStart:value=>invoke('web-start',value),webStop:()=>invoke('web-stop'),webInvite:()=>invoke('web-invite'),webCopyInvite:()=>invoke('web-copy-invite'),webApprove:(id,accept,allowSend)=>invoke('web-approve',id,accept,allowSend),webRevoke:id=>invoke('web-revoke',id),webPublish:id=>invoke('web-publish',id),webRemove:id=>invoke('web-remove',id),webFollow:value=>invoke('web-follow',value),
  syncState:()=>invoke('sync-state'),syncConfigure:value=>invoke('sync-configure',value),syncInvite:host=>invoke('sync-invite',host),syncJoin:code=>invoke('sync-join',code),syncApprove:(id,accept)=>invoke('sync-approve',id,accept),syncCancel:()=>invoke('sync-cancel'),syncRevoke:id=>invoke('sync-revoke',id),syncNow:()=>invoke('sync-now'),syncShare:id=>invoke('sync-share',id),syncLocal:(id,only)=>invoke('sync-local',id,only),
  dataState:()=>invoke('data-state'),chooseStorage:()=>invoke('storage-choose'),migrateStorage:token=>invoke('storage-migrate',token),chooseBackupFolder:()=>invoke('backup-folder'),configureBackup:value=>invoke('backup-configure',value),backupNow:()=>invoke('backup-now'),exportProtected:password=>invoke('backup-protected',password),chooseRestore:name=>invoke('restore-choose',name),previewRestore:(token,password)=>invoke('restore-preview',token,password),restoreBackup:token=>invoke('restore-commit',token),cancelRestore:token=>invoke('restore-cancel',token),
  aiState:()=>invoke('ai-state'),aiProfile:value=>invoke('ai-profile',value),removeAIProfile:id=>invoke('ai-remove',id),defaultAIProfile:id=>invoke('ai-default',id),reorderAIProfiles:ids=>invoke('ai-order',ids),aiModels:(profileId,requestId)=>invoke('ai-models',profileId,requestId),aiModelCatalog:(profileId,requestId)=>invoke('ai-model-catalog',profileId,requestId),aiRun:value=>invoke('ai-run',value),aiCancel:id=>invoke('ai-cancel',id),
  codexStatus:()=>invoke('codex-status'),codexLogin:()=>invoke('codex-login'),codexCancelLogin:()=>invoke('codex-login-cancel'),codexLogout:()=>invoke('codex-logout'),
  codexChooseExecutable:()=>invoke('codex-executable-choose'),codexAutoExecutable:()=>invoke('codex-executable-auto'),
  codexOpenLogin:()=>invoke('codex-open-login'),codexCopyCode:()=>invoke('codex-copy-code'),codexModels:request=>invoke('codex-models',request),
  commands:()=>invoke('commands'),saveCommand:value=>invoke('command-save',value),removeCommand:(id,revision)=>invoke('command-remove',id,revision),
  scripts:()=>invoke('scripts'),saveScript:value=>invoke('script-save',value),removeScript:id=>invoke('script-remove',id),runScript:value=>invoke('script-run',value),cancelScript:id=>invoke('script-cancel',id),scriptBackup:mode=>invoke('script-backup',mode),applyText:value=>invoke('apply-text',value),
  integrations:()=>invoke('integrations'),registerIntegration:enabled=>invoke('integration-register',enabled),resolveExternal:(id,accept)=>invoke('external-resolve',id,accept),
  recordShortcut:active=>invoke('record-shortcut',active),search:(query,category)=>invoke('search',query,category),state:()=>invoke('state'),detail:id=>invoke('detail',id),action:(id,a)=>invoke('action',id,a),undo:()=>invoke('undo'),edit:(id,text,tags)=>invoke('edit',id,text,tags),copy:(id,paste,plain=false)=>invoke('copy',id,paste,plain),next:()=>invoke('next'),clearQueue:()=>invoke('clear-queue'),queueAction:(index,id,action,expected)=>invoke('queue-action',index,id,action,expected),
  snippet:value=>invoke('snippet',value),snippetDetail:id=>invoke('snippet-detail',id),removeSnippet:id=>invoke('remove-snippet',id),removeSnippets:ids=>invoke('remove-snippets',ids),reorderSnippets:ids=>invoke('snippet-order',ids),reorderFavorites:ids=>invoke('favorite-order',ids),useSnippet:(id,paste,values)=>invoke('use-snippet',id,paste,values),
  batch:(ids,action,tags)=>invoke('batch',ids,action,tags),categoryCounts:()=>invoke('category-counts'),category:value=>invoke('category',value),removeCategory:id=>invoke('remove-category',id),reorderCategories:ids=>invoke('category-order',ids),setManualCategory:(ids,category,assigned)=>invoke('manual-category',ids,category,assigned),
  metadata:value=>invoke('metadata',value),cancelMetadata:id=>invoke('metadata-cancel',id),
  exportAttachment:(id,index)=>invoke('export-attachment',id,index),contentInfo:(id,readFiles=false)=>invoke('content-info',id,readFiles),exportFormat:(id,name)=>invoke('export-format',id,name),
  fileAction:(id,index,action)=>invoke('file-action',id,index,action),
  imageHostState:()=>invoke('image-host-state'),configureImageHost:value=>invoke('image-host-configure',value),testImageHost:value=>invoke('image-host-test',value),uploadImage:id=>invoke('image-host-upload',id),
  addFiles:()=>invoke('add-files'),dropFiles:files=>importDroppedFiles(files,paths=>invoke('drop-files',paths),image=>invoke('drop-image',image)),dropImage:value=>invoke('drop-image',value),drag:id=>ipcRenderer.send('clip:drag',id),exportImage:id=>invoke('export-image',id),
  settings:value=>invoke('settings',value),backup:mode=>invoke('backup',mode),clear:()=>invoke('clear'),hide:()=>invoke('hide'),quit:()=>invoke('quit'),onChange:callback=>{const listener=()=>callback();ipcRenderer.on('clip:changed',listener);return()=>ipcRenderer.removeListener('clip:changed',listener);},onNotice:callback=>{const listener=(_e:unknown,text:string)=>callback(text);ipcRenderer.on('clip:notice',listener);return()=>ipcRenderer.removeListener('clip:notice',listener);}
};
contextBridge.exposeInMainWorld('clip',api);
