import {importDroppedFiles} from './file-drop';
import './language';
import './appearance';
import {contextBridge,ipcRenderer} from 'electron';
import type {ShelfAPI} from '../shared/desktop';
const invoke=(name:string,...args:unknown[])=>ipcRenderer.invoke('clip:shelf-'+name,...args);
let importing=0;
const hold=async<T>(fn:()=>Promise<T>)=>{if(++importing===1)await invoke('activity',true).catch(()=>{});try{return await fn();}finally{if(--importing===0)await invoke('activity',false).catch(()=>{});}};
const api:ShelfAPI={state:()=>invoke('state'),activity:active=>invoke('activity',active),choose:()=>hold(()=>invoke('choose')),dropFiles:files=>hold(()=>importDroppedFiles(files,paths=>invoke('files',paths),image=>invoke('image',image))),dropImage:value=>hold(()=>invoke('image',value)),dropText:text=>invoke('text',text),remove:id=>invoke('remove',id),copy:(id,paste)=>invoke('copy',id,paste),drag:id=>ipcRenderer.send('clip:shelf-drag',id),hide:()=>invoke('hide'),main:()=>invoke('main'),top:value=>invoke('top',value),mode:(value,reducedMotion)=>invoke('mode',value,reducedMotion),onChange:callback=>{const fn=()=>callback();ipcRenderer.on('clip:changed',fn);return()=>ipcRenderer.removeListener('clip:changed',fn);},onTransition:callback=>{const fn=(_e:unknown,active:boolean,mode:'compact'|'expanded',size?:{width:number;height:number})=>callback(active,mode,size);ipcRenderer.on('clip:shelf-transition',fn);return()=>ipcRenderer.removeListener('clip:shelf-transition',fn);},onNotice:callback=>{const fn=(_e:unknown,text:string)=>callback(text);ipcRenderer.on('clip:notice',fn);return()=>ipcRenderer.removeListener('clip:notice',fn);}};
contextBridge.exposeInMainWorld('clipShelf',api);
