import {t as tr} from './i18n';
export const metadataLabels={encryption:'加密方式',format:'格式',width:'宽度',height:'高度',make:'相机品牌',model:'相机型号',lens:'镜头',taken:'拍摄时间',exposure:'曝光时间',aperture:'光圈',iso:'ISO',orientation:'方向',colorSpace:'色彩空间',latitude:'纬度',longitude:'经度',altitude:'海拔',codec:'编码',duration:'时长',bitrate:'比特率',sampleRate:'采样率',channels:'声道',bitDepth:'位深',video:'视频轨',title:'标题',artist:'艺术家',album:'专辑',year:'年份',genre:'流派',track:'曲目',author:'作者',subject:'文档主题',keywords:'关键词',creator:'制作工具',producer:'生成工具',created:'创建时间',modified:'修改时间',pages:'页数',declaredPages:'声明页数',slides:'幻灯片',sheets:'工作表',words:'字数',application:'应用',company:'公司',lastAuthor:'最后修改者',revision:'修订版本',category:'分类',description:'说明'} as const;
export type MetadataKey=keyof typeof metadataLabels;
export type MetadataTarget={kind:'image'|'attachment'|'file';index:number};
export interface MetadataRequest {requestId:string;id:string;target:MetadataTarget;includeLocation:boolean;password?:string}
export interface MetadataResult {category:'image'|'media'|'pdf'|'office';name:string;size:number;fields:{key:MetadataKey;value:string}[]}
export function validateMetadataTarget(value:unknown):MetadataTarget{const v=value as MetadataTarget;if(!v||!['image','attachment','file'].includes(v.kind)||!Number.isInteger(v.index)||v.index<0||v.index>255||v.kind==='image'&&v.index!==0)throw new Error(tr('内部信息对象无效'));return {kind:v.kind,index:v.index};}
export function validateMetadataResult(value:unknown):MetadataResult{const v=value as MetadataResult;if(!v||!['image','media','pdf','office'].includes(v.category)||typeof v.name!=='string'||v.name.length>255||!Number.isSafeInteger(v.size)||v.size<0||v.size>2*1024**3||!Array.isArray(v.fields)||v.fields.length>64||new TextEncoder().encode(JSON.stringify(v)).length>64*1024)throw new Error(tr('内部信息返回无效'));const keys=new Set<string>();const fields=v.fields.map(f=>{if(!f||!Object.hasOwn(metadataLabels,f.key)||keys.has(f.key)||typeof f.value!=='string'||!f.value||f.value.length>2048)throw new Error(tr('内部信息字段无效'));keys.add(f.key);return {key:f.key,value:f.value};});return {category:v.category,name:v.name,size:v.size,fields};}
export const metadataKind=(name:string)=>/\.(jpe?g|jfif|png|tiff?|gif|webp|bmp|heic|heif|avif|dib)$/i.test(name)?'image':/\.(mp3|wav|flac|ogg|opus|aac|m4a|mp4|m4v|mov|webm|mkv|wma|aiff?|ape|wv)$/i.test(name)?'media':/\.pdf$/i.test(name)?'pdf':/\.(docx|xlsx|pptx|doc|xls|ppt|docm|xlsm|pptm|dotx|dotm|xltx|xltm|potx|potm)$/i.test(name)?'office':undefined;
