import {t as tr} from './i18n';
import type {Region} from './region';
export const RECORD_CHUNK=8*1024*1024,RECORD_BYTES=1024*1024*1024,RECORD_SECONDS=3600;
export type RecordingContainer='mp4'|'webm'|'wav';
export interface RecordingOptions {container?:RecordingContainer;mode:'video'|'audio';sourceId:string;systemAudio:boolean;microphone:boolean;microphoneId:string;fps:15|30|60;maxWidth:1920|2560;regionToken?:string}
export interface RecordingSource {id:string;name:string;type:'screen'|'window';thumbnail:string}
export type RecordingPhase='idle'|'arming'|'recording'|'paused'|'stopping'|'ready'|'saving';
export interface RecordingState {phase:RecordingPhase;token:string;seconds:number;bytes:number;dark:boolean;message:string;url?:string;mime?:string;saved?:string;options?:RecordingOptions;region?:Region}
export interface RecorderAPI {state():Promise<RecordingState>;chooseRegion(sourceId:string):Promise<{token:string;width:number;height:number}|null>;sources(type?:'screen'|'window'):Promise<RecordingSource[]>;arm(options:RecordingOptions):Promise<string>;started(token:string,mime:string):Promise<void>;chunk(token:string,sequence:number,data:Uint8Array):Promise<void>;heartbeat(token:string,seconds:number):Promise<void>;paused(token:string,paused:boolean):Promise<void>;finish(token:string,seconds:number,reason:string,mime:string):Promise<void>;cancel():Promise<void>;fail(token:string,message:string):Promise<void>;save():Promise<string|null>;copySaved():Promise<void>;onChange(callback:()=>void):()=>void;onStop(callback:()=>void):()=>void}
export function recordingOptions(value:unknown):RecordingOptions {const v=value as RecordingOptions;if(!v||v.container!==undefined&&(!['mp4','webm','wav'].includes(v.container)||v.container==='wav'&&v.mode!=='audio')||!['video','audio'].includes(v.mode)||typeof v.sourceId!=='string'||v.sourceId.length>120||v.mode==='video'&&!/^(screen|window):\d+:\d+$/.test(v.sourceId)||typeof v.systemAudio!=='boolean'||typeof v.microphone!=='boolean'||v.mode==='audio'&&!v.systemAudio&&!v.microphone||typeof v.microphoneId!=='string'||v.microphoneId.length>300||![15,30,60].includes(v.fps)||![1920,2560].includes(v.maxWidth)||v.regionToken!==undefined&&(typeof v.regionToken!=='string'||v.regionToken.length>80||v.mode!=='video'||!v.sourceId.startsWith('screen:')))throw new Error(tr('录制选项无效，请选择来源和声音'));return {...(v.container?{container:v.container}:{}),mode:v.mode,sourceId:v.mode==='video'?v.sourceId:'',systemAudio:v.systemAudio,microphone:v.microphone,microphoneId:v.microphoneId,fps:v.fps,maxWidth:v.maxWidth,...(v.regionToken?{regionToken:v.regionToken}:{})};}
export function recordingMime(mode:'video'|'audio',audio:boolean,container:RecordingContainer='mp4'){if(container==='wav')return 'audio/wav';if(container==='webm')return mode==='audio'?'audio/webm;codecs=opus':'video/webm;codecs=vp9'+(audio?',opus':'');return mode==='audio'?'audio/mp4;codecs=mp4a.40.2':'video/mp4;codecs=avc1.42001E'+(audio?',mp4a.40.2':'');}
export function validRecordingMime(mime:unknown,options:RecordingOptions):mime is string {if(options.container==='wav')return options.mode==='audio'&&mime==='audio/wav';if(options.container==='webm')return typeof mime==='string'&&(options.mode==='audio'?/^audio\/webm;codecs=opus$/i:/^video\/webm;codecs=vp[89](?:,opus)?$/i).test(mime)&&(options.mode==='audio'||(options.systemAudio||options.microphone)===mime.toLowerCase().includes('opus'));return typeof mime==='string'&&(options.mode==='audio'?/^audio\/mp4;codecs=mp4a\.40\.2$/i:/^video\/mp4;codecs=avc1\.[0-9a-f]{6}(?:,mp4a\.40\.2)?$/i).test(mime)&&(options.mode==='audio'||(options.systemAudio||options.microphone)===mime.toLowerCase().includes('mp4a.40.2'));}
export function recordingRange(header:string|null,size:number):{start:number;end:number;partial:boolean}{if(!Number.isSafeInteger(size)||size<1)throw new Error(tr('录制内容为空'));if(!header)return {start:0,end:size-1,partial:false};const match=/^bytes=(\d*)-(\d*)$/.exec(header);if(!match||!match[1]&&!match[2])throw new Error(tr('无效媒体范围'));let start=Number(match[1]),end=match[2]?Number(match[2]):size-1;if(!match[1]){if(end<1)throw new Error(tr('无效媒体范围'));start=Math.max(0,size-end);end=size-1;}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start>=size||end<start)throw new Error(tr('无效媒体范围'));return {start,end:Math.min(size-1,end),partial:true};}

export function recordingExtension(options:RecordingOptions){return options.container==='wav'?'wav':options.container==='webm'?'webm':options.mode==='audio'?'m4a':'mp4';}
export function recordingContentType(options:RecordingOptions){return options.container==='wav'?'audio/wav':(options.mode==='audio'?'audio/':'video/')+(options.container==='webm'?'webm':'mp4');}
