import { BrowserWindow, desktopCapturer, ipcMain, screen, nativeImage } from 'electron';
import { join } from 'node:path';
import {randomUUID} from 'node:crypto';
import {captureWindowInfo} from './native';
import type { Payload } from '../shared/types';
import {displaySignature,normalizedRegion,regionPixels,type Rectangle,type Region} from '../shared/region';
export class CaptureService {
 private choices=new Map<string,{id:string;pid:number;hwnd:number;name:string;created:number}>();private listing=0;
 private generation=0;active=false;private overlay?:BrowserWindow;private data?:{image:string;name:string;purpose:string};private finish?:((rect:Rectangle|null)=>void);
 constructor(){const check=(event:Electron.IpcMainInvokeEvent)=>{if(!this.overlay||event.sender!==this.overlay.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!=='clipper://app/capture.html')throw new Error('拒绝访问截图');};ipcMain.handle('clipper:capture-data',e=>{check(e);return this.data;});ipcMain.handle('clipper:capture-complete',(e,rect)=>{check(e);this.finish?.(rect);});}
 screens(){return screen.getAllDisplays().map((d,i)=>({id:d.id,name:d.label||`显示器 ${i+1}`,width:d.size.width,height:d.size.height}));}
 cancel(){this.generation++;this.listing++;this.choices.clear();this.data=undefined;this.finish?.(null);this.overlay?.destroy();this.overlay=undefined;}
 async captureWindows(){const generation=this.generation,listing=++this.listing;this.choices.clear();const sources=await desktopCapturer.getSources({types:['window'],thumbnailSize:{width:240,height:150}});if(generation!==this.generation||listing!==this.listing)return [];const result=[];for(const s of sources){const hwnd=Number(s.id.split(':')[1]),info=captureWindowInfo(hwnd);if(!info||info.pid===process.pid||s.thumbnail.isEmpty())continue;const token=randomUUID();this.choices.set(token,{id:s.id,pid:info.pid,hwnd,name:s.name,created:Date.now()});result.push({token,name:s.name,thumbnail:s.thumbnail.toDataURL()});if(result.length===80)break;}return result;}
 async takeWindow(token:unknown,windows:BrowserWindow[]):Promise<Payload|null>{if(this.active)throw new Error('截图正在进行');const choice=typeof token==='string'?this.choices.get(token):undefined;if(!choice||Date.now()-choice.created>120_000)throw new Error('窗口选择已失效，请刷新窗口列表');const check=()=>{const info=captureWindowInfo(choice.hwnd);if(!info||info.pid!==choice.pid||info.pid===process.pid)throw new Error('窗口已关闭或最小化，请刷新窗口列表');return info;};const info=check(),scale=Math.min(1,2560/info.width,2560/info.height,Math.sqrt(4_000_000/(info.width*info.height)));this.active=true;const generation=this.generation,shown=windows.filter(w=>!w.isDestroyed()&&w.isVisible());try{for(const w of shown)w.hide();await new Promise(r=>setTimeout(r,200));if(generation!==this.generation)return null;check();const sources=await desktopCapturer.getSources({types:['window'],thumbnailSize:{width:Math.max(2,Math.floor(info.width*scale)),height:Math.max(2,Math.floor(info.height*scale))}});if(generation!==this.generation)return null;check();const shot=sources.find(s=>s.id===choice.id&&s.name===choice.name);if(!shot||shot.thumbnail.isEmpty())throw new Error('所选窗口无法捕获或名称已变化，请刷新窗口列表');this.choices.delete(token as string);return {png:shot.thumbnail.toPNG().toString('base64')};}finally{this.active=false;if(generation===this.generation)for(const w of shown)if(!w.isDestroyed())w.show();}}
 async snapshot(displayId:number){const display=screen.getAllDisplays().find(d=>d.id===displayId);if(!display)throw new Error('显示器已断开');const signature=displaySignature(display),sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:Math.ceil(display.size.width*display.scaleFactor),height:Math.ceil(display.size.height*display.scaleFactor)}});const source=sources.find(s=>s.display_id===String(display.id));if(!source||source.thumbnail.isEmpty())throw new Error('无法捕获所选显示器');const current=screen.getAllDisplays().find(d=>d.id===displayId);if(!current||displaySignature(current)!==signature)throw new Error('显示器配置已改变，请重新选择');return {display,source,signature,image:nativeImage.createFromBuffer(source.thumbnail.toPNG())};}
 async choose(displayId:number,windows:BrowserWindow[],purpose='选定区域'):Promise<Region|null>{return this.run('region',displayId,windows,purpose,true) as Promise<Region|null>;}
 async take(mode:'region'|'screen',displayId:number,windows:BrowserWindow[]):Promise<Payload|null>{return this.run(mode,displayId,windows,'保存截图',false) as Promise<Payload|null>;}
 private async run(mode:'region'|'screen',displayId:number,windows:BrowserWindow[],purpose:string,regionOnly:boolean):Promise<Payload|Region|null>{
  if(this.active)throw new Error('截图正在进行');if(!['region','screen'].includes(mode))throw new Error('截图模式无效');this.active=true;const generation=this.generation,shown=windows.filter(w=>!w.isDestroyed()&&w.isVisible());let overlay:BrowserWindow|undefined;
  try{for(const w of shown)w.hide();await new Promise(r=>setTimeout(r,200));if(generation!==this.generation)return null;const shot=await this.snapshot(displayId);if(generation!==this.generation)return null;let image=shot.image;
   if(mode==='region'){const imageSize=image.getSize();this.data={image:image.toDataURL(),name:shot.display.label||'选区截图',purpose};overlay=new BrowserWindow({x:shot.display.bounds.x,y:shot.display.bounds.y,width:shot.display.bounds.width,height:shot.display.bounds.height,frame:false,show:false,alwaysOnTop:true,skipTaskbar:true,resizable:true,fullscreen:true,backgroundColor:'#111111',webPreferences:{preload:join(__dirname,'../preload/capture.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,webSecurity:true}});this.overlay=overlay;
    overlay.webContents.setWindowOpenHandler(()=>({action:'deny'}));overlay.webContents.on('will-navigate',e=>e.preventDefault());overlay.setAlwaysOnTop(true,'screen-saver');overlay.setVisibleOnAllWorkspaces(true);
    const selection=new Promise<Rectangle|null>(resolve=>{this.finish=resolve;overlay!.on('closed',()=>resolve(null));});overlay.setFullScreen(true);await overlay.loadURL('clipper://app/capture.html');if(generation!==this.generation||overlay.isDestroyed())return null;overlay.show();overlay.focus();const rect=await selection;if(!rect||generation!==this.generation||overlay.isDestroyed())return null;const d=screen.getAllDisplays().find(d=>d.id===displayId);if(!d||displaySignature(d)!==shot.signature)throw new Error('显示器配置已改变，请重新选择');const normalized=normalizedRegion(rect,overlay.getContentBounds()),crop=regionPixels(normalized,imageSize.width,imageSize.height);
    if(regionOnly)return {displayId,sourceId:shot.source.id,signature:shot.signature,rect:normalized,pixels:{width:crop.width,height:crop.height},screen:imageSize};image=image.crop(crop);
   }return {png:image.toPNG().toString('base64')};
  }finally{if(overlay&&!overlay.isDestroyed())overlay.destroy();if(this.overlay===overlay)this.overlay=undefined;this.data=undefined;this.finish=undefined;this.active=false;if(generation===this.generation)for(const w of shown)if(!w.isDestroyed())w.show();}
 }
}
