import {BrowserWindow,ipcMain,screen,nativeImage,dialog,shell,type IpcMainInvokeEvent,type Rectangle} from 'electron';
import {readFile,stat} from 'node:fs/promises';
import {join,basename} from 'node:path';
import {t as tr,interfaceLanguageArguments} from '../shared/i18n';
import {chatOptions,type ChatState,type ChatOptions,type ChatImage,type ChatEvent} from '../shared/chat';
import type {ChatService} from './chat';
import type {Store} from './store';
import {toolText,MAX_TOOL_OUTPUT} from '../shared/text-tools';
interface Context {service():ChatService;store():Store;blocked():boolean;dark():boolean;development:boolean;target():{hwnd:number;pid:number}|undefined;validTarget(target:{hwnd:number;pid:number}):boolean;copy(text:string,paste:boolean,target?:{hwnd:number;pid:number}):Promise<void>;saved():void;main():void;configure(value:ChatOptions):void;shortcutAvailable():boolean}
export class ChatWindow {
 window?:BrowserWindow;private target?:{hwnd:number;pid:number};private boundsTimer?:NodeJS.Timeout;private blurTimer?:NodeJS.Timeout;private choosingImages=false;private sidebarOpen=false;private sidebarAdded=258;private frameOffset={x:0,y:0,width:0,height:0};
 constructor(private ctx:Context){
  const handle=(name:string,fn:(...args:any[])=>unknown)=>ipcMain.handle('clip:chat-'+name,(event,...args)=>{this.authorize(event);return fn(...args);});
  handle('state',async id=>{const value=await ctx.service().state(id);return {...value,dark:ctx.dark(),canPaste:!!this.target&&ctx.validTarget(this.target),options:this.options(),sidebarOpen:this.sidebarOpen,shortcutAvailable:ctx.shortcutAvailable(),development:ctx.development} satisfies ChatState;});
  handle('models',(profile,request)=>ctx.service().models(profile,request));handle('cancel-models',request=>ctx.service().cancelModels(request));handle('create',()=>ctx.service().create());handle('remove',id=>ctx.service().remove(id));handle('rename',(id,title)=>ctx.service().rename(id,title));handle('draft',(id,draft,profile)=>ctx.service().draft(id,draft,profile));handle('send',value=>ctx.service().send(value));handle('cancel',id=>ctx.service().cancel(id));handle('retry',(id,profile,revision,destination,selection)=>ctx.service().retry(id,profile,revision,destination,selection));
  handle('image',(data,name)=>this.image(data,name));handle('choose-images',()=>this.chooseImages());
  handle('records',()=>ctx.store().cachedList().filter(item=>['image','text','link','code'].includes(item.kind)).slice(0,40).map(({id,title,kind,source})=>({id,title,kind,source})));
  handle('record',id=>{const item=ctx.store().get(id);return {text:item.payload.text||'',images:item.payload.png?[this.image('data:image/png;base64,'+item.payload.png,item.title)]:[]};});
  handle('apply',async(id,message,mode)=>{if(!['copy','paste','save'].includes(mode))throw new Error(tr('操作无效'));if(mode==='paste'&&(!this.target||!ctx.validTarget(this.target)))throw new Error(tr('原窗口已关闭或不可用，请复制回复'));const text=ctx.service().result(id,message,mode==='copy');if(mode==='save'){ctx.store().add({text},tr('AI 对话'));ctx.saved();}else await ctx.copy(text,mode==='paste',mode==='paste'?this.target:undefined);});
  handle('copy-text',text=>ctx.copy(toolText(text,MAX_TOOL_OUTPUT),false));
  handle('configure',value=>this.configure(value));handle('sidebar',open=>this.sidebar(open));
  handle('hide',()=>this.hide());handle('main',()=>{this.hide();ctx.main();});handle('open-url',async url=>{if(typeof url!=='string'||url.length>2048)throw new Error(tr('链接无效'));const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw new Error(tr('链接无效'));await shell.openExternal(parsed.href);});
 }
 private options(){return chatOptions(this.ctx.store().meta('ai-chat-options',{}));}
 configure(value:Partial<ChatOptions>){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(tr('对话窗口设置无效'));const next=chatOptions({...this.options(),...value});this.ctx.configure(next);if(this.window&&this.window.isAlwaysOnTop()!==next.onTop)this.window.setAlwaysOnTop(next.onTop);this.emit({type:'changed'});}
 private placeBounds(bounds:Rectangle){
  const window=this.window!;let request={x:bounds.x+this.frameOffset.x,y:bounds.y+this.frameOffset.y,width:Math.max(1,bounds.width+this.frameOffset.width),height:Math.max(1,bounds.height+this.frameOffset.height)};
  // Calibrate hidden-frame rounding before showing, then reuse the correction for later resizes.
  for(let i=0;i<3;i++){window.setBounds(request);const actual=window.getBounds();this.frameOffset={x:request.x-bounds.x,y:request.y-bounds.y,width:request.width-bounds.width,height:request.height-bounds.height};if(['x','y','width','height'].every(key=>actual[key as keyof Rectangle]===bounds[key as keyof Rectangle]))break;if(i<2)request={x:request.x+bounds.x-actual.x,y:request.y+bounds.y-actual.y,width:Math.max(1,request.width+bounds.width-actual.width),height:Math.max(1,request.height+bounds.height-actual.height)};}if(window.isAlwaysOnTop()!==this.options().onTop)window.setAlwaysOnTop(this.options().onTop);
 }
 private sidebar(open:unknown){
  if(typeof open!=='boolean')throw new Error(tr('对话窗口设置无效'));const window=this.window!;if(open===this.sidebarOpen)return;
  const before=window.getBounds(),area=screen.getDisplayMatching(before).workArea,width=open?Math.min(area.width,before.width+258):Math.max(Math.min(480,area.width),before.width-this.sidebarAdded),x=Math.max(area.x,Math.min(area.x+area.width-width,before.x+before.width-width));
  if(open)this.sidebarAdded=width-before.width;this.sidebarOpen=open;this.ctx.store().setMeta('ai-chat-sidebar',{open,added:this.sidebarAdded});
  // Apply one native resize: interpolating native bounds makes Windows repaint the frame repeatedly.
  if(!open)window.setMinimumSize(Math.min(area.width,480),Math.min(area.height,560));this.placeBounds({...before,x,width});if(open)window.setMinimumSize(Math.min(area.width,738),Math.min(area.height,560));this.saveBounds();
 }
 private authorize(event:IpcMainInvokeEvent){if(this.ctx.blocked()||!this.window||this.window.isDestroyed()||event.sender!==this.window.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!=='clip://app/chat.html')throw new Error(tr('拒绝访问'));}
 private image(data:unknown,name:unknown):ChatImage {
  if(typeof data!=='string'||data.length>23*1024*1024||!/^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/]*={0,2}$/.test(data)||typeof name!=='string')throw new Error(tr('图片格式无效或过大'));
  const image=nativeImage.createFromDataURL(data),size=image.getSize();if(image.isEmpty()||size.width>16384||size.height>16384||size.width*size.height>32*1024*1024)throw new Error(tr('图片尺寸过大或无法读取'));const png=image.toPNG();if(png.length>16*1024*1024)throw new Error(tr('图片超过 16 MiB'));return {name:name.slice(0,120),png:png.toString('base64')};
 }
 private async chooseImages(){const window=this.window!;this.choosingImages=true;let result;try{result=await dialog.showOpenDialog(window,{title:tr('添加图片'),properties:['openFile','multiSelections'],filters:[{name:tr('图片'),extensions:['png','jpg','jpeg','webp','gif']}]});}finally{this.choosingImages=false;}if(this.ctx.blocked()||window.isDestroyed()||this.window!==window)throw new Error(tr('窗口已关闭'));if(result.canceled)return [];if(result.filePaths.length>4)throw new Error(tr('每条消息最多添加 4 张图片'));const images:ChatImage[]=[];for(const path of result.filePaths){if((await stat(path)).size>16*1024*1024)throw new Error(tr('图片超过 16 MiB'));const data=await readFile(path);if(this.ctx.blocked()||window.isDestroyed()||this.window!==window)throw new Error(tr('窗口已关闭'));if(data.length>16*1024*1024)throw new Error(tr('图片超过 16 MiB'));const image=nativeImage.createFromBuffer(data);images.push(this.image(image.toDataURL(),basename(path)));}return images;}
 toggle(){if(this.window?.isVisible()){this.hide();return;}this.open();}
 open(){if(this.ctx.blocked())return;this.target=this.ctx.target();if(this.window&&!this.window.isDestroyed()){if(this.window.isMinimized())this.window.restore();this.window.show();this.window.focus();this.window.webContents.send('clip:chat-show');return;}
  const layout=this.ctx.store().meta('ai-chat-sidebar',{open:false,added:258});this.sidebarOpen=layout?.open===true;this.sidebarAdded=Number.isFinite(layout?.added)&&layout.added>=0&&layout.added<=258?layout.added:258;
  const stored=this.ctx.store().meta('ai-chat-bounds',null) as Rectangle|null,saved=stored&&['x','y','width','height'].every(key=>Number.isFinite(stored[key as keyof Rectangle]))&&stored.width>0&&stored.height>0?stored:null;
  const area=(saved?screen.getDisplayMatching(saved):screen.getDisplayNearestPoint(screen.getCursorScreenPoint())).workArea,minWidth=Math.min(area.width,480+(this.sidebarOpen?258:0)),minHeight=Math.min(area.height,560),width=Math.min(area.width,Math.max(minWidth,saved?.width||660)),height=Math.min(area.height,Math.max(minHeight,saved?.height||600)),x=Math.max(area.x,Math.min(area.x+area.width-width,saved?.x??area.x+(area.width-width)/2)),y=Math.max(area.y,Math.min(area.y+area.height-height,saved?.y??area.y+(area.height-height)/2));
  const window=new BrowserWindow({x:Math.round(x),y:Math.round(y),width,height,minWidth,minHeight,show:false,title:tr('Clip · AI 对话'),frame:true,titleBarStyle:'hidden',titleBarOverlay:false,thickFrame:true,hasShadow:true,skipTaskbar:true,alwaysOnTop:this.options().onTop,resizable:true,maximizable:false,minimizable:false,backgroundColor:this.ctx.dark()?'#181818':'#ffffff',webPreferences:{additionalArguments:interfaceLanguageArguments(),preload:join(__dirname,'../preload/chat.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});this.window=window;
  window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',event=>event.preventDefault());window.webContents.on('will-attach-webview',event=>event.preventDefault());window.on('close',event=>{event.preventDefault();this.hide();});window.on('closed',()=>{if(this.window===window)this.window=undefined;clearTimeout(this.boundsTimer);});const boundsChanged=()=>{clearTimeout(this.boundsTimer);this.boundsTimer=setTimeout(()=>this.saveBounds(),250);};window.on('move',boundsChanged);window.on('resize',boundsChanged);
  window.on('focus',()=>clearTimeout(this.blurTimer));window.on('blur',()=>{clearTimeout(this.blurTimer);this.blurTimer=setTimeout(()=>{if(this.window===window&&!window.isDestroyed()&&!window.isFocused()&&!window.webContents.isDevToolsFocused()&&!this.ctx.blocked()&&!this.choosingImages&&!this.options().keepOpen)this.hide();},120);});
  window.once('ready-to-show',()=>{void (async()=>{if(this.ctx.blocked()||window.isDestroyed())return;const bounds={x:Math.round(x),y:Math.round(y),width,height};this.frameOffset={x:0,y:0,width:0,height:0};window.setOpacity(0);window.showInactive();for(let attempt=0;attempt<3;attempt++){this.placeBounds(bounds);await new Promise(resolve=>setTimeout(resolve,40));if(window.isDestroyed())return;const actual=window.getBounds();if(actual.x===bounds.x&&actual.y===bounds.y&&actual.width===bounds.width&&actual.height===bounds.height)break;this.frameOffset={x:this.frameOffset.x+bounds.x-actual.x,y:this.frameOffset.y+bounds.y-actual.y,width:this.frameOffset.width+bounds.width-actual.width,height:this.frameOffset.height+bounds.height-actual.height};}if(this.ctx.blocked()){window.hide();window.setOpacity(1);return;}if(window.isAlwaysOnTop()!==this.options().onTop)window.setAlwaysOnTop(this.options().onTop);window.setOpacity(1);window.focus();window.webContents.send('clip:chat-show');})().catch(()=>{if(!window.isDestroyed())window.setOpacity(1);});});void window.loadURL('clip://app/chat.html').catch(()=>{if(!window.isDestroyed())window.destroy();});
 }
 flushBounds(persist?:(bounds:Rectangle)=>void){clearTimeout(this.boundsTimer);if(this.window&&!this.window.isDestroyed()){const bounds=this.window.getBounds();if(persist)persist(bounds);else if(!this.ctx.blocked())this.ctx.store().setMeta('ai-chat-bounds',bounds);}}
 private saveBounds(){this.flushBounds();}
 hide(){clearTimeout(this.blurTimer);this.saveBounds();this.window?.hide();}
 emit(event:ChatEvent){if(this.window&&!this.window.isDestroyed()&&!this.ctx.blocked())this.window.webContents.send('clip:chat-event',event);}
 destroy(){clearTimeout(this.boundsTimer);clearTimeout(this.blurTimer);this.window?.destroy();this.window=undefined;this.target=undefined;}
}
