import {dialog} from 'electron';
import {exportAttachmentDirectory} from './attachment-export';
import type {BrowserWindow} from 'electron';
import {lstat,open,unlink} from 'node:fs/promises';
import {basename,extname,dirname,join,win32} from 'node:path';
import {randomUUID} from 'node:crypto';
import {imageSize} from 'image-size';
import type {Detail} from '../shared/types';
import {formatDefinition,htmlContext,type ContentInfo} from '../shared/formats';
import {localMetadataDrive} from './native';
import {commitRecording} from './recording-move';
const category=(path:string)=>{const ext=extname(path).toLowerCase();return /\.(png|jpe?g|gif|webp|bmp|tiff?|svg|heic|avif)$/.test(ext)?'图片':/\.(mp4|mkv|mov|avi|webm|wmv)$/.test(ext)?'视频':/\.(mp3|wav|m4a|aac|flac|ogg|wma)$/.test(ext)?'音频':/\.(pdf|docx?|xlsx?|pptx?|txt|rtf|md|csv)$/.test(ext)?'文档':ext?ext.slice(1).toUpperCase()+' 文件':'文件';};
export async function contentInfo(item:Detail,readFiles=false):Promise<ContentInfo>{const p=item.payload,result:ContentInfo={formats:[]};for(const [key,name,label]of [['text','Unicode 文本','纯文本'],['html','HTML','HTML 预览内容'],['rtf','RTF','RTF 预览内容']] as const)if(p[key]!==undefined)result.formats.push({name,label,bytes:Buffer.byteLength(p[key]!),exportable:false});if(p.png){const png=Buffer.from(p.png,'base64');result.formats.push({name:'PNG',label:'PNG 图像',bytes:png.length,exportable:true});if(png.length>=24)result.image={width:png.readUInt32BE(16),height:png.readUInt32BE(20)};}
 for(const f of p.formats||[]){const data=Buffer.from(f.data,'base64'),definition=formatDefinition(f.name)!;result.formats.push({name:f.name,label:definition.label,bytes:data.length,exportable:true});if(f.name==='HTML Format')result.sourceUrl=htmlContext(data).sourceUrl;if(!result.image&&definition.mime.startsWith('image/'))try{const s=imageSize(data);result.image={width:s.width,height:s.height};}catch{}}
 if(p.attachments){result.attachments=p.attachments.map(({data,...a},index)=>({...a,index,bytes:Buffer.byteLength(data,'base64')}));result.formats.push({name:'FileContents',label:'已保存的虚拟附件',bytes:result.attachments.reduce((n,a)=>n+a.bytes,0),exportable:false});}
 if(p.files){result.formats.push({name:'CF_HDROP',label:'Windows 文件引用',bytes:Buffer.byteLength(p.files.join('\0'),'utf16le')+22,exportable:false});result.files=[];for(const path of p.files){const entry:NonNullable<ContentInfo['files']>[number]={path,name:win32.basename(path),type:category(path),status:'not-read'};if(readFiles&&localMetadataDrive(path)&&!path.slice(2).includes(':'))try{const stats=await lstat(path);if(stats.isSymbolicLink()){entry.type='链接';}else{entry.status='available';entry.type=stats.isDirectory()?'文件夹':entry.type;entry.bytes=stats.isFile()?stats.size:undefined;entry.modified=stats.mtimeMs;}}catch(e){entry.status=(e as NodeJS.ErrnoException).code==='ENOENT'?'missing':'unreadable';}result.files.push(entry);}}return result;}
export async function exportFormat(window:BrowserWindow,item:Detail,name:unknown,protect:(path:string)=>void,valid:()=>boolean){const definition=formatDefinition(name);if(!definition)throw new Error('不可导出此格式');const encoded=item.payload.formats?.find(f=>f.name===name)?.data||(name==='PNG'?item.payload.png:undefined);if(!encoded)throw new Error('此记录未保留该原始格式');const data=Buffer.from(encoded,'base64'),live=()=>{if(!valid())throw new Error('记录已改变、删除或历史已锁定');};live();try{const choice=await dialog.showSaveDialog(window,{title:'另存内容（未加密的新文件）',defaultPath:`Clipper-original-${Date.now()}.${definition.extension}`,filters:[{name:definition.label,extensions:[definition.extension]}]});live();if(choice.canceled||!choice.filePath)return null;const target=extname(choice.filePath).toLowerCase()==='.'+definition.extension?choice.filePath:choice.filePath+'.'+definition.extension;protect(target);const staging=join(dirname(target),'.Clipper-format-'+randomUUID()+'.part');let file;try{file=await open(staging,'wx',0o600);await file.writeFile(data);await file.sync();await file.close();file=undefined;live();commitRecording(staging,target);return basename(target);}finally{await file?.close().catch(()=>{});await unlink(staging).catch(()=>{});}}finally{data.fill(0);}}

export async function exportAttachment(window:BrowserWindow,item:Detail,index:unknown,protect:(path:string)=>void,valid:()=>boolean){if(!Number.isInteger(index)||Number(index)<0||Number(index)>255)throw new Error('附件编号无效');const attachment=item.payload.attachments?.[Number(index)];if(!attachment)throw new Error('附件不存在');const live=()=>{if(!valid())throw new Error('记录已改变、删除或历史已锁定');};live();const choice=await dialog.showSaveDialog(window,{title:attachment.directory?'另存文件夹（未加密的新目录）':'另存附件（未加密的新文件）',defaultPath:win32.basename(attachment.name)});live();if(choice.canceled||!choice.filePath)return null;const target=choice.filePath;protect(target);if(attachment.directory)return exportAttachmentDirectory(item.payload.attachments!,attachment.name,target,valid);const staging=join(dirname(target),'.Clipper-attachment-'+randomUUID()+'.part'),data=Buffer.from(attachment.data,'base64');let file;try{file=await open(staging,'wx',0o600);await file.writeFile(data);if(attachment.modified!==undefined)await file.utimes(new Date(attachment.accessed??attachment.modified),new Date(attachment.modified));await file.sync();await file.close();file=undefined;live();commitRecording(staging,target);return basename(target);}finally{data.fill(0);await file?.close().catch(()=>{});await unlink(staging).catch(()=>{});}}
