import {watchCollectionWindow,flushCollectionWindow} from './collection-window';
import {t as tr} from '../shared/i18n';
import {interfaceLanguageArguments} from '../shared/i18n';
import {BrowserWindow,screen} from 'electron';
import {join} from 'node:path';
import type {Store} from './store';
import {nativeAvailable,foreground,foregroundBounds,mouseButtons} from './native';
import {desktopDefaults,validateDesktop,dockRect,clampRect,validRect,contains,outerEdgeAt,topShelfAt,coversDisplay,type DesktopOptions,type DesktopState,type DisplayInfo,type Rect} from '../shared/desktop';
interface Context {store():Store;blocked():boolean;quick():BrowserWindow;peekQuick():BrowserWindow|undefined;rememberTarget():void;dark():boolean;changed():void;enqueue<T>(fn:()=>T|Promise<T>):Promise<T>}
// Windows rounds frame dimensions at fractional scale factors. Correct the
// measured result so restoring a saved window does not grow it on every launch.
function setBounds(window:BrowserWindow,bounds:Rect){let request={...bounds};for(let i=0;i<3;i++){window.setBounds(request);const actual=window.getBounds();if(actual.width===bounds.width&&actual.height===bounds.height)break;request={...bounds,width:Math.max(1,request.width+bounds.width-actual.width),height:Math.max(1,request.height+bounds.height-actual.height)};}}
export class DesktopController {
 shelf:BrowserWindow|undefined;private timer?:NodeJS.Timeout;private disposed=false;private intent='';private entered=0;private disarmed=false;private awaySince=0;private shelfAway=0;private autoShelf=false;private placingUntil=0;private saveTimer?:NodeJS.Timeout;private boundQuick=new WeakSet<BrowserWindow>();
 constructor(private ctx:Context){this.updatePolling();screen.on('display-added',this.displaysChanged);screen.on('display-removed',this.displaysChanged);screen.on('display-metrics-changed',this.displaysChanged);}
 get options():DesktopOptions{return validateDesktop(this.ctx.store().meta('desktop-options',desktopDefaults));}
 private updatePolling(){const options=this.options,needed=!this.disposed&&(options.dockEnabled||options.shelfTop);if(needed&&!this.timer){this.timer=setInterval(()=>this.tick(),120);this.timer.unref();}else if(!needed&&this.timer){clearInterval(this.timer);this.timer=undefined;}}
 private displays():DisplayInfo[]{return screen.getAllDisplays().map((d,i)=>({id:d.id,name:d.label||tr`显示器 ${i+1}`,bounds:d.bounds,workArea:d.workArea}));}
 private display(displays=this.displays()){const options=this.options;return displays.find(d=>d.id===options.displayId)||displays.find(d=>d.id===screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).id)||displays[0];}
 state():DesktopState{return {options:this.options,displays:this.displays(),shelfVisible:!!this.shelf?.isVisible(),quickVisible:!!this.ctx.peekQuick()?.isVisible()};}
 configure(value:DesktopOptions){const previous=this.options;this.ctx.store().setMeta('desktop-options',value);this.updatePolling();this.intent='';this.disarmed=true;if(this.shelf){this.shelf.setAlwaysOnTop(value.shelfOnTop,'floating');if(!value.shelfTop&&this.autoShelf)this.shelf.hide();}const quick=this.ctx.peekQuick();if(quick){quick.setAlwaysOnTop(value.dockEnabled,'floating');if(quick.isVisible()&&(previous.dockEnabled!==value.dockEnabled||previous.dockEdge!==value.dockEdge||previous.displayId!==value.displayId))this.placeQuick(quick);}this.ctx.changed();}
 private placeQuick(window:BrowserWindow){const options=this.options,display=this.display();if(!display)return;if(window.isMaximized())window.unmaximize();window.setMinimumSize(280,240);window.setAlwaysOnTop(options.dockEnabled,'floating');setBounds(window,options.dockEnabled?dockRect(display.workArea,options.dockEdge):clampRect({x:display.workArea.x+(display.workArea.width-600)/2,y:display.workArea.y+(display.workArea.height-560)/2,width:600,height:560},display.workArea));}
 showQuick(activate=true){if(this.disposed||this.ctx.blocked())return;this.ctx.rememberTarget();const window=this.ctx.quick();if(!this.boundQuick.has(window)){this.boundQuick.add(window);window.on('hide',()=>{this.disarmed=true;this.intent='';});}this.placeQuick(window);const show=()=>{if(this.disposed||this.ctx.blocked()||window.isDestroyed())return;if(window.isMinimized())window.restore();activate?(window.show(),window.focus()):window.showInactive();this.placeQuick(window);flushCollectionWindow(window);};if(window.webContents.isLoading())window.webContents.once('did-finish-load',show);else show();this.disarmed=true;this.awaySince=0;}
 private createShelf(){this.placingUntil=Date.now()+500;const display=this.display(),saved=this.ctx.store().meta('desktop-shelf-bounds',null),initial=validRect(saved)?saved:{x:display.workArea.x+(display.workArea.width-380)/2,y:display.workArea.y+70,width:380,height:510},area=screen.getDisplayMatching(initial).workArea,bounds=clampRect(initial,area);
  const dark=this.ctx.dark(),window=new BrowserWindow({...bounds,minWidth:280,minHeight:220,minimizable:false,maximizable:false,title:tr('Clipper · 拖放窗口'),show:false,icon:join(__dirname,'../clipper.png'),backgroundColor:dark?'#181818':'#ffffff',titleBarStyle:'hidden',titleBarOverlay:false,frame:true,thickFrame:true,hasShadow:true,autoHideMenuBar:true,skipTaskbar:true,alwaysOnTop:this.options.shelfOnTop,webPreferences:{additionalArguments:interfaceLanguageArguments(),preload:join(__dirname,'../preload/shelf.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});this.shelf=window;
  window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('will-attach-webview',e=>e.preventDefault());window.on('close',event=>{if(!this.disposed){event.preventDefault();window.hide();}});window.on('hide',()=>{this.autoShelf=false;this.disarmed=true;this.intent='';});
  const save=()=>{if(this.disposed||Date.now()<this.placingUntil||window.isDestroyed())return;this.autoShelf=false;clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>{if(this.disposed||window.isDestroyed())return;const b=window.isMaximized()?window.getNormalBounds():window.getBounds();void this.ctx.enqueue(()=>{if(!this.disposed)this.ctx.store().setMeta('desktop-shelf-bounds',b);}).catch(()=>{});},300);};window.on('will-move',()=>{this.placingUntil=0;this.autoShelf=false;});window.on('will-resize',()=>{this.placingUntil=0;this.autoShelf=false;});window.on('move',save);window.on('resize',save);window.once('ready-to-show',()=>{if(this.disposed||window.isDestroyed()||this.autoShelf)return;clearTimeout(this.saveTimer);this.placingUntil=Date.now()+350;setBounds(window,bounds);});watchCollectionWindow(window);void window.loadURL('clipper://app/shelf.html');return window;
 }
 showShelf(activate=true,top=false){if(this.disposed||this.ctx.blocked())return;this.ctx.rememberTarget();const window=this.shelf&&!this.shelf.isDestroyed()?this.shelf:this.createShelf();this.autoShelf=top;this.shelfAway=0;this.disarmed=true;if(top){const a=this.display().workArea;this.placingUntil=Date.now()+350;setBounds(window,clampRect({x:a.x+(a.width-380)/2,y:a.y,width:380,height:470},a));}
  const show=()=>{if(this.disposed||this.ctx.blocked()||window.isDestroyed())return;if(window.isMinimized())window.restore();activate?(window.show(),window.focus()):window.showInactive();window.webContents.send('clipper:changed');};if(window.webContents.isLoading())window.webContents.once('did-finish-load',show);else show();
 }
 private displaysChanged=()=>{if(this.disposed||this.ctx.blocked())return;const quick=this.ctx.peekQuick();if(quick?.isVisible())this.placeQuick(quick);if(this.shelf&&!this.shelf.isDestroyed()){const b=this.shelf.getBounds(),area=screen.getDisplayMatching(b).workArea;this.placingUntil=Date.now()+350;setBounds(this.shelf,clampRect(b,area));}this.ctx.changed();};
 private tick(){if(this.disposed)return;try{if(this.ctx.blocked()||!nativeAvailable()){this.intent='';return;}const options=this.options;if(!options.dockEnabled&&!options.shelfTop)return;const point=screen.getCursorScreenPoint(),displays=this.displays(),display=this.display(displays),buttons=mouseButtons(),quick=this.ctx.peekQuick(),own=foreground()?.pid===process.pid,physical=foregroundBounds();if(!display)return;
  const full=physical&&!own&&coversDisplay(screen.screenToDipRect(null,physical),display);if(full){this.intent='';this.disarmed=true;if(quick?.isVisible())quick.hide();if(this.autoShelf)this.shelf?.hide();return;}
  const quickHit=options.dockEnabled&&outerEdgeAt(point,display,displays,options.dockEdge),shelfHit=options.shelfTop&&buttons.left&&topShelfAt(point,display,displays);if(!quickHit&&!shelfHit)this.disarmed=false;
  const now=Date.now(),down=buttons.left||buttons.right||buttons.middle;if(quick?.isVisible()&&options.dockEnabled&&options.autoHide){if(contains(quick.getBounds(),point,12)||down||quick.isFocused()){this.awaySince=0;}else{this.awaySince||=now;if(now-this.awaySince>650){quick.hide();this.awaySince=0;}}}
  if(this.autoShelf&&this.shelf?.isVisible()){if(contains(this.shelf.getBounds(),point,12)||down||this.shelf.isFocused())this.shelfAway=0;else{this.shelfAway||=now;if(now-this.shelfAway>900)this.shelf.hide();}}
  const intent=!own&&!this.disarmed?(shelfHit&&!this.shelf?.isVisible()?'shelf':quickHit&&!down&&!quick?.isVisible()?'quick':''):'';if(!intent){this.intent='';return;}if(this.intent!==intent){this.intent=intent;this.entered=now;return;}if(now-this.entered>=options.dwellMs){this.intent='';intent==='shelf'?this.showShelf(false,true):this.showQuick(false);}
 }catch{this.intent='';}}
 flushBounds(write?:(bounds:Electron.Rectangle)=>void){if(this.disposed||this.ctx.blocked()||this.autoShelf||!this.shelf||this.shelf.isDestroyed()||Date.now()<this.placingUntil)return;clearTimeout(this.saveTimer);const b=this.shelf.isMaximized()?this.shelf.getNormalBounds():this.shelf.getBounds();if(write)write(b);else this.ctx.store().setMeta('desktop-shelf-bounds',b);}
 dispose(){if(this.disposed)return;this.disposed=true;clearInterval(this.timer);clearTimeout(this.saveTimer);screen.removeListener('display-added',this.displaysChanged);screen.removeListener('display-removed',this.displaysChanged);screen.removeListener('display-metrics-changed',this.displaysChanged);this.shelf?.destroy();this.shelf=undefined;}
}
