import {watchCollectionWindow} from './collection-window';
import {t as tr} from '../shared/i18n';
import {interfaceLanguageArguments} from '../shared/i18n';
import {BrowserWindow,screen} from 'electron';
import {join} from 'node:path';
import type {Store} from './store';
import {nativeAvailable,foreground,foregroundBounds,mouseButtons} from './native';
import {desktopDefaults,validateDesktop,clampRect,validRect,contains,topShelfAt,coversDisplay,shelfCompactRect,dragGestureReady,type DesktopOptions,type DesktopState,type DisplayInfo,type Rect,type Point,type ShelfMode} from '../shared/desktop';
interface Context {store():Store;blocked():boolean;rememberTarget():void;dark():boolean;changed():void;enqueue<T>(fn:()=>T|Promise<T>):Promise<T>}
// Windows rounds frame dimensions at fractional scale factors. Correct the
// measured result so restoring a saved window does not grow it on every launch.
function setBounds(window:BrowserWindow,bounds:Rect){let request={...bounds};for(let i=0;i<3;i++){window.setBounds(request);const actual=window.getBounds();if(actual.width===bounds.width&&actual.height===bounds.height)break;request={...bounds,width:Math.max(1,request.width+bounds.width-actual.width),height:Math.max(1,request.height+bounds.height-actual.height)};}}
export class DesktopController {
 shelf:BrowserWindow|undefined;shelfMode:ShelfMode='expanded';private expandedBounds?:Rect;private resizeTimer?:NodeJS.Timeout;private resizeVersion=0;private resizing=false;private timer?:NodeJS.Timeout;private disposed=false;private intent='';private entered=0;private disarmed=false;private shelfAway=0;private autoShelf=false;private placingUntil=0;private saveTimer?:NodeJS.Timeout;private dragOrigin?:Point;private dragBounds?:Rect;private dragSource?:number;private dragStarted=0;private dragUsed=false;private dragSuppressed=false;
 get activeShelf(){return this.shelf;}
 constructor(private ctx:Context){this.updatePolling();screen.on('display-added',this.displaysChanged);screen.on('display-removed',this.displaysChanged);screen.on('display-metrics-changed',this.displaysChanged);}
 get options():DesktopOptions{return validateDesktop(this.ctx.store().meta('desktop-options',desktopDefaults));}
 private updatePolling(){const options=this.options,needed=!this.disposed&&(options.shelfTop||options.shelfAutoDrag);if(needed&&!this.timer){this.timer=setInterval(()=>this.tick(),100);this.timer.unref();}else if(!needed&&this.timer){clearInterval(this.timer);this.timer=undefined;this.resetDrag();}}
 private resetDrag(){this.dragOrigin=undefined;this.dragBounds=undefined;this.dragSource=undefined;this.dragStarted=0;this.dragUsed=false;this.dragSuppressed=false;}
 private displays():DisplayInfo[]{return screen.getAllDisplays().map((d,i)=>({id:d.id,name:d.label||tr`显示器 ${i+1}`,bounds:d.bounds,workArea:d.workArea}));}
 private display(displays=this.displays()){const options=this.options;return displays.find(d=>d.id===options.displayId)||displays.find(d=>d.id===screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).id)||displays[0];}
 state():DesktopState{return {options:this.options,displays:this.displays(),shelfVisible:!!this.activeShelf?.isVisible()};}
 configure(value:DesktopOptions){const previous=this.options;this.ctx.store().setMeta('desktop-options',value);this.updatePolling();this.resetDrag();this.intent='';this.disarmed=true;this.shelf?.setAlwaysOnTop(value.shelfOnTop,'floating');if(!value.shelfTop&&!value.shelfAutoDrag&&this.autoShelf)this.shelf?.hide();if(this.shelf?.isVisible()&&this.shelfMode==='compact'&&previous.shelfPosition!==value.shelfPosition)setBounds(this.shelf,shelfCompactRect(this.display().workArea,value.shelfPosition));this.ctx.changed();}
 private createShelf(){this.placingUntil=Date.now()+500;const display=this.display(),saved=this.ctx.store().meta('desktop-shelf-bounds',null),initial=validRect(saved)?saved:{x:display.workArea.x+(display.workArea.width-380)/2,y:display.workArea.y+70,width:380,height:510},area=screen.getDisplayMatching(initial).workArea;this.expandedBounds||=clampRect(initial,area);const bounds=this.shelfMode==='compact'?shelfCompactRect(display.workArea,this.options.shelfPosition):this.expandedBounds;
  const dark=this.ctx.dark(),window=new BrowserWindow({...bounds,minWidth:280,minHeight:130,resizable:true,minimizable:false,maximizable:false,title:tr('Clipper · 拖放窗口'),show:false,icon:join(__dirname,'../clipper.png'),backgroundColor:dark?'#181818':'#ffffff',titleBarStyle:'hidden',titleBarOverlay:false,frame:true,thickFrame:true,hasShadow:true,autoHideMenuBar:true,skipTaskbar:true,alwaysOnTop:this.options.shelfOnTop,webPreferences:{additionalArguments:interfaceLanguageArguments(),preload:join(__dirname,'../preload/shelf.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});this.shelf=window;
  window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('will-attach-webview',e=>e.preventDefault());window.on('close',event=>{if(!this.disposed){event.preventDefault();window.hide();}});window.on('hide',()=>{if(this.activeShelf===window)this.autoShelf=false;this.disarmed=true;this.intent='';});
  const save=()=>{if(this.disposed||this.resizing||this.shelfMode==='compact'||Date.now()<this.placingUntil||window.isDestroyed())return;clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>{if(this.disposed||window.isDestroyed()||this.resizing||this.shelfMode==='compact')return;const b=window.isMaximized()?window.getNormalBounds():window.getBounds();this.expandedBounds=b;void this.ctx.enqueue(()=>{if(!this.disposed)this.ctx.store().setMeta('desktop-shelf-bounds',b);}).catch(()=>{});},300);};window.on('will-move',()=>{if(!this.resizing)this.placingUntil=0;});window.on('will-resize',()=>{if(!this.resizing)this.placingUntil=0;});window.on('move',save);window.on('resize',save);window.once('ready-to-show',()=>{if(this.disposed||window.isDestroyed())return;clearTimeout(this.saveTimer);this.placingUntil=Date.now()+350;setBounds(window,this.shelfMode==='compact'?shelfCompactRect(this.display().workArea,this.options.shelfPosition):this.expandedBounds!);});
  watchCollectionWindow(window);void window.loadURL('clipper://app/shelf.html');return window;
 }
 setShelfMode(mode:ShelfMode,reducedMotion=false,instant=false,activate=true){
  if(this.disposed||this.ctx.blocked())return;
  const window=this.shelf&&!this.shelf.isDestroyed()?this.shelf:this.createShelf();
  const start=window.getBounds();
  if(this.shelfMode==='expanded'&&mode==='compact'&&!this.resizing){this.expandedBounds=start;void this.ctx.enqueue(()=>{if(!this.disposed)this.ctx.store().setMeta('desktop-shelf-bounds',start);}).catch(()=>{});}
  this.shelfMode=mode;this.autoShelf=false;this.shelfAway=0;
  const destination=mode==='compact'?shelfCompactRect(this.display().workArea,this.options.shelfPosition):this.expandedBounds!;
  const version=++this.resizeVersion;clearInterval(this.resizeTimer);this.resizeTimer=undefined;
  const finish=()=>{if(version!==this.resizeVersion||window.isDestroyed())return;window.setBounds(destination);this.resizing=false;this.placingUntil=Date.now()+300;const content=window.getContentBounds();window.webContents.send('clipper:shelf-transition',false,mode,{width:content.width,height:content.height});window.webContents.send('clipper:changed');};
  if(!window.isVisible()||instant||reducedMotion){this.resizing=true;finish();if(window.webContents.isLoading())window.webContents.once('did-finish-load',()=>{if(version===this.resizeVersion){activate?(window.show(),window.focus()):window.showInactive();window.webContents.send('clipper:changed');}});else{activate?(window.show(),window.focus()):window.showInactive();window.webContents.send('clipper:changed');}return;}
  this.resizing=true;window.webContents.send('clipper:shelf-transition',true,mode);const began=performance.now(),duration=240;
  this.resizeTimer=setInterval(()=>{if(version!==this.resizeVersion||window.isDestroyed()){clearInterval(this.resizeTimer);return;}const progress=Math.min(1,(performance.now()-began)/duration),ease=1-Math.pow(1-progress,3);window.setBounds({x:Math.round(start.x+(destination.x-start.x)*ease),y:Math.round(start.y+(destination.y-start.y)*ease),width:Math.round(start.width+(destination.width-start.width)*ease),height:Math.round(start.height+(destination.height-start.height)*ease)});if(progress===1){clearInterval(this.resizeTimer);this.resizeTimer=undefined;finish();}},20);
 }
 showShelf(activate=true,top=false){if(this.disposed||this.ctx.blocked())return;this.ctx.rememberTarget();this.disarmed=true;this.setShelfMode(top?'compact':'expanded',false,false,activate);this.autoShelf=top;this.shelfAway=0;}
 private displaysChanged=()=>{if(this.disposed||this.ctx.blocked())return;if(this.shelf&&!this.shelf.isDestroyed()){const b=this.shelf.getBounds(),area=screen.getDisplayMatching(b).workArea;this.placingUntil=Date.now()+350;setBounds(this.shelf,this.shelfMode==='compact'?shelfCompactRect(this.display().workArea,this.options.shelfPosition):clampRect(b,area));}this.ctx.changed();};
 private tick(){if(this.disposed)return;try{if(this.ctx.blocked()||!nativeAvailable()){this.intent='';this.resetDrag();return;}const options=this.options;if(!options.shelfTop&&!options.shelfAutoDrag)return;const point=screen.getCursorScreenPoint(),displays=this.displays(),display=this.display(displays),buttons=mouseButtons(),front=foreground(),own=front?.pid===process.pid,physical=foregroundBounds();if(!display)return;
  const now=Date.now();if(!buttons.left||own)this.resetDrag();else if(!this.dragOrigin){this.dragOrigin=point;this.dragBounds=physical;this.dragSource=front?.hwnd;this.dragStarted=now;}else if(front?.hwnd===this.dragSource&&this.dragBounds&&physical&&["x","y","width","height"].some(key=>Math.abs(physical[key as keyof Rect]-this.dragBounds![key as keyof Rect])>5))this.dragSuppressed=true;
  const full=physical&&!own&&coversDisplay(screen.screenToDipRect(null,physical),display);if(full&&!options.shelfAutoDrag){this.intent='';this.disarmed=true;if(this.autoShelf)this.activeShelf?.hide();return;}
  const shelfHit=options.shelfTop&&!full&&buttons.left&&topShelfAt(point,display,displays);if(!shelfHit)this.disarmed=false;
  const down=buttons.left||buttons.right||buttons.middle;
  if(this.autoShelf&&this.activeShelf?.isVisible()&&!this.resizing){if(contains(this.activeShelf.getBounds(),point,12)||down||this.activeShelf.isFocused())this.shelfAway=0;else{this.shelfAway||=now;if(now-this.shelfAway>900)this.activeShelf.hide();}}
  if(options.shelfAutoDrag&&buttons.left&&!own&&!this.dragSuppressed&&!this.dragUsed&&this.dragOrigin&&dragGestureReady(this.dragOrigin,point,now-this.dragStarted)&&!this.activeShelf?.isVisible()){this.dragUsed=true;this.intent='';this.showShelf(false,true);return;}
  if(!options.shelfTop){this.intent='';return;}
  const intent=!own&&!this.disarmed&&shelfHit&&!this.activeShelf?.isVisible()?'shelf':'';if(!intent){this.intent='';return;}if(this.intent!==intent){this.intent=intent;this.entered=now;return;}if(now-this.entered>=options.dwellMs){this.intent='';this.showShelf(false,true);}
 }catch{this.intent='';}}
 flushBounds(write?:(bounds:Electron.Rectangle)=>void){if(this.disposed||this.ctx.blocked()||this.autoShelf||this.resizing||this.shelfMode==='compact'||!this.shelf||this.shelf.isDestroyed()||Date.now()<this.placingUntil)return;clearTimeout(this.saveTimer);const b=this.shelf.isMaximized()?this.shelf.getNormalBounds():this.shelf.getBounds();if(write)write(b);else this.ctx.store().setMeta('desktop-shelf-bounds',b);}
 dispose(){if(this.disposed)return;this.disposed=true;clearInterval(this.timer);clearInterval(this.resizeTimer);clearTimeout(this.saveTimer);screen.removeListener('display-added',this.displaysChanged);screen.removeListener('display-removed',this.displaysChanged);screen.removeListener('display-metrics-changed',this.displaysChanged);this.shelf?.destroy();this.shelf=undefined;}
}
