import {BrowserWindow,dialog,ipcMain,net,nativeImage,session} from 'electron';
import {join,resolve,dirname,extname,basename} from 'node:path';
import {pathToFileURL} from 'node:url';
import {open,unlink} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {editSize} from '../shared/image-edit';
import {validatePayload} from '../shared/core';
import type {Detail,Payload} from '../shared/types';
import {thumbnail} from './clipboard';
import {commitRecording} from './recording-move';
interface Context{blocked():boolean;dark():boolean;get(id:string):Detail;protect(path:string):void;commit(id:string,hash:string,payload:Payload,mode:'history'|'copy',valid:()=>boolean):Promise<string>;background<T>(task:Promise<T>):Promise<T>}
const URL='clipper://app/image-editor.html';
export class ImageEditorService{
 window?:BrowserWindow;private source?:{id:string;hash:string;name:string};private png?:Buffer;private token='';private generation=0;private dirty=false;private busy=false;private closing=false;
 constructor(private ctx:Context){const partition=session.fromPartition('clipper-image-editor'),renderer=resolve(__dirname,'../renderer');partition.setPermissionCheckHandler(()=>false);partition.setPermissionRequestHandler((_w,_p,cb)=>cb(false));partition.on('will-download',e=>e.preventDefault());partition.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','file://*/*']},(_r,cb)=>cb({cancel:true}));partition.protocol.handle('clipper',request=>{const u=new globalThis.URL(request.url);if(u.hostname!=='app')return new Response(null,{status:404});if(u.pathname==='/edit-source/'+this.token&&this.token&&this.png&&!ctx.blocked())return new Response(new Uint8Array(this.png),{headers:{'Content-Type':'image/png','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});const name=u.pathname.slice(1);if(!['image-editor.html','image-editor.js','image-editor.css'].includes(name))return new Response(null,{status:404});return net.fetch(pathToFileURL(join(renderer,name)).toString());});
  const handle=(name:string,fn:(...args:any[])=>unknown)=>ipcMain.handle('clipper:image-'+name,(event,...args)=>{if(ctx.blocked()||!this.window||event.sender!==this.window.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!==URL)throw new Error('拒绝访问图片编辑');return ctx.background(Promise.resolve().then(()=>{if(ctx.blocked())throw new Error('图片编辑已失效');return fn(...args);}));});
  handle('state',()=>({url:'clipper://app/edit-source/'+this.token,name:this.source?.name||'',dark:ctx.dark()}));handle('dirty',value=>{if(typeof value!=='boolean'||this.busy)throw new Error('图片编辑状态无效');this.dirty=value;});handle('save',(png,mode)=>this.save(png,mode));
 }
 get hasUnsaved(){return this.dirty||this.busy;}
 async open(id:string){if(this.ctx.blocked())throw new Error('请先解锁历史');if(this.window&&!this.window.isDestroyed()){this.window.show();this.window.focus();if(this.source?.id!==id)throw new Error('请先关闭当前图片编辑，再打开另一张图片');return;}const item=this.ctx.get(id);if(!item.payload.png)throw new Error('仅支持图片记录');thumbnail(item.payload);const png=Buffer.from(item.payload.png,'base64');editSize(png.readUInt32BE(16),png.readUInt32BE(20));this.png=png;this.token=randomUUID();this.source={id,hash:item.hash,name:item.title};const dark=this.ctx.dark(),window=new BrowserWindow({width:1080,height:800,minWidth:760,minHeight:620,title:'Clipper · 图片编辑',show:false,autoHideMenuBar:true,titleBarStyle:'hidden',titleBarOverlay:{height:46,color:dark?'#181818':'#fff',symbolColor:dark?'#eee':'#222'},backgroundColor:dark?'#181818':'#fff',webPreferences:{session:session.fromPartition('clipper-image-editor'),preload:join(__dirname,'../preload/image-editor.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});this.window=window;window.setContentProtection(true);window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('will-attach-webview',e=>e.preventDefault());window.webContents.on('render-process-gone',()=>this.abort());window.on('close',e=>{e.preventDefault();if(!this.hasUnsaved){this.abort();return;}if(this.closing)return;this.closing=true;const generation=this.generation;void dialog.showMessageBox(window,{type:'question',message:'放弃尚未保存的图片修改？',buttons:['继续编辑','放弃并关闭'],defaultId:0,cancelId:0}).then(result=>{if(generation===this.generation&&result.response===1)this.abort();}).catch(()=>{}).finally(()=>this.closing=false);});window.on('closed',()=>{if(this.window===window)this.abort();});try{await window.loadURL(URL);if(!window.isDestroyed()&&!this.ctx.blocked())window.show();}catch(e){this.abort();throw e;}}
 private live(generation:number){if(generation!==this.generation||this.ctx.blocked()||!this.source)throw new Error('图片编辑已取消');const item=this.ctx.get(this.source.id);if(item.hash!==this.source.hash)throw new Error('原图内容已改变，请重新打开图片');}
 private async save(value:unknown,mode:unknown){if(this.busy)throw new Error('正在保存，请稍后');if(!['history','copy','export'].includes(mode as string))throw new Error('保存方式无效');const generation=this.generation;this.live(generation);const payload=validatePayload({png:value as string});thumbnail(payload);const png=Buffer.from(payload.png!,'base64');editSize(png.readUInt32BE(16),png.readUInt32BE(20));const decoded=nativeImage.createFromBuffer(png).getSize();editSize(decoded.width,decoded.height);this.busy=true;try{if(mode!=='export'){const result=await this.ctx.commit(this.source!.id,this.source!.hash,payload,mode as 'history'|'copy',()=>generation===this.generation&&!this.ctx.blocked());this.live(generation);if(mode==='history')this.dirty=false;return result;}
   const choice=await dialog.showSaveDialog(this.window!,{title:'编辑图片另存为（未加密的新文件）',defaultPath:'Clipper-edit-'+new Date().toISOString().replaceAll(':','-').slice(0,19)+'.png',filters:[{name:'PNG 图片',extensions:['png']}]});this.live(generation);if(choice.canceled||!choice.filePath)return null;const target=extname(choice.filePath).toLowerCase()==='.png'?choice.filePath:choice.filePath+'.png';this.ctx.protect(target);const staging=join(dirname(target),'.Clipper-image-'+randomUUID()+'.part');let file;try{file=await open(staging,'wx',0o600);await file.writeFile(png);await file.sync();await file.close();file=undefined;this.live(generation);commitRecording(staging,target);this.dirty=false;return basename(target);}finally{await file?.close().catch(()=>{});await unlink(staging).catch(()=>{});}
  }finally{png.fill(0);if(generation===this.generation)this.busy=false;}}
 abort(){this.generation++;this.dirty=false;this.busy=false;this.source=undefined;this.token='';this.png?.fill(0);this.png=undefined;const window=this.window;this.window=undefined;if(window&&!window.isDestroyed())window.destroy();}
}
