import {t as tr} from '../shared/i18n';
import {documentInformation} from './document-info';
import {validateDIB} from '../shared/formats';
import {mp4Information} from './metadata-mp4';
import exifr from 'exifr';
import {imageSize} from 'image-size';
import {PDFString} from 'pdf-lib';
import {DOMParser} from '@xmldom/xmldom';
import {fromBuffer,open,type ZipFile,type Entry} from 'yauzl';
import {readFile} from 'node:fs/promises';
import {metadataKind,validateMetadataResult,type MetadataResult,type MetadataKey} from '../shared/metadata';
export interface MetadataInput {name:string;size:number;path?:string;bytes?:Uint8Array}
const maxDocument=64*1024*1024;
const xmlEntries=new Set(['docProps/core.xml','docProps/app.xml','xl/workbook.xml']);
async function office(input:MetadataInput){return new Promise<{xml:Map<string,string>;slides:number}>((resolve,reject)=>{
 const opened=(error:Error|null,zip?:ZipFile)=>{if(error||!zip){reject(new Error(tr('无法读取文档压缩结构')));return;}let count=0,total=0,slides=0,done=false;const xml=new Map<string,string>(),seen=new Set<string>();const fail=(error:unknown)=>{if(done)return;done=true;zip.close();reject(error);};zip.on('error',()=>fail(new Error(tr('文档压缩结构损坏'))));zip.on('end',()=>{if(done)return;done=true;resolve({xml,slides});});
 zip.on('entry',(entry:Entry)=>{if(++count>20000)return fail(new Error(tr('文档条目超过 20,000')));if(/^ppt\/slides\/slide\d+\.xml$/.test(entry.fileName)){if(seen.has(entry.fileName))return fail(new Error(tr('文档幻灯片条目重复')));seen.add(entry.fileName);slides++;}if(!xmlEntries.has(entry.fileName)){zip.readEntry();return;}if(seen.has(entry.fileName)||entry.generalPurposeBitFlag&1||entry.uncompressedSize>1024*1024)return fail(new Error(tr('文档属性重复、加密或过大')));seen.add(entry.fileName);zip.openReadStream(entry,(error,stream)=>{if(error||!stream)return fail(new Error(tr('无法读取文档属性')));const chunks:Buffer[]=[];let size=0;stream.on('data',(chunk:Buffer)=>{size+=chunk.length;total+=chunk.length;if(size>1024*1024||total>4*1024*1024){stream.destroy();fail(new Error(tr('文档属性解压后过大')));return;}chunks.push(chunk);});stream.on('error',()=>fail(new Error(tr('文档属性长度或压缩数据无效'))));stream.on('end',()=>{if(done)return;const data=Buffer.concat(chunks);let text:string;try{if(data[0]===0xff&&data[1]===0xfe)text=new TextDecoder('utf-16le',{fatal:true}).decode(data);else if(data[0]===0xfe&&data[1]===0xff)text=new TextDecoder('utf-16be',{fatal:true}).decode(data);else text=new TextDecoder('utf-8',{fatal:true}).decode(data);}catch{return fail(new Error(tr('文档属性编码无效')));}xml.set(entry.fileName,text);zip.readEntry();});});});zip.readEntry();
 };
 if(input.path)open(input.path,{lazyEntries:true,autoClose:true,validateEntrySizes:true},opened);else fromBuffer(Buffer.from(input.bytes!),{lazyEntries:true,autoClose:true,validateEntrySizes:true},opened);
});}
export async function inspectMetadata(input:MetadataInput,includeLocation=false,password=''):Promise<MetadataResult>{
 const category=metadataKind(input.name);if(!category)throw new Error(tr('暂不支持此文件的内部信息'));if(!input.size||input.size>(category==='media'?2*1024**3:maxDocument))throw new Error(category==='media'?tr('媒体文件须为 1 字节至 2 GiB'):tr('图片与文档须为 1 字节至 64 MiB'));
 const result:MetadataResult={category,name:input.name.slice(0,255),size:input.size,fields:[]};const add=(key:MetadataKey,value:unknown)=>{if(value===undefined||value===null||value===''||typeof value==='number'&&!Number.isFinite(value))return;const s=(value instanceof Date?(Number.isFinite(value.getTime())?value.toISOString():''):Array.isArray(value)?value.slice(0,50).join('、'):String(value)).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,'').trim();if(s)result.fields.push({key,value:s.length>2048?s.slice(0,2047)+'…':s});};
 const bytes=async()=>input.bytes?Buffer.from(input.bytes):readFile(input.path!);
 if(category==='image'){const data=await bytes();if(/\.dib$/i.test(input.name)){const info=validateDIB(data,data.readUInt32LE(0)===124);add('format','DIB');add('width',info.width+' px');add('height',info.height+' px');add('bitDepth',data.readUInt16LE(data.readUInt32LE(0)===12?10:14));if(data.readUInt32LE(0)>=108)add('colorSpace','0x'+data.readUInt32LE(56).toString(16));return validateMetadataResult(result);}let s;try{s=imageSize(data);}catch{throw new Error(tr('图片格式损坏或暂不支持'));}add('format',s.type?.toUpperCase());add('width',s.width+' px');add('height',s.height+' px');const fields={Make:'make',Model:'model',LensModel:'lens',DateTimeOriginal:'taken',ExposureTime:'exposure',FNumber:'aperture',ISO:'iso',Orientation:'orientation',ColorSpace:'colorSpace'} as const;let tags:any;try{if(['jpg','tiff','png','heif','heic','avif'].includes(s.type||''))tags=await exifr.parse(data,{pick:[...Object.keys(fields),...(includeLocation?['GPSLatitude','GPSLongitude','GPSLatitudeRef','GPSLongitudeRef','GPSAltitude','GPSAltitudeRef']:[])],gps:includeLocation,reviveValues:false,ifd1:false,makerNote:false,userComment:false,icc:false,iptc:false,xmp:false});}catch{throw new Error(tr('图片内部信息损坏或暂不支持'));}for(const [from,to]of Object.entries(fields))add(to,tags?.[from]);if(includeLocation){add('latitude',tags?.latitude);add('longitude',tags?.longitude);add('altitude',Number.isFinite(tags?.GPSAltitude)?(tags.GPSAltitudeRef===1?-tags.GPSAltitude:tags.GPSAltitude)+' m':undefined);}}
 else if(category==='media'){const {parseFile,parseBuffer}=await import('music-metadata');const options={skipCovers:true,duration:true,includeChapters:false};const m=input.path?await parseFile(input.path,options):await parseBuffer(input.bytes!,{path:input.name,size:input.size},options),f=m.format,c=m.common;add('format',f.container);add('codec',f.codec);add('duration',Number.isFinite(f.duration)?f.duration!.toFixed(3)+' s':undefined);add('bitrate',Number.isFinite(f.bitrate)?(f.bitrate!/1000).toFixed(1)+' kbps':undefined);add('sampleRate',Number.isFinite(f.sampleRate)?f.sampleRate+' Hz':undefined);add('channels',f.numberOfChannels);add('bitDepth',f.bitsPerSample);add('title',c.title);add('artist',c.artists||c.artist);add('album',c.album);add('year',c.year);add('genre',c.genre);add('track',c.track.no===null?undefined:c.track.no+(c.track.of?'/'+c.track.of:''));const video=(f.trackInfo||[]).filter(t=>t.video).slice(0,8).map(t=>{const v=t.video!;return [t.codecName,v.pixelWidth&&v.pixelHeight?`${v.pixelWidth} × ${v.pixelHeight} px`:undefined].filter(Boolean).join(' · ');});if(/\.(mp4|m4a|m4v|mov)$/i.test(input.name)){const extra=await mp4Information(input);if(!Number.isFinite(f.duration)&&extra.duration!==undefined)add('duration',extra.duration.toFixed(3)+' s');if(!video.length)video.push(...extra.videos);}add('video',video.length?video:undefined);}
 else if(category==='pdf'){const raw=await bytes();try{const data=await documentInformation(raw,input.name,'pdf',password);for(const[key,value]of Object.entries(data.fields||{})){if(['created','modified'].includes(key)){try{add(key as MetadataKey,PDFString.of(String(value)).decodeDate());}catch{}}else add(key as MetadataKey,value);}}finally{raw.fill(0);}}
 else{let source=input,plain:Buffer|undefined;const raw=await bytes();try{if(raw.subarray(0,8).toString('hex')==='d0cf11e0a1b11ae1'){const native=await documentInformation(raw,input.name,'office',password);if(native.fields){for(const[key,value]of Object.entries(native.fields))add(key as MetadataKey,['created','modified'].includes(key)&&typeof value==='number'?new Date(value):value);return validateMetadataResult(result);}plain=native.package;if(!plain)throw new Error(tr('文档数据、密码校验或内部结构无效'));source={name:input.name,size:plain.length,bytes:plain};add('encryption','Office password');}const data=await office(source),kind=input.name.split('.').pop()!.toUpperCase();add('format',kind);const parse=(value:string)=>{if(/<!DOCTYPE|<!ENTITY/i.test(value))throw new Error(tr('不接受包含外部实体或 DTD 的文档属性'));return new DOMParser({onError:(level,message)=>{if(level!=='warning')throw new Error(tr('文档属性 XML 无效'));}}).parseFromString(value,'application/xml');};const texts=(doc:ReturnType<typeof parse>,name:string)=>{const all=doc.getElementsByTagName('*');for(let i=0;i<all.length;i++)if(all[i].localName===name)return all[i].textContent;};const core=data.xml.get('docProps/core.xml');if(core){const doc=parse(core);for(const [name,key]of Object.entries({title:'title',creator:'author',subject:'subject',keywords:'keywords',description:'description',lastModifiedBy:'lastAuthor',revision:'revision',created:'created',modified:'modified',category:'category'}))add(key as MetadataKey,texts(doc,name));}const app=data.xml.get('docProps/app.xml');if(app){const doc=parse(app);for(const [name,key]of Object.entries({Application:'application',Company:'company',Words:'words',Pages:'declaredPages'}))add(key as MetadataKey,texts(doc,name));}if(/^(PPTX|PPTM|POTX|POTM)$/.test(kind))add('slides',data.slides);if(/^(XLSX|XLSM|XLTX|XLTM)$/.test(kind)&&data.xml.has('xl/workbook.xml')){const doc=parse(data.xml.get('xl/workbook.xml')!);add('sheets',doc.getElementsByTagNameNS('http://schemas.openxmlformats.org/spreadsheetml/2006/main','sheet').length);}if(result.fields.length===1)throw new Error(tr('文档未提供可读取的内部属性'));}finally{raw.fill(0);plain?.fill(0);}}
 return validateMetadataResult(result);
}
