import {rendererAssetAllowed} from '../shared/renderer-assets';
import {confirmWindow} from './window-confirm';
import {t as tr} from '../shared/i18n';
import {interfaceLanguageArguments} from '../shared/i18n';
import {displaySignature,type Region} from '../shared/region';
import {stat} from 'node:fs/promises';
import {windowExists,captureWindowInfo} from './native';
import {app,BrowserWindow,screen,nativeImage,dialog,ipcMain,net,session,type Session} from 'electron';
import {RecordingSources} from './recording-sources';
import {join,resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {Readable} from 'node:stream';
import {RecordingFile} from './recording-file';
import {recordingOptions,recordingExtension,recordingContentType,validRecordingMime,recordingRange,RECORD_SECONDS,RECORD_BYTES,RECORD_CHUNK,type RecordingOptions,type RecordingPhase,type RecordingState,type RecordingSource} from '../shared/recording';
interface Context{chooseRegion(displayId:number):Promise<Region|null>;cancelRegion():void;blocked():boolean;dark():boolean;prepare():void;protect(file:string):void;copy(file:string,valid:()=>boolean):Promise<void>;windows():BrowserWindow[];background<T>(task:Promise<T>):Promise<T>}
const URL='clipper://app/recorder.html';
export class RecordingService {
 window?:BrowserWindow;private selectedRegion?:{token:string;region:Region};private region?:Region;private picking=false;private session:Session;private file?:RecordingFile;private phase:RecordingPhase='idle';private token='';private options?:RecordingOptions;private mime='';private seconds=0;private message='';private saved='';private savedFile?:{path:string;size:number;mtimeMs:number;ino:number};private generation=0;private heartbeatAt=0;private created=0;private displayGrant=false;private micGrant=false;private source?:Electron.DesktopCapturerSource;private shown:BrowserWindow[]=[];private pendingBytes=0;private timer:NodeJS.Timeout;private busyClose=false;private initError='';
 private sourceChoices=new Map<string,{source:Electron.DesktopCapturerSource;created:number;pid?:number;executable?:string;signature?:string}>();private listing=0;
 readonly directory=join(app.getPath('userData'),'work','recording');
 private previews=new RecordingSources();
 constructor(private ctx:Context){this.session=session.fromPartition('clipper-recording');const renderer=resolve(__dirname,'../renderer');this.session.protocol.handle('clipper',request=>{const u=new globalThis.URL(request.url);if(u.hostname==='app'&&u.pathname.startsWith('/recording/'))return this.media(request);const name=u.pathname.slice(1);if(u.hostname!=='app'||!rendererAssetAllowed('recording',name))return new Response('Not found',{status:404});return net.fetch(pathToFileURL(join(renderer,name)).toString());});
  this.session.on('will-download',event=>event.preventDefault());
  this.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','file://*/*']},(_d,cb)=>cb({cancel:true}));
  this.session.setPermissionCheckHandler((wc,p,_o,d)=>wc===this.window?.webContents&&d.isMainFrame&&d.requestingUrl===URL&&!this.ctx.blocked()&&(p==='fullscreen'&&this.phase==='ready'||this.armed()&&p==='media'&&d.mediaType==='audio'&&!!this.options?.microphone));
  this.session.setPermissionRequestHandler((wc,p,cb,d)=>{let allowed=wc===this.window?.webContents&&d.isMainFrame&&d.requestingUrl===URL&&!this.ctx.blocked()&&p==='fullscreen'&&this.phase==='ready';if(wc===this.window?.webContents&&d.isMainFrame&&d.requestingUrl===URL&&this.armed()&&p==='media'&&'mediaTypes'in d&&d.mediaTypes){if(d.mediaTypes.length===0)allowed=this.needsDisplay()&&!this.displayGrant;else if(d.mediaTypes.length===1&&d.mediaTypes[0]==='audio'&&this.options?.microphone&&!this.micGrant){allowed=true;this.micGrant=true;}}cb(allowed);});
  this.session.setDisplayMediaRequestHandler((request,callback)=>{if(!this.armed()||this.displayGrant||request.frame!==this.window?.webContents.mainFrame||request.frame?.url!==URL||!request.videoRequested||request.audioRequested!==!!this.options?.systemAudio||!this.needsDisplay()){callback({});return;}this.displayGrant=true;callback({video:this.options?.mode==='audio'?this.window!.webContents.mainFrame:this.source,audio:this.options?.systemAudio?'loopback':undefined});});
  const handle=(name:string,fn:(...args:any[])=>unknown)=>ipcMain.handle('clipper:record-'+name,(event,...args)=>{if(this.ctx.blocked()||!this.window||event.sender!==this.window.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!==URL)throw new Error(tr('拒绝访问录制'));return this.ctx.background(Promise.resolve().then(()=>{if(this.ctx.blocked())throw new Error(tr('录制已锁定'));return fn(...args);}));});
  handle('choose-region',source=>this.chooseRegion(source));handle('state',()=>this.state());handle('sources',type=>this.sources(type));handle('arm',value=>this.arm(value));handle('started',(token,mime)=>this.started(token,mime));handle('chunk',(token,index,data)=>this.chunk(token,index,data));handle('heartbeat',(token,seconds)=>{this.check(token);this.time(seconds);this.heartbeatAt=Date.now();});handle('paused',(token,paused)=>{this.check(token);if(typeof paused!=='boolean'||!['recording','paused'].includes(this.phase))throw new Error(tr('无法暂停录制'));this.phase=paused?'paused':'recording';this.changed();});handle('finish',(token,seconds,reason,mime)=>this.finish(token,seconds,reason,mime));handle('cancel',()=>this.reset());handle('fail',(token,message)=>{this.check(token);return this.reset(typeof message==='string'?message.slice(0,500):tr('录制失败'));});handle('save',()=>this.save());handle('copy-saved',async()=>{const saved=this.savedFile;if(this.phase!=='ready'||!saved)throw new Error(tr('请先保存录制'));const current=await stat(saved.path);if(this.savedFile!==saved||this.ctx.blocked()||!current.isFile()||current.size!==saved.size||current.mtimeMs!==saved.mtimeMs||current.ino!==saved.ino)throw new Error(tr('已保存文件发生改变，请重新保存'));await this.ctx.copy(saved.path,()=>this.savedFile===saved&&!this.ctx.blocked());});
  this.timer=setInterval(()=>{if(this.active){const age=Date.now()-this.heartbeatAt;if(this.ctx.blocked()||age>15000){void this.ctx.background(this.abort(this.ctx.blocked()?tr('录制已停止'):tr('录制窗口长时间未响应，已停止')));return;}if(this.phase==='arming'&&Date.now()-this.created>12000){void this.ctx.background(this.reset(tr('未能取得录制来源，请重试')));return;}if(this.phase!=='stopping'&&this.region){const display=screen.getAllDisplays().find(d=>d.id===this.region!.displayId);if(!display||displaySignature(display)!==this.region.signature){this.phase='stopping';this.message=tr('显示器配置已改变，请重新选择录制区域');this.window?.webContents.send('clipper:record-stop');this.changed();}}if(this.phase!=='stopping'&&this.source&&this.options?.mode==='video'&&(this.source.id.startsWith('window:')?!windowExists(Number(this.source.id.split(':')[1])):!screen.getAllDisplays().some(d=>String(d.id)===this.source!.display_id))){this.phase='stopping';this.message=tr('录制来源已关闭或断开');this.window?.webContents.send('clipper:record-stop');this.changed();}if(this.phase!=='stopping'&&(this.seconds>=RECORD_SECONDS||this.file&&this.file.bytes>=RECORD_BYTES-32*1024*1024||Date.now()-this.created>=2*RECORD_SECONDS*1000)){this.phase='stopping';this.message=tr('已达到录制时长或容量上限');this.window?.webContents.send('clipper:record-stop');this.changed();}}},1000);this.timer.unref();
 }
 async init(){try{await RecordingFile.clean(this.directory);}catch{this.initError=tr('录制暂存目录无法清理，请检查目录权限后重启');this.message=this.initError;}}
 get active(){return ['arming','recording','paused','stopping'].includes(this.phase);}
 get hasUnsaved(){return this.picking||this.active||!!this.file&&!this.saved;}
 private armed(){return !this.ctx.blocked()&&this.phase==='arming'&&Date.now()-this.created<12000;}
 private needsDisplay(){return this.options?.mode==='video'||!!this.options?.systemAudio;}
 refreshAppearance(){this.changed();}
 private changed(){if(this.window&&!this.window.isDestroyed())this.window.webContents.send('clipper:record-changed');}
 private check(token:unknown){if(typeof token!=='string'||!token||token!==this.token||!this.file||this.ctx.blocked())throw new Error(tr('录制会话已失效'));}
 private time(value:unknown){if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>RECORD_SECONDS+10||value<this.seconds-1)throw new Error(tr('录制计时无效'));this.seconds=value;}
 state():RecordingState{return {phase:this.phase,token:this.token,seconds:this.seconds,bytes:this.file?.bytes||0,dark:this.ctx.dark(),message:this.message,...(this.mime?{mime:this.mime}:{}),...(this.options?{options:this.options}:{}),...(this.region?{region:this.region}:{}),...(this.saved?{saved:this.saved}:{}),...(['ready','saving'].includes(this.phase)&&this.file?{url:'clipper://app/recording/'+this.token}:{} )};}
 async open(){if(this.ctx.blocked())return;if(this.window&&!this.window.isDestroyed()){this.window.show();this.window.focus();return;}const dark=this.ctx.dark();const window=new BrowserWindow({width:940,height:760,minWidth:680,minHeight:520,title:tr('Clipper · 录屏与录音'),show:false,autoHideMenuBar:true,titleBarStyle:'hidden',titleBarOverlay:false,frame:true,thickFrame:true,hasShadow:true,backgroundColor:dark?'#181818':'#fff',webPreferences:{additionalArguments:interfaceLanguageArguments(),session:this.session,preload:join(__dirname,'../preload/recorder.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true,backgroundThrottling:false}});this.window=window;window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('will-attach-webview',e=>e.preventDefault());window.webContents.on('render-process-gone',()=>void this.ctx.background(this.abort(tr('录制窗口已关闭，未保存内容已清除'))));window.on('close',e=>{if(this.hasUnsaved){e.preventDefault();if(this.busyClose)return;this.busyClose=true;void confirmWindow(window,{type:'question',message:tr('放弃尚未保存的录制？'),detail:tr('关闭后无法恢复。'),buttons:[tr('保留录制'),tr('放弃并关闭')],defaultId:0,cancelId:0}).then(async answer=>{if(answer.response===1)await this.abort();}).catch(()=>{}).finally(()=>this.busyClose=false);}else void this.ctx.background(this.reset());});window.on('closed',()=>{if(this.window===window)this.window=undefined;});await window.loadURL(URL);if(!window.isDestroyed()&&!this.ctx.blocked())window.show();}
 private async sources(type:unknown='screen'){
  if(this.phase!=='idle')throw new Error(tr('请先完成当前录制'));if(type!=='screen'&&type!=='window')throw new Error(tr('录制来源已失效'));
  const generation=this.generation,listing=++this.listing;this.sourceChoices.clear();const valid=()=>generation===this.generation&&listing===this.listing&&!this.ctx.blocked()&&this.phase==='idle';const all=await this.previews.run(type,valid);if(!valid())return [];
  const own=new Set(this.ctx.windows().map(w=>String(w.getNativeWindowHandle().readBigUInt64LE())));if(this.window)own.add(String(this.window.getNativeWindowHandle().readBigUInt64LE()));const choices:RecordingSource[]=[];
  for(const source of all){if(choices.length===150)break;let pid:number|undefined,executable:string|undefined,signature:string|undefined;
   if(type==='window'){const hwnd=source.id.split(':')[1],info=captureWindowInfo(Number(hwnd));if(own.has(hwnd)||!info||info.pid===process.pid||info.pid!==source.pid)continue;pid=info.pid;executable=info.executable;}else{const display=screen.getAllDisplays().find(d=>String(d.id)===source.display_id);if(!display)continue;signature=displaySignature(display);}
   this.sourceChoices.set(source.id,{source:{id:source.id,name:source.name,display_id:source.display_id,thumbnail:nativeImage.createEmpty(),appIcon:nativeImage.createEmpty()},created:Date.now(),pid,executable,signature});choices.push({id:source.id,name:source.name,type,thumbnail:source.thumbnail});
  }return choices;
 }
 private selectedSource(id:string){const choice=this.sourceChoices.get(id);if(!choice||Date.now()-choice.created>120000)throw new Error(tr('录制来源已失效'));if(id.startsWith('window:')){const info=captureWindowInfo(Number(id.split(':')[1]));if(!info||info.pid!==choice.pid||info.executable!==choice.executable||info.pid===process.pid)throw new Error(tr('录制来源已关闭，请重新选择'));}else{const display=screen.getAllDisplays().find(d=>String(d.id)===choice.source.display_id);if(!display||displaySignature(display)!==choice.signature)throw new Error(tr('录制来源已失效'));}return choice.source;}
 private async chooseRegion(sourceId:unknown){if(this.phase!=='idle'||this.picking||typeof sourceId!=='string'||!/^screen:\d+:\d+$/.test(sourceId))throw new Error(tr('请先选择屏幕'));const generation=this.generation;this.picking=true;try{const source=this.selectedSource(sourceId);if(!source||generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制来源已失效'));this.ctx.prepare();const region=await this.ctx.chooseRegion(Number(source.display_id));if(generation!==this.generation||this.ctx.blocked()||!region)return null;this.selectedRegion={token:randomUUID(),region};return {token:this.selectedRegion.token,...region.pixels};}finally{if(generation===this.generation)this.picking=false;}}
 private async arm(value:unknown){if(this.initError)throw new Error(this.initError);if(this.phase!=='idle'||this.picking)throw new Error(tr('请先完成选区或当前录制'));const options=recordingOptions(value);if(options.regionToken){const selected=this.selectedRegion,display=screen.getAllDisplays().find(d=>d.id===selected?.region.displayId);if(!selected||selected.token!==options.regionToken||selected.region.sourceId!==options.sourceId||!display||displaySignature(display)!==selected.region.signature)throw new Error(tr('录制选区已失效，请重新选择'));this.region=selected.region;}else this.region=undefined;const generation=++this.generation;this.options=options;this.phase='arming';this.created=this.heartbeatAt=Date.now();this.message=tr('正在准备录制');this.displayGrant=false;this.micGrant=false;this.seconds=0;this.saved='';this.savedFile=undefined;this.token=randomUUID();const file=new RecordingFile(this.directory,RECORD_BYTES,options.container||'mp4');this.file=file;this.changed();try{if(options.mode==='video'){const source=this.selectedSource(options.sourceId);if(generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制已取消'));this.source=source;if(!this.source)throw new Error(tr('录制来源已关闭，请重新选择'));const own=this.ctx.windows().concat(this.window?[this.window]:[]).some(w=>String(w.getNativeWindowHandle().readBigUInt64LE())===options.sourceId.split(':')[1]);if(options.sourceId.startsWith('window:')&&own)throw new Error(tr('不能录制 Clipper 自己的窗口'));}await file.create();if(generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制已取消'));this.ctx.prepare();return this.token;}catch(e){if(generation===this.generation)await this.reset(String((e as Error).message));else await file.dispose();throw e;}}
 private started(token:unknown,mime:unknown){this.check(token);if(!this.armed()||!validRecordingMime(mime,this.options!)||this.needsDisplay()&&!this.displayGrant)throw new Error(tr('录制来源或编码器无效'));this.mime=mime;this.phase='recording';this.message='';this.heartbeatAt=Date.now();this.shown=this.ctx.windows().filter(w=>w!==this.window&&w.isVisible());for(const w of this.shown)w.hide();this.window?.setAlwaysOnTop(true);this.window?.setMinimumSize(420,260);this.window?.setSize(480,260);this.changed();}
 private async chunk(token:unknown,index:unknown,data:unknown){this.check(token);if(!['recording','paused','stopping'].includes(this.phase)||typeof index!=='number'||!(data instanceof Uint8Array)||this.pendingBytes+data.byteLength>RECORD_CHUNK*2)throw new Error(tr('录制片段无法接收'));const generation=this.generation,file=this.file!;this.pendingBytes+=data.byteLength;try{await file.append(index,data);if(generation!==this.generation)throw new Error(tr('录制已取消'));}finally{this.pendingBytes-=data.byteLength;}}
 private async finish(token:unknown,seconds:unknown,reason:unknown,mime:unknown){this.check(token);if(!['recording','paused','stopping'].includes(this.phase))throw new Error(tr('录制尚未开始'));if(!validRecordingMime(mime,this.options!))throw new Error(tr('实际编码格式不受支持'));this.mime=mime;this.time(seconds);const generation=this.generation,file=this.file!;this.phase='stopping';await file.finish();if(generation!==this.generation||this.ctx.blocked())return;this.phase='ready';this.message=typeof reason==='string'&&reason?reason.slice(0,300):this.message;this.window?.setAlwaysOnTop(false);this.window?.setSize(940,760);this.window?.setMinimumSize(680,520);this.restore();this.window?.show();this.changed();}
 private restore(){for(const w of this.shown)if(!w.isDestroyed()&&!this.ctx.blocked())w.show();this.shown=[];}
 private async reset(message=''){const revoke=this.active,window=this.window;const generation=++this.generation;if(this.picking)this.ctx.cancelRegion();this.picking=false;this.listing++;this.sourceChoices.clear();this.selectedRegion=undefined;this.region=undefined;const file=this.file;this.file=undefined;this.token='';this.source=undefined;this.options=undefined;this.mime='';this.seconds=0;this.saved='';this.savedFile=undefined;this.phase='idle';this.message=message;this.displayGrant=false;this.micGrant=false;this.window?.webContents.send('clipper:record-stop');this.window?.setAlwaysOnTop(false);if(this.window&&!this.window.isDestroyed()){this.window.setSize(940,760);this.window.setMinimumSize(680,520);}this.restore();this.changed();await Promise.all([file?.dispose(),this.previews.stop()]);if(generation===this.generation&&revoke&&window&&!window.isDestroyed()&&this.window===window&&!this.ctx.blocked())window.webContents.reload();}
 abort(message=''){const window=this.window;this.window=undefined;window?.destroy();return this.reset(message);}
 private async save(){if(this.phase!=='ready'||!this.file)throw new Error(tr('请先停止录制'));const generation=this.generation,file=this.file,extension=recordingExtension(this.options!);this.phase='saving';this.changed();try{const choice=await dialog.showSaveDialog(this.window!,{title:tr('保存录制（未加密的新文件）'),defaultPath:`Clipper-${new Date().toISOString().replaceAll(':','-').slice(0,19)}.${extension}`,filters:[{name:extension.toUpperCase(),extensions:[extension]}]});if(choice.canceled||!choice.filePath)return null;if(generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制已取消'));let destination=choice.filePath;if(extname(destination).toLowerCase()!=='.'+extension)destination+='.'+extension;this.ctx.protect(destination);if(resolve(destination).toLowerCase().startsWith(resolve(this.directory).toLowerCase()+sep))throw new Error(tr('不能保存到录制暂存目录'));try{const result=await file.export(destination,()=>generation===this.generation&&!this.ctx.blocked());if(generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制已取消'));const info=await stat(destination);if(generation!==this.generation||this.ctx.blocked())throw new Error(tr('录制已取消'));this.savedFile={path:destination,size:info.size,mtimeMs:info.mtimeMs,ino:info.ino};this.saved=result;this.message=tr`已保存：${result}`;return result;}catch(e){if((e as NodeJS.ErrnoException).code==='EEXIST')throw new Error(tr('文件已存在，请选择新文件名'));throw e;}}finally{if(generation===this.generation){this.phase='ready';this.changed();}}}
 private media(request:Request):Response{const url=new globalThis.URL(request.url);if(this.ctx.blocked()||url.pathname!=='/recording/'+this.token||!this.file||!['ready','saving'].includes(this.phase)||!['GET','HEAD'].includes(request.method))return new Response('Not found',{status:404});const file=this.file;let range;try{range=recordingRange(request.headers.get('Range'),file.bytes);}catch{return new Response(null,{status:416,headers:{'Content-Range':`bytes */${file.bytes}`}});}const headers:Record<string,string>={'Content-Type':recordingContentType(this.options!),'Accept-Ranges':'bytes','Content-Length':String(range.end-range.start+1),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};if(range.partial)headers['Content-Range']=`bytes ${range.start}-${range.end}/${file.bytes}`;return new Response(request.method==='HEAD'?null:Readable.toWeb(Readable.from(file.read(range.start,range.end))) as ReadableStream,{status:range.partial?206:200,headers});}
 dispose(){clearInterval(this.timer);return this.abort();}
}
