import {app,BrowserWindow,dialog,ipcMain,net,screen,session} from 'electron';
import {join,resolve,dirname,extname,basename} from 'node:path';
import {pathToFileURL} from 'node:url';
import {open,unlink} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {Worker} from 'node:worker_threads';
import type {CaptureService} from './capture';
import {displaySignature,regionPixels,type Region} from '../shared/region';
import type {ScrollState} from '../shared/scroll';
import {appendFrame,checkFrame,SCROLL_FRAMES,type Frame,type Match} from './stitch';
import {commitRecording} from './recording-move';
interface Context {capture:CaptureService;blocked():boolean;dark():boolean;prepare():void;protect(path:string):void;windows():BrowserWindow[];copy(png:Buffer,valid:()=>boolean):Promise<void>;background<T>(task:Promise<T>):Promise<T>}
const URL='clipper://app/scroll.html';
export class ScrollCaptureService {
 window?:BrowserWindow;private thumbs=new WeakMap<Frame,string>();private phase:ScrollState['phase']='idle';private message='';private region?:Region;private composite?:Frame;private previous?:Frame;private pending?:Frame;private undoState?:{height:number;previous:Frame};private png?:Buffer;private token='';private generation=0;private frames=0;private saved=false;private busy=false;private closing=false;private worker?:Worker;private created=0;private shown:BrowserWindow[]=[];private timer:NodeJS.Timeout;
 constructor(private ctx:Context){const partition=session.fromPartition('clipper-scroll'),renderer=resolve(__dirname,'../renderer');partition.setPermissionCheckHandler(()=>false);partition.setPermissionRequestHandler((_w,_p,cb)=>cb(false));partition.on('will-download',e=>e.preventDefault());partition.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','file://*/*']},(_r,cb)=>cb({cancel:true}));partition.protocol.handle('clipper',request=>{const u=new globalThis.URL(request.url);if(u.hostname!=='app')return new Response(null,{status:404});if(u.pathname==='/scroll-image/'+this.token&&this.token&&this.png&&!this.ctx.blocked())return new Response(new Uint8Array(this.png),{headers:{'Content-Type':'image/png','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});const name=u.pathname.slice(1);if(!['scroll.html','scroll.js','scroll.css'].includes(name))return new Response(null,{status:404});return net.fetch(pathToFileURL(join(renderer,name)).toString());});
  const handle=(name:string,fn:(...args:any[])=>unknown,mutation=true)=>ipcMain.handle('clipper:scroll-'+name,(event,...args)=>{if(this.ctx.blocked()||!this.window||event.sender!==this.window.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!==URL)throw new Error('拒绝访问长截图');return this.ctx.background((async()=>{if(mutation&&this.busy)throw new Error('正在处理，请稍后');if(mutation)this.busy=true;const generation=this.generation;try{return await fn(...args);}catch(e){if(generation===this.generation){this.message=(e as Error).message;this.changed();}throw e;}finally{if(mutation&&generation===this.generation)this.busy=false;}})());});
  handle('state',()=>this.state(),false);handle('screens',()=>this.ctx.capture.screens(),false);handle('start',id=>this.start(id));handle('append',()=>this.append());handle('align',overlap=>this.align(overlap));handle('reject',()=>{if(this.phase!=='aligning')throw new Error('没有待对齐画面');this.pending=undefined;this.phase='capturing';this.message='已丢弃当前画面，可向上滚回一些后重试';this.changed();});handle('undo',()=>this.undo());handle('finish',()=>{if(!this.composite||!['capturing','aligning'].includes(this.phase))throw new Error('没有可完成的截图');this.pending=undefined;this.phase='ready';this.message='';this.restore();this.resize(false);this.changed();});handle('cancel',()=>this.reset(),false);handle('save',()=>this.save());handle('copy',async()=>{if(this.phase!=='ready'||!this.png)throw new Error('请先完成截图');const generation=this.generation,png=this.png;await this.ctx.copy(png,()=>generation===this.generation&&!this.ctx.blocked());if(generation===this.generation){this.saved=true;this.message='已加入图片历史并复制';this.changed();}});
  this.timer=setInterval(()=>{if(this.phase==='picking')return;if(this.active&&this.ctx.blocked()){this.abort();return;}if(this.active&&!this.validRegion()){this.halt('显示器配置已改变，已停止捕获；可保存已完成的长图');return;}if(this.active&&Date.now()-this.created>15*60_000){this.halt('本次捕获已达 15 分钟上限，请保存后开始新的截图');}},1000);this.timer.unref();
 }
 get active(){return ['picking','capturing','aligning'].includes(this.phase);}
 get hasUnsaved(){return this.active||!!this.png&&!this.saved;}
 private halt(message:string){this.generation++;this.busy=false;void this.worker?.terminate();this.worker=undefined;this.pending=undefined;this.phase=this.composite?'ready':'idle';this.message=message;this.restore();this.resize(false);this.changed();}
 private changed(){if(this.window&&!this.window.isDestroyed())this.window.webContents.send('clipper:scroll-changed');}
 private validRegion(){const d=screen.getAllDisplays().find(d=>d.id===this.region?.displayId);return !!d&&!!this.region&&displaySignature(d)===this.region.signature;}
 private live(generation:number){if(generation!==this.generation||this.ctx.blocked())throw new Error('长截图已取消');}
 private resize(compact:boolean){if(!this.window||this.window.isDestroyed())return;this.window.setAlwaysOnTop(compact);this.window.setMinimumSize(compact?440:680,compact?290:540);this.window.setSize(compact?520:960,compact?350:780);this.window.showInactive();}
 private restore(){for(const w of this.shown)if(!w.isDestroyed()&&!this.ctx.blocked())w.show();this.shown=[];}
 async open(){if(this.ctx.blocked())throw new Error('请先完成其他捕获或解锁历史');if(this.window&&!this.window.isDestroyed()){this.window.show();this.window.focus();return;}const dark=this.ctx.dark(),window=new BrowserWindow({width:960,height:780,minWidth:680,minHeight:540,title:'Clipper · 长截图',show:false,autoHideMenuBar:true,titleBarStyle:'hidden',titleBarOverlay:{height:46,color:dark?'#181818':'#fff',symbolColor:dark?'#eee':'#222'},backgroundColor:dark?'#181818':'#fff',webPreferences:{session:session.fromPartition('clipper-scroll'),preload:join(__dirname,'../preload/scroll.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});this.window=window;window.setContentProtection(true);window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('will-attach-webview',e=>e.preventDefault());window.webContents.on('render-process-gone',()=>this.abort());window.on('close',e=>{e.preventDefault();if(!this.hasUnsaved){this.abort();return;}if(this.closing)return;this.closing=true;void dialog.showMessageBox(window,{type:'question',message:'放弃尚未保存的长截图？',buttons:['保留','放弃并关闭'],defaultId:0,cancelId:0}).then(answer=>{if(answer.response===1)this.abort();}).catch(()=>{}).finally(()=>this.closing=false);});window.on('closed',()=>{if(this.window===window)this.window=undefined;});await window.loadURL(URL);if(!window.isDestroyed()&&!this.ctx.blocked())window.show();}
 state():ScrollState {return {phase:this.phase,dark:this.ctx.dark(),message:this.message,width:this.composite?.width||0,height:this.composite?.height||0,frames:this.frames,canUndo:!!this.undoState,saved:this.saved,...(this.png?{url:'clipper://app/scroll-image/'+this.token}:{}),...(this.pending&&this.previous?{pending:{previous:this.small(this.previous),next:this.small(this.pending),height:this.pending.height,suggested:Math.floor(this.pending.height/2)}}:{})};}
 private small(frame:Frame){const cached=this.thumbs.get(frame);if(cached)return cached;const scale=Math.min(1,420/frame.width,500/frame.height),url=require('electron').nativeImage.createFromBitmap(Buffer.from(frame.data),{width:frame.width,height:frame.height}).resize({width:Math.max(1,Math.floor(frame.width*scale)),height:Math.max(1,Math.floor(frame.height*scale))}).toDataURL() as string;this.thumbs.set(frame,url);return url;}
 private async compute<T>(data:Record<string,unknown>):Promise<T>{const worker=new Worker(join(__dirname,'scroll-worker.cjs'),{workerData:data});this.worker=worker;try{return await new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>{void worker.terminate();reject(new Error('拼接处理超时，请缩小选区'));},8000);const done=(fn:()=>void)=>{clearTimeout(timer);fn();};worker.once('message',result=>done(()=>result?.error?reject(new Error(result.error)):resolve(result)));worker.once('error',e=>done(()=>reject(e)));worker.once('exit',code=>done(()=>reject(new Error(code===0?'拼接进程未返回结果':'拼接处理已取消'))));});}finally{if(this.worker===worker)this.worker=undefined;void worker.terminate();}}
 private async snapshot(generation:number){if(!this.region||!this.validRegion())throw new Error('显示器配置已改变，请重新选择区域');const visible=this.ctx.windows().filter(w=>!w.isDestroyed()&&w.isVisible());for(const w of visible)w.hide();try{await new Promise(r=>setTimeout(r,220));this.live(generation);const shot=await this.ctx.capture.snapshot(this.region.displayId);this.live(generation);if(shot.signature!==this.region.signature)throw new Error('显示器配置已改变');const size=shot.image.getSize(),crop=regionPixels(this.region.rect,size.width,size.height),image=shot.image.crop(crop),frame={...image.getSize(),data:image.toBitmap()};checkFrame(frame);return frame;}finally{if(generation===this.generation&&!this.ctx.blocked())for(const w of visible)if(!w.isDestroyed())w.showInactive();}}
 private async start(displayId:unknown){if(this.phase!=='idle'||!Number.isSafeInteger(displayId))throw new Error('请先完成当前截图并选择显示器');const generation=this.generation;this.phase='picking';this.ctx.prepare();this.changed();try{const region=await this.ctx.capture.choose(displayId as number,this.ctx.windows(),'选定滚动区域');this.live(generation);if(!region){this.phase='idle';this.changed();return;}if(region.pixels.width<64||region.pixels.height<64)throw new Error('请选择至少 64 × 64 像素的滚动内容');this.region=region;this.created=Date.now();this.shown=this.ctx.windows().filter(w=>w!==this.window&&w.isVisible());for(const w of this.shown)w.hide();const frame=await this.snapshot(generation),png=Buffer.from(await this.compute<Uint8Array>({mode:'png',frame}));this.live(generation);this.composite=this.previous=frame;this.png=png;this.token=randomUUID();this.frames=1;this.saved=false;this.phase='capturing';this.message='向下滚动，保留部分重叠内容，再追加一屏';this.resize(true);this.changed();}catch(e){if(generation===this.generation){this.phase='idle';this.region=undefined;this.restore();this.resize(false);}throw e;}}
 private async append(){if(this.phase!=='capturing'||!this.previous||!this.composite)throw new Error('请先选区或处理待对齐画面');if(this.frames>=SCROLL_FRAMES)throw new Error('最多拼接 30 屏，请完成并保存');const generation=this.generation,next=await this.snapshot(generation),match=await this.compute<Match>({mode:'match',previous:this.previous,next});this.live(generation);if(match.kind==='same'){this.message='画面没有变化，未追加';this.changed();return;}if(match.kind==='uncertain'){this.pending=next;this.phase='aligning';this.message='无法可靠识别重叠，请对照上下画面调整后确认，或放弃这一屏';this.resize(false);this.changed();return;}await this.commit(next,match.overlap,generation);}
 private async commit(next:Frame,overlap:number,generation:number){const original=this.composite!,previous=this.previous!,combined=appendFrame(original,next,overlap),png=Buffer.from(await this.compute<Uint8Array>({mode:'png',frame:combined}));this.live(generation);this.undoState={height:original.height,previous};this.composite=combined;this.previous=next;this.png=png;this.token=randomUUID();this.pending=undefined;this.frames++;this.saved=false;this.phase='capturing';this.message='已拼接，继续向下滚动或完成预览';this.resize(true);this.changed();}
 private async align(overlap:unknown){if(this.phase!=='aligning'||!this.pending||typeof overlap!=='number')throw new Error('没有待对齐画面');await this.commit(this.pending,overlap,this.generation);}
 private async undo(){if(!['capturing','ready'].includes(this.phase)||!this.undoState||!this.composite)throw new Error('没有可撤销的追加');const generation=this.generation,old=this.undoState,frame={width:this.composite.width,height:old.height,data:this.composite.data.slice(0,this.composite.width*old.height*4)},png=Buffer.from(await this.compute<Uint8Array>({mode:'png',frame}));this.live(generation);this.composite=frame;this.previous=old.previous;this.png=png;this.token=randomUUID();this.undoState=undefined;this.frames--;this.saved=false;this.message='已撤销最近一次追加；继续捕获前请把目标页面滚回上一屏';this.changed();}
 private async save(){if(this.phase!=='ready'||!this.png)throw new Error('请先完成截图');const generation=this.generation,png=this.png;this.phase='saving';this.changed();try{const choice=await dialog.showSaveDialog(this.window!,{title:'长截图另存为（未加密的新文件）',defaultPath:'Clipper-long-'+new Date().toISOString().replaceAll(':','-').slice(0,19)+'.png',filters:[{name:'PNG 图片',extensions:['png']}]});this.live(generation);if(choice.canceled||!choice.filePath)return null;const target=extname(choice.filePath).toLowerCase()==='.png'?choice.filePath:choice.filePath+'.png';this.ctx.protect(target);const staging=join(dirname(target),'.Clipper-image-'+randomUUID()+'.part');let file;try{file=await open(staging,'wx',0o600);await file.writeFile(png);await file.sync();await file.close();file=undefined;this.live(generation);commitRecording(staging,target);this.saved=true;this.message='已保存：'+basename(target);return basename(target);}finally{await file?.close().catch(()=>{});await unlink(staging).catch(()=>{});}}finally{if(generation===this.generation){this.phase='ready';this.changed();}}}
 private reset(){this.generation++;this.thumbs=new WeakMap();if(this.phase==='picking')this.ctx.capture.cancel();void this.worker?.terminate();this.worker=undefined;this.busy=false;for(const data of [this.composite?.data,this.previous?.data,this.pending?.data,this.undoState?.previous.data,this.png])data?.fill(0);this.composite=this.previous=this.pending=undefined;this.undoState=undefined;this.png=undefined;this.region=undefined;this.token='';this.frames=0;this.saved=false;this.phase='idle';this.message='';this.restore();this.resize(false);this.changed();}
 abort(){const window=this.window;this.window=undefined;window?.destroy();this.reset();}
 dispose(){clearInterval(this.timer);this.abort();}
}
