import {t as tr} from '../shared/i18n';
import {deflateSync} from 'node:zlib';
export interface Frame {width:number;height:number;data:Uint8Array}
export const SCROLL_PIXELS=24_000_000,SCROLL_FRAME_PIXELS=12_000_000,SCROLL_EDGE=16384,SCROLL_FRAMES=30;
export type Match={kind:'same'}|{kind:'match'|'uncertain';overlap:number;score:number};
export function checkFrame(frame:Frame,max=SCROLL_FRAME_PIXELS){if(!frame||![frame.width,frame.height].every(Number.isSafeInteger)||frame.width<2||frame.height<2||frame.width>SCROLL_EDGE||frame.height>SCROLL_EDGE||frame.width*frame.height>max||!(frame.data instanceof Uint8Array)||frame.data.length!==frame.width*frame.height*4)throw new Error(tr('截图尺寸或像素无效'));}
function difference(a:Frame,b:Frame,shift:number,columns=32,rows=32){const overlap=a.height-shift;let total=0,n=0;for(let row=0;row<Math.min(rows,overlap);row++){const y=Math.floor((row+.5)*overlap/Math.min(rows,overlap));for(let col=0;col<Math.min(columns,a.width);col++){const x=Math.floor((col+.5)*a.width/Math.min(columns,a.width)),ai=((y+shift)*a.width+x)*4,bi=(y*b.width+x)*4;for(let c=0;c<3;c++){total+=Math.abs(a.data[ai+c]-b.data[bi+c]);n++;}}}return total/n;}
function texture(a:Frame){let total=0,n=0;for(let y=1;y<a.height;y+=Math.max(1,Math.floor(a.height/100)))for(let x=0;x<a.width;x+=Math.max(1,Math.floor(a.width/64))){const i=(y*a.width+x)*4,j=((y-1)*a.width+x)*4;for(let c=0;c<3;c++){total+=Math.abs(a.data[i+c]-a.data[j+c]);n++;}}return total/n;}
export function matchFrames(previous:Frame,next:Frame):Match{
 checkFrame(previous);checkFrame(next);if(previous.width!==next.width||previous.height!==next.height)throw new Error(tr('画面尺寸改变，请重新选择区域'));if(difference(previous,next,0,96,96)<.35)return {kind:'same'};
 const minimum=Math.max(32,Math.floor(previous.height*.18)),scores:{shift:number;score:number}[]=[];for(let shift=2;shift<=previous.height-minimum;shift++)scores.push({shift,score:difference(previous,next,shift)});scores.sort((a,b)=>a.score-b.score);const best=scores[0];if(!best)return {kind:'uncertain',overlap:Math.floor(previous.height/2),score:255};const rival=scores.find(s=>Math.abs(s.shift-best.shift)>4),verified=difference(previous,next,best.shift,128,96),unique=!rival||rival.score>best.score+1.5;
 return {kind:best.score<2.5&&verified<2.5&&unique&&texture(next)>.4?'match':'uncertain',overlap:previous.height-best.shift,score:verified};
}
export function appendFrame(composite:Frame,next:Frame,overlap:number):Frame{checkFrame(composite,SCROLL_PIXELS);checkFrame(next);if(composite.width!==next.width||!Number.isInteger(overlap)||overlap<0||overlap>=next.height)throw new Error(tr('重叠高度无效'));const height=composite.height+next.height-overlap;if(height>SCROLL_EDGE||height*composite.width>SCROLL_PIXELS)throw new Error(tr('长图已达尺寸上限，请完成并保存'));return {width:composite.width,height,data:Buffer.concat([composite.data,next.data.subarray(overlap*next.width*4)])};}
const crcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function pngChunk(type:string,data:Buffer){const name=Buffer.from(type),body=Buffer.concat([name,data]);let crc=0xffffffff;for(const byte of body)crc=crcTable[(crc^byte)&255]^(crc>>>8);const length=Buffer.alloc(4),sum=Buffer.alloc(4);length.writeUInt32BE(data.length);sum.writeUInt32BE((crc^0xffffffff)>>>0);return Buffer.concat([length,body,sum]);}
export function framePNG(frame:Frame){checkFrame(frame,SCROLL_PIXELS);const stride=frame.width*4,raw=Buffer.alloc((stride+1)*frame.height);for(let y=0;y<frame.height;y++){const row=y*(stride+1);for(let x=0;x<frame.width;x++){const i=y*stride+x*4,o=row+1+x*4;raw[o]=frame.data[i+2];raw[o+1]=frame.data[i+1];raw[o+2]=frame.data[i];raw[o+3]=frame.data[i+3];}}const header=Buffer.alloc(13);header.writeUInt32BE(frame.width,0);header.writeUInt32BE(frame.height,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),pngChunk('IHDR',header),pngChunk('IDAT',deflateSync(raw,{level:3})),pngChunk('IEND',Buffer.alloc(0))]);}
