import {isInvitation} from '../shared/web-share';
import {createServer,type Server} from 'node:https';
import type {IncomingMessage,ServerResponse} from 'node:http';
import type {TLSSocket} from 'node:tls';
import {randomUUID,randomBytes,timingSafeEqual} from 'node:crypto';
import {hostname} from 'node:os';
import {Store} from './store';
import {SyncLedger} from './sync-ledger';
import {createSyncIdentity,validateIdentity,type SyncIdentity} from './sync-identity';
import {readSyncBody,syncResponse,syncRequest,socketFingerprint,remoteAddress} from './sync-transport';
import {SyncDiscovery,localAddresses} from './sync-discovery';
import {syncName,syncPeer,syncRecord,privateAddress,type SyncPeer,type SyncOptions,type SyncState,type SyncRecord} from '../shared/sync';
import type {Payload,Detail} from '../shared/types';
interface Vault {available():Promise<boolean>;encrypt(value:string):Promise<string>;decrypt(value:string):Promise<string>}
interface Saved extends SyncOptions {id:string;cert:string;secret:string;fingerprint:string;port:number;peers:SyncPeer[]}
interface Invitation extends SyncPeer {token:string;expires:number;v:1}
interface Pending {id:string;peer:SyncPeer;expires:number;accepted:boolean;rejected:boolean}
export class SyncService {
 readonly ledger:SyncLedger;private identity:SyncIdentity|undefined;private server:Server|undefined;private discovery:SyncDiscovery|undefined;private timer:NodeJS.Timeout|undefined;
 private sockets=new Set<TLSSocket>();private requests=new Map<string,AbortController>();private status=new Map<string,{lastSync:number;error:string;busy:boolean}>();private generation=0;private error='';private invitation:Invitation|undefined;private pending:Pending|undefined;private joining:{peer:Invitation;requestId:string}|undefined;private ticking=false;private changing=false;
 constructor(private store:()=>Store,private vault:Vault,private changed:()=>void,private enqueue:<T>(fn:()=>T|Promise<T>)=>Promise<T>,thumbnail:(p:Payload)=>string|undefined=()=>undefined,private options:{bindHost?:string;discovery?:boolean;afterMutation?:(previous:Detail|undefined,next?:Detail)=>void}={}){this.ledger=new SyncLedger(store,()=>this.saved().id,thumbnail);this.bindStore();}
 bindStore(){this.store().onChange=(previous,next)=>{this.ledger.observe(previous,next);this.options.afterMutation?.(previous,next);};}
 async resume(){try{await this.start();}catch(e){this.error=String((e as Error).message);await this.stop();this.changed();}}
 private saved():Saved{return {enabled:false,name:hostname().slice(0,60)||'我的电脑',autoNew:false,id:'',cert:'',secret:'',fingerprint:'',port:0,peers:[],...this.store().meta('lan-config',{})};}
 private save(value:Saved){this.store().setMeta('lan-config',value);}
 state():SyncState{const s=this.saved(),entries=this.ledger.entries(),now=Date.now();if(this.invitation&&this.invitation.expires<now)this.invitation=undefined;if(this.pending&&this.pending.expires<now)this.pending=undefined;return {enabled:s.enabled,name:s.name,autoNew:s.autoNew,id:s.id,port:s.port,fingerprint:s.fingerprint,addresses:this.options.bindHost?[this.options.bindHost]:localAddresses(),error:this.error,shared:new Set(entries.filter(e=>!e.deleted).map(e=>e.localId)).size,tombstones:entries.filter(e=>e.deleted).length,peers:s.peers.map(p=>({...p,...(this.status.get(p.id)||{lastSync:0,error:'',busy:false})})),nearby:this.discovery?.list()||[],pending:this.pending&&!this.pending.accepted&&!this.pending.rejected?[{id:this.pending.id,name:this.pending.peer.name,host:this.pending.peer.host,fingerprint:this.pending.peer.fingerprint}]:[],joining:this.joining?.peer.name||'',invitation:this.invitation?'clipper-pair:'+Buffer.from(JSON.stringify(this.invitation)).toString('base64url'):'',expires:this.invitation?.expires||0};}
 async configure(value:SyncOptions){if(this.changing)throw new Error('同步设置正在切换');if(!value||typeof value.enabled!=='boolean'||typeof value.autoNew!=='boolean')throw new Error('同步设置无效');const name=syncName(value.name);this.changing=true;try{await this.stop();let next={...this.saved(),enabled:value.enabled,name,autoNew:value.autoNew};
  if(next.enabled&&!next.id){if(!await this.vault.available())throw new Error('Windows 安全存储不可用，无法保存设备私钥');const identity=await createSyncIdentity();next={...next,id:identity.id,cert:identity.cert,fingerprint:identity.fingerprint,secret:await this.vault.encrypt(identity.key)};}
  this.save(next);if(next.enabled)await this.start();this.changed();
 }catch(e){this.error=String((e as Error).message);this.save({...this.saved(),enabled:false});await this.stop();this.changed();throw e;}finally{this.changing=false;}}
 async start(){const saved=this.saved();if(!saved.enabled||this.server)return;this.error='';const key=await this.vault.decrypt(saved.secret);this.identity={id:saved.id,cert:saved.cert,key,fingerprint:saved.fingerprint};validateIdentity(this.identity);const server=this.server=createServer({key,cert:saved.cert,minVersion:'TLSv1.3',maxVersion:'TLSv1.3',requestCert:true,rejectUnauthorized:false,handshakeTimeout:5000},(req,res)=>{void this.receive(req,res).catch(e=>{if(!res.headersSent)syncResponse(res,{error:String(e instanceof Error?e.message:e).slice(0,250)},400);else res.destroy();});});
  server.maxConnections=32;server.requestTimeout=10000;server.headersTimeout=5000;server.keepAliveTimeout=1000;server.maxRequestsPerSocket=1;server.on('secureConnection',socket=>{socket.disableRenegotiation();this.sockets.add(socket);socket.once('close',()=>this.sockets.delete(socket));});
  try{await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(saved.port,this.options.bindHost||'0.0.0.0',()=>{server.removeListener('error',reject);resolve();});});}catch(e){this.server=undefined;server.close();throw e;}
  server.on('error',e=>{this.error=e.message;this.changed();});const port=(server.address() as {port:number}).port;this.save({...this.saved(),port});if(this.options.discovery!==false){this.discovery=new SyncDiscovery(()=>this.self(),this.changed,value=>{this.error=value;this.changed();});this.discovery.start();}this.timer=setInterval(()=>void this.tick(),3000);this.changed();
 }
 private self():SyncPeer{const s=this.saved();return {id:s.id,name:s.name,host:this.options.bindHost||localAddresses()[0]||'127.0.0.1',port:s.port,fingerprint:s.fingerprint};}
 async stop(){this.generation++;clearInterval(this.timer);this.discovery?.stop();this.discovery=undefined;for(const controller of this.requests.values())controller.abort();this.requests.clear();for(const socket of this.sockets)socket.destroy();this.sockets.clear();const server=this.server;this.server=undefined;if(server)await new Promise<void>(resolve=>server.close(()=>resolve()));this.identity=undefined;this.invitation=undefined;this.pending=undefined;this.joining=undefined;}
 invite(host:unknown){if(!this.server)throw new Error('请先启用局域网同步');if(!privateAddress(host)||!this.state().addresses.includes(host))throw new Error('请选择本机局域网地址');this.pending=undefined;this.invitation={...this.self(),host,v:1,token:randomBytes(32).toString('hex'),expires:Date.now()+300000};this.changed();return this.state().invitation;}
 async cancelPairing(){const joining=this.joining;this.invitation=undefined;this.pending=undefined;this.joining=undefined;this.changed();if(joining)await this.call(joining.peer,'/v1/pair-cancel',{requestId:joining.requestId});}
 private async call(peer:SyncPeer,path:string,body?:unknown){if(!this.identity||!this.server)throw new Error('同步已关闭');const controller=new AbortController(),id=randomUUID();this.requests.set(id,controller);try{return await syncRequest(this.identity,peer,path,body,controller.signal);}finally{this.requests.delete(id);}}
 async join(code:unknown){if(this.joining)throw new Error('已有配对正在进行');if(typeof code!=='string'||!code.startsWith('clipper-pair:')||code.length>4096)throw new Error('配对码无效');const value=JSON.parse(Buffer.from(code.slice(13),'base64url').toString('utf8')),peer={...syncPeer(value),v:1 as const,token:value.token,expires:value.expires};if(value.v!==1||!Number.isFinite(peer.expires)||peer.expires<Date.now()||peer.expires>Date.now()+600000||typeof peer.token!=='string'||!/^[0-9a-f]{64}$/.test(peer.token))throw new Error('配对码无效或已过期');if(peer.id===this.saved().id)throw new Error('不能与自己配对');if(this.saved().peers.length>=8)throw new Error('最多配对 8 台设备');const generation=this.generation;const response=await this.call(peer,'/v1/pair',{token:peer.token,device:this.self()});if(generation!==this.generation)throw new Error('配对已取消');if(typeof response.requestId!=='string')throw new Error('配对响应无效');this.joining={peer,requestId:response.requestId};this.changed();}
 approve(id:string,accept:boolean){const p=this.pending;if(!p||p.id!==id||p.expires<Date.now()||p.accepted||p.rejected||typeof accept!=='boolean')throw new Error('配对请求已失效');if(accept)this.trust(p.peer);p.accepted=accept;p.rejected=!accept;this.changed();}
 private trust(peer:SyncPeer){const s=this.saved();if(s.peers.some(p=>p.id===peer.id&&p.fingerprint!==peer.fingerprint||p.id!==peer.id&&p.fingerprint===peer.fingerprint))throw new Error('设备身份冲突，请先撤销旧设备');const peers=[...s.peers.filter(p=>p.id!==peer.id),peer];if(peers.length>8)throw new Error('最多配对 8 台设备');this.save({...s,peers});this.error='';}
 revoke(id:string){const s=this.saved();this.save({...s,peers:s.peers.filter(p=>p.id!==id)});this.generation++;for(const c of this.requests.values())c.abort();for(const socket of this.sockets)socket.destroy();this.status.delete(id);this.pending=undefined;this.joining=undefined;this.changed();}
 capture(clip:Detail){if(isInvitation(clip.payload.text||'')){this.ledger.local(clip.id,true);return;}const saved=this.saved();if(saved.enabled&&saved.autoNew&&!clip.payload.files&&!clip.payload.attachments&&!clip.localOnly)this.ledger.publish(clip.id);}
 share(id:string){if(!this.saved().id)throw new Error('请先启用并初始化同步');this.ledger.publish(id);this.changed();}
 local(id:string,only:boolean){this.ledger.local(id,only);this.changed();}
 private async receive(req:IncomingMessage,res:ServerResponse){const socket=req.socket as TLSSocket,host=remoteAddress(socket.remoteAddress||'');if(!this.server||!privateAddress(host)||req.headers.origin)throw new Error('请求来源不受支持');const fingerprint=socketFingerprint(socket),generation=this.generation;
  const ensure=()=>{if(generation!==this.generation||!this.server)throw new Error('同步已停止或信任已改变');};
  if(req.method==='POST'&&req.url==='/v1/pair'){
   const value=await readSyncBody(req,8192);ensure();const invite=this.invitation;if(!invite||invite.expires<Date.now()||typeof value.token!=='string'||!/^[0-9a-f]{64}$/.test(value.token)||!timingSafeEqual(Buffer.from(invite.token),Buffer.from(value.token)))throw new Error('配对码无效、已使用或已过期');const peer=syncPeer({...value.device,host,fingerprint});if(peer.id===this.saved().id)throw new Error('设备身份冲突');this.invitation=undefined;this.pending={id:randomUUID(),peer,expires:Date.now()+300000,accepted:false,rejected:false};this.changed();syncResponse(res,{requestId:this.pending.id});return;
  }
  if(req.method==='POST'&&req.url==='/v1/pair-status'){const value=await readSyncBody(req,4096);ensure();const p=this.pending;if(!p||p.id!==value.requestId||p.peer.fingerprint!==fingerprint||p.expires<Date.now())throw new Error('配对请求已失效');syncResponse(res,{status:p.accepted?'accepted':p.rejected?'rejected':'pending'});return;}
  if(req.method==='POST'&&req.url==='/v1/pair-cancel'){const value=await readSyncBody(req,4096);ensure();const p=this.pending;if(!p||p.id!==value.requestId||p.peer.fingerprint!==fingerprint||p.expires<Date.now())throw new Error('配对请求已失效');if(p.accepted){const s=this.saved();this.save({...s,peers:s.peers.filter(peer=>peer.fingerprint!==fingerprint)});this.generation++;for(const controller of this.requests.values())controller.abort();}this.pending=undefined;this.changed();syncResponse(res,{ok:true});return;}
  const peer=this.saved().peers.find(p=>p.fingerprint===fingerprint);if(!peer){syncResponse(res,{error:'设备未配对或信任已撤销'},403);return;}
  if(req.method==='GET'&&req.url==='/v1/manifest'){syncResponse(res,{payloadVersion:4,records:this.ledger.manifest(req.headers['x-clipper-payload-version']==='4')});return;}
  if(req.method==='POST'&&req.url==='/v1/item'){const value=await readSyncBody(req,4096);ensure();const item=this.ledger.item(value.id);if(item.payload.formats?.length&&value.payloadVersion!==4)throw new Error('原始格式同步需要双方升级至 Clipper 0.13 或以上');syncResponse(res,item);return;}
  if(req.method==='POST'&&req.url==='/v1/apply'){const value=await readSyncBody(req);ensure();const result=await this.enqueue(()=>{ensure();const result=this.ledger.apply(value.record,value.payload);if(result)this.changed();return result;});syncResponse(res,{changed:result});return;}
  syncResponse(res,{error:'不支持的同步操作'},404);
 }
 async tick(){if(this.ticking||!this.server)return;this.ticking=true;const generation=this.generation;try{
  if(this.joining){const joining=this.joining;try{const result=await this.call(joining.peer,'/v1/pair-status',{requestId:joining.requestId});if(this.joining!==joining||generation!==this.generation)return;if(result.status==='accepted'){this.trust(syncPeer(joining.peer));this.joining=undefined;this.changed();}else if(result.status==='rejected')throw new Error('另一台设备拒绝了配对');}catch(e){if(generation===this.generation){this.error=String((e as Error).message);this.joining=undefined;this.changed();}}}
  if(generation!==this.generation||!this.server)return;
  for(const configured of this.saved().peers){if(generation!==this.generation)return;const nearby=this.discovery?.list().find(p=>p.id===configured.id&&p.fingerprint===configured.fingerprint),peer=nearby?{...configured,host:nearby.host,port:nearby.port}:configured;await this.syncPeer(peer,generation);}
 }finally{this.ticking=false;}}
 private async syncPeer(peer:SyncPeer,generation:number){const status=this.status.get(peer.id)||{lastSync:0,error:'',busy:false};status.busy=true;this.status.set(peer.id,status);try{
  const reply=await this.call(peer,'/v1/manifest');if(!Array.isArray(reply.records)||reply.records.length>20000)throw new Error('设备同步目录无效');const records:SyncRecord[]=reply.records.map(syncRecord);if(new Set(records.map(r=>r.id)).size!==records.length)throw new Error('设备同步目录重复');let operations=0,unsupported=0;let ours=new Map(this.ledger.manifest().map(r=>[r.id,r]));
  for(const record of records){if(generation!==this.generation)return;const known=ours.get(record.id);if(known&&(known.hash!==record.hash||known.createdAt!==record.createdAt))throw new Error('设备同步目录冲突');if(known?.deleted||known&&!record.deleted)continue;if(operations++>=64)break;const data=record.deleted?{record}:await this.call(peer,'/v1/item',{id:record.id,payloadVersion:4});if(JSON.stringify(syncRecord(data.record))!==JSON.stringify(record))throw new Error('设备内容已改变，请重试');await this.enqueue(()=>{if(generation!==this.generation)return;if(this.ledger.apply(data.record,data.payload))this.changed();});}
  const remote=new Map(records.map(r=>[r.id,r]));for(const record of this.ledger.manifest()){if(generation!==this.generation)return;const other=remote.get(record.id);if(other?.deleted||other&&!record.deleted)continue;const data=record.deleted?{record}:this.ledger.item(record.id);if('payload' in data&&data.payload.formats?.length&&reply.payloadVersion!==4){unsupported++;continue;}if(operations++>=128)break;await this.call(peer,'/v1/apply',data);}
  status.lastSync=Date.now();status.error=unsupported?`${unsupported} 条原始格式待同步，请将另一台设备升级至 Clipper 0.13 或以上`:'';
 }catch(e){if(generation===this.generation)status.error=String((e as Error).message).slice(0,250);}finally{status.busy=false;if(generation===this.generation)this.changed();}}
}
