import {readdir,readFile,lstat,mkdir,writeFile,rm,unlink,rmdir} from 'node:fs/promises';
import {resolve,join,relative,isAbsolute} from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),asar=require('@electron/asar');
export function newestVersions(values){return [...new Set(values)].filter(value=>/^\d+\.\d+\.\d+$/.test(value)).sort((a,b)=>{const left=a.split('.').map(Number),right=b.split('.').map(Number);for(let i=0;i<3;i++)if(left[i]!==right[i])return right[i]-left[i];return 0;});}
async function boundary(root,file){root=resolve(root);file=resolve(file);const rel=relative(root,file);if(!rel||isAbsolute(rel)||rel==='..'||rel.startsWith('..\\')||rel.startsWith('../'))throw Error('Release path outside its root');let current=root;if((await lstat(current)).isSymbolicLink())throw Error('Linked release root');for(const part of rel.split(/[\\/]/)){current=join(current,part);try{if((await lstat(current)).isSymbolicLink())throw Error('Linked release path');}catch(error){if(error.code!=='ENOENT')throw error;}}return file;}
export async function releasePlan(root){const packages=[];for(const item of await readdir(root,{withFileTypes:true}).catch(()=>[])){if(!item.isDirectory()||!/^\d+\.\d+\.\d+$/.test(item.name))continue;const folder=await boundary(root,join(root,item.name)),archive=join(folder,'win-unpacked/resources/app.asar');try{await lstat(join(folder,'win-unpacked/Clipper.exe'));const version=JSON.parse(asar.extractFile(archive,'package.json')).version;if(version===item.name)packages.push(version);}catch{}}const versions=newestVersions(packages);return {retained:versions.slice(0,2),remove:versions.slice(2)};}
export async function removeRelease(root,file){
 file=await boundary(root,file);
 async function links(folder){for(const item of await readdir(folder,{withFileTypes:true})){if(item.isSymbolicLink())throw Error('Linked release contents');if(item.isDirectory())await links(join(folder,item.name));}}
 await links(file);
 const options={recursive:true,force:true,maxRetries:12,retryDelay:250},marker=join(file,'.clipper-generated-release');
 if(await readFile(marker,'utf8').catch(()=>'')==='Clipper generated release staging\n'){
  // Keep ownership until the payload has gone, so a failed cleanup can be retried.
  for(const item of await readdir(file))if(item!=='.clipper-generated-release')await rm(join(file,item),options);
  await unlink(marker);await rmdir(file);
 }else await rm(file,options);
}
export async function retainReleases(root,activePaths=[]){const plan=await releasePlan(root),removed=[];for(const version of plan.remove){const folder=join(resolve(root),version);if(activePaths.some(file=>resolve(file).toLowerCase().startsWith((folder+'/').replaceAll('/', '\\').toLowerCase())))throw Error('Old release is running: '+version);await removeRelease(root,folder);removed.push(version);}return {retained:plan.retained,removed};}
export async function staging(root,version){await mkdir(root,{recursive:true});if(version!==undefined&&!/^\d+\.\d+\.\d+$/.test(version))throw Error('Invalid release staging version');const folder=join(root,version?'.building-'+version:'.building'),marker=join(folder,'.clipper-generated-release');try{if(await readFile(marker,'utf8')!=='Clipper generated release staging\n')throw Error('Release staging marker mismatch');await removeRelease(root,folder);}catch(error){if(error.code!=='ENOENT')throw error;try{await lstat(folder);throw Error('Unmarked release staging');}catch(error){if(error.code!=='ENOENT')throw error;}}await mkdir(folder);await writeFile(marker,'Clipper generated release staging\n');return folder;}
export async function validateRelease(folder,source,version){const archive=join(folder,'win-unpacked/resources/app.asar');await lstat(join(folder,'win-unpacked/Clipper.exe'));if(JSON.parse(asar.extractFile(archive,'package.json')).version!==version)throw Error('Release version mismatch');const hash=value=>createHash('sha256').update(value).digest('hex');let checked=0;async function compare(directory){for(const item of await readdir(directory,{withFileTypes:true})){if(item.isSymbolicLink())throw Error('Linked build input');const file=join(directory,item.name);if(item.isDirectory()){await compare(file);continue;}if(item.name.endsWith('.map'))continue;const entry=relative(source,file),description=asar.statFile(archive,entry),packaged=description.unpacked?await readFile(join(archive+'.unpacked',entry)):asar.extractFile(archive,entry);if(hash(packaged)!==hash(await readFile(file)))throw Error('Packaged build differs: '+entry);checked++;}}await compare(join(source,'dist'));return {version,checked,buildMatchesPackage:true,fullFeatureAcceptance:false};}
