import './app.css';
import type {WebClientState} from '../shared/web-share';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let invitation=new URLSearchParams(location.hash.slice(1)).get('clipper-web')||'';history.replaceState(null,'',location.pathname);
let expiresAt=0,lastContact=Date.now();
let token='',closed=false,state:WebClientState|undefined,selected='',selectionGeneration=0,blobURL='',blob:Blob|undefined,bodyText='',pollTimer:ReturnType<typeof setTimeout>|undefined,streamController:AbortController|undefined,detailController:AbortController|undefined,refreshPromise:Promise<void>|undefined,retryRefresh=false;
const notice=(value:unknown)=>{$('notice').textContent=value instanceof Error?value.message:String(value);};
function clearDetail(){selectionGeneration++;detailController?.abort();detailController=undefined;if(blobURL)URL.revokeObjectURL(blobURL);blobURL='';blob=undefined;bodyText='';$('text').textContent='';$('image').removeAttribute('src');$('download').removeAttribute('href');$('detail').hidden=true;$('empty').hidden=false;}
function end(){if(closed)return;closed=true;token='';invitation='';receipt=undefined;clearTimeout(pollTimer);streamController?.abort();clearDetail();state=undefined;selected='';$('items').replaceChildren();$<HTMLTextAreaElement>('message').value='';$<HTMLInputElement>('file').value='';for(const id of ['join','waiting','workspace'])$(id).hidden=true;$('closed').hidden=false;$('connection').textContent='已结束';}
async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,cache:'no-store',credentials:'omit',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});if(!response.ok){let message='连接暂时不可用';try{message=(await response.json()).error||message;}catch{}if(response.status===410||response.status===403&&path!=='/api/connect')end();throw new Error(message);}lastContact=Date.now();return response;}
function render(){if(!state||closed)return;$('join').hidden=true;$('waiting').hidden=state.approved;$('workspace').hidden=!state.approved;$('code').textContent=state.code;$('connection').textContent=state.approved?'已连接 · '+state.name:'等待确认';if(!state.approved)return;$('role').textContent=state.allowSend?'可接收与发送':'仅接收';$('send').hidden=!state.allowSend;$('expiry').textContent='有效至 '+new Date(state.expires).toLocaleTimeString()+' · 内容由电脑端选择';$('count').textContent=String(state.items.length);
 if(selected&&!state.items.some(i=>i.id===selected)){selected='';clearDetail();notice('电脑端已撤回该内容');}
 const nodes=state.items.map(item=>{const button=document.createElement('button');button.className='item'+(item.id===selected?' selected':'');button.dataset.id=item.id;button.setAttribute('aria-pressed',String(item.id===selected));const title=document.createElement('strong'),preview=document.createElement('span');title.textContent=(item.image?'▧  ':'')+item.title;preview.textContent=item.preview;button.append(title,preview);button.onclick=()=>void select(item.id).catch(notice);return button;});$('items').replaceChildren(...nodes);if(!nodes.length){const p=document.createElement('p');p.className='hint';p.textContent='电脑端尚未选择共享内容';$('items').append(p);}
}
async function refresh(){if(closed||!token)return;if(refreshPromise){retryRefresh=true;return refreshPromise;}refreshPromise=(async()=>{do{retryRefresh=false;const next=await(await request('/api/state')).json() as WebClientState;if(closed)return;state=next;expiresAt=next.expires;render();}while(retryRefresh&&!closed);})().finally(()=>{refreshPromise=undefined;});return refreshPromise;}
async function waitForApproval(){try{await refresh();if(closed)return;if(state?.approved){void stream();return;}}catch(e){notice(e);}if(!closed)pollTimer=setTimeout(()=>void waitForApproval(),1200);}
function disconnected(){selected='';clearDetail();$('items').replaceChildren();state=undefined;$('workspace').hidden=true;$('connection').textContent='正在重新连接…';}
async function stream(){while(!closed){try{streamController=new AbortController();const response=await request('/api/events',{signal:streamController.signal}),reader=response.body!.getReader(),decoder=new TextDecoder();let pending='';while(!closed){const next=await reader.read();if(next.done)break;lastContact=Date.now();pending+=decoder.decode(next.value,{stream:true});if(pending.length>8192)throw new Error('更新消息异常');let boundary;while((boundary=pending.indexOf('\n\n'))>=0){const event=pending.slice(0,boundary);pending=pending.slice(boundary+2);if(event.includes('event: closed')){end();return;}if(event.includes('event: changed'))await refresh();}}}catch(e){if(closed)return;notice(e);}finally{streamController?.abort();}if(!closed){disconnected();await new Promise<void>(resolve=>setTimeout(resolve,2000));try{await refresh();}catch(e){notice(e);}}}}
async function select(id:string){if(!state?.items.some(i=>i.id===id))return;clearDetail();notice('');selected=id;render();const generation=selectionGeneration,controller=detailController=new AbortController();const response=await request('/api/item/'+id,{signal:controller.signal});const isImage=response.headers.get('content-type')==='image/png';const value=isImage?await response.blob():(await response.json()).text;if(closed||generation!==selectionGeneration||!state?.items.some(i=>i.id===id))return;$('title').textContent=state.items.find(i=>i.id===id)!.title;$('image').hidden=!isImage;$('text').hidden=isImage;$('download').hidden=!isImage;$('select').hidden=isImage;if(isImage){blob=value;blobURL=URL.createObjectURL(value);$<HTMLImageElement>('image').src=blobURL;$<HTMLAnchorElement>('download').href=blobURL;}else{bodyText=value;$('text').textContent=value;}$('detail').hidden=false;$('empty').hidden=true;}
$('connect-form').onsubmit=async e=>{e.preventDefault();const button=$<HTMLButtonElement>('connect');button.disabled=true;try{if(!invitation)throw new Error('邀请缺失，请从电脑端的新邀请链接打开');const result=await(await request('/api/connect',{method:'POST',body:JSON.stringify({invite:invitation,name:$<HTMLInputElement>('name').value,verified:$<HTMLInputElement>('verified').checked})})).json();token=result.token;invitation='';await waitForApproval();}catch(e){notice(e);}finally{button.disabled=false;}};
$('copy').onclick=()=>{if(!selected||closed)return;const task=blob?navigator.clipboard?.write([new ClipboardItem({'image/png':blob})]):navigator.clipboard?.writeText(bodyText);if(!task){notice('浏览器不允许复制，请选中文字或另存图片');return;}void task.then(()=>notice('已复制')).catch(()=>notice('浏览器不允许复制，请选中文字或另存图片'));};
$('select').onclick=()=>{const range=document.createRange();range.selectNodeContents($('text'));const selection=getSelection();selection?.removeAllRanges();selection?.addRange(range);notice('已选中文字，可使用系统复制操作');};
let sending=false,receipt:{key:string;id:string}|undefined;
async function send(payload:{text?:string;png?:string}){if(sending||closed)return;const key=JSON.stringify(payload);if(new TextEncoder().encode(key).length>16*1024*1024)throw new Error('转换后的内容超过 16 MiB');if(!receipt||receipt.key!==key)receipt={key,id:crypto.randomUUID()};sending=true;$<HTMLButtonElement>('send-text').disabled=true;$<HTMLInputElement>('file').disabled=true;try{await request('/api/send',{method:'POST',body:JSON.stringify({requestId:receipt.id,payload})});receipt=undefined;notice('已发送到电脑的 Clipper 历史');}finally{sending=false;$<HTMLButtonElement>('send-text').disabled=false;$<HTMLInputElement>('file').disabled=false;}}
$('send-form').onsubmit=e=>{e.preventDefault();const text=$<HTMLTextAreaElement>('message').value;if(!text.trim()){notice('请输入文字');return;}if(new TextEncoder().encode(text).length>1024*1024){notice('文字超过 1 MiB');return;}void send({text}).catch(notice);};
$<HTMLInputElement>('file').onchange=()=>{const file=$<HTMLInputElement>('file').files?.[0];if(!file)return;void(async()=>{if(file.size>16*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('请选择不超过 16 MiB 的 PNG、JPEG 或 WebP 图片');const image=await createImageBitmap(file);try{if(image.width>16384||image.height>16384||image.width*image.height>40000000)throw new Error('图片尺寸过大');const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d')!.drawImage(image,0,0);const png=canvas.toDataURL('image/png').split(',')[1];await send({png});}finally{image.close();$<HTMLInputElement>('file').value='';}})().catch(notice);};
setInterval(()=>{if(token&&(expiresAt&&Date.now()>=expiresAt||Date.now()-lastContact>90000))end();else if(state?.approved&&Date.now()-lastContact>35000){streamController?.abort();disconnected();}},1000);addEventListener('pagehide',end);if(!invitation){$<HTMLButtonElement>('connect').disabled=true;notice('邀请缺失，请从电脑端生成的完整链接打开此页');}
addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).has('clipper-web'))location.reload();});

addEventListener('offline',()=>{if(!closed&&token){streamController?.abort();disconnected();}});
