import type {ClipPreview,SnippetPreview} from '../shared/preview';
import {t as tr} from '../shared/i18n';
import {setupShortcut} from './shortcut';
import type {ReplyIntent} from '../shared/efficiency';
import {showContentInfo} from './content-info-ui';
import type { Category, Snippet, Detail, Payload, Kind } from '../shared/types';
import { categoryColors, templateVariables, builtins, fillTemplate } from '../shared/advanced';
const api=window.clipper;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown,undo?:boolean):void;select(id:string):Promise<void>;refresh():Promise<void>;ai(text:string):Promise<void>}
export function advancedUI(ctx:Context){
  function category(value?:Category){let color=value?.color||categoryColors[0],kind=value?.kind||'all';ctx.modal(value?tr('编辑分类'):tr('新建分类'),tr`<label class="field">名称<input id="category-name" value="${esc(value?.name)}" maxlength="40" required></label><div class="field">颜色<div class="color-choices">${categoryColors.map(c=>tr`<button type="button" data-category-color="${c}" class="color-choice ${c===color?'chosen':''}" style="--swatch:${c}" aria-label="颜色 ${c}"></button>`).join('')}</div></div><div class="field">内容类型<div class="type-choices tabs">${['all','text','link','code','image','files'].map((k,i)=>`<button type="button" data-category-kind="${k}" class="${k===kind?'active':''}">${[tr('不限'),tr('文本'),tr('链接'),tr('代码'),tr('图片'),tr('文件')][i]}</button>`).join('')}</div></div><label class="field">内容包含<input id="category-contains" value="${esc(value?.contains)}" maxlength="200" placeholder="例如 github.com"></label><label class="field">来源应用包含<input id="category-source" value="${esc(value?.source)}" maxlength="200" placeholder="例如 chrome"></label><label class="field">标签等于<input id="category-tag" value="${esc(value?.tag)}" maxlength="32" placeholder="例如 工作"></label><p class="field-help">已填写的条件须同时满足；分类会自动包含符合条件的历史记录。</p>`,async()=>{await api.category({id:value?.id,name:q<HTMLInputElement>('category-name').value,color,kind,contains:q<HTMLInputElement>('category-contains').value,source:q<HTMLInputElement>('category-source').value,tag:q<HTMLInputElement>('category-tag').value});await ctx.refresh();ctx.toast(tr('分类已保存'));});
    document.querySelectorAll<HTMLButtonElement>('[data-category-color]').forEach(b=>b.onclick=()=>{color=b.dataset.categoryColor!;document.querySelectorAll<HTMLElement>('[data-category-color]').forEach(x=>x.classList.toggle('chosen',x===b));});
    document.querySelectorAll<HTMLButtonElement>('[data-category-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.categoryKind as Category['kind'];document.querySelectorAll<HTMLElement>('[data-category-kind]').forEach(x=>x.classList.toggle('active',x===b));});
  }
  async function editSnippet(value?:Partial<Snippet>|Partial<SnippetPreview>,clip?:ClipPreview){let initialText='';if(value?.id&&typeof value.payload?.png!=='boolean')value=await api.snippetPreview(value.id);const settings=await api.efficiencyState(),key=settings.options.bindings.find(b=>b.id===value?.id)?.shortcut||'';const payload=clip?.payload||value?.payload,hasBinary=!!(payload?.png||payload?.files||payload?.attachments||!payload?.text&&payload?.formats?.length),text=payload?.text??value?.text??'';
    ctx.modal(value?.id?tr('编辑快捷回复'):tr('新建快捷回复'),tr`<label class="field">标题<input id="reply-title" maxlength="120" value="${esc(clip?.title??value?.title)}" placeholder="例如：邮件签名" required></label>${hasBinary?`<div class="template-attachment">${payload?.png?tr`<img src="${esc(clip?.imageURL||(value as Partial<SnippetPreview>)?.imageURL)}" alt="图片模板">`:`<p>${(payload?.files||payload?.attachments?.map(a=>a.name)||payload?.formats?.map(f=>f.name)||[]).map(esc).join('<br>')}</p>`}</div><p class="field-help">${payload?.png||payload?.attachments||payload?.formats?.length?tr('原始内容随模板保留。'):tr('文件模板保留原路径，源文件移动后需重新保存模板。')}</p>`:tr`<label class="field">内容<textarea id="reply-text" rows="8" placeholder="输入常用文字" required>${esc(text)}</textarea></label><p class="field-help">用 {{姓名}} 插入填写项，{{日期}} / {{时间}} 自动填入本地日期与时间。未改动内容时保留原格式；修改或填写变量后使用纯文本。</p>`}<label class="field">独立快捷键<input id="reply-shortcut" data-value="${esc(key)}" aria-label="模板独立快捷键"></label><p class="field-help">可留空。普通模板直接粘贴，带填写项的模板先预览。Delete 清除，Esc 取消录入。</p>`,async()=>{await api.snippet({id:value?.id,shortcut:q('reply-shortcut').dataset.value||'',title:q<HTMLInputElement>('reply-title').value,...(hasBinary?{clipId:clip?.id}:q<HTMLTextAreaElement>('reply-text').value===initialText&&(clip||value?.id)?(clip?{clipId:clip.id}:{}):{text:q<HTMLTextAreaElement>('reply-text').value})});await ctx.refresh();ctx.toast(tr('已保存快捷回复'));});if(!hasBinary)initialText=q<HTMLTextAreaElement>('reply-text').value;setupShortcut(q<HTMLInputElement>('reply-shortcut'),ctx.toast);
  }
  async function useSnippet(id:string,paste:boolean,intent?:Extract<ReplyIntent,{kind:'fill'}>){const snippet=intent?.snippet||await api.snippetPreview(id),submit=(values:Record<string,string>={})=>intent?api.resolveReply(intent.token,values):api.useSnippet(id,paste,values),variables=templateVariables(snippet.text).filter(v=>!builtins.includes(v));if(!variables.length){await submit();if(!paste)ctx.toast(tr('已复制'));return;}
    ctx.modal(tr('填写回复内容'),tr`<p class="template-title">${esc(snippet.title)}</p>${variables.map((v,i)=>`<label class="field">${esc(v)}<input data-variable="${i}" maxlength="10000" required></label>`).join('')}<div class="field">预览<pre id="template-preview" class="template-preview">填写变量后显示预览</pre></div>`,async()=>{const values=Object.fromEntries(variables.map((name,i)=>[name,document.querySelector<HTMLInputElement>(`[data-variable="${i}"]`)!.value]));await submit(values);if(!paste)ctx.toast(tr('已复制'));},paste?tr('粘贴'):tr('复制'));if(intent)q<HTMLDialogElement>('dialog').addEventListener('close',()=>{void api.resolveReply(intent.token,null).catch(()=>{});},{once:true});
    document.querySelectorAll<HTMLInputElement>('[data-variable]').forEach(input=>input.oninput=()=>{try{const values=Object.fromEntries(variables.map((name,i)=>[name,document.querySelector<HTMLInputElement>(`[data-variable="${i}"]`)!.value]));q('template-preview').textContent=fillTemplate({text:snippet.text},values).text||'';}catch{q('template-preview').textContent=tr('填写所有变量后显示预览');}});
  }
  async function ocr(id:string){
    ctx.modal(tr('识别图片文字'),tr(`<div id="ocr-info" class="field-help">正在检查本地识别语言…</div><div id="ocr-languages" class="type-choices tabs"></div><div class="ocr-toolbar"><button type="button" id="ocr-run" disabled>开始识别</button><button type="button" id="ocr-cancel" hidden>取消识别</button><span id="ocr-progress"></span></div><label class="field">识别结果<textarea id="ocr-output" rows="10" placeholder="识别后可在这里修正文字"></textarea></label>`),async()=>{const created=await api.saveOcr(q<HTMLTextAreaElement>('ocr-output').value);await ctx.select(created);ctx.toast(tr('识别文字已保存到历史'));},tr('保存文字'));
    const output=q<HTMLTextAreaElement>('ocr-output'),infoNode=q('ocr-info'),run=q<HTMLButtonElement>('ocr-run'),cancel=q('ocr-cancel'),progress=q('ocr-progress');let language='',running=false;
    const translate=document.createElement('button');translate.type='button';translate.id='ocr-translate';translate.textContent=tr('翻译文字');run.parentElement!.append(translate);translate.onclick=()=>{if(!output.value.trim()){ctx.toast(tr('请先识别或输入文字'));return;}const text=output.value;q<HTMLDialogElement>('dialog').close();void ctx.ai(text).catch(ctx.toast);};
    q<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(running)void api.cancelOcr();},{once:true});
    const info=await api.ocrStatus();if(!infoNode.isConnected)return;if(info.error||!info.languages.length){infoNode.textContent=info.error||tr('未安装 OCR 语言。请在 Windows 设置 → 时间和语言中添加识别组件，然后重启 Clipper。');return;}
    language=info.languages[0].tag;infoNode.textContent=tr('使用 Windows 本地识别，图片不会上传。');q('ocr-languages').innerHTML=info.languages.map(l=>`<button type="button" data-ocr-language="${esc(l.tag)}" class="${l.tag===language?'active':''}">${esc(l.name)}</button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-ocr-language]').forEach(b=>b.onclick=()=>{language=b.dataset.ocrLanguage!;document.querySelectorAll<HTMLElement>('[data-ocr-language]').forEach(x=>x.classList.toggle('active',x===b));});run.disabled=false;
    run.onclick=async()=>{run.disabled=true;running=true;cancel.hidden=false;progress.textContent=tr('正在识别…');try{const result=await api.ocr(id,language);if(!output.isConnected)return;output.value=result.text;progress.textContent=result.text?(result.scaled?tr('识别完成（图片已按系统限制缩小）'):tr('识别完成')):tr('未识别到文字，可换个区域重试');}catch(e){if(progress.isConnected)progress.textContent=String((e as Error).message).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{running=false;run.disabled=false;cancel.hidden=true;}};
    cancel.onclick=()=>void api.cancelOcr();
  }
  async function screenshot(){const screens=await api.screens();let display=screens[0]?.id,mode:'region'|'screen'|'window'='region',token='',loading=0;if(display===undefined)throw new Error(tr('没有可用显示器'));ctx.modal(tr('截图'),tr`<div class="field">模式<div class="type-choices tabs"><button id="capture-region" type="button" class="active">区域截图</button><button id="capture-window" type="button">独立窗口</button><button id="capture-long" type="button">滚动长截图</button><button id="capture-screen" type="button">整个显示器</button></div></div><div class="field" id="capture-displays">显示器<div class="screen-choices">${screens.map(s=>`<button type="button" data-screen="${s.id}" class="${s.id===display?'active':''}">${esc(s.name)}<small>${s.width} × ${s.height}</small></button>`).join('')}</div></div><div id="capture-window-panel" hidden><button type="button" id="capture-refresh">刷新窗口</button><div id="capture-windows" class="capture-windows"></div></div><p id="capture-help" class="field-help">开始后 Clipper 会暂时隐藏。区域截图按 Esc 取消，确认后保存到图片历史。</p>`,async()=>{if(mode==='window'&&!token)throw new Error(tr('请先选择一个窗口'));const id=mode==='window'?await api.screenshotWindow(token):await api.screenshot(mode,display);q<HTMLDialogElement>('dialog').close();if(id){await ctx.select(id);ctx.toast(tr('截图已保存'));}},tr('开始截图'));
    const refresh=async()=>{token='';const request=++loading,node=q('capture-windows');node.textContent=tr('正在查找可捕获窗口…');try{const choices=await api.captureWindows();if(!node.isConnected||loading!==request)return;node.replaceChildren();for(const choice of choices){const b=document.createElement('button');b.type='button';b.className='capture-window-choice';b.dataset.windowToken=choice.token;const img=document.createElement('img');img.src=choice.thumbnail;img.alt='';const name=document.createElement('span');name.textContent=choice.name;b.append(img,name);b.onclick=()=>{token=choice.token;node.querySelectorAll('button').forEach(el=>el.classList.toggle('active',el===b));};node.append(b);}if(!choices.length)node.textContent=tr('没有可捕获窗口。请打开或还原目标窗口后刷新。');}catch(e){if(node.isConnected)node.textContent=String(e);}};
    q('capture-refresh').onclick=()=>void refresh();for(const value of ['region','screen','window'] as const)q('capture-'+value).onclick=()=>{mode=value;for(const name of ['region','screen','window'])q('capture-'+name).classList.toggle('active',name===value);q('capture-displays').hidden=value==='window';q('capture-window-panel').hidden=value!=='window';q('capture-help').textContent=value==='window'?tr('请选择未最小化的窗口。最长边 2,560 像素；受保护内容可能无法捕获。'):tr('开始后 Clipper 会暂时隐藏。区域截图按 Esc 取消，确认后保存到图片历史。');if(value==='window')void refresh();};q('capture-long').onclick=()=>{q<HTMLDialogElement>('dialog').close();void api.openScrollCapture().catch(ctx.toast);};document.querySelectorAll<HTMLElement>('[data-screen]').forEach(b=>b.onclick=()=>{display=Number(b.dataset.screen);document.querySelectorAll<HTMLElement>('[data-screen]').forEach(x=>x.classList.toggle('active',x===b));});
  }
  const contentInfo=(id:string)=>showContentInfo(ctx,id);
  return {category,editSnippet,useSnippet,ocr,screenshot,contentInfo};
}
