import {requiredForm} from './form-validation';
import type {ClipPreview,SnippetPreview} from '../shared/preview';
import {t as tr} from '../shared/i18n';
import {setupShortcut} from './shortcut';
import {editCategory} from './category-ui';
import type {ReplyIntent} from '../shared/efficiency';
import {showContentInfo} from './content-info-ui';
import type { Category, Snippet } from '../shared/types';
import { templateVariables, builtins, fillTemplate } from '../shared/advanced';
const api=window.clip;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
interface Context {categories():Category[];modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown,undo?:boolean):void;select(id:string):Promise<void>;refresh():Promise<void>}
export function advancedUI(ctx:Context){
  const category=(value?:Category)=>editCategory(ctx,value);
  async function editSnippet(value?:Partial<Snippet>|Partial<SnippetPreview>,clip?:ClipPreview){let initialText='';if(value?.id&&typeof value.payload?.png!=='boolean')value=await api.snippetPreview(value.id);const settings=await api.efficiencyState(),key=settings.options.bindings.find(b=>b.id===value?.id)?.shortcut||'';const payload=clip?.payload||value?.payload,hasBinary=!!(payload?.png||payload?.files||payload?.attachments||!payload?.text&&payload?.formats?.length),text=payload?.text??value?.text??'';
    ctx.modal(value?.id?tr('编辑快捷回复'):tr('新建快捷回复'),tr`<label class="field">标题<input id="reply-title" maxlength="120" value="${esc(clip?.title??value?.title)}" placeholder="例如：邮件签名" required data-required-message="${tr('请输入标题')}"></label>${hasBinary?`<div class="template-attachment">${payload?.png?tr`<img src="${esc(clip?.imageURL||(value as Partial<SnippetPreview>)?.imageURL)}" alt="图片模板">`:`<p>${(payload?.files||payload?.attachments?.map(a=>a.name)||payload?.formats?.map(f=>f.name)||[]).map(esc).join('<br>')}</p>`}</div><p class="field-help">${payload?.png||payload?.attachments||payload?.formats?.length?tr('原始内容随模板保留。'):tr('文件模板保留原路径，源文件移动后需重新保存模板。')}</p>`:tr`<label class="field">内容<textarea id="reply-text" rows="8" placeholder="输入常用文字" required data-required-message="${tr('请输入回复内容')}">${esc(text)}</textarea></label><p class="field-help">用 {{姓名}} 插入填写项，{{日期}} / {{时间}} 自动填入本地日期与时间。未改动内容时保留原格式；修改或填写变量后使用纯文本。</p>`}<label class="field">独立快捷键<input id="reply-shortcut" data-value="${esc(key)}" aria-label="模板独立快捷键"></label><p class="field-help">可留空。普通模板直接粘贴，带填写项的模板先预览。Delete 清除，Esc 取消录入。</p>`,async()=>{await api.snippet({id:value?.id,shortcut:q('reply-shortcut').dataset.value||'',title:q<HTMLInputElement>('reply-title').value,...(hasBinary?{clipId:clip?.id}:q<HTMLTextAreaElement>('reply-text').value===initialText&&(clip||value?.id)?(clip?{clipId:clip.id}:{}):{text:q<HTMLTextAreaElement>('reply-text').value})});await ctx.refresh();ctx.toast(tr('已保存快捷回复'));});const editor=q<HTMLDialogElement>('dialog');editor.classList.add('reply-editor');for(const group of editor.querySelectorAll('.modal-fields'))group.replaceWith(...group.childNodes);editor.addEventListener('close',()=>editor.classList.remove('reply-editor'),{once:true});requiredForm(editor.querySelector('form')!);if(!hasBinary)initialText=q<HTMLTextAreaElement>('reply-text').value;setupShortcut(q<HTMLInputElement>('reply-shortcut'),ctx.toast);
  }
  async function useSnippet(id:string,paste:boolean,intent?:Extract<ReplyIntent,{kind:'fill'}>){const snippet=intent?.snippet||await api.snippetPreview(id),submit=(values:Record<string,string>={})=>intent?api.resolveReply(intent.token,values):api.useSnippet(id,paste,values),variables=templateVariables(snippet.text).filter(v=>!builtins.includes(v));if(!variables.length){await submit();if(!paste)ctx.toast(tr('已复制'));return;}
    ctx.modal(tr('填写回复内容'),tr`<p class="template-title">${esc(snippet.title)}</p>${variables.map((v,i)=>`<label class="field">${esc(v)}<input data-variable="${i}" maxlength="10000" required></label>`).join('')}<div class="field">预览<pre id="template-preview" class="template-preview">填写变量后显示预览</pre></div>`,async()=>{const values=Object.fromEntries(variables.map((name,i)=>[name,document.querySelector<HTMLInputElement>(`[data-variable="${i}"]`)!.value]));await submit(values);if(!paste)ctx.toast(tr('已复制'));},paste?tr('粘贴'):tr('复制'));if(intent)q<HTMLDialogElement>('dialog').addEventListener('close',()=>{void api.resolveReply(intent.token,null).catch(()=>{});},{once:true});
    document.querySelectorAll<HTMLInputElement>('[data-variable]').forEach(input=>input.oninput=()=>{try{const values=Object.fromEntries(variables.map((name,i)=>[name,document.querySelector<HTMLInputElement>(`[data-variable="${i}"]`)!.value]));q('template-preview').textContent=fillTemplate({text:snippet.text},values).text||'';}catch{q('template-preview').textContent=tr('填写所有变量后显示预览');}});
  }
  const contentInfo=(id:string)=>showContentInfo(ctx,id);
  return {category,editSnippet,useSnippet,contentInfo};
}
