import {renderReplyCards} from './reply-cards';
import {acceptsDrop,importDroppedImage} from './image-drop';
import {recordRemoval} from './record-motion';
import {categoryGlyph,hydrateCategoryGlyphs} from './category-glyph';
import {HISTORY_CLEAR_DETAIL} from '../shared/history-clear';
import {QUICK_SHORTCUT} from '../shared/quick-panel';
import {tasksUI} from './tasks-ui';
import {openAnchoredPopover,closeAnchoredPopover} from './anchored-popover';
import {bindHeadingMenu} from './heading-menu';
import {captureToolsUI} from './capture-tools-ui';
import {dialogParts,openOneDialog,oneDialogDismissLocked} from './dialog-shell';
import {searchField,setSearchFieldValue} from './one-search';
import {icon as componentIcon,iconButton,registerIcons} from './ui';
import type {ClipPreview} from '../shared/preview';
import {mountImagePreview} from './image-preview';
import {filesPreviewMarkup,mountFilesPreview} from './file-preview';
import {closeDialog,resetDialogMotion} from './dialog-motion';
import {collectionLayout,detailLayout,bindDetailLayout,modalLayout} from './layout-029';
import {setMarkup,keyedMarkup,patchMarkup,clearMarkup,retainListScroll} from './markup';
import {collectionItems} from '../shared/collection';
import {clipExtension,clipFilterPredicate,emptyClipFilters,hasClipFilters,normalizeClipFilters,type ClipFilters} from '../shared/clip-filters';
import {windowControls,setupChrome} from './chrome';
import {showShortcutRegistrationErrors} from './settings-shortcuts';
import {setupShortcut,shortcutFeedback,isShortcutError} from './shortcut';
import {shortcutLabel} from '../shared/shortcut';
import {bindSettingsPreferences} from './settings-preferences';
import {applySidebarLayout,readSidebarLayout,saveSidebarLayout,sidebarGroups,type SidebarGroup} from './sidebar-layout';
import {revealToolbar} from './toolbar-motion';
import {applicationSegments} from './application-segments';
import {appIdentity,hydrateAppIcons,sourceKey} from './source-apps';
import {dateField,bindDatePickers} from './date-picker';
import {inlineSettings} from './inline-settings';
import {closeControls} from './controls';
import {APP_VERSION} from '../shared/version';
import {mountUpdates} from './update-ui';
import {mountProgramVersions} from './program-versions-ui';
import {sectionLayout} from './page-layout';
import {bindSortable} from './sortable';
import {mountImageHostSettings} from './image-host-ui';
import {Palette,MousePointer2,Database,Archive,RotateCcw} from 'lucide';
import {enableFeedbackScroll,showFeedback,dismissFeedback} from './feedback';
import {ActionScope,setActionDisabled} from './actions';
import {mountTextPreview,useTextReader,type TextPreviewHandle} from './lazy-text-preview';
import type {TextPreviewSnapshot} from './text-preview';
import {isWindowVisible,onWindowVisibility,setupWindowVisibility} from './window-visibility';
import './locale';
import {t as tr,formatBytes,formatDate,formatNumber} from '../shared/i18n';
import {languageUI} from './language-ui';
import './appearance';
import {appearanceUI} from './appearance-ui';
import {stackUI} from './stack-ui';
import {efficiencyUI} from './efficiency-ui';
import {mountAuxiliaryShortcuts} from './settings-shortcuts';
import {webUI} from './web-ui';
import './styles.css';
import './date-picker.css';
import './settings-stage.css';
import './desktop.css';
import {desktopUI} from './desktop-ui';
import {cardNavigation} from '../shared/desktop';
import { Clipboard, History, Star, Layers, MessageSquare, Settings2, Search, FileText, Image, Folder, FolderInput, Link, Code, Copy, Pin, Trash2, Plus, ArrowUp, ArrowDown, GripVertical, X, Check, Pause, Play, ChevronRight, List, Grid2X2, Download, Upload, Keyboard, ShieldCheck, CloudUpload, Sun, Moon, Monitor, MonitorSmartphone, Pencil, CornerDownLeft, Undo2, Power, PanelLeft, Info, Ellipsis, AppWindow, Smile, BookOpen, Bot, SlidersHorizontal, RefreshCw, type IconNode } from 'lucide';
import type { State, Clip, Detail, Kind, Settings, Snippet, ClipAction } from '../shared/types';
import { advancedUI } from './advanced-ui';
import { textToolsUI } from './text-tools-ui';
import {dataUI} from './data-ui';
import {syncUI} from './sync-ui';
const actions=new ActionScope();
const api=window.clip;
const icons:Record<string,IconNode>={clipboard:Clipboard,history:History,star:Star,stack:Layers,replies:MessageSquare,settings:Settings2,search:Search,text:FileText,image:Image,files:Folder,container:FolderInput,link:Link,code:Code,copy:Copy,pin:Pin,trash:Trash2,plus:Plus,up:ArrowUp,down:ArrowDown,grip:GripVertical,close:X,check:Check,pause:Pause,play:Play,chevron:ChevronRight,list:List,grid:Grid2X2,download:Download,upload:Upload,keyboard:Keyboard,shield:ShieldCheck,sun:Sun,moon:Moon,monitor:Monitor,devices:MonitorSmartphone,edit:Pencil,enter:CornerDownLeft,undo:Undo2,power:Power,panel:PanelLeft,info:Info,more:Ellipsis,app:AppWindow,smile:Smile,book:BookOpen,bot:Bot,filter:SlidersHorizontal,refresh:RefreshCw};
registerIcons(icons);
const ico=(key:string)=>componentIcon('lucide:'+key);
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const button=(id:string,label:string,icon:string,cls='')=>`<button id="${id}" class="${cls}">${ico(icon)}<span>${label}</span></button>`;
const ib=(id:string,label:string,icon:string,active=false)=>iconButton(id,label,'lucide:'+icon,active);
const labels:Record<string,string>={history:tr('全部记录'),favorites:tr('收藏'),stack:tr('堆栈'),replies:tr('快捷回复'),settings:tr('设置'),shelf:tr('拖拽容器'),'text-tools':tr('AI与脚本'),'capture-tools':tr('截图与录制'),ai:tr('AI 服务'),scripts:tr('文本脚本'),uri:'URI',web:tr('网页共享'),sync:tr('局域网同步'),symbols:tr('表情符号'),cheats:'CheetSheet',text:tr('文本'),link:tr('链接'),code:tr('代码'),image:tr('图片'),files:tr('文件'),all:tr('全部')};
const shortcut=(s:string)=>shortcutLabel(s).replaceAll('+',' + ');
const bytes=formatBytes;
function time(n:number){const diff=Date.now()-n;return diff<60000?tr('刚刚'):diff<3600000?tr`${Math.floor(diff/60000)} 分钟前`:diff<86400000?tr`${Math.floor(diff/3600000)} 小时前`:formatDate(n,{month:'short',day:'numeric'});}
let state:State,page='history',selected='',query='',matches:Set<string>|null=null,limit=100,visible:Clip[]=[],toastTimer:ReturnType<typeof setTimeout>,searchTimer:ReturnType<typeof setTimeout>,detailToken=0,refreshToken=0,searchRevision=0;
let replyLayout: 'cards'|'list'=localStorage.getItem('reply-layout')==='list'?'list':'cards';
let disposeTextPreview:TextPreviewHandle|undefined,disposeImagePreview:(()=>void)|undefined,disposeFilesPreview:(()=>void)|undefined,detailKey='',detailRoot:HTMLElement|undefined,imageLease:string|undefined;
let renderedPreviewIdentity='',retainedClip:ClipPreview|undefined,pendingPreview:{root:HTMLElement;identity:string}|undefined;
function previewIdentity(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);return JSON.stringify([page==='replies'?'snippet':'clip',selected,query,item&&('hash'in item?[item.hash,item.kind]:[item.revision,item.kind])]);}
let suspendedPreview:{key:string;top:number;left:number;reader?:TextPreviewSnapshot}|undefined;
function contentKey(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);return JSON.stringify([page,selected,selectedQueueIndex,query,item&&('hash'in item?[item.hash,item.kind]:[item.revision,item.kind])]);}
function suspendDetail(){const root=q('detail');if(root?.childElementCount){const key=contentKey(),reader=disposeTextPreview?.snapshot();if(reader||!suspendedPreview||suspendedPreview.key!==key)suspendedPreview={key,top:root.querySelector('.preview-body')?.scrollTop||0,left:root.querySelector('.preview-body')?.scrollLeft||0,reader};}releaseDetail();root?.replaceChildren();}
function releaseDetail(){if(detailRoot)clearMarkup(detailRoot);renderedPreviewIdentity='';retainedClip=undefined;pendingPreview=undefined;if(imageLease){void api.releasePreview(imageLease).catch(()=>{});imageLease=undefined;}disposeTextPreview?.();disposeTextPreview=undefined;disposeImagePreview?.();disposeImagePreview=undefined;disposeFilesPreview?.();disposeFilesPreview=undefined;detailKey='';detailRoot=undefined;detailToken++;}
function currentDetailKey(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);const metadata=item&&('hash'in item?[item.id,item.hash,item.kind,item.title,item.source,item.createdAt,item.updatedAt,item.favorite,item.pinned,item.tags,item.bytes,item.shared,item.localOnly]:[item.id,item.title,item.updatedAt,item.kind,item.shortcut,item.revision]);return JSON.stringify([page,selected,selectedQueueIndex,query,state.queue.includes(selected),state.stack.options.duplicates,metadata]);}
function showTextReader(text:string,code:boolean){const host=q('detail').querySelector<HTMLElement>('.preview-body')!,button=q<HTMLButtonElement>('preview-wrap'),storageKey=code?'preview-code-wrap':'preview-text-wrap',saved=localStorage.getItem(storageKey);disposeTextPreview=mountTextPreview(host,text,{code,query,wrap:saved===null?!code:saved==='true',wrapButton:button,changedWrap:value=>localStorage.setItem(storageKey,String(value)),resume:suspendedPreview?.key===contentKey()?suspendedPreview.reader:undefined});}
function restorePreviewPosition(){const saved=suspendedPreview;suspendedPreview=undefined;if(saved?.key!==contentKey())return;const host=q('detail').querySelector<HTMLElement>('.preview-body');if(host){host.scrollTop=saved.top;host.scrollLeft=saved.left;}}
let selectedQueueIndex=-1,visibleQueueIndices:number[]=[];
let batchMode=false,checked=new Set<string>(),clipsByID=new Map<string,Clip>();
let clipFilters:ClipFilters=emptyClipFilters(),filterPopoverOpen=false;
const resetClipFilters=()=>{clipFilters=emptyClipFilters();filterPopoverOpen=false;};
const updateClipFilters=(value:Partial<ClipFilters>)=>{clipFilters=normalizeClipFilters({...clipFilters,...value});limit=100;selected='';releaseDetail();renderCollection();};
function setFilterPopover(open:boolean){filterPopoverOpen=open;const popover=document.getElementById('advanced-filter-popover'),toggle=document.getElementById('advanced-filter-toggle');toggle?.setAttribute('aria-expanded',String(open));if(!popover||!toggle)return;popover.setAttribute('aria-hidden',String(!open));popover.style.pointerEvents=open?'':'none';if(open){popover.hidden=false;openAnchoredPopover(popover,toggle,580,660);}else closeAnchoredPopover(popover);}
document.addEventListener('pointerdown',event=>{const target=event.target;if(!filterPopoverOpen||!(target instanceof Element)||target.closest('.advanced-filter')||target.closest('.select-popup')&&document.querySelector('.advanced-filter [role=combobox][aria-expanded=true]'))return;setFilterPopover(false);});
const categoryId=()=>page.startsWith('category:')?page.slice(9):undefined;
const selectClip=async(id:string)=>{resetClipFilters();await refresh();page=state.shelf.includes(id)?'shelf':'history';selected=id;query='';matches=null;render();};
const tools=textToolsUI({modal,toast,select:selectClip,active:target=>page===target||(page==='text-tools'&&target!=='uri'),navigate:(target,search='')=>{resetClipFilters();if(target==='ai'||target==='scripts'||target==='commands'){tools.setTab(target);target='text-tools';}page=target;selected='';query=search;matches=null;render();if(search)void runSearch().catch(toast);}});
let incomingBusy=false;
const checkExternal=()=>{if(!isWindowVisible()||incomingBusy||q<HTMLDialogElement>('dialog').open)return;incomingBusy=true;void(async()=>{const reply=await api.replyIntent();if(reply){resetClipFilters();page='replies';query='';matches=null;selected=reply.kind==='fill'?reply.snippet.id:'';render();if(reply.kind==='fill')await advanced.useSnippet(reply.snippet.id,true,reply);return;}await tools.external();})().catch(toast).finally(()=>incomingBusy=false);};
const dataPanel=dataUI({modal,toast,refresh,active:()=>page==='settings',rerender:async()=>{if(page==='settings')await renderSettings();}});
const webPanel=webUI({modal,toast,history:()=>state.clips,active:()=>page==='web'});
const syncPanel=syncUI({modal,toast,history:()=>state.clips,active:()=>page==='sync'});
const stackPanel=stackUI({modal,toast});
const efficiencyPanel=efficiencyUI({modal,toast,reuse:term=>{query=term;limit=100;setSearchFieldValue(q<HTMLInputElement>('search'),term);q('search').focus();void api.rememberSearch(term).then(()=>runSearch()).catch(toast);}});
const advanced=advancedUI({categories:()=>state.categories,modal,toast,refresh,select:selectClip});
const captureTools=captureToolsUI({select:selectClip,toast});
const tasksPanel=tasksUI({modal,toast,select:selectClip});
function manageCategories(){
 const order=state.categories.map(category=>category.id);
 modal(tr('管理分类'),`<p class="category-order-help">${tr('拖动分类调整顺序，也可以使用 Alt + 方向键。')}</p><div id="category-order-list" class="category-order-list"></div>`,async()=>{await api.reorderCategories(order);await refresh();toast(tr('分类顺序已保存'));},tr('完成'));
 const root=q('category-order-list');root.innerHTML=order.map(id=>{const category=state.categories.find(item=>item.id===id)!;return `<div class="category-order-row" data-category-order="${id}"><span class="category-order-grip" draggable="true" tabindex="0" aria-label="${esc(tr('拖拽排序')+' · '+category.name)}" title="${tr('拖拽排序')}">${ico('grip')}</span><span class="category-mark" style="--category-color:${category.color}">${categoryGlyph(category.icon)}</span><span class="category-order-name">${esc(category.name)}</span></div>`;}).join('');hydrateCategoryGlyphs(root);
 bindSortable(root,{itemSelector:'.category-order-row',handleSelector:'.category-order-grip',id:item=>item.dataset.categoryOrder!,commit:ids=>{order.splice(0,order.length,...ids);}});
}
function manageSidebar(){
  const draft=readSidebarLayout();
  const groupNames:Record<SidebarGroup,string>={clipboard:tr('剪贴板'),tools:tr('工具'),connections:tr('连接与分享')};
  const iconNames:Record<string,string>={shelf:'files',favorites:'star',stack:'stack',replies:'replies',history:'history','text-tools':'bot','capture-tools':'monitor',ai:'bot',scripts:'code',symbols:'smile',cheats:'book',sync:'devices',web:'monitor',uri:'link'};
  const draw=()=>{
    const root=q('sidebar-order-list');
    root.innerHTML=(Object.keys(sidebarGroups) as SidebarGroup[]).map(group=>`<section class="sidebar-manage-group" data-manage-group="${group}"><h3>${groupNames[group]}</h3>${draft.order[group].map(key=>`<div class="sidebar-manage-row" data-sidebar-key="${key}" data-sidebar-group="${group}"><button type="button" class="sidebar-manage-grip" draggable="true" aria-label="${esc(labels[key])} · ${tr('拖拽排序')}" aria-keyshortcuts="Alt+ArrowUp Alt+ArrowDown" title="${tr('拖拽排序')}">${ico('grip')}</button><span class="sidebar-manage-icon">${ico(iconNames[key])}</span><span class="sidebar-manage-label">${esc(labels[key])}</span><label class="sidebar-manage-visible"><input type="checkbox" data-sidebar-visible="${key}" ${draft.hidden.includes(key)?'':'checked'}><span>${tr('显示')}</span></label></div>`).join('')}</section>`).join('')+`<label class="sidebar-manage-categories"><input type="checkbox" id="sidebar-categories-visible" ${draft.categoriesVisible?'checked':''}><span>${tr('显示自定义分类')}</span></label>`;
    root.querySelectorAll<HTMLInputElement>('[data-sidebar-visible]').forEach(input=>input.onchange=()=>{
      draft.hidden=input.checked?draft.hidden.filter(key=>key!==input.dataset.sidebarVisible):[...draft.hidden,input.dataset.sidebarVisible!];
    });
    q<HTMLInputElement>('sidebar-categories-visible').onchange=event=>{
      draft.categoriesVisible=(event.currentTarget as HTMLInputElement).checked;
    };
    root.querySelectorAll<HTMLButtonElement>('.sidebar-manage-grip').forEach(grip=>{
      grip.onkeydown=event=>{
        if(!event.altKey||(event.key!=='ArrowUp'&&event.key!=='ArrowDown'))return;
        event.preventDefault();
        const row=grip.closest<HTMLElement>('.sidebar-manage-row')!;
        const group=row.dataset.sidebarGroup as SidebarGroup,key=row.dataset.sidebarKey!;
        const order=draft.order[group],index=order.indexOf(key),next=index+(event.key==='ArrowUp'?-1:1);
        if(next<0||next>=order.length)return;
        [order[index],order[next]]=[order[next],order[index]];
        draw();
        root.querySelector<HTMLButtonElement>(`[data-sidebar-key="${key}"] .sidebar-manage-grip`)?.focus();
      };
    });
    root.querySelectorAll<HTMLElement>('.sidebar-manage-group').forEach(groupNode=>{const group=groupNode.dataset.manageGroup as SidebarGroup;bindSortable(groupNode,{itemSelector:'.sidebar-manage-row',handleSelector:'.sidebar-manage-grip',id:item=>item.dataset.sidebarKey!,commit:ids=>{draft.order[group].splice(0,draft.order[group].length,...ids);}});});
  };
  modal(tr('管理侧边栏'),'<div id="sidebar-order-list" class="sidebar-order-list"></div>',async()=>{
    saveSidebarLayout(draft);
    toast(tr('侧边栏已更新'));
  },tr('保存'));
  draw();
}
function organizeManualCategories(ids:string[]){const categories=state.categories.filter(category=>category.manual);if(!categories.length){toast(tr('请先新建一个手动分类'));return;}const selectedItems=ids.map(id=>clipsByID.get(id)).filter((item):item is Clip=>!!item);modal(tr('整理到手动分类'),tr`<p class="field-help">${tr('勾选后会将所选记录归入分类；取消勾选会移出该分类。')}</p><div class="manual-category-list">${categories.map(category=>{const checked=selectedItems.length>0&&selectedItems.every(item=>item.manualCategories?.includes(category.id));return `<label><input type="checkbox" data-manual-category="${category.id}" ${checked?'checked':''}><span class="category-mark" style="--category-color:${category.color}">${categoryGlyph(category.icon)}</span><span>${esc(category.name)}</span></label>`;}).join('')}</div>`,async()=>{for(const category of categories)await api.setManualCategory(ids,category.id,document.querySelector<HTMLInputElement>(`[data-manual-category="${category.id}"]`)!.checked);await refresh();toast(tr('分类已更新'));},tr('保存分类'));}
function orderedCategories(){return state.categories.filter(c=>!c.parentId).flatMap(c=>[c,...state.categories.filter(child=>child.parentId===c.id)]);}
let categoryCounts:Record<string,number>={},categoryCountRequest=0;
async function refreshCategoryCounts(){const request=++categoryCountRequest;if(!state.categories.length){categoryCounts={};return;}try{const counts=await api.categoryCounts();if(request!==categoryCountRequest||!counts)return;categoryCounts=counts;for(const category of state.categories){const button=document.querySelector<HTMLElement>(`#categories [data-category="${category.id}"]`),count=counts[category.id];if(button&&Number.isInteger(count)&&count>=0){button.querySelector('small')!.textContent=formatNumber(count);button.title=category.name+' · '+formatNumber(count);}}}catch(error){if(request===categoryCountRequest)toast(error);}}
function categoryNavigation(){const node=q('categories');if(!node)return;keyedMarkup(node,[{key:':heading',html:`<div class="category-heading"><span>${tr('自定义分类')}</span><div class="category-heading-actions">${state.categories.length?ib('manage-categories',tr('管理分类'),'more'):''}${ib('add-category',tr('新建分类'),'plus')}</div></div>`},...orderedCategories().map(c=>({key:c.id,html:`<button class="nav-item category-nav-item ${c.parentId?'sub-category':''} ${page==='category:'+c.id?'selected':''}" data-category="${c.id}" aria-label="${esc(c.name)}" title="${esc(c.name)}" ${page==='category:'+c.id?'aria-current="page"':''}><span class="category-mark" style="--category-color:${c.color}">${categoryGlyph(c.icon)}</span><span class="category-name">${esc(c.name)}</span><small>${categoryCounts[c.id]===undefined?'':formatNumber(categoryCounts[c.id])}</small></button>`}))]);hydrateCategoryGlyphs(node);on('add-category',()=>advanced.category());on('manage-categories',manageCategories);node.querySelectorAll<HTMLElement>('[data-category]').forEach(b=>b.onclick=()=>{resetClipFilters();page='category:'+b.dataset.category;selected='';query='';checked.clear();matches=null;render();void runSearch().catch(toast);});void refreshCategoryCounts();}
function headingActions(){
 if(page==='replies')return button('new-reply',tr('新建回复'),'plus','primary')+ib('batch-mode',batchMode?tr('退出批量选择'):tr('批量选择'),batchMode?'close':'check',batchMode);
 if(page==='stack')return ib('stack-rules',tr('堆栈规则'),'settings')+ib('stack-batch',tr('批量入栈'),'plus')+ib('stack-reverse',tr('反转顺序'),'undo')+button('stack-running',state.stack.running?tr('停止自动入栈'):tr('开始自动入栈'),state.stack.running?'pause':'play')+button('paste-next',tr('粘贴下一项'),'enter','primary');
 const menuAction=(id:string,label:string,glyph:string)=>`<button id="${id}" type="button" role="menuitem">${ico(glyph)}<span>${label}</span></button>`;
 const extra=page==='shelf'?menuAction('open-shelf',tr('浮动窗口'),'monitor'):categoryId()?menuAction('edit-category',tr('编辑分类'),'edit')+menuAction('remove-category',tr('删除分类'),'trash'):'';
 const menu=`<div class="collection-action-menu">${ib('collection-more-toggle',tr('更多操作'),'more')}<div id="collection-more-menu" class="collection-more-menu" role="menu" aria-label="${tr('更多操作')}" aria-hidden="true" hidden>${menuAction('open-quick-panel',tr('快捷面板'),'clipboard')}${extra}${page==='history'?`<div role="separator"></div>${menuAction('clear-history-main',tr('清空历史'),'trash')}`:''}</div></div>`;
 return (page==='shelf'?button('add-files',tr('添加文件'),'plus','primary'):'')+ib('batch-mode',batchMode?tr('退出批量选择'):tr('批量选择'),batchMode?'close':'check',batchMode)+ib('undo-delete',tr('撤销删除'),'undo')+menu;
}
function bindAdvanced(){
  on('clear-history-main',()=>confirm(tr('清空历史？'),tr(HISTORY_CLEAR_DETAIL),async()=>{await api.clear();selected='';checked.clear();matches=null;await refresh();},true));
  on('stack-rules',()=>stackPanel.rules());on('stack-batch',()=>stackPanel.batch());on('stack-reverse',()=>api.reverseStack());on('stack-running',()=>api.setStackRunning(!state.stack.running));
  on('open-quick-panel',()=>api.showQuick());on('open-shelf',()=>api.showShelf());on('add-files',()=>api.addFiles());on('batch-mode',()=>{batchMode=!batchMode;checked.clear();renderCollection();});
  on('edit-category',()=>advanced.category(state.categories.find(c=>c.id===categoryId())));on('remove-category',()=>confirm(tr('删除分类？'),tr('只删除分类规则，历史内容保留。'),async()=>{await api.removeCategory(categoryId()!);page='history';matches=null;await refresh();render();}));
  const drop=q('shelf-drop');if(drop){const area=q('content');area.ondragover=e=>{if(acceptsDrop(e.dataTransfer)){e.preventDefault();e.dataTransfer!.dropEffect='copy';drop.classList.add('dragging');}};area.ondragleave=e=>{if(!area.contains(e.relatedTarget as Node))drop.classList.remove('dragging');};area.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');let pending:Promise<boolean>|null=null;try{pending=e.dataTransfer&&importDroppedImage(e.dataTransfer,api);}catch(error){toast(error);return;}if(pending)void pending.then(imported=>{if(imported)toast(tr('已添加到拖拽容器'));}).catch(toast);};}else{q('content').ondragover=null;q('content').ondrop=null;q('content').ondragleave=null;}
}
function filteredReplies(){return state.snippets.filter(s=>(s.title+'\n'+s.text).toLowerCase().includes(query.toLowerCase()));}
function toggleReplySelection(id:string){if(checked.has(id))checked.delete(id);else{if(checked.size>=500){toast(tr('已选择前 500 条结果'));return;}checked.add(id);}renderCollection();}
function renderBatch(){const bar=q('batch-bar');if(!bar)return;const hasManualCategory=state.categories.some(category=>category.manual);if(!batchMode){revealToolbar(bar,false);return;}const recordActions=page==='replies'?'':ib('batch-favorite',tr('批量收藏'),'star')+ib('batch-enqueue',tr('批量加入堆栈'),'stack')+ib('batch-tag',tr('批量添加标签'),'edit')+(hasManualCategory?ib('batch-category',tr('整理到分类'),'files'):'')+ib('batch-shelf',page==='shelf'?tr('批量移出容器'):tr('批量加入拖拽容器'),'files');patchMarkup(bar,`<label class="batch-selection"><input id="batch-all" type="checkbox" aria-label="${tr('全选当前筛选结果')}"><strong class="batch-count">${tr`已选择 ${formatNumber(checked.size)} 项`}</strong></label><span class="spacer"></span><div class="batch-actions">${recordActions}${ib('batch-delete',tr('批量删除'),'trash')}</div>`);bar.querySelectorAll<HTMLButtonElement>('.batch-actions>button').forEach(button=>setActionDisabled(button,!checked.size));revealToolbar(bar,true);
  const all=q<HTMLInputElement>('batch-all'),candidates=[...new Set((page==='replies'?filteredReplies():visible).map(c=>c.id))],available=candidates.slice(0,500),selectedCount=candidates.filter(id=>checked.has(id)).length;all.checked=!!candidates.length&&selectedCount===candidates.length;all.indeterminate=selectedCount>0&&!all.checked;all.disabled=!available.length;all.title=all.checked?tr('清空选择'):tr('全选当前筛选结果');all.onchange=()=>{if(available.every(id=>checked.has(id)))checked.clear();else checked=new Set(available);renderCollection();if(candidates.length>500&&checked.size)toast(tr('已选择前 500 条结果'));};
  if(page==='replies'){on('batch-delete',()=>{const ids=[...checked];if(!ids.length)return;confirm(tr`删除 ${formatNumber(ids.length)} 条快捷回复？`,tr('删除后不可撤销。'),async()=>{await api.removeSnippets(ids);checked.clear();await refresh();toast(tr('批量操作完成'));});});return;}
  for(const action of ['favorite','enqueue','shelf','delete','tag'] as const)on('batch-'+action,async()=>{const ids=[...checked];if(!ids.length){toast(tr('请先选择记录'));return;}const perform=async(tags:string[]=[])=>{await api.batch(ids,action==='shelf'&&page==='shelf'?'unshelf':action,tags);checked.clear();await refresh();toast(action==='delete'?tr`已删除 ${formatNumber(ids.length)} 条记录`:tr('批量操作完成'),action==='delete');};if(action==='delete')modal(tr`删除 ${formatNumber(ids.length)} 条记录？`,tr('<p>仅删除历史内容，不删除源文件。完成后可撤销。</p>'),()=>perform(),tr('删除'));else if(action==='tag')modal(tr('批量添加标签'),tr('<label class="field">标签<input id="batch-tags" placeholder="逗号分隔，例如 工作, 资料"></label>'),()=>perform(q<HTMLInputElement>('batch-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean)));else await perform();});on('batch-category',()=>organizeManualCategories([...checked]));
}
function toast(text:unknown,undo=false){showFeedback(q('toast'),()=>{q('toast').innerHTML=`<span tabindex="0">${esc(String(text instanceof Error?text.message:text).replace(/^Error invoking remote method '[^']+': Error: /,''))}</span>${undo?tr('<button id="undo-toast">撤销</button>'):''}`;});enableFeedbackScroll(q('toast').firstElementChild as HTMLElement);const arm=()=>{clearTimeout(toastTimer);toastTimer=setTimeout(()=>{if(!q('toast').matches(':hover,:focus-within'))dismissFeedback(q('toast'),()=>q('toast').hidden=true);},6500);};q('toast').onmouseenter=()=>clearTimeout(toastTimer);q('toast').onmouseleave=arm;q('toast').querySelectorAll<HTMLElement>('[tabindex],button').forEach(el=>{el.onfocus=()=>clearTimeout(toastTimer);el.onblur=arm;});arm();if(undo)on('undo-toast',async()=>{await api.undo();await refresh();toast(tr('已撤销删除'));});}
function on(id:string,fn:()=>unknown){actions.bind(q<HTMLButtonElement>(id),fn,toast,['copy','paste','plain'].includes(id)?'clipboard':id);}
function shell(){
  const nav=(p:string,icon:string,count=false)=>`<button data-page="${p}" class="nav-item" aria-label="${labels[p]}">${ico(icon)}<span>${labels[p]}</span>${count?`<small id="count-${p}"></small>`:''}</button>`;
  const group=(key:SidebarGroup,name:string,items:string,extra='')=>`<section class="sidebar-group" data-sidebar-group="${key}"><h2 class="sidebar-group-caption">${name}</h2><nav class="${extra}" aria-label="${name}">${items}</nav></section>`;
  q('app').innerHTML=`<header class="titlebar"><div class="brand"><span class="brand-icon"><img src="clip-mark.png" alt=""></span><strong>Clip</strong><button id="pause-nav" class="quiet recording-status" aria-label="${tr('记录开关')}"></button></div><div class="title-tools">${ib('sidebar-toggle',tr('收起侧边栏'),'panel')}<span class="spacer"></span></div>${windowControls()}</header><aside class="sidebar"><div class="sidebar-scroll">${group('clipboard',tr('剪贴板'),nav('history','history',true)+nav('stack','stack',true)+nav('shelf','container',true)+nav('replies','replies',true))}<div id="categories" role="navigation" aria-label="${tr('自定义分类')}"></div>${group('tools',tr('工具'),nav('text-tools','bot')+nav('capture-tools','monitor')+nav('symbols','smile')+nav('cheats','book'))}${group('connections',tr('连接与分享'),nav('sync','devices')+nav('web','monitor')+nav('uri','link'),'nav-secondary')}</div><div class="sidebar-bottom"><button id="task-center" type="button"></button>${nav('settings','settings')}</div></aside><main id="main"><div id="content"></div></main>`;
  applySidebarLayout();tasksPanel.mount();api.onOpenRecording?.(()=>{captureTools.setTab('recording');page='capture-tools';render();});
  setupChrome();document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>{b.title=labels[b.dataset.page!];b.onclick=()=>{(document.activeElement as HTMLElement)?.blur();closeControls();resetClipFilters();page=b.dataset.page!;selected='';query='';matches=null;limit=100;checked.clear();batchMode=false;render();};});
  const collapse=(value:boolean)=>{document.body.classList.toggle('sidebar-collapsed',value);const toggle=q('sidebar-toggle');toggle.setAttribute('aria-expanded',String(!value));toggle.title=value?tr('展开侧边栏'):tr('收起侧边栏');toggle.setAttribute('aria-label',toggle.title);};collapse(localStorage.getItem('sidebar-collapsed')==='true');on('sidebar-toggle',()=>{const value=!document.body.classList.contains('sidebar-collapsed');collapse(value);localStorage.setItem('sidebar-collapsed',String(value));});
  on('pause-nav',()=>api.settings({...state.settings,paused:!state.settings.paused}));
}
function applyServiceStatus(){const services=state.services;for(const name of ['sync','web'] as const){const button=document.querySelector<HTMLButtonElement>(`.nav-secondary [data-page="${name}"]`);if(!button)continue;const value=name==='web'?(services?.web?'sharing':'off'):(services?.sync||'off'),label=value==='sharing'?tr('共享中'):value==='busy'?tr('同步中'):value==='error'?tr('需检查'):value==='ready'?tr('已开启'):'';button.dataset.service=value;let badge=button.querySelector<HTMLElement>('.nav-service-status');if(label){if(!badge){badge=document.createElement('small');badge.className='nav-service-status';button.append(badge);}badge.textContent=label;}else badge?.remove();button.title=labels[name]+(label?' · '+label:'');}}
function applyState(){document.documentElement.dataset.theme=state.dark?'dark':'light';for(const p of ['history','stack','shelf','replies'])q('count-'+p).textContent=formatNumber(p==='history'?collectionItems(state.clips,clipsByID,'history',[],state.shelf,'all',null).items.length:p==='favorites'?state.clips.filter(i=>i.favorite).length:p==='stack'?state.queue.length:p==='shelf'?state.shelf.length:state.snippets.length);const pause=q('pause-nav'),paused=state.settings.paused;pause.dataset.paused=String(paused);setMarkup(pause,`<span class="recording-label">${paused?tr('已暂停'):tr('自动记录')}</span><i class="recording-action" aria-hidden="true">${ico(paused?'play':'pause')}</i>`);pause.title=(paused?tr('恢复记录'):tr('暂停记录'))+' · '+shortcut(state.settings.shortcut);pause.setAttribute('aria-label',paused?tr('恢复记录'):tr('暂停记录'));pause.setAttribute('aria-pressed',String(!paused));applyServiceStatus();document.querySelectorAll<HTMLElement>('[data-page]').forEach(b=>{const active=b.dataset.page===page;b.classList.toggle('selected',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function settingsStorageSummary(){return tr`${formatNumber(state.clips.length)} 条记录`+' · '+bytes(state.bytes);}
function storageUsage(){const maximum=state.settings.maxHistoryMiB*1024*1024,ratio=maximum?state.bytes/maximum:0,percent=Math.round(ratio*100),level=ratio>=1?'full':ratio>=.9?'urgent':ratio>=.8?'warning':'normal',hint=level==='full'?tr('容量已达到上限。请清理历史或提高上限后继续记录。'):level==='urgent'?tr('容量即将用尽。建议现在清理历史或提高上限。'):level==='warning'?tr('空间使用较高。可提前调整上限或清理不需要的历史。'):tr('空间充足，可根据需要调整容量上限。');return {maximum,ratio,percent,level,hint};}
function storageBreakdownMarkup(){const byKind=new Map<Kind,number>(),bySource=new Map<string,number>();for(const clip of state.clips){const amount=Math.max(0,clip.bytes||0);byKind.set(clip.kind,(byKind.get(clip.kind)||0)+amount);bySource.set(clip.source,(bySource.get(clip.source)||0)+amount);}const kinds=[...byKind.entries()].filter(([,amount])=>amount>0).sort((a,b)=>b[1]-a[1]),sources=[...bySource.entries()].filter(([,amount])=>amount>0).sort((a,b)=>b[1]-a[1]).slice(0,4),total=kinds.reduce((sum,[,amount])=>sum+amount,0);if(!total)return '';const rows=(items:readonly [string,number][],name:(key:string)=>string)=>items.map(([key,amount])=>`<div class="storage-breakdown-row"><span title="${esc(name(key))}">${esc(name(key))}</span><b>${bytes(amount)}</b></div>`).join('');return `<section class="storage-distribution" aria-label="${tr('记录内容分布')}"><div class="storage-distribution-heading"><strong>${tr('记录内容分布')}</strong><span>${tr('按记录内容估算')}</span></div><div class="storage-breakdown-grid"><div><small>${tr('内容类型')}</small>${rows(kinds,key=>labels[key]||key)}</div><div><small>${tr('来源应用')}</small>${sources.length?rows(sources,key=>key.replace(/\\.exe$/i,'')):`<p>${tr('暂无来源数据')}</p>`}</div></div></section>`;}
function updateStorageSummary(){
  const summary=q('settings-storage-summary');
  if(summary)summary.textContent=settingsStorageSummary();
  const meter=q('storage-meter');
  if(!meter)return;
  const usage=storageUsage();
  meter.dataset.level=usage.level;
  const amount=meter.querySelector<HTMLElement>('#storage-bytes');
  const percent=meter.querySelector<HTMLElement>('#storage-percent');
  const bar=meter.querySelector<HTMLElement>('#storage-progress');
  const notice=meter.querySelector<HTMLElement>('#storage-notice');
  if(!amount||!percent||!bar||!notice)return;
  amount.textContent=bytes(state.bytes)+' / '+bytes(usage.maximum);
  percent.textContent=usage.percent+'%';
  bar.style.width=Math.min(100,usage.ratio*100)+'%';
  bar.parentElement?.setAttribute('aria-valuenow',String(Math.min(100,usage.percent)));
  notice.textContent=usage.hint;
  const breakdown=q('storage-distribution');
  if(breakdown)breakdown.innerHTML=storageBreakdownMarkup();
}
async function refresh(){clearTimeout(refreshScheduled);refreshScheduled=undefined;refreshPending=false;const token=++refreshToken,revision=searchRevision;const next=await api.state();if(token!==refreshToken)return;const remaining=new Set(next.clips.map(item=>item.id)),animate=recordRemoval(q('results'),'.clip-row',row=>!remaining.has(row.dataset.id!));state=next;clipsByID=new Map(state.clips.map(c=>[c.id,c]));checked=new Set([...checked].filter(id=>page==='replies'?state.snippets.some(item=>item.id===id):clipsByID.has(id)));applyState();categoryNavigation();updateStorageSummary();if(categoryId()&&q('content').querySelector('h1'))q('content').querySelector('h1')!.textContent=state.categories.find(c=>c.id===categoryId())?.name||tr('全部记录');if(!['settings','text-tools','capture-tools','ai','scripts','uri','sync','web','symbols','cheats'].includes(page)){renderCollection();if(revision===searchRevision&&(query||categoryId()))await runSearch();}animate();if(page==='settings')void dataPanel.updateStatus().catch(toast);if(page==='sync')void syncPanel.update().catch(toast);if(page==='web')void webPanel.update().catch(toast);checkExternal();}
let referenceLoad:Promise<typeof import('./reference-pages.js')>|undefined,disposeReference:(()=>void)|undefined,referenceRevision=0;
function renderReference(kind:'symbols'|'cheats'){
 const root=q('content'),revision=++referenceRevision;root.innerHTML='<div class="reference-loading" aria-hidden="true"><i></i><i></i><i></i></div>';
 referenceLoad??=import(new URL('./reference-pages.js',location.href).href) as Promise<typeof import('./reference-pages.js')>;
 void referenceLoad.then(module=>{if(revision===referenceRevision&&page===kind&&q('content')===root)disposeReference=module.mountReference(root,kind,toast);}).catch(error=>{referenceLoad=undefined;if(page===kind)toast(error);});
}
function render(){if(page!=='capture-tools')captureTools.leave();suspendedPreview=undefined;releaseDetail();searchRevision++;referenceRevision++;disposeReference?.();disposeReference=undefined;disposeUpdates?.();disposeUpdates=undefined;disposeVersions?.();disposeVersions=undefined;applyState();categoryNavigation();if(page==='settings')void renderSettings().catch(toast);else if(page==='capture-tools')captureTools.render();else if(page==='text-tools'||page==='ai'||page==='scripts'||page==='uri')void tools.render(page).catch(toast);else if(page==='sync')void syncPanel.render().catch(toast);else if(page==='web')void webPanel.render().catch(toast);else if(page==='symbols'||page==='cheats')renderReference(page);else{
  q('content').innerHTML=tr`<section class="collection"><div class="page-heading"><div><h1>${esc(labels[page]||state.categories.find(c=>c.id===categoryId())?.name||tr('全部记录'))}</h1></div><div class="heading-actions">${headingActions()}</div></div><div class="collection-toolbar">${searchField('search',tr('搜索剪贴板'),page==='replies'?tr('搜索快捷回复'):tr('搜索内容、标签或来源应用'),ib('search-history',tr('搜索历史'),'history'))}</div><div class="filterbar"><div id="filters" class="tabs"></div></div><div id="source-filters" class="source-filterbar tabs" role="tablist" aria-label="来源应用"></div><div id="filter-chips" class="filter-chips" aria-label="当前筛选条件" hidden></div><div id="batch-bar" class="batch-bar" hidden></div>${page==='shelf'?tr('<div id="shelf-drop" class="shelf-drop">拖入文件或图片；拖动记录即可放到其他应用</div>'):''}<div class="workspace"><div id="results" class="results" tabindex="0" aria-label="剪贴板记录"></div><section id="detail" class="detail" aria-label="内容预览"></section></div></section>`;
  collectionLayout(q('content'));if(page==='replies'){q('content').querySelector('.collection')!.classList.add('replies-collection');q('detail')?.remove();const controls=document.createElement('div');controls.id='reply-layout-controls';controls.className='reply-layout-controls tabs';controls.setAttribute('role','group');controls.setAttribute('aria-label',tr('快捷回复布局'));controls.innerHTML=(['list','cards'] as const).map(layout=>'<button type="button" data-reply-layout="'+layout+'" aria-pressed="'+(layout===replyLayout)+'" class="'+(layout===replyLayout?'selected':'')+'">'+ico(layout==='list'?'list':'grid')+'<span>'+tr(layout==='list'?'列表':'卡片')+'</span></button>').join('');q('content').querySelector('.collection-toolbar')!.append(controls);controls.onclick=event=>{const button=event.target instanceof Element?event.target.closest<HTMLButtonElement>('[data-reply-layout]'):null;if(!button||!controls.contains(button))return;replyLayout=button.dataset.replyLayout==='list'?'list':'cards';localStorage.setItem('reply-layout',replyLayout);controls.querySelectorAll<HTMLButtonElement>('button').forEach(node=>{const active=node.dataset.replyLayout===replyLayout;node.classList.toggle('selected',active);node.setAttribute('aria-pressed',String(active));});renderCollection();};}const input=q<HTMLInputElement>('search');input.value=query;input.dispatchEvent(new Event('input'));let composing=false;const changed=()=>{searchRevision++;query=input.value.trim();limit=100;clearTimeout(searchTimer);if(!composing)searchTimer=setTimeout(()=>void runSearch().catch(toast),120);};input.oninput=changed;input.addEventListener('compositionstart',()=>{composing=true;clearTimeout(searchTimer);});input.addEventListener('compositionend',()=>{composing=false;changed();});input.onblur=()=>{if(!composing&&input.value.trim())void api.rememberSearch(input.value).catch(toast);};on('search-history',()=>efficiencyPanel.history());
  bindHeadingMenu(q('content'));on('undo-delete',async()=>{await api.undo();await refresh();toast(tr('已撤销删除'));});on('new-reply',()=>editReply());on('paste-next',()=>api.next());bindAdvanced();renderCollection();
}}
async function runSearch(){
 if(!isWindowVisible()){scheduleRefresh();return;}
 const revision=++searchRevision,requested=query,category=categoryId();
 try{
  const searching=(query||category)&&page!=='replies';
  const found=!searching?null:new Set(await api.search(query,category));
  if(revision!==searchRevision||requested!==query||category!==categoryId())return;matches=found;renderCollection();
 }catch(error){if(revision===searchRevision&&requested===query&&category===categoryId())throw error;}
}
function highlight(text:string){if(!query)return esc(text);const first=query.split(/\s+/)[0],at=text.toLocaleLowerCase().indexOf(first.toLocaleLowerCase());return at<0?esc(text):esc(text.slice(0,at))+'<mark>'+esc(text.slice(at,at+first.length))+'</mark>'+esc(text.slice(at+first.length));}
function row(c:Clip,index:number){
 const active=selected===c.id&&(page!=='stack'||selectedQueueIndex===visibleQueueIndices[index]);
 const contentRecord=c.kind!=='files';
 const thumbnail=c.thumbnail&&/^data:image\/(?:png|jpeg|webp|gif);base64,/.test(c.thumbnail)?`<img class="record-thumbnail" src="${esc(c.thumbnail)}" alt="" loading="lazy" decoding="async">`:'';
 const image=contentRecord&&c.kind==='image';
 const body=image?(thumbnail||`<span class="record-image-placeholder">${ico('image')}</span>`):highlight(contentRecord?(c.preview.trim()?c.preview:c.title):c.title);
 const summary=contentRecord||c.kind==='image'||c.preview.trim()===c.title.trim()?'':c.preview.replaceAll('\n',' ');
 const flags=`<span class="row-flags">${c.pinned?'<span class="record-flag record-pinned" role="img" aria-label="'+tr('已置顶')+'" title="'+tr('已置顶')+'">'+ico('pin')+'</span>':''}${c.favorite?'<span class="record-flag record-favorite" role="img" aria-label="'+tr('已收藏')+'" title="'+tr('已收藏')+'">'+ico('star')+'</span>':''}</span>`;
 return `<button class="clip-row ${contentRecord?'content-record ':''}${active?'selected':''}" data-id="${c.id}" data-kind="${c.kind}" data-pinned="${c.pinned}" data-favorite="${c.favorite}" data-queue-index="${page==='stack'?visibleQueueIndices[index]:-1}" aria-label="${esc(c.title)}" aria-pressed="${active}"><span class="row-content"><span class="row-heading">${contentRecord?'':`<span class="row-kind">${page==='stack'?'<span class="queue-index">'+(visibleQueueIndices[index]+1)+'</span>':ico(c.kind)}</span>`}<span class="row-title ${contentRecord?(image?'record-visual':'record-text'):''}">${body}</span>${contentRecord?'':flags}${page==='favorites'?'<span class="row-sort-grip" title="'+tr('拖拽排序')+'">'+ico('grip')+'</span>':''}</span>${summary?'<span class="row-preview">'+highlight(summary)+'</span>':''}<span class="row-meta"><span class="row-application">${appIdentity(c.source)}<span>${esc(c.source.replace(/\.exe$/i,''))}</span></span>${contentRecord?flags:''}<span class="row-time">${time(c.updatedAt)}</span></span>${c.tags.length?'<span class="row-tags">'+c.tags.slice(0,2).map(tag=>'<span class="tag">'+esc(tag)+'</span>').join('')+'</span>':''}</span></button>`;
}
function sourceEntries(clips:readonly Clip[]){const apps=new Map<string,{name:string;count:number}>();for(const clip of clips){const key=sourceKey(clip.source),entry=apps.get(key);if(entry)entry.count++;else apps.set(key,{name:clip.source,count:1});}return [...apps].sort((a,b)=>b[1].count-a[1].count||a[0].localeCompare(b[0])).map(([key,value])=>({key,...value}));}
function tagEntries(){const tags=new Map<string,{name:string;count:number}>();for(const clip of state.clips)for(const tag of clip.tags){const key=tag.trim().toLocaleLowerCase(),entry=tags.get(key);if(!key)continue;if(entry)entry.count++;else tags.set(key,{name:tag,count:1});}return [...tags].sort((a,b)=>b[1].count-a[1].count||a[1].name.localeCompare(b[1].name)).slice(0,12).map(([key,value])=>({key,...value}));}
function extensionEntries(){const entries=new Map<string,number>();for(const clip of state.clips){const extension=clipExtension(clip);if(extension)entries.set(extension,(entries.get(extension)||0)+1);}return [...entries].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,8).map(([extension,count])=>({extension,count}));}
function filterButton(label:string,value:string,selected:boolean,attribute:string,count?:number){return `<button type="button" class="advanced-filter-option ${selected?'selected':''}" ${attribute}="${esc(value)}" aria-pressed="${selected}">${esc(label)}${count?`<small>${formatNumber(count)}</small>`:''}</button>`;}
function sourceFilterButton(app:{key:string;name:string;count:number}){const selected=clipFilters.sources.includes(app.key),name=app.name.replace(/\.exe$/i,'');return `<button type="button" class="advanced-filter-option advanced-source-option ${selected?'selected':''}" data-filter-source="${esc(app.key)}" data-source-name="${esc(name.toLocaleLowerCase())}" aria-pressed="${selected}">${appIdentity(app.name)}<span>${esc(name)}</span><small>${formatNumber(app.count)}</small></button>`;}
function filterSummary(){const chips:{group:keyof ClipFilters;label:string}[]=[];if(clipFilters.kinds.length)chips.push({group:'kinds',label:clipFilters.kinds.map(kind=>labels[kind]).join('、')});if(clipFilters.sources.length){const names=new Map(sourceEntries(state.clips).map(item=>[item.key,item.name]));chips.push({group:'sources',label:clipFilters.sources.map(source=>names.get(source)||source.replace(/\.exe$/i,'')).join('、')});}if(clipFilters.period)chips.push({group:'period',label:{today:tr('今天'),yesterday:tr('昨天'),week:tr('本周'),month:tr('本月'),custom:tr('自定义日期')}[clipFilters.period]});if(clipFilters.favorite)chips.push({group:'favorite',label:tr('已收藏')});if(clipFilters.pinned)chips.push({group:'pinned',label:tr('已置顶')});if(clipFilters.tags.length)chips.push({group:'tags',label:tr('标签：')+clipFilters.tags.join('、')});if(clipFilters.extensions.length)chips.push({group:'extensions',label:clipFilters.extensions.map(extension=>'.'+extension).join('、')});if(clipFilters.size)chips.push({group:'size',label:{small:tr('小于 1 MB'),medium:tr('1–10 MB'),large:tr('大于 10 MB')}[clipFilters.size]});return chips;}
function advancedFilterMarkup(){const apps=sourceEntries(collectionItems(state.clips,clipsByID,page,state.queue,state.shelf,'all',matches).items),tags=tagEntries(),extensions=extensionEntries(),active=filterSummary().length;
 const periods:[ClipFilters['period'],string][]=[[undefined,tr('不限')],['today',tr('今天')],['yesterday',tr('昨天')],['week',tr('本周')],['month',tr('本月')],['custom',tr('自定义')]];
 return `<div class="advanced-filter"><button id="advanced-filter-toggle" type="button" class="icon-button quiet ${active?'active':''}" aria-expanded="${filterPopoverOpen}" aria-controls="advanced-filter-popover" title="${tr('高级筛选')}" aria-label="${tr('高级筛选')}">${ico('filter')}${active?`<b>${active}</b>`:''}</button><section id="advanced-filter-popover" class="advanced-filter-popover" ${filterPopoverOpen?'':'hidden'} aria-label="${tr('高级筛选')}"><header><strong>${tr('筛选记录')}</strong><button id="advanced-filter-reset" type="button" class="quiet small" ${active?'':'disabled'}>${tr('清除条件')}</button></header><div class="advanced-filter-group"><span>${tr('类型')}</span><div>${(['text','image','files','link','code'] as Kind[]).map(kind=>filterButton(labels[kind],kind,clipFilters.kinds.includes(kind),'data-filter-kind')).join('')}</div></div><div class="advanced-filter-group"><span>${tr('日期')}</span><div>${periods.map(([period,label])=>filterButton(label,period||'all',clipFilters.period===period,'data-filter-period')).join('')}</div>${clipFilters.period==='custom'?`<div class="advanced-filter-dates">${dateField({filter:'from',value:clipFilters.from,label:tr('开始日期')})}<span>–</span>${dateField({filter:'to',value:clipFilters.to,label:tr('结束日期')})}</div>`:''}</div><div class="advanced-filter-group"><span>${tr('状态')}</span><div>${filterButton(tr('已收藏'),'favorite',!!clipFilters.favorite,'data-filter-state')}${filterButton(tr('已置顶'),'pinned',!!clipFilters.pinned,'data-filter-state')}</div></div>${apps.length?`<div class="advanced-filter-group"><span>${tr('来源应用')}</span><div class="advanced-source-picker"><input id="advanced-source-search" type="search" maxlength="120" placeholder="${tr('搜索应用')}" aria-label="${tr('搜索应用')}"><div class="advanced-source-list">${apps.map(sourceFilterButton).join('')}</div></div></div>`:''}${tags.length?`<div class="advanced-filter-group"><span>${tr('标签')}</span><div>${tags.map(tag=>filterButton(tag.name,tag.key,clipFilters.tags.includes(tag.key),'data-filter-tag',tag.count)).join('')}</div></div>`:''}${extensions.length?`<div class="advanced-filter-group"><span>${tr('文件类型')}</span><div>${extensions.map(entry=>filterButton('.'+entry.extension,entry.extension,clipFilters.extensions.includes(entry.extension),'data-filter-extension',entry.count)).join('')}</div></div>`:''}<div class="advanced-filter-group"><span>${tr('大小')}</span><div>${filterButton(tr('小于 1 MB'),'small',clipFilters.size==='small','data-filter-size')}${filterButton(tr('1–10 MB'),'medium',clipFilters.size==='medium','data-filter-size')}${filterButton(tr('大于 10 MB'),'large',clipFilters.size==='large','data-filter-size')}</div></div></section></div>`;
}
function renderFilterChips(){
 const root=q('filter-chips'),chips=filterSummary().filter(chip=>chip.group!=='favorite'&&chip.group!=='pinned');root.hidden=page==='replies';
 patchMarkup(root,(['favorite','pinned'] as const).map(status=>{const active=!!clipFilters[status],label=status==='favorite'?tr('已收藏'):tr('已置顶');return '<button type="button" class="filter-chip filter-status '+(active?'active':'')+'" data-toggle-filter="'+status+'" aria-pressed="'+active+'">'+ico(status==='favorite'?'star':'pin')+'<span>'+label+'</span></button>';}).join('')+chips.map(chip=>'<button type="button" class="filter-chip" data-remove-filter="'+chip.group+'" title="'+tr('移除筛选条件')+'：'+esc(chip.label)+'"><span>'+esc(chip.label)+'</span>'+ico('close')+'</button>').join(''));
 root.onclick=event=>{const button=event.target instanceof Element?event.target.closest<HTMLButtonElement>('button'):null;if(!button||!root.contains(button))return;const status=button.dataset.toggleFilter as 'favorite'|'pinned'|undefined;if(status){updateClipFilters({[status]:!clipFilters[status]});return;}const group=button.dataset.removeFilter as keyof ClipFilters;if(group)updateClipFilters({[group]:Array.isArray(clipFilters[group])?[]:undefined} as Partial<ClipFilters>);};
}
function bindAdvancedFilters(root:HTMLElement){
 if(filterPopoverOpen)setFilterPopover(true);
 on('advanced-filter-toggle',()=>setFilterPopover(!filterPopoverOpen));on('advanced-filter-reset',()=>{clipFilters=emptyClipFilters();filterPopoverOpen=true;limit=100;selected='';releaseDetail();renderCollection();});
 root.querySelectorAll<HTMLButtonElement>('[data-filter-kind]').forEach(button=>button.onclick=()=>{const kind=button.dataset.filterKind as Kind;const kinds=clipFilters.kinds.includes(kind)?clipFilters.kinds.filter(item=>item!==kind):[...clipFilters.kinds,kind];updateClipFilters({kinds});});
 root.querySelectorAll<HTMLButtonElement>('[data-filter-period]').forEach(button=>button.onclick=()=>{const period=button.dataset.filterPeriod==='all'?undefined:button.dataset.filterPeriod as ClipFilters['period'];updateClipFilters({period,from:period==='custom'?clipFilters.from:undefined,to:period==='custom'?clipFilters.to:undefined});});
 root.querySelectorAll<HTMLButtonElement>('[data-filter-state]').forEach(button=>button.onclick=()=>{const state=button.dataset.filterState as 'favorite'|'pinned';updateClipFilters({[state]:!clipFilters[state]});});
 for(const [attribute,group] of [['data-filter-source','sources'],['data-filter-tag','tags'],['data-filter-extension','extensions']] as const)root.querySelectorAll<HTMLButtonElement>('['+attribute+']').forEach(button=>button.onclick=()=>{const value=button.getAttribute(attribute)! as string,current=clipFilters[group],next=current.includes(value)?current.filter(item=>item!==value):[...current,value];updateClipFilters({[group]:next});});
 root.querySelectorAll<HTMLButtonElement>('[data-filter-size]').forEach(button=>button.onclick=()=>{const size=button.dataset.filterSize as ClipFilters['size'];updateClipFilters({size:clipFilters.size===size?undefined:size});});
 root.querySelectorAll<HTMLInputElement>('[data-filter-date]').forEach(input=>input.onchange=()=>{let from=root.querySelector<HTMLInputElement>('[data-filter-date="from"]')?.value||undefined,to=root.querySelector<HTMLInputElement>('[data-filter-date="to"]')?.value||undefined;if(from&&to&&from>to){if(input.dataset.filterDate==='from')to=undefined;else from=undefined;}updateClipFilters({period:'custom',from,to});});
 bindDatePickers(root);
 const sourceSearch=root.querySelector<HTMLInputElement>('#advanced-source-search');if(sourceSearch)sourceSearch.oninput=()=>{const term=sourceSearch.value.trim().toLocaleLowerCase();root.querySelectorAll<HTMLElement>('[data-source-name]').forEach(option=>option.hidden=!!term&&!option.dataset.sourceName!.includes(term));};
}
function renderSourceFilters(){const root=q('source-filters');if(!root)return;root.hidden=page==='replies';if(root.hidden)return;const withoutSource={...clipFilters,sources:[]},candidates=collectionItems(state.clips,clipsByID,page,state.queue,state.shelf,'all',matches).items.filter(clipFilterPredicate(withoutSource)),apps=sourceEntries(candidates);root.hidden=!candidates.length;if(root.hidden)return;const entries=[{key:':all',name:tr('全部应用'),count:candidates.length},...apps];applicationSegments(root,entries,clipFilters.sources.length===1?clipFilters.sources[0]:':all',key=>{const focusSegment=document.activeElement instanceof HTMLElement&&document.activeElement.matches('[data-source]');updateClipFilters({sources:key===':all'?[]:[key]});if(focusSegment)requestAnimationFrame(()=>root.querySelector<HTMLElement>('[data-source="'+encodeURIComponent(key)+'"]')?.focus({preventScroll:true}));});}

let moreObserver:IntersectionObserver|undefined;
function renderCollection(){if(!q('results'))return;const results=q('results'),restoreScroll=retainListScroll(results);results.dataset.view='list';const focusRow=(document.activeElement as HTMLElement)?.closest<HTMLElement>('.clip-row'),focusId=focusRow?.dataset.id,focusIndex=focusRow?.dataset.queueIndex;
  if(page==='stack'){const toggle=q('stack-running');if(toggle){setMarkup(toggle,ico(state.stack.running?'pause':'play')+'<span>'+(state.stack.running?tr('停止自动入栈'):tr('开始自动入栈'))+'</span>');toggle.setAttribute('aria-pressed',String(state.stack.running));}}
  const filters=q('filters'),filterbar=filters.closest<HTMLElement>('.filterbar')!,filterActions=q('filter-actions');filterbar.hidden=page==='replies';filterbar.classList.toggle('is-stack',page==='stack');filters.hidden=page==='replies';filters.classList.toggle('tabs',!filters.hidden);filters.setAttribute('role','tablist');filters.setAttribute('aria-label',tr('类型'));const selectedKind=clipFilters.kinds.length===1?clipFilters.kinds[0]:'all';
  keyedMarkup(filters,filters.hidden?[]:['all','text','image','files','link','code'].map(kind=>({key:kind,html:`<button type="button" role="tab" class="filter ${kind===selectedKind?'active':''}" data-kind="${kind}" aria-selected="${kind===selectedKind}">${kind==='all'?'':ico(kind)}${labels[kind]}</button>`})));
  const oldPopover=filterActions.querySelector<HTMLElement>('#advanced-filter-popover'),oldSourceSearch=oldPopover?.querySelector<HTMLInputElement>('#advanced-source-search'),sourceTerm=oldSourceSearch?.value||'',sourceFocused=oldSourceSearch===document.activeElement,popoverScroll=oldPopover?.scrollTop||0;filterActions.hidden=page==='replies';filterActions.innerHTML=filterActions.hidden?'':advancedFilterMarkup()+(page==='stack'&&state.queue.length?ib('clear-queue',tr('清空堆栈'),'trash'):'' );const newPopover=filterActions.querySelector<HTMLElement>('#advanced-filter-popover');if(newPopover){newPopover.scrollTop=popoverScroll;const search=newPopover.querySelector<HTMLInputElement>('#advanced-source-search');if(search&&sourceTerm)search.value=sourceTerm;if(sourceFocused)search?.focus({preventScroll:true});}const pasteNext=q('paste-next');if(pasteNext)pasteNext.title=tr('粘贴下一项')+' · '+shortcut(state.settings.nextShortcut);
  filters.querySelectorAll<HTMLElement>('[data-kind]').forEach(button=>button.onclick=()=>{const kind=button.dataset.kind!;updateClipFilters({kinds:kind==='all'?[]:[kind as Kind]});});on('clear-queue',()=>confirm(tr('清空堆栈？'),state.stack.running?tr('只移出待粘贴项目，历史保留。自动入栈仍会继续。'):tr('只移出待粘贴项目，历史保留。'),()=>api.clearQueue()));bindAdvancedFilters(filterActions);if(sourceTerm)newPopover?.querySelector<HTMLInputElement>('#advanced-source-search')?.dispatchEvent(new Event('input'));renderFilterChips();
  const batchToggle=q('batch-mode');if(batchToggle){setMarkup(batchToggle,ico(batchMode?'close':'check')); batchToggle.classList.toggle('active',batchMode);batchToggle.setAttribute('aria-pressed',String(batchMode));batchToggle.title=batchMode?tr('退出批量选择'):tr('批量选择');batchToggle.setAttribute('aria-label',batchToggle.title);}
  if(page==='replies'){renderReplies();restoreScroll();renderBatch();return;}
  renderSourceFilters();
  const baseProjection=collectionItems(state.clips,clipsByID,page,state.queue,state.shelf,'all',matches),matchClip=clipFilterPredicate(clipFilters),included=baseProjection.items.map(matchClip),projection={items:baseProjection.items.filter((_,index)=>included[index]),indices:baseProjection.indices.filter((_,index)=>included[index])};if(page==='favorites'){const order=new Map(state.favoriteOrder.map((id,index)=>[id,index]));projection.items.sort((a,b)=>(order.get(a.id)??Infinity)-(order.get(b.id)??Infinity));}visible=projection.items;visibleQueueIndices=projection.indices;if(page==='stack'&&(state.queue[selectedQueueIndex]!==selected||!visibleQueueIndices.includes(selectedQueueIndex)))selectedQueueIndex=visibleQueueIndices.find(i=>state.queue[i]===selected)??visibleQueueIndices[0]??-1;
  if(!visible.some(c=>c.id===selected))selected=visible[0]?.id||'';if(page==='stack'&&selectedQueueIndex<0)selectedQueueIndex=visibleQueueIndices[0]??-1;
  results.closest('.workspace')!.classList.toggle('is-empty',!visible.length);keyedMarkup(results,visible.length?[...visible.slice(0,limit).map((c,i)=>({key:page==='stack'?'slot:'+visibleQueueIndices[i]+'@'+c.id:'clip:'+c.id,html:batchMode?tr`<div class="clip-entry"><input type="checkbox" data-check="${c.id}" aria-label="选择 ${esc(c.title)}" ${checked.has(c.id)?'checked':''}>${row(c,i)}</div>`:row(c,i)})),...(visible.length>limit?[{key:':more',html:tr('<button id="load-more" class="load-more quiet">显示更多记录</button>')}]:[])]:[{key:':empty',html:empty(query?tr('没有找到相关内容'):page==='favorites'?tr('暂无收藏'):page==='stack'?tr('堆栈为空'):page==='shelf'?tr('容器为空'):categoryId()?tr('还没有符合分类的记录'):tr('暂无记录'),query?tr('换个关键词，或调整筛选条件'):page==='favorites'?tr('选中记录后，点击星标收藏'):page==='stack'?tr('在内容预览中，将记录加入堆栈'):page==='shelf'?tr('拖入文件或图片，或点击右上角添加文件'):categoryId()?tr('复制符合规则的内容，或编辑分类条件'):state.settings.paused?tr('自动记录已暂停。点击侧边栏底部的播放按钮继续记录。'):tr('在其他应用复制文字、图片或文件，记录会出现在这里'))}]);
  restoreScroll();if(focusId)results.querySelector<HTMLElement>(`[data-id="${focusId}"]${page==='stack'?`[data-queue-index="${focusIndex}"]`:''}`)?.focus({preventScroll:true});renderBatch();bindRows();void hydrateAppIcons(q('content'));on('load-more',()=>{limit+=100;renderCollection();});moreObserver?.disconnect();const more=q('load-more');if(more){moreObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)&&more.isConnected&&q('results')===results){moreObserver?.disconnect();limit+=100;renderCollection();}},{root:results,rootMargin:'240px'});moreObserver.observe(more);}void renderDetail().catch(toast);
}
function empty(title:string,description:string){return `<div class="empty"><div class="empty-icon">${ico(query?'search':page==='stack'?'stack':page==='favorites'?'star':'clipboard')}</div><h2>${title}</h2><p>${description}</p></div>`;}
function selectRow(id:string,index=-1){selected=id;selectedQueueIndex=page==='stack'?index:-1;const root=q('results'),previous=root.querySelector<HTMLElement>('.clip-row.selected'),next=root.querySelector<HTMLElement>('[data-id="'+CSS.escape(id)+'"]'+(page==='stack'?'[data-queue-index="'+index+'"]':''));for(const node of new Set([previous,next]))if(node){const active=node===next;node.classList.toggle('selected',active);if(node.getAttribute('aria-pressed')!==String(active))node.setAttribute('aria-pressed',String(active));}void renderDetail().catch(toast);}
const boundRows=new WeakSet<HTMLElement>();
function bindRows(){const root=q('results');if(!boundRows.has(root)){boundRows.add(root);const row=(event:Event)=>event.target instanceof Element?event.target.closest<HTMLButtonElement>('.clip-row'):null;
 root.addEventListener('click',event=>{const button=row(event);if(button&&root.contains(button))selectRow(button.dataset.id!,Number(button.dataset.queueIndex));});
 root.addEventListener('dblclick',event=>{const button=row(event);if(button&&root.contains(button))void useSelected(true).catch(toast);});
 root.addEventListener('dragstart',event=>{const button=row(event),grip=event.target instanceof Element&&!!event.target.closest('.row-sort-grip');if(grip)return;const clip=button&&clipsByID.get(button.dataset.id!);if(button&&clip&&page!=='replies'&&['image','files'].includes(clip.kind)){event.preventDefault();api.drag(clip.id);}});
 root.addEventListener('change',event=>{const input=event.target;if(input instanceof HTMLInputElement&&input.matches('[data-check]')){input.checked?checked.add(input.dataset.check!):checked.delete(input.dataset.check!);renderBatch();}});
 }root.querySelectorAll<HTMLInputElement>('[data-check]').forEach(input=>input.checked=checked.has(input.dataset.check!));for(const button of root.querySelectorAll<HTMLButtonElement>('.clip-row')){const clip=clipsByID.get(button.dataset.id!),draggable=page!=='replies'&&!!clip&&['image','files'].includes(clip.kind);if(button.draggable!==draggable)button.draggable=draggable;button.querySelector<HTMLElement>('.row-sort-grip')?.setAttribute('draggable','true');}bindSortable(root,{itemSelector:'.clip-row',handleSelector:'.row-sort-grip',id:item=>item.dataset.id!,enabled:()=>page==='favorites'||page==='replies',commit:visibleIds=>{const full=page==='favorites'?[...state.favoriteOrder]:state.snippets.map(item=>item.id),visible=new Set(visibleIds);let index=0;const next=full.map(id=>visible.has(id)?visibleIds[index++]:id);return (page==='favorites'?api.reorderFavorites(next):api.reorderSnippets(next)).then(refresh).catch(toast);}});}
async function renderDetail(){if(!isWindowVisible())return;if(page==='replies')return;const root=q('detail');if(!root)return;const key=currentDetailKey();if(detailRoot===root&&detailKey===key)return;const identity=previewIdentity(),retain=detailRoot===root&&renderedPreviewIdentity===identity&&!!retainedClip;if(!retain&&pendingPreview?.root===root&&pendingPreview.identity===identity)return;
  if(!retain){releaseDetail();root.innerHTML='<div class="preview-empty">'+ico('clipboard')+tr('<span>内容预览</span></div>');}if(!selected)return;const token=detailToken;let item:ClipPreview;
  if(retain)item=retainedClip!;else{const pending={root,identity};pendingPreview=pending;try{item=await api.preview(selected);}finally{if(pendingPreview===pending)pendingPreview=undefined;}}
  if(!isWindowVisible()||token!==detailToken||q('detail')!==root||previewIdentity()!==identity){if(item.imageURL)void api.releasePreview(item.imageURL).catch(()=>{});return;}item={...item,...clipsByID.get(selected)!};if(!retain)imageLease=item.imageURL;const reader=useTextReader(item.payload.text||'',item.kind==='code'),showContext=page!=='history'||!!query||hasClipFilters(clipFilters);
  const content=retain?'':item.kind==='image'&&!item.payload.png?tr('<div class="preview-empty"><span>原始图片已保留，可复制或另存。此格式暂不提供预览。</span></div>'):item.kind==='image'?tr`<div class="image-preview"><img src="${esc(item.imageURL)}" alt="剪贴板图片预览"></div>`:item.kind==='files'?filesPreviewMarkup(item):!item.payload.text&&item.payload.formats?.length?tr('<div class="preview-empty"><span>原始富文本已保留，可复制或在「格式与信息」中另存。</span></div>'):reader?'':`<pre class="text-preview ${item.kind==='code'?'code-preview':''}">${highlight(item.payload.text||'')}</pre>`;
  patchMarkup(root,tr`<div class="detail-top"><span class="preview-heading"><strong class="preview-title">${esc(item.title)}</strong><span class="detail-kind">${appIdentity(item.source)}${esc(item.source.replace(/\.exe$/i,''))}<span class="preview-kind">${ico(item.kind)}${labels[item.kind]}</span></span></span><div class="detail-tools">${(reader?ib('preview-wrap',tr('自动换行'),'text'):'')+ib('favorite',item.favorite?tr('取消收藏'):tr('收藏'),'star',item.favorite)}${ib('pin',item.pinned?tr('取消置顶'):tr('置顶'),'pin',item.pinned)}${ib('edit',tr('编辑内容和标签'),'edit')}${ib('delete',item.shared?tr('删除并同步撤回'):tr('删除记录'),'trash')}</div></div><div class="preview-body">${content}</div><div class="detail-meta"><time datetime="${new Date(item.updatedAt).toISOString()}">${formatDate(item.updatedAt,{dateStyle:'medium',timeStyle:'medium'})}</time><span>${bytes(item.bytes)}${item.payload.html?tr(' · 含富文本'):''}</span>${item.tags.length?'<div class="tags">'+item.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')+'</div>':''}</div><div class="detail-actions"><div class="primary-actions">${button('paste',tr('粘贴'),'enter','primary')}${button('copy',tr('复制'),'copy')}</div><details class="detail-more"><summary>${tr('更多操作')}</summary><div class="secondary-actions">${page==='stack'?`${ib('queue-up',tr('上移'),'up')}${ib('queue-down',tr('下移'),'down')}${button('dequeue',tr('移出堆栈'),'close','quiet')}`:button('enqueue',state.queue.includes(item.id)&&!state.stack.options.duplicates?tr('已加入堆栈'):tr('加入堆栈'),'stack','quiet')}${item.payload.text?`${ib('plain',tr('复制纯文本'),'text')}${ib('split',tr('按行拆分到堆栈'),'list')}`:''}${ib('share-record',item.shared?tr('已共享'):item.kind==='files'?tr('共享文件副本'):tr('共享此条'),'link',!!item.shared)+ib('private-record',item.localOnly?tr('允许共享'):tr('设为仅本机'),'shield',!!item.localOnly)}${ib('save-reply',tr('存为快捷回复'),'replies')}${item.payload.png||item.payload.text?ib('sticker-open',tr('贴到桌面'),'pin'):''}${ib('content-info',tr('格式与信息'),'files')}${item.payload.png?ib('edit-image',tr('编辑图片'),'edit')+ib('ai-image',tr('AI 处理'),'bot')+ib('export-image',tr('图片另存为'),'download')+ib('upload-image',tr('上传图片并复制链接'),'link')+ib('reupload-image',tr('重新上传'),'refresh'):''}${ib('shelf-item',page==='shelf'?tr('移出容器'):tr('加入拖拽容器'),page==='shelf'?'close':'files')}</div>${item.payload.text?'<div class="text-tool-actions">'+button('translate',tr('翻译'),'replies','quiet small')+button('summarize',tr('总结'),'text','quiet small')+button('rewrite',tr('改写'),'edit','quiet small')+button('run-command',tr('运行指令'),'bot','quiet small')+button('run-script',tr('脚本'),'code','quiet small')+'</div>':''}</details></div>`,source=>detailLayout(source,false),retain?node=>node.classList.contains('preview-body'):undefined);bindDetailLayout(root);void hydrateAppIcons(root);
  if(showContext){if(!root.querySelector('#show-context'))root.querySelector<HTMLElement>('.secondary-actions')?.insertAdjacentHTML('beforeend',ib('show-context',tr('在时间线中显示'),'history'));on('show-context',()=>{resetClipFilters();page=state.shelf.includes(item.id)?'shelf':'history';query='';matches=null;checked.clear();render();});}if(state.categories.some(category=>category.manual)){if(!root.querySelector('#organize-manual-categories'))root.querySelector<HTMLElement>('.secondary-actions')?.insertAdjacentHTML('beforeend',ib('organize-manual-categories',tr('整理到分类'),'files'));on('organize-manual-categories',()=>organizeManualCategories([item.id]));}bindDetailLayout(root);
  if(q('share-record')){setActionDisabled(q<HTMLButtonElement>('share-record'),!!item.shared||!!item.localOnly);on('share-record',()=>api.syncShare(item.id));on('private-record',()=>modal(item.localOnly?tr('允许此内容共享？'):tr('设为仅本机？'),item.localOnly?tr('<p>取消限制后，可手动共享；再次复制时也遵守自动同步设置。</p>'):tr('<p>保留本机记录并撤回已共享的发布；再次复制相同内容也不会自动共享。其他设备的备份不受影响。</p>'),()=>api.syncLocal(item.id,!item.localOnly),item.localOnly?tr('允许共享'):tr('设为仅本机')));}
  const act=(name:string,action:ClipAction)=>on(name,async()=>{if(page==='stack'&&['dequeue','up','down'].includes(action)){const index=selectedQueueIndex;await api.queueAction(index,item.id,action as 'dequeue'|'up'|'down',[...state.queue]);selectedQueueIndex=action==='dequeue'?index:Math.max(0,Math.min(state.queue.length-1,index+(action==='up'?-1:1)));}else await api.action(item.id,action);if(action==='delete')toast(tr('已删除记录'),true);else if(action==='enqueue')toast(tr('已加入堆栈'));else if(action==='split')toast(tr('已按行加入堆栈'));});act('favorite','favorite');act('pin','pin');act('delete','delete');act('enqueue','enqueue');act('dequeue','dequeue');act('queue-up','up');act('queue-down','down');act('split','split');on('translate',()=>tools.ai(item,'translate'));on('summarize',()=>tools.ai(item,'summarize'));on('ai-image',()=>tools.ai(item,'custom'));on('rewrite',()=>tools.ai(item,'rewrite'));on('run-command',()=>tools.ai(item));on('run-script',()=>tools.script(item));
  if(!retain){disposeImagePreview=mountImagePreview(root);if(item.kind==='files')disposeFilesPreview=mountFilesPreview(root,item,api,toast);if(reader)showTextReader(item.payload.text||'',item.kind==='code');restorePreviewPosition();}retainedClip=item;renderedPreviewIdentity=identity;detailRoot=root;detailKey=currentDetailKey();on('copy',()=>performSelected(false));on('paste',()=>performSelected(true));on('plain',async()=>{await api.copy(item.id,false,true);toast(tr('已复制纯文本'));});on('edit',()=>editClip(item));on('save-reply',()=>advanced.editSnippet(undefined,item));on('content-info',()=>advanced.contentInfo(item.id));on('sticker-open',async()=>{await api.pinToDesktop(item.id);toast(tr('已贴到桌面'));});on('edit-image',()=>api.editImage(item.id));on('export-image',async()=>{const result=await api.exportImage(item.id);if(result)toast(tr('已保存：')+result);});on('upload-image',async()=>{await api.startImageUpload(item.id);toast(tr('已加入任务中心，完成后复制链接'));});on('reupload-image',async()=>{await api.startImageUpload(item.id,true);toast(tr('已加入重新上传任务'));});if(item.payload.png)void api.imageUploadRecord(item.id).then(receipt=>{if(!receipt||retainedClip?.id!==item.id||!root.isConnected)return;const upload=root.querySelector<HTMLButtonElement>('#upload-image');if(upload){upload.title=upload.ariaLabel=tr('复制图床链接');const label=upload.querySelector('span');if(label)label.textContent=tr('复制图床链接');}const group=root.querySelector<HTMLElement>('[data-action-group="hosting"]');if(group){const note=group.querySelector<HTMLElement>('.hosting-receipt')||document.createElement('small');note.className='hosting-receipt';note.textContent=tr('已上传，再次使用前会检查链接');group.querySelector('h4')?.after(note);}}).catch(()=>{});on('shelf-item',async()=>{await api.batch([item.id],page==='shelf'?'unshelf':'shelf');toast(page==='shelf'?tr('已移出容器'):tr('已加入拖拽容器'));});
}
function useSelected(paste:boolean){const button=q<HTMLButtonElement>(paste?'paste':'copy');return actions.run('clipboard',()=>performSelected(paste),button?[button]:[]);}
async function performSelected(paste:boolean){const id=selected,targetPage=page,term=query;if(!id)return;if(term){await runSearch();await api.rememberSearch(term);}if(targetPage==='replies'){await advanced.useSnippet(id,paste);return;}await api.copy(id,paste);if(!paste)toast(tr('已复制'));}
function renderReplies(){const list=filteredReplies();if(!list.some(s=>s.id===selected))selected='';renderReplyCards(q('results'),list,{icon:ico,label:kind=>labels[kind],highlight,empty:()=>empty(tr('暂无快捷回复'),tr('点击“新建回复”添加')),select:id=>{selected=id;},use:(id,paste)=>advanced.useSnippet(id,paste),edit:id=>advanced.editSnippet({id}),remove:id=>confirm(tr('删除快捷回复？'),tr('删除后不可撤销。'),async()=>{await api.removeSnippet(id);await refresh();}),reorder:ids=>{const shown=new Set(ids);let index=0;return api.reorderSnippets(state.snippets.map(item=>shown.has(item.id)?ids[index++]:item.id)).then(refresh).catch(toast);},notice:toast,selection:batchMode?{checked,toggle:toggleReplySelection}:undefined},replyLayout);}
function modal(title:string,body:string,onSave:()=>Promise<void>,save=tr('保存')){const dialog=q<HTMLDialogElement>('dialog');resetDialogMotion(dialog);dialog.classList.add('one-form-dialog');dialog.classList.add('one-dialog');dialog.innerHTML=`<form method="dialog">${dialogParts(title,body,`<button id="modal-cancel" type="button">${tr('取消')}</button><button class="primary" type="submit">${esc(save)}</button>`,true)}</form>`;modalLayout(dialog);const dismiss=()=>{if(!oneDialogDismissLocked(dialog))void closeDialog(dialog);};on('modal-close',dismiss);q('modal-close').setAttribute('type','button');on('modal-cancel',dismiss);const form=dialog.querySelector('form')!,saves=new ActionScope(),b=form.querySelector<HTMLButtonElement>('[type=submit]')!;form.onsubmit=e=>{e.preventDefault();if(b.disabled||!form.isConnected||dialog.querySelector('form')!==form)return;void saves.run('save',async()=>{await onSave();if(dialog.querySelector('form')===form)await closeDialog(dialog);},[b]).catch(e=>{if(!dialog.open||dialog.querySelector('form')!==form){toast(e);return;}const shortcutField=form.querySelector<HTMLInputElement>('.shortcut-input');if(shortcutField&&isShortcutError(e)&&shortcutFeedback(shortcutField,e,()=>form.requestSubmit())){q('modal-error').textContent='';return;}q('modal-error').textContent=String((e as Error).message).replace(/^Error invoking remote method '[^']+': Error: /,'');});};dialog.oncancel=event=>{event.preventDefault();dismiss();};openOneDialog(dialog,dismiss);}
function editClip(item:ClipPreview){let initialText='';const editable=item.kind!=='image'&&item.kind!=='files'&&!!item.payload.text;modal(tr('编辑记录'),tr`${editable?tr`<label class="field">内容<textarea id="edit-text" rows="10">${esc(item.payload.text)}</textarea></label><p class="field-help">更改正文会保存为纯文本，原有富文本格式将移除。</p>`:''}<label class="field">标签<input id="edit-tags" value="${esc(item.tags.join(', '))}" placeholder="用逗号分隔，例如 工作, 灵感"></label>`,async()=>{await api.edit(item.id,editable?(q<HTMLTextAreaElement>('edit-text').value===initialText?item.payload.text!:q<HTMLTextAreaElement>('edit-text').value):'',q<HTMLInputElement>('edit-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean));toast(tr('已保存'));});if(editable){const input=q<HTMLTextAreaElement>('edit-text'),help=input.closest('label')!.nextElementSibling as HTMLElement;initialText=input.value;const update=()=>help.hidden=input.value===initialText||!item.payload.html&&!item.payload.rtf&&!item.payload.formats?.length;input.addEventListener('input',update);update();}}
function editReply(value?:Partial<Snippet>){return advanced.editSnippet(value);}
function confirm(title:string,description:string,fn:()=>Promise<void>,undo=false){modal(title,`<p>${description}</p>`,async()=>{await fn();toast(tr('操作完成'),undo);},tr('确认'));}
function switchField(id:string,checked:boolean,label:string){return `<label class="switch"><input id="${id}" type="checkbox" role="switch" aria-label="${label}" ${checked?'checked':''}><span></span></label>`;}
let disposeVersions:(()=>void)|undefined,settingsRevision=0;
let disposeUpdates:(()=>void)|undefined;
async function renderSettings(){const revision=++settingsRevision;disposeUpdates?.();disposeVersions?.();const s=state.settings,content=q('content');if(!content.querySelector('.collection'))content.replaceChildren();const stage=document.createElement('div');stage.className='settings-stage';content.append(stage);stage.innerHTML=tr`<section class="settings-page"><div class="page-heading"><div><h1>${tr('设置')}</h1></div><span class="version"></span></div><div class="settings-scroll"><h2 class="section-label">${tr('外观')}</h2><div class="setting-row"><div><strong>${tr('主题')}</strong></div><div class="theme-modes" id="theme-options">${['system','light','dark'].map((t,i)=>`<button data-theme-choice="${t}" aria-pressed="${s.theme===t}" class="theme-choice" aria-label="${[tr('系统'),tr('浅色'),tr('深色')][i]}"><span class="theme-mini ${t}"><i></i><b></b><em></em></span><span>${[tr('系统'),tr('浅色'),tr('深色')][i]}</span></button>`).join('')}</div></div><div id="appearance-inline"></div><h2 class="section-label">${tr('界面语言')}</h2><div id="language-inline"></div><h2 class="section-label">${tr('桌面交互')}</h2><div id="desktop-inline"></div><div id="efficiency-inline"></div><div class="setting-row"><div><label for="max-items">${tr('记录数量上限')}</label></div><div class="inline-fields"><label><input id="max-items" type="number" min="50" max="10000" value="${s.maxItems}">${tr('条')}</label></div></div><div class="setting-row"><div><label for="retention">${tr('保留天数')}</label><p>${tr('收藏、置顶、堆栈、容器、共享及设为永久存储的分类不受自动清理影响')}</p></div><div class="inline-fields"><label><input id="retention" type="number" min="1" max="365" value="${s.retentionDays}">${tr('天')}</label></div></div><div class="setting-row align-top"><div><strong>${tr('排除应用')}</strong></div><textarea id="excluded-apps" rows="4" aria-label="${tr('排除应用')}" placeholder="${tr('每行一个进程名称，例如 bitwarden.exe')}">${esc(s.excludedApps.join('\n'))}</textarea></div><div class="setting-row"><div><span>${tr('开机启动')}</span></div>${switchField('launch-login',s.launchAtLogin,tr('开机启动'))}</div><h2 class="section-label">${tr('快捷键')}</h2>${[['shortcut',tr('打开主窗口')],['nextShortcut',tr('粘贴堆栈下一项')]].map(([key,name])=>tr`<div class="setting-row"><label for="${key}">${name}</label><input class="hotkey-input" id="${key}" data-value="${esc(s[key as keyof Settings])}" value="${shortcut(s[key as 'shortcut'])}" readonly aria-label="${name}快捷键" title="点击后按下新的快捷键"></div>`).join('')}<div class="setting-row"><label for="ai-chat-shortcut">${tr('打开 AI 对话')}</label><input class="hotkey-input" id="ai-chat-shortcut" data-value="${esc(state.chatShortcut??'Alt+Space')}" value="${shortcut(state.chatShortcut??'Alt+Space')}" readonly aria-label="${tr('AI 对话快捷键')}" title="${tr('点击后按下新的快捷键')}"></div><div id="shortcut-unassigned-error" class="warning" hidden></div></div></section>`;
  stage.querySelector('#ai-chat-shortcut')!.closest('.setting-row')!.insertAdjacentHTML('afterend',`<div class="setting-row"><div><label for="quick-panel-shortcut">${tr('打开快捷面板')}</label><p>${tr('点击粘贴，右键复制')}</p></div><input class="hotkey-input" id="quick-panel-shortcut" data-value="${esc(state.quickShortcut??QUICK_SHORTCUT)}" value="${shortcut(state.quickShortcut??QUICK_SHORTCUT)}" readonly aria-label="${tr('快捷面板快捷键')}" title="${tr('点击后按下新的快捷键')}"></div>`);
  stage.querySelector('#quick-panel-shortcut')!.closest('.setting-row')!.insertAdjacentHTML('afterend',`<div class="setting-row"><div><label for="intercept-win-v">${tr('拦截 Win+V 系统剪贴板')}</label><p>${tr('开启后按 Win+V 打开快捷面板，退出 Clip 后恢复系统剪贴板。')}</p></div>${switchField('intercept-win-v',state.interceptWinV===true,tr('拦截 Win+V 系统剪贴板'))}</div>`);
  stage.querySelector('.version')!.textContent='v'+APP_VERSION;const settingsRoot=stage.querySelector<HTMLElement>('.settings-scroll')!,first=settingsRoot.firstElementChild!;
  q('retention').closest('.setting-row')!.insertAdjacentHTML('afterend',`<div class="setting-row"><div><strong>${tr('本地历史容量上限')}</strong><p>${tr('当前使用')} ${bytes(state.bytes)}。${tr('调低上限不会删除已有内容。')}</p></div><div class="inline-fields"><label><input id="history-cap" type="number" min="64" max="1024" step="1" value="${s.maxHistoryMiB}">MiB</label></div></div>`);
  q('launch-login').closest('.setting-row')!.insertAdjacentHTML('afterend',`<h2 class="section-label">${tr('图床')}</h2><div id="image-host-settings"></div>`);
  await mountImageHostSettings(q('image-host-settings'),api,toast);
  const general=document.createElement('h2');general.className='section-label';general.textContent=tr('基本设置');settingsRoot.insertBefore(general,first);const launch=q('launch-login').closest<HTMLElement>('.setting-row')!;const language=q('language-inline');language.previousElementSibling?.remove();
  const sidebarSetting=document.createElement('div');sidebarSetting.className='setting-row';sidebarSetting.innerHTML=`<div><strong>${tr('侧边栏')}</strong><p>${tr('选择显示的入口，并调整同组顺序。')}</p></div><button type="button" id="manage-sidebar" class="quiet">${tr('管理侧边栏')}</button>`;
  const restartSetting=document.createElement('div');restartSetting.className='setting-row';restartSetting.innerHTML=`<div><strong>${tr('重启 Clip')}</strong><p>${tr('重新启动应用并保留当前数据和设置。')}</p></div><button type="button" id="restart-clip">${tr('重启 Clip')}</button>`;
  const applicationCard=document.createElement('section');applicationCard.className='settings-card basic-application-card';applicationCard.innerHTML='<h3>'+tr('应用')+'</h3>';const traySetting=document.createElement('div');traySetting.className='setting-row';traySetting.innerHTML=`<div><strong>${tr('托盘图标左键单击')}</strong><p>${tr('选择单击托盘图标时打开的页面。')}</p></div><select id="tray-click-action">${([['open',tr('打开 Clip')],['recent',tr('最近记录')],['quick',tr('快捷面板')],['replies',tr('快捷回复')],['shelf',tr('拖拽容器')]] as const).map(([value,label])=>`<option value="${value}" ${value===(s.trayClickAction||'open')?'selected':''}>${tr(label)}</option>`).join('')}</select>`;applicationCard.append(launch,traySetting,sidebarSetting,restartSetting);
  const historyCard=document.createElement('section');historyCard.className='settings-card basic-history-card';historyCard.innerHTML='<h3>'+tr('剪贴板记录')+'</h3>';historyCard.append(q('excluded-apps').closest('.setting-row')!,q('max-items').closest('.setting-row')!,q('retention').closest('.setting-row')!,q('history-cap').closest('.setting-row')!);
  general.after(language,applicationCard,historyCard);on('manage-sidebar',manageSidebar);on('restart-clip',()=>api.restart());
  const updateHeading=document.createElement('h2');updateHeading.className='section-label';updateHeading.textContent=tr('应用更新');const updatesRoot=document.createElement('div');updatesRoot.id='updates';q('desktop-inline').previousElementSibling!.before(updateHeading,updatesRoot);disposeUpdates=mountUpdates(updatesRoot,toast);
  await Promise.all([languageUI(inlineSettings(q('language-inline'),toast)),appearanceUI(inlineSettings(q('appearance-inline'),toast,true)),desktopUI(inlineSettings(q('desktop-inline'),toast)),efficiencyUI({...inlineSettings(q('efficiency-inline'),toast),reuse:()=>{}}).settings(false)].map(task=>task.catch(toast)));
  language.querySelector('.inline-settings-card')?.classList.remove('settings-card','inline-settings-card');applicationCard.querySelector('h3')!.after(language);general.after(applicationCard,q('efficiency-inline'),historyCard);
  const themeRow=settingsRoot.querySelector<HTMLElement>('.setting-row:has(.theme-modes)'),colorHeader=settingsRoot.querySelector('.appearance-colors>.settings-card-heading');if(themeRow&&colorHeader)colorHeader.after(themeRow);bindSettingsPreferences(settingsRoot,s,toast);
  await mountAuxiliaryShortcuts(settingsRoot,toast);settingsRoot.append(q('intercept-win-v').closest('.setting-row')!);
  settingsRoot.querySelectorAll<HTMLInputElement>('.hotkey-input').forEach(input=>setupShortcut(input,toast));
  showShortcutRegistrationErrors(settingsRoot,state.hotkeyError);
  const chatShortcutInput=settingsRoot.querySelector<HTMLInputElement>('#ai-chat-shortcut')!;let savedChatShortcut=state.chatShortcut??'Alt+Space',chatShortcutSaves=Promise.resolve();chatShortcutInput.addEventListener('change',()=>{const value=chatShortcutInput.dataset.value||'';chatShortcutSaves=chatShortcutSaves.catch(()=>{}).then(async()=>{try{await api.configureChatShortcut(value);savedChatShortcut=value;if(chatShortcutInput.dataset.value===value)shortcutFeedback(chatShortcutInput);}catch(error){if(chatShortcutInput.dataset.value!==value)return;chatShortcutInput.dataset.value=savedChatShortcut;chatShortcutInput.value=shortcutLabel(savedChatShortcut);shortcutFeedback(chatShortcutInput,error,()=>{chatShortcutInput.dataset.value=value;chatShortcutInput.value=shortcutLabel(value);chatShortcutInput.dispatchEvent(new Event('change',{bubbles:true}));});}});});
  const quickShortcutInput=settingsRoot.querySelector<HTMLInputElement>('#quick-panel-shortcut')!;let savedQuickShortcut=state.quickShortcut??QUICK_SHORTCUT,quickShortcutSaves=Promise.resolve();quickShortcutInput.addEventListener('change',()=>{const value=quickShortcutInput.dataset.value||'';quickShortcutSaves=quickShortcutSaves.catch(()=>{}).then(async()=>{try{await api.configureQuickShortcut(value);savedQuickShortcut=value;interceptInput.disabled=!value;if(value===''){savedIntercept=false;interceptInput.checked=false;}if(quickShortcutInput.dataset.value===value)shortcutFeedback(quickShortcutInput);}catch(error){if(quickShortcutInput.dataset.value!==value)return;quickShortcutInput.dataset.value=savedQuickShortcut;quickShortcutInput.value=shortcutLabel(savedQuickShortcut);shortcutFeedback(quickShortcutInput,error,()=>{quickShortcutInput.dataset.value=value;quickShortcutInput.value=shortcutLabel(value);quickShortcutInput.dispatchEvent(new Event('change',{bubbles:true}));});}});});
  const interceptInput=settingsRoot.querySelector<HTMLInputElement>('#intercept-win-v')!;let savedIntercept=state.interceptWinV===true;interceptInput.disabled=!quickShortcutInput.dataset.value;interceptInput.addEventListener('change',async()=>{const value=interceptInput.checked;interceptInput.disabled=true;try{await api.configureWinVInterception(value);savedIntercept=value;}catch(error){interceptInput.checked=savedIntercept;toast(error);}finally{interceptInput.disabled=!quickShortcutInput.dataset.value;}});
   const dataMount=document.createElement('div');dataMount.className='settings-data-mount';settingsRoot.append(dataMount);let body:HTMLElement|undefined;try{body=await dataPanel.render(dataMount,true);}catch(error){dataMount.remove();toast(error);}if(revision!==settingsRevision||page!=='settings'||!settingsRoot.isConnected){stage.remove();return;}
   if(body)try{const nodes=Array.from(body.children);dataMount.replaceWith(...nodes);const storageStart=q('history-vault').previousElementSibling as HTMLElement;const storage=storageUsage(),storageCard=document.createElement('section');storageCard.className='settings-card';storageCard.innerHTML=tr`<div class="storage-meter" id="storage-meter" data-level="${storage.level}"><div class="storage-meter-head"><strong id="settings-storage-summary">${settingsStorageSummary()}</strong><span id="storage-usage"><span id="storage-bytes">${bytes(state.bytes)} / ${bytes(storage.maximum)}</span> · <b id="storage-percent">${storage.percent}%</b></span></div><div class="storage-progress-track" role="progressbar" aria-label="${tr('本地历史容量')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.min(100,storage.percent)}"><i id="storage-progress" style="width:${Math.min(100,storage.ratio*100)}%"></i></div><div class="storage-meter-note"><span id="storage-notice">${storage.hint}</span><button id="adjust-history-cap" type="button" class="quiet small">${tr('调整上限')}</button></div></div><div class="setting-row"><div><span>清除普通历史</span><p>保留收藏、置顶、堆栈、容器、共享及永久分类记录和快捷回复，可撤销本次清除</p></div><button id="clear-history">清除历史</button></div>`;storageStart.after(storageCard);
   const summary=storageCard.querySelector<HTMLElement>('#settings-storage-summary')!;summary.textContent=settingsStorageSummary();const breakdown=document.createElement('div');breakdown.id='storage-distribution';breakdown.innerHTML=storageBreakdownMarkup();storageCard.querySelector('.storage-meter')!.after(breakdown);const capacityRow=q('history-cap').closest<HTMLElement>('.setting-row')!;capacityRow.querySelector('p')!.textContent=tr('调低上限不会删除已有内容。');breakdown.after(capacityRow);
   const location=q('storage-directory').closest<HTMLElement>('.storage-location')!;
   const locationLabel=document.createElement('span');locationLabel.className='storage-location-label';locationLabel.textContent=tr('资料目录');location.prepend(locationLabel);
   storageCard.append(location);
   const previousDirectory=settingsRoot.querySelector<HTMLElement>('.storage-previous');if(previousDirectory)storageCard.append(previousDirectory);
   on('adjust-history-cap',()=>{const input=q<HTMLInputElement>('history-cap'),panel=input.closest<HTMLElement>('.section-panel');if(panel?.hidden)settingsRoot.querySelector<HTMLButtonElement>('.settings-nav button[aria-controls="'+panel.id+'"]')?.click();requestAnimationFrame(()=>{input.scrollIntoView({block:'center',behavior:'smooth'});input.focus({preventScroll:true});input.select();});});on('clear-history',()=>confirm(tr('清除普通历史？'),tr('只删除 Clip 中的普通记录，源文件不受影响。收藏、置顶、堆栈、拖拽容器及永久分类记录将保留。'),async()=>{await api.clear();await refresh();if(page==='settings')await renderSettings();},true));
   const versionsRoot=document.createElement('section');versionsRoot.className='program-versions settings-card';settingsRoot.append(versionsRoot);const versions=mountProgramVersions(versionsRoot,{toast,modal});disposeVersions=versions.dispose;const configure=(value:import('../shared/updates').UpdateState)=>versions.configure({installed:value.installed,current:value.current,busy:['checking','downloading','installing'].includes(value.phase)});void api.updateState().then(configure).catch(toast);const unsubscribe=api.onUpdate(configure);disposeVersions=()=>{unsubscribe?.();versions.dispose();};
   }catch(error){toast(error);}
  const headings=Array.from(settingsRoot.querySelectorAll<HTMLElement>(':scope > .section-label,:scope > .tools-section-heading'));sectionLayout(settingsRoot,headings.map(h=>h.querySelector('h2')?.textContent||h.textContent!),headings,'settings-section-051',{icons:[Settings2,Palette,Download,MousePointer2,CloudUpload,Keyboard,Database,Archive,History,RotateCcw],groups:[tr('常规'),tr('常规'),tr('常规'),tr('交互与连接'),tr('交互与连接'),tr('交互与连接'),tr('数据'),tr('数据'),tr('数据'),tr('数据')]});content.replaceChildren(...stage.childNodes);

}
document.addEventListener('clip:feedback',e=>toast((e as CustomEvent).detail));
document.addEventListener('keydown',e=>{
  if(e.isComposing||e.defaultPrevented)return;if(document.querySelector('dialog[open]'))return;const target=e.target as HTMLElement,editing=target.matches('input,textarea,select');
  if(e.key==='Escape'){if(document.querySelector('.reference-popover:not([hidden])'))return;e.preventDefault();if(filterPopoverOpen){setFilterPopover(false);q<HTMLButtonElement>('advanced-filter-toggle').focus();return;}void api.hide();return;}
  if(target.closest('.text-reader'))return;
  if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();(document.getElementById('reference-search')||document.getElementById('search'))?.focus();return;}
  if(target.closest('#toast')||(!editing&&target.closest('button,summary,[role=combobox]')&&!target.closest('.clip-row')))return;
  if(['settings','text-tools','capture-tools','ai','scripts','uri','sync','web','symbols','cheats'].includes(page))return;
  if(e.ctrlKey&&e.key.toLowerCase()==='z'&&!editing){e.preventDefault();void api.undo().catch(toast);return;}
  if(editing&&target.id!=='search')return;
  if(e.key==='Enter'){e.preventDefault();void useSelected(!e.ctrlKey).catch(toast);}
  if(['ArrowDown','ArrowUp'].includes(e.key)&&page!=='replies'){e.preventDefault();const fromRow=!!target.closest('.clip-row'),i=page==='stack'?visibleQueueIndices.indexOf(selectedQueueIndex):visible.findIndex(c=>c.id===selected),index=cardNavigation(i,visible.length,1,'vertical',e.key),next=visible[index];if(next){if(index>=limit){limit=Math.ceil((index+1)/100)*100;renderCollection();}selectRow(next.id,visibleQueueIndices[index]??-1);const row=document.querySelector<HTMLElement>(`[data-id="${selected}"]${page==='stack'?`[data-queue-index="${selectedQueueIndex}"]`:''}`);row?.scrollIntoView({block:'nearest'});if(fromRow)row?.focus({preventScroll:true});}}
  if(e.key==='Delete'&&!editing&&selected&&page!=='replies'){e.preventDefault();void api.action(selected,'delete').then(()=>toast(tr('已删除记录'),true)).catch(toast);}
});
window.addEventListener('clip:language-reload',()=>sessionStorage.setItem('clip-language-navigation',JSON.stringify({page,filters:clipFilters,selected,query})));try{const saved=JSON.parse(sessionStorage.getItem('clip-language-navigation')||'null');sessionStorage.removeItem('clip-language-navigation');if(saved&&typeof saved.page==='string'){page=saved.page==='data'?'settings':saved.page==='tools'?'ai':saved.page;clipFilters=normalizeClipFilters(saved.filters||{kinds:saved.kind&&saved.kind!=='all'?[saved.kind]:[],sources:saved.sourceApp?[saved.sourceApp]:[]});selected=saved.selected||'';query=saved.query||'';}}catch{}
q<HTMLDialogElement>('dialog').addEventListener('close',()=>setTimeout(()=>checkExternal(),0));
let refreshScheduled:ReturnType<typeof setTimeout>|undefined,refreshPending=false;
function scheduleRefresh(){refreshPending=true;if(!state||!isWindowVisible()||refreshScheduled)return;refreshScheduled=setTimeout(()=>{refreshScheduled=undefined;if(!isWindowVisible())return;refreshPending=false;void refresh().catch(toast);},32);}
setupWindowVisibility();onWindowVisibility(shown=>{if(!state)return;if(shown)scheduleRefresh();else{clearTimeout(refreshScheduled);refreshScheduled=undefined;clearTimeout(searchTimer);refreshToken++;searchRevision++;closeControls();suspendDetail();}});
api.onChange(scheduleRefresh);api.onNotice(toast);api.onChatSettings?.(()=>{page='text-tools';tools.setTab('ai');render();});
async function start(){state=await api.state();clipsByID=new Map(state.clips.map(c=>[c.id,c]));shell();render();checkExternal();if(refreshPending)scheduleRefresh();}
void start().catch(e=>{q('app').textContent=tr('Clip 加载失败：')+String(e);});
