import {dialogParts,openOneDialog,oneDialogDismissLocked} from './dialog-shell';
import {searchField,setSearchFieldValue} from './one-search';
import {icon as componentIcon,registerIcons} from './ui';
import type {ClipPreview,SnippetPreview} from '../shared/preview';
import {mountImagePreview} from './image-preview';
import {closeDialog,resetDialogMotion} from './dialog-motion';
import {collectionLayout,detailLayout,bindDetailLayout,modalLayout,toggleRecordInfo} from './layout-029';
import {setMarkup,keyedMarkup,patchMarkup,clearMarkup,retainListScroll} from './markup';
import {collectionItems} from '../shared/collection';
import {windowControls,setupChrome} from './chrome';
import {setupShortcut} from './shortcut';
import {bindSettingsPreferences} from './settings-preferences';
import {revealToolbar} from './toolbar-motion';
import {applicationSegments} from './application-segments';
import {appIdentity,hydrateAppIcons,sourceKey} from './source-apps';
import {inlineSettings} from './inline-settings';
import {closeControls} from './controls';
import {APP_VERSION} from '../shared/version';
import {mountUpdates} from './update-ui';
import {mountProgramVersions} from './program-versions-ui';
import {sectionLayout} from './page-layout';
import {Palette,MousePointer2,Database,Archive,RotateCcw} from 'lucide';
import {enableFeedbackScroll} from './feedback';
import {ActionScope,setActionDisabled} from './actions';
import {mountTextPreview,useTextReader,type TextPreviewHandle} from './lazy-text-preview';
import type {TextPreviewSnapshot} from './text-preview';
import {isWindowVisible,onWindowVisibility,setupWindowVisibility} from './window-visibility';
import './locale';
import {t as tr,formatBytes,formatDate,formatNumber} from '../shared/i18n';
import {languageUI} from './language-ui';
import './appearance';
import {appearanceUI} from './appearance-ui';
import {stackUI} from './stack-ui';
import {efficiencyUI} from './efficiency-ui';
import {webUI} from './web-ui';
import './styles.css';
import './desktop.css';
import {desktopUI} from './desktop-ui';
import {cardNavigation} from '../shared/desktop';
import { Clipboard, History, Star, Layers, MessageSquare, Settings2, Search, FileText, Image, Folder, Link, Code, Copy, Pin, Trash2, Plus, ArrowUp, ArrowDown, X, Check, Pause, Play, ChevronRight, List, Grid2X2, Download, Upload, Keyboard, ShieldCheck, Sun, Moon, Monitor, Pencil, CornerDownLeft, Undo2, Power, PanelLeft, Info, Ellipsis, AppWindow, Smile, BookOpen, Bot, Network, type IconNode } from 'lucide';
import type { State, Clip, Detail, Kind, Settings, Snippet, ClipAction } from '../shared/types';
import { advancedUI } from './advanced-ui';
import { textToolsUI } from './text-tools-ui';
import {dataUI} from './data-ui';
import {syncUI} from './sync-ui';
const actions=new ActionScope();
const api=window.clipper;
const icons:Record<string,IconNode>={clipboard:Clipboard,history:History,star:Star,stack:Layers,replies:MessageSquare,settings:Settings2,search:Search,text:FileText,image:Image,files:Folder,link:Link,code:Code,copy:Copy,pin:Pin,trash:Trash2,plus:Plus,up:ArrowUp,down:ArrowDown,close:X,check:Check,pause:Pause,play:Play,chevron:ChevronRight,list:List,grid:Grid2X2,download:Download,upload:Upload,keyboard:Keyboard,shield:ShieldCheck,sun:Sun,moon:Moon,monitor:Monitor,edit:Pencil,enter:CornerDownLeft,undo:Undo2,power:Power,panel:PanelLeft,info:Info,more:Ellipsis,app:AppWindow,smile:Smile,book:BookOpen,bot:Bot,network:Network};
registerIcons(icons);
const ico=(key:string)=>componentIcon('lucide:'+key);
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const button=(id:string,label:string,icon:string,cls='')=>`<button id="${id}" class="${cls}">${ico(icon)}<span>${label}</span></button>`;
const ib=(id:string,label:string,icon:string,active=false)=>`<button id="${id}" class="icon-button quiet ${active?'active':''}" title="${label}" aria-label="${label}"${active?' aria-pressed="true"':''}>${ico(icon)}</button>`;
const labels:Record<string,string>={history:tr('全部记录'),favorites:tr('收藏'),stack:tr('堆栈'),replies:tr('快捷回复'),settings:tr('设置'),shelf:tr('拖拽容器'),ai:tr('AI 服务'),scripts:tr('文本脚本'),uri:'URI',web:tr('网页共享'),sync:tr('局域网同步'),symbols:tr('表情符号'),cheats:'CheetSheet',text:tr('文本'),link:tr('链接'),code:tr('代码'),image:tr('图片'),files:tr('文件'),all:tr('全部')};
const shortcut=(s:string)=>s.replaceAll('Control','Ctrl').replaceAll('+',' + ');
const bytes=formatBytes;
function time(n:number){const diff=Date.now()-n;return diff<60000?tr('刚刚'):diff<3600000?tr`${Math.floor(diff/60000)} 分钟前`:diff<86400000?tr`${Math.floor(diff/3600000)} 小时前`:formatDate(n,{month:'short',day:'numeric'});}
let state:State,page='history',sourceApp='',kind='all',selected='',query='',matches:Set<string>|null=null,limit=100,visible:Clip[]=[],toastTimer:ReturnType<typeof setTimeout>,searchTimer:ReturnType<typeof setTimeout>,detailToken=0,refreshToken=0,searchRevision=0;
let disposeTextPreview:TextPreviewHandle|undefined,disposeImagePreview:(()=>void)|undefined,detailKey='',detailRoot:HTMLElement|undefined,imageLease:string|undefined;
let renderedPreviewIdentity='',retainedClip:ClipPreview|undefined,retainedSnippet:SnippetPreview|undefined,pendingPreview:{root:HTMLElement;identity:string}|undefined;
function previewIdentity(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);return JSON.stringify([page==='replies'?'snippet':'clip',selected,query,item&&('hash'in item?[item.hash,item.kind]:[item.revision,item.kind])]);}
let suspendedPreview:{key:string;top:number;left:number;reader?:TextPreviewSnapshot}|undefined;
function contentKey(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);return JSON.stringify([page,selected,selectedQueueIndex,query,item&&('hash'in item?[item.hash,item.kind]:[item.revision,item.kind])]);}
function suspendDetail(){const root=q('detail');if(root?.childElementCount){const key=contentKey(),reader=disposeTextPreview?.snapshot();if(reader||!suspendedPreview||suspendedPreview.key!==key)suspendedPreview={key,top:root.querySelector('.preview-body')?.scrollTop||0,left:root.querySelector('.preview-body')?.scrollLeft||0,reader};}releaseDetail();root?.replaceChildren();}
function releaseDetail(){if(detailRoot)clearMarkup(detailRoot);renderedPreviewIdentity='';retainedClip=retainedSnippet=undefined;pendingPreview=undefined;if(imageLease){void api.releasePreview(imageLease).catch(()=>{});imageLease=undefined;}disposeTextPreview?.();disposeTextPreview=undefined;disposeImagePreview?.();disposeImagePreview=undefined;detailKey='';detailRoot=undefined;detailToken++;}
function currentDetailKey(){const item=page==='replies'?state.snippets.find(s=>s.id===selected):clipsByID.get(selected);const metadata=item&&('hash'in item?[item.id,item.hash,item.kind,item.title,item.source,item.createdAt,item.updatedAt,item.favorite,item.pinned,item.tags,item.bytes,item.shared,item.localOnly]:[item.id,item.title,item.updatedAt,item.kind,item.shortcut,item.revision]);return JSON.stringify([page,selected,selectedQueueIndex,query,state.queue.includes(selected),state.stack.options.duplicates,metadata]);}
function showTextReader(text:string,code:boolean){const host=q('detail').querySelector<HTMLElement>('.preview-body')!,button=q<HTMLButtonElement>('preview-wrap'),storageKey=code?'preview-code-wrap':'preview-text-wrap',saved=localStorage.getItem(storageKey);disposeTextPreview=mountTextPreview(host,text,{code,query,wrap:saved===null?!code:saved==='true',wrapButton:button,changedWrap:value=>localStorage.setItem(storageKey,String(value)),resume:suspendedPreview?.key===contentKey()?suspendedPreview.reader:undefined});}
function restorePreviewPosition(){const saved=suspendedPreview;suspendedPreview=undefined;if(saved?.key!==contentKey())return;const host=q('detail').querySelector<HTMLElement>('.preview-body');if(host){host.scrollTop=saved.top;host.scrollLeft=saved.left;}}
let selectedQueueIndex=-1,visibleQueueIndices:number[]=[];
let batchMode=false,checked=new Set<string>(),clipsByID=new Map<string,Clip>();
const categoryId=()=>page.startsWith('category:')?page.slice(9):undefined;
const selectClip=async(id:string)=>{sourceApp='';page='history';selected=id;kind='all';query='';matches=null;await refresh();render();};
const tools=textToolsUI({modal,toast,select:selectClip,active:target=>page===target,navigate:(target,search='')=>{page=target;selected='';kind='all';query=search;matches=null;render();if(search)void runSearch().catch(toast);}});
let incomingBusy=false;
const checkExternal=()=>{if(!isWindowVisible()||incomingBusy||q<HTMLDialogElement>('dialog').open)return;incomingBusy=true;void(async()=>{const reply=await api.replyIntent();if(reply){page='replies';kind='all';query='';matches=null;selected=reply.kind==='fill'?reply.snippet.id:'';render();if(reply.kind==='fill')await advanced.useSnippet(reply.snippet.id,true,reply);return;}await tools.external();})().catch(toast).finally(()=>incomingBusy=false);};
const dataPanel=dataUI({modal,toast,refresh,active:()=>page==='settings',rerender:async()=>{if(page==='settings')await renderSettings();}});
const webPanel=webUI({modal,toast,history:()=>state.clips,active:()=>page==='web'});
const syncPanel=syncUI({modal,toast,history:()=>state.clips,active:()=>page==='sync'});
const stackPanel=stackUI({modal,toast});
const efficiencyPanel=efficiencyUI({modal,toast,reuse:term=>{query=term;limit=100;setSearchFieldValue(q<HTMLInputElement>('search'),term);q('search').focus();void api.rememberSearch(term).then(()=>runSearch()).catch(toast);}});
const advanced=advancedUI({modal,toast,refresh,select:selectClip,ai:text=>tools.ai(text)});
function categoryNavigation(){const node=q('categories');if(!node)return;keyedMarkup(node,[{key:':heading',html:tr`<div class="category-heading"><span>自定义分类</span>${ib('add-category',tr('新建分类'),'plus')}</div>`},...state.categories.map(c=>({key:c.id,html:`<button class="nav-item ${page==='category:'+c.id?'selected':''}" data-category="${c.id}"><i class="category-dot" style="background:${c.color}"></i><span>${esc(c.name)}</span></button>`}))]);on('add-category',()=>advanced.category());node.querySelectorAll<HTMLElement>('[data-category]').forEach(b=>b.onclick=()=>{page='category:'+b.dataset.category;selected='';kind='all';query='';checked.clear();matches=null;render();void runSearch().catch(toast);});}
function headingActions(){if(page==='replies')return ib('reply-hotkeys',tr('快捷回复设置'),'keyboard')+button('new-reply',tr('新建回复'),'plus','primary');if(page==='stack')return ib('stack-rules',tr('堆栈规则'),'settings')+ib('stack-batch',tr('批量入栈'),'plus')+ib('stack-reverse',tr('反转顺序'),'undo')+button('stack-running',state.stack.running?tr('停止自动入栈'):tr('开始自动入栈'),state.stack.running?'pause':'play')+button('paste-next',tr('粘贴下一项'),'enter','primary');return (page==='shelf'?button('add-files',tr('添加文件'),'plus','primary')+button('open-shelf',tr('浮动窗口'),'monitor'):button('take-screenshot',tr('截图'),'monitor')+button('open-recorder',tr('录制'),'play'))+ib('batch-mode',batchMode?tr('退出批量选择'):tr('批量选择'),batchMode?'close':'check',batchMode)+(categoryId()?ib('edit-category',tr('编辑分类'),'edit')+ib('remove-category',tr('删除分类'),'trash'):ib('undo-delete',tr('撤销删除'),'undo'));}
function bindAdvanced(){
  on('stack-rules',()=>stackPanel.rules());on('stack-batch',()=>stackPanel.batch());on('stack-reverse',()=>api.reverseStack());on('stack-running',()=>api.setStackRunning(!state.stack.running));
  on('reply-hotkeys',()=>efficiencyPanel.settings());on('open-recorder',()=>api.openRecorder());on('open-shelf',()=>api.showShelf());on('add-files',()=>api.addFiles());on('take-screenshot',()=>advanced.screenshot());on('batch-mode',()=>{batchMode=!batchMode;checked.clear();renderCollection();});
  on('edit-category',()=>advanced.category(state.categories.find(c=>c.id===categoryId())));on('remove-category',()=>confirm(tr('删除分类？'),tr('只删除分类规则，历史内容保留。'),async()=>{await api.removeCategory(categoryId()!);page='history';matches=null;await refresh();render();}));
  const drop=q('shelf-drop');if(drop){const area=q('content');area.ondragover=e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';drop.classList.add('dragging');}};area.ondragleave=e=>{if(!area.contains(e.relatedTarget as Node))drop.classList.remove('dragging');};area.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');const files=Array.from(e.dataTransfer?.files||[]);if(files.length)void api.dropFiles(files).then(()=>toast(tr('已添加到拖拽容器'))).catch(toast);};}else{q('content').ondragover=null;q('content').ondrop=null;q('content').ondragleave=null;}
}
function renderBatch(){const bar=q('batch-bar');if(!bar)return;const shown=batchMode&&page!=='replies';if(!shown){revealToolbar(bar,false);return;}patchMarkup(bar,tr`<strong class="batch-count">已选择 ${checked.size} 项</strong><button id="batch-all" class="quiet small">选择筛选结果</button><span class="spacer"></span><div class="batch-actions">${ib('batch-favorite',tr('批量收藏'),'star')}${ib('batch-enqueue',tr('批量加入堆栈'),'stack')}${ib('batch-tag',tr('批量添加标签'),'edit')}${ib('batch-shelf',page==='shelf'?tr('批量移出容器'):tr('批量加入拖拽容器'),'files')}${ib('batch-delete',tr('批量删除'),'trash')}</div>`);bar.querySelectorAll<HTMLButtonElement>('.batch-actions>button').forEach(button=>setActionDisabled(button,!checked.size));revealToolbar(bar,true);
  on('batch-all',()=>{checked=new Set(visible.slice(0,500).map(c=>c.id));renderCollection();if(visible.length>500)toast(tr('已选择前 500 条结果'));});
  for(const action of ['favorite','enqueue','shelf','delete','tag'] as const)on('batch-'+action,async()=>{const ids=[...checked];if(!ids.length){toast(tr('请先选择记录'));return;}const perform=async(tags:string[]=[])=>{await api.batch(ids,action==='shelf'&&page==='shelf'?'unshelf':action,tags);checked.clear();await refresh();toast(action==='delete'?tr`已删除 ${formatNumber(ids.length)} 条记录`:tr('批量操作完成'),action==='delete');};if(action==='delete')modal(tr`删除 ${formatNumber(ids.length)} 条记录？`,tr('<p>仅删除历史内容，不删除源文件。完成后可撤销。</p>'),()=>perform(),tr('删除'));else if(action==='tag')modal(tr('批量添加标签'),tr('<label class="field">标签<input id="batch-tags" placeholder="逗号分隔，例如 工作, 资料"></label>'),()=>perform(q<HTMLInputElement>('batch-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean)));else await perform();});
}
function toast(text:unknown,undo=false){q('toast').innerHTML=`<span tabindex="0">${esc(String(text instanceof Error?text.message:text).replace(/^Error invoking remote method '[^']+': Error: /,''))}</span>${undo?tr('<button id="undo-toast">撤销</button>'):''}`;q('toast').hidden=false;enableFeedbackScroll(q('toast').firstElementChild as HTMLElement);const arm=()=>{clearTimeout(toastTimer);toastTimer=setTimeout(()=>{if(!q('toast').matches(':hover,:focus-within'))q('toast').hidden=true;},6500);};q('toast').onmouseenter=()=>clearTimeout(toastTimer);q('toast').onmouseleave=arm;q('toast').querySelectorAll<HTMLElement>('[tabindex],button').forEach(el=>{el.onfocus=()=>clearTimeout(toastTimer);el.onblur=arm;});arm();if(undo)on('undo-toast',async()=>{await api.undo();toast(tr('已撤销删除'));});}
function on(id:string,fn:()=>unknown){actions.bind(q<HTMLButtonElement>(id),fn,toast,['copy','paste','plain'].includes(id)?'clipboard':id);}
function shell(){
  const nav=(p:string,icon:string,count=false)=>`<button data-page="${p}" class="nav-item" aria-label="${labels[p]}">${ico(icon)}<span>${labels[p]}</span>${count?`<small id="count-${p}"></small>`:''}</button>`;
  const group=(name:string,items:string,extra='')=>`<section class="sidebar-group"><h2 class="sidebar-group-caption">${name}</h2><nav class="${extra}" aria-label="${name}">${items}</nav></section>`;
  q('app').innerHTML=`<header class="titlebar"><div class="brand"><span class="brand-icon">${ico('clipboard')}</span><strong>Clipper</strong></div><div class="title-tools">${ib('sidebar-toggle',tr('收起侧边栏'),'panel')}<span class="spacer"></span></div>${windowControls()}</header><aside class="sidebar"><div class="sidebar-scroll">${group(tr('剪贴板'),nav('history','history',true)+nav('favorites','star',true)+nav('stack','stack',true)+nav('shelf','files',true)+nav('replies','replies',true))}<div id="categories"></div>${group(tr('工具'),nav('ai','bot')+nav('scripts','code')+nav('symbols','smile')+nav('cheats','book'))}${group(tr('连接与分享'),nav('sync','network')+nav('web','monitor')+nav('uri','link'),'nav-secondary')}</div><div class="sidebar-bottom"><button id="pause-nav" class="nav-item recording-status" aria-label="${tr('记录开关')}"></button>${nav('settings','settings')}</div></aside><main id="main"><div id="content"></div></main>`;
  setupChrome();document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>{b.title=labels[b.dataset.page!];b.onclick=()=>{(document.activeElement as HTMLElement)?.blur();closeControls();page=b.dataset.page!;selected='';kind='all';query='';matches=null;limit=100;checked.clear();batchMode=false;render();};});
  const collapse=(value:boolean)=>{document.body.classList.toggle('sidebar-collapsed',value);const toggle=q('sidebar-toggle');toggle.setAttribute('aria-expanded',String(!value));toggle.title=value?tr('展开侧边栏'):tr('收起侧边栏');toggle.setAttribute('aria-label',toggle.title);};collapse(localStorage.getItem('sidebar-collapsed')==='true');on('sidebar-toggle',()=>{const value=!document.body.classList.contains('sidebar-collapsed');collapse(value);localStorage.setItem('sidebar-collapsed',String(value));});
  on('pause-nav',()=>api.settings({...state.settings,paused:!state.settings.paused}));
}
function applyServiceStatus(){const services=state.services;for(const name of ['sync','web'] as const){const button=document.querySelector<HTMLButtonElement>(`.nav-secondary [data-page="${name}"]`);if(!button)continue;const value=name==='web'?(services?.web?'sharing':'off'):(services?.sync||'off'),label=value==='sharing'?tr('共享中'):value==='busy'?tr('同步中'):value==='error'?tr('需检查'):value==='ready'?tr('已开启'):'';button.dataset.service=value;let badge=button.querySelector<HTMLElement>('.nav-service-status');if(label){if(!badge){badge=document.createElement('small');badge.className='nav-service-status';button.append(badge);}badge.textContent=label;}else badge?.remove();button.title=labels[name]+(label?' · '+label:'');}}
function applyState(){document.documentElement.dataset.theme=state.dark?'dark':'light';for(const p of ['history','favorites','stack','shelf','replies'])q('count-'+p).textContent=formatNumber(p==='history'?state.clips.length:p==='favorites'?state.clips.filter(i=>i.favorite).length:p==='stack'?state.queue.length:p==='shelf'?state.shelf.length:state.snippets.length);const pause=q('pause-nav'),paused=state.settings.paused;pause.dataset.paused=String(paused);setMarkup(pause,`<i class="recording-indicator" aria-hidden="true">${ico('clipboard')}<b></b></i><span>${paused?tr('已暂停'):tr('自动记录')}</span><i class="recording-action" aria-hidden="true">${ico(paused?'play':'pause')}</i>`);pause.title=(paused?tr('恢复记录'):tr('暂停记录'))+' · '+shortcut(state.settings.shortcut);pause.setAttribute('aria-label',paused?tr('恢复记录'):tr('暂停记录'));pause.setAttribute('aria-pressed',String(!paused));applyServiceStatus();document.querySelectorAll<HTMLElement>('[data-page]').forEach(b=>{const active=b.dataset.page===page;b.classList.toggle('selected',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
async function refresh(){const token=++refreshToken,revision=searchRevision;const next=await api.state();if(token!==refreshToken)return;state=next;clipsByID=new Map(state.clips.map(c=>[c.id,c]));checked=new Set([...checked].filter(id=>clipsByID.has(id)));applyState();categoryNavigation();if(categoryId()&&q('content').querySelector('h1'))q('content').querySelector('h1')!.textContent=state.categories.find(c=>c.id===categoryId())?.name||tr('全部记录');if(!['settings','ai','scripts','uri','sync','web','symbols','cheats'].includes(page)){renderCollection();if(revision===searchRevision&&(query||categoryId()))await runSearch();}if(page==='settings')void dataPanel.updateStatus().catch(toast);if(page==='sync')void syncPanel.update().catch(toast);if(page==='web')void webPanel.update().catch(toast);checkExternal();}
let referenceLoad:Promise<typeof import('./reference-pages.js')>|undefined,disposeReference:(()=>void)|undefined,referenceRevision=0;
function renderReference(kind:'symbols'|'cheats'){
 const root=q('content'),revision=++referenceRevision;root.innerHTML='<div class="reference-loading" aria-hidden="true"><i></i><i></i><i></i></div>';
 referenceLoad??=import(new URL('./reference-pages.js',location.href).href) as Promise<typeof import('./reference-pages.js')>;
 void referenceLoad.then(module=>{if(revision===referenceRevision&&page===kind&&q('content')===root)disposeReference=module.mountReference(root,kind,toast);}).catch(error=>{referenceLoad=undefined;if(page===kind)toast(error);});
}
function render(){suspendedPreview=undefined;releaseDetail();searchRevision++;referenceRevision++;disposeReference?.();disposeReference=undefined;disposeUpdates?.();disposeUpdates=undefined;disposeVersions?.();disposeVersions=undefined;applyState();categoryNavigation();if(page==='settings')void renderSettings().catch(toast);else if(page==='ai'||page==='scripts'||page==='uri')void tools.render(page).catch(toast);else if(page==='sync')void syncPanel.render().catch(toast);else if(page==='web')void webPanel.render().catch(toast);else if(page==='symbols'||page==='cheats')renderReference(page);else{
  q('content').innerHTML=tr`<section class="collection"><div class="page-heading"><div><h1>${esc(labels[page]||state.categories.find(c=>c.id===categoryId())?.name||tr('全部记录'))}</h1></div><div class="heading-actions">${headingActions()}</div></div><div class="collection-toolbar">${searchField('search',tr('搜索剪贴板'),page==='replies'?tr('搜索快捷回复'):tr('搜索内容、标签或来源应用'),ib('search-history',tr('搜索历史'),'history'))}</div><div class="filterbar"><div id="filters" class="tabs"></div></div><div id="source-filters" class="source-filterbar tabs" role="tablist" aria-label="来源应用"></div><div id="batch-bar" class="batch-bar" hidden></div>${page==='shelf'?tr('<div id="shelf-drop" class="shelf-drop">拖入文件或图片；拖动记录即可放到其他应用</div>'):''}<div class="workspace"><div id="results" class="results" tabindex="0" aria-label="剪贴板记录"></div><section id="detail" class="detail" aria-label="内容预览"></section></div></section>`;
  collectionLayout(q('content'));const input=q<HTMLInputElement>('search');input.value=query;input.dispatchEvent(new Event('input'));let composing=false;const changed=()=>{searchRevision++;query=input.value.trim();limit=100;clearTimeout(searchTimer);if(!composing)searchTimer=setTimeout(()=>void runSearch().catch(toast),120);};input.oninput=changed;input.addEventListener('compositionstart',()=>{composing=true;clearTimeout(searchTimer);});input.addEventListener('compositionend',()=>{composing=false;changed();});input.onblur=()=>{if(!composing&&input.value.trim())void api.rememberSearch(input.value).catch(toast);};on('search-history',()=>efficiencyPanel.history());
  on('undo-delete',async()=>{await api.undo();toast(tr('已撤销删除'));});on('new-reply',()=>editReply());on('paste-next',()=>api.next());bindAdvanced();renderCollection();
}}
async function runSearch(){if(!isWindowVisible()){scheduleRefresh();return;}const revision=++searchRevision,requested=query,category=categoryId();try{const found=(query||category)&&page!=='replies'?new Set(await api.search(query,category)):null;if(revision!==searchRevision||requested!==query||category!==categoryId())return;matches=found;renderCollection();}catch(error){if(revision===searchRevision&&requested===query&&category===categoryId())throw error;}}
function highlight(text:string){if(!query)return esc(text);const first=query.split(/\s+/)[0],at=text.toLocaleLowerCase().indexOf(first.toLocaleLowerCase());return at<0?esc(text):esc(text.slice(0,at))+'<mark>'+esc(text.slice(at,at+first.length))+'</mark>'+esc(text.slice(at+first.length));}
function row(c:Clip,index:number){const active=selected===c.id&&(page!=='stack'||selectedQueueIndex===visibleQueueIndices[index]),summary=c.kind==='image'||c.preview.trim()===c.title.trim()?'':c.preview.replaceAll('\n',' ');return `<button class="clip-row ${active?'selected':''}" data-id="${c.id}" data-queue-index="${page==='stack'?visibleQueueIndices[index]:-1}" aria-label="${esc(c.title)}" aria-pressed="${active}"><span class="row-content"><span class="row-heading"><span class="row-kind">${page==='stack'?'<span class="queue-index">'+(visibleQueueIndices[index]+1)+'</span>':ico(c.kind)}</span><span class="row-title">${highlight(c.title)}</span><span class="row-flags">${c.pinned?ico('pin'):''}${c.favorite?ico('star'):''}</span></span>${summary?'<span class="row-preview">'+highlight(summary)+'</span>':''}<span class="row-meta"><span class="row-application">${appIdentity(c.source)}<span>${esc(c.source.replace(/\.exe$/i,''))}</span></span><span class="row-time">${time(c.updatedAt)}</span></span>${c.tags.length?'<span class="row-tags">'+c.tags.slice(0,2).map(tag=>'<span class="tag">'+esc(tag)+'</span>').join('')+'</span>':''}</span></button>`;}
function renderSourceFilters(){const root=q('source-filters');if(!root)return;root.hidden=page==='replies';if(root.hidden)return;const candidates=collectionItems(state.clips,clipsByID,page,state.queue,state.shelf,kind,matches).items,apps=new Map<string,{name:string;count:number}>();for(const clip of candidates){const key=sourceKey(clip.source),entry=apps.get(key);if(entry)entry.count++;else apps.set(key,{name:clip.source,count:1});}if(sourceApp&&!apps.has(sourceApp))sourceApp='';root.hidden=!candidates.length;if(root.hidden)return;const entries=[{key:':all',name:tr('全部应用'),count:candidates.length},...[...apps].sort((a,b)=>b[1].count-a[1].count||a[0].localeCompare(b[0])).map(([key,value])=>({key,...value}))];applicationSegments(root,entries,sourceApp||':all',key=>{sourceApp=key===':all'?'':key;limit=100;selected='';releaseDetail();renderCollection();requestAnimationFrame(()=>root.querySelector<HTMLElement>('[aria-selected=true]')?.focus());});}

function renderCollection(){if(!q('results'))return;const results=q('results'),restoreScroll=retainListScroll(results);const focusRow=(document.activeElement as HTMLElement)?.closest<HTMLElement>('.clip-row'),focusId=focusRow?.dataset.id,focusIndex=focusRow?.dataset.queueIndex;
  if(page==='stack'){const toggle=q('stack-running');if(toggle){setMarkup(toggle,ico(state.stack.running?'pause':'play')+'<span>'+(state.stack.running?tr('停止自动入栈'):tr('开始自动入栈'))+'</span>');toggle.setAttribute('aria-pressed',String(state.stack.running));}}
  const filters=q('filters'),filterbar=filters.closest<HTMLElement>('.filterbar')!,filterActions=q('filter-actions');filterbar.hidden=page==='replies';filterbar.classList.toggle('is-stack',page==='stack');filters.hidden=['stack','replies'].includes(page);filters.classList.toggle('tabs',!filters.hidden);
  keyedMarkup(filters,filters.hidden?[]:['all','text','image','files','link','code'].map(k=>({key:k,html:`<button class="filter ${kind===k?'active':''}" data-kind="${k}" aria-pressed="${kind===k}">${k==='all'?'':ico(k)}${labels[k]}</button>`})));
  filterActions.hidden=page!=='stack'||!state.queue.length;keyedMarkup(filterActions,filterActions.hidden?[]:[{key:':clear',html:ib('clear-queue',tr('清空堆栈'),'trash')}]);const pasteNext=q('paste-next');if(pasteNext)pasteNext.title=tr('粘贴下一项')+' · '+shortcut(state.settings.nextShortcut);
  filters.querySelectorAll<HTMLElement>('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind!;limit=100;renderCollection();});on('clear-queue',()=>confirm(tr('清空堆栈？'),state.stack.running?tr('只移出待粘贴项目，历史保留。自动入栈仍会继续。'):tr('只移出待粘贴项目，历史保留。'),()=>api.clearQueue()));
  const batchToggle=q('batch-mode');if(batchToggle){setMarkup(batchToggle,ico(batchMode?'close':'check'));batchToggle.classList.toggle('active',batchMode);batchToggle.setAttribute('aria-pressed',String(batchMode));batchToggle.title=batchMode?tr('退出批量选择'):tr('批量选择');batchToggle.setAttribute('aria-label',batchToggle.title);}
  if(page==='replies'){renderReplies();restoreScroll();renderBatch();return;}
  renderSourceFilters();
  const projection=collectionItems(state.clips,clipsByID,page,state.queue,state.shelf,kind,matches,sourceApp);visible=projection.items;visibleQueueIndices=projection.indices;if(page==='stack'&&(state.queue[selectedQueueIndex]!==selected||!visibleQueueIndices.includes(selectedQueueIndex)))selectedQueueIndex=visibleQueueIndices.find(i=>state.queue[i]===selected)??visibleQueueIndices[0]??-1;
  if(!visible.some(c=>c.id===selected))selected=visible[0]?.id||'';if(page==='stack'&&selectedQueueIndex<0)selectedQueueIndex=visibleQueueIndices[0]??-1;
  results.closest('.workspace')!.classList.toggle('is-empty',!visible.length);keyedMarkup(results,visible.length?[...visible.slice(0,limit).map((c,i)=>({key:page==='stack'?'slot:'+visibleQueueIndices[i]+'@'+c.id:'clip:'+c.id,html:batchMode?tr`<div class="clip-entry"><input type="checkbox" data-check="${c.id}" aria-label="选择 ${esc(c.title)}" ${checked.has(c.id)?'checked':''}>${row(c,i)}</div>`:row(c,i)})),...(visible.length>limit?[{key:':more',html:tr('<button id="load-more" class="load-more quiet">显示更多记录</button>')}]:[])]:[{key:':empty',html:empty(query?tr('没有找到相关内容'):page==='favorites'?tr('暂无收藏'):page==='stack'?tr('堆栈为空'):page==='shelf'?tr('容器为空'):categoryId()?tr('还没有符合分类的记录'):tr('暂无记录'),query?tr('换个关键词，或调整筛选条件'):page==='favorites'?tr('选中记录后，点击星标收藏'):page==='stack'?tr('在内容预览中，将记录加入堆栈'):page==='shelf'?tr('拖入文件或图片，或点击右上角添加文件'):categoryId()?tr('复制符合规则的内容，或编辑分类条件'):tr('在其他应用复制文字、图片或文件，记录会出现在这里'))}]);
  restoreScroll();if(focusId)results.querySelector<HTMLElement>(`[data-id="${focusId}"]${page==='stack'?`[data-queue-index="${focusIndex}"]`:''}`)?.focus({preventScroll:true});renderBatch();bindRows();void hydrateAppIcons(q('content'));on('load-more',()=>{limit+=100;renderCollection();});void renderDetail().catch(toast);
}
function empty(title:string,description:string){return `<div class="empty"><div class="empty-icon">${ico(query?'search':page==='stack'?'stack':page==='favorites'?'star':'clipboard')}</div><h2>${title}</h2><p>${description}</p></div>`;}
function selectRow(id:string,index=-1){selected=id;selectedQueueIndex=page==='stack'?index:-1;const root=q('results'),previous=root.querySelector<HTMLElement>('.clip-row.selected'),next=root.querySelector<HTMLElement>('[data-id="'+CSS.escape(id)+'"]'+(page==='stack'?'[data-queue-index="'+index+'"]':''));for(const node of new Set([previous,next]))if(node){const active=node===next;node.classList.toggle('selected',active);if(node.getAttribute('aria-pressed')!==String(active))node.setAttribute('aria-pressed',String(active));}void renderDetail().catch(toast);}
const boundRows=new WeakSet<HTMLElement>();
function bindRows(){const root=q('results');if(!boundRows.has(root)){boundRows.add(root);const row=(event:Event)=>event.target instanceof Element?event.target.closest<HTMLButtonElement>('.clip-row'):null;
 root.addEventListener('click',event=>{const button=row(event);if(button&&root.contains(button))selectRow(button.dataset.id!,Number(button.dataset.queueIndex));});
 root.addEventListener('dblclick',event=>{const button=row(event);if(button&&root.contains(button))void useSelected(true).catch(toast);});
 root.addEventListener('dragstart',event=>{const button=row(event),clip=button&&clipsByID.get(button.dataset.id!);if(button&&clip&&page!=='replies'&&['image','files'].includes(clip.kind)){event.preventDefault();api.drag(clip.id);}});
 root.addEventListener('change',event=>{const input=event.target;if(input instanceof HTMLInputElement&&input.matches('[data-check]')){input.checked?checked.add(input.dataset.check!):checked.delete(input.dataset.check!);renderBatch();}});
 }root.querySelectorAll<HTMLInputElement>('[data-check]').forEach(input=>input.checked=checked.has(input.dataset.check!));for(const button of root.querySelectorAll<HTMLButtonElement>('.clip-row')){const clip=clipsByID.get(button.dataset.id!),draggable=page!=='replies'&&!!clip&&['image','files'].includes(clip.kind);if(button.draggable!==draggable)button.draggable=draggable;}}
async function renderDetail(){if(!isWindowVisible())return;if(page==='replies'){await replyDetail();return;}const root=q('detail');if(!root)return;const key=currentDetailKey();if(detailRoot===root&&detailKey===key)return;const identity=previewIdentity(),retain=detailRoot===root&&renderedPreviewIdentity===identity&&!!retainedClip;if(!retain&&pendingPreview?.root===root&&pendingPreview.identity===identity)return;
  if(!retain){releaseDetail();root.innerHTML='<div class="preview-empty">'+ico('clipboard')+tr('<span>内容预览</span></div>');}if(!selected)return;const token=detailToken;let item:ClipPreview;
  if(retain)item=retainedClip!;else{const pending={root,identity};pendingPreview=pending;try{item=await api.preview(selected);}finally{if(pendingPreview===pending)pendingPreview=undefined;}}
  if(!isWindowVisible()||token!==detailToken||q('detail')!==root||previewIdentity()!==identity){if(item.imageURL)void api.releasePreview(item.imageURL).catch(()=>{});return;}item={...item,...clipsByID.get(selected)!};if(!retain)imageLease=item.imageURL;const reader=useTextReader(item.payload.text||'',item.kind==='code');
  const content=retain?'':item.kind==='image'&&!item.payload.png?tr('<div class="preview-empty"><span>原始图片已保留，可复制或另存。此格式暂不提供预览。</span></div>'):item.kind==='image'?tr`<div class="image-preview"><img src="${esc(item.imageURL)}" alt="剪贴板图片预览"></div>`:item.kind==='files'?`<div class="files-preview">${(item.payload.files||item.payload.attachments!.map(a=>a.name)).map(f=>`<div>${ico('files')}<span><strong>${esc(item.payload.attachments?f:f.split('\\').pop())}</strong><small>${item.payload.attachments?(item.payload.attachments.find(a=>a.name===f)!.directory?tr('已保存文件夹'):tr('已保存附件 · ')+bytes(item.payload.attachments.find(a=>a.name===f)!.bytes)):esc(f)}</small></span></div>`).join('')}</div>`:!item.payload.text&&item.payload.formats?.length?tr('<div class="preview-empty"><span>原始富文本已保留，可复制或在「格式与信息」中另存。</span></div>'):reader?'':`<pre class="text-preview ${item.kind==='code'?'code-preview':''}">${highlight(item.payload.text||'')}</pre>`;
  patchMarkup(root,tr`<div class="detail-top"><span class="preview-heading"><strong class="preview-title">${esc(item.title)}</strong><span class="detail-kind">${appIdentity(item.source)}${esc(item.source.replace(/\.exe$/i,''))}<span class="preview-kind">${ico(item.kind)}${labels[item.kind]}</span></span></span><div class="detail-tools">${(reader?ib('preview-wrap',tr('自动换行'),'text'):'')+ib('favorite',item.favorite?tr('取消收藏'):tr('收藏'),'star',item.favorite)}${ib('pin',item.pinned?tr('取消置顶'):tr('置顶'),'pin',item.pinned)}${ib('edit',tr('编辑内容和标签'),'edit')}${ib('delete',item.shared?tr('删除并同步撤回'):tr('删除记录'),'trash')}</div></div><div class="preview-body">${content}</div><div class="detail-meta"><button type="button" id="record-info-toggle" aria-expanded="false" aria-controls="record-info">记录信息 ${ico('down')}</button><div id="record-info" class="record-info" hidden><dl><dt>来源</dt><dd>${esc(item.source)}</dd><dt>最近复制</dt><dd>${formatDate(item.updatedAt,{dateStyle:'medium',timeStyle:'medium'})}</dd><dt>大小</dt><dd>${bytes(item.bytes)}${item.payload.html?tr(' · 含富文本'):''}</dd></dl><div class="tags">${item.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></div><div class="detail-actions"><div class="primary-actions">${button('paste',tr('粘贴'),'enter','primary')}${button('copy',tr('复制'),'copy')}</div><details class="detail-more"><summary>${tr('更多操作')}</summary><div class="secondary-actions">${page==='stack'?`${ib('queue-up',tr('上移'),'up')}${ib('queue-down',tr('下移'),'down')}${button('dequeue',tr('移出堆栈'),'close','quiet')}`:button('enqueue',state.queue.includes(item.id)&&!state.stack.options.duplicates?tr('已加入堆栈'):tr('加入堆栈'),'stack','quiet')}${item.payload.text?`${ib('plain',tr('复制纯文本'),'text')}${ib('split',tr('按行拆分到堆栈'),'list')}`:''}${ib('share-record',item.shared?tr('已共享'):item.kind==='files'?tr('共享文件副本'):tr('共享此条'),'link',!!item.shared)+ib('private-record',item.localOnly?tr('允许共享'):tr('设为仅本机'),'shield',!!item.localOnly)}${ib('save-reply',tr('存为快捷回复'),'replies')}${ib('content-info',tr('格式与信息'),'files')}${item.payload.png?ib('edit-image',tr('编辑图片'),'edit')+ib('ocr',tr('识别图片文字'),'text')+ib('export-image',tr('图片另存为'),'download'):''}${ib('shelf-item',page==='shelf'?tr('移出容器'):tr('加入拖拽容器'),page==='shelf'?'close':'files')}</div>${item.payload.text?'<div class="text-tool-actions">'+button('translate',tr('翻译'),'replies','quiet small')+button('summarize',tr('总结'),'text','quiet small')+button('run-script',tr('脚本'),'code','quiet small')+'</div>':''}</details></div>`,source=>detailLayout(source,false),retain?node=>node.classList.contains('preview-body'):undefined);bindDetailLayout(root);void hydrateAppIcons(root);
  if(q('share-record')){setActionDisabled(q<HTMLButtonElement>('share-record'),!!item.shared||!!item.localOnly);on('share-record',()=>api.syncShare(item.id));on('private-record',()=>modal(item.localOnly?tr('允许此内容共享？'):tr('设为仅本机？'),item.localOnly?tr('<p>取消限制后，可手动共享；再次复制时也遵守自动同步设置。</p>'):tr('<p>保留本机记录并撤回已共享的发布；再次复制相同内容也不会自动共享。其他设备的备份不受影响。</p>'),()=>api.syncLocal(item.id,!item.localOnly),item.localOnly?tr('允许共享'):tr('设为仅本机')));}
  on('record-info-toggle',()=>toggleRecordInfo(q('record-info'),q('record-info-toggle')));q('record-info-toggle').onkeydown=e=>{if(['Enter',' ','ArrowDown','ArrowUp'].includes(e.key))e.stopPropagation();};
  const act=(name:string,action:ClipAction)=>on(name,async()=>{if(page==='stack'&&['dequeue','up','down'].includes(action)){const index=selectedQueueIndex;await api.queueAction(index,item.id,action as 'dequeue'|'up'|'down',[...state.queue]);selectedQueueIndex=action==='dequeue'?index:Math.max(0,Math.min(state.queue.length-1,index+(action==='up'?-1:1)));}else await api.action(item.id,action);if(action==='delete')toast(tr('已删除记录'),true);else if(action==='enqueue')toast(tr('已加入堆栈'));else if(action==='split')toast(tr('已按行加入堆栈'));});act('favorite','favorite');act('pin','pin');act('delete','delete');act('enqueue','enqueue');act('dequeue','dequeue');act('queue-up','up');act('queue-down','down');act('split','split');on('translate',()=>tools.ai(item,'translate'));on('summarize',()=>tools.ai(item,'summarize'));on('run-script',()=>tools.script(item));
  if(!retain){disposeImagePreview=mountImagePreview(root);if(reader)showTextReader(item.payload.text||'',item.kind==='code');restorePreviewPosition();}retainedClip=item;renderedPreviewIdentity=identity;detailRoot=root;detailKey=currentDetailKey();on('copy',()=>performSelected(false));on('paste',()=>performSelected(true));on('plain',async()=>{await api.copy(item.id,false,true);toast(tr('已复制纯文本'));});on('edit',()=>editClip(item));on('save-reply',()=>advanced.editSnippet(undefined,item));on('content-info',()=>advanced.contentInfo(item.id));on('edit-image',()=>api.editImage(item.id));on('ocr',()=>advanced.ocr(item.id));on('export-image',async()=>{const result=await api.exportImage(item.id);if(result)toast(tr('已保存：')+result);});on('shelf-item',async()=>{await api.batch([item.id],page==='shelf'?'unshelf':'shelf');toast(page==='shelf'?tr('已移出容器'):tr('已加入拖拽容器'));});
}
function useSelected(paste:boolean){const button=q<HTMLButtonElement>(paste?'paste':'copy');return actions.run('clipboard',()=>performSelected(paste),button?[button]:[]);}
async function performSelected(paste:boolean){const id=selected,targetPage=page,term=query;if(!id)return;if(term){await runSearch();await api.rememberSearch(term);}if(targetPage==='replies'){await advanced.useSnippet(id,paste);return;}await api.copy(id,paste);if(!paste)toast(tr('已复制'));}
function renderReplies(){const list=state.snippets.filter(s=>(s.title+'\n'+s.text).toLowerCase().includes(query.toLowerCase()));if(!list.some(s=>s.id===selected))selected=list[0]?.id||'';q('results').closest('.workspace')!.classList.toggle('is-empty',!list.length);keyedMarkup(q('results'),list.length?list.map(s=>({key:'reply:'+s.id,html:`<button class="clip-row ${s.id===selected?'selected':''}" data-id="${s.id}" aria-label="${esc(s.title)}" aria-pressed="${s.id===selected}"><span class="row-content"><span class="row-heading"><span class="row-kind">${ico('replies')}</span><span class="row-title">${highlight(s.title)}</span></span><span class="row-preview">${highlight(s.text.slice(0,150)||tr`${labels[s.kind]}模板`)}</span><span class="row-meta"><span class="row-application">${ico(s.kind)}<span>${labels[s.kind]}</span>${s.shortcut?'<kbd>'+esc(shortcut(s.shortcut))+'</kbd>':''}</span><span class="row-time">${time(s.updatedAt)}</span></span></span></button>`})): [{key:':empty',html:empty(tr('暂无快捷回复'),tr('点击“新建回复”添加'))}]);bindRows();void replyDetail().catch(toast);}
async function replyDetail(){if(!isWindowVisible())return;const root=q('detail');if(!root)return;const key=currentDetailKey();if(detailRoot===root&&detailKey===key)return;const identity=previewIdentity(),retain=detailRoot===root&&renderedPreviewIdentity===identity&&!!retainedSnippet;if(!retain&&pendingPreview?.root===root&&pendingPreview.identity===identity)return;if(!retain)releaseDetail();const token=detailToken,id=selected;if(!id){q('detail').innerHTML='<div class="preview-empty">'+ico('replies')+tr('<span>回复预览</span></div>');return;}let s:SnippetPreview;if(retain)s=retainedSnippet!;else{const pending={root,identity};pendingPreview=pending;try{s=await api.snippetPreview(id);}finally{if(pendingPreview===pending)pendingPreview=undefined;}}if(!isWindowVisible()||token!==detailToken||q('detail')!==root||previewIdentity()!==identity){if(s.imageURL)void api.releasePreview(s.imageURL).catch(()=>{});return;}const {text:summaryText,...metadata}=state.snippets.find(item=>item.id===id)!;s={...s,...metadata};if(!retain)imageLease=s.imageURL;const reader=!!s.text&&useTextReader(s.text,s.kind==='code');const content=retain?'':s.payload.png?'<div class="image-preview"><img src="'+esc(s.imageURL)+tr('" alt="图片模板"></div>'):s.payload.attachments?'<pre class="text-preview">'+s.payload.attachments.map(a=>esc(a.name)+(a.directory?tr(' · 已保存文件夹'):tr(' · 已保存附件'))).join('\n')+'</pre>':s.payload.files?'<pre class="text-preview">'+esc(s.payload.files.join('\n'))+'</pre>':!s.text&&s.payload.formats?.length?tr('<div class="preview-empty"><span>原始内容已保留，可复制或粘贴使用。</span></div>'):reader?'':'<pre class="text-preview">'+esc(s.text)+'</pre>';patchMarkup(root,`<div class="detail-top"><span class="preview-heading"><strong class="preview-title">${esc(s.title)}</strong><span class="detail-kind">${ico(s.kind)}${labels[s.kind]}${s.shortcut?'<kbd>'+esc(shortcut(s.shortcut))+'</kbd>':''}</span></span><div class="detail-tools">${reader?ib('preview-wrap',tr('自动换行'),'text'):''}${ib('edit-reply',tr('编辑回复'),'edit')}${ib('delete-reply',tr('删除回复'),'trash')}</div></div><div class="preview-body">${content}</div><div class="detail-actions"><div class="primary-actions">${button('paste',tr('粘贴'),'enter','primary')}${button('copy',tr('复制'),'copy')}</div></div>`,source=>detailLayout(source,false),retain?node=>node.classList.contains('preview-body'):undefined);if(!retain){disposeImagePreview=mountImagePreview(root);if(reader)showTextReader(s.text,s.kind==='code');restorePreviewPosition();}retainedSnippet=s;renderedPreviewIdentity=identity;detailRoot=root;detailKey=currentDetailKey();on('copy',()=>performSelected(false));on('paste',()=>performSelected(true));on('edit-reply',()=>advanced.editSnippet(s));on('delete-reply',()=>confirm(tr('删除快捷回复？'),tr('删除后不可撤销。'),()=>api.removeSnippet(s.id)));}
function modal(title:string,body:string,onSave:()=>Promise<void>,save=tr('保存')){const dialog=q<HTMLDialogElement>('dialog');resetDialogMotion(dialog);dialog.classList.add('one-form-dialog');dialog.classList.add('one-dialog');dialog.innerHTML=`<form method="dialog">${dialogParts(title,body,`<button id="modal-cancel" type="button">${tr('取消')}</button><button class="primary" type="submit">${esc(save)}</button>`,true)}</form>`;modalLayout(dialog);const dismiss=()=>{if(!oneDialogDismissLocked(dialog))void closeDialog(dialog);};on('modal-close',dismiss);q('modal-close').setAttribute('type','button');on('modal-cancel',dismiss);const form=dialog.querySelector('form')!,saves=new ActionScope(),b=form.querySelector<HTMLButtonElement>('[type=submit]')!;form.onsubmit=e=>{e.preventDefault();if(b.disabled||!form.isConnected||dialog.querySelector('form')!==form)return;void saves.run('save',async()=>{await onSave();if(dialog.querySelector('form')===form)await closeDialog(dialog);},[b]).catch(e=>{if(!dialog.open||dialog.querySelector('form')!==form){toast(e);return;}q('modal-error').textContent=String((e as Error).message).replace(/^Error invoking remote method '[^']+': Error: /,'');});};dialog.oncancel=event=>{event.preventDefault();dismiss();};openOneDialog(dialog,dismiss);}
function editClip(item:ClipPreview){let initialText='';const editable=item.kind!=='image'&&item.kind!=='files'&&!!item.payload.text;modal(tr('编辑记录'),tr`${editable?tr`<label class="field">内容<textarea id="edit-text" rows="10">${esc(item.payload.text)}</textarea></label><p class="field-help">更改正文会保存为纯文本，原有富文本格式将移除。</p>`:''}<label class="field">标签<input id="edit-tags" value="${esc(item.tags.join(', '))}" placeholder="用逗号分隔，例如 工作, 灵感"></label>`,async()=>{await api.edit(item.id,editable?(q<HTMLTextAreaElement>('edit-text').value===initialText?item.payload.text!:q<HTMLTextAreaElement>('edit-text').value):'',q<HTMLInputElement>('edit-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean));toast(tr('已保存'));});if(editable){const input=q<HTMLTextAreaElement>('edit-text'),help=input.closest('label')!.nextElementSibling as HTMLElement;initialText=input.value;const update=()=>help.hidden=input.value===initialText||!item.payload.html&&!item.payload.rtf&&!item.payload.formats?.length;input.addEventListener('input',update);update();}}
function editReply(value?:Partial<Snippet>){return advanced.editSnippet(value);}
function confirm(title:string,description:string,fn:()=>Promise<void>,undo=false){modal(title,`<p>${description}</p>`,async()=>{await fn();toast(tr('操作完成'),undo);},tr('确认'));}
function switchField(id:string,checked:boolean,label:string){return `<label class="switch"><input id="${id}" type="checkbox" role="switch" aria-label="${label}" ${checked?'checked':''}><span></span></label>`;}
let disposeVersions:(()=>void)|undefined,settingsRevision=0;
let disposeUpdates:(()=>void)|undefined;
async function renderSettings(){const revision=++settingsRevision;disposeUpdates?.();disposeVersions?.();const s=state.settings;q('content').innerHTML=tr`<section class="settings-page"><div class="page-heading"><div><h1>设置</h1></div><span class="version"></span></div><div class="settings-scroll"><h2 class="section-label">外观</h2><div class="setting-row"><div><strong>主题</strong></div><div class="theme-modes" id="theme-options">${['system','light','dark'].map((t,i)=>`<button data-theme-choice="${t}" aria-pressed="${s.theme===t}" class="theme-choice" aria-label="${[tr('系统'),tr('浅色'),tr('深色')][i]}"><span class="theme-mini ${t}"><i></i><b></b><em></em></span><span>${[tr('系统'),tr('浅色'),tr('深色')][i]}</span></button>`).join('')}</div></div><div id="appearance-inline"></div><h2 class="section-label">界面语言</h2><div id="language-inline"></div><h2 class="section-label">桌面交互</h2><div id="desktop-inline"></div><div id="efficiency-inline"></div><h2 class="section-label">记录与隐私</h2><div class="setting-row"><div><strong>暂停自动记录</strong></div>${switchField('paused',s.paused,tr('暂停自动记录'))}</div><div class="setting-row"><div><strong>历史保留</strong><p>收藏、置顶、堆栈、容器和共享记录不受自动清理影响</p></div><div class="inline-fields"><label><input id="max-items" type="number" min="50" max="10000" value="${s.maxItems}">条</label><label><input id="retention" type="number" min="1" max="365" value="${s.retentionDays}">天</label></div></div><div class="setting-row align-top"><div><strong>排除应用</strong></div><textarea id="excluded-apps" rows="4" aria-label="排除应用" placeholder="每行一个进程名称，例如 bitwarden.exe">${esc(s.excludedApps.join('\n'))}</textarea></div><div class="setting-row"><div><span>开机启动</span></div>${switchField('launch-login',s.launchAtLogin,tr('开机启动'))}</div><h2 class="section-label">快捷键</h2>${[['shortcut',tr('打开主窗口')],['quickShortcut',tr('快速粘贴面板')],['nextShortcut',tr('粘贴堆栈下一项')]].map(([key,name])=>tr`<div class="setting-row"><label for="${key}">${name}</label><input class="hotkey-input" id="${key}" data-value="${esc(s[key as keyof Settings])}" value="${shortcut(s[key as 'shortcut'])}" readonly aria-label="${name}快捷键" title="点击后按下新的快捷键"></div>`).join('')}${state.hotkeyError?`<div class="warning">${esc(state.hotkeyError)}</div>`:''}</div></section>`;
  q('content').querySelector('.version')!.textContent='v'+APP_VERSION;const settingsRoot=q('content').querySelector<HTMLElement>('.settings-scroll')!,first=settingsRoot.firstElementChild!;
  const general=document.createElement('h2');general.className='section-label';general.textContent=tr('基本设置');settingsRoot.insertBefore(general,first);const launch=q('launch-login').closest<HTMLElement>('.setting-row')!;const language=q('language-inline');language.previousElementSibling?.remove();general.after(language,launch);
  const updateHeading=document.createElement('h2');updateHeading.className='section-label';updateHeading.textContent=tr('应用更新');const updatesRoot=document.createElement('div');updatesRoot.id='updates';settingsRoot.append(updateHeading,updatesRoot);disposeUpdates=mountUpdates(updatesRoot,toast);
  void languageUI(inlineSettings(q('language-inline'),toast)).catch(toast);void appearanceUI(inlineSettings(q('appearance-inline'),toast,true)).catch(toast);void desktopUI(inlineSettings(q('desktop-inline'),toast)).catch(toast);void efficiencyUI({...inlineSettings(q('efficiency-inline'),toast),reuse:()=>{}}).settings().catch(toast);bindSettingsPreferences(settingsRoot,s,toast);
  settingsRoot.querySelectorAll<HTMLInputElement>('.hotkey-input').forEach(input=>setupShortcut(input,toast));
  const dataMount=document.createElement('div');dataMount.className='settings-data-mount';settingsRoot.append(dataMount);const body=await dataPanel.render(dataMount,true);if(revision!==settingsRevision||page!=='settings'||!settingsRoot.isConnected)return;
  if(body){const nodes=Array.from(body.children);dataMount.replaceWith(...nodes);const storageStart=q('history-vault').previousElementSibling as HTMLElement;const storageCard=document.createElement('section');storageCard.className='settings-card';storageCard.innerHTML=tr`<div class="setting-row"><div><strong>${formatNumber(state.clips.length)} 条记录 · ${bytes(state.bytes)}</strong></div></div><div class="setting-row"><div><span>清除普通历史</span><p>保留收藏、置顶、堆栈、容器、共享记录和快捷回复，可撤销本次清除</p></div><button id="clear-history">清除历史</button></div>`;storageStart.after(storageCard);
   on('clear-history',()=>confirm(tr('清除普通历史？'),tr('只删除 Clipper 中的普通记录，源文件不受影响。收藏、置顶、堆栈和拖拽容器将保留。'),async()=>{await api.clear();await refresh();if(page==='settings')await renderSettings();},true));
   const versionsRoot=document.createElement('section');versionsRoot.className='program-versions settings-card';settingsRoot.append(versionsRoot);const versions=mountProgramVersions(versionsRoot,{toast,modal});disposeVersions=versions.dispose;const configure=(value:import('../shared/updates').UpdateState)=>versions.configure({installed:value.installed,current:value.current,busy:['checking','downloading','installing'].includes(value.phase)});void api.updateState().then(configure).catch(toast);const unsubscribe=api.onUpdate(configure);disposeVersions=()=>{unsubscribe?.();versions.dispose();};
  }
  const headings=Array.from(settingsRoot.querySelectorAll<HTMLElement>(':scope > .section-label,:scope > .tools-section-heading'));sectionLayout(settingsRoot,headings.map(h=>h.querySelector('h2')?.textContent||h.textContent!),headings,'settings-section-050',{icons:[Settings2,Palette,MousePointer2,ShieldCheck,Keyboard,Download,Database,Archive,History,RotateCcw],groups:[tr('常规'),tr('常规'),tr('交互'),tr('交互'),tr('交互'),tr('维护'),tr('数据'),tr('数据'),tr('数据'),tr('数据')]});

}
document.addEventListener('clipper:feedback',e=>toast((e as CustomEvent).detail));
document.addEventListener('keydown',e=>{
  if(e.isComposing||e.defaultPrevented)return;if(document.querySelector('dialog[open]'))return;const target=e.target as HTMLElement,editing=target.matches('input,textarea,select');
  if(e.key==='Escape'){if(document.querySelector('.reference-popover:not([hidden])'))return;e.preventDefault();void api.hide();return;}
  if(target.closest('.text-reader'))return;
  if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();(document.getElementById('reference-search')||document.getElementById('search'))?.focus();return;}
  if(target.closest('#toast')||(!editing&&target.closest('button,summary,[role=combobox]')&&!target.closest('.clip-row')))return;
  if(['settings','ai','scripts','uri','sync','web','symbols','cheats'].includes(page))return;
  if(e.ctrlKey&&e.key.toLowerCase()==='z'&&!editing){e.preventDefault();void api.undo().catch(toast);return;}
  if(editing&&target.id!=='search')return;
  if(e.key==='Enter'){e.preventDefault();void useSelected(!e.ctrlKey).catch(toast);}
  if(['ArrowDown','ArrowUp'].includes(e.key)&&page!=='replies'){e.preventDefault();const i=page==='stack'?visibleQueueIndices.indexOf(selectedQueueIndex):visible.findIndex(c=>c.id===selected),index=cardNavigation(i,visible.length,1,'vertical',e.key),next=visible[index];if(next){if(index>=limit){limit=Math.ceil((index+1)/100)*100;renderCollection();}selectRow(next.id,visibleQueueIndices[index]??-1);document.querySelector(`[data-id="${selected}"]${page==='stack'?`[data-queue-index="${selectedQueueIndex}"]`:''}`)?.scrollIntoView({block:'nearest'});}}
  if(e.key==='Delete'&&!editing&&selected&&page!=='replies'){e.preventDefault();void api.action(selected,'delete').then(()=>toast(tr('已删除记录'),true)).catch(toast);}
});
window.addEventListener('clipper:language-reload',()=>sessionStorage.setItem('clipper-language-navigation',JSON.stringify({page,kind,sourceApp,selected,query})));try{const saved=JSON.parse(sessionStorage.getItem('clipper-language-navigation')||'null');sessionStorage.removeItem('clipper-language-navigation');if(saved&&typeof saved.page==='string'){page=saved.page==='data'?'settings':saved.page==='tools'?'ai':saved.page;kind=saved.kind||'all';sourceApp=saved.sourceApp||'';selected=saved.selected||'';query=saved.query||'';}}catch{}
q<HTMLDialogElement>('dialog').addEventListener('close',()=>setTimeout(()=>checkExternal(),0));
let refreshScheduled:ReturnType<typeof setTimeout>|undefined,refreshPending=false;
function scheduleRefresh(){refreshPending=true;if(!state||!isWindowVisible()||refreshScheduled)return;refreshScheduled=setTimeout(()=>{refreshScheduled=undefined;if(!isWindowVisible())return;refreshPending=false;void refresh().catch(toast);},32);}
setupWindowVisibility();onWindowVisibility(shown=>{if(!state)return;if(shown)scheduleRefresh();else{clearTimeout(refreshScheduled);refreshScheduled=undefined;clearTimeout(searchTimer);refreshToken++;searchRevision++;closeControls();suspendDetail();}});
api.onChange(scheduleRefresh);api.onNotice(toast);
async function start(){state=await api.state();clipsByID=new Map(state.clips.map(c=>[c.id,c]));shell();render();checkExternal();if(refreshPending)scheduleRefresh();}
void start().catch(e=>{q('app').textContent=tr('Clipper 加载失败：')+String(e);});
