import {onRemoval} from './controls';
import {t as tr} from '../shared/i18n';
import {appearanceScales,defaultAppearance,validateAppearance,type UIAppearance} from '../shared/appearance';
import {applyAppearance} from './appearance';
import {setupFontPicker} from './font-picker';
import {icon} from './ui';
interface Context{active?():boolean;modal(title:string,body:string,onSave:()=>Promise<void>,save?:string):void;toast(value:unknown):void}
function appearancePage(){return tr`<div class="appearance-page"><div class="settings-card"><div class="appearance-row"><strong>强调色</strong><div class="swatch-list">${['#303030','#4479d8','#6d61bd','#41886c','#b67838','#b55875'].map(color=>`<button type="button" class="accent-swatch" data-color="${color}" style="--swatch:${color}" aria-label="${tr('强调色')} ${color}"></button>`).join('')}</div><span class="color-field"><i aria-hidden="true"></i><input id="appearance-accent" aria-label="自定义强调色" maxlength="7" spellcheck="false"></span></div><div class="appearance-row"><strong>背景</strong><span class="color-field"><i aria-hidden="true"></i><input id="appearance-bg" aria-label="背景颜色" maxlength="7" spellcheck="false"></span></div><div class="appearance-row"><strong>前景</strong><span class="color-field"><i aria-hidden="true"></i><input id="appearance-fg" aria-label="前景颜色" maxlength="7" spellcheck="false"></span></div></div><div class="settings-card"><div class="appearance-row"><strong>字体</strong><button type="button" id="appearance-font" class="custom-select" role="combobox" aria-label="界面字体" aria-haspopup="listbox" aria-expanded="false"><span>系统默认</span>${icon('chevron-down')}</button></div><div class="appearance-row"><strong>文字大小</strong><select id="appearance-scale" aria-label="文字大小">${appearanceScales.map(n=>`<option value="${n}">${n}%</option>`).join('')}</select></div><div class="appearance-row"><strong>间距</strong><select id="appearance-density" aria-label="界面间距"><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></div></div><div class="settings-card"><div class="appearance-row"><strong>提示位置</strong><select id="appearance-toastPosition" aria-label="提示位置"><option value="top-center">顶部中间</option><option value="top-right">顶部右侧</option><option value="top-left">顶部左侧</option><option value="bottom-center">底部中间</option><option value="bottom-right">底部右侧</option><option value="bottom-left">底部左侧</option></select></div><div class="appearance-row"><strong>圆角</strong><input type="range" id="appearance-radius" aria-label="界面圆角" min="4" max="16"><output id="radius-value"></output></div></div><div class="appearance-actions"><button type="button" id="appearance-reset">恢复默认选项</button></div></div>`;}

export async function appearanceUI(ctx:Context){const current=await window.clipperAppearance!.state(),q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;let value=validateAppearance(current.value);
 if(ctx.active&&!ctx.active())return;ctx.modal(tr('外观'),appearancePage(),async()=>{await window.clipper.configureAppearance(value);ctx.toast(tr('外观已保存'));});
 if(!q('appearance-font'))return;setupFontPicker(q<HTMLButtonElement>('appearance-font'));let saveRevision=0;
 const dark=()=>document.documentElement.dataset.theme==='dark';
 const fill=()=>{q<HTMLInputElement>('appearance-accent').value=value.accent;q<HTMLInputElement>('appearance-bg').value=dark()?value.darkBackground:value.lightBackground;q<HTMLInputElement>('appearance-fg').value=dark()?value.darkForeground:value.lightForeground;for(const key of ['font','scale','density','toastPosition','radius'])q<HTMLInputElement>('appearance-'+key).value=String(value[key as keyof UIAppearance]);q('radius-value').textContent=value.radius+' px';for(const key of ['accent','bg','fg']){const input=q<HTMLInputElement>('appearance-'+key);input.parentElement!.style.setProperty('--swatch',input.value);}};
 const persist=()=>{const request=++saveRevision;applyAppearance(value);void window.clipper.configureAppearance(value).catch(async error=>{if(request!==saveRevision)return;value=(await window.clipperAppearance!.state()).value;applyAppearance(value);if(q('appearance-font'))fill();ctx.toast(error);});};
 fill();if(current.warning)ctx.toast(current.warning);
 document.querySelectorAll<HTMLElement>('[data-color]').forEach(b=>b.onclick=()=>{value={...value,accent:b.dataset.color!};fill();persist();});
 for(const key of ['accent','bg','fg','font','scale','density','radius','toastPosition'])q('appearance-'+key).addEventListener('change',()=>{const input=q<HTMLInputElement>('appearance-'+key),raw=input.value;if(['accent','bg','fg'].includes(key)&&!/^#[a-f0-9]{6}$/i.test(raw)){ctx.toast(tr('请输入 #RRGGBB 格式颜色'));fill();return;}const property=key==='bg'?(dark()?'darkBackground':'lightBackground'):key==='fg'?(dark()?'darkForeground':'lightForeground'):key;value=validateAppearance({...value,[property]:key==='radius'||key==='scale'?Number(raw):raw});fill();persist();});
 q('appearance-reset').onclick=()=>{value=defaultAppearance();fill();persist();};
 const observer=new MutationObserver(()=>{if(q('appearance-font'))fill();else observer.disconnect();});observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});onRemoval(q('appearance-font'),()=>observer.disconnect());
}
