import {keyedMarkup} from './markup';
import {customControls,onRemoval} from './controls';
import {appIdentity,hydrateAppIcons} from './source-apps';
import {icon} from './ui';
import {t} from '../shared/i18n';
export interface SourceEntry{key:string;name:string;count:number}
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const controllers=new WeakMap<HTMLElement,{update(entries:SourceEntry[],selected:string,choose:(key:string)=>void):void}>();
/** One segments and select popup share a row. Resize keeps the selected app visible. */
export function applicationSegments(root:HTMLElement,entries:SourceEntry[],selected:string,choose:(key:string)=>void){
 let controller=controllers.get(root);if(!controller){let current:SourceEntry[]=[],active='',select:(key:string)=>void=()=>{},signature='',frame=0,compactAll=false;const widthKeys=new Map<string,string>(),widths=new Map<string,number>(),measure=document.createElement('div');measure.className='source-measure';measure.setAttribute('aria-hidden','true');document.body.append(measure);
  const html=(entry:SourceEntry)=>`<button class="source-segment quiet ${entry.key===':all'&&compactAll?'source-all-compact':''} ${active===entry.key?'selected':''}" role="tab" aria-label="${escape(entry.name.replace(/\.exe$/i,''))}" aria-selected="${active===entry.key}" data-source="${encodeURIComponent(entry.key)}">${entry.key===':all'?icon('lucide:app'):appIdentity(entry.name)}<span>${escape(entry.name.replace(/\.exe$/i,''))}</span><small>${entry.count}</small></button>`;
  const draw=()=>{frame=0;if(!root.isConnected)return;const parent=root.parentElement!,siblings=Array.from(parent.children).filter(node=>node!==root&&node.getClientRects().length),available=parent.clientWidth-siblings.reduce((sum,node)=>sum+node.getBoundingClientRect().width,0)-siblings.length*14,totalWidth=current.reduce((sum,entry)=>sum+(widths.get(entry.key)||100)+4,0)+6,width=Math.max(140,Math.min(available,totalWidth));if(!parent.clientWidth)return;root.style.width=width+'px';const all=current[0],visible:SourceEntry[]=[all];compactAll=active!==':all'&&width<(widths.get(all.key)||110)+(widths.get(active)||100)+44;let used=compactAll?34:widths.get(all.key)||110;root.style.setProperty('--app-label-max',Math.max(24,width-used-110)+'px');const selectedEntry=current.find(entry=>entry.key===active),ranked=current.slice(1);if(selectedEntry&&selectedEntry!==all){ranked.splice(ranked.indexOf(selectedEntry),1);ranked.unshift(selectedEntry);}
   // Reserve a dropdown until all applications are known to fit.
   const total=current.reduce((sum,entry)=>sum+(widths.get(entry.key)||100)+4,0);const budget=width-(total>width?36:0)-6;
   for(const entry of ranked){const size=(widths.get(entry.key)||100)+4;if(used+size<=budget){visible.push(entry);used+=size;}}
   if(selectedEntry&&selectedEntry!==all&&!visible.includes(selectedEntry)){if(visible.length>1)visible.splice(visible.length-1,1);visible.push(selectedEntry);}
   const hidden=current.filter(entry=>!visible.includes(entry)),key=JSON.stringify([visible.map(entry=>[entry.key,entry.name,entry.count]),hidden.map(entry=>[entry.key,entry.name,entry.count]),active,compactAll]);if(key===signature)return;signature=key;
   keyedMarkup(root,[...visible.map(entry=>({key:entry.key,html:html(entry)})),...(hidden.length?[{key:':overflow',html:`<span class="source-overflow"><select id="source-overflow" aria-label="${t('更多应用')}">${hidden.map(entry=>`<option value="${encodeURIComponent(entry.key)}" data-source-app="${escape(entry.name)}">${escape(entry.name.replace(/\.exe$/i,''))} · ${entry.count}</option>`).join('')}</select></span>`}]:[])]);
   for(const button of root.querySelectorAll<HTMLButtonElement>('[data-source]'))button.onclick=()=>select(decodeURIComponent(button.dataset.source!));
   const overflow=root.querySelector<HTMLSelectElement>('#source-overflow');if(overflow){overflow.selectedIndex=-1;overflow.onchange=()=>select(decodeURIComponent(overflow.value));customControls(root);const trigger=root.querySelector<HTMLButtonElement>('#source-overflow-trigger')!;trigger.classList.add('source-overflow-trigger');trigger.title=t('更多应用');}
   void hydrateAppIcons(root);
  };
  const schedule=()=>{if(!frame)frame=requestAnimationFrame(draw);},observer=new ResizeObserver(schedule);observer.observe(root.parentElement!);const fonts=()=>{widthKeys.clear();widths.clear();controller?.update(current,active,select);signature='';schedule();};document.fonts.addEventListener('loadingdone',fonts);onRemoval(root,()=>{observer.disconnect();cancelAnimationFrame(frame);measure.remove();document.fonts.removeEventListener('loadingdone',fonts);});
  controller={update(entries,selected,choose){current=entries;active=selected;select=choose;const font=getComputedStyle(root).font+document.documentElement.dataset.textScale+getComputedStyle(root).getPropertyValue('--text-scale'),changed=entries.filter(entry=>widthKeys.get(entry.key)!==JSON.stringify([entry.name,String(entry.count).length,font]));measure.innerHTML=changed.map(entry=>html(entry).replace(/\sdata-source="[^"]*"/,'').replace(/\srole="tab"/,'').replace(/\saria-selected="[^"]*"/,'')).join('');Array.from(measure.children).forEach((node,index)=>{const entry=changed[index];widths.set(entry.key,node.getBoundingClientRect().width);widthKeys.set(entry.key,JSON.stringify([entry.name,String(entry.count).length,font]));});for(const key of widthKeys.keys())if(!entries.some(entry=>entry.key===key)){widthKeys.delete(key);widths.delete(key);}schedule();}};controllers.set(root,controller);
 }controller.update(entries,selected,choose);
}
