import {createElement,Folder,Briefcase,Bookmark,Star,Pin,Heart,Tag,House,Code,Image,Music,Film,BookOpen,Key,LockKeyhole,Palette,GraduationCap,Lightbulb,Globe,Coffee,Wallet,Gift,Calendar,Clipboard,FileText,ChartNoAxesCombined,Box,ShoppingBag,Plane,Gamepad2,Sparkles,type IconNode} from 'lucide';
import type {CategoryIcon} from '../shared/category-icons';
import {t} from '../shared/i18n';

const nodes:Partial<Record<CategoryIcon,IconNode>>={folder:Folder,briefcase:Briefcase,bookmark:Bookmark,star:Star,pin:Pin,heart:Heart,tag:Tag,house:House,code:Code,image:Image,music:Music,film:Film,'book-open':BookOpen,key:Key,'lock-keyhole':LockKeyhole,palette:Palette,'graduation-cap':GraduationCap,lightbulb:Lightbulb,globe:Globe,coffee:Coffee,wallet:Wallet,gift:Gift,calendar:Calendar,clipboard:Clipboard,'file-text':FileText,'chart-no-axes-combined':ChartNoAxesCombined,box:Box,'shopping-bag':ShoppingBag,plane:Plane,'gamepad-2':Gamepad2,sparkles:Sparkles};
const cache=new Map<CategoryIcon,string>();
let catalog:Promise<void>|undefined;
export function loadCategoryGlyphs(){return catalog??=import(new URL('category-icon-catalog.js',location.href).href).then(module=>{Object.assign(nodes,module.categoryCatalog);}).catch(error=>{catalog=undefined;throw error;});}
export function categoryGlyph(name?:CategoryIcon){const key=name||'folder';let markup=cache.get(key);if(!markup){markup=createElement(nodes[key]||Folder,{'class':'icon','aria-hidden':'true',focusable:'false','stroke-width':1.75,'data-category-glyph':key,...(!nodes[key]?{'data-category-loading':'true'}:{})}).outerHTML;if(nodes[key])cache.set(key,markup);}return markup;}
export function hydrateCategoryGlyphs(root:HTMLElement){if(!root.querySelector('[data-category-loading]'))return;void loadCategoryGlyphs().then(()=>{if(!root.isConnected)return;for(const node of root.querySelectorAll<SVGElement>('[data-category-loading]'))node.outerHTML=categoryGlyph(node.dataset.categoryGlyph as CategoryIcon);}).catch(error=>document.dispatchEvent(new CustomEvent('clip:feedback',{detail:error.message})));}
export function categoryIconNames():Partial<Record<CategoryIcon,string>>{return {folder:t('文件夹'),briefcase:t('公文包'),bookmark:t('书签'),star:t('星标'),pin:t('置顶'),heart:t('爱心'),tag:t('标签'),house:t('主页'),code:t('代码'),image:t('图片'),music:t('音乐'),film:t('影片'),'book-open':t('书籍'),key:t('钥匙'),'lock-keyhole':t('锁'),palette:t('调色板'),'graduation-cap':t('学习'),lightbulb:t('灵感'),globe:t('网络'),coffee:t('咖啡'),wallet:t('钱包'),gift:t('礼物'),calendar:t('日历'),clipboard:t('剪贴板'),'file-text':t('文档'),'chart-no-axes-combined':t('图表'),box:t('收纳盒'),'shopping-bag':t('购物'),plane:t('旅行'),'gamepad-2':t('游戏'),sparkles:t('闪光')};}

export function categoryIconLabel(name:CategoryIcon){return categoryIconNames()[name]||name.replace(/-/g,' ').replace(/\b\w/g,char=>char.toUpperCase());}
