import './locale';
import './appearance';
import './chat.css';
import {chatMarkdown as markdown} from './chat-markdown';
import {Sparkles,Plus,X,ArrowUp,Paperclip,Clipboard,PanelLeft,Copy,CornerDownLeft,Bookmark,ChevronDown,Trash2,Pencil,Image,FileText,RefreshCw,Check,Pin,SquareMousePointer} from 'lucide';
import {t as tr,formatDate} from '../shared/i18n';
import {emptyChatDraft,chatImages,type ChatAPI,type ChatState,type ChatDraft,type ChatMessage,type ChatEvent} from '../shared/chat';
import {aiEndpoint,aiModelsFor,aiReasoningEfforts,reasoningLabel} from '../shared/text-tools';
import {modelPicker} from './model-picker';
import {registerIcons,icon,iconButton,q} from './ui';
import {customControls,closeControls} from './controls';
import {openAnchoredPopover,closeAnchoredPopover} from './anchored-popover';
import {keyedMarkup,clearMarkup,patchMarkup} from './markup';
import {windowCloseButton} from './chrome';
declare global{interface Window{clipperChat:ChatAPI}}
const api=window.clipperChat,esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
registerIcons({sparkles:Sparkles,plus:Plus,close:X,send:ArrowUp,attach:Paperclip,clipboard:Clipboard,sidebar:PanelLeft,copy:Copy,paste:CornerDownLeft,save:Bookmark,down:ChevronDown,trash:Trash2,rename:Pencil,image:Image,text:FileText,retry:RefreshCw,check:Check,pin:Pin,keep:SquareMousePointer});
const ib=(id:string,label:string,glyph:string)=>iconButton(id,tr(label),'lucide:'+glyph);
let state:ChatState|undefined,draft:ChatDraft=emptyChatDraft(),profileId='',submitting=false,loading=0,dirty=false,draftTimer:ReturnType<typeof setTimeout>|undefined,saving=Promise.resolve(),popup:HTMLElement|undefined,composing=false,autoScroll=true,smoothScrolling=false;
const input=q<HTMLTextAreaElement>('chat-input');
function status(error:unknown){const text=String(error instanceof Error?error.message:error).replace(/^Error invoking remote method '[^']+': Error: /,'');q('chat-status').textContent=text;q('chat-status').hidden=!text;}
function run(fn:()=>Promise<unknown>){void fn().catch(error=>{status(error);if(!state){q('chat-messages').innerHTML=`<div class="chat-initial-loading" role="status"><span>${tr('加载失败，请重试')}</span><button id="chat-load-retry" class="quiet">${tr('重试')}</button></div>`;q('chat-load-retry').onclick=()=>run(async()=>{await refresh(undefined,true);input.focus();});}});}
function profile(){return state?.profiles.find(value=>value.id===profileId);}
function running(){return state?.conversation.messages.some(message=>message.status==='running')||false;}
function buttons(){const p=profile(),working=running(),send=q<HTMLButtonElement>('chat-send'),buttonState=working?'running':'idle';send.disabled=submitting||!state||!working&&(!p||!draft.text.trim()&&!draft.images.length);if(send.dataset.state!==buttonState){send.dataset.state=buttonState;send.innerHTML=working?'<span class="chat-stop-mark" aria-hidden="true"></span>':icon('lucide:send');}const scroll=q('chat-scroll-bottom');if(scroll.dataset.state!==buttonState){scroll.dataset.state=buttonState;scroll.innerHTML=working?'<span class="chat-working" aria-hidden="true"><i></i><i></i><i></i></span>':icon('lucide:down');}send.setAttribute('aria-label',tr(working?'停止生成':'发送消息'));send.title=tr(working?'停止生成':'发送消息');input.disabled=submitting||!state;for(const id of ['chat-history-toggle','chat-new','chat-pin','chat-keep','chat-attach','chat-reference'])q<HTMLButtonElement>(id).disabled=!state;picker.update();q('chat-pin').setAttribute('aria-pressed',String(state?.options.onTop??true));q('chat-keep').setAttribute('aria-pressed',String(state?.options.keepOpen??true));}
function sizeInput(){input.style.height='0';input.style.height=Math.min(150,Math.max(60,input.scrollHeight))+'px';}
function markDirty(){dirty=true;clearTimeout(draftTimer);draftTimer=setTimeout(()=>run(flushDraft),400);buttons();}
async function flushDraft(){clearTimeout(draftTimer);if(dirty&&state){dirty=false;const id=state.conversation.id,value=structuredClone(draft),selected=profileId;saving=saving.catch(()=>{}).then(()=>api.draft(id,value,selected));}await saving;}
function attachments(){q('chat-attachments').hidden=!draft.images.length;keyedMarkup(q('chat-attachments'),draft.images.map((image,index)=>({key:String(index)+image.png.slice(-20),html:`<div class="chat-attachment"><img src="data:image/png;base64,${image.png}" alt="${esc(image.name)}">${ib('remove-image-'+index,tr('移除图片'),'close')}</div>`})));q('chat-attachments').querySelectorAll<HTMLButtonElement>('button').forEach((button,index)=>button.onclick=()=>{draft.images.splice(index,1);attachments();markDirty();});}
function restoreDraft(){draft=structuredClone(state!.conversation.draft);draft.commandId='';draft.values={};input.value=draft.text;attachments();sizeInput();buttons();}
function selectedOptions(){if(!state)return;profileId=state.profiles.some(p=>p.id===profileId)?profileId:state.profiles.find(p=>p.id===state!.conversation.profileId)?.id||state.defaultId||state.profiles[0]?.id||'';const p=profile(),models=p?aiModelsFor(p):[];if(!models.some(model=>model.id===draft.modelId))draft.modelId=models.find(model=>model.id===p?.model)?.id??models[0]?.id;const efforts=p?aiReasoningEfforts(p,draft.modelId):[];if(draft.reasoningEffort===undefined||draft.reasoningEffort&&!efforts.includes(draft.reasoningEffort))draft.reasoningEffort=efforts.includes(p?.reasoningEffort||'')?p!.reasoningEffort:'';const select=q<HTMLSelectElement>('chat-reasoning');select.hidden=p?.kind!=='codex';const options=[{value:'',label:reasoningLabel('')},...efforts.map(value=>({value,label:reasoningLabel(value)}))];if(JSON.stringify(options)!==select.dataset.options){select.dataset.options=JSON.stringify(options);select.dispatchEvent(new CustomEvent('one:options',{detail:options}));}select.value=draft.reasoningEffort||'';picker.update();}
function messageHTML(message:ChatMessage,index:number){
 const answer=message.role==='assistant',working=message.status==='running',images=message.images?.map((image,i)=>`<img data-view-image="${message.id}:${i}" src="data:image/png;base64,${image.png}" alt="${esc(image.name)}" tabindex="0" role="button">`).join('')||'';
 const retry=answer&&index===state!.conversation.messages.length-1&&['failed','cancelled'].includes(message.status);
 const body=answer?message.text?markdown(message.text):working?'':esc(message.text):esc(message.text);
 const actions=answer&&message.status==='complete'?ib('copy-'+message.id,tr('复制回复'),'copy')+ib('paste-'+message.id,tr('粘贴到原窗口'),'paste')+ib('save-'+message.id,tr('保存为记录'),'save'):!answer&&message.text.trim()?ib('copy-'+message.id,tr('复制消息'),'copy'):retry?`<button data-retry="${message.id}" class="quiet small">${icon('lucide:retry')}${tr('重试')}</button>`:'';
 return `<article class="chat-message" data-message-id="${message.id}" data-role="${message.role}" data-status="${message.status}">${answer?`<div class="message-caption">${icon('lucide:sparkles')}<span>${esc(message.model||state!.profiles.find(p=>p.id===message.profileId)?.name||tr('AI'))}</span></div>`:message.commandTitle?`<div class="message-caption">${esc(message.commandTitle)}</div>`:''}${images?`<div class="message-images">${images}</div>`:''}${answer||message.text.trim()?`<div class="message-body ${answer?'markdown':''}">${body}</div>`:''}${working?`<span class="chat-working" aria-label="${tr('正在生成')}"><i></i><i></i><i></i></span>`:''}${message.error?`<div class="message-error">${esc(message.error)}</div>`:''}${actions?`<div class="message-actions">${actions}</div>`:''}</article>`;
}
function scrollBottom(behavior:ScrollBehavior='instant'){const host=q('chat-messages');smoothScrolling=behavior==='smooth'&&!matchMedia('(prefers-reduced-motion: reduce)').matches;autoScroll=true;q('chat-scroll-bottom').hidden=true;host.scrollTo({top:host.scrollHeight,behavior:smoothScrolling?'smooth':'instant'});}
function followLatest(){if(autoScroll&&!smoothScrolling)requestAnimationFrame(()=>{if(autoScroll&&!smoothScrolling)scrollBottom();});}
function renderMessages(){const host=q('chat-messages'),messages=state!.conversation.messages;if(!messages.length){clearMarkup(host);host.innerHTML=`<div class="chat-empty"><h1>${tr('有什么想问的？')}</h1></div>`;}else keyedMarkup(host,messages.map((message,index)=>({key:message.id,html:messageHTML(message,index)})));
 host.setAttribute('aria-busy',String(running()));host.querySelectorAll<HTMLButtonElement>('[id^=paste-]').forEach(button=>button.disabled=!state!.canPaste);followLatest();buttons();}
function history(){if(!state)return;const text=q<HTMLInputElement>('history-search').value.trim().toLowerCase();keyedMarkup(q('history-items'),state.history.filter(item=>item.title.toLowerCase().includes(text)).map(item=>({key:item.id,html:`<div class="chat-history-item ${item.id===state!.conversation.id?'active':''}"><button class="quiet" data-conversation="${item.id}"><strong>${esc(item.title)}</strong><small>${item.running?tr('正在生成')+' · ':''}${esc(formatDate(item.updatedAt,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</small></button><div class="chat-history-actions">${ib('rename-chat-'+item.id,tr('重命名对话'),'rename')}${ib('delete-chat-'+item.id,tr('删除对话'),'trash')}</div></div>`})));}
async function refresh(id?:string,reset=false){const serial=++loading,next=await api.state(id);if(serial!==loading)return;const changed=next.conversation.id!==state?.conversation.id;state=next;delete document.body.dataset.loading;q('chat-reasoning').closest('label')!.hidden=false;document.documentElement.dataset.theme=next.dark?'dark':'light';if(changed){dirty=false;profileId=next.conversation.profileId;autoScroll=true;smoothScrolling=false;}if(changed||reset)restoreDraft();selectedOptions();renderMessages();history();buttons();q('chat-history').hidden=!next.sidebarOpen;q('chat-history-toggle').setAttribute('aria-pressed',String(next.sidebarOpen));}
const streamRenders=new Map<string,ReturnType<typeof setTimeout>>();
function renderStream(message:ChatMessage){
 if(streamRenders.has(message.id)||document.hidden)return;
 streamRenders.set(message.id,setTimeout(()=>{streamRenders.delete(message.id);const node=document.querySelector<HTMLElement>(`[data-message-id="${message.id}"] .message-body`);const current=state?.conversation.messages.find(value=>value.id===message.id);if(!node||current?.status!=='running')return;
  const selection=window.getSelection();if(selection&&!selection.isCollapsed&&node.contains(selection.anchorNode)){renderStream(message);return;}
  patchMarkup(node,markdown(current.text));followLatest();
 },80));
}
function event(value:ChatEvent){if(value.type==='changed'){run(()=>refresh());return;}if(!state||value.conversationId!==state.conversation.id)return;const message=state.conversation.messages.find(m=>m.id===value.messageId);if(!message||message.status!=='running')return;if(message.text.length<value.offset){run(()=>refresh());return;}if(message.text.length<value.offset+value.delta.length)message.text+=value.delta.slice(message.text.length-value.offset);renderStream(message);}
function closePopup(){picker.close();if(popup){const panel=popup;popup=undefined;closeAnchoredPopover(panel);setTimeout(()=>panel.remove(),160);}}
function openPopup(anchor:HTMLElement,html:string,width=320){closePopup();closeControls();const panel=document.createElement('div');panel.className='chat-popup';panel.setAttribute('role','region');panel.innerHTML=html;document.body.append(panel);popup=panel;openAnchoredPopover(panel,anchor,width,450);return panel;}
document.addEventListener('pointerdown',event=>{if(popup&&!popup.contains(event.target as Node)&&!(event.target as HTMLElement).closest('#chat-reference'))closePopup();});
function renameConversation(anchor:HTMLElement,id:string){const item=state?.history.find(item=>item.id===id);if(!item)return;const panel=openPopup(anchor,`<h2>${tr('重命名对话')}</h2><label class="field">${tr('对话名称')}<input id="chat-rename-title" maxlength="120" value="${esc(item.title)}"></label><div class="popup-actions"><button id="chat-rename-cancel" class="quiet">${tr('取消')}</button><button id="chat-rename-save" class="primary">${tr('保存')}</button></div>`,280),field=panel.querySelector<HTMLInputElement>('input')!,save=panel.querySelector<HTMLButtonElement>('#chat-rename-save')!;save.disabled=!field.value.trim();field.oninput=()=>save.disabled=!field.value.trim();save.onclick=()=>run(async()=>{save.disabled=true;try{await api.rename(id,field.value);closePopup();await refresh();}finally{save.disabled=false;}});panel.querySelector<HTMLButtonElement>('#chat-rename-cancel')!.onclick=()=>closePopup();field.onkeydown=event=>{if(event.key==='Enter'&&!event.isComposing){event.preventDefault();if(!save.disabled)save.click();}};field.focus();field.select();}
async function addImages(images:import('../shared/chat').ChatImage[]){draft.images=chatImages([...draft.images,...images]);attachments();markDirty();input.focus();}
async function reference(){const panel=openPopup(q('chat-reference'),`<h2>${tr('引用剪贴板记录')}</h2><input id="record-search" type="search" aria-label="${tr('搜索记录')}" placeholder="${tr('搜索记录')}"><div id="record-choices"></div>`);panel.classList.add('chat-record-picker');const items=await api.records();if(popup!==panel)return;const search=panel.querySelector<HTMLInputElement>('input')!,list=panel.querySelector<HTMLElement>('#record-choices')!;const render=()=>{list.innerHTML=items.filter(item=>item.title.toLowerCase().includes(search.value.toLowerCase())).map(item=>`<button class="quiet chat-record" data-record="${item.id}">${icon('lucide:'+(item.kind==='image'?'image':'text'))}<span class="chat-record-copy"><strong>${esc(item.title)}</strong><small>${esc(item.source||tr(item.kind==='image'?'图片':'文字'))}</small></span></button>`).join('')||`<p>${tr('没有可引用的记录')}</p>`;list.querySelectorAll<HTMLButtonElement>('[data-record]').forEach(button=>button.onclick=()=>run(async()=>{const value=await api.record(button.dataset.record!);const text=[draft.text,value.text].filter(Boolean).join('\n\n');if(new TextEncoder().encode(text).length>256*1024)throw new Error(tr('引用文字过长'));const images=chatImages([...draft.images,...value.images]);draft.text=text;draft.images=images;input.value=text;attachments();sizeInput();markDirty();closePopup();input.focus();}));};search.oninput=render;render();search.focus();}
async function send(){if(!state||submitting)return;if(running()){await api.cancel(state.conversation.id);return;}const p=profile();if(!p)return;submitting=true;buttons();const original=structuredClone(draft),id=state.conversation.id;
 try{await flushDraft();await api.send({conversationId:id,profileId:p.id,revision:p.revision,approvedDestination:aiEndpoint(p),text:draft.text,images:draft.images,language:draft.language,modelId:draft.modelId,reasoningEffort:draft.reasoningEffort});draft={...emptyChatDraft(),modelId:draft.modelId,reasoningEffort:draft.reasoningEffort};input.value='';attachments();sizeInput();status('');autoScroll=true;await refresh();}catch(error){draft=original;status(error);}finally{submitting=false;buttons();input.focus();}}
q('chat-sidebar-control').innerHTML=ib('chat-history-toggle',tr('历史对话'),'sidebar');q('chat-header-actions').innerHTML=ib('chat-new',tr('新建对话'),'plus')+'<span class="chat-header-divider" role="separator" aria-orientation="vertical"></span>'+ib('chat-pin',tr('置顶窗口'),'pin')+ib('chat-keep',tr('保持窗口（失去焦点仍保留）'),'keep')+windowCloseButton('chat',tr('收起窗口'));q('chat-scroll-bottom').innerHTML=icon('lucide:down');q('chat-input-tools').innerHTML=ib('chat-attach',tr('添加图片'),'attach')+ib('chat-reference',tr('引用剪贴板记录'),'clipboard');
q('chat-pin').onclick=()=>run(async()=>{if(state)await api.configure({onTop:!state.options.onTop});});q('chat-keep').onclick=()=>run(async()=>{if(state)await api.configure({keepOpen:!state.options.keepOpen});});
q('chat-profile-trigger').insertAdjacentHTML('beforeend',icon('lucide:down'));
const picker=modelPicker(q<HTMLButtonElement>('chat-profile-trigger'),()=>({profiles:state?.profiles||[],profileId,modelId:draft.modelId||''}),(id,modelId)=>{const changed=profileId!==id;profileId=id;draft.modelId=modelId;if(changed)draft.reasoningEffort=undefined;selectedOptions();markDirty();},async id=>{const models=await api.models(id,crypto.randomUUID());const p=state?.profiles.find(p=>p.id===id);if(p)p.models=models;selectedOptions();});
q<HTMLSelectElement>('chat-reasoning').innerHTML=`<option value="">${reasoningLabel('')}</option>`;customControls(document.body);
q('chat-new').onclick=()=>run(async()=>{await flushDraft();closePopup();await refresh(await api.create(),true);input.focus();});
async function toggleHistory(open=!state?.sidebarOpen){const button=q<HTMLButtonElement>('chat-history-toggle'),conversation=document.querySelector<HTMLElement>('.chat-conversation')!;button.disabled=true;const width=conversation.getBoundingClientRect().width;conversation.style.flex='0 0 '+width+'px';q('chat-history').hidden=!open;button.setAttribute('aria-pressed',String(open));history();try{await api.sidebar(open);}finally{conversation.style.flex='';button.disabled=false;await refresh();}}
q('chat-history-toggle').onclick=()=>run(()=>toggleHistory());q<HTMLInputElement>('history-search').oninput=history;
q('history-items').onclick=event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;run(async()=>{await flushDraft();if(button.dataset.conversation){await refresh(button.dataset.conversation,true);input.focus();}else if(button.id.startsWith('rename-chat-'))renameConversation(button,button.id.slice(12));else if(button.id.startsWith('delete-chat-')){await api.remove(button.id.slice(12));await refresh();}});};
q('chat-close').onclick=()=>run(async()=>{await flushDraft();await api.hide();});q('chat-send').onclick=()=>run(send);q('chat-scroll-bottom').onclick=()=>scrollBottom('smooth');q('chat-attach').onclick=()=>run(async()=>addImages(await api.chooseImages()));q('chat-reference').onclick=()=>run(reference);
q<HTMLSelectElement>('chat-reasoning').onchange=event=>{draft.reasoningEffort=(event.target as HTMLSelectElement).value;markDirty();};
q('chat-messages').onclick=event=>{const target=event.target as HTMLElement,button=target.closest<HTMLButtonElement>('button'),image=target.closest<HTMLImageElement>('[data-view-image]'),link=target.closest<HTMLAnchorElement>('a');if(link){event.preventDefault();run(()=>api.openURL(link.href));return;}if(image){const dialog=document.createElement('dialog');dialog.className='chat-image-dialog';dialog.innerHTML=ib('image-close',tr('关闭'),'close')+`<img src="${image.src}" alt="${esc(image.alt)}">`;document.body.append(dialog);dialog.querySelector('button')!.onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();return;}if(!button||!state)return;if(button.hasAttribute('data-copy-code')){run(async()=>{await api.copyText(button.closest('.chat-code')!.querySelector('code')!.textContent!);button.innerHTML=icon('lucide:check');setTimeout(()=>{if(button.isConnected)button.innerHTML=icon('lucide:copy');},1200);});return;}if(button.dataset.retry)run(async()=>{const p=profile();if(!p)throw new Error(tr('请选择 AI 服务'));await flushDraft();await api.retry(state!.conversation.id,p.id,p.revision,aiEndpoint(p),{modelId:draft.modelId,reasoningEffort:draft.reasoningEffort});});else for(const mode of ['copy','paste','save'] as const)if(button.id.startsWith(mode+'-'))run(async()=>{await api.apply(state!.conversation.id,button.id.slice(mode.length+1),mode);button.innerHTML=icon('lucide:check');setTimeout(()=>{if(button.isConnected)button.innerHTML=icon('lucide:'+mode);},1200);});};
input.oninput=()=>{draft.text=input.value;sizeInput();markDirty();};input.addEventListener('compositionstart',()=>composing=true);input.addEventListener('compositionend',()=>composing=false);
input.onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&!composing&&event.keyCode!==229){event.preventDefault();if(!running())run(send);}};
input.addEventListener('paste',event=>{const files=Array.from(event.clipboardData?.files||[]).filter(file=>file.type.startsWith('image/'));if(files.length){event.preventDefault();run(async()=>{const images=[];for(const file of files)images.push(await api.image(await dataURL(file),file.name||tr('粘贴的图片')));await addImages(images);});}});
const dataURL=(file:File)=>new Promise<string>((resolve,reject)=>{if(file.size>16*1024*1024){reject(new Error(tr('图片超过 16 MiB')));return;}const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error(tr('图片无法读取')));reader.readAsDataURL(file);});
q('chat-composer').addEventListener('dragover',event=>{event.preventDefault();});q('chat-composer').addEventListener('drop',event=>{event.preventDefault();const files=Array.from(event.dataTransfer?.files||[]);run(async()=>{if(!files.length||files.length>4||files.some(file=>!file.type.startsWith('image/')))throw new Error(tr('请拖入最多 4 张图片'));const images=[];for(const file of files)images.push(await api.image(await dataURL(file),file.name));await addImages(images);});});
q('chat-messages').onscroll=()=>{if(smoothScrolling)return;const host=q('chat-messages');autoScroll=host.scrollHeight-host.scrollTop-host.clientHeight<80;q('chat-scroll-bottom').hidden=autoScroll;};
q('chat-messages').addEventListener('scrollend',event=>{const host=q('chat-messages');if(event.target!==host||!smoothScrolling)return;if(host.scrollHeight-host.scrollTop-host.clientHeight>1){host.scrollTo({top:host.scrollHeight,behavior:'smooth'});return;}smoothScrolling=false;});
const interruptScroll=()=>{if(!smoothScrolling)return;const host=q('chat-messages');smoothScrolling=false;host.scrollTo({top:host.scrollTop,behavior:'instant'});autoScroll=host.scrollHeight-host.scrollTop-host.clientHeight<80;q('chat-scroll-bottom').hidden=autoScroll;};
for(const event of ['wheel','touchstart','pointerdown'])q('chat-messages').addEventListener(event,interruptScroll,{passive:true});
q('chat-messages').addEventListener('keydown',event=>{if(['ArrowUp','ArrowDown','PageUp','PageDown','Home','End'].includes(event.key))interruptScroll();});
q('chat-messages').addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)&&(event.target as HTMLElement).matches('[data-view-image]')){event.preventDefault();(event.target as HTMLElement).click();}});
document.addEventListener('keydown',event=>{if(event.key!=='Escape'||event.defaultPrevented||document.querySelector('dialog[open]'))return;event.preventDefault();if(popup){closePopup();input.focus();return;}if(document.querySelector('.custom-select[aria-expanded=true]')){closeControls();input.focus();return;}if(!q('chat-history').hidden){run(()=>toggleHistory(false));return;}run(async()=>{await flushDraft();await api.hide();});});
api.onEvent(event);api.onShow(()=>run(async()=>{closePopup();await refresh();input.focus();}));document.addEventListener('visibilitychange',()=>{if(document.hidden)run(flushDraft);});buttons();run(async()=>{await refresh(undefined,true);input.focus();});
