import {t as tr,formatDate,formatBytes,formatNumber} from '../shared/i18n';
import {createElement,Archive} from 'lucide';
import {utilityEmpty} from './utility-empty';
import type {CheckpointEntry} from '../shared/checkpoints';
import type {RecoveryChoice,RecoveryPreview} from '../shared/recovery';
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;refresh():Promise<void>}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function checkpointDescription(point:CheckpointEntry){const reason=point.reason==='upgrade'?tr('版本变化前'):point.reason==='update'?tr('安装更新前'):tr('手动创建');return [reason,(point.sourceVersion||tr('未知版本'))+' → '+point.targetVersion,point.encrypted?tr('历史加密'):tr('明文数据库'),formatBytes(point.bytes)].join(' · ');}
export async function renderCheckpoints(root:HTMLElement,ctx:Context,heading?:HTMLElement){
 const api=window.clipper;
 root.innerHTML='<details class="utility-guide"><summary>'+esc(tr('恢复点说明'))+'</summary><p class="field-help">'+esc(tr('未关联旧程序的自动恢复点保留最近三份；程序回退所需的恢复点随旧程序保留。手动恢复点需要自行删除。恢复点包含本机数据库配置，不包含引用的源文件。'))+'</p><p class="field-help">'+esc(tr('开启历史加密不会加密此前的明文恢复点。'))+'</p></details><div class="data-controls"><button id="checkpoint-create">'+esc(tr('创建恢复点'))+'</button><span id="checkpoint-status" role="status"></span></div><div id="checkpoint-list"></div>';
 if(heading){heading.append(root.querySelector('#checkpoint-create')!);root.querySelector('.data-controls')!.replaceWith(root.querySelector('#checkpoint-status')!);}
 const list=root.querySelector<HTMLElement>('#checkpoint-list')!;list.classList.add('utility-list');const status=root.querySelector<HTMLElement>('#checkpoint-status')!;
 async function refresh(){const points=await api.checkpoints();if(!root.isConnected)return;let limit=50;const draw=()=>{list.replaceChildren();if(!points.length){list.append(utilityEmpty(tr('还没有恢复点'),Archive));return;}for(const point of points.slice(0,limit)){const row=document.createElement('article');row.className='checkpoint-entry';const copy=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small');title.textContent=formatDate(point.createdAt);meta.textContent=checkpointDescription(point);copy.className='archive-entry-copy';copy.append(title,meta);if(!point.compatible){const hint=document.createElement('small');hint.textContent=tr('需要匹配的新版程序');copy.append(hint);}const actions=document.createElement('div'),restore=document.createElement('button'),remove=document.createElement('button');actions.className='checkpoint-actions';restore.textContent=tr('校验与恢复');restore.dataset.checkpointRestore=point.id;restore.disabled=!point.compatible;restore.onclick=()=>void select(point.id).catch(ctx.toast);remove.textContent=tr('删除');remove.dataset.checkpointDelete=point.id;remove.onclick=()=>ctx.modal(tr('删除恢复点'),'<p>'+esc(formatDate(point.createdAt))+'</p><p class="field-help">'+esc(tr('只删除这份已校验的恢复点，当前历史资料保持不变。'))+'</p>',()=>locked(async()=>{await api.deleteCheckpoint(point.id);await refresh();}),tr('删除'));actions.append(restore,remove);const glyph=document.createElement('span');glyph.className='archive-entry-icon';glyph.append(createElement(Archive,{'class':'icon','aria-hidden':'true'}));row.append(glyph,copy,actions);list.append(row);}if(points.length>limit){const more=document.createElement('button');more.className='load-more';more.textContent=tr('载入更多');more.onclick=()=>{limit+=50;draw();};list.append(more);}};draw();}
 q('checkpoint-create').onclick=()=>void (async()=>{const button=q<HTMLButtonElement>('checkpoint-create');button.disabled=true;status.textContent=tr('正在创建并校验恢复点…');try{await api.createCheckpoint();await refresh();if(root.isConnected)status.textContent=tr('恢复点已创建');}finally{button.disabled=false;}})().catch(e=>{if(root.isConnected)status.textContent='';ctx.toast(e);});
 async function locked(action:()=>Promise<void>){const dialog=q<HTMLDialogElement>('dialog'),cancel=(e:Event)=>e.preventDefault(),buttons=Array.from(dialog.querySelectorAll<HTMLButtonElement>('button'));dialog.addEventListener('cancel',cancel);buttons.forEach(b=>b.disabled=true);try{await action();}finally{dialog.removeEventListener('cancel',cancel);buttons.forEach(b=>b.disabled=false);}}
 function wipeOnClose(){const dialog=q('dialog'),fields=Array.from(dialog.querySelectorAll<HTMLInputElement>('input')),key=dialog.querySelector<HTMLElement>('#checkpoint-recovery-key');dialog.addEventListener('close',()=>{fields.forEach(f=>{f.value='';});if(key)key.textContent='';},{once:true});}
 async function select(id:string){let choice:RecoveryChoice;try{choice=await api.chooseCheckpoint(id);if(!choice.encrypted&&!choice.requiresProtection){showPreview(await api.previewCheckpoint(choice.token));return;}}catch(e){await api.cancelCheckpoint().catch(()=>{});throw e;}
  let preview:RecoveryPreview|undefined;
  const password=choice.encrypted?'<label class="field">'+esc(tr('资料密码或恢复密钥'))+'<input id="checkpoint-password" type="password" autocomplete="off" maxlength="1024" required></label><label class="tool-check"><input id="checkpoint-use-key" type="checkbox">'+esc(tr('使用恢复密钥'))+'</label>':'';
  const protection=choice.requiresProtection?'<label class="field">'+esc(tr('新历史解锁密码'))+'<input id="checkpoint-new-password" type="password" autocomplete="new-password" maxlength="1024" required></label><label class="field">'+esc(tr('再次输入新密码'))+'<input id="checkpoint-repeat" type="password" autocomplete="new-password" maxlength="1024" required></label>':'';
  ctx.modal(tr('校验恢复点'),'<p class="path">'+esc(choice.name)+'</p>'+password+protection,()=>locked(async()=>{const input=q<HTMLInputElement>('checkpoint-new-password'),newPassword=input?.value;if(choice.requiresProtection&&(newPassword!.length<12||newPassword!==q<HTMLInputElement>('checkpoint-repeat').value))throw new Error(tr('新密码至少 12 个字符，且两次填写一致'));preview=await api.previewCheckpoint(choice.token,q<HTMLInputElement>('checkpoint-password')?.value,newPassword,q<HTMLInputElement>('checkpoint-use-key')?.checked?'recovery':'password');}),tr('校验与预览'));
  wipeOnClose();q('dialog').addEventListener('close',()=>{if(preview)queueMicrotask(()=>showPreview(preview!));else void api.cancelCheckpoint().catch(()=>{});},{once:true});
 }
 function showPreview(preview:RecoveryPreview){let committed=false;const counts=[['clips',tr('历史记录')],['snippets',tr('快捷回复')],['categories',tr('分类')],['scripts',tr('文本脚本')]] as const;
  const summary='<div class="restore-summary">'+counts.map(([key,label])=>'<div><strong>'+esc(formatNumber(preview[key]))+'</strong><span>'+esc(label)+'</span></div>').join('')+'</div>';
  const recoveryKey=preview.recoveryKey?'<p class="field-help">'+esc(tr('请保存新恢复密钥，再填写完整密钥确认。'))+'</p><pre class="vault-recovery" id="checkpoint-recovery-key">'+esc(preview.recoveryKey)+'</pre><label class="field">'+esc(tr('完整恢复密钥'))+'<input id="checkpoint-proof" autocomplete="off" maxlength="1024" required></label>':'';
  ctx.modal(tr('恢复点校验通过'),'<p class="path">'+esc(preview.name)+'</p>'+summary+'<p class="field-help">'+esc(tr('恢复到独立目录并切换，当前资料和恢复点均保留。恢复后暂停记录、自动备份和同步。'))+'</p>'+recoveryKey,()=>locked(async()=>{await api.restoreCheckpoint(preview.token,q<HTMLInputElement>('checkpoint-proof')?.value);committed=true;await ctx.refresh();ctx.toast(tr('已恢复副本，记录与同步保持暂停'));}),tr('创建并切换恢复副本'));
  wipeOnClose();q('dialog').addEventListener('close',()=>{if(!committed)void api.cancelCheckpoint().catch(()=>{});},{once:true});
 }
 await refresh();
}
