import {t as tr} from '../shared/i18n';
import {openAnchoredPopover,closeAnchoredPopover} from './anchored-popover';
import {onRemoval} from './controls';

function hsv(hex:string){const values=hex.slice(1).match(/../g)!.map(value=>parseInt(value,16)/255),[r,g,b]=values,max=Math.max(...values),min=Math.min(...values),delta=max-min;let hue=0;if(delta)hue=max===r?((g-b)/delta+6)%6:max===g?(b-r)/delta+2:(r-g)/delta+4;return {h:hue*60,s:max?delta/max:0,v:max};}
function hex(h:number,s:number,v:number){const sector=h/60,x=v*(1-s*Math.abs(sector%2-1)),low=v*(1-s),high=v,colors=[[high,x,low],[x,high,low],[low,high,x],[low,x,high],[x,low,high],[high,low,x]][Math.floor(sector)%6];return '#'+colors.map(value=>Math.round(value*255).toString(16).padStart(2,'0')).join('');}

/** An app-owned color panel; the backing input remains the editor's color value. */
export function setupColorPicker(input:HTMLInputElement){
 const wrapper=document.createElement('span');wrapper.className='color-picker-control';input.before(wrapper);wrapper.append(input);input.hidden=true;
 const trigger=document.createElement('button');trigger.type='button';trigger.className='color-picker-trigger';trigger.id=input.id+'-trigger';trigger.setAttribute('aria-label',tr('选择颜色'));trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-expanded','false');trigger.innerHTML='<span class="color-picker-swatch" aria-hidden="true"></span><span class="color-picker-value"></span>';wrapper.append(trigger);
 const panel=document.createElement('div');panel.className='color-picker-panel';panel.id=input.id+'-panel';panel.popover='manual';panel.role='dialog';panel.setAttribute('aria-label',tr('选择颜色'));
 panel.innerHTML=`<div class="color-picker-plane" tabindex="0" role="slider" aria-label="${tr('色彩')}" aria-valuemin="0" aria-valuemax="100"><span class="color-picker-marker"></span></div><input class="color-picker-hue" type="range" min="0" max="359" aria-label="${tr('色调')}"><div class="color-picker-presets"></div><label class="color-picker-hex"><span>HEX</span><input maxlength="7" spellcheck="false" aria-label="${tr('十六进制颜色')}"></label>`;
 document.body.append(panel);trigger.setAttribute('aria-controls',panel.id);
 const plane=panel.querySelector<HTMLElement>('.color-picker-plane')!,hue=panel.querySelector<HTMLInputElement>('.color-picker-hue')!,field=panel.querySelector<HTMLInputElement>('.color-picker-hex input')!,presets=panel.querySelector<HTMLElement>('.color-picker-presets')!;
 let value=hsv(input.value),open=false,pointer:number|undefined;
 const sync=()=>{const color=input.value.toUpperCase();trigger.style.setProperty('--picked-color',color);trigger.querySelector('.color-picker-value')!.textContent=color;panel.style.setProperty('--picked-hue',hex(value.h,1,1));plane.style.setProperty('--picked-x',value.s*100+'%');plane.style.setProperty('--picked-y',(1-value.v)*100+'%');plane.setAttribute('aria-valuenow',String(Math.round(value.s*100)));plane.setAttribute('aria-valuetext',color);hue.value=String(value.h);if(document.activeElement!==field)field.value=color;for(const button of presets.querySelectorAll<HTMLButtonElement>('button'))button.setAttribute('aria-pressed',String(button.dataset.color===input.value));};
 const apply=()=>{input.value=hex(value.h,value.s,value.v);sync();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));};
 for(const color of ['#de4747','#e89a38','#e2c645','#5eaa71','#4c95d8','#9b72cf','#ffffff','#202020']){const button=document.createElement('button');button.type='button';button.dataset.color=color;button.style.setProperty('--preset-color',color);button.setAttribute('aria-label',color);button.onclick=()=>{value=hsv(color);apply();};presets.append(button);}
 const pick=(event:PointerEvent)=>{const rect=plane.getBoundingClientRect();value.s=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));value.v=1-Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height));apply();};
 plane.onpointerdown=event=>{if(event.button!==0)return;event.preventDefault();plane.focus();pointer=event.pointerId;plane.setPointerCapture(pointer);pick(event);};plane.onpointermove=event=>{if(event.pointerId===pointer)pick(event);};plane.onpointerup=plane.onpointercancel=event=>{if(plane.hasPointerCapture(event.pointerId))plane.releasePointerCapture(event.pointerId);pointer=undefined;};
 plane.onkeydown=event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const step=event.shiftKey?.1:.02;value.s=Math.max(0,Math.min(1,value.s+(event.key==='ArrowRight'?step:event.key==='ArrowLeft'?-step:0)));value.v=Math.max(0,Math.min(1,value.v+(event.key==='ArrowUp'?step:event.key==='ArrowDown'?-step:0)));apply();};
 hue.oninput=()=>{value.h=Number(hue.value);apply();};field.oninput=()=>{const color=field.value.startsWith('#')?field.value:'#'+field.value;if(/^#[\da-f]{6}$/i.test(color)){value=hsv(color);apply();}};field.onblur=()=>{field.value=input.value.toUpperCase();};
 const close=(restore=false)=>{if(!open)return;open=false;closeAnchoredPopover(panel);trigger.setAttribute('aria-expanded','false');document.removeEventListener('pointerdown',outside,true);if(restore)trigger.focus();};
 const outside=(event:PointerEvent)=>{if(!panel.contains(event.target as Node)&&!trigger.contains(event.target as Node))close();};
 trigger.onclick=()=>{if(open){close();return;}value=hsv(input.value);sync();open=true;openAnchoredPopover(panel,trigger,260,440);trigger.setAttribute('aria-expanded','true');document.addEventListener('pointerdown',outside,true);plane.focus({preventScroll:true});};
 panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close(true);}else if(event.key==='Tab'){const controls=Array.from(panel.querySelectorAll<HTMLElement>('button,input,[tabindex="0"]')),first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
 input.addEventListener('change',()=>{value=hsv(input.value);sync();});onRemoval(wrapper,()=>{close();panel.remove();});sync();
}
