import {metadataUI} from './metadata-ui';
import {formatDefinition} from '../shared/formats';
const api=window.clipper,esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void}
export async function showContentInfo(ctx:Context,id:string){
 ctx.modal('格式与信息','<div id="content-info-body">正在读取记录信息…</div>',async()=>{},'完成');
 const node=document.getElementById('content-info-body')!,dialog=node.closest('dialog')!;let disposeMetadata=()=>{};
 const draw=async(readFiles=false)=>{
  const data=await api.contentInfo(id,readFiles);if(!node.isConnected||!dialog.open)return;disposeMetadata();
  const targets=[...(data.formats.some(f=>f.name==='PNG'||formatDefinition(f.name)?.mime.startsWith('image/'))?[{name:'保存的原图',target:{kind:'image' as const,index:0}}]:[]),...(data.attachments||[]).filter(a=>!a.directory).map(a=>({name:'保存附件 · '+a.name,target:{kind:'attachment' as const,index:a.index}})),...(data.files||[]).map((f,index)=>({name:'本机文件 · '+f.name,target:{kind:'file' as const,index}}))];
  node.innerHTML=`${targets.length?'<div class="segmented content-info-tabs" role="group" aria-label="信息类别"><button id="format-tab" type="button" aria-pressed="true" class="active">格式与来源</button><button id="metadata-tab" type="button" aria-pressed="false">内部信息</button></div>':''}<section id="format-details">${data.image?'<p class="field-help">图像尺寸：'+data.image.width+' × '+data.image.height+' 像素</p>':''}${data.sourceUrl?'<label class="field">HTML 来源<input readonly value="'+esc(data.sourceUrl)+'"></label>':''}<div class="format-list">${data.formats.map(f=>`<div class="format-row"><div><strong>${esc(f.label)}</strong><small>${esc(f.name)} · ${f.bytes.toLocaleString()} 保存字节</small></div>${f.exportable?`<button type="button" data-export-format="${esc(f.name)}">另存</button>`:''}</div>`).join('')}</div>
  ${data.attachments?'<p class="field-help">附件内容已保存在历史中，不依赖来源应用。复制或拖出会生成未加密临时文件，锁定或退出时清理；被其他程序占用的文件在释放后或下次启动时重试。</p><div class="file-info-list">'+data.attachments.map(a=>'<div class="format-row"><div><strong>'+esc(a.name)+'</strong><small>'+(a.directory?'已保存文件夹':a.bytes.toLocaleString()+' 字节')+(a.modified!==undefined?' · 修改于 '+new Date(a.modified).toLocaleString('zh-CN'):'')+'</small>'+(a.created!==undefined?'<small>创建于 '+new Date(a.created).toLocaleString('zh-CN')+'</small>':'')+'</div><button type="button" data-export-attachment="'+a.index+'">'+(a.directory?'另存文件夹':'另存附件')+'</button></div>').join('')+'</div>':''}
  ${data.files?'<p class="field-help">保留文件引用，原文件未重编码。以下状态为读取时信息，不代表复制时快照。</p><button id="read-file-info" type="button">读取本机文件信息</button><div class="file-info-list">'+data.files.map(f=>'<div><strong>'+esc(f.name)+'</strong><small>'+esc(f.type)+' · '+({available:'可访问',missing:'已不存在',unreadable:'无法读取','not-read':'未读取'}[f.status])+(f.bytes!==undefined?' · '+f.bytes.toLocaleString()+' 字节':'')+'</small><small>'+esc(f.path)+'</small>'+(f.modified!==undefined?'<small>修改时间：'+new Date(f.modified).toLocaleString('zh-CN')+'</small>':'')+'</div>').join('')+'</div>':''}
  <p class="field-help">原始格式可能包含来源、图片注释等元数据；网页共享仅提供文字/PNG。另存文件未加密，HTML 上下文以 .cfhtml 数据文件保存。</p></section><div id="metadata-host" hidden></div>`;
  const host=node.querySelector<HTMLElement>('#metadata-host')!,details=node.querySelector<HTMLElement>('#format-details')!;disposeMetadata=metadataUI(host,id,targets);
  if(targets.length){const formatTab=node.querySelector<HTMLButtonElement>('#format-tab')!,metadataTab=node.querySelector<HTMLButtonElement>('#metadata-tab')!;const view=(metadata:boolean)=>{details.hidden=metadata;host.hidden=!metadata;formatTab.classList.toggle('active',!metadata);metadataTab.classList.toggle('active',metadata);formatTab.setAttribute('aria-pressed',String(!metadata));metadataTab.setAttribute('aria-pressed',String(metadata));if(!metadata){const cancel=host.querySelector<HTMLButtonElement>('#metadata-cancel');if(cancel&&!cancel.hidden)cancel.click();}};formatTab.onclick=()=>view(false);metadataTab.onclick=()=>view(true);}
  node.querySelectorAll<HTMLButtonElement>('[data-export-format]').forEach(b=>b.onclick=()=>{b.disabled=true;void api.exportFormat(id,b.dataset.exportFormat!).then(file=>{if(file)ctx.toast('已保存：'+file);}).catch(ctx.toast).finally(()=>b.disabled=false);});
  node.querySelectorAll<HTMLButtonElement>('[data-export-attachment]').forEach(b=>b.onclick=()=>{b.disabled=true;void api.exportAttachment(id,Number(b.dataset.exportAttachment)).then(file=>{if(file)ctx.toast('已保存：'+file);}).catch(ctx.toast).finally(()=>b.disabled=false);});
  if(data.files){const button=node.querySelector<HTMLButtonElement>('#read-file-info')!;button.onclick=()=>{button.disabled=true;void draw(true).catch(ctx.toast);};}
 };
 await draw();
}
