import {utilityLayout} from './layout-029';
import {ActionScope} from './actions';
import {sectionLayout} from './page-layout';
import {createElement,HardDrive,Archive,History,RotateCcw} from 'lucide';
import {utilityEmpty} from './utility-empty';
import {t as tr,formatBytes,formatDate,formatNumber} from '../shared/i18n';
import {renderVault} from './vault-ui';
import {renderCheckpoints} from './checkpoint-ui';
import type {DataState,RestorePreview} from '../shared/data';
const api=window.clipper,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const size=formatBytes;
const date=(n:number)=>n?formatDate(n,{dateStyle:'medium',timeStyle:'medium',hour12:false}):tr('尚无');
interface Context {active():boolean;modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;refresh():Promise<void>;rerender?():Promise<void>}
export function dataUI(ctx:Context){
 let generation=0,restoreGeneration=0,embedded=false;
 const actions=new ActionScope(),on=(id:string,fn:()=>unknown)=>actions.bind(q<HTMLButtonElement>(id),fn,ctx.toast,id==='restore-file'?'restore-source':id);
 function protectInputs(){const nodes=Array.from(q('dialog').querySelectorAll<HTMLInputElement>('input[type=password]'));q('dialog').addEventListener('close',()=>nodes.forEach(n=>n.value=''),{once:true});}
 async function locked(work:()=>Promise<void>){const dialog=q<HTMLDialogElement>('dialog'),cancel=(e:Event)=>{e.preventDefault();e.stopImmediatePropagation();};dialog.addEventListener('cancel',cancel,true);const buttons=[q<HTMLButtonElement>('modal-close'),q<HTMLButtonElement>('modal-cancel')];buttons.forEach(b=>b.disabled=true);try{await work();}finally{dialog.removeEventListener('cancel',cancel,true);buttons.forEach(b=>b.disabled=false);}}
 function status(state:DataState){
  const b=state.backup,node=q('backup-status');if(!node)return;
  node.innerHTML=tr`<div><span>最近成功</span><strong>${date(b.lastSuccess)}</strong></div><div><span>下次备份</span><strong>${b.enabled?date(b.nextAt):tr('未启用')}</strong></div>${b.lastError?`<p class="data-error" role="status">${esc(b.lastError)}</p>`:''}`;
  const entries=q('backup-entries');entries.classList.add('utility-list');entries.innerHTML=state.entries.length?state.entries.map(e=>tr`<article class="backup-entry"><span class="archive-entry-icon">${createElement(Archive,{class:"icon","aria-hidden":"true"}).outerHTML}</span><div class="archive-entry-copy"><strong>${date(e.createdAt)}</strong><small title="${esc(e.name)}">${e.encrypted?tr('密码加密'):tr('明文 JSON')} · ${size(e.bytes)}</small></div><button data-restore-name="${esc(e.name)}">校验与恢复</button></article>`).join(''):utilityEmpty(tr('还没有自动备份'),Archive).outerHTML;
  entries.querySelectorAll<HTMLButtonElement>('[data-restore-name]').forEach(button=>actions.bind(button,()=>restore(button.dataset.restoreName),ctx.toast,'restore-source'));
 }
 async function updateStatus(){if(!ctx.active()||!q('backup-status'))return;const state=await api.dataState();if(ctx.active())status(state);}
 async function render(target?:HTMLElement,integrated=false){
  if(!target&&embedded){await ctx.rerender?.();return;}embedded=integrated;const destination=target||q('content');
  const token=++generation,state=await api.dataState();if(token!==generation||!ctx.active())return;const b=state.backup,scroll=q('content').querySelector('.data-page .tools-scroll')?.scrollTop||0;
  destination.innerHTML=tr`<section class="tools-page data-page"><div class="page-heading"><div><h1>数据与备份</h1></div></div><div class="tools-scroll"><div id="history-vault"></div><div class="tools-section-heading"><h2>当前存储</h2><button id="migrate-storage">迁移目录</button></div><div class="storage-location"><code id="storage-directory">${esc(state.directory)}</code><small>数据库与日志 ${size(state.databaseBytes)} · 历史、模板、分类、脚本与本机配置</small></div>${state.previousDirectory?tr`<p class="field-help">此前使用的目录：${esc(state.previousDirectory)}。新内容仅写入当前目录。</p>`:''}<div class="tools-section-heading"><h2>自动备份</h2><label class="tool-check"><input id="backup-enabled" type="checkbox" ${b.enabled?'checked':''}>启用</label></div><label class="field">备份文件夹<div class="data-path-row"><input id="backup-directory" readonly value="${esc(b.directory)}"><button id="backup-choose-folder">选择文件夹</button></div></label><div class="tool-field-grid"><label class="field">间隔（小时）<input id="backup-interval" type="number" min="1" max="168" value="${b.intervalHours}"></label><label class="field">保留最近几份<input id="backup-keep" type="number" min="1" max="100" value="${b.keep}"></label></div><label class="tool-check"><input id="backup-encrypted" type="checkbox" ${b.encrypted?'checked':''}>使用密码加密备份</label><div class="tool-field-grid" id="backup-password-fields"><label class="field">备份密码<input id="backup-password" type="password" autocomplete="new-password" maxlength="1024" placeholder="${b.hasPassword?tr('已保存，留空保留'):tr('至少 12 个字符')}"></label><label class="field">再次输入新密码<input id="backup-password-repeat" type="password" autocomplete="new-password" maxlength="1024" placeholder="填写新密码时确认"></label></div><p class="field-help">请自行保存密码，忘记后无法恢复。更换密码只影响新备份；改用明文会清除已保存的密码。备份包括历史、模板、分类和脚本，不包含 API 密钥、本机设置或源文件本体。</p><div class="data-controls"><button id="save-backup-settings" class="primary">保存备份设置</button><button id="backup-now" ${b.enabled?'':'disabled'}>立即备份</button><span id="data-feedback"></span></div><div class="backup-status" id="backup-status"></div><div class="tools-section-heading"><h2>备份记录</h2><div><button id="protected-export">手动导出</button><button id="restore-file">从文件恢复</button></div></div><div id="backup-entries"></div></div></section>`;
  const body=destination.querySelector<HTMLElement>('.tools-scroll')!,headings=Array.from(body.querySelectorAll<HTMLElement>(':scope > .tools-section-heading')),pointHeading=document.createElement('div'),pointTitle=document.createElement('h2'),points=document.createElement('div');points.className='checkpoint-workbench';pointHeading.className='tools-section-heading';pointTitle.textContent=tr('升级恢复点');pointHeading.append(pointTitle);body.append(pointHeading,points);if(!embedded)sectionLayout(body,[tr('当前存储'),tr('自动备份'),tr('备份记录'),tr('升级恢复点')],[q('history-vault'),headings[1],headings[2],pointHeading],'data-section',{icons:[HardDrive,Archive,History,RotateCcw]});
  if(!embedded)utilityLayout('data');status(state);body.scrollTop=scroll;q('backup-password-fields').hidden=!b.encrypted;
  q<HTMLInputElement>('backup-encrypted').onchange=()=>{q('backup-password-fields').hidden=!q<HTMLInputElement>('backup-encrypted').checked;};
  on('backup-choose-folder',async()=>{const input=q<HTMLInputElement>('backup-directory'),folder=await api.chooseBackupFolder();if(folder&&input.isConnected)input.value=folder;});
  on('save-backup-settings',async()=>{const password=q<HTMLInputElement>('backup-password').value;if(password!==q<HTMLInputElement>('backup-password-repeat').value)throw new Error(tr('两次填写的密码不一致'));await api.configureBackup({enabled:q<HTMLInputElement>('backup-enabled').checked,directory:q<HTMLInputElement>('backup-directory').value,intervalHours:Number(q<HTMLInputElement>('backup-interval').value),keep:Number(q<HTMLInputElement>('backup-keep').value),encrypted:q<HTMLInputElement>('backup-encrypted').checked,password:password||undefined});await render();ctx.toast(tr('备份设置已保存'));});
  on('backup-now',async()=>{const button=q<HTMLButtonElement>('backup-now');button.disabled=true;q('data-feedback').textContent=tr('正在生成并校验备份…');try{await api.backupNow();await render();ctx.toast(tr('备份已完成并通过恢复校验'));}finally{if(button.isConnected){button.disabled=false;q('data-feedback').textContent='';}}});
  on('migrate-storage',async()=>{const plan=await api.chooseStorage();if(!plan)return;ctx.modal(tr('迁移数据目录'),tr`<p>将当前全部数据复制到：</p><pre class="external-preview">${esc(plan.directory)}</pre><p class="field-help">当前数据库与日志 ${size(plan.bytes)}。校验通过后立即切换，无需重启；原目录保留作回退。迁移期间会结束正在进行的 AI 和脚本任务，开始后请等待完成。</p>`,()=>locked(async()=>{await api.migrateStorage(plan.token);await render();ctx.toast(tr('已切换到新目录，原数据仍保留'));}),tr('开始迁移'));});
  on('protected-export',exportDialog);on('restore-file',()=>restore());
  await renderVault({...ctx,refresh:async()=>{await ctx.refresh();await render();}});
  await renderCheckpoints(points,{...ctx,refresh:async()=>{await ctx.refresh();await render();}},pointHeading);
  if(embedded){headings[0].before(q('history-vault'));q('history-vault').before(headings[0]);pointTitle.textContent=tr('恢复与回退');return body;}
 }
 function exportDialog(){ctx.modal(tr('导出备份'),tr('<label class="tool-check"><input id="export-encrypted" type="checkbox" checked>使用密码加密</label><div id="export-password-fields"><label class="field">备份密码<input id="export-password" type="password" autocomplete="new-password" maxlength="1024" placeholder="至少 12 个字符"></label><label class="field">再次输入<input id="export-repeat" type="password" autocomplete="new-password" maxlength="1024"></label></div><p class="field-help">包含历史、模板、分类和脚本；不包含 API 密钥、本机设置和源文件本体。请自行保存密码，忘记后无法恢复。</p>'),()=>locked(async()=>{const encrypted=q<HTMLInputElement>('export-encrypted').checked,password=q<HTMLInputElement>('export-password').value;if(encrypted&&(password.length<12||password!==q<HTMLInputElement>('export-repeat').value))throw new Error(tr('密码至少 12 个字符，且两次填写一致'));const result=await api.exportProtected(encrypted?password:undefined);if(result)ctx.toast(tr('已导出 ')+result);}),tr('选择位置并导出'));protectInputs();q<HTMLInputElement>('export-encrypted').onchange=()=>q('export-password-fields').hidden=!q<HTMLInputElement>('export-encrypted').checked;}
 async function restore(name?:string){
  const generation=++restoreGeneration,file=await api.chooseRestore(name);if(!file)return;if(!ctx.active()||generation!==restoreGeneration){void api.cancelRestore(file.token).catch(()=>{});return;}
  let nextPreview:RestorePreview|undefined,cancelled=false;
  ctx.modal(file.encrypted?tr('解锁备份'):tr('校验备份'),`<p class="field-help">${esc(file.name)}</p>${file.encrypted?tr('<label class="field">备份密码<input id="restore-password" type="password" autocomplete="off" maxlength="1024" required></label>'):''}<p class="field-help">${tr('校验和预览不会修改当前数据。')}</p><p id="restore-progress" class="field-help" role="status" hidden>${tr('正在校验备份…')}</p>`,async()=>{
   const progress=q('restore-progress'),password=q<HTMLInputElement>('restore-password');progress.hidden=false;
   try{const result=await api.previewRestore(file.token,password?.value);if(!cancelled&&!q('dialog').classList.contains('closing')&&ctx.active()&&generation===restoreGeneration)nextPreview=result;else void api.cancelRestore(file.token).catch(()=>{});}
   catch(error){if(!cancelled)throw error;}finally{if(progress.isConnected)progress.hidden=true;if(password)password.value='';}
  },tr('解锁并校验'));
  const dialog=q<HTMLDialogElement>('dialog'),listeners=new AbortController(),dismiss=()=>{cancelled=true;void api.cancelRestore(file.token).catch(()=>{});};
  for(const id of ['modal-close','modal-cancel'])q(id).addEventListener('click',dismiss,{capture:true,signal:listeners.signal});dialog.addEventListener('cancel',dismiss,{capture:true,signal:listeners.signal});
  dialog.addEventListener('close',()=>{listeners.abort();if(nextPreview&&!cancelled&&ctx.active()&&generation===restoreGeneration){const result=nextPreview;queueMicrotask(()=>showPreview(result));}else dismiss();},{once:true});protectInputs();
  if(!file.encrypted){dialog.querySelector<HTMLButtonElement>('[type=submit]')!.hidden=true;dialog.querySelector('form')!.requestSubmit();}
 }
 function showPreview(value:RestorePreview){let committed=false,cancelled=false;const generation=restoreGeneration;ctx.modal(tr('备份校验通过'),tr`<p class="field-help">${esc(value.name)}</p><div class="restore-summary"><div><strong>${formatNumber(value.clips)}</strong><span>历史记录</span></div><div><strong>${formatNumber(value.snippets)}</strong><span>快捷回复</span></div><div><strong>${formatNumber(value.categories)}</strong><span>分类</span></div><div><strong>${formatNumber(value.scripts)}</strong><span>文本脚本</span></div></div><p class="field-help">${value.exportedAt?tr`导出时间：${date(Date.parse(value.exportedAt)||0)}。`:''} 将备份合并到当前资料，重复内容去重；已有设置和服务密钥保持。脚本只导入，不自动运行。恢复失败整体回滚。</p>`+`<p id="restore-merge-progress" class="field-help" role="status" hidden>${tr('正在处理，请稍候…')}</p>`,async()=>{const progress=q('restore-merge-progress');progress.hidden=false;try{const count=await api.restoreBackup(value.token);committed=true;if(ctx.active()&&generation===restoreGeneration){await ctx.refresh();await render();ctx.toast(tr`已合并 ${formatNumber(count)} 条记录`);}}catch(error){if(!cancelled)throw error;}finally{if(progress.isConnected)progress.hidden=true;}},tr('合并恢复'));const dialog=q<HTMLDialogElement>('dialog'),listeners=new AbortController(),dismiss=()=>{if(!committed){cancelled=true;void api.cancelRestore(value.token).catch(()=>{});}};for(const id of ['modal-close','modal-cancel'])q(id).addEventListener('click',dismiss,{capture:true,signal:listeners.signal});dialog.addEventListener('cancel',dismiss,{capture:true,signal:listeners.signal});dialog.addEventListener('close',()=>{listeners.abort();dismiss();},{once:true});}
 return {render,updateStatus};
}
