import {t as tr} from '../shared/i18n';
import type {DesktopOptions} from '../shared/desktop';
interface Context{active?():boolean;modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(message:unknown):void}
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const shortcut=(s:string)=>s.replaceAll('Control','Ctrl').replaceAll('+',' + ');
export async function desktopUI(ctx:Context){const api=window.clipper,{options:o,displays}=await api.desktopState();
 const check=(key:keyof DesktopOptions,label:string)=>`<label class="desktop-check"><input type="checkbox" id="desktop-${key}" ${o[key]?'checked':''}><span>${label}</span></label>`;
 if(ctx.active&&!ctx.active())return;ctx.modal(tr('桌面交互'),tr`<div class="desktop-form"><h3>托盘最近记录</h3><button type="button" id="desktop-tray-open">打开最近记录</button><h3>边缘呼出</h3>${check('dockEnabled',tr('启用边缘停靠'))}<div class="desktop-fields"><label class="field">屏幕边缘<select id="desktop-edge">${[['left',tr('左侧')],['right',tr('右侧')],['top',tr('顶部')],['bottom',tr('底部')]].map(([value,label])=>`<option value="${value}" ${o.dockEdge===value?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">停留时间<select id="desktop-dwell">${[200,350,450,650,900,1200,1500,...([200,350,450,650,900,1200,1500].includes(o.dwellMs)?[]:[o.dwellMs])].sort((a,b)=>a-b).map(n=>tr`<option value="${n}" ${o.dwellMs===n?'selected':''}>${n} 毫秒</option>`).join('')}</select></label></div><label class="field">显示器<select id="desktop-display"><option value="" ${o.displayId===null?'selected':''}>跟随鼠标所在屏幕</option>${displays.map(d=>`<option value="${d.id}" ${o.displayId===d.id?'selected':''}>${esc(d.name)}</option>`).join('')}${o.displayId!==null&&!displays.some(d=>d.id===o.displayId)?tr`<option value="${o.displayId}" selected>显示器已断开 · 暂时跟随鼠标</option>`:''}</select></label>${check('autoHide',tr('离开面板后自动收起'))}<h3>浮动拖放窗口</h3>${check('shelfTop',tr('按住鼠标拖至顶部中央时呼出'))}${check('shelfOnTop',tr('保持拖放窗口置顶'))}<label class="field">呼出快捷键<input id="desktop-shortcut" readonly value="${shortcut(o.shelfShortcut)}" data-value="${o.shelfShortcut}" aria-label="拖放窗口快捷键"></label></div>`,async()=>{const display=q<HTMLSelectElement>('desktop-display').value;await api.configureDesktop({...o,dockEnabled:q<HTMLInputElement>('desktop-dockEnabled').checked,dockEdge:q<HTMLSelectElement>('desktop-edge').value as DesktopOptions['dockEdge'],dwellMs:Number(q<HTMLSelectElement>('desktop-dwell').value),displayId:display===''?null:Number(display),autoHide:q<HTMLInputElement>('desktop-autoHide').checked,shelfTop:q<HTMLInputElement>('desktop-shelfTop').checked,shelfOnTop:q<HTMLInputElement>('desktop-shelfOnTop').checked,shelfShortcut:q('desktop-shortcut').dataset.value!});ctx.toast(tr('桌面设置已保存'));});
 if(!q('desktop-shortcut'))return;
 q('desktop-tray-open').onclick=()=>void api.showTray().catch(ctx.toast);
 const input=q<HTMLInputElement>('desktop-shortcut');input.onfocus=()=>{void api.recordShortcut(true).catch(ctx.toast);input.value=tr('按下快捷键…');};input.onblur=()=>{void api.recordShortcut(false).catch(ctx.toast);input.value=shortcut(input.dataset.value!);};input.onkeydown=e=>{e.preventDefault();e.stopPropagation();if(e.key==='Escape'){input.blur();return;}if(['Control','Alt','Shift','Meta'].includes(e.key))return;const key=e.key.toUpperCase(),parts=[e.ctrlKey?'Control':'',e.altKey?'Alt':'',e.shiftKey?'Shift':'',e.metaKey?'Super':''].filter(Boolean);if(!/^(?:[A-Z0-9]|F(?:[1-9]|1[0-9]|2[0-4]))$/.test(key))return;if(parts.length<2){input.value=tr('至少两个修饰键');return;}input.dataset.value=[...parts,key].join('+');input.dispatchEvent(new Event('change',{bubbles:true}));input.value=shortcut(input.dataset.value);input.blur();};
}
