import {setupShortcut} from './shortcut';
const api=window.clipper,esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;reuse(query:string):void}
export function efficiencyUI(ctx:Context){
 async function settings(){const {options}=await api.efficiencyState();ctx.modal('搜索与快捷回复',`<label class="field">打开快捷回复<input id="replies-shortcut" data-value="${esc(options.repliesShortcut)}" aria-label="打开快捷回复快捷键"></label><p class="field-help">点击录入；Delete 清除，Esc 取消。模板独立快捷键在“编辑回复”中设置，最多 100 个。</p><label class="efficiency-toggle"><input id="history-enabled" type="checkbox" ${options.historyEnabled?'checked':''}>记录最近搜索</label><p class="field-help">离开搜索框或使用结果时保存，最多 20 条。关闭会清空；不进入备份或设备同步。</p>`,async()=>{await api.configureEfficiency({repliesShortcut:document.querySelector<HTMLElement>('#replies-shortcut')!.dataset.value!,historyEnabled:document.querySelector<HTMLInputElement>('#history-enabled')!.checked});ctx.toast('已保存搜索与快捷回复设置');});setupShortcut(document.querySelector<HTMLInputElement>('#replies-shortcut')!,ctx.toast);}
 async function history(){const state=await api.efficiencyState();ctx.modal('搜索历史',`<div class="search-history-toolbar"><label class="efficiency-toggle"><input id="remember-searches" type="checkbox" ${state.options.historyEnabled?'checked':''}>记录最近搜索</label><button id="clear-searches" type="button">清空</button></div><p class="field-help">离开搜索框或使用结果时保存完整词条；只保留在本机。选择词条后沿用当前页面与筛选。这里的更改立即保存。</p><div id="recent-searches" class="recent-searches"></div>`,async()=>{},'完成');document.querySelector<HTMLElement>('#modal-cancel')!.hidden=true;const host=document.querySelector<HTMLElement>('#recent-searches')!,toggle=document.querySelector<HTMLInputElement>('#remember-searches')!,clear=document.querySelector<HTMLButtonElement>('#clear-searches')!;
  const draw=async()=>{const current=await api.efficiencyState();if(!host.isConnected)return;toggle.checked=current.options.historyEnabled;clear.disabled=!current.history.length;host.innerHTML=current.history.length?current.history.map((query,index)=>`<div class="recent-search-row"><button type="button" data-reuse-search="${index}" title="${esc(query)}">${esc(query)}</button><button type="button" data-delete-search="${index}" aria-label="删除搜索 ${esc(query)}">删除</button></div>`).join(''):`<p class="search-history-empty">${current.options.historyEnabled?'还没有搜索历史':'开启后，在这里找回最近搜索'}</p>`;
   host.querySelectorAll<HTMLButtonElement>('[data-reuse-search]').forEach(b=>b.onclick=()=>{const term=current.history[Number(b.dataset.reuseSearch)];host.closest<HTMLDialogElement>('dialog')!.close();ctx.reuse(term);});host.querySelectorAll<HTMLButtonElement>('[data-delete-search]').forEach(b=>b.onclick=()=>{void api.removeSearch(current.history[Number(b.dataset.deleteSearch)]).then(draw).catch(ctx.toast);});};
  toggle.onchange=()=>{const enabled=toggle.checked;toggle.disabled=true;void api.efficiencyState().then(s=>api.configureEfficiency({historyEnabled:enabled,repliesShortcut:s.options.repliesShortcut})).then(draw).catch(ctx.toast).finally(()=>toggle.disabled=false);};clear.onclick=()=>{void api.removeSearch(null).then(draw).catch(ctx.toast);};await draw();
 }
 return {settings,history};
}
