import {t as tr} from '../shared/i18n';
import {setupShortcut} from './shortcut';
import {createElement,History,Search,X,CornerDownLeft} from 'lucide';
const api=window.clip,esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
interface Context {active?():boolean;modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;reuse(query:string):void}
export function efficiencyUI(ctx:Context){
 async function settings(shortcuts=true){
  const {options}=await api.efficiencyState();if(ctx.active&&!ctx.active())return;
  const reply=shortcuts?`<h3>${tr('快捷回复')}</h3><label class="field">${tr('打开快捷回复')}<input id="replies-shortcut" data-value="${esc(options.repliesShortcut)}" aria-label="${tr('打开快捷回复')} ${tr('快捷键')}"></label>`:'';
  ctx.modal(tr('搜索与快捷回复'),reply+`<h3>${tr('搜索历史')}</h3><label class="efficiency-toggle"><input id="history-enabled" type="checkbox" ${options.historyEnabled?'checked':''}>${tr('记录最近搜索')}</label>`,async()=>{
   const current=await api.efficiencyState();await api.configureEfficiency({repliesShortcut:shortcuts?document.querySelector<HTMLElement>('#replies-shortcut')!.dataset.value!:current.options.repliesShortcut,historyEnabled:document.querySelector<HTMLInputElement>('#history-enabled')!.checked});ctx.toast(tr('已保存搜索与快捷回复设置'));
  });
  if(shortcuts){const input=document.querySelector<HTMLInputElement>('#replies-shortcut');if(input)setupShortcut(input,ctx.toast);}
 }
 async function history(){const state=await api.efficiencyState(),glyph=(node:Parameters<typeof createElement>[0])=>createElement(node,{class:'icon','aria-hidden':'true','stroke-width':1.75}).outerHTML;
  ctx.modal(tr('搜索历史'),`<div class="search-history-preference"><label for="remember-searches">${tr('记录最近搜索')}</label><label class="switch"><input id="remember-searches" type="checkbox" role="switch" aria-label="${tr('记录最近搜索')}" ${state.options.historyEnabled?'checked':''}><span></span></label></div><div class="search-history-list-heading"><span>${tr('最近搜索')}</span><small id="search-history-count"></small></div><div id="recent-searches" class="recent-searches" role="list" aria-label="${tr('搜索历史')}"></div>`,async()=>{},tr('完成'));
  const dialog=document.querySelector<HTMLDialogElement>('#dialog')!;dialog.classList.add('search-history-dialog');dialog.addEventListener('close',()=>dialog.classList.remove('search-history-dialog'),{once:true});dialog.querySelector<HTMLElement>('#modal-cancel')!.hidden=true;
  const host=dialog.querySelector<HTMLElement>('#recent-searches')!,toggle=dialog.querySelector<HTMLInputElement>('#remember-searches')!,count=dialog.querySelector<HTMLElement>('#search-history-count')!,clear=document.createElement('button');clear.id='clear-searches';clear.type='button';clear.className='quiet';clear.textContent=tr('清空历史');dialog.querySelector('.modal-footer')!.prepend(clear);let revision=0;
  const draw=async()=>{const token=++revision,current=await api.efficiencyState();if(!host.isConnected||token!==revision)return;toggle.checked=current.options.historyEnabled;clear.disabled=!current.history.length;count.textContent=String(current.history.length);
   host.innerHTML=current.history.length?current.history.map((query,index)=>`<div class="recent-search-row" role="listitem"><button type="button" data-reuse-search="${index}" title="${esc(query)}">${glyph(Search)}<span>${esc(query)}</span><i>${glyph(CornerDownLeft)}</i></button><button class="quiet" type="button" data-delete-search="${index}" aria-label="${tr('删除搜索')} ${esc(query)}" title="${tr('删除搜索')}">${glyph(X)}</button></div>`).join(''):`<div class="search-history-empty">${glyph(History)}<strong>${current.options.historyEnabled?tr('还没有搜索历史'):tr('开启后，在这里找回最近搜索')}</strong></div>`;
   host.querySelectorAll<HTMLButtonElement>('[data-reuse-search]').forEach(button=>button.onclick=()=>{const term=current.history[Number(button.dataset.reuseSearch)];dialog.close();ctx.reuse(term);});host.querySelectorAll<HTMLButtonElement>('[data-delete-search]').forEach(button=>button.onclick=()=>{button.disabled=true;const index=Number(button.dataset.deleteSearch);void api.removeSearch(current.history[index]).then(draw).then(()=>{if(host.isConnected)host.querySelector<HTMLButtonElement>(`[data-reuse-search="${Math.min(index,host.children.length-1)}"]`)?.focus();}).catch(ctx.toast).finally(()=>button.disabled=false);});};
  host.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;const buttons=Array.from(host.querySelectorAll<HTMLButtonElement>('[data-reuse-search]')),index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(index<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();});
  toggle.onchange=()=>{const enabled=toggle.checked;toggle.disabled=true;void api.efficiencyState().then(s=>api.configureEfficiency({historyEnabled:enabled,repliesShortcut:s.options.repliesShortcut})).then(draw).catch(error=>{toggle.checked=!enabled;ctx.toast(error);}).finally(()=>toggle.disabled=false);};clear.onclick=()=>{clear.disabled=true;void api.removeSearch(null).then(draw).catch(error=>{clear.disabled=false;ctx.toast(error);});};await draw();
 }
 return {settings,history};
}
