import {t as tr} from '../shared/i18n';
import './locale';
import './appearance';
import './image-editor.css';
import {createElement,Image,Crop,RotateCw,FlipHorizontal,PenLine,Square,ArrowUpRight,Type,RectangleHorizontal,Undo2,Redo2} from 'lucide';
import {editBox,editSize,EDIT_STEPS,type EditOperation,type Point,type ImageEditorAPI} from '../shared/image-edit';
import {renderEdits,drawMark} from './image-draw';
import {actionFeedback} from './actions';
import {canvasPng} from './image-encode';
import {setupColorPicker} from './color-picker';
declare global{interface Window{clipperImage:ImageEditorAPI}}
const api=window.clipperImage,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,canvas=q<HTMLCanvasElement>('image'),overlay=q<HTMLCanvasElement>('overlay'),source=new window.Image();
setupColorPicker(q<HTMLInputElement>('color'));
q('brand').append(createElement(Image));for(const [selector,icon] of [['[data-tool=crop]',Crop],['#rotate',RotateCw],['#flip',FlipHorizontal],['[data-tool=pen]',PenLine],['[data-tool=rect]',Square],['[data-tool=arrow]',ArrowUpRight],['[data-tool=text]',Type],['[data-tool=cover]',RectangleHorizontal],['#undo',Undo2],['#redo',Redo2]] as const)document.querySelector(selector)!.prepend(createElement(icon,{'aria-hidden':'true','stroke-width':1.75}));
let ops:EditOperation[]=[],redo:EditOperation[]=[],tool='crop',start:Point|undefined,draft:EditOperation|undefined,pointer:number|undefined,busy=true,saved='[]';
let textEditor:{node:HTMLTextAreaElement;at:Point;color:string;size:number}|undefined,transformAnimation:Animation|undefined;
const error=(e:unknown)=>q('message').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,''),changed=()=>JSON.stringify(ops)!==saved||!!textEditor?.node.value.trim();
function controls(){q<HTMLButtonElement>('undo').disabled=busy||!ops.length;q<HTMLButtonElement>('redo').disabled=busy||!redo.length;for(const id of ['save','copy','export','rotate','flip'])q<HTMLButtonElement>(id).disabled=busy;q<HTMLButtonElement>('apply-crop').disabled=busy||draft?.kind!=='crop';q<HTMLButtonElement>('clear-selection').disabled=busy||!draft;q('dimensions').textContent=tr`${canvas.width} × ${canvas.height} 像素`;q('steps').textContent=tr`${ops.length} / ${EDIT_STEPS} 步`;q('dirty').textContent=changed()?tr('尚未保存'):tr('已保存');}
function fit(){
 if(!canvas.width)return;
 const viewport=q('viewport'),style=getComputedStyle(viewport),zoom=q<HTMLSelectElement>('zoom').value;
 const availableWidth=Math.max(1,viewport.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)),availableHeight=Math.max(1,viewport.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom));
 const scale=zoom==='fit'?Math.min(1,availableWidth/canvas.width,availableHeight/canvas.height):Number(zoom),width=Math.max(1,canvas.width*scale),height=Math.max(1,canvas.height*scale);
 const surface=q('surface');surface.style.width=width+'px';surface.style.height=height+'px';
 for(const node of [canvas,overlay]){node.style.width=width+'px';node.style.height=height+'px';}
 if(zoom==='fit'){viewport.scrollTop=0;viewport.scrollLeft=0;}
 if(transformAnimation)transformAnimation.cancel();
 positionText();
}
function positionText(){if(!textEditor)return;const {node,at,size}=textEditor,scale=q('surface').getBoundingClientRect().width/canvas.width;node.style.left=at.x*scale+'px';node.style.top=at.y*scale+'px';node.style.fontSize=size*scale+'px';node.style.width=Math.min(360,Math.max(40,(canvas.width-at.x)*scale))+'px';node.style.height='auto';node.style.height=Math.max(size*scale*1.3+8,node.scrollHeight)+'px';}
function finishText(commit=true){if(!textEditor)return;const {node,at,color,size}=textEditor,text=node.value.trimEnd();textEditor=undefined;node.remove();if(commit&&text.trim())add({kind:'text',at,text,color,width:size});else void dirty();}
function beginText(at:Point){
 finishText();const size=width('text-size'),node=document.createElement('textarea');node.className='image-text-editor';node.maxLength=500;node.rows=1;node.placeholder=tr('输入文字');node.setAttribute('aria-label',tr('图片上的文字'));node.style.color=q<HTMLInputElement>('color').value;
 textEditor={node,at:{x:Math.min(at.x,Math.max(0,canvas.width-size)),y:Math.min(at.y,Math.max(0,canvas.height-size))},color:q<HTMLInputElement>('color').value,size};q('surface').append(node);positionText();node.focus();node.oninput=()=>{positionText();void dirty();};node.onblur=()=>finishText();node.onkeydown=event=>{event.stopPropagation();if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();finishText(false);overlay.focus();}else if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();finishText();overlay.focus();}};
}
async function transform(kind:'rotate'|'flip'){
 if(busy)return;finishText();if(ops.length>=EDIT_STEPS){add({kind});return;}if(matchMedia('(prefers-reduced-motion: reduce)').matches){add({kind});return;}
 const surface=q('surface'),viewport=q('viewport'),bounds=viewport.getBoundingClientRect(),before=surface.getBoundingClientRect(),clip=document.createElement('div'),ghost=document.createElement('canvas');
 clip.className='image-transform-clip';clip.setAttribute('aria-hidden','true');Object.assign(clip.style,{left:bounds.left+'px',top:bounds.top+'px',width:bounds.width+'px',height:bounds.height+'px',borderRadius:getComputedStyle(viewport).borderRadius});
 ghost.className='image-transform-preview';ghost.width=canvas.width;ghost.height=canvas.height;ghost.getContext('2d')!.drawImage(canvas,0,0);ghost.style.width=before.width+'px';ghost.style.height=before.height+'px';clip.append(ghost);document.body.append(clip);add({kind});busy=true;controls();surface.style.visibility='hidden';const after=surface.getBoundingClientRect(),scale=kind==='rotate'?after.height/before.width:after.width/before.width;
 const center=(rect:DOMRect)=>({left:rect.x+rect.width/2-bounds.x+'px',top:rect.y+rect.height/2-bounds.y+'px'});transformAnimation=ghost.animate([{...center(before),transform:'translate(-50%, -50%) rotate(0deg) scale(1)'},{...center(after),transform:kind==='rotate'?`translate(-50%, -50%) rotate(90deg) scale(${scale})`:`translate(-50%, -50%) scale(${-scale}, ${scale})`}],{duration:320,easing:'cubic-bezier(.22,.8,.25,1)',fill:'forwards'});
 try{await transformAnimation.finished;}catch{/* Resizing reveals the current, fitted canvas immediately. */}finally{transformAnimation=undefined;clip.remove();ghost.width=ghost.height=0;surface.style.visibility='';busy=false;controls();}
}
function preview(){const ctx=overlay.getContext('2d')!;ctx.clearRect(0,0,overlay.width,overlay.height);if(draft?.kind==='crop'){const b=draft.box;ctx.fillStyle='rgba(0,0,0,.4)';ctx.fillRect(0,0,overlay.width,overlay.height);ctx.clearRect(b.x,b.y,b.width,b.height);ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,overlay.width/overlay.getBoundingClientRect().width);ctx.setLineDash([ctx.lineWidth*5,ctx.lineWidth*4]);ctx.strokeRect(b.x+.5,b.y+.5,b.width-1,b.height-1);ctx.setLineDash([]);}else if(draft)drawMark(ctx,draft);controls();}
function resetDraft(){start=undefined;draft=undefined;if(pointer!==undefined&&overlay.hasPointerCapture(pointer))overlay.releasePointerCapture(pointer);pointer=undefined;preview();}
async function dirty(){controls();try{await api.dirty(changed());}catch(e){error(e);}}
function render(){renderEdits(canvas,source,ops);overlay.width=canvas.width;overlay.height=canvas.height;resetDraft();fit();void dirty();}
function add(op:EditOperation){if(busy)return;if(ops.length>=EDIT_STEPS){error(tr('本次编辑已达 100 步，请保存副本后重新打开'));resetDraft();return;}const count=ops.reduce((n,o)=>n+(o.kind==='pen'?o.points.length:0),0)+(op.kind==='pen'?op.points.length:0);if(count>20000){error(tr('画笔点数已达上限，请保存后重新打开'));resetDraft();return;}ops.push(op);redo=[];render();}
function point(e:PointerEvent){const b=overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))};}
function width(id='width'){return Math.max(id==='width'?1:8,Math.min(id==='width'?80:240,Number(q<HTMLInputElement>(id).value)||4));}
overlay.onpointerdown=e=>{if(busy||e.button!==0)return;resetDraft();if(tool==='text'){e.preventDefault();beginText(point(e));return;}finishText();overlay.focus();start=point(e);const color=q<HTMLInputElement>('color').value;pointer=e.pointerId;overlay.setPointerCapture(pointer);draft=tool==='crop'?{kind:'crop',box:editBox(start,start,canvas.width,canvas.height)}:tool==='pen'?{kind:'pen',points:[start],color,width:width()}:{kind:tool as 'rect'|'arrow'|'cover',a:start,b:start,color,width:width()};preview();};
overlay.onpointermove=e=>{if(!start||pointer!==e.pointerId||!draft||busy)return;const p=point(e);if(draft.kind==='crop')draft.box=editBox(start,p,canvas.width,canvas.height);else if(draft.kind==='pen'){if(draft.points.length<1000)draft.points.push(p);}else if('b' in draft)draft.b=p;preview();};
overlay.onpointerup=e=>{if(pointer!==e.pointerId||!draft)return;const op=draft;start=undefined;pointer=undefined;if(overlay.hasPointerCapture(e.pointerId))overlay.releasePointerCapture(e.pointerId);if(op.kind!=='crop')add(op);};overlay.onpointercancel=resetDraft;
document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{if(busy)return;finishText();resetDraft();tool=b.dataset.tool!;document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('active',el===b));q('text-size-field').hidden=tool!=='text';q('apply-crop').hidden=q('clear-selection').hidden=tool!=='crop';q('hint').textContent=tool==='crop'?tr('拖动选择区域，再应用裁剪。Esc 取消当前选区。'):tool==='cover'?tr('拖动使用当前颜色完全覆盖选区；遮盖将写入最终图片。'):tool==='text'?tr('点击图片输入文字。Enter 完成，Shift+Enter 换行，Esc 取消。'):tr('在图片上拖动进行标注。Ctrl+Z 撤销，Ctrl+Y 重做。');});
q('apply-crop').onclick=()=>{if(draft?.kind==='crop')add(draft);};q('clear-selection').onclick=resetDraft;q('rotate').onclick=()=>void transform('rotate');q('flip').onclick=()=>void transform('flip');q('undo').onclick=()=>{if(!busy&&ops.length){redo.push(ops.pop()!);render();}};q('redo').onclick=()=>{if(!busy&&redo.length){ops.push(redo.pop()!);render();}};q('zoom').onchange=fit;new ResizeObserver(fit).observe(q('viewport'));
async function save(mode:'history'|'copy'|'export'){if(busy)return;finishText();if(draft){error(tr('请先应用或取消裁剪选区'));return;}busy=true;controls();const finish=actionFeedback(q<HTMLButtonElement>(mode==='history'?'save':mode==='copy'?'copy':'export'));try{const png=await canvasPng(canvas),result=await api.save(png,mode);if(result!==null){if(mode!=='copy'){saved=JSON.stringify(ops);q('message').textContent=mode==='history'?tr('副本已保存到图片历史，原图保留'):tr('已保存：')+result;}else q('message').textContent=tr('已复制当前图片');}}catch(e){error(e);}finally{finish();busy=false;controls();}}
q('save').onclick=()=>void save('history');q('copy').onclick=()=>void save('copy');q('export').onclick=()=>void save('export');document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.isComposing||document.querySelector('dialog[open]'))return;if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='Escape')resetDraft();if(e.ctrlKey&&!e.altKey&&['z','y','s'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')void save('history');else q<HTMLButtonElement>(e.key.toLowerCase()==='y'||e.shiftKey?'redo':'undo').click();}});
api.onChange(()=>void api.state().then(s=>document.documentElement.dataset.theme=s.dark?'dark':'light').catch(error));void api.state().then(async s=>{document.documentElement.dataset.theme=s.dark?'dark':'light';source.src=s.url;await source.decode();editSize(source.naturalWidth,source.naturalHeight);busy=false;render();}).catch(error);controls();
