import {t as tr} from '../shared/i18n';
import './locale';
import './appearance';
import './image-editor.css';
import {createElement,Image,Crop,RotateCw,FlipHorizontal,PenLine,Square,ArrowUpRight,Type,MousePointer2,Undo2,Redo2,Circle,Triangle,Diamond,RectangleHorizontal} from 'lucide';
import {editBox,editSize,EDIT_STEPS,isImageMark,type ImageMark,type ShapeKind,type EditOperation,type Point,type ImageEditorAPI} from '../shared/image-edit';
import {markProjection,markBounds,projectedBox,mapPoint,unmapPoint,findMark,moveMark} from '../shared/image-marks';
import {renderEdits,applyEdit,drawMark} from './image-draw';
import {previewSize} from './image-motion-preview';
import {actionFeedback} from './actions';
import {canvasPng} from './image-encode';
import {setupColorPicker} from './color-picker';
import {customControls} from './controls';
declare global{interface Window{clipperImage:ImageEditorAPI}}
const api=window.clipperImage,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,canvas=q<HTMLCanvasElement>('image'),overlay=q<HTMLCanvasElement>('overlay'),source=new window.Image();
setupColorPicker(q<HTMLInputElement>('color'));
customControls(document.body);const shapeTrigger=q<HTMLButtonElement>('shape-kind-trigger'),shapeSymbol=document.createElement('span');shapeSymbol.className='shape-symbol';shapeTrigger.dataset.tool='shape';shapeTrigger.classList.add('quiet');shapeTrigger.prepend(shapeSymbol);
function shapeIcon(){const kind=q<HTMLSelectElement>('shape-kind').value;shapeSymbol.replaceChildren(createElement(kind==='ellipse'?Circle:kind==='triangle'?Triangle:kind==='diamond'?Diamond:kind==='roundrect'?RectangleHorizontal:Square,{'aria-hidden':'true','stroke-width':1.75}));shapeTrigger.title=q<HTMLSelectElement>('shape-kind').selectedOptions[0].text;}
shapeIcon();
q('brand').append(createElement(Image));for(const [selector,icon] of [['[data-tool=pointer]',MousePointer2],['[data-tool=crop]',Crop],['#rotate',RotateCw],['#flip',FlipHorizontal],['[data-tool=pen]',PenLine],['[data-tool=arrow]',ArrowUpRight],['[data-tool=text]',Type],['#undo',Undo2],['#redo',Redo2]] as const){const button=document.querySelector<HTMLButtonElement>(selector)!;const label=button.textContent?.trim();if(label&&!button.hasAttribute('aria-label'))button.setAttribute('aria-label',label);if(label&&!button.title)button.title=label;button.prepend(createElement(icon,{'aria-hidden':'true','stroke-width':1.75}));}
// History shares immutable vector operations. No full-size image snapshots are retained.
let ops:EditOperation[]=[],history:EditOperation[][]=[],redo:EditOperation[][]=[],tool='pointer',selected=-1,start:Point|undefined,draft:EditOperation|undefined,pointer:number|undefined,busy=true,saved='[]',signature='[]';
let textEditor:{node:HTMLTextAreaElement;at:Point;color:string;size:number;index?:number}|undefined,transformAnimation:Animation|undefined;
let moving:{original:ImageMark;mark:ImageMark;handle:number;at:Point}|undefined,propertyBase:EditOperation[]|undefined,propertyTimer:ReturnType<typeof setTimeout>|undefined,syncing=false;
const error=(e:unknown)=>q('message').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,''),changed=()=>signature!==saved||!!textEditor?.node.value.trim();
function controls(){q<HTMLButtonElement>('undo').disabled=busy||!(history.length||propertyBase);q<HTMLButtonElement>('redo').disabled=busy||!redo.length;for(const id of ['save','copy','export','rotate','flip'])q<HTMLButtonElement>(id).disabled=busy;q<HTMLButtonElement>('apply-crop').disabled=busy||draft?.kind!=='crop';q<HTMLButtonElement>('clear-selection').disabled=busy||!draft;q<HTMLButtonElement>('delete-mark').disabled=busy||selected<0;q('dimensions').textContent=tr`${canvas.width} × ${canvas.height} 像素`;q('steps').textContent=tr`${history.length+(propertyBase?1:0)} / ${EDIT_STEPS} 步`;q('dirty').textContent=changed()?tr('尚未保存'):tr('已保存');}
function canEdit(){if(history.length<EDIT_STEPS)return true;error(tr('本次编辑已达 100 步，请保存副本后重新打开'));return false;}
function remember(before:EditOperation[]){if(JSON.stringify(before)!==JSON.stringify(ops)){history.push(before);redo=[];}}
function flushProperties(){clearTimeout(propertyTimer);propertyTimer=undefined;if(propertyBase){remember(propertyBase);propertyBase=undefined;controls();}}
function selectedMark(){const mark=ops[selected];return mark&&isImageMark(mark)?mark:undefined;}
function measureText(text:string,size:number){const ctx=canvas.getContext('2d')!;ctx.save();ctx.font=`${size}px 'Segoe UI','Microsoft YaHei UI',sans-serif`;const width=ctx.measureText(text).width;ctx.restore();return width;}
function projection(){return markProjection(ops,selected,source.naturalWidth,source.naturalHeight);}
function markHandles(mark:ImageMark){if(mark.kind==='pen'||mark.kind==='text')return [];if(mark.kind==='arrow')return [mark.a,mark.b];const b=markBounds(mark,measureText);return [{x:b.x,y:b.y},{x:b.x+b.width,y:b.y},{x:b.x+b.width,y:b.y+b.height},{x:b.x,y:b.y+b.height}];}
function syncTools(){
 syncing=true;
 const mark=selectedMark(),shape=mark&&'a' in mark&&mark.kind!=='arrow';q('selected-mark').hidden=!mark;q('edit-text').hidden=mark?.kind!=='text';q('selected-label').textContent=mark?.kind==='text'?tr('文字'):mark?.kind==='arrow'?tr('箭头'):mark?.kind==='pen'?tr('画笔'):tr('形状');
 q('text-size-field').hidden=tool!=='text'&&mark?.kind!=='text';q('fill-field').hidden=tool!=='shape'&&!shape;q('width').closest('label')!.hidden=mark?.kind==='text'||tool==='text';q('apply-crop').closest('.crop-actions')!.toggleAttribute('hidden',tool!=='crop');overlay.style.cursor=tool==='pointer'?'default':tool==='text'?'text':'crosshair';
 if(mark){q<HTMLInputElement>('color').value=mark.color;q<HTMLInputElement>(mark.kind==='text'?'text-size':'width').value=String(mark.width);q<HTMLInputElement>('color').dispatchEvent(new Event('change'));if(shape){q<HTMLSelectElement>('shape-kind').value=mark.kind==='cover'?'rect':mark.kind;q<HTMLInputElement>('shape-filled').checked=!!mark.filled||mark.kind==='cover';}}
 shapeIcon();q('hint').textContent=tool==='pointer'?tr('点击标注选中，拖动移动；拖动端点调整大小。Delete 删除，双击文字编辑。'):tool==='crop'?tr('拖动选择区域，再应用裁剪。Esc 取消当前选区。'):tool==='text'?tr('点击图片输入文字。Enter 完成，Shift+Enter 换行，Esc 取消。'):tr('在图片上拖动进行标注。Ctrl+Z 撤销，Ctrl+Y 重做。');syncing=false;controls();
}
function fittedSize(imageWidth:number,imageHeight:number){
 const viewport=q('viewport'),style=getComputedStyle(viewport),zoom=q<HTMLSelectElement>('zoom').value;
 const availableWidth=Math.max(1,viewport.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)),availableHeight=Math.max(1,viewport.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom));
 const scale=zoom==='fit'?Math.min(1,availableWidth/imageWidth,availableHeight/imageHeight):Number(zoom);
 return {width:Math.max(1,imageWidth*scale),height:Math.max(1,imageHeight*scale)};
}
function fit(){
 if(!canvas.width)return;
 const viewport=q('viewport'),zoom=q<HTMLSelectElement>('zoom').value,{width,height}=fittedSize(canvas.width,canvas.height);
 const surface=q('surface');surface.style.width=width+'px';surface.style.height=height+'px';
 for(const node of [canvas,overlay]){node.style.width=width+'px';node.style.height=height+'px';}
 const pixelScale=Math.min(1,width/canvas.width*devicePixelRatio),pixelWidth=Math.max(1,Math.ceil(canvas.width*pixelScale)),pixelHeight=Math.max(1,Math.ceil(canvas.height*pixelScale));
 const redraw=overlay.width!==pixelWidth||overlay.height!==pixelHeight;if(overlay.width!==pixelWidth)overlay.width=pixelWidth;if(overlay.height!==pixelHeight)overlay.height=pixelHeight;if(redraw)preview();
 if(zoom==='fit'){viewport.scrollTop=0;viewport.scrollLeft=0;}
 if(transformAnimation)transformAnimation.cancel();
 positionText();
}
function positionText(){if(!textEditor)return;const {node,at,size,index}=textEditor,scale=q('surface').getBoundingClientRect().width/canvas.width,m=index===undefined?undefined:markProjection(ops,index,source.naturalWidth,source.naturalHeight),position=m?mapPoint(m.matrix,at):at;node.style.left=position.x*scale+'px';node.style.top=position.y*scale+'px';node.style.transformOrigin='0 0';node.style.transform=m?`matrix(${m.matrix.slice(0,4).join(',')},0,0)`:'';node.style.fontSize=size*scale+'px';node.style.width=Math.min(360,Math.max(40,((m?.size.width||canvas.width)-at.x)*scale))+'px';node.style.height='auto';node.style.height=Math.max(size*scale*1.3+8,node.scrollHeight)+'px';}
function finishText(commit=true){if(!textEditor)return;const {node,at,color,size,index}=textEditor,text=node.value.trimEnd();textEditor=undefined;node.remove();if(index!==undefined){if(commit&&text.trim()){const before=ops;ops=ops.map((op,i)=>i===index?{kind:'text',at,text,color,width:size}:op);remember(before);}render();syncTools();}else if(commit&&text.trim())add({kind:'text',at,text,color,width:size});else void dirty();}
function beginText(at:Point,index?:number){
 finishText();flushProperties();if(!canEdit())return;const old=index===undefined?undefined:ops[index],mark=old?.kind==='text'?old:undefined,size=mark?.width||width('text-size'),node=document.createElement('textarea');node.className='image-text-editor';node.maxLength=500;node.rows=1;node.placeholder=tr('输入文字');node.setAttribute('aria-label',tr('图片上的文字'));node.style.color=mark?.color||q<HTMLInputElement>('color').value;node.value=mark?.text||'';
 if(mark)renderEdits(canvas,source,ops.filter((_op,i)=>i!==index));textEditor={node,at:mark?.at||{x:Math.min(at.x,Math.max(0,canvas.width-size)),y:Math.min(at.y,Math.max(0,canvas.height-size))},color:mark?.color||q<HTMLInputElement>('color').value,size,index};q('surface').append(node);positionText();preview();node.focus();node.select();node.oninput=()=>{positionText();void dirty();};node.onblur=()=>finishText();node.onkeydown=event=>{event.stopPropagation();if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();finishText(false);overlay.focus();}else if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();finishText();overlay.focus();}};
}
async function transform(kind:'rotate'|'flip'){
 if(busy)return;finishText();flushProperties();selected=-1;syncTools();if(!canEdit())return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){add({kind});return;}
 const surface=q('surface'),viewport=q('viewport'),bounds=viewport.getBoundingClientRect(),before=surface.getBoundingClientRect(),clip=document.createElement('div'),ghost=document.createElement('canvas');
 clip.className='image-transform-clip';clip.setAttribute('aria-hidden','true');Object.assign(clip.style,{left:bounds.left+'px',top:bounds.top+'px',width:bounds.width+'px',height:bounds.height+'px',borderRadius:getComputedStyle(viewport).borderRadius});
 const next=fittedSize(kind==='rotate'?canvas.height:canvas.width,kind==='rotate'?canvas.width:canvas.height),pixels=previewSize(canvas.width,canvas.height,Math.max(before.width,kind==='rotate'?next.height:next.width),Math.max(before.height,kind==='rotate'?next.width:next.height),devicePixelRatio);
 ghost.className='image-transform-preview';ghost.width=pixels.width;ghost.height=pixels.height;const context=ghost.getContext('2d')!;context.imageSmoothingQuality='high';context.drawImage(canvas,0,0,pixels.width,pixels.height);ghost.style.width=before.width+'px';ghost.style.height=before.height+'px';clip.append(ghost);document.body.append(clip);add({kind});busy=true;controls();surface.style.visibility='hidden';const after=surface.getBoundingClientRect(),scale=kind==='rotate'?after.height/before.width:after.width/before.width;
 const center=(rect:DOMRect)=>({left:rect.x+rect.width/2-bounds.x+'px',top:rect.y+rect.height/2-bounds.y+'px'});transformAnimation=ghost.animate([{...center(before),transform:'translate(-50%, -50%) rotate(0deg) scale(1)'},{...center(after),transform:kind==='rotate'?`translate(-50%, -50%) rotate(90deg) scale(${scale})`:`translate(-50%, -50%) scale(${-scale}, ${scale})`}],{duration:320,easing:'cubic-bezier(.22,.8,.25,1)',fill:'forwards'});
 try{await transformAnimation.finished;}catch{/* Resizing reveals the current, fitted canvas immediately. */}finally{transformAnimation=undefined;clip.remove();ghost.width=ghost.height=0;surface.style.visibility='';busy=false;controls();}
}
function preview(){const ctx=overlay.getContext('2d')!;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,overlay.width,overlay.height);if(!canvas.width||!canvas.height)return;ctx.setTransform(overlay.width/canvas.width,0,0,overlay.height/canvas.height,0,0);if(draft?.kind==='crop'){const b=draft.box;ctx.fillStyle='rgba(0,0,0,.4)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.clearRect(b.x,b.y,b.width,b.height);ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,canvas.width/overlay.getBoundingClientRect().width);ctx.setLineDash([ctx.lineWidth*5,ctx.lineWidth*4]);ctx.strokeRect(b.x+.5,b.y+.5,b.width-1,b.height-1);ctx.setLineDash([]);}else if(draft)drawMark(ctx,draft,canvas);
 const mark=moving?.mark||selectedMark();if(mark&&!textEditor){const {matrix,size}=projection(),box=projectedBox(markBounds(mark,measureText),matrix),unit=canvas.width/overlay.getBoundingClientRect().width;if(moving){ctx.save();ctx.transform(...matrix);drawMark(ctx,mark,size);ctx.restore();}ctx.lineWidth=unit;ctx.strokeStyle='#4c95d8';ctx.setLineDash([4*unit,3*unit]);ctx.strokeRect(box.x-3*unit,box.y-3*unit,box.width+6*unit,box.height+6*unit);ctx.setLineDash([]);for(const p of markHandles(mark).map(p=>mapPoint(matrix,p))){ctx.fillStyle='#fff';ctx.fillRect(p.x-3*unit,p.y-3*unit,6*unit,6*unit);ctx.strokeRect(p.x-3*unit,p.y-3*unit,6*unit,6*unit);}}
 controls();}
function resetDraft(){start=undefined;draft=undefined;if(moving){moving=undefined;renderEdits(canvas,source,ops);}if(pointer!==undefined&&overlay.hasPointerCapture(pointer))overlay.releasePointerCapture(pointer);pointer=undefined;preview();}
async function dirty(){controls();try{await api.dirty(changed());}catch(e){error(e);}}
function render(op?:EditOperation){if(op)applyEdit(canvas,op);else renderEdits(canvas,source,ops);signature=JSON.stringify(ops);resetDraft();fit();void dirty();}
function add(op:EditOperation){if(busy)return;flushProperties();if(!canEdit()){resetDraft();return;}const count=ops.reduce((n,o)=>n+(o.kind==='pen'?o.points.length:0),0)+(op.kind==='pen'?op.points.length:0);if(count>20000){error(tr('画笔点数已达上限，请保存后重新打开'));resetDraft();return;}const before=ops;ops=[...ops,op];remember(before);render(op);}
function point(e:MouseEvent){const b=overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))};}
function width(id='width'){return Math.max(id==='width'?1:8,Math.min(id==='width'?80:240,Number(q<HTMLInputElement>(id).value)||4));}
overlay.onpointerdown=e=>{
 if(busy||e.button!==0)return;finishText();flushProperties();resetDraft();e.preventDefault();overlay.focus();const p=point(e);
 if(tool==='pointer'){
  let handle=-1,mark=selectedMark();const tolerance=8*canvas.width/overlay.getBoundingClientRect().width;
  if(mark)handle=markHandles(mark).map(at=>mapPoint(projection().matrix,at)).findIndex(at=>Math.hypot(at.x-p.x,at.y-p.y)<=tolerance);
  if(handle<0)selected=findMark(ops,p,source.naturalWidth,source.naturalHeight,tolerance/2,measureText);
  syncTools();mark=selectedMark();if(mark&&canEdit()){moving={original:mark,mark,handle,at:unmapPoint(projection().matrix,p)};renderEdits(canvas,source,ops.filter((_op,i)=>i!==selected));pointer=e.pointerId;overlay.setPointerCapture(pointer);}preview();return;
 }
 selected=-1;if(tool==='text'){beginText(p);return;}if(!canEdit())return;start=p;const color=q<HTMLInputElement>('color').value;pointer=e.pointerId;overlay.setPointerCapture(pointer);draft=tool==='crop'?{kind:'crop',box:editBox(start,start,canvas.width,canvas.height)}:tool==='pen'?{kind:'pen',points:[start],color,width:width()}:{kind:tool==='shape'?q<HTMLSelectElement>('shape-kind').value as ShapeKind:'arrow',a:start,b:start,color,width:width(),...(tool==='shape'?{filled:q<HTMLInputElement>('shape-filled').checked}:{})};preview();
};
overlay.onpointermove=e=>{
 if(pointer!==e.pointerId||busy)return;const p=point(e);
 if(moving){const {original,handle,at}=moving,{matrix,size}=projection(),local=unmapPoint(matrix,p);if(handle<0){const b=markBounds(original,measureText),dx=Math.max(-b.x,Math.min(size.width-b.x-b.width,local.x-at.x)),dy=Math.max(-b.y,Math.min(size.height-b.y-b.height,local.y-at.y));moving.mark=moveMark(original,dx,dy);}else if('a' in original){const end={x:Math.max(0,Math.min(size.width,local.x)),y:Math.max(0,Math.min(size.height,local.y))};moving.mark=original.kind==='arrow'?{...original,[handle?'b':'a']:end}:{...original,a:markHandles(original)[(handle+2)%4],b:end};}preview();return;}
 if(!start||!draft)return;if(draft.kind==='crop')draft.box=editBox(start,p,canvas.width,canvas.height);else if(draft.kind==='pen'){if(draft.points.length<1000)draft.points.push(p);}else if('b' in draft)draft.b=p;preview();
};
overlay.onpointerup=e=>{if(pointer!==e.pointerId)return;pointer=undefined;if(overlay.hasPointerCapture(e.pointerId))overlay.releasePointerCapture(e.pointerId);if(moving){const before=ops,mark=moving.mark;moving=undefined;ops=ops.map((op,i)=>i===selected?mark:op);remember(before);render();syncTools();return;}if(!draft)return;const op=draft;start=undefined;if(op.kind!=='crop')add(op);};overlay.onpointercancel=resetDraft;
overlay.ondblclick=e=>{if(tool==='pointer'&&!busy){const index=findMark(ops,point(e),source.naturalWidth,source.naturalHeight,4,measureText);if(index>=0&&ops[index].kind==='text'){selected=index;syncTools();beginText(point(e),index);}}};
function chooseTool(next:string){if(busy)return;finishText();flushProperties();resetDraft();tool=next;selected=-1;document.querySelectorAll<HTMLElement>('[data-tool]').forEach(el=>{el.classList.toggle('active',el.dataset.tool===tool);el.setAttribute('aria-pressed',String(el.dataset.tool===tool));});syncTools();preview();}
document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.addEventListener('click',()=>{if(b===shapeTrigger&&tool==='pointer'&&selectedMark()&&'a' in selectedMark()!&&selectedMark()!.kind!=='arrow')return;chooseTool(b.dataset.tool!);}));
function updateProperty(id:string){if(syncing||busy)return;const mark=selectedMark();if(!mark)return;if(!propertyBase&&!canEdit())return;let next:ImageMark=mark;if(id==='color')next={...mark,color:q<HTMLInputElement>('color').value};else if(id==='width'&&mark.kind!=='text')next={...mark,width:width()};else if(id==='text-size'&&mark.kind==='text')next={...mark,width:width('text-size')};else if('a' in mark&&mark.kind!=='arrow'){next={...mark,kind:q<HTMLSelectElement>('shape-kind').value as ShapeKind,filled:q<HTMLInputElement>('shape-filled').checked};}if(JSON.stringify(next)===JSON.stringify(mark))return;propertyBase??=ops;ops=ops.map((op,i)=>i===selected?next:op);render();clearTimeout(propertyTimer);propertyTimer=setTimeout(flushProperties,200);}
for(const id of ['color','width','text-size','shape-filled'])q(id).addEventListener('change',()=>updateProperty(id));
q('shape-kind').addEventListener('change',()=>{shapeIcon();const mark=selectedMark();if(tool==='pointer'&&mark&&'a' in mark&&mark.kind!=='arrow')updateProperty('shape-kind');else chooseTool('shape');});
function deleteMark(){if(busy||selected<0)return;finishText();flushProperties();if(!canEdit())return;const before=ops;ops=ops.filter((_op,i)=>i!==selected);selected=-1;remember(before);render();syncTools();}
q('delete-mark').onclick=deleteMark;q('edit-text').onclick=()=>{const mark=selectedMark();if(mark?.kind==='text'&&!busy)beginText(mark.at,selected);};
q('apply-crop').onclick=()=>{if(draft?.kind==='crop')add(draft);};q('clear-selection').onclick=resetDraft;q('rotate').onclick=()=>void transform('rotate');q('flip').onclick=()=>void transform('flip');q('undo').onclick=()=>{if(busy)return;finishText();flushProperties();if(history.length){redo.push(ops);ops=history.pop()!;selected=-1;render();syncTools();}};q('redo').onclick=()=>{if(busy)return;finishText();flushProperties();if(redo.length){history.push(ops);ops=redo.pop()!;selected=-1;render();syncTools();}};q('zoom').onchange=fit;new ResizeObserver(fit).observe(q('viewport'));
async function save(mode:'history'|'copy'|'export'){if(busy)return;finishText();flushProperties();if(draft){error(tr('请先应用或取消裁剪选区'));return;}resetDraft();busy=true;controls();const finish=actionFeedback(q<HTMLButtonElement>(mode==='history'?'save':mode==='copy'?'copy':'export'));try{const png=await canvasPng(canvas),result=await api.save(png,mode);if(result!==null){if(mode!=='copy'){saved=signature;q('message').textContent=mode==='history'?tr('副本已保存到图片历史，原图保留'):tr('已保存：')+result;}else q('message').textContent=tr('已复制当前图片');}}catch(e){error(e);}finally{finish();busy=false;controls();}}
q('save').onclick=()=>void save('history');q('copy').onclick=()=>void save('copy');q('export').onclick=()=>void save('export');document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.isComposing||document.querySelector('dialog[open]'))return;if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='Escape'){resetDraft();selected=-1;syncTools();preview();}if(tool==='pointer'&&selected>=0&&!busy){if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteMark();}else if(e.key.startsWith('Arrow')){e.preventDefault();flushProperties();if(canEdit()){const mark=selectedMark()!,matrix=projection().matrix,amount=e.shiftKey?10:1,a=unmapPoint(matrix,{x:0,y:0}),b=unmapPoint(matrix,{x:e.key==='ArrowLeft'?-amount:e.key==='ArrowRight'?amount:0,y:e.key==='ArrowUp'?-amount:e.key==='ArrowDown'?amount:0}),before=ops;ops=ops.map((op,i)=>i===selected?moveMark(mark,b.x-a.x,b.y-a.y):op);remember(before);render();}}}if(e.ctrlKey&&!e.altKey&&['z','y','s'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')void save('history');else q<HTMLButtonElement>(e.key.toLowerCase()==='y'||e.shiftKey?'redo':'undo').click();}});
api.onChange(()=>void api.state().then(s=>document.documentElement.dataset.theme=s.dark?'dark':'light').catch(error));void api.state().then(async s=>{document.documentElement.dataset.theme=s.dark?'dark':'light';source.src=s.url;await source.decode();editSize(source.naturalWidth,source.naturalHeight);busy=false;render();syncTools();}).catch(error);controls();
