import {t as tr} from '../shared/i18n';
import './locale';
import './appearance';
import './image-editor.css';
import {createElement,Image,Crop,RotateCw,FlipHorizontal,PenLine,Square,ArrowUpRight,Type,RectangleHorizontal,Undo2,Redo2} from 'lucide';
import {editBox,editSize,EDIT_STEPS,type EditOperation,type Point,type ImageEditorAPI} from '../shared/image-edit';
import {renderEdits,drawMark} from './image-draw';
import {actionFeedback} from './actions';
import {canvasPng} from './image-encode';
declare global{interface Window{clipperImage:ImageEditorAPI}}
const api=window.clipperImage,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,canvas=q<HTMLCanvasElement>('image'),overlay=q<HTMLCanvasElement>('overlay'),source=new window.Image();
q('brand').append(createElement(Image));for(const [selector,icon] of [['[data-tool=crop]',Crop],['#rotate',RotateCw],['#flip',FlipHorizontal],['[data-tool=pen]',PenLine],['[data-tool=rect]',Square],['[data-tool=arrow]',ArrowUpRight],['[data-tool=text]',Type],['[data-tool=cover]',RectangleHorizontal],['#undo',Undo2],['#redo',Redo2]] as const)document.querySelector(selector)!.prepend(createElement(icon,{'aria-hidden':'true','stroke-width':1.75}));
let ops:EditOperation[]=[],redo:EditOperation[]=[],tool='crop',start:Point|undefined,draft:EditOperation|undefined,pointer:number|undefined,busy=true,saved='[]';
const error=(e:unknown)=>q('message').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,''),changed=()=>JSON.stringify(ops)!==saved;
function controls(){q<HTMLButtonElement>('undo').disabled=busy||!ops.length;q<HTMLButtonElement>('redo').disabled=busy||!redo.length;for(const id of ['save','copy','export','rotate','flip'])q<HTMLButtonElement>(id).disabled=busy;q<HTMLButtonElement>('apply-crop').disabled=busy||draft?.kind!=='crop';q<HTMLButtonElement>('clear-selection').disabled=busy||!draft;q('dimensions').textContent=tr`${canvas.width} × ${canvas.height} 像素`;q('steps').textContent=tr`${ops.length} / ${EDIT_STEPS} 步`;q('dirty').textContent=changed()?tr('尚未保存'):tr('已保存');}
function fit(){if(!canvas.width)return;const v=q('viewport'),zoom=q<HTMLSelectElement>('zoom').value,scale=zoom==='fit'?Math.min(1,(v.clientWidth-24)/canvas.width,(v.clientHeight-24)/canvas.height):Number(zoom),w=Math.max(1,canvas.width*scale),h=Math.max(1,canvas.height*scale);q('surface').style.width=w+'px';q('surface').style.height=h+'px';for(const c of [canvas,overlay]){c.style.width=w+'px';c.style.height=h+'px';}}
function preview(){const ctx=overlay.getContext('2d')!;ctx.clearRect(0,0,overlay.width,overlay.height);if(draft?.kind==='crop'){const b=draft.box;ctx.fillStyle='rgba(0,0,0,.4)';ctx.fillRect(0,0,overlay.width,overlay.height);ctx.clearRect(b.x,b.y,b.width,b.height);ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,overlay.width/overlay.getBoundingClientRect().width);ctx.setLineDash([ctx.lineWidth*5,ctx.lineWidth*4]);ctx.strokeRect(b.x+.5,b.y+.5,b.width-1,b.height-1);ctx.setLineDash([]);}else if(draft)drawMark(ctx,draft);controls();}
function resetDraft(){start=undefined;draft=undefined;if(pointer!==undefined&&overlay.hasPointerCapture(pointer))overlay.releasePointerCapture(pointer);pointer=undefined;preview();}
async function dirty(){controls();try{await api.dirty(changed());}catch(e){error(e);}}
function render(){renderEdits(canvas,source,ops);overlay.width=canvas.width;overlay.height=canvas.height;resetDraft();fit();void dirty();}
function add(op:EditOperation){if(busy)return;if(ops.length>=EDIT_STEPS){error(tr('本次编辑已达 100 步，请保存副本后重新打开'));resetDraft();return;}const count=ops.reduce((n,o)=>n+(o.kind==='pen'?o.points.length:0),0)+(op.kind==='pen'?op.points.length:0);if(count>20000){error(tr('画笔点数已达上限，请保存后重新打开'));resetDraft();return;}ops.push(op);redo=[];render();}
function point(e:PointerEvent){const b=overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))};}
function width(id='width'){return Math.max(id==='width'?1:8,Math.min(id==='width'?80:240,Number(q<HTMLInputElement>(id).value)||4));}
overlay.onpointerdown=e=>{if(busy||e.button!==0)return;resetDraft();overlay.focus();start=point(e);const color=q<HTMLInputElement>('color').value;if(tool==='text'){const text=q<HTMLInputElement>('text-value').value.trim();if(!text){error(tr('先输入标注文字，再点击图片放置'));return;}add({kind:'text',at:start,text,color,width:width('text-size')});return;}pointer=e.pointerId;overlay.setPointerCapture(pointer);draft=tool==='crop'?{kind:'crop',box:editBox(start,start,canvas.width,canvas.height)}:tool==='pen'?{kind:'pen',points:[start],color,width:width()}:{kind:tool as 'rect'|'arrow'|'cover',a:start,b:start,color,width:width()};preview();};
overlay.onpointermove=e=>{if(!start||pointer!==e.pointerId||!draft||busy)return;const p=point(e);if(draft.kind==='crop')draft.box=editBox(start,p,canvas.width,canvas.height);else if(draft.kind==='pen'){if(draft.points.length<1000)draft.points.push(p);}else if('b' in draft)draft.b=p;preview();};
overlay.onpointerup=e=>{if(pointer!==e.pointerId||!draft)return;const op=draft;start=undefined;pointer=undefined;if(overlay.hasPointerCapture(e.pointerId))overlay.releasePointerCapture(e.pointerId);if(op.kind!=='crop')add(op);};overlay.onpointercancel=resetDraft;
document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{if(busy)return;resetDraft();tool=b.dataset.tool!;document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('active',el===b));q('text-size-field').hidden=q('text-value').hidden=tool!=='text';q('apply-crop').hidden=q('clear-selection').hidden=tool!=='crop';q('hint').textContent=tool==='crop'?tr('拖动选择区域，再应用裁剪。Esc 取消当前选区。'):tool==='cover'?tr('拖动使用当前颜色完全覆盖选区；遮盖将写入最终图片。'):tool==='text'?tr('输入文字与字号，点击图片放置。'):tr('在图片上拖动进行标注。Ctrl+Z 撤销，Ctrl+Y 重做。');});
q('apply-crop').onclick=()=>{if(draft?.kind==='crop')add(draft);};q('clear-selection').onclick=resetDraft;q('rotate').onclick=()=>add({kind:'rotate'});q('flip').onclick=()=>add({kind:'flip'});q('undo').onclick=()=>{if(!busy&&ops.length){redo.push(ops.pop()!);render();}};q('redo').onclick=()=>{if(!busy&&redo.length){ops.push(redo.pop()!);render();}};q('zoom').onchange=fit;new ResizeObserver(fit).observe(q('viewport'));
async function save(mode:'history'|'copy'|'export'){if(busy)return;if(draft){error(tr('请先应用或取消裁剪选区'));return;}busy=true;controls();const finish=actionFeedback(q<HTMLButtonElement>(mode==='history'?'save':mode==='copy'?'copy':'export'));try{const png=await canvasPng(canvas),result=await api.save(png,mode);if(result!==null){if(mode!=='copy'){saved=JSON.stringify(ops);q('message').textContent=mode==='history'?tr('副本已保存到图片历史，原图保留'):tr('已保存：')+result;}else q('message').textContent=tr('已复制当前图片');}}catch(e){error(e);}finally{finish();busy=false;controls();}}
q('save').onclick=()=>void save('history');q('copy').onclick=()=>void save('copy');q('export').onclick=()=>void save('export');document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.isComposing||document.querySelector('dialog[open]'))return;if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape')resetDraft();if(e.ctrlKey&&!e.altKey&&['z','y','s'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')void save('history');else q<HTMLButtonElement>(e.key.toLowerCase()==='y'||e.shiftKey?'redo':'undo').click();}});
api.onChange(()=>void api.state().then(s=>document.documentElement.dataset.theme=s.dark?'dark':'light').catch(error));void api.state().then(async s=>{document.documentElement.dataset.theme=s.dark?'dark':'light';source.src=s.url;await source.decode();editSize(source.naturalWidth,source.naturalHeight);busy=false;render();}).catch(error);controls();
