import {metadataLabels,type MetadataTarget,type MetadataResult} from '../shared/metadata';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function metadataUI(host:HTMLElement,id:string,targets:{name:string;target:MetadataTarget}[]){
 if(!targets.length)return ()=>{};host.innerHTML=`<section class="metadata-panel"><h3>内部信息</h3><p class="field-help">按需查看照片参数、媒体标签或文档属性。不会修改内容；本机文件显示读取时的信息。</p><label class="field">查看对象<select id="metadata-target">${targets.map((t,i)=>'<option value="'+i+'">'+esc(t.name)+'</option>').join('')}</select></label><label class="metadata-location"><input id="metadata-location" type="checkbox"> 包含照片位置信息</label><div class="metadata-actions"><button id="metadata-read" type="button">读取内部信息</button><button id="metadata-cancel" type="button" hidden>取消读取</button></div><p id="metadata-feedback" class="field-help" role="status"></p><dl id="metadata-values"></dl></section>`;
 const select=host.querySelector<HTMLSelectElement>('#metadata-target')!,location=host.querySelector<HTMLInputElement>('#metadata-location')!,read=host.querySelector<HTMLButtonElement>('#metadata-read')!,cancel=host.querySelector<HTMLButtonElement>('#metadata-cancel')!,feedback=host.querySelector<HTMLElement>('#metadata-feedback')!,values=host.querySelector<HTMLElement>('#metadata-values')!;let current='',disposed=false;
 const stop=()=>{const old=current;current='';if(old)void window.clipper.cancelMetadata(old).catch(()=>{});cancel.hidden=true;read.disabled=false;};
 const changed=()=>{stop();values.innerHTML='';feedback.textContent='点击读取以查看当前对象。';};select.onchange=changed;location.onchange=changed;cancel.onclick=()=>{stop();feedback.textContent='已取消读取。';};
 read.onclick=async()=>{stop();const token=crypto.randomUUID();current=token;read.disabled=true;cancel.hidden=false;values.innerHTML='';feedback.textContent='正在读取…';try{const result:MetadataResult=await window.clipper.metadata({requestId:token,id,target:targets[Number(select.value)].target,includeLocation:location.checked});if(disposed||current!==token||!host.isConnected)return;feedback.textContent=result.fields.length?'已读取 '+result.name+' · '+result.size.toLocaleString()+' 字节':'未找到可显示的内部信息。';values.innerHTML=result.fields.map(f=>'<div><dt>'+esc(metadataLabels[f.key])+'</dt><dd>'+esc(f.value)+'</dd></div>').join('');}catch(e){if(!disposed&&current===token&&host.isConnected)feedback.textContent=String((e as Error).message).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{if(current===token){current='';read.disabled=false;cancel.hidden=true;}}};
 const dialog=host.closest('dialog'),observer=new MutationObserver(()=>{if(!host.isConnected)dispose();});const dispose=()=>{if(disposed)return;disposed=true;stop();observer.disconnect();dialog?.removeEventListener('close',dispose);};dialog?.addEventListener('close',dispose);observer.observe(document.body,{childList:true,subtree:true});return dispose;
}
