import {aiModelsFor,type AIProfileView} from '../shared/text-tools';
import {t as tr} from '../shared/i18n';
import {icon} from './ui';
import {openAnchoredPopover,closeAnchoredPopover} from './anchored-popover';
import {closeControls} from './controls';

/** Service browsing is a preview; only choosing a model changes the conversation. */
export function modelPicker(button:HTMLButtonElement,get:()=>{profiles:AIProfileView[];profileId:string;modelId:string},choose:(profileId:string,modelId:string)=>void,load:(profileId:string)=>Promise<void>){
 let panel:HTMLElement|undefined,retiring:HTMLElement|undefined,browsing='',signature='';
 const pending=new Set<string>(),loaded=new Set<string>(),errors=new Map<string,string>();
 const close=(focus=false)=>{const previous=panel;panel=undefined;button.setAttribute('aria-expanded','false');button.removeAttribute('aria-controls');if(previous){previous.inert=true;previous.setAttribute('aria-hidden','true');retiring=previous;closeAnchoredPopover(previous);setTimeout(()=>previous.remove(),160);}if(focus)button.focus();};
 const renderModels=()=>{if(!panel)return;const state=get(),profile=state.profiles.find(item=>item.id===browsing),list=panel.querySelector<HTMLElement>('.model-picker-models')!,focused=list.contains(document.activeElement)?(document.activeElement as HTMLElement).dataset.model:undefined;list.replaceChildren();panel.querySelectorAll<HTMLElement>('[data-service]').forEach(node=>node.setAttribute('aria-selected',String(node.dataset.service===browsing)));
  for(const model of profile?aiModelsFor(profile):[]){const option=document.createElement('button');option.type='button';option.className='quiet model-picker-option';option.setAttribute('role','option');option.setAttribute('aria-selected',String(state.profileId===browsing&&state.modelId===model.id));option.dataset.model=model.id;const copy=document.createElement('span'),name=document.createElement('strong');name.textContent=model.name;copy.append(name);if(model.id&&model.name!==model.id){const id=document.createElement('small');id.textContent=model.id;copy.append(id);}option.append(copy);option.insertAdjacentHTML('beforeend',icon('check'));option.onclick=()=>{choose(browsing,model.id);close(true);};list.append(option);}
  if(pending.has(browsing)||errors.has(browsing)||!list.children.length){const empty=document.createElement('p');empty.className='model-picker-empty';empty.setAttribute('role','status');empty.textContent=pending.has(browsing)?tr('正在读取模型…'):errors.get(browsing)||tr('请先在 AI 服务中添加模型');list.append(empty);if(errors.has(browsing)){const retry=document.createElement('button');retry.className='quiet';retry.textContent=tr('重试');retry.onclick=()=>{loaded.delete(browsing);void discover(browsing);};list.append(retry);}}
  if(focused!==undefined)Array.from(list.querySelectorAll<HTMLButtonElement>('[data-model]')).find(option=>option.dataset.model===focused)?.focus({preventScroll:true});
 };
 const discover=async(id:string)=>{if(pending.has(id)||loaded.has(id))return;pending.add(id);errors.delete(id);renderModels();try{await load(id);loaded.add(id);}catch(error){errors.set(id,tr('读取模型失败，可使用已保存的模型或重试'));}finally{pending.delete(id);if(panel&&browsing===id)renderModels();}};
 const open=()=>{if(panel){close();return;}retiring?.remove();retiring=undefined;closeControls();const state=get();if(!state.profiles.length)return;browsing=state.profileId||state.profiles[0].id;panel=document.createElement('div');panel.id='chat-model-options';panel.className='model-picker';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',tr('选择模型'));panel.innerHTML=`<section><h2>${tr('AI 服务')}</h2><div class="model-picker-services" role="listbox" aria-label="${tr('AI 服务')}"></div></section><section><h2>${tr('模型')}</h2><div class="model-picker-models" role="listbox" aria-label="${tr('模型')}"></div></section>`;const services=panel.querySelector('.model-picker-services')!;
  for(const profile of state.profiles){const option=document.createElement('button');option.type='button';option.className='quiet model-picker-option';option.setAttribute('role','option');option.dataset.service=profile.id;option.textContent=profile.name;option.onfocus=()=>{browsing=profile.id;renderModels();void discover(browsing);};option.onclick=()=>{browsing=profile.id;renderModels();void discover(browsing);panel?.querySelector<HTMLButtonElement>('[data-model]')?.focus();};services.append(option);}
  renderModels();document.body.append(panel);button.setAttribute('aria-expanded','true');button.setAttribute('aria-controls',panel.id);openAnchoredPopover(panel,button,440,350);
  panel.onkeydown=event=>{const target=(event.target as HTMLElement).closest<HTMLButtonElement>('[role=option]');if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close(true);return;}if(!target)return;const group=target.parentElement!,items=Array.from(group.querySelectorAll<HTMLButtonElement>('[role=option]')),index=items.indexOf(target);let next:HTMLButtonElement|undefined;if(event.key==='ArrowDown')next=items[(index+1)%items.length];if(event.key==='ArrowUp')next=items[(index+items.length-1)%items.length];if(event.key==='Home')next=items[0];if(event.key==='End')next=items.at(-1);if(event.key==='ArrowRight'&&target.hasAttribute('data-service'))next=panel?.querySelector<HTMLButtonElement>('[data-model][aria-selected=true]')||panel?.querySelector<HTMLButtonElement>('[data-model]')||undefined;if(event.key==='ArrowLeft'&&target.hasAttribute('data-model'))next=panel?.querySelector<HTMLButtonElement>('[data-service][aria-selected=true]')||undefined;if(next){event.preventDefault();next.focus();next.scrollIntoView({block:'nearest'});}};
  (panel.querySelector<HTMLButtonElement>('[data-model][aria-selected=true]')||panel.querySelector<HTMLButtonElement>('[data-model]')||panel.querySelector<HTMLButtonElement>('[data-service]'))?.focus();
  void discover(browsing);
 };
 button.onclick=open;button.onkeydown=event=>{if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();if(!panel)open();}};
 document.addEventListener('pointerdown',event=>{if(panel&&!panel.contains(event.target as Node)&&!button.contains(event.target as Node))close();});document.addEventListener('focusin',event=>{if(panel&&!panel.contains(event.target as Node)&&event.target!==button)close();});
 return {close,update(){const state=get(),profile=state.profiles.find(item=>item.id===state.profileId),model=profile&&aiModelsFor(profile).find(item=>item.id===state.modelId),next=JSON.stringify(state.profiles.map(item=>[item.id,item.revision]));if(signature&&next!==signature){close();loaded.clear();}signature=next;button.disabled=!state.profiles.length;button.querySelector('span')!.textContent=model?.name||profile?.name||tr('尚未添加服务');button.title=profile?`${profile.name} · ${model?.id||tr('默认模型')}`:tr('请选择 AI 服务');}};
}
