import {aiModelsFor,aiReasoningEfforts,reasoningLabel,type AIModel,type AIProfileView,type AIKind} from '../shared/text-tools';
import {t as tr} from '../shared/i18n';
import {Plus,Trash2} from 'lucide';
import {icon,registerIcons} from './ui';
import {customControls} from './controls';
registerIcons({'model-add':Plus,'model-delete':Trash2});

export function modelEditor(root:HTMLElement,profile:AIProfileView|undefined,kind:()=>AIKind,fetch:()=>Promise<AIModel[]>){
 let models=profile?aiModelsFor(profile).filter(model=>model.id):[],defaultId=profile?.model||'',codexAvailable=false,loading=false,version=0,lastKind=kind();
 const defaults=document.getElementById('ai-model') as HTMLSelectElement,effort=document.getElementById('ai-effort') as HTMLSelectElement;
 root.innerHTML=`<header><strong>${tr('模型列表')}</strong><div><button type="button" id="ai-fetch-models" class="quiet small">${tr('读取模型')}</button><button type="button" id="ai-add-model" class="quiet small">${icon('lucide:model-add')}${tr('添加模型')}</button></div></header><div class="ai-model-column-labels"><span>${tr('显示名称')}</span><span>${tr('模型 ID')}</span></div><div id="ai-model-rows"></div><p id="ai-model-status" class="field-help" role="status" hidden></p>`;
 const rows=root.querySelector<HTMLElement>('#ai-model-rows')!,read=()=>Array.from(rows.children).map((row,index)=>({id:(row.querySelector('[data-model-id]') as HTMLInputElement).value.trim(),name:(row.querySelector('[data-model-name]') as HTMLInputElement).value.trim(),...(models[index]?.reasoningEfforts?{reasoningEfforts:models[index].reasoningEfforts}:{})})).filter(model=>model.id||model.name);
 const updateEffort=()=>{const options=[{value:'',label:reasoningLabel('')},...aiReasoningEfforts({kind:kind(),model:defaults.value,models:read()}).map(value=>({value,label:reasoningLabel(value)}))],current=effort.value;effort.dispatchEvent(new CustomEvent('one:options',{detail:options}));effort.value=options.some(option=>option.value===current)?current:'';effort.closest('label')!.hidden=kind()!=='codex';};
 const sync=()=>{if(lastKind!==kind()){lastKind=kind();version++;status.hidden=true;}load.hidden=!profile&&kind()!=='codex';load.disabled=loading||kind()==='codex'&&!codexAvailable;const entries=read().filter(model=>model.id),options=entries.map(model=>({value:model.id,label:model.name||model.id}));if(kind()==='codex')options.unshift({value:'',label:tr('Codex 默认模型')});if(!options.length)options.push({value:'',label:tr('尚未添加模型')});defaults.dispatchEvent(new CustomEvent('one:options',{detail:options}));defaultId=options.some(option=>option.value===defaultId)?defaultId:options[0].value;defaults.value=defaultId;root.querySelector<HTMLButtonElement>('#ai-add-model')!.disabled=rows.children.length>=100;updateEffort();};
 const render=()=>{rows.replaceChildren();for(const model of models){const row=document.createElement('div');row.className='ai-model-row';for(const [key,label,value,max]of [['name',tr('显示名称'),model.name,120],['id',tr('模型 ID'),model.id,200]] as const){const field=document.createElement('input');field.setAttribute('aria-label',label);field.dataset[key==='id'?'modelId':'modelName']='';field.placeholder=key==='id'?'model-id':tr('显示名称');field.maxLength=max;field.value=value;field.oninput=()=>{if(key==='id'&&defaultId===model.id){defaultId=field.value.trim();model.id=defaultId;}sync();};row.append(field);}const remove=document.createElement('button');remove.type='button';remove.className='quiet icon-button';remove.title=tr('删除模型');remove.setAttribute('aria-label',remove.title);remove.innerHTML=icon('lucide:model-delete');remove.onclick=()=>{models=read();models.splice(Array.from(rows.children).indexOf(row),1);render();};row.append(remove);rows.append(row);}sync();};
 const status=root.querySelector<HTMLElement>('#ai-model-status')!,load=root.querySelector<HTMLButtonElement>('#ai-fetch-models')!;
 load.onclick=async()=>{if(loading)return;loading=true;const requestVersion=version;load.disabled=true;status.hidden=false;status.textContent=tr('正在读取模型…');try{const discovered=await fetch();if(!root.isConnected||requestVersion!==version)return;const existing=new Map(read().map(model=>[model.id,model]));for(const model of discovered){const previous=existing.get(model.id);existing.set(model.id,{...model,name:previous?.name&&previous.name!==previous.id?previous.name:model.name});}models=[...existing.values()].slice(0,100);render();status.textContent=discovered.length?tr`找到 ${discovered.length} 个模型`:tr('服务未返回模型，请先在模型服务中安装或加载模型');}catch(error){if(status.isConnected&&requestVersion===version)status.textContent=String(error instanceof Error?error.message:error);}finally{loading=false;sync();}};
 root.querySelector<HTMLButtonElement>('#ai-add-model')!.onclick=()=>{models=read();models.push({id:'',name:''});render();rows.lastElementChild?.querySelector('input')?.focus();};
 defaults.onchange=()=>{defaultId=defaults.value;updateEffort();};customControls(root.parentElement!);render();if(profile?.reasoningEffort)effort.value=profile.reasoningEffort;
 return {read,update:sync,setCodexAvailable(value:boolean){codexAvailable=value;sync();}};
}
