import {t as tr} from '../shared/i18n';
import {emptyClipFilters,hasClipFilters,normalizeClipFilters,type ClipFilters} from '../shared/clip-filters';
import type {TrayState} from '../shared/tray';
import {openAnchoredPopover,closeAnchoredPopover} from './anchored-popover';
import {icon} from './ui';
import {dateField,bindDatePickers,closeDatePickers} from './date-picker';
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function quickFilters(button:HTMLButtonElement,changed:()=>void,opening:()=>void){
 let value=emptyClipFilters(),opened=false,sources:NonNullable<TrayState['sources']>=[];
 const panel=document.createElement('section');panel.className='quick-filter-popover clip-popover';panel.popover='manual';panel.setAttribute('aria-label',tr('筛选记录'));document.body.append(panel);
 const options=(choices:readonly(readonly[string,string])[],selected='',glyphs?:Record<string,string>)=>choices.map(([key,label])=>`<option value="${esc(key)}"${glyphs?.[key]?` data-icon="${glyphs[key]}"`:''}${key===selected?' selected':''}>${esc(label)}</option>`).join('');
 const sourceOptions=()=>{const entries=[{value:'',label:tr('全部应用'),source:''},...sources.map(source=>({value:source.name.trim().toLocaleLowerCase(),label:source.name.replace(/\.exe$/i,'')+' · '+source.count,source:source.name})),...value.sources.filter(name=>!sources.some(source=>source.name.trim().toLocaleLowerCase()===name)).map(name=>({value:name,label:name,source:name}))];return entries.map(entry=>`<option value="${esc(entry.value)}"${entry.source?` data-source-app="${esc(entry.source)}"`:' data-icon="lucide:app"'}${entry.value===(value.sources[0]||'')?' selected':''}>${esc(entry.label)}</option>`).join('');};
 function refresh(){const count=Number(!!value.kinds.length)+Number(!!value.sources.length)+Number(!!value.period)+Number(!!value.favorite)+Number(!!value.pinned)+Number(!!value.size)+Number(!!value.tags.length)+Number(!!value.extensions.length);button.innerHTML=icon('lucide:filter')+(count?`<small>${count}</small>`:'');button.classList.toggle('has-filters',hasClipFilters(value));}
 function close(){opened=false;closeDatePickers(panel);button.setAttribute('aria-expanded','false');closeAnchoredPopover(panel);document.removeEventListener('pointerdown',outside,true);document.removeEventListener('keydown',keyboard,true);}
 function outside(event:PointerEvent){if(!(event.target instanceof Element&&event.target.closest('.select-popup'))&&!panel.contains(event.target as Node)&&!button.contains(event.target as Node))close();}
 function keyboard(event:KeyboardEvent){if(panel.querySelector('.clip-date-trigger[aria-expanded=true]'))return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();close();button.focus();}}
 function draw(){
  panel.innerHTML=`<header><strong>${tr('筛选记录')}</strong><button type="button" data-reset>${tr('清除条件')}</button></header><div class="quick-filter-grid"><label>${tr('类型')}<select data-field="kind">${options([['',tr('全部')],['text',tr('文本')],['image',tr('图片')],['files',tr('文件')],['link',tr('链接')],['code',tr('代码')]],value.kinds[0],{'':'lucide:clipboard',text:'lucide:file-text',image:'image',files:'lucide:folder',link:'lucide:link',code:'lucide:code'})}</select></label><label>${tr('日期')}<select data-field="period">${options([['',tr('不限')],['today',tr('今天')],['yesterday',tr('昨天')],['week',tr('本周')],['month',tr('本月')],['custom',tr('自定义')]],value.period)}</select></label><div class="quick-filter-dates"${value.period==='custom'?'':' hidden'}><label>${tr('开始日期')}${dateField({filter:'from',value:value.from,label:tr('开始日期')})}</label><label>${tr('结束日期')}${dateField({filter:'to',value:value.to,label:tr('结束日期')})}</label></div><label class="filter-full">${tr('来源应用')}<select data-field="source" data-show-source-icon="true">${sourceOptions()}</select></label><div class="filter-full quick-filter-status"><span>${tr('状态')}</span><button type="button" data-status="favorite" aria-pressed="${!!value.favorite}">${icon('lucide:star')}${tr('已收藏')}</button><button type="button" data-status="pinned" aria-pressed="${!!value.pinned}">${icon('lucide:pin')}${tr('已置顶')}</button></div><label>${tr('大小')}<select data-field="size">${options([['',tr('不限')],['small',tr('小于 1 MB')],['medium','1–10 MB'],['large',tr('大于 10 MB')]],value.size)}</select></label><label>${tr('文件扩展名')}<input data-field="extensions" placeholder="pdf, docx, zip" value="${esc(value.extensions.join(', '))}" maxlength="200"></label><label class="filter-full">${tr('标签')}<input data-field="tags" value="${esc(value.tags.join(', '))}" maxlength="200" placeholder="${tr('用逗号分隔')}"></label></div>`;
  const read=()=>{const field=(name:string)=>panel.querySelector<HTMLInputElement|HTMLSelectElement>(`[data-field="${name}"],[data-filter-date="${name}"]`)!.value;value=normalizeClipFilters({...value,kinds:field('kind')?[field('kind') as ClipFilters['kinds'][number]]:[],sources:field('source')?[field('source')]:[],period:field('period') as ClipFilters['period'],from:field('from'),to:field('to'),size:field('size') as ClipFilters['size'],extensions:field('extensions').split(/[,，\s]+/),tags:field('tags').split(/[,，]+/)});panel.querySelector<HTMLElement>('.quick-filter-dates')!.hidden=value.period!=='custom';refresh();changed();};
  panel.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-field],[data-filter-date]').forEach(field=>field.onchange=read);bindDatePickers(panel);
  panel.querySelectorAll<HTMLButtonElement>('[data-status]').forEach(toggle=>toggle.onclick=()=>{const name=toggle.dataset.status as 'favorite'|'pinned';value={...value,[name]:!value[name]||undefined};toggle.setAttribute('aria-pressed',String(!!value[name]));refresh();changed();});
  panel.querySelector<HTMLButtonElement>('[data-reset]')!.onclick=()=>{value=emptyClipFilters();draw();refresh();changed();};
 }
 button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-expanded','false');button.onclick=()=>{if(opened){close();return;}opening();draw();opened=true;button.setAttribute('aria-expanded','true');openAnchoredPopover(panel,button,340,460);document.addEventListener('pointerdown',outside,true);document.addEventListener('keydown',keyboard,true);requestAnimationFrame(()=>panel.querySelector<HTMLElement>('.custom-select,select')?.focus());};refresh();
 return {get value(){return value;},update(state:TrayState){sources=state.sources||[];const select=panel.querySelector<HTMLSelectElement>('[data-field=source]');if(opened&&select)select.innerHTML=sourceOptions();},close,reset(){close();value=emptyClipFilters();refresh();}};
}
