import {t as tr} from '../shared/i18n';
import './locale';
import './appearance';
document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';
import './recovery.css';
import {checkpointDescription} from './checkpoint-ui';
import {formatDate} from '../shared/i18n';
import type {RecoveryAPI,RecoveryChoice} from '../shared/recovery';
const api=(window as unknown as {recovery:RecoveryAPI}).recovery;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let choice:RecoveryChoice|null=null,processing=false;
async function work(action:()=>Promise<void>){if(processing)return;processing=true;$('feedback').textContent='';const controls=Array.from(document.querySelectorAll<HTMLButtonElement|HTMLInputElement>('button,input')),disabled=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);$('progress').textContent=tr('正在处理，请稍候…');try{await action();}catch(e){$('feedback').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{controls.forEach((c,i)=>{if(c.isConnected)c.disabled=disabled[i];});processing=false;$('progress').textContent=tr('所有恢复操作均在本机完成');}}
async function preview(password?:string){if(!choice)return;const newPassword=$<HTMLInputElement>('new-password').value;if(choice.requiresProtection&&(newPassword.length<12||newPassword!==$<HTMLInputElement>('repeat-password').value))throw new Error(tr('新密码至少 12 个字符，且两次填写一致'));const result=await api.preview(choice.token,password,choice.requiresProtection?newPassword:undefined,$<HTMLInputElement>('source-key').checked?'recovery':'password');$<HTMLInputElement>('new-password').value='';$<HTMLInputElement>('repeat-password').value='';$('recovery-key-fields').hidden=!result.recoveryKey;$('recovery-key').textContent=result.recoveryKey||'';$<HTMLInputElement>('password').value='';$('unlock').hidden=true;$('summary').hidden=false;$('preview-title').textContent=tr('资料已通过校验');$('counts').replaceChildren(...(['clips','snippets','categories','scripts'] as const).map((key,index)=>{const card=document.createElement('div'),number=document.createElement('b');number.textContent=String(result[key]);card.append(number,document.createTextNode([tr('历史记录'),tr('模板'),tr('分类'),tr('脚本')][index]));return card;}));}
async function select(value:RecoveryChoice|null){choice=value;if(!choice)return;$('choices').hidden=true;$('preview').hidden=false;$('summary').hidden=true;$('preview-title').textContent=tr('校验资料');$('source').textContent=choice.name;$('unlock').hidden=!(choice.encrypted||choice.requiresProtection);$('password').parentElement!.hidden=!choice.encrypted;$('password-label').hidden=!choice.encrypted;$('password-label').textContent=choice.kind==='database'?tr('资料密码或恢复密钥'):tr('备份密码');$<HTMLInputElement>('password').placeholder=choice.kind==='database'?tr('密码或 C7- 开头的恢复密钥'):tr('备份密码');$('source-key-choice').hidden=choice.kind!=='database'||!choice.encrypted;$<HTMLInputElement>('source-key').checked=false;$('protection-fields').hidden=!choice.requiresProtection;if(choice.encrypted)$('password').focus();else if(choice.requiresProtection)$('new-password').focus();else await preview();}
for(const kind of ['database','backup'] as const)$('choose-'+kind).onclick=()=>void work(async()=>select(await api.choose(kind)));
$('unlock').onsubmit=event=>{event.preventDefault();void work(()=>preview($<HTMLInputElement>('password').value));};
$('commit').onclick=()=>void work(async()=>{if(choice)await api.commit(choice.token,$<HTMLInputElement>('recovery-proof').value);});
$('retry').onclick=()=>void work(()=>api.retry());$('quit').onclick=()=>void api.quit();
$('cancel').onclick=()=>void work(async()=>{await api.cancel();choice=null;for(const input of document.querySelectorAll('input'))input.value='';$('recovery-key').textContent='';$('preview').hidden=true;$('choices').hidden=false;});
void work(async()=>{const state=await api.state();$('startup-error').textContent=state.error;$('destination').textContent=tr('恢复副本将保存在：')+state.directory;const points=await api.checkpoints(),list=$('startup-checkpoints');if(!points.length){$('checkpoint-options').hidden=true;return;}for(const point of points){const button=document.createElement('button');button.className='option';button.dataset.startupCheckpoint=point.id;button.disabled=!point.compatible;const title=document.createElement('b'),meta=document.createElement('span');title.textContent=formatDate(point.createdAt);meta.textContent=checkpointDescription(point)+(point.compatible?'':' · '+tr('需要匹配的新版程序'));button.append(title,meta);button.onclick=()=>void work(async()=>select(await api.chooseCheckpoint(point.id)));list.append(button);}});
