import './recorder.css';
import {cropStream} from './region-stream';
import {createElement,Video} from 'lucide';
import {recordingMime,RECORD_CHUNK,RECORD_SECONDS,type RecorderAPI,type RecordingOptions,type RecordingSource,type RecordingState} from '../shared/recording';
declare global {interface Window{clipperRecorder:RecorderAPI}}
const api=window.clipperRecorder,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
q('brand').appendChild(createElement(Video,{'aria-hidden':'true','stroke-width':1.7}));
const format=(seconds:number)=>[Math.floor(seconds/60),Math.floor(seconds%60)].map(s=>String(s).padStart(2,'0')).join(':'),size=(bytes:number)=>(bytes/1048576).toFixed(1)+' MB';
const error=(value:unknown)=>{q('message').textContent=String(value instanceof Error?value.message:value).replace(/^Error invoking remote method '[^']+': Error: /,'');};
let state:RecordingState|undefined,sources:RecordingSource[]=[],sourceId='',sourceType:'screen'|'window'='screen',refreshId=0;
interface Run{abort:AbortController;cropDispose?:()=>void;token:string;streams:MediaStream[];context?:AudioContext;recorder?:MediaRecorder;analyser?:AnalyserNode;chain:Promise<void>;sequence:number;queued:number;written:number;started:number;pausedAt:number;pausedMs:number;ending:boolean;reason:string;timer?:ReturnType<typeof setInterval>}
let sourceRequest=0,choosingRegion=false;let run:Run|undefined;let regionChoice:{token:string;width:number;height:number}|undefined;function regionLabel(){q('region-label').textContent=regionChoice?`${regionChoice.width} × ${regionChoice.height} 像素选区`:'录制整个来源';q('clear-region').hidden=!regionChoice;q<HTMLButtonElement>('choose-region').disabled=!sourceId.startsWith('screen:');}function clearRegion(){regionChoice=undefined;regionLabel();}
const elapsed=(r:Run)=>(r.started?((r.pausedAt||performance.now())-r.started-r.pausedMs)/1000:0);
function release(r:Run){r.abort.abort();r.cropDispose?.();clearInterval(r.timer);if(r.recorder){r.recorder.ondataavailable=null;r.recorder.onstop=null;r.recorder.onerror=null;if(r.recorder.state!=='inactive')r.recorder.stop();}for(const stream of r.streams)for(const track of stream.getTracks())track.stop();void r.context?.close().catch(()=>{});if(run===r)run=undefined;}
async function fail(r:Run,value:unknown){if(run!==r)return;release(r);await api.fail(r.token,String(value instanceof Error?value.message:value)).catch(()=>{});error(value);}
async function accept(r:Run,promise:Promise<MediaStream>){const stream=await promise;if(run!==r){stream.getTracks().forEach(t=>t.stop());throw new Error('录制已取消');}r.streams.push(stream);return stream;}
function renderSources(){const list=q('sources');list.replaceChildren();const filtered=sources.filter(s=>s.type===sourceType);if(!filtered.some(s=>s.id===sourceId)){sourceId=filtered[0]?.id||'';clearRegion();}regionLabel();for(const source of filtered){const b=document.createElement('button'),image=document.createElement('img'),label=document.createElement('span');image.src=source.thumbnail;image.alt='';label.textContent=source.name;b.title=source.name;b.dataset.id=source.id;b.setAttribute('aria-pressed',String(source.id===sourceId));b.append(image,label);b.onclick=()=>{if(sourceId!==source.id)clearRegion();sourceId=source.id;renderSources();};list.append(b);}if(!filtered.length){const p=document.createElement('p');p.className='empty';p.textContent='没有可用来源，可打开窗口后刷新';list.append(p);}}
async function loadSources(){if(choosingRegion)return;const request=++sourceRequest;q<HTMLButtonElement>('refresh').disabled=true;try{const next=await api.sources();if(request!==sourceRequest||choosingRegion||state?.phase!=='idle')return;sources=next;renderSources();}catch(e){if(request===sourceRequest)error(e);}finally{if(request===sourceRequest&&!choosingRegion)q<HTMLButtonElement>('refresh').disabled=false;}}
async function refresh(){const id=++refreshId;try{const next=await api.state();if(id!==refreshId)return;const previous=state;state=next;document.documentElement.dataset.theme=next.dark?'dark':'light';const active=['arming','recording','paused','stopping'].includes(next.phase);document.documentElement.dataset.recording=String(active);q('setup').hidden=next.phase!=='idle';q('active').hidden=!active;q('result').hidden=!['ready','saving'].includes(next.phase);q('message').textContent=next.message;q('phase-label').textContent=({arming:'正在准备',recording:'正在录制',paused:'已暂停',stopping:'正在处理'} as Record<string,string>)[next.phase]||'';q<HTMLButtonElement>('pause').disabled=!['recording','paused'].includes(next.phase);q('pause').textContent=next.phase==='paused'?'继续':'暂停';q<HTMLButtonElement>('stop').disabled=!['recording','paused'].includes(next.phase);q('size').textContent=size(next.bytes);if(next.phase==='arming')q('elapsed').textContent='00:00';q('saved').textContent=next.saved?'已保存：'+next.saved:'';q<HTMLButtonElement>('copy-saved').disabled=!next.saved||next.phase!=='ready';q<HTMLButtonElement>('save').disabled=next.phase==='saving';q<HTMLButtonElement>('again').disabled=next.phase==='saving';if(run&&next.token!==run.token&&run.token)release(run);if(next.url){const video=q<HTMLVideoElement>('preview');if(video.getAttribute('src')!==next.url)video.src=next.url;q('summary').textContent=`${format(next.seconds)} · ${size(next.bytes)} · ${next.options?.mode==='audio'?'M4A 音频':'MP4 视频'}`;}else{const video=q<HTMLVideoElement>('preview');if(video.hasAttribute('src')){video.pause();video.removeAttribute('src');video.load();}}if(next.phase==='idle'&&previous?.phase!=='idle'){clearRegion();void loadSources();}}catch(e){if(run)release(run);error(e);}}
async function start(){if(run)return;const options:RecordingOptions={mode:(document.querySelector<HTMLInputElement>('[name=mode]:checked')!.value as 'video'|'audio'),sourceId,systemAudio:q<HTMLInputElement>('system-audio').checked,microphone:q<HTMLInputElement>('microphone').checked,microphoneId:q<HTMLSelectElement>('microphone-device').value,fps:Number(q<HTMLSelectElement>('fps').value) as 15|30|60,maxWidth:Number(q<HTMLSelectElement>('resolution').value) as 1920|2560,...(regionChoice?{regionToken:regionChoice.token}:{})};const mime=recordingMime(options.mode,options.systemAudio||options.microphone);if(!MediaRecorder.isTypeSupported(mime)){error('此系统不支持所需的 H.264/AAC 编码器，请安装 Windows 媒体功能后重试');return;}const r:Run={abort:new AbortController(),token:'',streams:[],chain:Promise.resolve(),sequence:0,queued:0,written:0,started:0,pausedAt:0,pausedMs:0,ending:false,reason:''};run=r;q<HTMLButtonElement>('start').disabled=true;
 try{r.token=await api.arm(options);if(run!==r)throw new Error('录制已取消');const region=(await api.state()).region;if(run!==r)throw new Error('录制已取消');let desktop:MediaStream|undefined,mic:MediaStream|undefined;const mixed=new MediaStream();
  if(options.mode==='video'||options.systemAudio){desktop=await accept(r,navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:options.fps,max:options.fps},width:{max:region?.screen.width||options.maxWidth},height:{max:region?.screen.height||options.maxWidth}},audio:options.systemAudio}));if(options.systemAudio&&!desktop.getAudioTracks().length)throw new Error('没有取得系统声音轨道');if(options.mode==='video'){const video=desktop.getVideoTracks()[0];if(!video)throw new Error('没有取得画面轨道');if(region){const cropped=await cropStream(desktop,region,options.maxWidth,options.fps,r.abort.signal,()=>{if(r.recorder?.state==='recording'||r.recorder?.state==='paused')stop('显示器画面尺寸已改变，请重新选择区域');else void fail(r,'显示器画面尺寸已改变，请重新选择区域');});r.cropDispose=cropped.dispose;r.streams.push(cropped.stream);if(run!==r){cropped.dispose();throw new Error('录制已取消');}mixed.addTrack(cropped.stream.getVideoTracks()[0]);}else mixed.addTrack(video);}else desktop.getVideoTracks().forEach(t=>t.stop());}
  if(options.microphone){mic=await accept(r,navigator.mediaDevices.getUserMedia({video:false,audio:options.microphoneId?{deviceId:{exact:options.microphoneId},echoCancellation:true}:{echoCancellation:true}}));if(!mic.getAudioTracks().length)throw new Error('没有取得麦克风轨道');}
  const audio=[desktop,mic].filter((s):s is MediaStream=>!!s&&s.getAudioTracks().length>0);if(audio.length){const context=new AudioContext();r.context=context;await context.resume();if(run!==r)throw new Error('录制已取消');const destination=context.createMediaStreamDestination(),analyser=context.createAnalyser();analyser.fftSize=256;r.analyser=analyser;for(const stream of audio){const input=context.createMediaStreamSource(new MediaStream(stream.getAudioTracks()));const gain=context.createGain();gain.gain.value=audio.length>1?.5:1;input.connect(gain);gain.connect(destination);gain.connect(analyser);}mixed.addTrack(destination.stream.getAudioTracks()[0]);r.streams.push(destination.stream);}
  const recorder=new MediaRecorder(mixed,{mimeType:mime,videoBitsPerSecond:options.maxWidth===2560?12000000:6000000,audioBitsPerSecond:128000});r.recorder=recorder;
  recorder.ondataavailable=e=>{if(run!==r||!e.data.size)return;if(r.queued+e.data.size>RECORD_CHUNK*3){void fail(r,'磁盘写入跟不上录制，已停止；请降低帧率后重试');return;}r.queued+=e.data.size;r.chain=r.chain.then(async()=>{const data=new Uint8Array(await e.data.arrayBuffer());for(let offset=0;offset<data.byteLength;offset+=RECORD_CHUNK){if(run!==r)throw new Error('录制已取消');const part=data.subarray(offset,offset+RECORD_CHUNK);await api.chunk(r.token,r.sequence++,part);r.written+=part.length;q('size').textContent=size(r.written);}}).finally(()=>r.queued-=e.data.size);void r.chain.catch(e=>fail(r,e));};
  recorder.onerror=e=>void fail(r,(e as ErrorEvent).error||'编码器失败');recorder.onstop=()=>{if(run!==r)return;const duration=Math.min(RECORD_SECONDS+5,elapsed(r));for(const stream of r.streams)stream.getTracks().forEach(t=>t.stop());void r.chain.then(async()=>{if(run!==r)return;await api.finish(r.token,duration,r.reason,recorder.mimeType);release(r);await refresh();}).catch(e=>fail(r,e));};
  await api.started(r.token,recorder.mimeType);if(run!==r)throw new Error('录制已取消');r.started=performance.now();recorder.start(750);for(const stream of r.streams)for(const track of stream.getTracks())track.onended=()=>{if(run===r&&!r.ending)stop('录制来源已结束');};r.timer=setInterval(()=>{if(run!==r)return;const seconds=elapsed(r);q('elapsed').textContent=format(seconds);const samples=new Float32Array(r.analyser?.fftSize||0);r.analyser?.getFloatTimeDomainData(samples);q<HTMLMeterElement>('level').value=samples.length?Math.min(1,Math.sqrt(samples.reduce((sum,v)=>sum+v*v,0)/samples.length)*5):0;void api.heartbeat(r.token,Math.min(RECORD_SECONDS+5,seconds)).catch(e=>fail(r,e));if(seconds>=RECORD_SECONDS)stop('已达到 60 分钟上限');},500);await refresh();
 }catch(e){if(run===r)await fail(r,e);else release(r);}finally{q<HTMLButtonElement>('start').disabled=false;}}
function stop(reason=''){const r=run;if(!r||r.ending||!r.recorder||r.recorder.state==='inactive')return;r.ending=true;r.reason=reason;if(r.pausedAt){r.pausedMs+=performance.now()-r.pausedAt;r.pausedAt=0;}r.recorder.stop();q('phase-label').textContent='正在处理';q<HTMLButtonElement>('stop').disabled=true;q<HTMLButtonElement>('pause').disabled=true;}
q('choose-region').onclick=()=>{choosingRegion=true;sourceRequest++;q<HTMLButtonElement>('refresh').disabled=true;q<HTMLButtonElement>('start').disabled=true;q<HTMLButtonElement>('choose-region').disabled=true;void api.chooseRegion(sourceId).then(result=>{if(result)regionChoice=result;regionLabel();}).catch(error).finally(()=>{choosingRegion=false;q<HTMLButtonElement>('refresh').disabled=false;q<HTMLButtonElement>('start').disabled=false;regionLabel();});};q('clear-region').onclick=clearRegion;q('start').onclick=()=>void start();q('stop').onclick=()=>stop();q('pause').onclick=async()=>{const r=run;if(!r?.recorder||r.ending)return;try{const pause=r.recorder.state==='recording';if(pause){r.recorder.pause();r.pausedAt=performance.now();}else{r.recorder.resume();r.pausedMs+=performance.now()-r.pausedAt;r.pausedAt=0;}await api.paused(r.token,pause);await refresh();}catch(e){void fail(r,e);}};
const discard=async()=>{if((run||!state?.saved)&&!confirm('放弃尚未保存的录制？'))return;if(run)release(run);await api.cancel();await refresh();};q('discard').onclick=()=>void discard().catch(error);q('again').onclick=()=>void discard().catch(error);q('copy-saved').onclick=()=>void api.copySaved().then(()=>{q('message').textContent='已复制文件并加入历史';}).catch(error);q<HTMLVideoElement>('preview').onerror=()=>{if(state?.url)error('无法播放录制文件，请重试保存或重新录制');};q('save').onclick=()=>void api.save().then(refresh).catch(error);q('refresh').onclick=()=>void loadSources();
for(const type of ['screen','window'] as const)q(type==='screen'?'screens':'windows').onclick=()=>{sourceType=type;q('screens').setAttribute('aria-pressed',String(type==='screen'));q('windows').setAttribute('aria-pressed',String(type==='window'));renderSources();};document.querySelectorAll<HTMLInputElement>('[name=mode]').forEach(input=>input.onchange=()=>{q('video-settings').hidden=input.value==='audio';if(input.value==='audio')clearRegion();});
q('microphone').onchange=()=>{q<HTMLSelectElement>('microphone-device').disabled=!q<HTMLInputElement>('microphone').checked;};q<HTMLSelectElement>('microphone-device').disabled=true;
void navigator.mediaDevices.enumerateDevices().then(devices=>{let i=0;for(const device of devices.filter(d=>d.kind==='audioinput'&&d.deviceId&&d.deviceId!=='default')){const o=document.createElement('option');o.value=device.deviceId;o.textContent=device.label||`麦克风 ${++i}`;q('microphone-device').appendChild(o);}}).catch(()=>{});
api.onChange(()=>void refresh());api.onStop(()=>{void api.state().then(next=>{if(run&&next.token===run.token&&next.phase==='stopping')stop(next.message);else if(run)release(run);}).catch(()=>{if(run)release(run);});});window.addEventListener('beforeunload',()=>{if(run)release(run);});void refresh();
