import './recovery.css';
import type {RecoveryAPI,RecoveryChoice} from '../shared/recovery';
const api=(window as unknown as {recovery:RecoveryAPI}).recovery;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let choice:RecoveryChoice|null=null;
async function work(action:()=>Promise<void>){$('feedback').textContent='';document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);$('progress').textContent='正在处理，请稍候…';try{await action();}catch(e){$('feedback').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);$('progress').textContent='所有恢复操作均在本机完成';}}
async function preview(password?:string){if(!choice)return;const newPassword=$<HTMLInputElement>('new-password').value;if(choice.requiresProtection&&(newPassword.length<12||newPassword!==$<HTMLInputElement>('repeat-password').value))throw new Error('新密码至少 12 个字符，且两次填写一致');const result=await api.preview(choice.token,password,choice.requiresProtection?newPassword:undefined,$<HTMLInputElement>('source-key').checked?'recovery':'password');$<HTMLInputElement>('new-password').value='';$<HTMLInputElement>('repeat-password').value='';$('recovery-key-fields').hidden=!result.recoveryKey;$('recovery-key').textContent=result.recoveryKey||'';$<HTMLInputElement>('password').value='';$('unlock').hidden=true;$('summary').hidden=false;$('preview-title').textContent='资料已通过校验';$('counts').replaceChildren(...(['clips','snippets','categories','scripts'] as const).map((key,index)=>{const card=document.createElement('div'),number=document.createElement('b');number.textContent=String(result[key]);card.append(number,document.createTextNode(['历史记录','模板','分类','脚本'][index]));return card;}));}
for(const kind of ['database','backup'] as const)$('choose-'+kind).onclick=()=>void work(async()=>{choice=await api.choose(kind);if(!choice)return;$('choices').hidden=true;$('preview').hidden=false;$('summary').hidden=true;$('preview-title').textContent='校验资料';$('source').textContent=choice.name;$('unlock').hidden=!(choice.encrypted||choice.requiresProtection);$('password').parentElement!.hidden=!choice.encrypted;$('password-label').hidden=!choice.encrypted;$('password-label').textContent=choice.kind==='database'?'资料密码或恢复密钥':'备份密码';$<HTMLInputElement>('password').placeholder=choice.kind==='database'?'密码或 C7- 开头的恢复密钥':'备份密码';$('source-key-choice').hidden=choice.kind!=='database'||!choice.encrypted;$<HTMLInputElement>('source-key').checked=false;$('protection-fields').hidden=!choice.requiresProtection;if(choice.encrypted)$('password').focus();else if(choice.requiresProtection)$('new-password').focus();else await preview();});
$('unlock').onsubmit=event=>{event.preventDefault();void work(()=>preview($<HTMLInputElement>('password').value));};
$('commit').onclick=()=>void work(async()=>{if(choice)await api.commit(choice.token,$<HTMLInputElement>('recovery-proof').value);});
$('retry').onclick=()=>void work(()=>api.retry());$('quit').onclick=()=>void api.quit();
$('cancel').onclick=()=>void work(async()=>{await api.cancel();choice=null;for(const input of document.querySelectorAll('input'))input.value='';$('recovery-key').textContent='';$('preview').hidden=true;$('choices').hidden=false;});
void work(async()=>{const state=await api.state();$('startup-error').textContent=state.error;$('destination').textContent='恢复副本将保存在：'+state.directory;});
