import './scroll.css';
import {createElement,ScanLine} from 'lucide';
import type {ScrollAPI,ScrollState} from '../shared/scroll';
declare global {interface Window{clipperScroll:ScrollAPI}}
const api=window.clipperScroll,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;let state:ScrollState|undefined,busy=false,refreshId=0;
q('brand').appendChild(createElement(ScanLine,{'aria-hidden':'true','stroke-width':1.7}));
const error=(e:unknown)=>q('message').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');
function seam(){const a=q<HTMLImageElement>('previous'),b=q<HTMLImageElement>('next'),c=q<HTMLCanvasElement>('seam'),height=state?.pending?.height,overlap=q<HTMLInputElement>('overlap').valueAsNumber;if(!height||!a.complete||!b.complete||!a.naturalWidth||!b.naturalWidth||!Number.isInteger(overlap)||overlap<0||overlap>=height)return;const cut=overlap/height*b.naturalHeight,bottom=Math.min(120,a.naturalHeight),remaining=Math.min(120,b.naturalHeight-cut);c.width=b.naturalWidth;c.height=Math.ceil(bottom+remaining);const ctx=c.getContext('2d')!;ctx.drawImage(a,0,a.naturalHeight-bottom,a.naturalWidth,bottom,0,0,c.width,bottom);ctx.drawImage(b,0,cut,b.naturalWidth,remaining,0,bottom,c.width,remaining);}
q<HTMLInputElement>('overlap').oninput=seam;q<HTMLImageElement>('previous').onload=seam;q<HTMLImageElement>('next').onload=seam;
async function refresh(){const id=++refreshId;try{const next=await api.state();if(id!==refreshId)return;const previous=state;state=next;document.documentElement.dataset.theme=next.dark?'dark':'light';document.documentElement.dataset.compact=String(next.phase==='capturing');q('setup').hidden=!['idle','picking'].includes(next.phase);q('capture').hidden=next.phase!=='capturing';q('alignment').hidden=next.phase!=='aligning';q('result').hidden=!['ready','saving'].includes(next.phase);const summary=`${next.frames} 屏 · ${next.width} × ${next.height} 像素`;q('progress').textContent=summary;q('summary').textContent=summary;q('message').textContent=next.message;for(const b of document.querySelectorAll<HTMLButtonElement>('button'))b.disabled=busy||next.phase==='picking'||next.phase==='saving';q<HTMLButtonElement>('undo').disabled=busy||!next.canUndo;if(next.url&&q<HTMLImageElement>('preview').getAttribute('src')!==next.url)q<HTMLImageElement>('preview').src=next.url;if(!next.url)q<HTMLImageElement>('preview').removeAttribute('src');if(next.pending){q<HTMLImageElement>('previous').src=next.pending.previous;q<HTMLImageElement>('next').src=next.pending.next;q<HTMLInputElement>('overlap').max=String(next.pending.height-1);if(previous?.phase!=='aligning')q<HTMLInputElement>('overlap').value=String(next.pending.suggested);q('overlap-range').textContent=`0–${next.pending.height-1} 像素`;}else{q<HTMLImageElement>('previous').removeAttribute('src');q<HTMLImageElement>('next').removeAttribute('src');}}catch(e){error(e);}}
async function action(fn:()=>Promise<unknown>){if(busy)return;busy=true;void refresh();let failure:unknown;try{await fn();}catch(e){failure=e;}finally{busy=false;await refresh();if(failure)error(failure);}}
q('start').onclick=()=>void action(()=>api.start(Number(q<HTMLSelectElement>('display').value)));q('append').onclick=()=>void action(()=>api.append());q('align').onclick=()=>void action(()=>api.align(q<HTMLInputElement>('overlap').valueAsNumber));q('reject').onclick=()=>void action(()=>api.reject());q('undo').onclick=()=>void action(()=>api.undo());q('finish').onclick=()=>void action(()=>api.finish());q('save').onclick=()=>void action(()=>api.save());q('copy').onclick=()=>void action(()=>api.copy());const discard=()=>{if(state&&!state.saved&&!confirm('放弃尚未保存的长截图？'))return;void action(()=>api.cancel());};q('discard').onclick=discard;q('new').onclick=discard;
api.onChange(()=>void refresh());void api.screens().then(displays=>{for(const d of displays){const option=document.createElement('option');option.value=String(d.id);option.textContent=d.name;q('display').appendChild(option);}}).catch(error);void refresh();
