import type {Settings} from '../shared/types';
import {onRemoval} from './controls';
import {shortcutLabel} from '../shared/shortcut';
import {shortcutFeedback} from './shortcut';
const keys:Record<string,keyof Settings>={'tray-click-action':'trayClickAction','launch-login':'launchAtLogin','max-items':'maxItems','retention':'retentionDays','history-cap':'maxHistoryMiB','excluded-apps':'excludedApps',shortcut:'shortcut',nextShortcut:'nextShortcut'};
/** Read the latest persisted settings before each patch, preserving other windows' edits. */
export function bindSettingsPreferences(root:HTMLElement,initial:Settings,report:(error:unknown)=>void){
 let chain=Promise.resolve();const timers=new Map<string,ReturnType<typeof setTimeout>>(),saved={...initial,trayClickAction:initial.trayClickAction||'open'};
 const read=(node:HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement)=>node instanceof HTMLSelectElement?node.value:node.dataset.value!==undefined?node.dataset.value:node instanceof HTMLInputElement&&node.type==='checkbox'?node.checked:node instanceof HTMLInputElement&&node.type==='number'?Number(node.value):node.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean);
 const persist=(patch:Partial<Settings>,rollback:(error:unknown)=>void,success?:()=>void)=>{chain=chain.catch(()=>{}).then(async()=>{try{const latest=await window.clip.state();await window.clip.settings({...latest.settings,...patch});Object.assign(saved,patch);success?.();}catch(error){rollback(error);}});};
 const commit=(node:HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement)=>{clearTimeout(timers.get(node.id));timers.delete(node.id);if(!node.checkValidity())return;const key=keys[node.id];if(!key)return;const value=read(node);if(JSON.stringify(value)===JSON.stringify(saved[key]))return;persist({[key]:value},error=>{if(JSON.stringify(read(node))!==JSON.stringify(value))return;const before=saved[key];if(node.dataset.value!==undefined){node.dataset.value=String(before);node.value=shortcutLabel(String(before));}else if(node instanceof HTMLInputElement&&node.type==='checkbox')node.checked=!!before;else node.value=Array.isArray(before)?before.join('\n'):String(before);node.dispatchEvent(new Event('clip:preference-rollback'));if(node instanceof HTMLSelectElement)node.dispatchEvent(new Event('change'));if(node instanceof HTMLInputElement&&node.dataset.shortcutControl&&shortcutFeedback(node,error,()=>{node.dataset.value=String(value);node.value=shortcutLabel(String(value));commit(node);})){return;}report(error);},()=>{if(node instanceof HTMLInputElement&&read(node)===value)shortcutFeedback(node);});};
 const changed=(event:Event)=>{const node=event.target;if(!(node instanceof HTMLInputElement||node instanceof HTMLTextAreaElement||node instanceof HTMLSelectElement)||!keys[node.id]||!node.checkValidity())return;clearTimeout(timers.get(node.id));if(event.type==='input'&&!(node instanceof HTMLInputElement&&node.type==='checkbox'))timers.set(node.id,setTimeout(()=>commit(node),250));else commit(node);};
 root.addEventListener('input',changed);root.addEventListener('change',changed);root.addEventListener('focusout',event=>{const node=event.target;if(node instanceof HTMLInputElement||node instanceof HTMLTextAreaElement||node instanceof HTMLSelectElement){if(timers.has(node.id))commit(node);}});
 for(const button of root.querySelectorAll<HTMLButtonElement>('[data-theme-choice]'))button.onclick=()=>{const theme=button.dataset.themeChoice as Settings['theme'];const draw=(value:Settings['theme'])=>root.querySelectorAll<HTMLElement>('[data-theme-choice]').forEach(node=>{node.classList.toggle('active',node.dataset.themeChoice===value);node.setAttribute('aria-pressed',String(node.dataset.themeChoice===value));});draw(theme);persist({theme},error=>{draw(saved.theme);report(error);});};
 onRemoval(root,()=>{for(const timer of timers.values())clearTimeout(timer);});
}
