import type {StackOptions,StackPreview} from '../shared/stack';
const api=window.clipper,esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const input=<T extends HTMLElement=HTMLInputElement>(id:string)=>document.getElementById(id) as T;
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void}
export function stackUI(ctx:Context){
 async function rules(){const {options:o,running}=await api.stackState();if(running)throw new Error('请先停止自动入栈再修改规则');
  ctx.modal('堆栈规则',`<div class="stack-rule-grid"><label class="field">内容类型<select id="stack-kind">${['all','text','link','code','image','files'].map((v,i)=>`<option value="${v}" ${o.kind===v?'selected':''}>${['全部','文字','链接','代码','图片','文件'][i]}</option>`).join('')}</select></label><label class="field">加入方式<select id="stack-mode"><option value="whole" ${o.mode==='whole'?'selected':''}>整条加入</option><option value="lines" ${o.mode==='lines'?'selected':''}>文字按行拆分</option></select></label></div><label class="field">来源应用（可选）<input id="stack-source" maxlength="256" value="${esc(o.source)}" placeholder="进程名，例如 notepad.exe"></label><label class="field">包含文字（可选）<input id="stack-contains" maxlength="256" value="${esc(o.contains)}" placeholder="正文、文件路径或附件名称"></label><label class="efficiency-toggle"><input id="stack-trim" type="checkbox" ${o.trim?'checked':''}>拆分时去除每行首尾空白</label><p class="field-help">同时满足条件才加入。按行拆分保存为纯文本并跳过空行；图片和文件仍需选择整条加入。相同内容保持第一次入栈的位置，最多 200 项。</p>`,async()=>{const next:StackOptions={kind:input<HTMLSelectElement>('stack-kind').value as StackOptions['kind'],source:input('stack-source').value,contains:input('stack-contains').value,mode:input<HTMLSelectElement>('stack-mode').value as StackOptions['mode'],trim:input('stack-trim').checked};await api.configureStack(next);ctx.toast('已保存堆栈规则');});
 }
 async function batch(){let preview:StackPreview|undefined,request=0;
  ctx.modal('批量入栈',`<p class="field-help">使用已保存的堆栈规则筛选历史，只追加到队尾，原记录保留。</p><div class="stack-preview-toolbar"><label class="field">排列顺序<select id="stack-order"><option value="oldest">由旧到新</option><option value="newest">由新到旧</option></select></label><button id="stack-preview" type="button">预览匹配结果</button></div><p id="stack-summary" role="status">先预览，再确认加入。</p><ol id="stack-samples" class="stack-samples"></ol>`,async()=>{if(!preview)throw new Error('请先预览匹配结果');const count=await api.commitStack(preview.token);ctx.toast(`已加入 ${count} 项`);},'加入堆栈');
  const dialog=input<HTMLDialogElement>('dialog'),summary=input('stack-summary'),samples=input('stack-samples'),submit=dialog.querySelector<HTMLButtonElement>('[type=submit]')!,button=input<HTMLButtonElement>('stack-preview');submit.disabled=true;
  dialog.addEventListener('close',()=>{request++;void api.cancelStackPreview().catch(()=>{});},{once:true});
  input<HTMLSelectElement>('stack-order').onchange=()=>{request++;preview=undefined;submit.disabled=true;summary.textContent='顺序已改变，请重新预览。';samples.innerHTML='';};
  button.onclick=()=>{const current=++request;button.disabled=true;submit.disabled=true;void api.previewStack(input<HTMLSelectElement>('stack-order').value as 'oldest'|'newest').then(result=>{if(current!==request||!dialog.open)return;preview=result;summary.textContent=`匹配 ${result.matched} 条历史，可新增 ${result.added} 项，跳过重复 ${result.duplicates} 项${result.added>12?'（下方显示前 12 项）':''}。`;samples.innerHTML=result.samples.map(s=>`<li>${esc(s)}</li>`).join('');submit.disabled=result.added===0;}).catch(error=>{if(current===request&&dialog.open){preview=undefined;summary.textContent=String((error as Error).message).replace(/^Error invoking remote method '[^']+': Error: /,'');}}).finally(()=>button.disabled=false);};
 }
 return {rules,batch};
}
