import type {SyncState} from '../shared/sync';
import './sync.css';
const api=window.clipper,$=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
interface Context {active():boolean;toast(value:unknown):void;modal(title:string,body:string,save:()=>Promise<void>,label?:string):void}
export function syncUI(ctx:Context){
 let generation=0;const on=(id:string,fn:()=>unknown)=>$(id)?.addEventListener('click',()=>void Promise.resolve().then(fn).catch(ctx.toast));
 function live(s:SyncState){if(!$('sync-live'))return;$('sync-live').innerHTML=`<div class="sync-metrics"><span>${s.enabled?'已启用':'已关闭'} · ${s.shared} 项共享 · ${s.peers.length} 台配对设备</span><button id="sync-refresh" ${s.enabled?'':'disabled'}>立即同步</button></div>${s.error?`<p class="sync-error" role="alert">${esc(s.error)}</p>`:''}<h2 class="section-label">配对设备</h2>${s.peers.length?s.peers.map(p=>`<article class="sync-device"><div><strong>${esc(p.name)}</strong><p>${esc(p.host)}:${p.port} · ${p.busy?'正在同步':p.lastSync?'最近同步 '+new Date(p.lastSync).toLocaleTimeString():'等待同步'}</p>${p.error?`<p class="sync-error">${esc(p.error)}</p>`:''}</div><button data-revoke="${p.id}">撤销信任</button></article>`).join(''):'<p class="field-help">配对后才允许同步。接收内容只加入历史，不会自动粘贴。</p>'}${s.pending.map(p=>`<article class="sync-request"><strong>${esc(p.name)} 请求配对</strong><p>${esc(p.host)} · 指纹 ${esc(p.fingerprint.slice(0,16))}…</p><button data-approve="${p.id}" class="primary">允许配对</button><button data-deny="${p.id}">拒绝</button></article>`).join('')}${s.joining?`<p class="field-help">等待 ${esc(s.joining)} 确认配对… <button id="sync-cancel-join">取消</button></p>`:''}<h2 class="section-label">附近的 Clipper</h2>${s.nearby.length?s.nearby.map(p=>`<div class="sync-nearby"><strong>${esc(p.name)}</strong><span>${esc(p.host)}:${p.port}</span></div>`).join(''):'<p class="field-help">暂无附近设备。可在另一台设备生成配对码，然后粘贴到这里。</p>'}`;
  on('sync-refresh',()=>api.syncNow());on('sync-cancel-join',()=>api.syncCancel());document.querySelectorAll<HTMLButtonElement>('[data-approve]').forEach(b=>b.onclick=()=>void api.syncApprove(b.dataset.approve!,true).catch(ctx.toast));document.querySelectorAll<HTMLButtonElement>('[data-deny]').forEach(b=>b.onclick=()=>void api.syncApprove(b.dataset.deny!,false).catch(ctx.toast));document.querySelectorAll<HTMLButtonElement>('[data-revoke]').forEach(b=>b.onclick=()=>ctx.modal('撤销设备信任','<p>该设备将不能继续同步。两端已经接收的内容仍保留；重新连接需要再次配对。</p>',()=>api.syncRevoke(b.dataset.revoke!),'撤销信任'));
  if($('sync-invitation')){$<HTMLTextAreaElement>('sync-invitation').value=s.invitation;$('sync-code-area').hidden=!s.invitation;$('sync-expiry').textContent=s.invitation?'有效至 '+new Date(s.expires).toLocaleTimeString()+'，仅使用一次':'';}
 }
 async function update(){if(!ctx.active())return;const s=await api.syncState();if(ctx.active())live(s);}
 async function render(){const token=++generation,s=await api.syncState();if(token!==generation||!ctx.active())return;
  $('content').innerHTML=`<section class="tools-page sync-page"><div class="page-heading"><div><h1>局域网同步</h1><p>让信任的电脑共享文字与图片</p></div><span class="version">v0.7.0</span></div><div class="tools-scroll"><h2 class="section-label">本机</h2><label class="field">设备名称<input id="sync-name" maxlength="60" value="${esc(s.name)}"></label><label class="tool-check"><input id="sync-enabled" type="checkbox" ${s.enabled?'checked':''}>启用局域网同步</label><label class="tool-check"><input id="sync-auto" type="checkbox" ${s.autoNew?'checked':''}>自动同步之后新复制的文字与图片</label><p class="field-help">默认不发送已有历史。仅本机内容、文件路径、设置和密钥不发送。共享记录不受自动清理影响，手动删除会同步到配对设备。</p><button id="sync-save" class="primary">保存同步设置</button><div id="sync-live"></div><h2 class="section-label">添加设备</h2><p class="field-help">让两台电脑连接同一个局域网。生成配对码，交给另一台电脑，再核对设备名称并允许配对。Windows 防火墙需要允许 Clipper 访问专用网络。</p><div class="sync-pair-row"><select id="sync-address" aria-label="本机地址">${s.addresses.map(a=>`<option>${esc(a)}</option>`).join('')}</select><button id="sync-create" ${s.enabled&&s.addresses.length?'':'disabled'}>生成配对码</button></div><div id="sync-code-area" hidden><textarea id="sync-invitation" readonly rows="3" aria-label="本机配对码"></textarea><p id="sync-expiry" class="field-help"></p><button id="sync-select-code">选中配对码</button><button id="sync-cancel-code">取消配对码</button></div><label class="field">另一台设备的配对码<textarea id="sync-join-code" rows="3" maxlength="4096" placeholder="clipper-pair:…" spellcheck="false"></textarea></label><button id="sync-join" ${s.enabled?'':'disabled'}>请求配对</button><h2 class="section-label">选择已有内容</h2><p class="field-help">只分享主动选择的记录。不同电脑离线编辑同一内容时保留各自的新结果。</p><div id="sync-clips"></div></div></section>`;
  live(s);on('sync-save',async()=>{await api.syncConfigure({name:$<HTMLInputElement>('sync-name').value,enabled:$<HTMLInputElement>('sync-enabled').checked,autoNew:$<HTMLInputElement>('sync-auto').checked});await render();ctx.toast('同步设置已保存');});on('sync-create',async()=>{await api.syncInvite($<HTMLSelectElement>('sync-address').value);await update();});on('sync-select-code',()=>{$<HTMLTextAreaElement>('sync-invitation').focus();$<HTMLTextAreaElement>('sync-invitation').select();});on('sync-cancel-code',()=>api.syncCancel());on('sync-join',async()=>{await api.syncJoin($<HTMLTextAreaElement>('sync-join-code').value.trim());$<HTMLTextAreaElement>('sync-join-code').value='';await update();});await clips();
 }
 async function clips(){const state=await api.state();if(!ctx.active()||!$('sync-clips'))return;const list=state.clips.filter(c=>c.kind!=='files').slice(0,100);$('sync-clips').innerHTML=list.length?list.map(c=>`<article class="sync-device"><div><strong title="${esc(c.title)}">${esc(c.title)}</strong><p>${c.localOnly?'仅本机':c.shared?'已共享':'尚未共享'} · ${esc(c.source)}</p></div><div>${c.localOnly?`<button data-allow="${c.id}">允许共享</button>`:`${!c.shared?`<button data-share="${c.id}">共享此条</button>`:''}<button data-local="${c.id}">仅本机</button>`}</div></article>`).join(''):'<p class="field-help">复制一些文字或图片后，可在这里选择共享。最多展示最近 100 条。</p>';const act=(key:string,fn:(id:string)=>Promise<void>)=>document.querySelectorAll<HTMLButtonElement>('[data-'+key+']').forEach(b=>b.onclick=()=>void fn(b.dataset[key]!).then(clips).catch(ctx.toast));act('share',id=>api.syncShare(id));act('allow',id=>api.syncLocal(id,false));act('local',id=>new Promise<void>(resolve=>ctx.modal('将内容设为仅本机','<p>保留本机记录，撤回已经同步的发布；之后复制相同内容也不会自动共享。其他设备保存的备份不受影响。</p>',async()=>{await api.syncLocal(id,true);resolve();},'设为仅本机')));}
 return {render,update:async()=>{await update();await clips();}};
}
