import type {Detail} from '../shared/types';
import type {AIProfileView,AIKind,TextAction,TextScript,TextApply} from '../shared/text-tools';
import {aiEndpoint} from '../shared/text-tools';
const api=window.clipper;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const message=(e:unknown)=>String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');
const uid=()=>crypto.randomUUID();
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;active():boolean;select(id:string):Promise<void>;navigate(page:string,query?:string):void}
export function textToolsUI(ctx:Context){
 let renderToken=0,externalBusy=false;
 const close=()=>{const d=q<HTMLDialogElement>('dialog');if(d.open)d.close();};
 const listen=(id:string,fn:()=>unknown)=>q(id)?.addEventListener('click',()=>{Promise.resolve().then(fn).catch(ctx.toast);});
 function modal(title:string,body:string,save:()=>Promise<void>,label?:string){close();ctx.modal(title,body,save,label);}
 function processingLayout(){
  const dialog=q<HTMLDialogElement>('dialog');dialog.classList.add('text-processing');
  dialog.addEventListener('close',()=>dialog.classList.remove('text-processing'),{once:true});
  const input=q('tool-input').closest('label')!,output=q('tool-output').closest('label')!,panes=document.createElement('div');panes.className='tool-text-panes';input.before(panes);panes.append(input,output);
  const language=q('run-ai-language')?.closest('label');if(language){dialog.querySelector('.tool-field-grid')!.append(language);dialog.querySelector('.tool-field-grid')!.classList.add('tool-three-fields');}
 }
 async function render(){
  const token=++renderToken;const [ai,scripts,integration]=await Promise.all([api.aiState(),api.scripts(),api.integrations()]);if(token!==renderToken||!ctx.active())return;
  q('content').innerHTML=`<section class="tools-page"><div class="page-heading"><div><h1>文本工具</h1><p>连接模型，或用脚本处理文字</p></div><span class="version">v0.4.0</span></div><div class="tools-scroll"><div class="tools-section-heading"><h2>AI 服务</h2><button id="new-ai-profile" class="primary">添加服务</button></div><p class="field-help">从文字记录打开翻译、总结或改写，预览后再发送。密钥由 Windows 加密保存，不包含在历史备份中。</p><div class="tool-cards">${ai.profiles.length?ai.profiles.map(p=>`<article class="tool-card"><div class="tool-card-copy"><strong>${esc(p.name)} ${p.id===ai.defaultId?'<span class="tag">默认</span>':''}</strong><p>${esc(p.model||'尚未选择模型')}</p><small>${esc(p.baseUrl)}</small></div><div class="tool-card-actions"><button data-ai-models="${p.id}">模型列表</button><button data-ai-edit="${p.id}">编辑</button>${p.id!==ai.defaultId?`<button data-ai-default="${p.id}">设为默认</button>`:''}<button data-ai-remove="${p.id}" class="quiet">删除</button></div></article>`).join(''):'<div class="tools-empty">尚未添加服务。可连接 Ollama、LM Studio 或兼容聊天接口的在线服务。</div>'}</div><div class="tools-section-heading"><h2>文本脚本</h2><div><button id="import-scripts">导入</button><button id="export-scripts">导出</button><button id="new-script">新建脚本</button></div></div><p class="field-help">JavaScript 只接收本次选中文字并返回文字，无法访问文件、网络或系统剪贴板。运行前可查看代码和权限。</p><div class="tool-cards">${scripts.map(s=>`<article class="tool-card"><div class="tool-card-copy"><strong>${esc(s.name)}</strong><p>${esc(s.description||'文字转换脚本')}</p><small>仅选中文字 · ${(s.timeoutMs/1000).toFixed(1)} 秒上限</small></div><div class="tool-card-actions"><button data-script-edit="${s.id}">编辑</button><button data-script-remove="${s.id}" class="quiet">删除</button></div></article>`).join('')}</div><div class="tools-section-heading"><h2>外部链接</h2><button id="toggle-integration">${integration.registered?'停用 URL 入口':'启用 URL 入口'}</button></div><p class="field-help">允许其他应用通过 clipper-win:// 打开或搜索 Clipper。外部请求新增或复制文字时，始终先在应用内确认。当前：${integration.registered?'已注册':'未注册'}。</p><div class="url-examples"><code>clipper-win://open</code><code>clipper-win://search?q=关键词</code><code>clipper-win://add?text=待保存文字</code><code>clipper-win://copy?text=待复制文字</code></div></div></section>`;
  listen('new-ai-profile',()=>editProfile());listen('new-script',()=>editScript());listen('toggle-integration',async()=>{await api.registerIntegration(!integration.registered);await render();ctx.toast(integration.registered?'URL 入口已停用':'URL 入口已启用');});
  for(const mode of ['import','export'] as const)listen(mode+'-scripts',async()=>{const result=await api.scriptBackup(mode);if(result)ctx.toast(result);await render();});
  for(const p of ai.profiles){document.querySelector<HTMLElement>(`[data-ai-edit="${p.id}"]`)!.onclick=()=>editProfile(p);document.querySelector<HTMLElement>(`[data-ai-models="${p.id}"]`)!.onclick=()=>void modelList(p).catch(ctx.toast);const def=document.querySelector<HTMLElement>(`[data-ai-default="${p.id}"]`);if(def)def.onclick=()=>void api.defaultAIProfile(p.id).then(render).catch(ctx.toast);document.querySelector<HTMLElement>(`[data-ai-remove="${p.id}"]`)!.onclick=()=>modal('删除 AI 服务？',`<p>删除 ${esc(p.name)} 的配置与已保存密钥。</p>`,async()=>{await api.removeAIProfile(p.id);await render();},'删除');}
  for(const s of scripts){document.querySelector<HTMLElement>(`[data-script-edit="${s.id}"]`)!.onclick=()=>editScript(s);document.querySelector<HTMLElement>(`[data-script-remove="${s.id}"]`)!.onclick=()=>modal('删除文本脚本？',`<p>${esc(s.name)} 将被删除，历史内容保留。</p>`,async()=>{await api.removeScript(s.id);await render();},'删除');}
 }
 function editProfile(p?:AIProfileView){
  modal(p?'编辑 AI 服务':'添加 AI 服务',`<label class="field">服务名称<input id="ai-name" maxlength="60" value="${esc(p?.name||'Ollama')}" required></label><label class="field">接口类型<select id="ai-kind">${[['ollama','Ollama（本机）'],['lmstudio','LM Studio（本机）'],['openai','在线 / OpenAI 兼容接口']].map(([key,label])=>`<option value="${key}" ${p?.kind===key?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">服务基础地址<input id="ai-base" value="${esc(p?.baseUrl||'http://127.0.0.1:11434')}" placeholder="https://服务地址/v1" required></label><p class="field-help">Ollama 填根地址；兼容接口通常以 /v1 结尾。远程服务须使用 HTTPS。</p><label class="field">模型名称<input id="ai-model" maxlength="200" value="${esc(p?.model)}" placeholder="保存后可从模型列表选择"></label><label class="field">API 密钥<input id="ai-key" type="password" autocomplete="new-password" maxlength="8192" placeholder="${p?.hasKey?'已保存，留空保留':'本地服务无认证时可留空'}"></label>${p?.hasKey?'<label class="tool-check"><input id="ai-clear-key" type="checkbox">清除已保存密钥</label>':''}<div class="tool-field-grid"><label class="field">输出 token 上限<input id="ai-max" type="number" min="64" max="16384" value="${p?.maxTokens??2048}"></label><label class="field">等待时间（秒）<input id="ai-timeout" type="number" min="5" max="300" value="${p?.timeoutSeconds??90}"></label><label class="field">温度（可留空）<input id="ai-temperature" type="number" min="0" max="2" step="0.1" value="${p?.temperature??''}" placeholder="使用模型默认值"></label><label class="field">兼容接口输出参数<select id="ai-token-field"><option value="max_tokens">max_tokens</option><option value="max_completion_tokens" ${p?.tokenField==='max_completion_tokens'?'selected':''}>max_completion_tokens</option></select></label></div><p class="field-help">部分模型不接受温度参数，可留空。模型运行地点、内容保留及费用由所连接服务决定。</p>`,async()=>{const key=q<HTMLInputElement>('ai-key').value;await api.aiProfile({id:p?.id,name:q<HTMLInputElement>('ai-name').value,kind:q<HTMLSelectElement>('ai-kind').value as AIKind,baseUrl:q<HTMLInputElement>('ai-base').value,model:q<HTMLInputElement>('ai-model').value,apiKey:key||undefined,clearKey:q<HTMLInputElement>('ai-clear-key')?.checked||false,maxTokens:Number(q<HTMLInputElement>('ai-max').value),timeoutSeconds:Number(q<HTMLInputElement>('ai-timeout').value),temperature:q<HTMLInputElement>('ai-temperature').value===''?null:Number(q<HTMLInputElement>('ai-temperature').value),tokenField:q<HTMLSelectElement>('ai-token-field').value as 'max_tokens'|'max_completion_tokens'});q<HTMLInputElement>('ai-key').value='';await render();ctx.toast('服务已保存');});
  const keyInput=q<HTMLInputElement>('ai-key');q<HTMLDialogElement>('dialog').addEventListener('close',()=>{keyInput.value='';},{once:true});
  q<HTMLSelectElement>('ai-kind').onchange=()=>{const kind=q<HTMLSelectElement>('ai-kind').value;q<HTMLInputElement>('ai-name').value=kind==='ollama'?'Ollama':kind==='lmstudio'?'LM Studio':'在线服务';q<HTMLInputElement>('ai-base').value=kind==='ollama'?'http://127.0.0.1:11434':kind==='lmstudio'?'http://127.0.0.1:1234/v1':'';};
 }
 async function modelList(p:AIProfileView){const request=uid();modal('选择模型',`<p class="field-help">查询 ${esc(p.baseUrl)} 的模型列表，不发送剪贴板内容。</p><p id="models-progress">正在查询…</p><label class="field">模型<select id="models-select" disabled></select></label>`,async()=>{const model=q<HTMLSelectElement>('models-select').value;if(!model)throw new Error('请先选择模型');const current=(await api.aiState()).profiles.find(s=>s.id===p.id);if(!current)throw new Error('服务已不存在');await api.aiProfile({...current,model});await render();},'使用模型');const select=q<HTMLSelectElement>('models-select'),progress=q('models-progress');q<HTMLDialogElement>('dialog').addEventListener('close',()=>void api.aiCancel(request),{once:true});try{const models=await api.aiModels(p.id,request);if(!select.isConnected)return;select.innerHTML=models.map(m=>`<option ${m===p.model?'selected':''}>${esc(m)}</option>`).join('');select.disabled=!models.length;progress.textContent=models.length?`找到 ${models.length} 个模型`:'服务未返回模型，请先在模型服务中安装或加载模型';}catch(e){if(progress.isConnected)progress.textContent=message(e);}}
 function editScript(s?:TextScript){modal(s?'编辑文本脚本':'新建文本脚本',`<label class="field">名称<input id="script-name" maxlength="60" required value="${esc(s?.name)}"></label><label class="field">说明<input id="script-description" maxlength="240" value="${esc(s?.description)}"></label><label class="field">JavaScript 函数体<textarea id="script-code" class="code-input" rows="10" spellcheck="false" required>${esc(s?.code||'return input.trim();')}</textarea></label><p class="field-help">参数 input 是本次文字；使用 return 返回字符串。可使用标准 JavaScript，无法调用文件、网络、Node 或 Electron。异步任务不受支持。</p><label class="field">运行时限（毫秒）<input id="script-timeout" type="number" min="100" max="5000" value="${s?.timeoutMs||1500}"></label><label class="tool-check"><input id="script-permission" type="checkbox" required ${s?'checked':''}>权限：仅读取本次选中文字并返回处理结果</label>`,async()=>{if(!q<HTMLInputElement>('script-permission').checked)throw new Error('请确认脚本权限');await api.saveScript({id:s?.id,name:q<HTMLInputElement>('script-name').value,description:q<HTMLInputElement>('script-description').value,code:q<HTMLTextAreaElement>('script-code').value,timeoutMs:Number(q<HTMLInputElement>('script-timeout').value),permission:'selected-text'});await render();ctx.toast('脚本已保存');});}
 function resultButtons(output:HTMLTextAreaElement,source:TextApply['source'],target?:Detail){
  processingLayout();
  const dialog=q<HTMLDialogElement>('dialog'),save=dialog.querySelector<HTMLButtonElement>('[type=submit]')!;save.disabled=true;
  const footer=dialog.querySelector('.modal-footer')!;const buttons=document.createElement('div');buttons.className='result-actions';buttons.innerHTML=`<button id="result-copy" type="button" disabled>复制结果</button>${target?'<button id="result-replace" type="button" disabled>替换原记录</button>':''}`;footer.prepend(buttons);
  const enable=(running=false)=>{const disabled=running||!output.value.trim();save.disabled=disabled;q<HTMLButtonElement>('result-copy').disabled=disabled;if(target)q<HTMLButtonElement>('result-replace').disabled=disabled;};output.oninput=()=>enable();
  listen('result-copy',async()=>{await api.applyText({mode:'copy',text:output.value,source});ctx.toast('结果已复制');});
  if(target)listen('result-replace',async()=>{const id=await api.applyText({mode:'replace',text:output.value,source,clipId:target.id,expectedHash:target.hash});close();if(id)await ctx.select(id);ctx.toast('已替换为纯文本');});return enable;
 }
 async function ai(target:Detail|string,action:TextAction='translate'){
  const state=await api.aiState();if(!state.profiles.length){modal('先添加 AI 服务','<p>可连接本机 Ollama、LM Studio，或填写在线服务地址和模型。</p>',async()=>{ctx.navigate('tools');},'打开文本工具');return;}
  const original=typeof target==='string'?undefined:target,input=typeof target==='string'?target:target.payload.text||'';let profile=state.profiles.find(p=>p.id===state.defaultId)||state.profiles[0],activeRequest='';
  modal('AI 文本处理',`<div class="tool-field-grid"><label class="field">服务<select id="run-ai-profile">${state.profiles.map(p=>`<option value="${p.id}" ${p.id===profile.id?'selected':''}>${esc(p.name)} · ${esc(p.model||'未选择模型')}</option>`).join('')}</select></label><label class="field">操作<select id="run-ai-action">${[['translate','翻译'],['summarize','总结'],['rewrite','改写'],['custom','自定义指令']].map(([id,label])=>`<option value="${id}" ${action===id?'selected':''}>${label}</option>`).join('')}</select></label></div><label class="field">目标语言<input id="run-ai-language" value="简体中文" maxlength="60"></label><label class="field" id="instruction-field" ${action==='custom'?'':'hidden'}>处理指令<textarea id="run-ai-instruction" rows="3" maxlength="4000" placeholder="描述如何处理这段文字"></textarea></label><label class="field">发送的文字<textarea id="tool-input" rows="6">${esc(input)}</textarea></label><div class="send-destination"><span id="ai-destination"></span><small id="ai-cost"></small></div><label class="tool-check" id="send-consent-row"><input id="send-consent" type="checkbox">我确认将上方文字发送到此服务，并了解可能产生费用</label><div class="tool-run-bar"><button id="run-tool" type="button">开始处理</button><button id="cancel-tool" type="button" hidden>取消请求</button><span id="tool-progress"></span></div><label class="field">处理结果<textarea id="tool-output" rows="7" placeholder="结果可修改，然后复制、另存或替换"></textarea></label>${original?'<p class="field-help">替换会将原记录转为纯文本；另存结果会保留原记录。</p>':''}`,async()=>{const id=await api.applyText({mode:'save',text:q<HTMLTextAreaElement>('tool-output').value,source:'AI 处理'});if(id)await ctx.select(id);ctx.toast('结果已另存');},'另存结果');
  const inputNode=q<HTMLTextAreaElement>('tool-input'),output=q<HTMLTextAreaElement>('tool-output'),run=q<HTMLButtonElement>('run-tool'),cancel=q('cancel-tool'),progress=q('tool-progress'),consent=q<HTMLInputElement>('send-consent'),profileNode=q<HTMLSelectElement>('run-ai-profile'),actionNode=q<HTMLSelectElement>('run-ai-action'),languageNode=q<HTMLInputElement>('run-ai-language'),instructionNode=q<HTMLTextAreaElement>('run-ai-instruction');const enable=resultButtons(output,'AI 处理',original);
  const update=()=>{profile=state.profiles.find(p=>p.id===profileNode.value)!;q('ai-destination').textContent='接收地址：'+aiEndpoint(profile);q('ai-cost').textContent=`模型：${profile.model||'未选择'} · 输出上限 ${profile.maxTokens} tokens · 最多等待 ${profile.timeoutSeconds} 秒。费用与内容处理规则由该服务决定。`;const needsConsent=profile.kind==='openai'||!profile.local;q('send-consent-row').hidden=!needsConsent;run.disabled=!!activeRequest||!profile.model||(needsConsent&&!consent.checked);q('instruction-field').hidden=actionNode.value!=='custom';};
  const reset=()=>{output.value='';progress.textContent='';enable();consent.checked=false;update();};profileNode.onchange=reset;actionNode.onchange=reset;languageNode.oninput=reset;instructionNode.oninput=reset;inputNode.oninput=reset;consent.onchange=update;update();
  q<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(activeRequest)void api.aiCancel(activeRequest);},{once:true});cancel.onclick=()=>{if(activeRequest)void api.aiCancel(activeRequest);};
  run.onclick=async()=>{if(activeRequest)return;const request=activeRequest=uid(),started=Date.now();run.disabled=true;cancel.hidden=false;output.value='';enable(true);for(const el of [inputNode,output,profileNode,actionNode,languageNode,instructionNode,consent])el.disabled=true;progress.textContent='正在等待服务…';const timer=setInterval(()=>{if(progress.isConnected)progress.textContent=`正在处理 · ${Math.floor((Date.now()-started)/1000)} 秒`;},1000);
   try{const result=await api.aiRun({requestId:request,profileId:profile.id,revision:profile.revision,input:inputNode.value,action:actionNode.value as TextAction,language:languageNode.value,instruction:instructionNode.value,approvedDestination:aiEndpoint(profile)});if(!output.isConnected)return;output.value=result.text;progress.textContent=result.truncated?'达到输出上限，结果可能不完整':`处理完成${result.outputTokens!==undefined?' · 输出 '+result.outputTokens+' tokens':''}`;}catch(e){if(progress.isConnected)progress.textContent=message(e);}finally{clearInterval(timer);activeRequest='';if(run.isConnected){cancel.hidden=true;for(const el of [inputNode,output,profileNode,actionNode,languageNode,instructionNode,consent])el.disabled=false;enable();update();}}
  };
 }
 async function script(target:Detail|string){const scripts=await api.scripts();if(!scripts.length){ctx.navigate('tools');ctx.toast('请先添加文本脚本');return;}let activeRequest='';modal('运行文本脚本',`<label class="field">脚本<select id="run-script-id">${scripts.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><details class="script-preview" open><summary>查看代码与权限</summary><pre id="run-script-code"></pre><p>权限：仅本次选中文字 · 无文件与网络接口 · 独立运行</p></details><label class="field">输入文字<textarea id="tool-input" rows="5">${esc(typeof target==='string'?target:target.payload.text||'')}</textarea></label><label class="tool-check"><input id="run-script-consent" type="checkbox">允许此脚本处理上方文字</label><div class="tool-run-bar"><button id="run-tool" type="button" disabled>运行脚本</button><button id="cancel-tool" type="button" hidden>取消运行</button><span id="tool-progress"></span></div><label class="field">结果<textarea id="tool-output" rows="6" placeholder="运行后预览结果"></textarea></label>`,async()=>{const id=await api.applyText({mode:'save',text:q<HTMLTextAreaElement>('tool-output').value,source:'脚本处理'});if(id)await ctx.select(id);ctx.toast('结果已另存');},'另存结果');
  const selector=q<HTMLSelectElement>('run-script-id'),input=q<HTMLTextAreaElement>('tool-input'),output=q<HTMLTextAreaElement>('tool-output'),run=q<HTMLButtonElement>('run-tool'),cancel=q('cancel-tool'),consent=q<HTMLInputElement>('run-script-consent'),progress=q('tool-progress');const enable=resultButtons(output,'脚本处理',typeof target==='string'?undefined:target);
  const update=()=>{const selected=scripts.find(s=>s.id===selector.value)!;q('run-script-code').textContent=selected.code;run.disabled=!!activeRequest||!consent.checked;};selector.onchange=()=>{consent.checked=false;output.value='';enable();update();};consent.onchange=update;input.oninput=()=>{output.value='';enable();};update();cancel.onclick=()=>{if(activeRequest)void api.cancelScript(activeRequest);};q<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(activeRequest)void api.cancelScript(activeRequest);},{once:true});
  run.onclick=async()=>{const s=scripts.find(s=>s.id===selector.value)!;activeRequest=uid();run.disabled=true;cancel.hidden=false;selector.disabled=input.disabled=output.disabled=consent.disabled=true;progress.textContent='正在运行…';output.value='';enable(true);try{const result=await api.runScript({requestId:activeRequest,scriptId:s.id,input:input.value,permission:'selected-text',updatedAt:s.updatedAt});if(output.isConnected){output.value=result;progress.textContent='运行完成，原内容尚未改变';}}catch(e){if(progress.isConnected)progress.textContent=message(e);}finally{activeRequest='';if(run.isConnected){selector.disabled=input.disabled=output.disabled=consent.disabled=false;cancel.hidden=true;enable();update();}}};
 }
 async function external(){
  const dialog=q<HTMLDialogElement>('dialog');if(externalBusy||dialog.open)return;
  externalBusy=true;let awaitingDecision=false;
  try{
   const state=await api.integrations(),pending=state.pending;if(!pending||dialog.open)return;
   if(['open','search'].includes(pending.intent.action)){const result=await api.resolveExternal(pending.id,true);if(result)ctx.navigate('history',result.action==='search'?result.text:'');return;}
   let accepted=false;
   modal(pending.intent.action==='add'?'外部请求：新增记录':'外部请求：复制文字',`<p class="field-help">以下文字来自外部链接，确认后才会${pending.intent.action==='add'?'加入历史':'覆盖系统剪贴板'}。</p><pre class="external-preview">${esc(pending.intent.text)}</pre>`,async()=>{const result=await api.resolveExternal(pending.id,true);accepted=true;if(result?.clipId)await ctx.select(result.clipId);ctx.toast(pending.intent.action==='add'?'已添加记录':'文字已复制');},pending.intent.action==='add'?'添加记录':'复制文字');
   awaitingDecision=true;
   dialog.addEventListener('close',()=>{void(async()=>{if(!accepted)await api.resolveExternal(pending.id,false).catch(()=>{});externalBusy=false;await external();})().catch(ctx.toast);},{once:true});
  }finally{if(!awaitingDecision)externalBusy=false;}
 }

 return {render,ai,script,external};
}
