type TextTarget=Pick<Detail,'id'|'hash'> & Partial<Pick<Detail,'title'|'source'>> & {payload:{text?:string;png?:boolean|string};imageURL?:string};
import {utilityLayout} from './layout-029';
import {copyTextValue} from './copy-text';
import {ActionScope,actionFeedback} from './actions';
import {createElement,ArrowUpRight,Search,Plus,Copy,Bot,Code2,GripVertical,type IconNode} from 'lucide';
import {t as tr,formatNumber} from '../shared/i18n';
import type {Detail} from '../shared/types';
import type {AIProfileView,AIKind,TextAction,TextScript,TextApply} from '../shared/text-tools';
import {aiEndpoint,aiModelsFor} from '../shared/text-tools';
import {modelEditor} from './model-editor';
import {builtinCommands,commandVariables,promptVariables,renderCommandPrompt,type TextCommand} from '../shared/commands';
import {commandCards,bindCommandCards,editCommand} from './command-ui';
import {codexAccountMarkup,bindCodexAccount} from './codex-ui';
import {animateSort,bindSortable} from './sortable';
const api=window.clip;
// Request values and URL examples remain stable across interface languages.
const defaultTargetLanguage='简体中文';
const urlExamples=['clip-win://open','clip-win://search?q=关键词','clip-win://add?text=待保存文字','clip-win://copy?text=待复制文字'];
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const message=(e:unknown)=>String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');
const uid=()=>crypto.randomUUID();
const emptyState=(glyph:IconNode,title:string,description:string)=>`<div class="utility-empty tool-empty-state">${createElement(glyph,{class:'icon','aria-hidden':'true','stroke-width':1.5}).outerHTML}<strong>${esc(title)}</strong><p>${esc(description)}</p></div>`;
const uriExamplesMarkup=()=>urlExamples.map((url,i)=>`<div class="url-example">${createElement([ArrowUpRight,Search,Plus,Copy][i],{class:'icon','aria-hidden':'true'}).outerHTML}<span>${[tr('打开'),tr('搜索'),tr('新增'),tr('复制')][i]}</span><code>${esc(url)}</code><button class="icon-button quiet" data-uri-copy="${i}" aria-label="${tr('复制')} URI" title="${tr('复制')} URI">${createElement(Copy,{class:'icon','aria-hidden':'true'}).outerHTML}</button></div>`).join('');
export type TextToolPage = 'text-tools' | 'commands' | 'ai' | 'scripts' | 'uri';
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;active(page:TextToolPage):boolean;select(id:string):Promise<void>;navigate(page:string,query?:string):void}
export function textToolsUI(ctx:Context){
 let renderToken=0,externalBusy=false,currentPage:TextToolPage='text-tools',currentTab:'commands'|'ai'|'scripts'='ai';
 const setTab=(tab:'commands'|'ai'|'scripts')=>{currentTab=tab;};
 const close=()=>{const d=q<HTMLDialogElement>('dialog');if(d.open)d.close();};
 const actions=new ActionScope(),listen=(id:string,fn:()=>unknown)=>actions.bind(q<HTMLButtonElement>(id),fn,ctx.toast);
 function modal(title:string,body:string,save:()=>Promise<void>,label?:string){close();ctx.modal(title,body,save,label);}
 function processingLayout(){
  const dialog=q<HTMLDialogElement>('dialog');dialog.classList.add('text-processing');
  dialog.addEventListener('close',()=>dialog.classList.remove('text-processing','ai-processing','script-processing'),{once:true});
  if(dialog.querySelector('.ai-configuration,.script-configuration')){
   dialog.classList.add(dialog.querySelector('.ai-configuration')?'ai-processing':'script-processing');
   dialog.querySelector('.modal-footer')!.prepend(dialog.querySelector('.tool-run-bar')!);
   return;
  }
  const input=q('tool-input').closest('label')!,output=q('tool-output').closest('label')!,panes=document.createElement('div');panes.className='tool-text-panes';input.before(panes);panes.append(input,output);
 }
 async function render(page:TextToolPage=currentPage){
  if(page==='ai'||page==='scripts'||page==='commands'){currentTab=page;page='text-tools';}
  currentPage=page;const token=++renderToken;
  // Keep the shared segmented control mounted so its indicator can slide between tabs.
  const syncTabs=()=>q('content').querySelectorAll<HTMLButtonElement>('[data-text-tab]').forEach(button=>{const active=button.dataset.textTab===currentTab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});
  if(page==='text-tools')syncTabs();
  const ai=page!=='uri'&&currentTab==='ai'?await api.aiState():undefined,scripts=page!=='uri'&&currentTab==='scripts'?await api.scripts():undefined,integration=page==='uri'?await api.integrations():undefined,commands=page!=='uri'&&currentTab==='commands'?(await api.commands()||builtinCommands()):undefined;
  if(token!==renderToken||!ctx.active(page))return;
  if(ai)ai.profiles=[...ai.profiles].sort((a,b)=>Number(b.id===ai.defaultId)-Number(a.id===ai.defaultId));
  const title=page==='uri'?'URI':tr('AI与脚本');
  const buttons=commands?`<button id="new-command" class="primary">${tr('新建指令')}</button>`:ai?tr('<button id="new-ai-profile" class="primary">添加服务</button>'):scripts?tr('<button id="import-scripts">导入</button><button id="export-scripts">导出</button><button id="new-script" class="primary">新建脚本</button>'):`<button id="toggle-integration">${integration!.registered?tr('停用 URL 入口'):tr('启用 URL 入口')}</button>`;
  const body=ai?tr`<div class="tool-cards">${ai.profiles.length?ai.profiles.map(p=>`<article class="tool-card" data-ai-id="${esc(p.id)}" ${p.id===ai.defaultId?'':'data-ai-sort'}>${p.id===ai.defaultId?'':`<button type="button" class="ai-sort-grip icon-button quiet" aria-label="${tr('拖拽排序')} · ${esc(p.name)}" title="${tr('拖拽排序')}">${createElement(GripVertical,{class:'icon','aria-hidden':'true'}).outerHTML}</button>`}<div class="tool-card-copy"><strong>${esc(p.name)} ${p.id===ai.defaultId?tr('<span class="tag">默认</span>'):''}</strong><p>${esc(aiModelsFor(p).find(model=>model.id===p.model)?.name||tr('尚未选择模型'))}</p><small>${esc(p.kind==='codex'?tr('Codex（本机）'):p.baseUrl)}</small></div><div class="tool-card-actions"><button data-ai-models="${p.id}">${tr('模型列表')}</button><button data-ai-edit="${p.id}">${tr('编辑')}</button>${p.id!==ai.defaultId?tr`<button data-ai-default="${p.id}">设为默认</button>`:''}<button data-ai-remove="${p.id}" class="quiet">${tr('删除')}</button></div></article>`).join(''):emptyState(Bot,tr('尚未添加服务'),tr('添加服务后，可在文字记录中使用翻译、总结和改写。'))}</div>`:scripts?tr`<div class="tool-cards">${scripts.length?scripts.map(s=>tr`<article class="tool-card"><div class="tool-card-copy"><strong>${esc(s.name)}</strong>${s.description?`<p>${esc(s.description)}</p>`:''}</div><div class="tool-card-actions"><button data-script-edit="${s.id}">编辑</button><button data-script-remove="${s.id}" class="quiet">删除</button></div></article>`).join(''):emptyState(Code2,tr('尚未添加文本脚本'),tr('新建或导入脚本后，可在文字记录中运行。'))}</div>`:tr`<p class="field-help">允许其他应用通过 clip-win:// 打开或搜索 Clip。外部请求新增或复制文字时，始终先在应用内确认。</p><div class="url-examples">${uriExamplesMarkup()}</div>`;
  const status=integration?`<span class="status-badge" data-enabled="${integration.registered}">${integration.registered?tr('已注册'):tr('未注册')}</span>`:'';
  const tabs=page==='uri'?'':`<div class="text-tools-toolbar"><div class="tabs" role="tablist" aria-label="${tr('AI与脚本')}">${([['ai',tr('AI 服务')],['commands',tr('指令')],['scripts',tr('文本脚本')]] as const).map(([tab,label])=>`<button type="button" role="tab" data-text-tab="${tab}" aria-selected="${currentTab===tab}" class="${currentTab===tab?'active':''}">${label}</button>`).join('')}</div><div class="heading-actions"><button id="open-ai-chat" class="quiet">${tr('AI 对话')}</button>${buttons}</div></div>`;
  const panelLabel=page==='uri'?'URI':currentTab==='commands'?tr('指令'):currentTab==='ai'?tr('AI 服务'):tr('文本脚本'),panel=`<section class="section-panel tool-workbench">${commands?commandCards(commands):body}</section>`,existing=q('content').querySelector<HTMLElement>('.text-tool-page .text-tools-toolbar');
  if(page==='text-tools'&&existing){
   existing.querySelector('.heading-actions')!.innerHTML=`<button id="open-ai-chat" class="quiet">${tr('AI 对话')}</button>`+buttons;const scroll=q('content').querySelector<HTMLElement>('.text-tool-page .tools-scroll')!;scroll.innerHTML=panel;scroll.setAttribute('aria-label',panelLabel);syncTabs();
  }else q('content').innerHTML=`<section class="tools-page text-tool-page"><div class="page-heading"><div><h1>${title}</h1>${status}</div>${page==='uri'?`<div class="heading-actions">${buttons}</div>`:''}</div>${tabs}<div class="tools-scroll" role="${page==='uri'?'region':'tabpanel'}" aria-label="${panelLabel}">${panel}</div></section>`;
  if(page==='text-tools')listen('open-ai-chat',()=>api.openChat());
  if(!commands)utilityLayout('tools');
  q('content').querySelectorAll<HTMLButtonElement>('[data-text-tab]').forEach(button=>button.onclick=()=>{currentTab=button.dataset.textTab as typeof currentTab;void render().catch(ctx.toast);});
  if(commands){const commandContext={modal,toast:ctx.toast,render:()=>render()};listen('new-command',()=>editCommand(commandContext));bindCommandCards(commands,commandContext,actions);}
  if(integration){listen('toggle-integration',async()=>{await api.registerIntegration(!integration.registered);await render();ctx.toast(integration.registered?tr('URL 入口已停用'):tr('URL 入口已启用'));});q('content').querySelectorAll<HTMLButtonElement>('[data-uri-copy]').forEach(button=>{const index=Number(button.dataset.uriCopy);actions.bind(button,async()=>{await copyTextValue(urlExamples[index]);ctx.toast(tr('已复制'));},ctx.toast,'uri-copy-'+index);});}
  if(scripts){listen('new-script',()=>editScript());for(const mode of ['import','export'] as const)listen(mode+'-scripts',async()=>{const result=await api.scriptBackup(mode);if(result)ctx.toast(result);await render();});
   for(const s of scripts){document.querySelector<HTMLElement>(`[data-script-edit="${s.id}"]`)!.onclick=()=>editScript(s);document.querySelector<HTMLElement>(`[data-script-remove="${s.id}"]`)!.onclick=()=>modal(tr('删除文本脚本？'),tr`<p>${esc(s.name)} 将被删除，历史内容保留。</p>`,async()=>{await api.removeScript(s.id);await render();},tr('删除'));}
  }
  if(ai){const cards=q('content').querySelector<HTMLElement>('.tool-cards')!;cards.classList.add('ai-service-cards');bindSortable(cards,{itemSelector:'.tool-card[data-ai-sort]',handleSelector:'.ai-sort-grip',id:item=>item.dataset.aiId!,commit:ids=>api.reorderAIProfiles([...(ai.defaultId?[ai.defaultId]:[]),...ids]).catch(async error=>{ctx.toast(error);await render();})});listen('new-ai-profile',()=>editProfile());for(const p of ai.profiles){document.querySelector<HTMLElement>(`[data-ai-edit="${p.id}"]`)!.onclick=()=>editProfile(p);actions.bind(document.querySelector<HTMLButtonElement>(`[data-ai-models="${p.id}"]`),()=>modelList(p),ctx.toast,'models:'+p.id);const def=document.querySelector<HTMLElement>(`[data-ai-default="${p.id}"]`);if(def)actions.bind(def as HTMLButtonElement,async()=>{const before=new Map(Array.from(cards.querySelectorAll<HTMLElement>('[data-ai-id]'),item=>[item.dataset.aiId!,item.getBoundingClientRect()]));await api.defaultAIProfile(p.id);await render();const items=Array.from(q('content').querySelectorAll<HTMLElement>('.ai-service-cards>[data-ai-id]'));animateSort(items,new Map(items.flatMap(item=>{const rect=before.get(item.dataset.aiId!);return rect?[[item,rect] as const]:[];})));},ctx.toast,'default-profile');document.querySelector<HTMLElement>(`[data-ai-remove="${p.id}"]`)!.onclick=()=>modal(tr('删除 AI 服务？'),tr`<p>删除 ${esc(p.name)} 的配置与已保存密钥。</p>`,async()=>{await api.removeAIProfile(p.id);await render();},tr('删除'));}}
 }
 function editProfile(p?:AIProfileView){
  let editor:ReturnType<typeof modelEditor>;
  modal(p?tr('编辑 AI 服务'):tr('添加 AI 服务'),tr`<label class="field">服务名称<input id="ai-name" maxlength="60" value="${esc(p?.name||'Ollama')}" required></label><label class="field">接口类型<select id="ai-kind">${[['codex',tr('Codex（本机）')],['ollama',tr('Ollama（本机）')],['lmstudio',tr('LM Studio（本机）')],['openai',tr('在线 / OpenAI 兼容接口')]].map(([key,label])=>`<option value="${key}" ${(p?.kind||'ollama')===key?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">服务基础地址<input id="ai-base" value="${esc(p?.baseUrl||'http://127.0.0.1:11434')}" placeholder="https://服务地址/v1" required></label><p class="field-help">Ollama 填根地址；兼容接口通常以 /v1 结尾。远程服务须使用 HTTPS。</p><label class="field">默认模型<select id="ai-model"><option value="">${tr('尚未添加模型')}</option></select></label><label class="field">默认推理强度<select id="ai-effort"><option value="">${tr('默认推理')}</option></select></label><label class="field">API 密钥<input id="ai-key" type="password" autocomplete="new-password" maxlength="8192" placeholder="${p?.hasKey?tr('已保存，留空保留'):tr('本地服务无认证时可留空')}"></label><div class="tool-field-grid"><label class="field">输出 token 上限<input id="ai-max" type="number" min="64" max="16384" value="${p?.maxTokens??2048}"></label><label class="field">等待时间（秒）<input id="ai-timeout" type="number" min="5" max="300" value="${p?.timeoutSeconds??90}"></label><label class="field">温度（可留空）<input id="ai-temperature" type="number" min="0" max="2" step="0.1" value="${p?.temperature??''}" placeholder="使用模型默认值"></label><label class="field">兼容接口输出参数<select id="ai-token-field"><option value="max_tokens">max_tokens</option><option value="max_completion_tokens" ${p?.tokenField==='max_completion_tokens'?'selected':''}>max_completion_tokens</option></select></label></div><p class="field-help">部分模型不接受温度参数，可留空。模型运行地点、内容保留及费用由所连接服务决定。</p>`,async()=>{const input=q<HTMLInputElement>('ai-key'),key=input.value;await api.aiProfile({id:p?.id,name:q<HTMLInputElement>('ai-name').value,kind:q<HTMLSelectElement>('ai-kind').value as AIKind,baseUrl:q<HTMLSelectElement>('ai-kind').value==='codex'?'codex://local':q<HTMLInputElement>('ai-base').value,model:q<HTMLSelectElement>('ai-model').value,models:editor.read(),reasoningEffort:q<HTMLSelectElement>('ai-kind').value==='codex'?q<HTMLSelectElement>('ai-effort').value:'',apiKey:q<HTMLSelectElement>('ai-kind').value==='codex'?undefined:key||undefined,maxTokens:Number(q<HTMLInputElement>('ai-max').value),timeoutSeconds:Number(q<HTMLInputElement>('ai-timeout').value),temperature:q<HTMLInputElement>('ai-temperature').value===''?null:Number(q<HTMLInputElement>('ai-temperature').value),tokenField:q<HTMLSelectElement>('ai-token-field').value as 'max_tokens'|'max_completion_tokens'});input.value='';await render();ctx.toast(tr('服务已保存'));});
  const keyInput=q<HTMLInputElement>('ai-key'),dialog=q<HTMLDialogElement>('dialog'),body=dialog.querySelector('.modal-body')!,account=document.createElement('div');account.innerHTML=codexAccountMarkup();const accountRoot=account.firstElementChild as HTMLElement;
  const field=(id:string)=>q(id)?.closest('label'),help=Array.from(body.querySelectorAll<HTMLElement>(':scope>.field-help')),section=(className:string,ids:string[])=>{const section=document.createElement('section');section.className=className;for(const id of ids){const label=field(id);if(label)section.append(label);}return section;};
  const identity=section('ai-profile-fields',['ai-name','ai-kind']),connection=section('ai-profile-fields ai-profile-connection',['ai-base','ai-key']),model=section('ai-profile-model',['ai-model','ai-timeout','ai-effort']),tuning=section('ai-profile-tuning',['ai-max','ai-temperature','ai-token-field']);if(help[0])connection.append(help[0]);if(help[1])tuning.append(help[1]);const modelRoot=document.createElement('section');modelRoot.className='ai-profile-models';body.replaceChildren(identity,accountRoot,connection,modelRoot,model,tuning);dialog.classList.add('ai-profile-editor');
  editor=modelEditor(modelRoot,p,()=>q<HTMLSelectElement>('ai-kind').value as AIKind,()=>q<HTMLSelectElement>('ai-kind').value==='codex'?api.codexModels(uid()):api.aiModelCatalog(p!.id,uid()));
  const accountUI=bindCodexAccount(accountRoot,ctx.toast,state=>editor.setCodexAvailable(state.available&&state.loggedIn&&!state.error)),httpFields=['ai-base','ai-key','ai-max','ai-temperature','ai-token-field'].map(id=>q<HTMLInputElement>(id)).filter(Boolean);
  const toggleCodex=()=>{const codex=q<HTMLSelectElement>('ai-kind').value==='codex';accountRoot.hidden=!codex;connection.hidden=tuning.hidden=codex;for(const field of httpFields)field.disabled=codex;editor.update();if(codex)void accountUI.refresh().catch(ctx.toast);};toggleCodex();
  dialog.addEventListener('close',()=>{keyInput.value='';accountUI.dispose();dialog.classList.remove('ai-profile-editor');},{once:true});
  q<HTMLSelectElement>('ai-kind').onchange=()=>{const kind=q<HTMLSelectElement>('ai-kind').value;q<HTMLInputElement>('ai-name').value=kind==='ollama'?'Ollama':kind==='lmstudio'?'LM Studio':kind==='codex'?'Codex':tr('在线服务');q<HTMLInputElement>('ai-base').value=kind==='ollama'?'http://127.0.0.1:11434':kind==='lmstudio'?'http://127.0.0.1:1234/v1':'';toggleCodex();};
 }
 async function modelList(p:AIProfileView){const request=uid();modal(tr('选择模型'),tr`<p class="field-help">查询 ${esc(p.kind==='codex'?'Codex':p.baseUrl)} 的模型列表，不发送剪贴板内容。</p><p id="models-progress">正在查询…</p><label class="field">模型<select id="models-select" disabled></select></label>`,async()=>{const model=q<HTMLSelectElement>('models-select').value;if(!model)throw new Error(tr('请先选择模型'));const current=(await api.aiState()).profiles.find(s=>s.id===p.id);if(!current)throw new Error(tr('服务已不存在'));await api.aiProfile({...current,model,reasoningEffort:''});await render();},tr('使用模型'));const select=q<HTMLSelectElement>('models-select'),progress=q('models-progress');q<HTMLDialogElement>('dialog').addEventListener('close',()=>void api.aiCancel(request),{once:true});try{const catalog=await api.aiModelCatalog(p.id,request),models=catalog.map(model=>model.id);if(!select.isConnected)return;select.innerHTML=models.map(m=>`<option value="${esc(m)}" ${m===p.model?'selected':''}>${esc(catalog.find(model=>model.id===m)?.name||m)}</option>`).join('');select.disabled=!models.length;progress.textContent=models.length?tr`找到 ${formatNumber(models.length)} 个模型`:tr('服务未返回模型，请先在模型服务中安装或加载模型');}catch(e){if(progress.isConnected)progress.textContent=message(e);}}
 function editScript(s?:TextScript){modal(s?tr('编辑文本脚本'):tr('新建文本脚本'),tr`<label class="field">名称<input id="script-name" maxlength="60" required value="${esc(s?.name)}"></label><label class="field">说明<input id="script-description" maxlength="240" value="${esc(s?.description)}"></label><label class="field">JavaScript 函数体<textarea id="script-code" class="code-input" rows="10" spellcheck="false" required>${esc(s?.code||'return input.trim();')}</textarea></label><p class="field-help">参数 input 是本次文字；使用 return 返回字符串。可使用标准 JavaScript，无法调用文件、网络、Node 或 Electron。异步任务不受支持。</p><label class="field">运行时限（毫秒）<input id="script-timeout" type="number" min="100" max="5000" value="${s?.timeoutMs||1500}"></label><label class="tool-check"><input id="script-permission" type="checkbox" required ${s?'checked':''}>权限：仅读取本次选中文字并返回处理结果</label>`,async()=>{if(!q<HTMLInputElement>('script-permission').checked)throw new Error(tr('请确认脚本权限'));await api.saveScript({id:s?.id,name:q<HTMLInputElement>('script-name').value,description:q<HTMLInputElement>('script-description').value,code:q<HTMLTextAreaElement>('script-code').value,timeoutMs:Number(q<HTMLInputElement>('script-timeout').value),permission:'selected-text'});await render();ctx.toast(tr('脚本已保存'));});}
 function resultButtons(output:HTMLTextAreaElement,source:TextApply['source'],target?:TextTarget){
  processingLayout();
  const dialog=q<HTMLDialogElement>('dialog'),save=dialog.querySelector<HTMLButtonElement>('[type=submit]')!;save.disabled=true;
  const footer=dialog.querySelector('.modal-footer')!,toolbar=dialog.querySelector('.ai-result-actions');const buttons=document.createElement('div');buttons.className='result-actions';buttons.innerHTML=tr`<button id="result-copy" type="button" disabled>复制结果</button>${target?tr('<button id="result-replace" type="button" disabled>替换原记录</button>'):''}`;if(toolbar){buttons.querySelectorAll('button').forEach(button=>button.classList.add('quiet'));toolbar.append(buttons);}else footer.prepend(buttons);
  const enable=(running=false)=>{const disabled=running||!output.value.trim();save.disabled=disabled;if(toolbar)q('run-tool').classList.toggle('primary',!output.value.trim());q<HTMLButtonElement>('result-copy').disabled=disabled;if(target)q<HTMLButtonElement>('result-replace').disabled=disabled;};output.oninput=()=>enable();
  listen('result-copy',async()=>{await api.applyText({mode:'copy',text:output.value,source});ctx.toast(tr('结果已复制'));});
  if(target)listen('result-replace',async()=>{const form=dialog.querySelector('form'),id=await api.applyText({mode:'replace',text:output.value,source,clipId:target.id,expectedHash:target.hash});if(!dialog.open||dialog.querySelector('form')!==form)return;close();if(id)await ctx.select(id);ctx.toast(tr('已替换为纯文本'));});return enable;
 }
 async function ai(target:TextTarget|string,action:string='translate'){
  const [state,loadedCommands]=await Promise.all([api.aiState(),api.commands()]);const commands=loadedCommands||builtinCommands();
  if(!state.profiles.length){modal(tr('先添加 AI 服务'),tr('<p>可连接本机 Ollama、LM Studio，或填写在线服务地址和模型。</p>'),async()=>{ctx.navigate('ai');},tr('AI 服务'));return;}
  if(action!=='custom'&&!commands.some(command=>command.id===action))throw new Error(tr('指令已不存在，请重新选择'));
  const original=typeof target==='string'?undefined:target,image=!!original?.payload.png,input=typeof target==='string'?target:target.payload.text||(image?tr('描述这张图片的主要内容。'):'');let profile=state.profiles.find(p=>p.id===state.defaultId)||state.profiles[0],activeRequest='';
  modal(image?tr('AI 图片处理'):tr('AI 文本处理'),`<section class="ai-configuration"><div class="tool-field-grid tool-three-fields"><label class="field">${tr('服务')}<select id="run-ai-profile">${state.profiles.map(p=>`<option value="${p.id}" ${p.id===profile.id?'selected':''}>${esc(p.name)} · ${esc(p.model||tr(p.kind==='codex'?'Codex 默认模型':'未选择模型'))}</option>`).join('')}</select></label><label class="field">${tr('指令')}<select id="run-ai-action">${commands.map(command=>`<option value="${esc(command.id)}" data-icon="lucide:command-${esc(command.icon)}" ${action===command.id?'selected':''}>${esc(command.title)}</option>`).join('')}<option value="custom" data-icon="lucide:command-sparkles" ${action==='custom'?'selected':''}>${tr('临时指令')}</option></select></label><label class="field">${tr('目标语言')}<input id="run-ai-language" value="${esc(defaultTargetLanguage)}" maxlength="60"></label></div><label class="field ai-instruction" id="instruction-field" ${action==='custom'?'':'hidden'}>${tr('处理指令')}<textarea id="run-ai-instruction" rows="2" maxlength="4000" placeholder="${tr('描述如何处理这段文字')}">${image?esc(tr('根据用户的要求分析图片，使用目标语言回答。')):''}</textarea></label>${image?`<p class="ai-vision-hint">${tr('请选择支持图片输入的模型。图片会和提示词一起发送。')}</p>`:''}<div id="ai-command-variables" class="ai-command-variables"></div><details class="ai-command-preview"><summary>${tr('提示词预览')}</summary><pre id="ai-command-preview"></pre></details><details class="ai-service-info"><summary><span id="ai-destination"></span><span class="ai-service-toggle">${tr('服务详情')}</span></summary><small id="ai-cost"></small></details><label class="tool-check" id="send-consent-row"><input id="send-consent" type="checkbox">${image?tr('我确认将本次图片和提示词发送到此服务，并了解可能产生费用'):tr('我确认将本次文字发送到此服务，并了解可能产生费用')}</label></section><div class="tool-text-panes ai-text-panes"><section class="ai-text-pane"><header class="ai-pane-heading"><label for="tool-input">${image?tr('图片与要求'):tr('发送的文字')}</label></header>${image?`<div class="ai-input-image"><img src="${esc(original?.imageURL||'')}" alt="${tr('待处理图片')}"></div>`:''}<textarea id="tool-input" rows="10" spellcheck="false">${esc(input)}</textarea></section><section class="ai-text-pane"><header class="ai-pane-heading"><label for="tool-output">${tr('处理结果')}</label><div class="ai-result-actions"></div></header><textarea id="tool-output" rows="10" spellcheck="false" placeholder="${tr('结果可修改，然后复制、另存或替换')}"></textarea></section></div>${original?`<p class="ai-result-note">${image?tr('另存结果会保留原图片。'):tr('替换会将原记录转为纯文本；另存结果会保留原记录。')}</p>`:''}<div class="tool-run-bar"><button id="run-tool" class="primary" type="button">${tr('开始处理')}</button><button id="cancel-tool" type="button" hidden>${tr('取消请求')}</button><span id="tool-progress" role="status" aria-live="polite"></span></div>`,async()=>{const id=await api.applyText({mode:'save',text:q<HTMLTextAreaElement>('tool-output').value,source:'AI 处理'});if(id)await ctx.select(id);ctx.toast(tr('结果已另存'));},tr('另存结果'));
  const inputNode=q<HTMLTextAreaElement>('tool-input'),output=q<HTMLTextAreaElement>('tool-output'),run=q<HTMLButtonElement>('run-tool'),cancel=q('cancel-tool'),progress=q('tool-progress'),consent=q<HTMLInputElement>('send-consent'),profileNode=q<HTMLSelectElement>('run-ai-profile'),actionNode=q<HTMLSelectElement>('run-ai-action'),languageNode=q<HTMLInputElement>('run-ai-language'),instructionNode=q<HTMLTextAreaElement>('run-ai-instruction');const enable=resultButtons(output,'AI 处理',image?undefined:original);if(image)q('dialog').classList.add('ai-vision-processing');q<HTMLDialogElement>('dialog').addEventListener('close',()=>q('dialog').classList.remove('ai-vision-processing'),{once:true});
  const now=new Date(),pad=(value:number)=>String(value).padStart(2,'0'),variables:Record<string,string>={title:original?.title?.slice(0,4000)||'',source:original?.source?.slice(0,4000)||'',date:`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`,time:`${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`};
  const command=()=>commands.find(item=>item.id===actionNode.value);
  const controls=()=>[inputNode,output,profileNode,actionNode,languageNode,instructionNode,consent,...q('ai-command-variables').querySelectorAll<HTMLInputElement>('input')];
  const update=()=>{
   profile=state.profiles.find(p=>p.id===profileNode.value)!;q('ai-destination').textContent=profile.kind==='codex'?tr('Codex（本机）'):tr('接收地址：')+aiEndpoint(profile);q('ai-cost').textContent=profile.kind==='codex'?tr`模型：${profile.model||tr('Codex 默认模型')} · 最多等待 ${formatNumber(profile.timeoutSeconds)} 秒。使用 Codex 账户的模型服务和额度。`:tr`模型：${profile.model||tr('未选择')} · 输出上限 ${formatNumber(profile.maxTokens)} tokens · 最多等待 ${formatNumber(profile.timeoutSeconds)} 秒。费用与内容处理规则由该服务决定。`;
   const needsConsent=profile.kind==='openai'||profile.kind==='codex'||!profile.local;q('send-consent-row').hidden=!needsConsent;q('instruction-field').hidden=actionNode.value!=='custom';const selected=command();
   let invalid=false;try{q('ai-command-preview').textContent=selected?renderCommandPrompt(selected.prompt,inputNode.value,languageNode.value,variables):instructionNode.value;if(!selected&&!instructionNode.value.trim())invalid=true;}catch(error){invalid=true;q('ai-command-preview').textContent=message(error);}
   run.disabled=!!activeRequest||(profile.kind!=='codex'&&!profile.model)||invalid||(needsConsent&&!consent.checked);
  };
  const reset=()=>{output.value='';progress.textContent='';enable();consent.checked=false;update();};
  const fields=()=>{const selected=command(),names=selected?promptVariables(selected.prompt).filter(name=>!commandVariables.includes(name as typeof commandVariables[number])):[];q('ai-command-variables').innerHTML=names.map(name=>`<label class="field">${esc(name)}<input data-command-value="${name}" value="${esc(variables[name]||'')}" maxlength="4000" placeholder="${tr('填写变量')}" required></label>`).join('');q('ai-command-variables').querySelectorAll<HTMLInputElement>('input').forEach(field=>field.oninput=()=>{variables[field.dataset.commandValue!]=field.value;reset();});};
  profileNode.onchange=reset;actionNode.onchange=()=>{fields();reset();};languageNode.oninput=reset;instructionNode.oninput=reset;inputNode.oninput=reset;consent.onchange=update;fields();update();
  q<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(activeRequest)void api.aiCancel(activeRequest);},{once:true});cancel.onclick=()=>{if(activeRequest)void api.aiCancel(activeRequest);};
  run.onclick=async()=>{if(activeRequest||run.disabled)return;const request=activeRequest=uid(),started=Date.now(),finish=actionFeedback(run);run.disabled=true;cancel.hidden=false;output.value='';enable(true);for(const el of controls())el.disabled=true;progress.textContent=tr('正在等待服务…');const timer=setInterval(()=>{if(progress.isConnected)progress.textContent=tr`正在处理 · ${formatNumber(Math.floor((Date.now()-started)/1000))} 秒`;},1000);
   try{const result=await api.aiRun({requestId:request,profileId:profile.id,revision:profile.revision,input:inputNode.value,action:commands.find(item=>item.id===actionNode.value)?.builtin?actionNode.value as TextAction:'custom',language:languageNode.value,instruction:instructionNode.value,approvedDestination:aiEndpoint(profile),image:image?{clipId:original!.id,hash:original!.hash}:undefined,command:command()?{id:command()!.id,revision:command()!.revision,values:{...variables}}:undefined});if(!output.isConnected)return;output.value=result.text;progress.textContent=result.truncated?tr('达到输出上限，结果可能不完整'):tr`处理完成${result.outputTokens!==undefined?tr(' · 输出 ')+formatNumber(result.outputTokens)+' tokens':''}`;}catch(e){if(progress.isConnected)progress.textContent=message(e);}finally{finish();clearInterval(timer);activeRequest='';if(run.isConnected){cancel.hidden=true;for(const el of controls())el.disabled=false;enable();update();}}
  };
 }
 async function script(target:TextTarget|string){const scripts=await api.scripts();if(!scripts.length){ctx.navigate('scripts');ctx.toast(tr('请先添加文本脚本'));return;}let activeRequest='';modal(tr('运行文本脚本'),`<section class="script-configuration"><div class="script-selection"><label class="field">${tr('脚本')}<select id="run-script-id">${scripts.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><p id="run-script-description"></p></div><details class="script-preview"><summary>${tr('查看代码与权限')}</summary><pre id="run-script-code"></pre><p>${tr('权限：仅本次选中文字 · 无文件与网络接口 · 独立运行')}</p></details><label class="tool-check"><input id="run-script-consent" type="checkbox">${tr('允许此脚本处理上方文字')}</label></section><div class="tool-text-panes ai-text-panes"><section class="ai-text-pane"><header class="ai-pane-heading"><label for="tool-input">${tr('输入文字')}</label></header><textarea id="tool-input" rows="8" spellcheck="false">${esc(typeof target==='string'?target:target.payload.text||'')}</textarea></section><section class="ai-text-pane"><header class="ai-pane-heading"><label for="tool-output">${tr('处理结果')}</label><div class="ai-result-actions"></div></header><textarea id="tool-output" rows="8" spellcheck="false" placeholder="${tr('运行后可修改、复制或另存结果')}"></textarea></section></div><p class="ai-result-note">${tr('原内容在处理后保持不变，替换或另存由你决定。')}</p><div class="tool-run-bar"><button id="run-tool" class="primary" type="button" disabled>${tr('运行脚本')}</button><button id="cancel-tool" type="button" hidden>${tr('取消运行')}</button><span id="tool-progress" role="status" aria-live="polite"></span></div>`,async()=>{const id=await api.applyText({mode:'save',text:q<HTMLTextAreaElement>('tool-output').value,source:'脚本处理'});if(id)await ctx.select(id);ctx.toast(tr('结果已另存'));},tr('另存结果'));
  const selector=q<HTMLSelectElement>('run-script-id'),input=q<HTMLTextAreaElement>('tool-input'),output=q<HTMLTextAreaElement>('tool-output'),run=q<HTMLButtonElement>('run-tool'),cancel=q('cancel-tool'),consent=q<HTMLInputElement>('run-script-consent'),progress=q('tool-progress');const enable=resultButtons(output,'脚本处理',typeof target==='string'?undefined:target);
  const update=()=>{const selected=scripts.find(s=>s.id===selector.value)!;q('run-script-code').textContent=selected.code;q('run-script-description').textContent=selected.description||tr('使用本地脚本处理本次文字');run.disabled=!!activeRequest||!consent.checked;};selector.onchange=()=>{consent.checked=false;output.value='';enable();update();};consent.onchange=update;input.oninput=()=>{output.value='';enable();};update();cancel.onclick=()=>{if(activeRequest)void api.cancelScript(activeRequest);};q<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(activeRequest)void api.cancelScript(activeRequest);},{once:true});
  run.onclick=async()=>{if(activeRequest||run.disabled)return;const s=scripts.find(s=>s.id===selector.value)!,finish=actionFeedback(run);activeRequest=uid();run.disabled=true;cancel.hidden=false;selector.disabled=input.disabled=output.disabled=consent.disabled=true;progress.textContent=tr('正在运行…');output.value='';enable(true);try{const result=await api.runScript({requestId:activeRequest,scriptId:s.id,input:input.value,permission:'selected-text',updatedAt:s.updatedAt});if(output.isConnected){output.value=result;progress.textContent=tr('运行完成，原内容尚未改变');}}catch(e){if(progress.isConnected)progress.textContent=message(e);}finally{finish();activeRequest='';if(run.isConnected){selector.disabled=input.disabled=output.disabled=consent.disabled=false;cancel.hidden=true;enable();update();}}};
 }
 async function external(){
  const dialog=q<HTMLDialogElement>('dialog');if(externalBusy||dialog.open)return;
  externalBusy=true;let awaitingDecision=false,handled=false;
  try{
   const state=await api.integrations(),pending=state.pending;if(!pending||dialog.open)return;
   if(['open','search'].includes(pending.intent.action)){const result=await api.resolveExternal(pending.id,true);handled=true;if(result)ctx.navigate('history',result.action==='search'?result.text:'');return;}
   let accepted=false;
   modal(pending.intent.action==='add'?tr('外部请求：新增记录'):tr('外部请求：复制文字'),tr`<p class="field-help">以下文字来自外部链接，确认后才会${pending.intent.action==='add'?tr('加入历史'):tr('覆盖系统剪贴板')}。</p><pre class="external-preview">${esc(pending.intent.text)}</pre>`,async()=>{const result=await api.resolveExternal(pending.id,true);accepted=true;if(result?.clipId)await ctx.select(result.clipId);ctx.toast(pending.intent.action==='add'?tr('已添加记录'):tr('文字已复制'));},pending.intent.action==='add'?tr('添加记录'):tr('复制文字'));
   awaitingDecision=true;
   dialog.addEventListener('close',()=>{void(async()=>{if(!accepted)await api.resolveExternal(pending.id,false).catch(()=>{});externalBusy=false;await external();})().catch(ctx.toast);},{once:true});
  }finally{if(!awaitingDecision){externalBusy=false;if(handled)queueMicrotask(()=>void external().catch(ctx.toast));}}
 }

 return {render,ai,script,external,setTab};
}
