import './tray.css';
import {createElement,ArrowUpRight,X,FileText,Image,Folder,Link,Code,Star,Pin,type IconNode} from 'lucide';
import {trayQuery,type TrayAPI,type TrayQuery,type TrayState,type TrayPreview} from '../shared/tray';
declare global{interface Window{clipperTray:TrayAPI}}
const api=window.clipperTray,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(node:IconNode)=>createElement(node,{'aria-hidden':'true','stroke-width':1.6}).outerHTML;
const symbols={text:FileText,image:Image,files:Folder,link:Link,code:Code},kinds=[['all','全部'],['text','文字'],['image','图片'],['files','文件'],['link','链接'],['code','代码']];
let query:TrayQuery={...trayQuery},state:TrayState|undefined,selected='',querySerial=0,previewSerial=0,busy=false,searching=true,dragUntil=0;
let hover:ReturnType<typeof setTimeout>|undefined,debounce:ReturnType<typeof setTimeout>|undefined,noticeTimer:ReturnType<typeof setTimeout>|undefined;
function notice(error:unknown){q('notice').textContent=String(error instanceof Error?error.message:error).replace(/^Error invoking remote method '[^']+': Error: /,'');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>q('notice').textContent='',7000);}
const run=(action:()=>Promise<unknown>)=>void action().catch(notice);
function buttons(){q<HTMLButtonElement>('copy-selected').disabled=!selected||busy||searching;q<HTMLButtonElement>('paste-selected').disabled=!selected||busy||searching||!state?.canPaste;}
function clearPreview(){previewSerial++;clearTimeout(hover);selected='';q('preview').innerHTML='<div class="empty">悬停或使用方向键预览</div>';buttons();}
function renderPreview(value:TrayPreview){q('preview').innerHTML=`<div class="preview-heading">${icon(symbols[value.kind])}<strong>${esc(value.title)}</strong></div><div class="preview-content">${value.image?`<img class="preview-image" src="${esc(value.image)}" alt="图片预览">`:''}${value.text?`<pre class="${value.kind==='code'?'code':''}">${esc(value.text)}</pre>`:''}${value.files.length?`<ul class="files">${value.files.map(file=>`<li>${icon(file.directory?Folder:FileText)}<span><strong>${esc(file.name)}</strong><small>${file.saved?(file.directory?'已保存文件夹':'已保存附件'):'本机文件引用'}</small></span></li>`).join('')}</ul>`:''}${!value.text&&!value.image&&!value.files.length?'<div class="empty">此格式无可用预览，仍可复制原内容</div>':''}${value.truncated?'<p class="preview-note">仅预览前 32,768 字，复制使用完整内容。</p>':''}</div><dl><dt>来源</dt><dd>${esc(value.source)}</dd><dt>时间</dt><dd>${esc(new Date(value.updatedAt).toLocaleString())}</dd><dt>大小</dt><dd>${new Intl.NumberFormat().format(value.bytes)} 字节</dd></dl>`;}
function select(token:string,delay=0){if(busy||searching||!state?.items.some(i=>i.token===token))return;if(selected!==token)q('preview').innerHTML='<div class="empty">正在读取预览…</div>';selected=token;buttons();q('items').querySelectorAll<HTMLElement>('[data-token]').forEach(row=>{const active=row.dataset.token===token;row.classList.toggle('selected',active);row.setAttribute('aria-selected',String(active));});clearTimeout(hover);const request=++previewSerial;hover=setTimeout(()=>{void (async()=>{try{const value=await api.preview(token);if(request===previewSerial&&selected===token)renderPreview(value);}catch(e){if(request===previewSerial&&selected===token)notice(e);}})();},delay);}
async function refresh(){if(busy)return;const request=++querySerial,previous=state?.items.find(i=>i.token===selected)?.id;searching=true;clearPreview();q('items').inert=true;
 let next:TrayState;try{next=await api.state(query);}catch(e){if(request!==querySerial)return;if(query.category&&String(e).includes('分类已不存在')){query.category='';return refresh();}throw e;}
 if(request!==querySerial)return;state=next;searching=false;q('items').inert=false;document.documentElement.dataset.theme=state.dark?'dark':'light';
 q('category').innerHTML='<option value="">全部分类</option><option value="favorites">收藏</option>'+state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');q<HTMLSelectElement>('category').value=query.category;
 q('filters').innerHTML=kinds.map(([kind,label])=>`<button type="button" data-kind="${kind}" aria-pressed="${query.kind===kind}" class="${query.kind===kind?'active':''}">${label}</button>`).join('');
 q('filters').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{query.kind=b.dataset.kind as TrayQuery['kind'];run(refresh);});
 q('count').textContent=state.total>state.items.length?`显示最近 ${state.items.length} / ${state.total} 项 · 搜索可缩小范围`:`${state.total} 项记录`;
 q('items').innerHTML=state.items.length?state.items.map(i=>`<button type="button" role="option" aria-selected="false" class="tray-row" data-token="${i.token}" data-id="${i.id}" draggable="${i.draggable}"><span class="type-icon ${i.kind}">${icon(symbols[i.kind])}</span><span class="row-body"><strong>${esc(i.title)}</strong><span>${esc(i.preview||i.source)}</span><small>${esc(i.source)}</small></span><span class="flags">${i.favorite?icon(Star):''}${i.pinned?icon(Pin):''}</span></button>`).join(''):'<div class="empty"><strong>没有匹配记录</strong><span>尝试其他关键词或分类</span></div>';
 q('items').querySelectorAll<HTMLButtonElement>('[data-token]').forEach(row=>{const token=row.dataset.token!;row.onmouseenter=()=>select(token,180);row.onfocus=()=>select(token);row.onclick=()=>{if(Date.now()>=dragUntil)run(()=>use(token,false));};row.oncontextmenu=e=>{e.preventDefault();run(()=>use(token,true));};row.ondragstart=e=>{e.preventDefault();if(busy||searching||row.draggable===false)return;dragUntil=Date.now()+1500;busy=true;buttons();api.drag(token);};});
 const initial=state.items.find(i=>i.id===previous)||state.items[0];if(initial)select(initial.token);else buttons();q('hint').textContent=state.canPaste?'左键复制 · 右键粘贴 · 图片和文件可拖出':'未找到粘贴目标 · 可先复制，再手动粘贴';
}
async function use(token:string,paste:boolean){if(busy||searching||!token)return;if(paste&&!state?.canPaste)throw new Error('请先切换到目标应用，或使用复制');busy=true;buttons();try{await api.use(token,paste);}catch(e){busy=false;buttons();throw e;}}
q('open-main').innerHTML=icon(ArrowUpRight);q('close').innerHTML=icon(X);q('open-main').onclick=()=>run(()=>api.main());q('close').onclick=()=>run(()=>api.hide());q('copy-selected').onclick=()=>run(()=>use(selected,false));q('paste-selected').onclick=()=>run(()=>use(selected,true));
q<HTMLInputElement>('search').oninput=()=>{query.text=q<HTMLInputElement>('search').value;querySerial++;searching=true;clearPreview();q('items').inert=true;clearTimeout(debounce);debounce=setTimeout(()=>run(refresh),180);};
q<HTMLSelectElement>('category').onchange=()=>{query.category=q<HTMLSelectElement>('category').value;run(refresh);};
document.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Escape'){e.preventDefault();run(()=>api.hide());return;}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();q<HTMLInputElement>('search').focus();q<HTMLInputElement>('search').select();return;}if(busy||searching)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const rows=Array.from(q('items').querySelectorAll<HTMLButtonElement>('[data-token]')),index=rows.findIndex(r=>r.dataset.token===selected),next=Math.max(0,Math.min(rows.length-1,index+(e.key==='ArrowDown'?1:-1)));rows[next]?.focus();rows[next]?.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&selected&&!(document.activeElement instanceof HTMLSelectElement)&&!document.activeElement?.closest('.header-actions,.preview-actions,#filters')){e.preventDefault();run(()=>use(selected,e.ctrlKey));}});
api.onChange(()=>run(refresh));api.onNotice(message=>{busy=false;buttons();notice(message);});
