import {t as tr} from '../shared/i18n';
import './locale';
import './appearance';
document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';
import './unlock.css';
import type {UnlockAPI} from '../shared/vault';
const api=(window as unknown as {unlock:UnlockAPI}).unlock,$=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;let recovery=false,busy=false;
async function work(fn:()=>Promise<void>,label=tr('正在解锁…'),target='unlock-submit-label'){if(busy)return;busy=true;$('feedback').textContent='';document.body.dataset.busyTarget=target;$('unlock-form').setAttribute('aria-busy','true');const status=$(target),previous=status.textContent;status.textContent=label;const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('button')).filter(button=>!button.disabled),inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input')).filter(input=>!input.disabled);buttons.forEach(button=>button.disabled=true);inputs.forEach(input=>input.disabled=true);try{await fn();}catch(e){$('feedback').textContent=String(e instanceof Error?e.message:e).replace(/^Error invoking remote method '[^']+': Error: /,'');}finally{busy=false;delete document.body.dataset.busyTarget;$('unlock-form').removeAttribute('aria-busy');status.textContent=previous;buttons.forEach(button=>button.disabled=false);inputs.forEach(input=>input.disabled=false);if($('feedback').textContent)$('unlock-value').focus();}}
$('unlock-form').onsubmit=event=>{event.preventDefault();void work(async()=>{const password=$<HTMLInputElement>('new-password').value;if(recovery&&(password.length<12||password!==$<HTMLInputElement>('repeat-password').value))throw new Error(tr('新密码至少 12 个字符，且两次填写一致'));const value=$<HTMLInputElement>('unlock-value').value;$<HTMLInputElement>('unlock-value').value='';$<HTMLInputElement>('new-password').value='';$<HTMLInputElement>('repeat-password').value='';await api.unlock(value,recovery?'recovery':'password',recovery?password:undefined);});};
$('use-recovery').onclick=()=>{recovery=!recovery;$('value-label').textContent=recovery?tr('恢复密钥（C7- 开头）'):tr('解锁密码');$('recovery-action').textContent=recovery?tr('返回密码解锁'):tr('使用恢复密钥');$('recovery-hint').textContent=recovery?tr('使用原密码打开历史'):tr('忘记密码时，可用保存的密钥重设密码');$('unlock-submit-label').textContent=recovery?tr('重设密码并解锁'):tr('解锁历史');$('use-recovery').setAttribute('aria-expanded',String(recovery));$('new-password-fields').hidden=!recovery;$<HTMLInputElement>('unlock-value').value='';$('feedback').textContent='';$('unlock-value').focus();};
$('hello').onclick=()=>void work(()=>api.unlock('','hello'),tr('正在验证 Windows Hello…'),'hello-action');$('recover').onclick=()=>void work(()=>api.recover(),tr('正在打开恢复…'),'recover-action');$('quit').onclick=()=>void api.quit();
function unavailable(message:string){$('initial-progress').hidden=true;$('heading').textContent=tr('解锁暂不可用');$('description').textContent=tr('请退出后重新打开 Clip。');$('feedback').textContent=message;}
async function state(){try{const s=await api.state();if(s.error){unavailable(s.error);return;}if(!s.ready){setTimeout(()=>void state(),250);return;}$('initial-progress').hidden=true;$('unlock-options').hidden=false;$('heading').textContent=tr('历史已锁定');$('description').textContent=tr('输入密码以继续使用 Clip。');$('unlock-form').hidden=false;$('hello').hidden=!s.hello||!s.helloAvailable;$<HTMLButtonElement>('recover').disabled=false;$('unlock-value').focus();}catch(e){unavailable(String(e));}}void state();
