import {t as tr,formatBytes,formatDate} from '../shared/i18n';
import type {UpdateState} from '../shared/updates';
import './update.css';
const messages:Record<string,()=>string>={
 UPDATE_RELEASE_INVALID:()=>tr('发布信息无效，请稍后重试'),UPDATE_ASSET_MISSING:()=>tr('此版本尚未提供 Windows x64 安装器'),UPDATE_ASSET_INVALID:()=>tr('安装器缺少有效的大小或 SHA-256 摘要'),UPDATE_URL_INVALID:()=>tr('更新下载地址无效'),UPDATE_NETWORK_ERROR:()=>tr('无法连接 GitHub，请检查网络后重试'),UPDATE_RATE_LIMIT:()=>tr('GitHub 请求次数受限，请稍后重试'),UPDATE_TIMEOUT:()=>tr('更新请求超时，请重试'),UPDATE_LENGTH:()=>tr('下载不完整，请重新下载'),UPDATE_CHECKSUM:()=>tr('安装器校验失败，请重新下载'),UPDATE_SPACE:()=>tr('暂存磁盘空间不足'),UPDATE_BUSY:()=>tr('已有更新操作正在进行'),UPDATE_NOT_READY:()=>tr('请先下载并校验安装器'),UPDATE_PORTABLE:()=>tr('便携版请打开下载位置，手动运行安装器'),UPDATE_UNSAVED:()=>tr('请先保存或关闭捕获与图片编辑，并完成资料操作'),UPDATE_HOST_ERROR:()=>tr('无法启动更新安装程序，请打开下载位置手动安装'),UPDATE_EXIT_TIMEOUT:()=>tr('Clipper 未及时退出，未安装更新'),UPDATE_INSTALLED_VERSION:()=>tr('安装后版本核对失败，请查看安装日志')
};
export const updateError=(code:string)=>messages[code]?.()||(code.startsWith('UPDATE_INSTALL_')?tr('安装未完成，已保留安装日志'):tr('更新失败，请重试或手动安装'));
export function mountUpdates(container:HTMLElement,toast:(value:unknown)=>void,_modal?:(...args:any[])=>void){
  const root=document.createElement('div');root.className='settings-card update-current-card';container.replaceChildren(root);
  const api=window.clipper;let latest:UpdateState|undefined,unsubscribe:(()=>void)|undefined;
  const text=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  function render(value:UpdateState){
    if(!root.isConnected||!value)return;const old=latest;latest=value;
    if(old?.phase==='downloading'&&value.phase==='downloading'&&old.automatic===value.automatic&&old.installed===value.installed&&old.error===value.error&&old.release?.version===value.release?.version&&root.querySelector('progress')){
      root.querySelector<HTMLProgressElement>('progress')!.value=value.downloaded;
      root.querySelector('.update-release progress + p')!.textContent=formatBytes(value.downloaded)+' / '+formatBytes(value.release!.bytes);return;
    }
    const busy=['checking','downloading','installing'].includes(value.phase),release=value.release;
    const status=value.phase==='checking'?tr('正在检查更新…'):value.phase==='current'?tr('已是最新版本'):value.phase==='unpublished'?tr('暂无可用的正式发布'):value.phase==='available'?tr('发现新版本'):value.phase==='downloading'?tr('正在下载安装器…'):value.phase==='ready'?tr('安装器已下载并校验'):value.phase==='installing'?tr('正在退出并安装…'):value.phase==='error'?tr('检查或下载未完成'):tr('尚未检查更新');
    root.innerHTML=`<div class="setting-row"><div><strong>${tr('每日自动检查')}</strong></div><label class="switch"><input id="update-automatic" type="checkbox" role="switch" aria-label="${tr('每日自动检查')}" ${value.automatic?'checked':''} ${value.phase==='installing'?'disabled':''}><span></span></label></div><div class="update-summary"><div><strong>Clipper ${text(value.current)}</strong><p id="update-status" role="status">${status}</p>${value.checkedAt?`<p>${tr('上次检查')} · ${formatDate(value.checkedAt,{dateStyle:'medium',timeStyle:'short'})}</p>`:''}</div><button id="update-check" ${busy?'disabled':''}>${tr('检查更新')}</button></div>${value.previous?`<p class="field-help">${value.previous.success?tr('上次更新已完成'):updateError(value.previous.reason)}</p>`:''}${release?`<div class="update-release"><h3>${tr('新版本')} ${text(release.version)}</h3>${release.notes?`<pre class="update-notes">${text(release.notes)}</pre>`:''}${value.phase==='downloading'?`<progress value="${value.downloaded}" max="${release.bytes}" aria-label="${tr('下载进度')}"></progress><p class="field-help">${formatBytes(value.downloaded)} / ${formatBytes(release.bytes)}</p>`:''}<div class="update-actions">${['available','error'].includes(value.phase)?`<button class="primary" id="update-download">${tr('下载安装器')} · ${formatBytes(release.bytes)}</button>`:''}${value.phase==='ready'?`<button ${value.installed?'class="primary" id="update-install"':'id="update-show"'}>${value.installed?tr('退出并安装'):tr('打开下载位置')}</button>${value.installed?`<button id="update-show">${tr('打开下载位置')}</button>`:''}`:''}${value.phase==='downloading'?`<button id="update-cancel">${tr('取消下载')}</button>`:''}</div>${value.phase==='ready'?`<p class="field-help">${value.installed?tr('安装完成后重新打开 Clipper；安装器会保留历史数据'):tr('便携版请手动运行安装器，安装为当前用户的应用')}</p>`:''}</div>`:''}${value.phase==='checking'?`<button id="update-cancel">${tr('取消检查')}</button>`:''}<p id="update-error" role="alert" class="update-error">${value.error?updateError(value.error):''}</p><p class="field-help">${tr('发布来源')} · Robert-Stackflow/Clipper</p>`;
    root.prepend(root.querySelector('.update-summary')!);
    const action=(id:string,fn:()=>Promise<unknown>)=>{const button=root.querySelector<HTMLButtonElement>('#'+id);if(button)button.onclick=()=>{button.disabled=true;void fn().catch(e=>toast(updateError(String((e as Error).message).split('Error: ').pop()!))).finally(()=>{if(root.isConnected&&latest)render(latest);});};};
    action('update-check',async()=>render(await api.checkUpdate()));action('update-download',async()=>render(await api.downloadUpdate()));action('update-cancel',async()=>render(await api.cancelUpdate()));action('update-show',()=>api.showUpdateDownload());action('update-install',async()=>render(await api.installUpdate()));
    root.querySelector<HTMLInputElement>('#update-automatic')!.onchange=async event=>{const input=event.currentTarget as HTMLInputElement;input.disabled=true;try{render(await api.configureUpdates(input.checked));}catch(e){toast(e);if(latest)render(latest);}};
  }
  void api.updateState().then(render).catch(toast);const listener=api.onUpdate(render);if(typeof listener==='function')unsubscribe=listener;
  return()=>{unsubscribe?.();};
}
