import type {VaultState} from '../shared/vault';
const api=window.clipper,q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
interface Context {modal(title:string,body:string,save:()=>Promise<void>,label?:string):void;toast(text:unknown):void;refresh():Promise<void>}
export async function renderVault(ctx:Context){const state=await api.vaultState(),node=q('history-vault');if(!node)return;
 node.innerHTML=`<div class="tools-section-heading"><h2>历史保护</h2><span class="vault-badge">${state.encrypted?'已加密 · 当前已解锁':'尚未加密'}</span></div><div class="vault-card"><div class="vault-symbol" aria-hidden="true">${state.encrypted?'▣':'□'}</div><div><h3>${state.encrypted?'每次打开，都先确认是你':'为剪贴板历史加一把锁'}</h3><p>${state.encrypted?'历史、图片、模板与设置都保存在加密数据库中。锁定期间停止记录和共享。':'使用密码加密本机数据库。解锁后可正常记录、搜索、粘贴；支持恢复密钥找回。'}</p><div class="data-controls">${state.encrypted?'<button id="vault-lock" class="primary">锁定历史</button><button id="vault-password">更改密码</button>':'<button id="vault-enable" class="primary">启用历史加密</button>'}</div></div></div>${state.encrypted?`<div class="vault-options"><label class="field">离开电脑后自动锁定<select id="vault-idle">${[0,1,5,15,30,60,120].map(n=>`<option value="${n}" ${state.idleMinutes===n?'selected':''}>${n?n+' 分钟':'不按空闲时间锁定'}</option>`).join('')}</select></label><label class="tool-check"><input id="vault-hello" type="checkbox" ${state.hello?'checked':''} ${!state.helloAvailable&&!state.hello?'disabled':''}>Windows Hello 快捷解锁${state.helloAvailable?'':'（当前不可用）'}</label><p class="field-help">锁屏或休眠时自动锁定。Hello 通过后，使用当前 Windows 账户保护的本机凭据解锁；换电脑仍需密码或恢复密钥。</p><button id="vault-save">保存锁定设置</button></div>`:''}${state.plaintextDirectory?`<div class="vault-warning"><strong>加密已完成，原明文副本仍保留</strong><p id="vault-plaintext-path">${esc(state.plaintextDirectory)}</p><p>确认可以解锁后，请清理原副本。以往导出的备份和源文件仍由你管理。</p><button id="vault-cleanup">清理原明文副本</button></div>`:''}`;
 const on=(id:string,fn:()=>unknown)=>q(id)?.addEventListener('click',()=>void Promise.resolve().then(fn).catch(ctx.toast));
 on('vault-enable',()=>enable(ctx));on('vault-lock',()=>api.lockHistory());on('vault-password',()=>changePassword(ctx));on('vault-cleanup',()=>cleanup(ctx,state));
 on('vault-save',async()=>{await api.configureVault(q<HTMLInputElement>('vault-hello').checked,Number(q<HTMLSelectElement>('vault-idle').value));ctx.toast('锁定设置已保存');});
}
function wipe(){const nodes=Array.from(q('dialog').querySelectorAll<HTMLInputElement>('input'));q('dialog').addEventListener('close',()=>nodes.forEach(n=>n.value=''),{once:true});}
async function exclusive(fn:()=>Promise<void>){const d=q<HTMLDialogElement>('dialog'),cancel=(e:Event)=>e.preventDefault(),buttons=[q<HTMLButtonElement>('modal-close'),q<HTMLButtonElement>('modal-cancel')];d.addEventListener('cancel',cancel);buttons.forEach(b=>b.disabled=true);try{await fn();}finally{d.removeEventListener('cancel',cancel);buttons.forEach(b=>b.disabled=false);}}
const fields='<label class="field">新密码<input id="vault-new-password" type="password" autocomplete="new-password" minlength="12" maxlength="1024" required placeholder="至少 12 个字符"></label><label class="field">再次输入<input id="vault-repeat-password" type="password" autocomplete="new-password" maxlength="1024" required></label>';
function password(){const p=q<HTMLInputElement>('vault-new-password').value;if(p.length<12||p!==q<HTMLInputElement>('vault-repeat-password').value)throw new Error('密码至少 12 个字符，且两次填写一致');return p;}
function enable(ctx:Context){let plan:{token:string;recoveryKey:string}|undefined;ctx.modal('启用历史加密',fields+'<p class="field-help">先保存恢复密钥，再生成并校验加密副本。转换时会结束共享、AI 和脚本任务；原明文副本保留，完成后可清理。现有导出文件不会自动加密。</p>',()=>exclusive(async()=>{plan=await api.prepareEncryption(password());}),'继续，生成恢复密钥');wipe();q('dialog').addEventListener('close',()=>{if(plan){const value=plan;plan=undefined;queueMicrotask(()=>confirm(ctx,value));}},{once:true});}
function confirm(ctx:Context,plan:{token:string;recoveryKey:string}){let done=false;ctx.modal('保存你的恢复密钥',`<p>请保存到密码管理器或离线抄存。忘记密码时可用它恢复；密码和密钥都丢失后无法找回历史。</p><pre class="vault-recovery" id="vault-recovery-key">${esc(plan.recoveryKey)}</pre><label class="field">填写已保存的完整恢复密钥<input id="vault-recovery-proof" autocomplete="off" spellcheck="false" maxlength="64" required placeholder="C7-…"></label><p class="field-help">此步骤暂停记录剪贴板，10 分钟后过期并恢复记录。密钥不会自动写入文件。</p>`,()=>exclusive(async()=>{await api.encryptHistory(plan.token,q<HTMLInputElement>('vault-recovery-proof').value);done=true;await ctx.refresh();ctx.toast('历史已加密，请检查并清理原明文副本');}),'开始加密');wipe();q('dialog').addEventListener('close',()=>{q('vault-recovery-key')?.replaceChildren();plan.recoveryKey='';if(!done)void api.cancelEncryption().catch(()=>{});},{once:true});}
function changePassword(ctx:Context){ctx.modal('更改历史密码',fields+'<p class="field-help">恢复密钥保持有效。更改只作用于当前目录；旧资料副本和旧备份仍使用原密码。</p>',()=>exclusive(async()=>{await api.changeHistoryPassword(password());ctx.toast('当前资料的密码已更新');}),'更改密码');wipe();}
function cleanup(ctx:Context,state:VaultState){ctx.modal('清理原明文副本',`<p>将删除下列原目录中的 history.sqlite 及其日志文件：</p><pre class="external-preview">${esc(state.plaintextDirectory)}</pre><p class="field-help">清理前会再次校验加密数据库和原副本。其他文件、备份保持原样。文件删除不等同于磁盘安全擦除。</p>`,()=>exclusive(async()=>{await api.cleanupPlaintext();await ctx.refresh();ctx.toast('原明文数据库与日志已清理');}),'校验并清理');}
